import type { TranslationLanguage } from "./locale";

export const growthFeatureTranslations: Record<TranslationLanguage, Record<string, string>> = {
  en: {
    "nav.outletMatch": "Outlet Match",
    "home.featured.outletMatch.kicker": "Personalized discovery", "home.featured.outletMatch.title": "Find the outlet that fits your brands", "home.featured.outletMatch.subtitle": "Choose up to eight brands, rank matching outlets and compare your shortlist.", "home.featured.outletMatch.cta": "Start Outlet Match",
    "brandWishlist.matchTitle": "Match all your saved brands", "brandWishlist.matchText": "Rank outlets by how many of your favorite brands they carry.", "brandWishlist.matchCta": "Open Outlet Match",
    "outletMatch.kicker": "Your brands, one destination", "outletMatch.title": "Outlet Match", "outletMatch.subtitle": "Choose the brands you want to shop. We rank active outlets by real directory matches; you can compare and share the result.",
    "outletMatch.chooseBrands": "Choose brands", "outletMatch.chooseBrandsBody": "Select up to eight brands. Your saved brands are selected automatically when available.", "outletMatch.searchPlaceholder": "Search brands", "outletMatch.limitTitle": "Selection limit", "outletMatch.brandLimitBody": "You can compare up to eight brands at once.", "outletMatch.compareLimitBody": "You can compare up to three outlets at once.",
    "outletMatch.useLocation": "Rank by my location", "outletMatch.locating": "Finding location…", "outletMatch.locationActive": "Location ranking on", "outletMatch.locationDeniedTitle": "Location access is off", "outletMatch.locationDeniedBody": "Allow foreground location in device settings and try again.", "outletMatch.locationErrorTitle": "Location unavailable", "outletMatch.locationErrorBody": "Your location could not be determined. Brand matching still works without it.",
    "outletMatch.share": "Share result", "outletMatch.shareTitle": "My Outlet Match", "outletMatch.resultsTitle": "Best matches", "outletMatch.resultCount": "{count} matching outlets found", "outletMatch.selectPrompt": "Choose at least one brand to see matches.", "outletMatch.matchSummary": "{matched} of {total} selected brands", "outletMatch.distance": "{distance} km away", "outletMatch.viewOutlet": "Outlet details", "outletMatch.addCompare": "Compare", "outletMatch.removeCompare": "Remove", "outletMatch.planTrip": "Plan trip", "outletMatch.compareTitle": "Side-by-side comparison", "outletMatch.compareBody": "A check shows that the brand is listed in the current outlet directory.",
    "notifications.favoriteBrandCampaignsCategory": "Favorite brand campaigns", "notifications.favoriteBrandCampaignsCategoryDesc": "Verified offers for brands saved in your wishlist.", "notifications.savedCampaignRemindersCategory": "Saved campaign reminders", "notifications.savedCampaignRemindersCategoryDesc": "A device reminder before a campaign you saved ends.",
    "campaign.save": "Save campaign", "campaign.saved": "Campaign saved", "campaign.saving": "Saving…", "campaign.saveSignInMessage": "Sign in to save this campaign and keep it synced.", "campaign.reminderActive": "A reminder will be scheduled on this device before the campaign ends.", "campaign.reminderInactive": "The campaign is saved. Turn on saved-campaign reminders to receive an end-date alert.", "campaign.openNotificationSettings": "Open notification settings", "campaign.reminderTitle": "Saved campaign ending soon", "campaign.reminderBody": "{brand} at {outlet} ends {date}.",
    "favorites.savedCampaignsTitle": "Saved campaigns", "favorites.savedCampaignsSubtitle": "Active offers and events you want to revisit.", "favorites.savedCampaignLabel": "Saved campaign", "favorites.savedCampaignEnds": "Ends {date}", "favorites.savedCampaignsUnavailable": "Your saved campaigns have ended or are no longer available.",
    "travelBasket.smartContextApplied": "Destination and available dates will be added to supported partner searches.",
  },
  tr: {
    "nav.outletMatch": "Outlet Eşleştir", "home.featured.outletMatch.kicker": "Kişisel keşif", "home.featured.outletMatch.title": "Markalarına en uygun outlet’i bul", "home.featured.outletMatch.subtitle": "En fazla sekiz marka seç, eşleşen outletleri sırala ve kısa listeni karşılaştır.", "home.featured.outletMatch.cta": "Outlet Eşleştir’i aç",
    "brandWishlist.matchTitle": "Kayıtlı markalarını birlikte eşleştir", "brandWishlist.matchText": "Outletleri favori markalarının kaçına sahip olduklarına göre sırala.", "brandWishlist.matchCta": "Outlet Eşleştir’i aç",
    "outletMatch.kicker": "Markaların, tek destinasyon", "outletMatch.title": "Outlet Eşleştir", "outletMatch.subtitle": "Alışveriş yapmak istediğin markaları seç. Aktif outletleri gerçek mağaza eşleşmelerine göre sıralayalım; sonucu karşılaştır ve paylaş.", "outletMatch.chooseBrands": "Markaları seç", "outletMatch.chooseBrandsBody": "En fazla sekiz marka seç. Kayıtlı markaların varsa otomatik olarak seçilir.", "outletMatch.searchPlaceholder": "Marka ara", "outletMatch.limitTitle": "Seçim sınırı", "outletMatch.brandLimitBody": "Aynı anda en fazla sekiz markayı eşleştirebilirsin.", "outletMatch.compareLimitBody": "Aynı anda en fazla üç outlet karşılaştırabilirsin.",
    "outletMatch.useLocation": "Konumuma göre sırala", "outletMatch.locating": "Konum bulunuyor…", "outletMatch.locationActive": "Konum sıralaması açık", "outletMatch.locationDeniedTitle": "Konum erişimi kapalı", "outletMatch.locationDeniedBody": "Cihaz ayarlarından ön planda konum izni verip tekrar dene.", "outletMatch.locationErrorTitle": "Konum alınamadı", "outletMatch.locationErrorBody": "Konumun belirlenemedi. Marka eşleştirme konum olmadan da çalışır.",
    "outletMatch.share": "Sonucu paylaş", "outletMatch.shareTitle": "Outlet Eşleştirmem", "outletMatch.resultsTitle": "En iyi eşleşmeler", "outletMatch.resultCount": "{count} eşleşen outlet bulundu", "outletMatch.selectPrompt": "Eşleşmeleri görmek için en az bir marka seç.", "outletMatch.matchSummary": "Seçilen {total} markanın {matched} tanesi", "outletMatch.distance": "{distance} km uzakta", "outletMatch.viewOutlet": "Outlet detayı", "outletMatch.addCompare": "Karşılaştır", "outletMatch.removeCompare": "Çıkar", "outletMatch.planTrip": "Seyahati planla", "outletMatch.compareTitle": "Yan yana karşılaştırma", "outletMatch.compareBody": "Onay işareti, markanın güncel outlet dizininde listelendiğini gösterir.",
    "notifications.favoriteBrandCampaignsCategory": "Favori marka kampanyaları", "notifications.favoriteBrandCampaignsCategoryDesc": "İstek listene kaydettiğin markaların doğrulanmış kampanyaları.", "notifications.savedCampaignRemindersCategory": "Kayıtlı kampanya hatırlatmaları", "notifications.savedCampaignRemindersCategoryDesc": "Kaydettiğin kampanya sona ermeden önce cihaz hatırlatması.",
    "campaign.save": "Kampanyayı kaydet", "campaign.saved": "Kampanya kaydedildi", "campaign.saving": "Kaydediliyor…", "campaign.saveSignInMessage": "Kampanyayı kaydetmek ve hesabınla eşitlemek için giriş yap.", "campaign.reminderActive": "Kampanya bitmeden önce bu cihazda bir hatırlatma planlanacak.", "campaign.reminderInactive": "Kampanya kaydedildi. Bitiş uyarısı almak için kayıtlı kampanya hatırlatmalarını aç.", "campaign.openNotificationSettings": "Bildirim ayarlarını aç", "campaign.reminderTitle": "Kayıtlı kampanya yakında bitiyor", "campaign.reminderBody": "{outlet} içindeki {brand} kampanyası {date} tarihinde bitiyor.",
    "favorites.savedCampaignsTitle": "Kaydedilen kampanyalar", "favorites.savedCampaignsSubtitle": "Yeniden incelemek istediğin aktif kampanya ve etkinlikler.", "favorites.savedCampaignLabel": "Kayıtlı kampanya", "favorites.savedCampaignEnds": "Bitiş {date}", "favorites.savedCampaignsUnavailable": "Kaydettiğin kampanyalar sona ermiş veya artık yayında değil.",
    "travelBasket.smartContextApplied": "Destinasyon ve mevcut tarihler desteklenen partner aramalarına eklenecek.",
  },
  es: {
    "nav.outletMatch": "Outlet Match", "home.featured.outletMatch.kicker": "Descubrimiento personal", "home.featured.outletMatch.title": "Encuentra el outlet para tus marcas", "home.featured.outletMatch.subtitle": "Elige hasta ocho marcas, ordena los outlets coincidentes y compara tu lista.", "home.featured.outletMatch.cta": "Iniciar Outlet Match", "brandWishlist.matchTitle": "Combina tus marcas guardadas", "brandWishlist.matchText": "Ordena outlets por cuántas marcas favoritas ofrecen.", "brandWishlist.matchCta": "Abrir Outlet Match",
    "outletMatch.kicker": "Tus marcas, un destino", "outletMatch.title": "Outlet Match", "outletMatch.subtitle": "Elige tus marcas. Ordenamos outlets activos por coincidencias reales para comparar y compartir.", "outletMatch.chooseBrands": "Elige marcas", "outletMatch.chooseBrandsBody": "Selecciona hasta ocho marcas. Usaremos tus favoritas cuando existan.", "outletMatch.searchPlaceholder": "Buscar marcas", "outletMatch.limitTitle": "Límite de selección", "outletMatch.brandLimitBody": "Puedes combinar hasta ocho marcas.", "outletMatch.compareLimitBody": "Puedes comparar hasta tres outlets.", "outletMatch.useLocation": "Ordenar por ubicación", "outletMatch.locating": "Buscando ubicación…", "outletMatch.locationActive": "Ubicación activa", "outletMatch.locationDeniedTitle": "Ubicación desactivada", "outletMatch.locationDeniedBody": "Permite la ubicación en primer plano e inténtalo de nuevo.", "outletMatch.locationErrorTitle": "Ubicación no disponible", "outletMatch.locationErrorBody": "No se pudo obtener tu ubicación. La combinación de marcas sigue disponible.", "outletMatch.share": "Compartir resultado", "outletMatch.shareTitle": "Mi Outlet Match", "outletMatch.resultsTitle": "Mejores coincidencias", "outletMatch.resultCount": "{count} outlets coincidentes", "outletMatch.selectPrompt": "Elige al menos una marca.", "outletMatch.matchSummary": "{matched} de {total} marcas", "outletMatch.distance": "A {distance} km", "outletMatch.viewOutlet": "Ver outlet", "outletMatch.addCompare": "Comparar", "outletMatch.removeCompare": "Quitar", "outletMatch.planTrip": "Planificar viaje", "outletMatch.compareTitle": "Comparación directa", "outletMatch.compareBody": "La marca está listada cuando aparece una marca de verificación.",
    "notifications.favoriteBrandCampaignsCategory": "Campañas de marcas favoritas", "notifications.favoriteBrandCampaignsCategoryDesc": "Ofertas verificadas de las marcas de tu lista.", "notifications.savedCampaignRemindersCategory": "Recordatorios guardados", "notifications.savedCampaignRemindersCategoryDesc": "Aviso en el dispositivo antes de que termine una campaña guardada.", "campaign.save": "Guardar campaña", "campaign.saved": "Campaña guardada", "campaign.saving": "Guardando…", "campaign.saveSignInMessage": "Inicia sesión para guardar y sincronizar la campaña.", "campaign.reminderActive": "Se programará un aviso en este dispositivo antes del final.", "campaign.reminderInactive": "La campaña está guardada. Activa sus recordatorios para recibir un aviso.", "campaign.openNotificationSettings": "Abrir notificaciones", "campaign.reminderTitle": "La campaña guardada termina pronto", "campaign.reminderBody": "{brand} en {outlet} termina el {date}.", "favorites.savedCampaignsTitle": "Campañas guardadas", "favorites.savedCampaignsSubtitle": "Ofertas y eventos activos para consultar de nuevo.", "favorites.savedCampaignLabel": "Campaña guardada", "favorites.savedCampaignEnds": "Termina {date}", "favorites.savedCampaignsUnavailable": "Tus campañas guardadas terminaron o ya no están disponibles.", "travelBasket.smartContextApplied": "El destino y las fechas disponibles se añadirán a las búsquedas compatibles.",
  },
  fr: {
    "nav.outletMatch": "Outlet Match", "home.featured.outletMatch.kicker": "Découverte personnalisée", "home.featured.outletMatch.title": "Trouvez l’outlet de vos marques", "home.featured.outletMatch.subtitle": "Choisissez jusqu’à huit marques, classez les outlets et comparez votre sélection.", "home.featured.outletMatch.cta": "Lancer Outlet Match", "brandWishlist.matchTitle": "Associez vos marques enregistrées", "brandWishlist.matchText": "Classez les outlets selon le nombre de marques favorites présentes.", "brandWishlist.matchCta": "Ouvrir Outlet Match",
    "outletMatch.kicker": "Vos marques, une destination", "outletMatch.title": "Outlet Match", "outletMatch.subtitle": "Choisissez vos marques. Nous classons les outlets actifs selon les correspondances réelles, à comparer et partager.", "outletMatch.chooseBrands": "Choisir les marques", "outletMatch.chooseBrandsBody": "Sélectionnez jusqu’à huit marques. Vos favorites sont présélectionnées.", "outletMatch.searchPlaceholder": "Rechercher une marque", "outletMatch.limitTitle": "Limite de sélection", "outletMatch.brandLimitBody": "Vous pouvez associer huit marques maximum.", "outletMatch.compareLimitBody": "Vous pouvez comparer trois outlets maximum.", "outletMatch.useLocation": "Classer selon ma position", "outletMatch.locating": "Localisation…", "outletMatch.locationActive": "Classement local actif", "outletMatch.locationDeniedTitle": "Localisation désactivée", "outletMatch.locationDeniedBody": "Autorisez la position au premier plan puis réessayez.", "outletMatch.locationErrorTitle": "Position indisponible", "outletMatch.locationErrorBody": "Votre position est indisponible. La correspondance des marques reste accessible.", "outletMatch.share": "Partager le résultat", "outletMatch.shareTitle": "Mon Outlet Match", "outletMatch.resultsTitle": "Meilleures correspondances", "outletMatch.resultCount": "{count} outlets correspondants", "outletMatch.selectPrompt": "Choisissez au moins une marque.", "outletMatch.matchSummary": "{matched} marques sur {total}", "outletMatch.distance": "À {distance} km", "outletMatch.viewOutlet": "Voir l’outlet", "outletMatch.addCompare": "Comparer", "outletMatch.removeCompare": "Retirer", "outletMatch.planTrip": "Planifier", "outletMatch.compareTitle": "Comparaison côte à côte", "outletMatch.compareBody": "Une coche indique que la marque figure dans l’annuaire actuel.",
    "notifications.favoriteBrandCampaignsCategory": "Campagnes des marques favorites", "notifications.favoriteBrandCampaignsCategoryDesc": "Offres vérifiées des marques enregistrées.", "notifications.savedCampaignRemindersCategory": "Rappels de campagnes enregistrées", "notifications.savedCampaignRemindersCategoryDesc": "Un rappel sur l’appareil avant la fin d’une campagne enregistrée.", "campaign.save": "Enregistrer la campagne", "campaign.saved": "Campagne enregistrée", "campaign.saving": "Enregistrement…", "campaign.saveSignInMessage": "Connectez-vous pour enregistrer et synchroniser cette campagne.", "campaign.reminderActive": "Un rappel sera programmé sur cet appareil avant la fin.", "campaign.reminderInactive": "Campagne enregistrée. Activez les rappels pour recevoir une alerte.", "campaign.openNotificationSettings": "Ouvrir les notifications", "campaign.reminderTitle": "La campagne enregistrée se termine bientôt", "campaign.reminderBody": "{brand} chez {outlet} se termine le {date}.", "favorites.savedCampaignsTitle": "Campagnes enregistrées", "favorites.savedCampaignsSubtitle": "Offres et événements actifs à retrouver.", "favorites.savedCampaignLabel": "Campagne enregistrée", "favorites.savedCampaignEnds": "Fin {date}", "favorites.savedCampaignsUnavailable": "Vos campagnes enregistrées sont terminées ou indisponibles.", "travelBasket.smartContextApplied": "La destination et les dates disponibles seront ajoutées aux recherches compatibles.",
  },
  de: {
    "nav.outletMatch": "Outlet Match", "home.featured.outletMatch.kicker": "Personalisierte Suche", "home.featured.outletMatch.title": "Das passende Outlet für Ihre Marken", "home.featured.outletMatch.subtitle": "Bis zu acht Marken wählen, passende Outlets sortieren und vergleichen.", "home.featured.outletMatch.cta": "Outlet Match starten", "brandWishlist.matchTitle": "Gespeicherte Marken gemeinsam abgleichen", "brandWishlist.matchText": "Outlets nach der Zahl Ihrer Lieblingsmarken sortieren.", "brandWishlist.matchCta": "Outlet Match öffnen",
    "outletMatch.kicker": "Ihre Marken, ein Ziel", "outletMatch.title": "Outlet Match", "outletMatch.subtitle": "Wählen Sie Marken. Aktive Outlets werden nach echten Verzeichnis-Treffern sortiert, verglichen und geteilt.", "outletMatch.chooseBrands": "Marken wählen", "outletMatch.chooseBrandsBody": "Wählen Sie bis zu acht Marken. Gespeicherte Marken werden vorausgewählt.", "outletMatch.searchPlaceholder": "Marken suchen", "outletMatch.limitTitle": "Auswahllimit", "outletMatch.brandLimitBody": "Bis zu acht Marken sind möglich.", "outletMatch.compareLimitBody": "Bis zu drei Outlets sind vergleichbar.", "outletMatch.useLocation": "Nach Standort sortieren", "outletMatch.locating": "Standort wird ermittelt…", "outletMatch.locationActive": "Standortsortierung aktiv", "outletMatch.locationDeniedTitle": "Standortzugriff deaktiviert", "outletMatch.locationDeniedBody": "Erlauben Sie den Vordergrundstandort und versuchen Sie es erneut.", "outletMatch.locationErrorTitle": "Standort nicht verfügbar", "outletMatch.locationErrorBody": "Der Standort ist nicht verfügbar. Der Markenabgleich funktioniert weiterhin.", "outletMatch.share": "Ergebnis teilen", "outletMatch.shareTitle": "Mein Outlet Match", "outletMatch.resultsTitle": "Beste Treffer", "outletMatch.resultCount": "{count} passende Outlets", "outletMatch.selectPrompt": "Wählen Sie mindestens eine Marke.", "outletMatch.matchSummary": "{matched} von {total} Marken", "outletMatch.distance": "{distance} km entfernt", "outletMatch.viewOutlet": "Outlet ansehen", "outletMatch.addCompare": "Vergleichen", "outletMatch.removeCompare": "Entfernen", "outletMatch.planTrip": "Reise planen", "outletMatch.compareTitle": "Direkter Vergleich", "outletMatch.compareBody": "Ein Häkchen zeigt die Marke im aktuellen Verzeichnis.",
    "notifications.favoriteBrandCampaignsCategory": "Kampagnen von Lieblingsmarken", "notifications.favoriteBrandCampaignsCategoryDesc": "Verifizierte Angebote gespeicherter Marken.", "notifications.savedCampaignRemindersCategory": "Erinnerungen an gespeicherte Kampagnen", "notifications.savedCampaignRemindersCategoryDesc": "Geräteerinnerung vor dem Ende einer gespeicherten Kampagne.", "campaign.save": "Kampagne speichern", "campaign.saved": "Kampagne gespeichert", "campaign.saving": "Wird gespeichert…", "campaign.saveSignInMessage": "Melden Sie sich an, um die Kampagne zu speichern und zu synchronisieren.", "campaign.reminderActive": "Vor dem Ende wird auf diesem Gerät eine Erinnerung geplant.", "campaign.reminderInactive": "Kampagne gespeichert. Aktivieren Sie Erinnerungen für einen Hinweis.", "campaign.openNotificationSettings": "Benachrichtigungen öffnen", "campaign.reminderTitle": "Gespeicherte Kampagne endet bald", "campaign.reminderBody": "{brand} bei {outlet} endet am {date}.", "favorites.savedCampaignsTitle": "Gespeicherte Kampagnen", "favorites.savedCampaignsSubtitle": "Aktive Angebote und Events zum Wiederfinden.", "favorites.savedCampaignLabel": "Gespeicherte Kampagne", "favorites.savedCampaignEnds": "Endet {date}", "favorites.savedCampaignsUnavailable": "Ihre gespeicherten Kampagnen sind beendet oder nicht mehr verfügbar.", "travelBasket.smartContextApplied": "Ziel und verfügbare Daten werden in unterstützte Partnersuchen übernommen.",
  },
  ar: {
    "nav.outletMatch": "مطابقة الأوتلت", "home.featured.outletMatch.kicker": "اكتشاف شخصي", "home.featured.outletMatch.title": "اعثر على الأوتلت المناسب لعلاماتك", "home.featured.outletMatch.subtitle": "اختر حتى ثماني علامات ورتب مراكز الأوتلت وقارن قائمتك.", "home.featured.outletMatch.cta": "بدء المطابقة", "brandWishlist.matchTitle": "طابق علاماتك المحفوظة", "brandWishlist.matchText": "رتب مراكز الأوتلت حسب عدد علاماتك المفضلة.", "brandWishlist.matchCta": "فتح المطابقة",
    "outletMatch.kicker": "علاماتك في وجهة واحدة", "outletMatch.title": "مطابقة الأوتلت", "outletMatch.subtitle": "اختر العلامات وسنرتب مراكز الأوتلت النشطة وفق دليل المتاجر الفعلي للمقارنة والمشاركة.", "outletMatch.chooseBrands": "اختر العلامات", "outletMatch.chooseBrandsBody": "اختر حتى ثماني علامات، وتُحدد المفضلة تلقائياً.", "outletMatch.searchPlaceholder": "البحث عن علامة", "outletMatch.limitTitle": "حد الاختيار", "outletMatch.brandLimitBody": "يمكن اختيار ثماني علامات كحد أقصى.", "outletMatch.compareLimitBody": "يمكن مقارنة ثلاثة مراكز كحد أقصى.", "outletMatch.useLocation": "الترتيب حسب موقعي", "outletMatch.locating": "جارٍ تحديد الموقع…", "outletMatch.locationActive": "ترتيب الموقع مفعل", "outletMatch.locationDeniedTitle": "الموقع متوقف", "outletMatch.locationDeniedBody": "اسمح بموقع المقدمة وحاول مجدداً.", "outletMatch.locationErrorTitle": "الموقع غير متاح", "outletMatch.locationErrorBody": "تعذر تحديد الموقع، لكن مطابقة العلامات ما زالت تعمل.", "outletMatch.share": "مشاركة النتيجة", "outletMatch.shareTitle": "مطابقة الأوتلت الخاصة بي", "outletMatch.resultsTitle": "أفضل التطابقات", "outletMatch.resultCount": "تم العثور على {count} مركز", "outletMatch.selectPrompt": "اختر علامة واحدة على الأقل.", "outletMatch.matchSummary": "{matched} من أصل {total} علامات", "outletMatch.distance": "يبعد {distance} كم", "outletMatch.viewOutlet": "تفاصيل الأوتلت", "outletMatch.addCompare": "مقارنة", "outletMatch.removeCompare": "إزالة", "outletMatch.planTrip": "تخطيط الرحلة", "outletMatch.compareTitle": "مقارنة مباشرة", "outletMatch.compareBody": "تعني علامة الصح أن العلامة مدرجة في الدليل الحالي.",
    "notifications.favoriteBrandCampaignsCategory": "حملات العلامات المفضلة", "notifications.favoriteBrandCampaignsCategoryDesc": "عروض موثقة للعلامات المحفوظة.", "notifications.savedCampaignRemindersCategory": "تذكيرات الحملات المحفوظة", "notifications.savedCampaignRemindersCategoryDesc": "تذكير على الجهاز قبل انتهاء الحملة المحفوظة.", "campaign.save": "حفظ الحملة", "campaign.saved": "تم حفظ الحملة", "campaign.saving": "جارٍ الحفظ…", "campaign.saveSignInMessage": "سجل الدخول لحفظ الحملة ومزامنتها.", "campaign.reminderActive": "سيتم جدولة تذكير على هذا الجهاز قبل انتهاء الحملة.", "campaign.reminderInactive": "تم حفظ الحملة. فعّل التذكيرات لتلقي تنبيه.", "campaign.openNotificationSettings": "فتح إعدادات الإشعارات", "campaign.reminderTitle": "الحملة المحفوظة تنتهي قريباً", "campaign.reminderBody": "عرض {brand} في {outlet} ينتهي في {date}.", "favorites.savedCampaignsTitle": "الحملات المحفوظة", "favorites.savedCampaignsSubtitle": "العروض والفعاليات النشطة للعودة إليها.", "favorites.savedCampaignLabel": "حملة محفوظة", "favorites.savedCampaignEnds": "تنتهي في {date}", "favorites.savedCampaignsUnavailable": "انتهت حملاتك المحفوظة أو لم تعد متاحة.", "travelBasket.smartContextApplied": "ستُضاف الوجهة والتواريخ المتاحة إلى عمليات البحث المدعومة.",
  },
  ru: {
    "nav.outletMatch": "Подбор аутлета", "home.featured.outletMatch.kicker": "Персональный поиск", "home.featured.outletMatch.title": "Найдите аутлет для своих брендов", "home.featured.outletMatch.subtitle": "Выберите до восьми брендов, отсортируйте аутлеты и сравните список.", "home.featured.outletMatch.cta": "Начать подбор", "brandWishlist.matchTitle": "Сопоставьте сохранённые бренды", "brandWishlist.matchText": "Сортируйте аутлеты по числу любимых брендов.", "brandWishlist.matchCta": "Открыть подбор",
    "outletMatch.kicker": "Ваши бренды — одна поездка", "outletMatch.title": "Подбор аутлета", "outletMatch.subtitle": "Выберите бренды. Мы ранжируем активные аутлеты по реальному каталогу для сравнения и отправки.", "outletMatch.chooseBrands": "Выберите бренды", "outletMatch.chooseBrandsBody": "До восьми брендов. Сохранённые бренды выбираются автоматически.", "outletMatch.searchPlaceholder": "Поиск брендов", "outletMatch.limitTitle": "Лимит выбора", "outletMatch.brandLimitBody": "Можно выбрать до восьми брендов.", "outletMatch.compareLimitBody": "Можно сравнить до трёх аутлетов.", "outletMatch.useLocation": "Сортировать по геопозиции", "outletMatch.locating": "Определяем позицию…", "outletMatch.locationActive": "Геосортировка включена", "outletMatch.locationDeniedTitle": "Геопозиция выключена", "outletMatch.locationDeniedBody": "Разрешите геопозицию при использовании и повторите.", "outletMatch.locationErrorTitle": "Позиция недоступна", "outletMatch.locationErrorBody": "Не удалось определить позицию. Подбор брендов продолжает работать.", "outletMatch.share": "Поделиться", "outletMatch.shareTitle": "Мой подбор аутлета", "outletMatch.resultsTitle": "Лучшие совпадения", "outletMatch.resultCount": "Найдено аутлетов: {count}", "outletMatch.selectPrompt": "Выберите хотя бы один бренд.", "outletMatch.matchSummary": "{matched} из {total} брендов", "outletMatch.distance": "{distance} км", "outletMatch.viewOutlet": "Открыть аутлет", "outletMatch.addCompare": "Сравнить", "outletMatch.removeCompare": "Убрать", "outletMatch.planTrip": "Спланировать", "outletMatch.compareTitle": "Прямое сравнение", "outletMatch.compareBody": "Галочка означает, что бренд есть в текущем каталоге.",
    "notifications.favoriteBrandCampaignsCategory": "Акции любимых брендов", "notifications.favoriteBrandCampaignsCategoryDesc": "Проверенные предложения сохранённых брендов.", "notifications.savedCampaignRemindersCategory": "Напоминания о сохранённых акциях", "notifications.savedCampaignRemindersCategoryDesc": "Напоминание на устройстве перед окончанием акции.", "campaign.save": "Сохранить акцию", "campaign.saved": "Акция сохранена", "campaign.saving": "Сохраняем…", "campaign.saveSignInMessage": "Войдите, чтобы сохранить и синхронизировать акцию.", "campaign.reminderActive": "На этом устройстве будет создано напоминание до окончания.", "campaign.reminderInactive": "Акция сохранена. Включите напоминания, чтобы получить уведомление.", "campaign.openNotificationSettings": "Открыть уведомления", "campaign.reminderTitle": "Сохранённая акция скоро закончится", "campaign.reminderBody": "{brand} в {outlet}: окончание {date}.", "favorites.savedCampaignsTitle": "Сохранённые акции", "favorites.savedCampaignsSubtitle": "Активные предложения и события, к которым можно вернуться.", "favorites.savedCampaignLabel": "Сохранённая акция", "favorites.savedCampaignEnds": "До {date}", "favorites.savedCampaignsUnavailable": "Сохранённые акции завершились или больше недоступны.", "travelBasket.smartContextApplied": "Направление и доступные даты будут добавлены в поддерживаемые поиски.",
  },
  zh: {
    "nav.outletMatch": "奥莱匹配", "home.featured.outletMatch.kicker": "个性化发现", "home.featured.outletMatch.title": "找到适合你品牌的奥莱", "home.featured.outletMatch.subtitle": "最多选择八个品牌，排序匹配奥莱并比较候选。", "home.featured.outletMatch.cta": "开始奥莱匹配", "brandWishlist.matchTitle": "匹配已收藏品牌", "brandWishlist.matchText": "按收藏品牌覆盖数量排序奥莱。", "brandWishlist.matchCta": "打开奥莱匹配",
    "outletMatch.kicker": "你的品牌，一个目的地", "outletMatch.title": "奥莱匹配", "outletMatch.subtitle": "选择想逛的品牌。我们按真实目录匹配排序活跃奥莱，支持比较和分享。", "outletMatch.chooseBrands": "选择品牌", "outletMatch.chooseBrandsBody": "最多选择八个品牌；已有收藏时会自动选择。", "outletMatch.searchPlaceholder": "搜索品牌", "outletMatch.limitTitle": "选择上限", "outletMatch.brandLimitBody": "最多同时匹配八个品牌。", "outletMatch.compareLimitBody": "最多同时比较三个奥莱。", "outletMatch.useLocation": "按我的位置排序", "outletMatch.locating": "正在定位…", "outletMatch.locationActive": "位置排序已开启", "outletMatch.locationDeniedTitle": "位置权限已关闭", "outletMatch.locationDeniedBody": "请允许前台位置权限后重试。", "outletMatch.locationErrorTitle": "无法获取位置", "outletMatch.locationErrorBody": "无法确定位置，但品牌匹配仍可使用。", "outletMatch.share": "分享结果", "outletMatch.shareTitle": "我的奥莱匹配", "outletMatch.resultsTitle": "最佳匹配", "outletMatch.resultCount": "找到 {count} 个匹配奥莱", "outletMatch.selectPrompt": "请至少选择一个品牌。", "outletMatch.matchSummary": "匹配 {matched}/{total} 个品牌", "outletMatch.distance": "距离 {distance} 公里", "outletMatch.viewOutlet": "查看奥莱", "outletMatch.addCompare": "比较", "outletMatch.removeCompare": "移除", "outletMatch.planTrip": "规划行程", "outletMatch.compareTitle": "并排比较", "outletMatch.compareBody": "对勾表示该品牌已列入当前奥莱目录。",
    "notifications.favoriteBrandCampaignsCategory": "收藏品牌活动", "notifications.favoriteBrandCampaignsCategoryDesc": "已收藏品牌的官方验证优惠。", "notifications.savedCampaignRemindersCategory": "已收藏活动提醒", "notifications.savedCampaignRemindersCategoryDesc": "在已收藏活动结束前发送设备提醒。", "campaign.save": "收藏活动", "campaign.saved": "活动已收藏", "campaign.saving": "正在收藏…", "campaign.saveSignInMessage": "登录后可收藏并同步此活动。", "campaign.reminderActive": "本设备将在活动结束前安排提醒。", "campaign.reminderInactive": "活动已收藏。开启收藏活动提醒即可接收通知。", "campaign.openNotificationSettings": "打开通知设置", "campaign.reminderTitle": "收藏的活动即将结束", "campaign.reminderBody": "{outlet} 的 {brand} 活动将于 {date} 结束。", "favorites.savedCampaignsTitle": "已收藏活动", "favorites.savedCampaignsSubtitle": "可再次查看的有效优惠和活动。", "favorites.savedCampaignLabel": "已收藏活动", "favorites.savedCampaignEnds": "结束于 {date}", "favorites.savedCampaignsUnavailable": "已收藏活动已结束或不再可用。", "travelBasket.smartContextApplied": "目的地和可用日期将加入受支持的合作伙伴搜索。",
  },
};
