export const franceTransportation = [
  {
    "transportationId": "la-vallee-shuttle-paris",
    "outletId": "la-vallee-village",
    "transportType": "bus",
    "title": "Shopping Express® Shuttle from Paris",
    "duration": "≈40-50 min (estimated)",
    "cost": "Confirm with provider",
    "tip": "Official Shopping Express® shuttle runs direct from Hotel Pullman Paris Bercy at 09:00 with 14:30 or 18:45 returns; advance online reservation is required and tickets are not sold on board.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "la-vallee-train",
    "outletId": "la-vallee-village",
    "transportType": "train",
    "title": "RER A / TGV Train Access",
    "duration": "≈40-50 min (estimated)",
    "cost": "≈€5-8 (estimated)",
    "tip": "Take RER A from Paris toward Marne-la-Vallée and alight at Val d’Europe; TGV services use Marne-la-Vallée-Chessy-Parcs Disney®. Check official rail timetables before travelling.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "la-vallee-car-parking",
    "outletId": "la-vallee-village",
    "transportType": "car",
    "title": "Car / Parking",
    "duration": "40 min",
    "cost": "Free parking",
    "tip": "La Vallée Village states it is just 40 minutes from Paris by car and offers ample free parking.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "la-vallee-disney-shuttle",
    "outletId": "la-vallee-village",
    "transportType": "bus",
    "title": "Disney® Resort Hotels Shuttle",
    "duration": "≈10 min (estimated)",
    "cost": "€6 adult return / €3 child return",
    "tip": "Regular shuttle bus from Disney® Resort hotels to the Village; book through your hotel concierge or the La Vallée Village Welcome Center.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "la-vallee-airport",
    "outletId": "la-vallee-village",
    "transportType": "airport",
    "title": "Paris Charles de Gaulle / Orly airport access",
    "duration": "≈10-20 min by TGV from CDG to Marne-la-Vallée-Chessy + local transfer; ≈35-50 min by car (estimated)",
    "cost": "Check official TGV, airport shuttle, taxi or transfer fare",
    "tip": "Use official Paris airport ground transport or TGV to Marne-la-Vallée-Chessy/Val d’Europe connections before the Village transfer; no dedicated airport-to-village shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "troyes-car-parking",
    "outletId": "designer-outlet-troyes",
    "transportType": "car",
    "title": "Car / Motorcycle / Free Parking",
    "duration": "≈15-25 min (estimated)",
    "cost": "Free parking",
    "tip": "The official outlet page lists car and motorcycle access, and the services page confirms free parking throughout the centre with no time limits.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "troyes-train",
    "outletId": "designer-outlet-troyes",
    "transportType": "train",
    "title": "Train to Troyes + Local Transfer",
    "duration": "Rail time varies by origin + about 20 min by TCAT bus from Troyes",
    "cost": "Check official SNCF fare plus TCAT fare",
    "tip": "Use SNCF services to Troyes, then continue by official TCAT bus lines 1 or 12 toward Pont-Sainte-Marie/Creney, or by taxi; rail times and fares vary by departure.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "troyes-local-bus",
    "outletId": "designer-outlet-troyes",
    "transportType": "bus",
    "title": "TCAT Bus Lines 1 and 12",
    "duration": "About 20 min from central Troyes by bus",
    "cost": "Check official TCAT fare",
    "tip": "McArthurGlen states the centre is about 20 minutes from central Troyes by bus; take TCAT lines 1 or 12 toward Pont-Sainte-Marie or Creney and get off at Magasins.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "troyes-airport",
    "outletId": "designer-outlet-troyes",
    "transportType": "airport",
    "title": "Paris airports via rail to Troyes + local bus/taxi",
    "duration": "≈2-3 hr via Paris rail connections + Troyes local transfer (estimated)",
    "cost": "Check official SNCF/airport transit fare",
    "tip": "Use official Paris airport ground transport into Paris, SNCF services to Troyes, then TCAT bus or taxi; no dedicated airport-to-outlet shuttle is published.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "provence-shuttle",
    "outletId": "designer-outlet-provence",
    "transportType": "shuttle",
    "title": "McArthurGlen Shuttle from Marseille or Aix-en-Provence",
    "duration": "10:00 departures; 16:00 return; selected days until August 29, 2026",
    "cost": "€15 round trip; free for children under 12",
    "tip": "Official McArthurGlen Provence shuttle service is available by reservation from Marseille or Aix-en-Provence until August 29, 2026, operating Wednesdays, Saturdays, public holidays and Sundays July 5, July 12 and August 23.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "provence-car-parking",
    "outletId": "designer-outlet-provence",
    "transportType": "car",
    "title": "Car / Free Parking",
    "duration": "45 min",
    "cost": "Free parking",
    "tip": "The official outlet page says the centre is 45 minutes by car from Marseille, Aix-en-Provence and Avignon; free parking is available throughout the centre with no time limits.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "provence-train",
    "outletId": "designer-outlet-provence",
    "transportType": "train",
    "title": "Train to Miramas",
    "duration": "Rail time varies by origin; Miramas station is about 10-15 min onward by BAM bus",
    "cost": "Check official SNCF fare",
    "tip": "Miramas station is served by TGV and TER trains, including routes from Paris and regional links from Marseille, Avignon, Nîmes and Montpellier; confirm times with SNCF.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "provence-bus-bam",
    "outletId": "designer-outlet-provence",
    "transportType": "bus",
    "title": "BAM Direct Bus from Miramas Station",
    "duration": "≈10-15 min (estimated)",
    "cost": "Check official BAM fare",
    "tip": "The official outlet services page lists the direct premium BAM line between Miramas SNCF station, downtown Miramas and the Village of Brands; check official BAM details for current ticketing.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "provence-airports",
    "outletId": "designer-outlet-provence",
    "transportType": "airport",
    "title": "Nearby Airports",
    "duration": "≈35-50 min (estimated)",
    "cost": "Confirm with provider",
    "tip": "The official outlet page lists nearby airports as an access category; Marseille Provence Airport is a realistic road transfer, but fares depend on the chosen taxi, ride-hail or transfer provider.",
    "status": "active",
    "displayOrder": "5"
  },

  {
    "transportationId": "the-village-outlet-car-parking",
    "outletId": "the-village-outlet",
    "transportType": "car",
    "title": "Car via A43 Exit 6 / Free Parking",
    "duration": "About 30 min from Lyon",
    "cost": "Free parking",
    "tip": "The official access information places The Village Outlet at Parc du Couvent in Villefontaine, accessible via the A43 motorway Exit 6 Villefontaine, and official site copy references free parking; check live traffic before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "the-village-outlet-bus",
    "outletId": "the-village-outlet",
    "transportType": "bus",
    "title": "Lyon / Villefontaine Bus Access",
    "duration": "Check official operator timetable",
    "cost": "Check official operator fare",
    "tip": "The official access page lists bus access between Lyon and Villefontaine using Express 5 to The Village stop, and line 2990; verify the current route, stop and timetable with the official operator before travelling.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "the-village-outlet-train",
    "outletId": "the-village-outlet",
    "transportType": "train",
    "title": "TER to La Verpillière",
    "duration": "About 12 min walk from La Verpillière station",
    "cost": "Check official TER/SNCF fare",
    "tip": "The official opening/access information lists access from Gare La Verpillière as a 12-minute walk; use official SNCF/TER channels for current train times and fares.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "the-village-outlet-shuttle",
    "outletId": "the-village-outlet",
    "transportType": "shuttle",
    "title": "Free Event Shuttle",
    "duration": "Runs only during selected commercial and event periods",
    "cost": "Free",
    "tip": "The official shuttle page states free shuttles are provided for visitors during The Village Outlet's commercial and event highlights; confirm current dates, pickup points and reservations before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "roubaix-designer-outlet-car",
    "outletId": "roubaix-designer-outlet",
    "transportType": "car",
    "title": "Car from Lille / Belgium",
    "duration": "15 min from Lille city centre",
    "cost": "Road and parking costs vary",
    "tip": "McArthurGlen states Roubaix Designer Outlet is a 15-minute drive from Lille city centre and is conveniently accessible from Lille, Arras and Belgium; check live traffic before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "roubaix-designer-outlet-parking",
    "outletId": "roubaix-designer-outlet",
    "transportType": "car",
    "title": "Centre Parking",
    "duration": "On site",
    "cost": "1 hr 30 min free with qualifying purchase",
    "tip": "The official McArthurGlen search result for Roubaix states visitors can enjoy 1 hour 30 minutes of free parking with a purchase of €30 or more; confirm current parking validation terms before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "roubaix-designer-outlet-public-transport",
    "outletId": "roubaix-designer-outlet",
    "transportType": "bus",
    "title": "Public Transport from Lille and Surrounding Areas",
    "duration": "Check official public transport timetable",
    "cost": "Check official operator fare",
    "tip": "McArthurGlen states the centre is easily accessible by public transport and lists tramway, metro and bus access categories, including bus services from Lille and surrounding areas; verify the current route with the official operator before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "roubaix-designer-outlet-airport",
    "outletId": "roubaix-designer-outlet",
    "transportType": "airport",
    "title": "Airport Access via Official Ground Transport",
    "duration": "Check official airport and local transport timetable",
    "cost": "Check official operator or taxi fare",
    "tip": "McArthurGlen lists plane access as a getting-here category for Roubaix; use official airport ground transport and local public transport, taxi or rental-car options for the last mile.",
    "status": "active",
    "displayOrder": "4"
  },

  {
    "transportationId": "roppenheim-car-parking",
    "outletId": "roppenheim-the-style-outlets",
    "transportType": "car",
    "title": "Car / on-site parking",
    "duration": "≈30-40 min from Strasbourg; ≈25-35 min from Baden-Baden (estimated)",
    "cost": "Free parking",
    "tip": "The official Roppenheim access page lists the centre at 1 Route de L’Europe and provides car directions; the official parking page lists 1,713 car spaces, 21 motorcycle spaces and 62 bicycle spaces.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "roppenheim-strasbourg-shuttle",
    "outletId": "roppenheim-the-style-outlets",
    "transportType": "shuttle",
    "title": "Free shuttle from Strasbourg",
    "duration": "≈40-50 min (estimated)",
    "cost": "Free with reservation",
    "tip": "Roppenheim's official booking partner page lists a Strasbourg shuttle with compulsory outbound and return reservation, bookable until 1 hour before departure; confirm current operating days before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "roppenheim-bus-231",
    "outletId": "roppenheim-the-style-outlets",
    "transportType": "bus",
    "title": "Cross-border bus 231 Soufflenheim - Rastatt",
    "duration": "Runs during outlet opening hours; verify line 231 times",
    "cost": "Check official regional bus fare",
    "tip": "Official accessibility information for the centre references cross-border bus line 231 between Soufflenheim and Rastatt running during outlet opening hours; verify the current timetable and stop before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "roppenheim-train-taxi",
    "outletId": "roppenheim-the-style-outlets",
    "transportType": "train",
    "title": "Train to Roppenheim or nearby stations + taxi/bus",
    "duration": "≈35-60 min from Strasbourg with last-mile transfer (estimated)",
    "cost": "Check SNCF/TER or DB fare",
    "tip": "Use official SNCF/TER Grand Est or DB channels to reach Roppenheim, Baden-Baden or Rastatt, then continue by local bus, shuttle or taxi; rail schedules and last-mile options vary by day.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "roppenheim-airports",
    "outletId": "roppenheim-the-style-outlets",
    "transportType": "airport",
    "title": "Baden-Airpark or Strasbourg Airport access",
    "duration": "≈25-45 min by car/taxi from Baden-Airpark; ≈45-60 min from Strasbourg Airport (estimated)",
    "cost": "Confirm with airport taxi, rental-car or transfer provider",
    "tip": "For airport arrivals, use official airport ground-transport services to arrange a taxi, rental car or transfer; no official dedicated airport shuttle to the outlet is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "paris-giverny-shuttle",
    "outletId": "paris-giverny-designer-outlet",
    "transportType": "shuttle",
    "title": "Direct shuttle from Paris",
    "duration": "Runs Friday to Sunday; check official schedule",
    "cost": "Check official shuttle fare and promotions",
    "tip": "Official McArthurGlen information advertises a direct shuttle from Paris departing Pullman Tour Eiffel to Paris-Giverny Designer Outlet; reserve and verify current operating dates before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "paris-giverny-car",
    "outletId": "paris-giverny-designer-outlet",
    "transportType": "car",
    "title": "Car via A13 exit 16",
    "duration": "45 min from Paris, Versailles or Rouen",
    "cost": "Fuel, tolls and provider costs vary",
    "tip": "Official McArthurGlen directions state the centre is directly at Exit 16 of the A13 and about 45 minutes from Paris, Versailles and Rouen; check traffic before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "paris-giverny-parking",
    "outletId": "paris-giverny-designer-outlet",
    "transportType": "car",
    "title": "Free parking and EV charging",
    "duration": "On site",
    "cost": "Free parking; EV charging fees may apply",
    "tip": "Official services list free parking with no time limits and more than 120 electric-car charging stations subject to availability, with fees applicable for charging.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "paris-giverny-train",
    "outletId": "paris-giverny-designer-outlet",
    "transportType": "train",
    "title": "Train to Vernon-Giverny + local transfer",
    "duration": "45 min from Paris or 40 min from Rouen to Vernon-Giverny, then local transfer",
    "cost": "Check official SNCF/TER fare",
    "tip": "Official McArthurGlen information lists Vernon-Giverny station as 45 minutes from Paris and 40 minutes from Rouen; confirm the onward shuttle, bus or taxi option and rail timetable before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "paris-giverny-airport",
    "outletId": "paris-giverny-designer-outlet",
    "transportType": "airport",
    "title": "Paris airports via Paris rail/shuttle or road transfer",
    "duration": "Airport transfer to Paris + shuttle/train; road timing varies",
    "cost": "Check official airport transport, SNCF, shuttle or transfer fare",
    "tip": "Use official Paris airport ground transport into Paris for the McArthurGlen shuttle or rail via Vernon-Giverny, or arrange a taxi/transfer; no dedicated airport-to-outlet shuttle was verified.",
    "status": "active",
    "displayOrder": "5"
  },

  {
    "transportationId": "one-nation-paris-car-parking",
    "outletId": "one-nation-paris",
    "transportType": "car",
    "title": "Car / Free Parking",
    "duration": "About 30 min from Paris",
    "cost": "Free parking",
    "tip": "Official One Nation Paris access information lists free parking and car access from Paris via A13, A12 and N12 toward Dreux, exiting at Plaisir / Centre Commercial Régional and following One Nation Paris signs.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "one-nation-paris-train-line-n",
    "outletId": "one-nation-paris",
    "transportType": "train",
    "title": "Transilien Line N to Villepreux-les-Clayes",
    "duration": "Train time varies; about 10 min walk or short bus connection from station",
    "cost": "Check official Transilien fare",
    "tip": "Official One Nation Paris access information says to take Transilien Line N from Paris Montparnasse toward Plaisir Grignon or Mantes-la-Jolie and alight at Villepreux-les-Clayes, then walk about 10 minutes or connect by bus.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "one-nation-paris-bus-5101",
    "outletId": "one-nation-paris",
    "transportType": "bus",
    "title": "Bus 5101 from Villepreux-les-Clayes",
    "duration": "First stop from Villepreux-les-Clayes station",
    "cost": "Check official Île-de-France Mobilités fare",
    "tip": "Official One Nation Paris access information lists bus line 5101 from Villepreux-les-Clayes station, with One Nation Paris Outlet as the first stop; confirm the current timetable before travelling.",
    "status": "active",
    "displayOrder": "3"
  }
];
