export const germanyTransportation = [
  {
    "transportationId": "metzingen-car-parking",
    "outletId": "outletcity-metzingen",
    "transportType": "car",
    "title": "Car + Outletcity parking",
    "duration": "30 min from Stuttgart",
    "cost": "Free parking at P4/P4.1; paid garage rates not published",
    "tip": "Official getting-there information places Outletcity about 30 minutes from Stuttgart and lists garages P0-P3, free spaces P4/P4.1, and EV charging points.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "metzingen-shopping-shuttle",
    "outletId": "outletcity-metzingen",
    "transportType": "shuttle",
    "title": "Shopping Shuttle from Stuttgart",
    "duration": "Check official timetable",
    "cost": "Advance round trip €10; on bus round trip €12 / one-way €8.50",
    "tip": "Official Shopping Shuttle runs several times a week from Stuttgart city centre and Stuttgart Airport area; book online and confirm current times.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "metzingen-train",
    "outletId": "outletcity-metzingen",
    "transportType": "train",
    "title": "Train to Metzingen (Württ)",
    "duration": "≈35–50 min from Stuttgart Hbf (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Official getting-there information lists Metzingen (Württ) station for train access; use official rail or local transport providers for current departures.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "metzingen-bus",
    "outletId": "outletcity-metzingen",
    "transportType": "bus",
    "title": "Bus and regional transport",
    "duration": "eXpresso hourly; other buses check official timetable",
    "cost": "≈€8–15 (estimated); Swiss shuttle fare check provider",
    "tip": "Official options include bwegt regional transport, the hourly eXpresso bus, Eurobus Shuttle Swiss, and bus parking for tour groups.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "metzingen-airport",
    "outletId": "outletcity-metzingen",
    "transportType": "airport",
    "title": "Stuttgart Airport via eXpresso bus or shuttle",
    "duration": "≈20-30 min by road from Stuttgart Airport; eXpresso bus check official timetable",
    "cost": "Check official eXpresso/Shopping Shuttle fare or airport taxi fare",
    "tip": "Official Outletcity access includes the Stuttgart Airport area and eXpresso regional bus connections; verify current airport-area stop and timetable before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "ingolstadt-car-parking",
    "outletId": "ingolstadt-village",
    "transportType": "car",
    "title": "Car + complimentary parking",
    "duration": "45 min from Munich",
    "cost": "Complimentary parking; check EV charging fees",
    "tip": "The Village is directly on the A9 motorway and officially lists complimentary parking and EV charging points.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "ingolstadt-shopping-express",
    "outletId": "ingolstadt-village",
    "transportType": "bus",
    "title": "Shopping Express from Munich",
    "duration": "Check official timetable",
    "cost": "Check official booking page",
    "tip": "Official Shopping Express runs from Munich to Ingolstadt Village and back Monday to Saturday, with departures from Karlsplatz and BMW Welt; book ahead and confirm current departures.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "ingolstadt-train-bus",
    "outletId": "ingolstadt-village",
    "transportType": "train",
    "title": "Train + local bus",
    "duration": "≈20–35 min from Ingolstadt Hbf (estimated); hourly buses",
    "cost": "≈€3–5 (estimated)",
    "tip": "Official directions route Central Station via bus 10 or 11 to Brückenkopf, then bus 20 to the Village; from Ingolstadt Nordbahnhof use bus 20 direct. Official bus timetables should be checked before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "ingolstadt-private-transfer",
    "outletId": "ingolstadt-village",
    "transportType": "taxi",
    "title": "Chauffeur service / private transfer",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "The official getting-here page lists a Chauffeur Service for private transfer arrivals; retain provider confirmation because pricing and pickup details depend on the requested transfer.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "ingolstadt-airport",
    "outletId": "ingolstadt-village",
    "transportType": "airport",
    "title": "Munich Airport by car or rail/bus",
    "duration": "≈45-60 min by car from Munich Airport; rail/bus via Munich or Ingolstadt check official timetable",
    "cost": "Confirm MVV/DB fare or airport taxi/transfer fare",
    "tip": "Use official Munich Airport ground transport, then DB/local bus connections to Ingolstadt Village or an airport road transfer; no dedicated airport shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "wertheim-car-parking",
    "outletId": "wertheim-village",
    "transportType": "car",
    "title": "Car + complimentary parking",
    "duration": "Just under 1 hour from Frankfurt",
    "cost": "Complimentary parking; check EV charging fees",
    "tip": "Official Village information lists train, bus, and car access plus more than 2,500 complimentary parking spaces and EV chargers.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wertheim-shopping-express",
    "outletId": "wertheim-village",
    "transportType": "bus",
    "title": "Shopping Express from Frankfurt",
    "duration": "Check official timetable",
    "cost": "Check official booking page",
    "tip": "Official Shopping Express runs from Frankfurt to Wertheim Village and back Monday to Saturday; book ahead and confirm current departures.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wertheim-train-bus",
    "outletId": "wertheim-village",
    "transportType": "train",
    "title": "Train / bus connections",
    "duration": "≈35–50 min from Würzburg Hbf by regional rail/bus (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Official Village materials describe train and bus access from Frankfurt and Würzburg; confirm current public-transport connections with the operator.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wertheim-private-transfer",
    "outletId": "wertheim-village",
    "transportType": "taxi",
    "title": "Private transfer / group shuttle on request",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "Official partner information lists private transfers on request and a shuttle bus service for groups on request.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "wertheim-airport",
    "outletId": "wertheim-village",
    "transportType": "airport",
    "title": "Frankfurt Airport by car or Frankfurt coach connection",
    "duration": "≈55-75 min by car from Frankfurt Airport; airport rail to Frankfurt + Shopping Express check official timetable",
    "cost": "Confirm airport rail, Shopping Express, taxi or transfer fare",
    "tip": "Use official Frankfurt Airport ground transport to Frankfurt city for the official Shopping Express, or arrange a road transfer; no dedicated airport-to-village shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "berlin-car-parking",
    "outletId": "designer-outlet-berlin",
    "transportType": "car",
    "title": "Car + free parking",
    "duration": "30 min from downtown Berlin; 25 min from Potsdam",
    "cost": "Free parking; check EV charging terms",
    "tip": "Official directions place the outlet directly on the B5 motorway and list 3,000 free parking spaces, disabled parking spaces, and 10 EV charging stations.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "berlin-free-shuttle",
    "outletId": "designer-outlet-berlin",
    "transportType": "shuttle",
    "title": "Free shuttle bus from Berlin",
    "duration": "30 min non-stop; check official timetable",
    "cost": "Free; reserve seat if required",
    "tip": "Official shuttle information lists service from Kurfürstendamm 225 / Hard Rock Café on Fridays, Saturdays, and events; confirm current departures before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "berlin-public-transport",
    "outletId": "designer-outlet-berlin",
    "transportType": "bus",
    "title": "Public transport / A05 Express Bus",
    "duration": "≈45–60 min from central Berlin (estimated)",
    "cost": "≈€4–8 (estimated)",
    "tip": "Official directions confirm public-transport access; use the official rail/VBB provider for current Berlin-Elstal/Wustermark connections and fares before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "berlin-train",
    "outletId": "designer-outlet-berlin",
    "transportType": "train",
    "title": "Regional train to Elstal + local bus",
    "duration": "≈25 min by regional train from Berlin Hbf to Elstal, then local bus/short transfer (estimated)",
    "cost": "Check official VBB/DB fare",
    "tip": "Designer Outlet Berlin officially lists public transport access; use VBB or DB for regional trains toward Elstal/Wustermark and the official local connection to the centre.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "berlin-airport",
    "outletId": "designer-outlet-berlin",
    "transportType": "airport",
    "title": "Berlin Brandenburg Airport via Berlin public transport or car",
    "duration": "≈45-70 min by car; rail/bus via Berlin-Elstal/Wustermark check official timetable",
    "cost": "Confirm VBB/DB fare or airport taxi/transfer fare",
    "tip": "Use official BER ground transport and VBB/DB connections via Berlin toward Elstal/Wustermark before the outlet connection; no dedicated airport-to-outlet shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "neumunster-car-parking",
    "outletId": "designer-outlet-neumunster",
    "transportType": "car",
    "title": "Car + centre parking",
    "duration": "30 min from Hamburg north or Kiel",
    "cost": "Parking €5 per day; first hour free; Premium Parking €10",
    "tip": "Official centre information lists 3,000 parking spaces, disabled parking on P1, Premium Parking, and paid EV charging on P1.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "neumunster-public-transport",
    "outletId": "designer-outlet-neumunster",
    "transportType": "bus",
    "title": "Public transport to Oderstraße",
    "duration": "≈55–75 min from Hamburg Hbf by train + local connection (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "The official visit page lists public transport as an arrival option; confirm current Neumünster train and local bus/taxi connections with the transport provider.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "neumunster-group-ferry",
    "outletId": "designer-outlet-neumunster",
    "transportType": "bus",
    "title": "Ferry and group bookings",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "Official visit information includes ferry and group-booking arrival sections; retain provider confirmation because group/ferry routing and prices vary by origin and operator.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "neumunster-train",
    "outletId": "designer-outlet-neumunster",
    "transportType": "train",
    "title": "Train to Neumünster + local connection",
    "duration": "≈45–60 min train from Hamburg Hbf to Neumünster, then local bus/taxi (estimated)",
    "cost": "Check official NAH.SH/HVV/DB fare",
    "tip": "Official centre information lists public transport as an arrival option. Use official rail to Neumünster station, then confirm the current local bus or taxi connection to Oderstraße before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "neumunster-airport",
    "outletId": "designer-outlet-neumunster",
    "transportType": "airport",
    "title": "Hamburg Airport via train or car",
    "duration": "≈45-60 min by car; S-Bahn/train via Hamburg Hbf and Neumünster check official timetable",
    "cost": "Confirm HVV/DB fare or airport taxi/transfer fare",
    "tip": "Use official Hamburg Airport ground transport to Hamburg Hbf, then rail to Neumünster with local onward transport; no dedicated airport shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "wolfsburg-car-parking",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "car",
    "title": "Car + paid outlet parking",
    "duration": "≈60–75 min from Hannover by car (estimated)",
    "cost": "First 20 min free; 20-120 min €1; 2-4 hours €0.50/hour; from 5th hour €1.50/hour; from 8th hour €5/hour",
    "tip": "Official parking information lists about 1,000 paid spaces, family and accessible spaces, motorcycle parking, and a 1.90 m height limit for tunnel and garage access.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wolfsburg-train",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "train",
    "title": "Train to Wolfsburg Hauptbahnhof",
    "duration": "2 min walk from station",
    "cost": "Check provider fare",
    "tip": "Official directions state Wolfsburg Hauptbahnhof is only a two-minute walk from Designer Outlets Wolfsburg.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wolfsburg-bus",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "bus",
    "title": "Bus to Wolfsburg central bus station",
    "duration": "A few metres from Wolfsburg ZOB",
    "cost": "≈€2–4 (estimated)",
    "tip": "Official directions say all local public transport bus lines serve Wolfsburg ZOB, a few metres from the centre toward Porschestraße.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wolfsburg-airport",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "airport",
    "title": "Hannover Airport via rail or car",
    "duration": "≈60-80 min by car; S-Bahn/ICE via Hannover Hbf to Wolfsburg check official timetable",
    "cost": "Confirm GVH/DB fare or airport taxi/transfer fare",
    "tip": "Use official Hannover Airport rail access to Hannover Hbf, then DB services to Wolfsburg Hauptbahnhof; the outlet is a short walk from the station.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "bad-munstereifel-car-parking",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "car",
    "title": "Car + town parking",
    "duration": "≈50–70 min from Cologne by car (estimated)",
    "cost": "Free spaces in Im Goldenen Tal; paid spaces in Trierer Straße, Kölner Straße, and under Schleidtalstraße",
    "tip": "Official directions say to use A1 exit 112 Bad Münstereifel/Mechernich and follow parking guidance; official services list about 2,200 spaces in town.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "bad-munstereifel-train",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "train",
    "title": "Train to Bad Münstereifel",
    "duration": "≈80–100 min from Cologne Hbf (estimated); station about 150 m from pedestrian zone",
    "cost": "VRS/NRW/Germany Ticket accepted where valid; otherwise ≈€8–15 (estimated)",
    "tip": "Official directions list direct S23/RB23 Voreifelbahn connections via Euskirchen to Bad Münstereifel, with the station close to the outlet area.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "bad-munstereifel-bus-groups",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "bus",
    "title": "Coach groups and bus parking",
    "duration": "Confirm with outlet",
    "cost": "Free bus parking; confirm group details with outlet",
    "tip": "Official services list free bus parking on Schießbachstraße at the L234 and a free group package for groups of 12 or more by registration.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "bad-munstereifel-airport",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "airport",
    "title": "Cologne Bonn Airport via rail or car",
    "duration": "≈55-75 min by car; rail via Cologne/Euskirchen check official timetable",
    "cost": "Confirm airport rail, taxi or rental-car fare",
    "tip": "Use official Cologne Bonn Airport ground transport and DB/VRS rail connections via Cologne and Euskirchen to Bad Münstereifel; no dedicated airport shuttle is published.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "montabaur-car-parking",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "car",
    "title": "Car via A3",
    "duration": "≈35–50 min from Koblenz or Limburg by car (estimated)",
    "cost": "Free parking; check EV charging fees",
    "tip": "Official outlet information lists the centre at Am Fashion Outlet 72 and shows free parking spaces and charging-station services; use A3/Montabaur routing for car access.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "montabaur-train",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "train",
    "title": "ICE train to Montabaur",
    "duration": "Short walk from ICE station",
    "cost": "Check provider fare",
    "tip": "Official outlet information places the centre next to Montabaur ICE train station.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "montabaur-bus",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "bus",
    "title": "RMV bus connections",
    "duration": "≈35–50 min from Koblenz or Limburg by regional bus (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Official outlet information places the centre beside Montabaur transport links; confirm current regional bus connections and fares with the transport provider.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "montabaur-airport",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "airport",
    "title": "Frankfurt Airport ICE access",
    "duration": "≈30-45 min by ICE to Montabaur + short walk; ≈55-75 min by car (estimated)",
    "cost": "Check official DB fare or airport taxi/transfer fare",
    "tip": "Frankfurt Airport has an official long-distance rail station; use DB ICE services to Montabaur station next to the outlet, or official airport road transport.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "zweibrucken-car-parking",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "car",
    "title": "Car + outlet parking",
    "duration": "≈35–50 min from Saarbrücken by car (estimated)",
    "cost": "Parking available; confirm EV charging fees",
    "tip": "Official centre information lists Londoner Bogen 10-90 with parking and charging-station amenities; operator information places the outlet directly at A8 exit 34.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "zweibrucken-bus",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "bus",
    "title": "Bus from Zweibrücken",
    "duration": "Hourly Monday-Saturday; ≈10–15 min from Zweibrücken city/Hbf (estimated)",
    "cost": "≈€3–5 (estimated)",
    "tip": "Official operator information notes a bus connection with the city of Zweibrücken every hour from Monday to Saturday; confirm same-day schedules with the local provider.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "zweibrucken-train-bus",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "train",
    "title": "Train to Zweibrücken + bus",
    "duration": "≈35–50 min from Saarbrücken Hbf via Zweibrücken + bus (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Use official rail and local bus planners for connections via Zweibrücken, then continue by the official hourly city bus connection to the outlet.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "zweibrucken-airport",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "airport",
    "title": "Saarbrücken Airport by road or rail/bus connection",
    "duration": "≈25-40 min by car from Saarbrücken Airport (estimated)",
    "cost": "Confirm airport taxi, rental-car or regional transit fare",
    "tip": "Use official Saarbrücken Airport ground transport to Saarbrücken, then rail/local bus via Zweibrücken or a road transfer; no dedicated airport shuttle is published.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "halle-leipzig-style-outlets-car-parking",
    "outletId": "halle-leipzig-the-style-outlets",
    "transportType": "car",
    "title": "Car via A9 + outlet parking",
    "duration": "≈25–35 min from Leipzig or Halle by car (estimated)",
    "cost": "Free parking; fuel varies",
    "tip": "Official outlet information lists Berliner Straße 1 in Sandersdorf-Brehna and parking; regional tourism information notes convenient A9 access and about 1,800 parking spaces.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "halle-leipzig-style-outlets-train",
    "outletId": "halle-leipzig-the-style-outlets",
    "transportType": "train",
    "title": "S-Bahn S8 to Brehna",
    "duration": "13 min from Halle by train, then local walk or taxi",
    "cost": "Check MDV/DB fare",
    "tip": "Official directions list S-Bahn S8 from Halle toward Lutherstadt Wittenberg, Bitterfeld or Dessau to Brehna, with an approximate 13-minute train journey from Halle.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "halle-leipzig-style-outlets-shuttle",
    "outletId": "halle-leipzig-the-style-outlets",
    "transportType": "bus",
    "title": "Free Saturday shuttle from Leipzig and Halle",
    "duration": "≈25–40 min from Leipzig Hbf or Halle bus station (estimated)",
    "cost": "Free; booking required where offered",
    "tip": "Official directions advertise a free shuttle bus every Saturday from Leipzig main station and Halle bus station; check the official booking page for current departure times.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "halle-leipzig-style-outlets-airport",
    "outletId": "halle-leipzig-the-style-outlets",
    "transportType": "airport",
    "title": "Leipzig/Halle Airport by car or S-Bahn",
    "duration": "≈20–30 min by car from Leipzig/Halle Airport (estimated)",
    "cost": "Confirm taxi, rental car or MDV/DB fare",
    "tip": "Leipzig/Halle Airport officially has its own rail station below check-in with Deutsche Bahn connections; connect by rail via Halle/Leipzig or use the outlet's A9-area road access.",
    "status": "active",
    "displayOrder": "4"
  }
];
