export const germanyTransportation = [
  {
    "transportationId": "ingolstadt-shopping-express",
    "outletId": "ingolstadt-village",
    "transportType": "shuttle",
    "title": "Shopping Express from Munich",
    "duration": "60-75 min",
    "cost": "€20-25",
    "tip": "Best direct option from Munich. Check the latest timetable before travelling.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "ingolstadt-train",
    "outletId": "ingolstadt-village",
    "transportType": "train",
    "title": "Train + Local Transfer",
    "duration": "70-95 min",
    "cost": "€20-35",
    "tip": "Take a train to Ingolstadt Hbf, then continue by bus or taxi.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "ingolstadt-car",
    "outletId": "ingolstadt-village",
    "transportType": "taxi",
    "title": "Car / Taxi from Munich",
    "duration": "55-80 min",
    "cost": "€130-220",
    "tip": "Convenient for groups, families, or airport transfers.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wertheim-shopping-express",
    "outletId": "wertheim-village",
    "transportType": "shuttle",
    "title": "Shopping Express from Frankfurt",
    "duration": "60-75 min",
    "cost": "€20-25",
    "tip": "Best direct option from Frankfurt. Book ahead during weekends and holidays.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wertheim-train",
    "outletId": "wertheim-village",
    "transportType": "train",
    "title": "Train + Local Transfer",
    "duration": "90-130 min",
    "cost": "€20-40",
    "tip": "Use train connections towards Wertheim, then continue by local bus or taxi.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wertheim-car",
    "outletId": "wertheim-village",
    "transportType": "taxi",
    "title": "Car / Taxi from Frankfurt",
    "duration": "55-80 min",
    "cost": "€140-230",
    "tip": "Most flexible option if you plan to shop with large bags.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "metzingen-shopping-shuttle",
    "outletId": "outletcity-metzingen",
    "transportType": "shuttle",
    "title": "Shopping Shuttle from Stuttgart",
    "duration": "40 min",
    "cost": "€10-15",
    "tip": "Official Outletcity Shopping Shuttle. Check departure times before travelling.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "metzingen-train",
    "outletId": "outletcity-metzingen",
    "transportType": "train",
    "title": "Train + Short Walk",
    "duration": "35-45 min",
    "cost": "€10-20",
    "tip": "Travel to Metzingen station, then walk about 10 minutes to Outletcity.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "metzingen-airport-taxi",
    "outletId": "outletcity-metzingen",
    "transportType": "taxi",
    "title": "Taxi / Car from Stuttgart Airport",
    "duration": "25-35 min",
    "cost": "€60-90",
    "tip": "Fastest option from Stuttgart Airport.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "berlin-shuttle",
    "outletId": "designer-outlet-berlin",
    "transportType": "shuttle",
    "title": "Shopping Shuttle from Berlin",
    "duration": "35-45 min",
    "cost": "€10-15",
    "tip": "Use the official shopping shuttle where available and check the latest timetable.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "berlin-train",
    "outletId": "designer-outlet-berlin",
    "transportType": "train",
    "title": "Regional Train + Bus",
    "duration": "45-60 min",
    "cost": "€5-15",
    "tip": "Travel towards Wustermark, then continue by local bus.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "berlin-car",
    "outletId": "designer-outlet-berlin",
    "transportType": "taxi",
    "title": "Car / Taxi",
    "duration": "30-40 min",
    "cost": "€50-80",
    "tip": "Fastest option from Berlin city centre or BER Airport.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "neumunster-train",
    "outletId": "designer-outlet-neumunster",
    "transportType": "train",
    "title": "Train from Hamburg",
    "duration": "60-75 min",
    "cost": "€15-30",
    "tip": "Travel to Neumünster station, then continue by local bus or taxi.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "neumunster-car",
    "outletId": "designer-outlet-neumunster",
    "transportType": "taxi",
    "title": "Car / Taxi from Hamburg",
    "duration": "50-70 min",
    "cost": "€100-160",
    "tip": "Most flexible option from Hamburg city centre or Hamburg Airport.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "neumunster-bus",
    "outletId": "designer-outlet-neumunster",
    "transportType": "bus",
    "title": "Local Bus from Neumünster",
    "duration": "10-20 min",
    "cost": "€2-5",
    "tip": "Use local bus connections from Neumünster station to the outlet area.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "montabaur-train",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "train",
    "title": "ICE Train + Short Taxi",
    "duration": "60-75 min",
    "cost": "€20-40",
    "tip": "Take the ICE to Montabaur, then a short taxi ride.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "montabaur-car",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "taxi",
    "title": "Car / Taxi",
    "duration": "60-70 min",
    "cost": "Varies",
    "tip": "Fastest option from Frankfurt Airport.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "montabaur-bus",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "bus",
    "title": "Local Bus",
    "duration": "10-15 min",
    "cost": "€2-5",
    "tip": "Available from Montabaur station.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "zweibrucken-train",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "train",
    "title": "Train + Local Bus",
    "duration": "70-90 min",
    "cost": "€15-30",
    "tip": "Travel to Zweibrücken, then continue by local bus.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "zweibrucken-car",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "taxi",
    "title": "Car / Taxi",
    "duration": "35-45 min",
    "cost": "Varies",
    "tip": "Fastest option from Saarbrücken Airport.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "zweibrucken-bus",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "bus",
    "title": "Regional Bus",
    "duration": "15-20 min",
    "cost": "€2-5",
    "tip": "Regular buses connect the station and outlet.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "bad-munstereifel-train",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "train",
    "title": "Train to Bad Münstereifel",
    "duration": "70-90 min",
    "cost": "€15-30",
    "tip": "Travel via Euskirchen, then continue to Bad Münstereifel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "bad-munstereifel-car",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "taxi",
    "title": "Car / Taxi",
    "duration": "60-70 min",
    "cost": "Varies",
    "tip": "Fastest option from Cologne.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "bad-munstereifel-bus",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "bus",
    "title": "Regional Bus",
    "duration": "10-20 min",
    "cost": "€2-5",
    "tip": "Available from Bad Münstereifel station.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wolfsburg-train",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "train",
    "title": "Train to Wolfsburg",
    "duration": "60-80 min",
    "cost": "€15-30",
    "tip": "Outlet is a short walk from Wolfsburg Hauptbahnhof.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wolfsburg-car",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "taxi",
    "title": "Car / Taxi",
    "duration": "60-70 min",
    "cost": "Varies",
    "tip": "Convenient from Hannover Airport.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wolfsburg-bus",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "bus",
    "title": "City Bus",
    "duration": "5-10 min",
    "cost": "€2-4",
    "tip": "Several buses connect the station and outlet.",
    "status": "active",
    "displayOrder": "3"
  }
];
