export const germanyTransportation = [
  {
    "transportationId": "metzingen-car-parking",
    "outletId": "outletcity-metzingen",
    "transportType": "taxi",
    "title": "Car + Outletcity parking",
    "duration": "Check route planner",
    "cost": "Check official parking information",
    "tip": "Official parking includes garages P0-P3, free spaces P4/P4.1, and EV charging points; Stuttgart Airport is nearby.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "metzingen-shopping-shuttle",
    "outletId": "outletcity-metzingen",
    "transportType": "shuttle",
    "title": "Shopping Shuttle from Stuttgart",
    "duration": "Check official timetable",
    "cost": "Advance round trip €10; on bus round trip €12 / one-way €8.50",
    "tip": "Official Shopping Shuttle runs several times a week from Stuttgart city centre and Stuttgart Airport area; book online and confirm current times.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "metzingen-train",
    "outletId": "outletcity-metzingen",
    "transportType": "train",
    "title": "Train to Metzingen (Württ)",
    "duration": "Check official timetable",
    "cost": "Check provider fare",
    "tip": "Use Metzingen (Württ) station for train access to Outletcity; confirm connections with the official rail or local transport provider.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "metzingen-bus",
    "outletId": "outletcity-metzingen",
    "transportType": "bus",
    "title": "Bus and regional transport",
    "duration": "Check official timetable",
    "cost": "Check provider fare",
    "tip": "Official options include bwegt regional transport, the hourly eXpresso bus, Eurobus Shuttle Swiss, and bus parking for tour groups.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "ingolstadt-car-parking",
    "outletId": "ingolstadt-village",
    "transportType": "taxi",
    "title": "Car + complimentary parking",
    "duration": "45 min from Munich",
    "cost": "Complimentary parking; check EV charging fees",
    "tip": "The Village is directly on the A9 motorway and officially lists complimentary parking and EV charging points.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "ingolstadt-shopping-express",
    "outletId": "ingolstadt-village",
    "transportType": "shuttle",
    "title": "Shopping Express from Munich",
    "duration": "Check official timetable",
    "cost": "Check official booking page",
    "tip": "Official Shopping Express runs from Munich to Ingolstadt Village and back Monday to Saturday, with departures from Karlsplatz and BMW Welt; book ahead and confirm current departures.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "ingolstadt-train-bus",
    "outletId": "ingolstadt-village",
    "transportType": "train",
    "title": "Train + local bus",
    "duration": "≈20–35 min from Ingolstadt Hbf (estimated); hourly buses",
    "cost": "≈€3–5 (estimated)",
    "tip": "Official directions route Central Station via bus 10 or 11 to Brückenkopf, then bus 20 to the Village; from Ingolstadt Nordbahnhof use bus 20 direct. Official bus timetables should be checked before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "ingolstadt-private-transfer",
    "outletId": "ingolstadt-village",
    "transportType": "taxi",
    "title": "Chauffeur service / private transfer",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "The official getting-here page lists a Chauffeur Service for private transfer arrivals; retain provider confirmation because pricing and pickup details depend on the requested transfer.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "wertheim-car-parking",
    "outletId": "wertheim-village",
    "transportType": "taxi",
    "title": "Car + complimentary parking",
    "duration": "Just under 1 hour from Frankfurt",
    "cost": "Complimentary parking; check EV charging fees",
    "tip": "Official Village information lists train, bus, and car access plus more than 2,500 complimentary parking spaces and EV chargers.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wertheim-shopping-express",
    "outletId": "wertheim-village",
    "transportType": "shuttle",
    "title": "Shopping Express from Frankfurt",
    "duration": "Check official timetable",
    "cost": "Check official booking page",
    "tip": "Official Shopping Express runs from Frankfurt to Wertheim Village and back Monday to Saturday; book ahead and confirm current departures.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wertheim-train-bus",
    "outletId": "wertheim-village",
    "transportType": "train",
    "title": "Train / bus connections",
    "duration": "Check official timetable",
    "cost": "Check provider fare",
    "tip": "The official Village materials describe access by train, bus, or car; confirm current connections with the relevant transport operator.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wertheim-private-transfer",
    "outletId": "wertheim-village",
    "transportType": "taxi",
    "title": "Private transfer / group shuttle on request",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "Official partner information lists private transfers on request and a shuttle bus service for groups on request.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "berlin-car-parking",
    "outletId": "designer-outlet-berlin",
    "transportType": "taxi",
    "title": "Car + free parking",
    "duration": "30 min from downtown Berlin; 25 min from Potsdam",
    "cost": "Free parking; check EV charging terms",
    "tip": "Official directions place the outlet directly on the B5 motorway and list 3,000 free parking spaces, disabled parking spaces, and 10 EV charging stations.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "berlin-free-shuttle",
    "outletId": "designer-outlet-berlin",
    "transportType": "shuttle",
    "title": "Free shuttle bus from Berlin",
    "duration": "30 min non-stop; check official timetable",
    "cost": "Free; reserve seat if required",
    "tip": "Official shuttle information lists service from Kurfürstendamm 225 / Hard Rock Café on Fridays, Saturdays, and events; confirm current departures before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "berlin-public-transport",
    "outletId": "designer-outlet-berlin",
    "transportType": "bus",
    "title": "Public transport / A05 Express Bus",
    "duration": "≈45–60 min from central Berlin (estimated)",
    "cost": "≈€4–8 (estimated)",
    "tip": "Official directions confirm public-transport access; use the official rail/VBB provider for current Berlin-Elstal/Wustermark connections and fares before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "neumunster-car-parking",
    "outletId": "designer-outlet-neumunster",
    "transportType": "taxi",
    "title": "Car + centre parking",
    "duration": "30 min from Hamburg north or Kiel",
    "cost": "Parking €5 per day; first hour free; Premium Parking €10",
    "tip": "Official centre information lists 3,000 parking spaces, disabled parking on P1, Premium Parking, and paid EV charging on P1.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "neumunster-public-transport",
    "outletId": "designer-outlet-neumunster",
    "transportType": "bus",
    "title": "Public transport to Oderstraße",
    "duration": "≈55–75 min from Hamburg Hbf by train + local connection (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "The official visit page lists public transport as an arrival option; confirm current Neumünster train and local bus/taxi connections with the transport provider.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "neumunster-group-ferry",
    "outletId": "designer-outlet-neumunster",
    "transportType": "bus",
    "title": "Ferry and group bookings",
    "duration": "Confirm with provider",
    "cost": "Confirm with provider",
    "tip": "Official visit information includes ferry and group-booking arrival sections; retain provider confirmation because group/ferry routing and prices vary by origin and operator.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "wolfsburg-car-parking",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "taxi",
    "title": "Car + paid outlet parking",
    "duration": "≈60–75 min from Hannover by car (estimated)",
    "cost": "First 20 min free; 20-120 min €1; 2-4 hours €0.50/hour; from 5th hour €1.50/hour; from 8th hour €5/hour",
    "tip": "Official parking information lists about 1,000 paid spaces, family and accessible spaces, motorcycle parking, and a 1.90 m height limit for tunnel and garage access.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "wolfsburg-train",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "train",
    "title": "Train to Wolfsburg Hauptbahnhof",
    "duration": "2 min walk from station",
    "cost": "Check provider fare",
    "tip": "Official directions state Wolfsburg Hauptbahnhof is only a two-minute walk from Designer Outlets Wolfsburg.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "wolfsburg-bus",
    "outletId": "designer-outlets-wolfsburg",
    "transportType": "bus",
    "title": "Bus to Wolfsburg central bus station",
    "duration": "A few metres from Wolfsburg ZOB",
    "cost": "≈€2–4 (estimated)",
    "tip": "Official directions say all local public transport bus lines serve Wolfsburg ZOB, a few metres from the centre toward Porschestraße.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "bad-munstereifel-car-parking",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "taxi",
    "title": "Car + town parking",
    "duration": "≈50–70 min from Cologne by car (estimated)",
    "cost": "Free spaces in Im Goldenen Tal; paid spaces in Trierer Straße, Kölner Straße, and under Schleidtalstraße",
    "tip": "Official directions say to use A1 exit 112 Bad Münstereifel/Mechernich and follow parking guidance; official services list about 2,200 spaces in town.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "bad-munstereifel-train",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "train",
    "title": "Train to Bad Münstereifel",
    "duration": "≈80–100 min from Cologne Hbf (estimated); station about 150 m from pedestrian zone",
    "cost": "VRS/NRW/Germany Ticket accepted where valid; otherwise ≈€8–15 (estimated)",
    "tip": "Official directions list direct S23/RB23 Voreifelbahn connections via Euskirchen to Bad Münstereifel, with the station close to the outlet area.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "bad-munstereifel-bus-groups",
    "outletId": "city-outlet-bad-munstereifel",
    "transportType": "bus",
    "title": "Coach groups and bus parking",
    "duration": "Confirm with outlet",
    "cost": "Free bus parking; confirm group details with outlet",
    "tip": "Official services list free bus parking on Schießbachstraße at the L234 and a free group package for groups of 12 or more by registration.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "montabaur-car-parking",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "taxi",
    "title": "Car via A3",
    "duration": "Check route planner",
    "cost": "Check official parking information",
    "tip": "Official outlet information places Montabaur The Style Outlets directly by the A3 motorway; confirm current parking details before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "montabaur-train",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "train",
    "title": "ICE train to Montabaur",
    "duration": "Short walk from ICE station",
    "cost": "Check provider fare",
    "tip": "Official outlet information places the centre next to Montabaur ICE train station.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "montabaur-bus",
    "outletId": "montabaur-the-style-outlets",
    "transportType": "bus",
    "title": "RMV bus connections",
    "duration": "Check official timetable",
    "cost": "Check RMV fare",
    "tip": "Official outlet information says the centre is reachable by bus through RMV connections from cities such as Koblenz or Limburg.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "zweibrucken-car-parking",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "taxi",
    "title": "Car + outlet parking",
    "duration": "Check route planner",
    "cost": "Check official parking information",
    "tip": "Official centre information lists the address at Londoner Bogen 10-90, parking, and charging-station amenities; the operator notes location at A8 exit 34.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "zweibrucken-bus",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "bus",
    "title": "Bus from Zweibrücken",
    "duration": "Check official timetable",
    "cost": "Check provider fare",
    "tip": "Official operator information notes a bus connection with the city of Zweibrücken every hour from Monday to Saturday; confirm current schedules before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "zweibrucken-train-bus",
    "outletId": "zweibrucken-fashion-outlet",
    "transportType": "train",
    "title": "Train to Zweibrücken + bus",
    "duration": "Check official timetable",
    "cost": "Check provider fare",
    "tip": "Use official rail and local bus planners for connections via Zweibrücken, then continue by the official city bus connection to the outlet.",
    "status": "active",
    "displayOrder": "3"
  }
];
