export const italyTransportation = [
  {
    "transportationId": "barberino-car",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Car via A1 motorway",
    "duration": "Check route conditions",
    "cost": "Varies by route and provider",
    "tip": "Official directions list A1 motorway access to the Barberino exit, plus routes from Florence and Prato; use the official route link before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "barberino-parking",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official McArthurGlen services list free parking at Barberino Designer Outlet; follow centre signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "barberino-shuttle",
    "outletId": "barberino",
    "transportType": "shuttle",
    "title": "Shuttle from Firenze Santa Maria Novella",
    "duration": "Check official timetable",
    "cost": "Check official ticket details",
    "tip": "Official information says the shuttle links Firenze Santa Maria Novella and Barberino Outlet; verify current departures and book via the official ticket channel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "barberino-train-shuttle",
    "outletId": "barberino",
    "transportType": "train",
    "title": "Train to Firenze SMN + outlet shuttle",
    "duration": "Depends on train origin and shuttle timetable",
    "cost": "Check Trenitalia combined ticket",
    "tip": "Official outlet information notes a combined train and shuttle ticket for travel via Firenze Santa Maria Novella.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "barberino-private-transfer",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Private transfer from hotel",
    "duration": "Confirm when booking",
    "cost": "Confirm with Infopoint",
    "tip": "Official information lists hotel pick-up private transfer reservations through the outlet Infopoint; confirm availability before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "castel-romano-car",
    "outletId": "castel-romano",
    "transportType": "taxi",
    "title": "Car from Rome",
    "duration": "About 30 min from Rome",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information positions Castel Romano Designer Outlet about 30 minutes from Rome; follow official directions to Via Ponte di Piscina Cupa.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "castel-romano-parking",
    "outletId": "castel-romano",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Castel Romano Designer Outlet; follow parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "castel-romano-shuttle",
    "outletId": "castel-romano",
    "transportType": "shuttle",
    "title": "Shuttle from Termini or EUR Fermi",
    "duration": "Check official timetable",
    "cost": "Check official ticket details",
    "tip": "Official McArthurGlen shuttle information lists service from Termini Station or Eur Fermi Underground stop; book or verify departures on the official service page.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "castel-romano-train-bus",
    "outletId": "castel-romano",
    "transportType": "train",
    "title": "Trenitalia train + bus Outlet Link",
    "duration": "Check Trenitalia timetable",
    "cost": "Check Trenitalia fare",
    "tip": "Trenitalia officially lists Castel Romano Designer Outlet Link as a train plus bus service from Roma Termini, with buses departing from Via Giolitti 48.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "fidenza-coach",
    "outletId": "fidenza-village",
    "transportType": "shuttle",
    "title": "Coach service from Milan",
    "duration": "Check official timetable",
    "cost": "Check official ticket details",
    "tip": "Fidenza Village's official getting-here page lists a coach service from Milan; book and confirm the current schedule through the Village.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "fidenza-car",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "Car via A1 motorway",
    "duration": "About 60 min from Milan or Bologna; about 20 min from Parma",
    "cost": "Varies by route and provider",
    "tip": "Official destination information places Fidenza Village near the A1 Milan-Bologna motorway at Fidenza/Salsomaggiore Terme, with access from Milan, Bologna and Parma.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "fidenza-parking",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Confirm with the Village",
    "tip": "Use the official Village directions and on-site signage for parking; confirm any special parking arrangements with Guest Services.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "fidenza-private-transfer",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "Private chauffeur transfer",
    "duration": "Confirm when booking",
    "cost": "Confirm with Concierge",
    "tip": "Fidenza Village officially offers chauffeur booking via Concierge with at least 24 hours' notice; provide transfer details when reserving.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "la-reggia-car",
    "outletId": "la-reggia",
    "transportType": "taxi",
    "title": "Car via A1 Caserta Sud",
    "duration": "Check route conditions",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information says La Reggia is adjacent to the A1 motorway at the Caserta Sud exit, with access from Naples, Caserta and Sorrento.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "la-reggia-parking",
    "outletId": "la-reggia",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list more than 3,000 free parking spaces at La Reggia Designer Outlet.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "la-reggia-public-transport",
    "outletId": "la-reggia",
    "transportType": "bus",
    "title": "Official public transport guidance",
    "duration": "Check official timetable",
    "cost": "Check operator fare",
    "tip": "McArthurGlen lists public transport options for La Reggia; confirm the current operator route and stop on the official outlet page before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "la-reggia-private-transfer",
    "outletId": "la-reggia",
    "transportType": "taxi",
    "title": "Private transfer",
    "duration": "Confirm when booking",
    "cost": "Confirm with provider",
    "tip": "Official McArthurGlen information lists private transfer as an option for La Reggia; confirm availability, pickup point and fare with the provider.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "noventa-car",
    "outletId": "noventa",
    "transportType": "taxi",
    "title": "Car to Noventa di Piave",
    "duration": "Check route conditions",
    "cost": "Varies by route and provider",
    "tip": "Use the official McArthurGlen directions for Noventa di Piave Designer Outlet and confirm traffic conditions before leaving Venice or nearby airports.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "noventa-parking",
    "outletId": "noventa",
    "transportType": "taxi",
    "title": "Outlet parking",
    "duration": "On site",
    "cost": "Confirm on official page",
    "tip": "Official outlet information lists parking and may announce extra parking with free shuttle during busy dates; check the official plan-your-visit page before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "noventa-atvo-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO direct bus from Venice and Mestre",
    "duration": "Check ATVO timetable",
    "cost": "Check ATVO fare",
    "tip": "ATVO officially lists a direct bus from Venice Piazzale Roma and Mestre Railway Station to Noventa di Piave Designer Outlet.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "noventa-airport-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO airport connection",
    "duration": "Check ATVO timetable",
    "cost": "Check ATVO fare",
    "tip": "ATVO official outlet service information references airport arrival and bus-stop guidance; confirm current airport stops and times with ATVO.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "serravalle-car",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Car from Milan, Genoa or Turin",
    "duration": "About 1 hr from Milan, 45 min from Genoa, under 90 min from Turin",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen directions list convenient road access from Milan, Genoa and Turin; check traffic and route conditions before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "serravalle-parking",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Serravalle Designer Outlet; follow outlet parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "serravalle-shuttle",
    "outletId": "serravalle-designer-outlet",
    "transportType": "shuttle",
    "title": "Daily shuttle service",
    "duration": "Check official timetable",
    "cost": "Check official ticket details",
    "tip": "Official McArthurGlen information lists a daily shuttle service for Serravalle; verify the latest timetable and booking channel before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "serravalle-train-bus",
    "outletId": "serravalle-designer-outlet",
    "transportType": "train",
    "title": "Trenitalia train + bus Outlet Link",
    "duration": "Check Trenitalia timetable",
    "cost": "Check Trenitalia fare",
    "tip": "Trenitalia and McArthurGlen list Serravalle Outlet as a combined train plus bus destination; select 'Serravalle Outlet' in Trenitalia channels.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "serravalle-private-transfer",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Private transfer",
    "duration": "Confirm when booking",
    "cost": "Confirm with provider",
    "tip": "Official McArthurGlen plan-your-visit information lists private transfer as an option for Serravalle; confirm price, pickup point and timing with the provider.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "firenze-car",
    "outletId": "the-mall-firenze",
    "transportType": "taxi",
    "title": "Car via A1 Incisa-Reggello",
    "duration": "Check route conditions",
    "cost": "Varies by route and provider",
    "tip": "The Mall Firenze official visit page lists Via Europa 8, Leccio Reggello, and directions to leave the motorway at Incisa-Reggello.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "firenze-direct-bus",
    "outletId": "the-mall-firenze",
    "transportType": "shuttle",
    "title": "The Mall by Bus from Florence",
    "duration": "Check Busitalia timetable",
    "cost": "Check Busitalia fare",
    "tip": "Busitalia officially operates The Mall by Bus as a direct connection from Piazzale Montelungo near Firenze Santa Maria Novella to The Mall Firenze.",
    "status": "active",
    "displayOrder": "2"
  }
];
