export const italyTransportation = [
  {
    "transportationId": "barberino-car",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Car via A1 motorway",
    "duration": "≈30–40 min from Florence by car",
    "cost": "Varies by route and provider",
    "tip": "Official directions list A1 motorway access at the Barberino exit; keep traffic-dependent car timing as an estimate and use the official route link before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "barberino-parking",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official McArthurGlen services list free parking at Barberino Designer Outlet; follow centre signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "barberino-shuttle",
    "outletId": "barberino",
    "transportType": "shuttle",
    "title": "Shuttle from Firenze Santa Maria Novella",
    "duration": "30 min from Firenze Santa Maria Novella",
    "cost": "From €13 one-way; check official ticket details",
    "tip": "Official Barberino and Trenitalia Outlet Link information lists a non-stop 30-minute shuttle from Firenze Santa Maria Novella, with three daily round trips; verify the current seasonal departures before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "barberino-train-shuttle",
    "outletId": "barberino",
    "transportType": "train",
    "title": "Train to Firenze SMN + outlet shuttle",
    "duration": "Train to Firenze SMN + 30 min Outlet Link bus",
    "cost": "Check Trenitalia combined ticket",
    "tip": "Trenitalia officially sells Barberino Outlet Link as a train plus non-stop bus connection from Firenze Santa Maria Novella; fare varies by rail origin, so price the combined ticket in Trenitalia channels.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "barberino-private-transfer",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Private transfer from hotel",
    "duration": "≈30–45 min from Florence (estimated)",
    "cost": "Confirm with Infopoint",
    "tip": "Official information lists hotel pick-up private transfer reservations through the outlet Infopoint; confirm availability before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "castel-romano-car",
    "outletId": "castel-romano",
    "transportType": "taxi",
    "title": "Car from Rome",
    "duration": "About 30 min from Rome",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information positions Castel Romano Designer Outlet about 30 minutes from Rome; follow official directions to Via Ponte di Piscina Cupa.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "castel-romano-parking",
    "outletId": "castel-romano",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Castel Romano Designer Outlet; follow parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "castel-romano-shuttle",
    "outletId": "castel-romano",
    "transportType": "shuttle",
    "title": "Shuttle from Termini or EUR Fermi",
    "duration": "≈30–45 min from Rome (estimated)",
    "cost": "€18 return from Termini or €13 return from EUR Fermi",
    "tip": "Official McArthurGlen shuttle information lists departures from Termini and EUR Fermi, with published return fares; book or verify departures on the official service page.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "castel-romano-train-bus",
    "outletId": "castel-romano",
    "transportType": "train",
    "title": "Trenitalia train + bus Outlet Link",
    "duration": "≈30–45 min bus segment from Roma Termini (estimated)",
    "cost": "Check Trenitalia combined fare",
    "tip": "Trenitalia officially lists Castel Romano Designer Outlet Link as a train plus bus service from Roma Termini, with buses departing from Via Giolitti 48.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "fidenza-coach",
    "outletId": "fidenza-village",
    "transportType": "shuttle",
    "title": "Coach service from Milan",
    "duration": "1 hr 30 min from Milan Piazza della Repubblica",
    "cost": "€10 adult; €5 children 5–11; free infants 0–4",
    "tip": "The official Shopping Express page lists a 9:45 departure from Milan and 11:15 arrival at Fidenza Village, returning 17:00 to 18:30; book on the official channel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "fidenza-car",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "Car via A1 motorway",
    "duration": "About 60 min from Milan or Bologna; about 20 min from Parma",
    "cost": "Varies by route and provider",
    "tip": "Official destination information places Fidenza Village near the A1 Milan-Bologna motorway at Fidenza/Salsomaggiore Terme, with access from Milan, Bologna and Parma.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "fidenza-parking",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Use the official Village directions and on-site signage for the complimentary parking areas; confirm any special parking arrangements with Guest Services.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "fidenza-private-transfer",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "Private chauffeur transfer",
    "duration": "≈60 min from Milan or Bologna (estimated)",
    "cost": "Confirm with Concierge",
    "tip": "Fidenza Village officially offers chauffeur booking via Concierge with at least 24 hours' notice; provide transfer details when reserving.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "la-reggia-car",
    "outletId": "la-reggia",
    "transportType": "taxi",
    "title": "Car via A1 Caserta Sud",
    "duration": "≈20–30 min from Naples; ≈15 min from Caserta",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information says La Reggia is adjacent to the A1 motorway at Caserta Sud and about 20 minutes from Naples; check traffic before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "la-reggia-parking",
    "outletId": "la-reggia",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list more than 3,000 free parking spaces at La Reggia Designer Outlet.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "la-reggia-public-transport",
    "outletId": "la-reggia",
    "transportType": "bus",
    "title": "Public transport via Naples or Caserta",
    "duration": "≈35–50 min from Naples; ≈20–30 min from Caserta (estimated)",
    "cost": "≈€3–8 (estimated)",
    "tip": "McArthurGlen lists public transport for La Reggia but does not publish current route details or fares on the access page; use the official local transport provider timetable before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "la-reggia-shuttle",
    "outletId": "la-reggia",
    "transportType": "shuttle",
    "title": "Shuttle service from Naples",
    "duration": "≈35–50 min from Naples (estimated)",
    "cost": "Confirm with provider",
    "tip": "McArthurGlen's access page officially lists a shuttle service from Naples, but current fare details are not published on the accessible official page; confirm pickup point, operating dates and price with the provider before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "noventa-car",
    "outletId": "noventa",
    "transportType": "taxi",
    "title": "Car to Noventa di Piave",
    "duration": "30 min from Venice by car",
    "cost": "Varies by route and provider",
    "tip": "Use the official McArthurGlen directions for Noventa di Piave Designer Outlet and confirm traffic conditions before leaving Venice or nearby airports.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "noventa-parking",
    "outletId": "noventa",
    "transportType": "taxi",
    "title": "Outlet parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official outlet information lists parking and may announce extra parking with free shuttle during busy dates; check the official plan-your-visit page before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "noventa-atvo-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO direct bus from Venice and Mestre",
    "duration": "90 min from Venice Piazzale Roma; 75 min from Mestre",
    "cost": "€9.20 return; free under 6",
    "tip": "ATVO and McArthurGlen officially list direct Venice, Mestre and airport buses to Noventa di Piave Designer Outlet with a published return fare; check the current ATVO timetable before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "noventa-airport-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO airport connection",
    "duration": "55 min from Venice Marco Polo Airport",
    "cost": "€9.20 return on outlet service; confirm airport fare rules with ATVO",
    "tip": "ATVO official outlet service information lists Marco Polo Airport as an intermediate stop; confirm current airport stops, times and ticket validity with ATVO.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "serravalle-car",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Car from Milan, Genoa or Turin",
    "duration": "About 1 hr from Milan, 45 min from Genoa, under 90 min from Turin",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen directions list convenient road access from Milan, Genoa and Turin; check traffic and route conditions before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "serravalle-parking",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Serravalle Designer Outlet; follow outlet parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "serravalle-shuttle",
    "outletId": "serravalle-designer-outlet",
    "transportType": "shuttle",
    "title": "Daily shuttle from Milan",
    "duration": "≈80–100 min from Milan (estimated)",
    "cost": "€25 return; €10 children 4–12; free under 4",
    "tip": "Official McArthurGlen Bus Connection information lists daily Zani Viaggi and Frigerio Viaggi departures from Milan Centrale, Cairoli, Brera, Cadorna, Buenos Aires and Navigli, with the published return fare; book through the official partner link and confirm the selected departure.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "serravalle-genoa-bus",
    "outletId": "serravalle-designer-outlet",
    "transportType": "bus",
    "title": "FlixBus from Genoa",
    "duration": "≈35–50 min from Genoa (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Official McArthurGlen Bus Connection information lists daily FlixBus services from Genova Fanti d’Italia to Serravalle; fare varies by travel date, so book and verify the exact stop with FlixBus.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "serravalle-train-bus",
    "outletId": "serravalle-designer-outlet",
    "transportType": "train",
    "title": "Trenitalia train + Outlet Link bus",
    "duration": "≈90–120 min from Milan depending on connection (estimated)",
    "cost": "Check Trenitalia combined fare",
    "tip": "McArthurGlen lists the Trenitalia Serravalle Designer Outlet LINK as a combined train plus bus ticket from Serravalle Scrivia, Arquata Scrivia and Novi Ligure stations; select 'Serravalle Outlet' in Trenitalia channels for the current combined itinerary.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "serravalle-airports",
    "outletId": "serravalle-designer-outlet",
    "transportType": "taxi",
    "title": "Nearby airports by car or transfer",
    "duration": "≈60–90 min from Milan airports or Genoa Airport (estimated)",
    "cost": "Confirm with provider",
    "tip": "Official McArthurGlen plan-your-visit information flags nearby airports and private transfer options, but does not publish airport transfer fares; confirm pickup point, price and timing with the chosen provider.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "firenze-car",
    "outletId": "the-mall-firenze",
    "transportType": "taxi",
    "title": "Car via A1 Incisa-Reggello",
    "duration": "≈30–45 min from Florence by car",
    "cost": "Varies by route and provider",
    "tip": "The Mall Firenze official visit page lists Via Europa 8, Leccio Reggello, and directions to leave the motorway at Incisa-Reggello; check traffic before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "firenze-parking",
    "outletId": "the-mall-firenze",
    "transportType": "taxi",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "The Mall Firenze official visit page lists the outlet address and Google directions; use on-site signage for the customer parking areas when arriving by car.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "firenze-direct-bus",
    "outletId": "the-mall-firenze",
    "transportType": "shuttle",
    "title": "The Mall by Bus from Florence",
    "duration": "≈50–60 min from Florence (estimated)",
    "cost": "€9.50 one-way or €18 return",
    "tip": "Busitalia officially operates The Mall by Bus from Piazzale Montelungo near Firenze Santa Maria Novella to The Mall Firenze, with published fares and same-day return validity; confirm the current timetable before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "firenze-train-taxi",
    "outletId": "the-mall-firenze",
    "transportType": "train",
    "title": "Train to Rignano sull'Arno-Reggello + taxi",
    "duration": "≈35–50 min train and taxi from Florence (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Use official Trenitalia services from Firenze Santa Maria Novella to Rignano sull'Arno-Reggello, then a short local taxi or arranged transfer to The Mall Firenze; confirm taxi availability for the last-mile segment.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "firenze-airport",
    "outletId": "the-mall-firenze",
    "transportType": "taxi",
    "title": "Florence Airport by car or taxi",
    "duration": "≈35–50 min from Florence Airport (estimated)",
    "cost": "Confirm with provider",
    "tip": "The Mall Firenze travel guide places Florence Airport about 45 km from the outlet; use the airport's official taxi or transfer providers and confirm the fare before departure.",
    "status": "active",
    "displayOrder": "5"
  }
];
