export const italyTransportation = [
  {
    "transportationId": "barberino-car",
    "outletId": "barberino",
    "transportType": "car",
    "title": "Car via A1 motorway",
    "duration": "≈30–40 min from Florence by car",
    "cost": "Varies by route and provider",
    "tip": "Official directions list A1 motorway access at the Barberino exit; keep traffic-dependent car timing as an estimate and use the official route link before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "barberino-parking",
    "outletId": "barberino",
    "transportType": "car",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official McArthurGlen services list free parking at Barberino Designer Outlet; follow centre signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "barberino-shuttle",
    "outletId": "barberino",
    "transportType": "bus",
    "title": "Shuttle from Firenze Santa Maria Novella",
    "duration": "30 min from Firenze Santa Maria Novella",
    "cost": "From €13 one-way; check official ticket details",
    "tip": "Official Barberino and Trenitalia Outlet Link information lists a non-stop 30-minute shuttle from Firenze Santa Maria Novella, with three daily round trips; verify the current seasonal departures before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "barberino-train-shuttle",
    "outletId": "barberino",
    "transportType": "train",
    "title": "Train to Firenze SMN + outlet shuttle",
    "duration": "Train to Firenze SMN + 30 min Outlet Link bus",
    "cost": "Check Trenitalia combined ticket",
    "tip": "Trenitalia officially sells Barberino Outlet Link as a train plus non-stop bus connection from Firenze Santa Maria Novella; fare varies by rail origin, so price the combined ticket in Trenitalia channels.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "barberino-private-transfer",
    "outletId": "barberino",
    "transportType": "taxi",
    "title": "Private transfer from hotel",
    "duration": "≈30–45 min from Florence (estimated)",
    "cost": "Confirm with Infopoint",
    "tip": "Official information lists hotel pick-up private transfer reservations through the outlet Infopoint; confirm availability before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "barberino-airport",
    "outletId": "barberino",
    "transportType": "airport",
    "title": "Florence Airport via Florence SMN shuttle",
    "duration": "≈15-25 min airport to Firenze SMN + 30 min outlet shuttle (estimated)",
    "cost": "Airport tram/bus fare + official shuttle fare",
    "tip": "Use official Florence Airport ground transport to reach Firenze Santa Maria Novella, then use the official Barberino shuttle/Outlet Link; no dedicated airport-to-outlet shuttle is published.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "castel-romano-car",
    "outletId": "castel-romano",
    "transportType": "car",
    "title": "Car from Rome",
    "duration": "About 30 min from Rome",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information positions Castel Romano Designer Outlet about 30 minutes from Rome; follow official directions to Via Ponte di Piscina Cupa.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "castel-romano-parking",
    "outletId": "castel-romano",
    "transportType": "car",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Castel Romano Designer Outlet; follow parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "castel-romano-shuttle",
    "outletId": "castel-romano",
    "transportType": "bus",
    "title": "Shuttle from Termini or EUR Fermi",
    "duration": "Termini departures 09:30, 10:30, 11:30, 12:30; EUR Fermi departures 10:00, 11:00, 12:00, 13:00",
    "cost": "€18 return from Termini or €13 return from EUR Fermi; free under 10",
    "tip": "Official McArthurGlen/Cilia shuttle information lists daily departures from Termini and EUR Fermi, with return departures from Castel Romano from 16:30; verify same-day service on the official page.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "castel-romano-train-bus",
    "outletId": "castel-romano",
    "transportType": "train",
    "title": "Trenitalia train + bus Outlet Link",
    "duration": "≈30–45 min bus segment from Roma Termini (estimated)",
    "cost": "Check Trenitalia combined fare",
    "tip": "Trenitalia officially lists Castel Romano Designer Outlet Link as a train plus bus service from Roma Termini, with buses departing from Via Giolitti 48.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "castel-romano-airport",
    "outletId": "castel-romano",
    "transportType": "airport",
    "title": "Rome airports via Termini/EUR or road transfer",
    "duration": "≈25-40 min by car from Fiumicino or Ciampino; airport rail/bus + outlet shuttle via Rome (estimated)",
    "cost": "Confirm airport train/bus plus outlet shuttle or taxi fare",
    "tip": "Use official Rome airport ground transport to reach Termini/EUR for the official outlet shuttle, or book an airport taxi/transfer; no dedicated airport-to-outlet shuttle is published.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "fidenza-coach",
    "outletId": "fidenza-village",
    "transportType": "bus",
    "title": "Coach service from Milan",
    "duration": "1 hr 30 min from Milan Piazza della Repubblica",
    "cost": "€10 adult; €5 children 5–11; free infants 0–4",
    "tip": "The official Shopping Express page lists a 9:45 departure from Milan and 11:15 arrival at Fidenza Village, returning 17:00 to 18:30; book on the official channel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "fidenza-car",
    "outletId": "fidenza-village",
    "transportType": "car",
    "title": "Car via A1 motorway",
    "duration": "About 60 min from Milan or Bologna; about 20 min from Parma",
    "cost": "Varies by route and provider",
    "tip": "Official destination information places Fidenza Village near the A1 Milan-Bologna motorway at Fidenza/Salsomaggiore Terme, with access from Milan, Bologna and Parma.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "fidenza-parking",
    "outletId": "fidenza-village",
    "transportType": "car",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Use the official Village directions and on-site signage for the complimentary parking areas; confirm any special parking arrangements with Guest Services.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "fidenza-train",
    "outletId": "fidenza-village",
    "transportType": "train",
    "title": "Train to Fidenza station + local transfer",
    "duration": "≈60–90 min from Milan or Bologna by rail; last-mile transfer varies (estimated)",
    "cost": "Check official Trenitalia fare; last-mile fare varies",
    "tip": "Use official Trenitalia services to Fidenza station, then confirm the current local bus, taxi or Village transfer option with official local transport or Concierge before travelling.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "fidenza-private-transfer",
    "outletId": "fidenza-village",
    "transportType": "taxi",
    "title": "Private chauffeur transfer",
    "duration": "≈60 min from Milan or Bologna (estimated)",
    "cost": "Confirm with Concierge",
    "tip": "Fidenza Village officially offers chauffeur booking via Concierge with at least 24 hours' notice; provide transfer details when reserving.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "fidenza-airport",
    "outletId": "fidenza-village",
    "transportType": "airport",
    "title": "Milan/Bologna airports by car or rail + coach",
    "duration": "≈60-90 min by car from Milan Linate, Malpensa or Bologna airports (estimated)",
    "cost": "Confirm airport rail, coach, taxi or transfer fare",
    "tip": "Use official airport ground transport to reach Milan for the official Shopping Express or continue by rail/car; no dedicated airport-to-village shuttle is published.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "la-reggia-car",
    "outletId": "la-reggia",
    "transportType": "car",
    "title": "Car via A1 Caserta Sud",
    "duration": "≈20–30 min from Naples; ≈15 min from Caserta",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen information says La Reggia is adjacent to the A1 motorway at Caserta Sud and about 20 minutes from Naples; check traffic before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "la-reggia-parking",
    "outletId": "la-reggia",
    "transportType": "car",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list more than 3,000 free parking spaces at La Reggia Designer Outlet.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "la-reggia-public-transport",
    "outletId": "la-reggia",
    "transportType": "bus",
    "title": "Public transport via Naples or Caserta",
    "duration": "≈35–50 min from Naples; ≈20–30 min from Caserta (estimated)",
    "cost": "≈€3–8 (estimated)",
    "tip": "McArthurGlen lists public transport for La Reggia but does not publish current route details or fares on the access page; use the official local transport provider timetable before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "la-reggia-shuttle",
    "outletId": "la-reggia",
    "transportType": "shuttle",
    "title": "Shuttle service from Naples",
    "duration": "Naples departures around 10:00 and 15:30 by stop; return about 19:00",
    "cost": "Confirm with official booking provider",
    "tip": "McArthurGlen's access page lists a Naples shuttle service; current booking pages list Naples pickup points including Municipio, Piazza Vittoria, Molo Beverello and Naples Central Station. Confirm times, fare and operating dates before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "la-reggia-train-bus",
    "outletId": "la-reggia",
    "transportType": "train",
    "title": "Train to Caserta + official outlet bus link",
    "duration": "≈75–90 min from Naples by train + bus (estimated)",
    "cost": "Check Trenitalia/official local transport fare",
    "tip": "Use official rail to Caserta and the officially referenced public-transport/Outlet Link connection toward La Reggia; verify current bus departures and ticketing before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "la-reggia-airport",
    "outletId": "la-reggia",
    "transportType": "airport",
    "title": "Naples Airport road transfer or city connection",
    "duration": "≈20-35 min by car from Naples Airport (estimated)",
    "cost": "Confirm airport taxi, rental-car or transfer fare",
    "tip": "Use official Naples Airport ground transport for taxi, rental car or bus into Naples before onward outlet transport; no dedicated airport-to-outlet shuttle is published.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "noventa-car",
    "outletId": "noventa",
    "transportType": "car",
    "title": "Car to Noventa di Piave",
    "duration": "30 min from Venice by car",
    "cost": "Varies by route and provider",
    "tip": "Use the official McArthurGlen directions for Noventa di Piave Designer Outlet and confirm traffic conditions before leaving Venice or nearby airports.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "noventa-parking",
    "outletId": "noventa",
    "transportType": "car",
    "title": "Outlet parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official outlet information lists parking and may announce extra parking with free shuttle during busy dates; check the official plan-your-visit page before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "noventa-atvo-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO direct bus from Venice and Mestre",
    "duration": "90 min from Venice Piazzale Roma; 75 min from Mestre",
    "cost": "€9.20 return; free under 6",
    "tip": "ATVO and McArthurGlen officially list direct Venice, Mestre and airport buses to Noventa di Piave Designer Outlet with a published return fare; check the current ATVO timetable before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "noventa-train-bus",
    "outletId": "noventa",
    "transportType": "train",
    "title": "Train to Venezia Mestre + ATVO/Outlet Link bus",
    "duration": "Train to Mestre + under 1 hr bus to the outlet",
    "cost": "Check Trenitalia combined fare or ATVO fare",
    "tip": "Trenitalia officially sells Noventa di Piave Designer Outlet Link as train plus bus via Venezia Mestre; ATVO also lists Mestre Railway Station as a direct-bus stop. Verify the current timetable before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "noventa-airport-bus",
    "outletId": "noventa",
    "transportType": "bus",
    "title": "ATVO airport connection",
    "duration": "55 min from Venice Marco Polo Airport",
    "cost": "€9.20 return on outlet service; confirm airport fare rules with ATVO",
    "tip": "ATVO official outlet service information lists Marco Polo Airport as an intermediate stop; confirm current airport stops, times and ticket validity with ATVO.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "noventa-airport",
    "outletId": "noventa",
    "transportType": "airport",
    "title": "Venice Marco Polo / Treviso airport ATVO access",
    "duration": "≈30-45 min from Venice Marco Polo or Treviso Airport by car; ATVO bus check official timetable",
    "cost": "Check official ATVO fare or airport taxi/transfer fare",
    "tip": "ATVO and the outlet officially list airport bus access serving Noventa di Piave; verify current airport stop, dates and timetable before travel.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "serravalle-car",
    "outletId": "serravalle-designer-outlet",
    "transportType": "car",
    "title": "Car from Milan, Genoa or Turin",
    "duration": "About 1 hr from Milan, 45 min from Genoa, under 90 min from Turin",
    "cost": "Varies by route and provider",
    "tip": "Official McArthurGlen directions list convenient road access from Milan, Genoa and Turin; check traffic and route conditions before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "serravalle-parking",
    "outletId": "serravalle-designer-outlet",
    "transportType": "car",
    "title": "Free parking at the outlet",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "Official services list free parking at Serravalle Designer Outlet; follow outlet parking signage on arrival.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "serravalle-shuttle",
    "outletId": "serravalle-designer-outlet",
    "transportType": "shuttle",
    "title": "Daily shuttle from Milan",
    "duration": "≈90 min from Milan by official coach (estimated)",
    "cost": "€25 return; €10 children 4–12; free under 4",
    "tip": "Official McArthurGlen Bus Connection information lists daily Zani Viaggi and Frigerio Viaggi departures from Milan Centrale, Cairoli, Brera, Cadorna, Buenos Aires and Navigli, with the published return fare; book through the official partner link and confirm the selected departure.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "serravalle-genoa-bus",
    "outletId": "serravalle-designer-outlet",
    "transportType": "bus",
    "title": "FlixBus from Genoa",
    "duration": "≈35–50 min from Genoa (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Official McArthurGlen Bus Connection information lists daily FlixBus services from Genova Fanti d’Italia to Serravalle; fare varies by travel date, so book and verify the exact stop with FlixBus.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "serravalle-train-bus",
    "outletId": "serravalle-designer-outlet",
    "transportType": "train",
    "title": "Trenitalia train + Outlet Link bus",
    "duration": "≈90–120 min from Milan depending on connection (estimated)",
    "cost": "Check Trenitalia combined fare",
    "tip": "McArthurGlen lists the Trenitalia Serravalle Designer Outlet LINK as a combined train plus bus ticket from Serravalle Scrivia, Arquata Scrivia and Novi Ligure stations; select 'Serravalle Outlet' in Trenitalia channels for the current combined itinerary.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "serravalle-airports",
    "outletId": "serravalle-designer-outlet",
    "transportType": "airport",
    "title": "Nearby airports by car or transfer",
    "duration": "≈60–90 min from Milan airports or Genoa Airport (estimated)",
    "cost": "Confirm with provider",
    "tip": "Official McArthurGlen plan-your-visit information flags nearby airports and private transfer options, but does not publish airport transfer fares; confirm pickup point, price and timing with the chosen provider.",
    "status": "active",
    "displayOrder": "6"
  },
  {
    "transportationId": "firenze-car",
    "outletId": "the-mall-firenze",
    "transportType": "car",
    "title": "Car via A1 Incisa-Reggello",
    "duration": "≈30–45 min from Florence by car",
    "cost": "Varies by route and provider",
    "tip": "The Mall Firenze official visit page lists Via Europa 8, Leccio Reggello, and directions to leave the motorway at Incisa-Reggello; check traffic before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "firenze-parking",
    "outletId": "the-mall-firenze",
    "transportType": "car",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Free parking",
    "tip": "The Mall Firenze official visit page lists the outlet address and Google directions; use on-site signage for the customer parking areas when arriving by car.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "firenze-direct-bus",
    "outletId": "the-mall-firenze",
    "transportType": "bus",
    "title": "The Mall by Bus from Florence",
    "duration": "≈50–60 min from Florence (estimated)",
    "cost": "€9.50 one-way or €18 return",
    "tip": "Busitalia officially operates The Mall by Bus from Piazzale Montelungo near Firenze Santa Maria Novella to The Mall Firenze, with published fares and same-day return validity; confirm the current timetable before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "firenze-train-taxi",
    "outletId": "the-mall-firenze",
    "transportType": "train",
    "title": "Train to Rignano sull'Arno-Reggello + taxi",
    "duration": "≈35–50 min train and taxi from Florence (estimated)",
    "cost": "≈€8–15 (estimated)",
    "tip": "Use official Trenitalia services from Firenze Santa Maria Novella to Rignano sull'Arno-Reggello, then a short local taxi or arranged transfer to The Mall Firenze; confirm taxi availability for the last-mile segment.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "firenze-airport",
    "outletId": "the-mall-firenze",
    "transportType": "airport",
    "title": "Florence Airport by car or taxi",
    "duration": "≈35–50 min from Florence Airport (estimated)",
    "cost": "Confirm with provider",
    "tip": "The Mall Firenze travel guide places Florence Airport about 45 km from the outlet; use the airport's official taxi or transfer providers and confirm the fare before departure.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "valdichiana-village-car-parking",
    "outletId": "valdichiana-village",
    "transportType": "car",
    "title": "Car to Foiano della Chiana",
    "duration": "≈60–75 min from Florence; ≈35–45 min from Arezzo (estimated)",
    "cost": "Parking available; fuel and tolls vary",
    "tip": "Official Valdichiana Designer Village information lists the centre at Via Enzo Ferrari 5, Foiano della Chiana; use the official directions link and local signage for parking.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "valdichiana-village-train-bus",
    "outletId": "valdichiana-village",
    "transportType": "train",
    "title": "Train to Arezzo + LS5 bus",
    "duration": "50 min bus from Arezzo Terminal Tiemme to Valdichiana Designer Village",
    "cost": "Check Trenitalia and Autolinee Toscane fares",
    "tip": "Official directions list train access to Arezzo station, then Tiemme/Autolinee Toscane LS5 bus from Arezzo Terminal to Valdichiana Designer Village.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "valdichiana-village-bus",
    "outletId": "valdichiana-village",
    "transportType": "bus",
    "title": "Autolinee Toscane LS5 bus",
    "duration": "50 min from Arezzo Terminal Tiemme",
    "cost": "Check Autolinee Toscane fare",
    "tip": "Official directions identify LS5 Arezzo-Foiano-Bettolle as the public bus route serving Valdichiana Designer Village; verify current departure times before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "valdichiana-village-airports",
    "outletId": "valdichiana-village",
    "transportType": "airport",
    "title": "Florence or Perugia airport access",
    "duration": "≈70–90 min from Florence Airport; ≈60–80 min from Perugia Airport (estimated)",
    "cost": "Confirm rental car, taxi or transfer fare",
    "tip": "Use official airport ground transport or rental car channels, then drive to Foiano della Chiana; no official dedicated airport shuttle is published on the outlet directions page.",
    "status": "active",
    "displayOrder": "4"
  },

  {
    "transportationId": "palmanova-car-parking",
    "outletId": "palmanova-designer-village",
    "transportType": "car",
    "title": "Car via A4 Palmanova exit",
    "duration": "25 min from Udine; ≈35-45 min from Trieste; ≈75-90 min from Venice (estimated)",
    "cost": "Parking available; fuel and tolls vary",
    "tip": "The official directions page says Palmanova Designer Village is just 25 minutes from Udine and sits near the A4 Palmanova exit linking Venice, Trieste and Austria.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "palmanova-train-cervignano",
    "outletId": "palmanova-designer-village",
    "transportType": "train",
    "title": "Train to Cervignano-Aquileia-Grado + taxi/car",
    "duration": "Train varies + 13 min / 12 km by car from station",
    "cost": "Check Trenitalia fare; taxi/transfer extra",
    "tip": "The official directions page lists public transport by train to Cervignano-Aquileia-Grado station, then continuing 12 km / 13 minutes by car to the Village; verify Trenitalia times before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "palmanova-bus-fvg",
    "outletId": "palmanova-designer-village",
    "transportType": "bus",
    "title": "TPL FVG regional bus toward Palmanova/Aiello del Friuli",
    "duration": "Regional bus times vary; plan with TPL FVG",
    "cost": "Check official TPL FVG fare",
    "tip": "Use official TPL FVG journey planning for regional buses serving Palmanova or Aiello del Friuli, then complete the last mile by local taxi or on foot where practical; services vary by route and day.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "palmanova-airports",
    "outletId": "palmanova-designer-village",
    "transportType": "airport",
    "title": "Trieste or Venice airport access",
    "duration": "≈20-30 min from Trieste Airport; ≈75-90 min from Venice Airport by car (estimated)",
    "cost": "Confirm with airport taxi, rental-car or transfer provider",
    "tip": "Use official Trieste Airport or Venice Airport ground-transport channels for rental cars, taxis or transfers; no official dedicated outlet airport shuttle is published.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "franciacorta-car",
    "outletId": "franciacorta-designer-village",
    "transportType": "car",
    "title": "Car to Rodengo Saiano",
    "duration": "≈15-25 min from Brescia; traffic varies",
    "cost": "Fuel, tolls and provider costs vary",
    "tip": "Use the official Franciacorta Designer Village directions to Via del Borgo 1, Rodengo Saiano; check traffic before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "franciacorta-parking",
    "outletId": "franciacorta-designer-village",
    "transportType": "car",
    "title": "On-site parking",
    "duration": "On site",
    "cost": "Check centre parking information",
    "tip": "Arrive by car using the official Village directions and follow on-site parking signage; confirm any parking restrictions on the official page before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "franciacorta-train-brescia",
    "outletId": "franciacorta-designer-village",
    "transportType": "train",
    "title": "Train to Brescia + LS029 bus",
    "duration": "46 min from Milano Centrale or 30 min from Verona Porta Nuova to Brescia, then 25 min by bus",
    "cost": "Check official Trenitalia and bus fares",
    "tip": "The official directions page lists trains to Brescia from Milano Centrale, Verona Porta Nuova and Iseo, then bus line LS029 from Brescia SIA Station; verify current timetables before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "franciacorta-bus-ls029",
    "outletId": "franciacorta-designer-village",
    "transportType": "bus",
    "title": "Brescia SIA Station bus LS029",
    "duration": "25 min from Brescia SIA Station",
    "cost": "Check official bus fare",
    "tip": "Use the officially listed LS029 Brescia - Ome - Monticelli - Brusati bus from Brescia SIA Station; check operator timetable and stop details before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "franciacorta-airport",
    "outletId": "franciacorta-designer-village",
    "transportType": "airport",
    "title": "Bergamo, Milan or Verona airport access",
    "duration": "Airport rail/bus via Brescia or road transfer; timing varies",
    "cost": "Check official airport, rail, bus or transfer fare",
    "tip": "Use official airport ground transport to reach Brescia/Milan/Verona rail or bus connections, then continue with the official train plus LS029 route; no dedicated airport-to-village shuttle was verified.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "mantova-car",
    "outletId": "mantova-village",
    "transportType": "car",
    "title": "Car via SP 413 or A22",
    "duration": "13 km / 15 min from Mantova station without traffic; 48 km / 31 min from Verona Porta Nuova without traffic",
    "cost": "Fuel, tolls and provider costs vary",
    "tip": "Official Mantova Village directions list SP 413 from Mantova and the A22 toll motorway from Verona; check traffic before departure.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "mantova-parking",
    "outletId": "mantova-village",
    "transportType": "car",
    "title": "Village parking",
    "duration": "On site",
    "cost": "Check centre parking information",
    "tip": "Use official Mantova Village directions to arrive by car and follow on-site parking signage; confirm parking details with the centre before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "mantova-train-car",
    "outletId": "mantova-village",
    "transportType": "train",
    "title": "Train to Mantova or Verona + road transfer",
    "duration": "Train varies + 13 km from Mantova station or 48 km from Verona Porta Nuova",
    "cost": "Check Trenitalia fare; taxi/car cost varies",
    "tip": "The official directions page lists Trenitalia to Mantova station or Verona Porta Nuova, then continuing by SP 413/A22 by car or taxi; verify rail and transfer availability before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "mantova-train-bus",
    "outletId": "mantova-village",
    "transportType": "bus",
    "title": "Train + Bus from Mantova station",
    "duration": "Check official APAM/rail timetable",
    "cost": "Check official APAM and Trenitalia fares",
    "tip": "Mantova Village's official page includes a Train + Bus option from Mantova station; use official APAM and Trenitalia timetables for current lines, times and fares before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "mantova-airport",
    "outletId": "mantova-village",
    "transportType": "airport",
    "title": "Verona Airport via Verona or road transfer",
    "duration": "Airport bus/rail via Verona + road transfer; timing varies",
    "cost": "Check official airport, rail, bus or transfer fare",
    "tip": "Use official Verona Airport ground transport toward Verona Porta Nuova, then continue by the official Mantova Village Verona route; no dedicated airport-to-village shuttle was verified.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "vicolungo-car-parking",
    "outletId": "vicolungo-the-style-outlets",
    "transportType": "car",
    "title": "By Car / Parking",
    "duration": "Use A4/A26 Biandrate-Vicolungo area",
    "cost": "Check official parking information",
    "tip": "The official outlet page lists car access to Piazza S. Caterina / Via Papa Giovanni XXIII. Follow official directions and check current parking information before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "vicolungo-cavourese-shuttle",
    "outletId": "vicolungo-the-style-outlets",
    "transportType": "shuttle",
    "title": "Cavourese shuttle from Milan / Novara",
    "duration": "Check official Cavourese timetable",
    "cost": "Check official Cavourese fare",
    "tip": "Official operator Cavourese publishes Vicolungo Outlet Bus service from Milan and Novara on selected days. Book ahead and check the official timetable/fare before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "vicolungo-airport-malpensa",
    "outletId": "vicolungo-the-style-outlets",
    "transportType": "airport",
    "title": "Milan Malpensa Airport",
    "duration": "About 33 km by road",
    "cost": "Check onward transport fare",
    "tip": "Milan Malpensa is the nearest major airport listed for this outlet; continue by car, taxi/confirmed transfer, or official rail/bus via Novara/Milan. No dedicated airport shuttle was verified.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "castel-guelfo-car-parking",
    "outletId": "castel-guelfo-the-style-outlets",
    "transportType": "car",
    "title": "By Car / Parking",
    "duration": "A14 exit Castel San Pietro Terme",
    "cost": "Check official parking information",
    "tip": "The official outlet pages list Via del Commercio 4/2 and A14 Bologna-Ancona, exit Castel San Pietro Terme. Follow official directions and check current parking information before travel.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "castel-guelfo-train-shuttle",
    "outletId": "castel-guelfo-the-style-outlets",
    "transportType": "train",
    "title": "Train to Castel San Pietro Terme + shuttle",
    "duration": "Check Trenitalia and shuttle timetable",
    "cost": "Check official train fare; shuttle terms may vary",
    "tip": "Use Trenitalia to Castel San Pietro Terme, then only use a current official outlet/operator shuttle if published for your travel date. Check official timetable/fare before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "castel-guelfo-bus-205",
    "outletId": "castel-guelfo-the-style-outlets",
    "transportType": "bus",
    "title": "TPER regional bus",
    "duration": "Check official TPER timetable",
    "cost": "Check official TPER fare",
    "tip": "Use official TPER journey planning for buses serving the Castel Guelfo outlet area; verify the route, stop, timetable, and fare before travel.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "castel-guelfo-airport-bologna",
    "outletId": "castel-guelfo-the-style-outlets",
    "transportType": "airport",
    "title": "Bologna Airport",
    "duration": "About 35 km by road",
    "cost": "Check onward transport fare",
    "tip": "From Bologna Airport, continue by car, taxi/confirmed transfer, or official public transport via Bologna and Castel San Pietro Terme. No dedicated airport shuttle was verified.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "puglia-village-car-parking",
    "outletId": "puglia-village",
    "transportType": "car",
    "title": "Car to Molfetta / on-site parking",
    "duration": "SS16 from Bari Airport: 21 min without traffic",
    "cost": "Parking available; fuel, tolls and provider costs vary",
    "tip": "The official Puglia Village directions list Via dei Portuali 12 in Molfetta, Bari Airport via SS16, and parking areas A-B-C-D-E-F; follow official directions and on-site signage.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "puglia-village-train-bus",
    "outletId": "puglia-village",
    "transportType": "train",
    "title": "Train to Molfetta + local bus",
    "duration": "16-30 min train from Bari Centrale + 33 min bus without traffic",
    "cost": "Check official Trenitalia and MTM Molfetta fares",
    "tip": "Official directions list Trenitalia from Bari Centrale to Molfetta station, then MTM Molfetta Line 4 or Line 6 from Molfetta station to Puglia Village; verify current timetables before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "puglia-village-shuttle-bari",
    "outletId": "puglia-village",
    "transportType": "shuttle",
    "title": "Shuttle bus from Bari",
    "duration": "Check official shuttle timetable",
    "cost": "Check official booking terms",
    "tip": "Puglia Village officially lists shuttle bus stops at Bari Central Station, Corso Vittorio Emanuele II and the Port of Bari; use the official timetable link before travelling.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "puglia-village-taxi",
    "outletId": "puglia-village",
    "transportType": "taxi",
    "title": "Taxi booking via Info Point",
    "duration": "Timing varies by pickup point",
    "cost": "Confirm fare with provider",
    "tip": "The official Puglia Village page says the Info Point can help with directions or taxi booking; contact the centre before travel for current availability.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "puglia-village-airport-bari",
    "outletId": "puglia-village",
    "transportType": "airport",
    "title": "Bari Airport by road",
    "duration": "21 min without traffic via SS16 from Bari Airport",
    "cost": "Confirm airport taxi, rental-car or transfer fare",
    "tip": "Official directions list Bari Airport 27 km away and SS16 road access to Puglia Village; use official airport ground transport or rental car channels.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "sicilia-outlet-village-car-parking",
    "outletId": "sicilia-outlet-village",
    "transportType": "car",
    "title": "Car via A19 Dittaino-Outlet exit",
    "duration": "30 min from Catania or Enna; 70 min from Palermo or Taormina",
    "cost": "Large free parking available; fuel and tolls vary",
    "tip": "The official find-us page places the Village on the A19 Palermo-Catania highway at the Dittaino-Outlet exit and lists large free visitor parking.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "sicilia-outlet-village-bus",
    "outletId": "sicilia-outlet-village",
    "transportType": "bus",
    "title": "Public bus with Interbus or Sais Autolinee",
    "duration": "Check official operator timetable",
    "cost": "Check official Interbus or Sais fare",
    "tip": "Sicilia Outlet Village officially points visitors to Interbus and Sais Autolinee for public-bus schedules and bookings; verify the current route and stop before travel.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "sicilia-outlet-village-shuttle",
    "outletId": "sicilia-outlet-village",
    "transportType": "shuttle",
    "title": "Outlet shuttle from Sicily destinations",
    "duration": "Weekly departures; timetable varies by route",
    "cost": "Check official route booking page",
    "tip": "The official page lists shuttle routes from Palermo, Messina, the Taormina Coast and Cefalù with dedicated booking/timetable pages; book only after checking the official route page.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "sicilia-outlet-village-taxi-transfer",
    "outletId": "sicilia-outlet-village",
    "transportType": "taxi",
    "title": "Taxi or private transfer",
    "duration": "Timing varies by pickup point",
    "cost": "Confirm fare with provider",
    "tip": "Sicilia Outlet Village officially says taxi or NCC private transfer can be booked from any location in Sicily, with Info Point assistance by email.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "sicilia-outlet-village-airport",
    "outletId": "sicilia-outlet-village",
    "transportType": "airport",
    "title": "Catania or Palermo airport via Sais Autolinee",
    "duration": "About 30 min from Catania Airport; about 70 min from Palermo Airport",
    "cost": "Check official Sais Autolinee fare",
    "tip": "The official find-us page states Catania and Palermo airports are connected to the Village by Sais Autolinee bus service; confirm airport stop and timetable before travel.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "scalo-milano-car-parking",
    "outletId": "scalo-milano-outlet-more",
    "transportType": "car",
    "title": "Car or motorcycle from Milan",
    "duration": "15 min from central Milan",
    "cost": "Free covered and uncovered parking; fuel and provider costs vary",
    "tip": "Official Scalo Milano directions list Via Milano 5, Locate Triulzi, route via SS 412 Val Tidone, and large free covered and uncovered parking on arrival.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "scalo-milano-shuttle",
    "outletId": "scalo-milano-outlet-more",
    "transportType": "shuttle",
    "title": "Shuttle bus from Milan",
    "duration": "Departures from Milan at 10:00, 14:45 and 17:30; returns at 13:30, 16:00 and 19:00",
    "cost": "Free booking with current official promo code; verify terms",
    "tip": "Official Scalo Milano shuttle information lists stops at Piazza della Repubblica, Via Lorenzini/Fondazione Prada and Via Ripamonti/IEO; reserve on the official linked booking channel and verify current promo-code validity.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "scalo-milano-train",
    "outletId": "scalo-milano-outlet-more",
    "transportType": "train",
    "title": "S13 train to Locate Triulzi",
    "duration": "Station is a few steps from Gate 1",
    "cost": "Check official rail fare",
    "tip": "The official directions page says Scalo Milano is served by Locate Triulzi station near Gate 1 on the Passante Ferroviario S13, with metro interchanges at Porta Venezia, Porta Garibaldi, Repubblica and Rogoredo.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "scalo-milano-bus",
    "outletId": "scalo-milano-outlet-more",
    "transportType": "bus",
    "title": "ATM and regional buses",
    "duration": "Check official operator timetable",
    "cost": "Check official fare",
    "tip": "Official Scalo Milano directions list ATM 220 Locate di Triulzi-Rozzano plus lines 94 Pavia-Milano Romolo and 155 San Zenone Po-Milano Famagosta; verify current stops and timetables before travel.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "scalo-milano-airports",
    "outletId": "scalo-milano-outlet-more",
    "transportType": "airport",
    "title": "Malpensa or Linate airport by road",
    "duration": "Timing varies by airport traffic",
    "cost": "Confirm airport taxi, rental-car or transfer fare",
    "tip": "Official directions provide road routes from Malpensa and Linate airports via Milan's western ring road/A1 toward SS 412 Val Tidone and Locate Triulzi; no dedicated airport shuttle was verified.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "torino-outlet-village-car",
    "outletId": "torino-outlet-village",
    "transportType": "car",
    "title": "Car via Turin-Milan highway",
    "duration": "10 min from Turin city center; 50 min from West Milan",
    "cost": "Fuel, tolls and provider costs vary",
    "tip": "Official directions place Torino Outlet Village near the Turin-Milan highway, with recommended exits Settimo Torinese (A5-A4) or Falchera-Abbadia di Stura (A55), at Via Torino 160-162.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "torino-outlet-village-public-transport",
    "outletId": "torino-outlet-village",
    "transportType": "bus",
    "title": "Tram 4 + GTT bus SE1/SE2",
    "duration": "Bus segment: 4 stops from Stura to Nervi",
    "cost": "Check official GTT fare",
    "tip": "Official directions say to take Tram 4 toward Falchera to Stura Station, then GTT bus SE1 or SE2 from the terminus by the Stura multi-storey car park to Nervi.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "torino-outlet-village-train-bus",
    "outletId": "torino-outlet-village",
    "transportType": "train",
    "title": "SFM train to Torino Stura + GTT bus",
    "duration": "9 min train journey from listed Turin stations + 4 bus stops",
    "cost": "Check official Trenitalia/Italo/SFM and GTT fares",
    "tip": "Official directions list SFM lines 1, 2, 4, 6 or 7 from Torino Lingotto, Porta Susa or Rebaudengo to Torino Stura, then GTT SE1 or SE2 to Nervi.",
    "status": "active",
    "displayOrder": "3"
  },
  {
    "transportationId": "torino-outlet-village-airport-taxi",
    "outletId": "torino-outlet-village",
    "transportType": "airport",
    "title": "Turin Airport by taxi",
    "duration": "About 15 min from Turin Airport",
    "cost": "Confirm taxi fare with provider",
    "tip": "The official find-us page states Turin Airport is linked to Torino Outlet Village by taxi service in about 15 minutes.",
    "status": "active",
    "displayOrder": "4"
  },
  {
    "transportationId": "torino-outlet-village-private-transfer",
    "outletId": "torino-outlet-village",
    "transportType": "taxi",
    "title": "Private transfer on request",
    "duration": "Timing varies by pickup point",
    "cost": "Confirm with the outlet",
    "tip": "Torino Outlet Village officially offers private transfer on request; contact the outlet email or phone number listed on the official find-us page for booking information.",
    "status": "active",
    "displayOrder": "5"
  },
  {
    "transportationId": "mondovicino-outlet-village-car",
    "outletId": "mondovicino-outlet-village",
    "transportType": "car",
    "title": "Car via A6 Mondovì exit",
    "duration": "A6 Torino-Savona exit Mondovì; timing varies by origin",
    "cost": "Fuel, tolls and provider costs vary",
    "tip": "Official Mondovicino directions list A6 Torino-Savona exit Mondovì from Turin or Savona, SS28 from Cuneo, SP12 from the Langhe, and A10 then A6 from the Côte d'Azur.",
    "status": "active",
    "displayOrder": "1"
  },
  {
    "transportationId": "mondovicino-outlet-village-train-bus",
    "outletId": "mondovicino-outlet-village",
    "transportType": "train",
    "title": "Train to Mondovì + urban circular bus",
    "duration": "Check official urban circular timetable",
    "cost": "Check official train and bus fares",
    "tip": "Official Mondovicino directions say the outlet is connected to Mondovì railway station by the urban circular transport system and link to the current weekday/holiday timetable.",
    "status": "active",
    "displayOrder": "2"
  },
  {
    "transportationId": "mondovicino-outlet-village-airports",
    "outletId": "mondovicino-outlet-village",
    "transportType": "airport",
    "title": "Cuneo, Turin, Genoa, Malpensa or Nice airports by car",
    "duration": "30 min from Cuneo; 1 hr from Turin; 1 hr 30 min from Genoa; 2 hr 30 min from Milan Malpensa or Nice",
    "cost": "Confirm airport taxi, rental-car or transfer fare",
    "tip": "The official directions page lists car access from Cuneo, Turin, Genoa, Milan Malpensa and Nice airports; no dedicated airport shuttle was verified.",
    "status": "active",
    "displayOrder": "3"
  }
];
