export const turkeyTransportation = [
  {
    transportationId: "viaport-asia-outlet-shopping-car-parking",
    outletId: "viaport-asia-outlet-shopping",
    transportType: "car",
    title: "By Car / Free Parking",
    duration: "",
    cost: "Free parking",
    tip: "Use Yenişehir Mahallesi, Dedepaşa Caddesi No:19, Pendik; Viaport Asia confirms free parking.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "olivium-outlet-center-marmaray-kazlicesme",
    outletId: "olivium-outlet-center",
    transportType: "train",
    title: "Marmaray to Kazlıçeşme",
    duration: "About 5 min walk from Kazlıçeşme station",
    cost: "",
    tip: "Use Marmaray to Kazlıçeşme; Olivium's official transport page states the centre is about a 5-minute walk from the station.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "olivium-outlet-center-metrobus-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "bus",
    title: "Metrobüs to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu Metrobüs stop and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "4",
  },
  {
    transportationId: "olivium-outlet-center-m1a-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "metro",
    title: "M1A Metro to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu station on the M1A line and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "olivium-outlet-center-t1-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "metro",
    title: "T1 Tram to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu stop on the T1 tram and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "olivium-outlet-center-bus-lines",
    outletId: "olivium-outlet-center",
    transportType: "bus",
    title: "Municipal Bus Lines 93, 93C, 93M, 93T, BN3, MR11, MR20 and 97E",
    duration: "",
    cost: "",
    tip: "Olivium's official transport page lists lines 93, 93C, 93M, 93T, BN3, MR11, MR20 and 97E; check İETT for the current stop and timetable.",
    status: "active",
    displayOrder: "5",
  },
  {
    transportationId: "olivium-outlet-center-car",
    outletId: "olivium-outlet-center",
    transportType: "car",
    title: "By Car",
    duration: "",
    cost: "",
    tip: "Use Prof. Dr. Muammer Aksoy Cad. No:30, Zeytinburnu for navigation.",
    status: "active",
    displayOrder: "6",
  },
  {
    transportationId: "starcity-outlet-m9-dogu-sanayi",
    outletId: "starcity-outlet",
    transportType: "metro",
    title: "M9 Metro to Doğu Sanayi",
    duration: "About 500 m walk from Doğu Sanayi station",
    cost: "",
    tip: "Use the Ataköy–Olimpiyat M9 line and alight at Doğu Sanayi; StarCity's official transport page places the outlet about 500 metres from the station.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "starcity-outlet-minibus-sirinevler-sefakoy",
    outletId: "starcity-outlet",
    transportType: "bus",
    title: "Minibus from Şirinevler or Küçükçekmece",
    duration: "",
    cost: "",
    tip: "StarCity's official transport page lists the Şirinevler–Yenibosna and Küçükçekmece–Sefaköy minibus connections; check current service details before travel.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "starcity-outlet-car-parking",
    outletId: "starcity-outlet",
    transportType: "car",
    title: "By Car / Free Parking",
    duration: "",
    cost: "Free parking",
    tip: "Use Yenibosna Merkez Mahallesi, Değirmenbahçe Caddesi No:34, Bahçelievler; StarCity lists free parking as a service.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "venezia-mega-outlet-car",
    outletId: "venezia-mega-outlet",
    transportType: "car",
    title: "By Car",
    duration: "",
    cost: "",
    tip: "Use Karadeniz Mahallesi, Eski Edirne Asfaltı Caddesi No:408, Gaziosmanpaşa for navigation.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "venezia-mega-outlet-taxi",
    outletId: "venezia-mega-outlet",
    transportType: "taxi",
    title: "Venezia Mega Taxi / Karadeniz Taxi",
    duration: "",
    cost: "",
    tip: "Venezia Mega Outlet's services page lists Venezia Mega Taxi and Karadeniz Taxi; confirm pickup and fare directly with the provider.",
    status: "active",
    displayOrder: "2",
  },
];
