export const turkeyTransportation = [
  {
    transportationId: "viaport-asia-outlet-shopping-iett-bus-lines",
    outletId: "viaport-asia-outlet-shopping",
    transportType: "bus",
    title: "İETT Bus Lines 132K, KM25, KM27, 16KH, 134 and 130H",
    duration: "",
    cost: "",
    tip: "Viaport Asia's official İETT page lists lines 132K, KM25, KM27, 16KH, 134 and 130H; verify current stops and schedules with İETT.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "viaport-asia-outlet-shopping-minibus-routes",
    outletId: "viaport-asia-outlet-shopping",
    transportType: "bus",
    title: "Public Minibuses to Viaport Asia",
    duration: "",
    cost: "",
    tip: "Viaport Asia's official minibus page lists Pendik–Kurtköy–Viaport, Pendik–Velibaba–Viaport, Kartal–Sultanbeyli–Viaport, Dudullu–Yedpa–Viaport and Çekmeköy–Madenler–Viaport.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "viaport-asia-outlet-shopping-car-parking",
    outletId: "viaport-asia-outlet-shopping",
    transportType: "car",
    title: "By Car / Free Parking",
    duration: "",
    cost: "Free parking",
    tip: "Use Yenişehir Mahallesi, Dedepaşa Caddesi No:19, Pendik; Viaport Asia confirms free parking.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "olivium-outlet-center-marmaray-kazlicesme",
    outletId: "olivium-outlet-center",
    transportType: "train",
    title: "Marmaray to Kazlıçeşme",
    duration: "About 5 min walk from Kazlıçeşme station",
    cost: "",
    tip: "Use Marmaray to Kazlıçeşme; Olivium's official transport page states the centre is about a 5-minute walk from the station.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "olivium-outlet-center-m1a-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "metro",
    title: "M1A Metro to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu station on the M1A line and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "olivium-outlet-center-t1-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "metro",
    title: "T1 Tram to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu stop on the T1 tram and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "olivium-outlet-center-metrobus-zeytinburnu",
    outletId: "olivium-outlet-center",
    transportType: "bus",
    title: "Metrobüs to Zeytinburnu + Bus or Minibus",
    duration: "About 10 min onward by bus or minibus",
    cost: "",
    tip: "Alight at Zeytinburnu Metrobüs stop and continue by the bus or minibus connection identified on Olivium's official transport page.",
    status: "active",
    displayOrder: "4",
  },
  {
    transportationId: "olivium-outlet-center-bus-lines",
    outletId: "olivium-outlet-center",
    transportType: "bus",
    title: "Municipal Bus Lines 93, 93C, 93M, 93T, BN3, MR11, MR20 and 97E",
    duration: "",
    cost: "",
    tip: "Olivium's official transport page lists lines 93, 93C, 93M, 93T, BN3, MR11, MR20 and 97E; check İETT for the current stop and timetable.",
    status: "active",
    displayOrder: "5",
  },
  {
    transportationId: "olivium-outlet-center-ferry-sea-access",
    outletId: "olivium-outlet-center",
    transportType: "ferry",
    title: "Ferry or Sea Bus + Rail Connection",
    duration: "",
    cost: "",
    tip: "Olivium's official transport page lists Kadıköy or Üsküdar ferry to Eminönü, then T1 toward Zeytinburnu; it also lists sea bus to Yenikapı, then Marmaray to Kazlıçeşme.",
    status: "active",
    displayOrder: "6",
  },
  {
    transportationId: "olivium-outlet-center-car",
    outletId: "olivium-outlet-center",
    transportType: "car",
    title: "By Car",
    duration: "",
    cost: "",
    tip: "Use Prof. Dr. Muammer Aksoy Cad. No:30, Zeytinburnu for navigation.",
    status: "active",
    displayOrder: "7",
  },
  {
    transportationId: "starcity-outlet-m9-dogu-sanayi",
    outletId: "starcity-outlet",
    transportType: "metro",
    title: "M9 Metro to Doğu Sanayi",
    duration: "",
    cost: "",
    tip: "Use the Ataköy–Olimpiyat M9 line and alight at Doğu Sanayi; StarCity's official transport page places the outlet about 500 metres from the station.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "starcity-outlet-metrobus-local-connection",
    outletId: "starcity-outlet",
    transportType: "bus",
    title: "Metrobüs + Local Connection",
    duration: "",
    cost: "",
    tip: "Leave the Metrobüs at Şirinevler, Yenibosna or Sefaköy and continue by minibus, municipal bus or the M9 Metro; StarCity does not describe a direct Metrobüs service to the outlet.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "starcity-outlet-iett-bus-lines",
    outletId: "starcity-outlet",
    transportType: "bus",
    title: "İETT Bus Access",
    duration: "",
    cost: "",
    tip: "İETT lines 31, 31E, 36AY, 78B, 79F, 79G, 79K, 79Ş, 89YB, 98B, 98H and 98T serve near Dr. Enver Ören Kültür Merkezi and Alışveriş Merkezi – Bahçelievler; check İETT schedules.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "starcity-outlet-minibus-sirinevler-sefakoy",
    outletId: "starcity-outlet",
    transportType: "bus",
    title: "Minibus from Şirinevler or Küçükçekmece",
    duration: "",
    cost: "",
    tip: "StarCity's official transport page lists the Şirinevler–Yenibosna and Küçükçekmece–Sefaköy minibus connections; check current service details before travel.",
    status: "active",
    displayOrder: "4",
  },
  {
    transportationId: "starcity-outlet-car-parking",
    outletId: "starcity-outlet",
    transportType: "car",
    title: "By Car / Free Parking",
    duration: "",
    cost: "Free parking",
    tip: "Use Yenibosna Merkez Mahallesi, Değirmenbahçe Caddesi No:34, Bahçelievler; StarCity lists free parking as a service.",
    status: "active",
    displayOrder: "5",
  },
  {
    transportationId: "venezia-mega-outlet-t4-kiptas-venezia",
    outletId: "venezia-mega-outlet",
    transportType: "train",
    title: "T4 Tram to Kiptaş–Venezia",
    duration: "",
    cost: "",
    tip: "Take the T4 Topkapı–Habipler / Mescid-i Selam tram and alight at Kiptaş–Venezia.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "venezia-mega-outlet-m7-karadeniz-mahallesi",
    outletId: "venezia-mega-outlet",
    transportType: "metro",
    title: "M7 Metro to Karadeniz Mahallesi",
    duration: "",
    cost: "",
    tip: "Use the Mecidiyeköy–Mahmutbey M7 line and alight at Karadeniz Mahallesi.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "venezia-mega-outlet-metrobus-t4",
    outletId: "venezia-mega-outlet",
    transportType: "bus",
    title: "Metrobüs + T4 Tram Connection",
    duration: "",
    cost: "",
    tip: "Alight at Edirnekapı or Şehitlik and transfer to T4 for Kiptaş–Venezia; the official page also references line 34AS.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "venezia-mega-outlet-marmaray-m1a-t4",
    outletId: "venezia-mega-outlet",
    transportType: "train",
    title: "Marmaray + M1A + T4 Connection",
    duration: "",
    cost: "",
    tip: "From Marmaray Yenikapı, transfer to M1A, alight at Topkapı–Ulubatlı and transfer to T4 for Kiptaş–Venezia.",
    status: "active",
    displayOrder: "4",
  },
  {
    transportationId: "venezia-mega-outlet-iett-bus-lines",
    outletId: "venezia-mega-outlet",
    transportType: "bus",
    title: "İETT Bus Lines to Venezia Mega Outlet",
    duration: "",
    cost: "",
    tip: "The official page lists İETT lines 36A, 36E, 36M, 36V, 36CY, 36EM, 336, 336E, 336M, 336Y and 79KM; check İETT for current stops and schedules.",
    status: "active",
    displayOrder: "5",
  },
  {
    transportationId: "venezia-mega-outlet-car",
    outletId: "venezia-mega-outlet",
    transportType: "car",
    title: "By Car",
    duration: "",
    cost: "",
    tip: "Use Karadeniz Mahallesi, Eski Edirne Asfaltı Caddesi No:408, Gaziosmanpaşa for navigation.",
    status: "active",
    displayOrder: "6",
  },
  {
    transportationId: "venezia-mega-outlet-taxi",
    outletId: "venezia-mega-outlet",
    transportType: "taxi",
    title: "Venezia Mega Taxi / Karadeniz Taxi",
    duration: "",
    cost: "",
    tip: "Venezia Mega Outlet's services page lists Venezia Mega Taxi and Karadeniz Taxi; confirm pickup and fare directly with the provider.",
    status: "active",
    displayOrder: "7",
  },
];
