export const unitedArabEmiratesTransportation = [
  {
    transportationId: "dubai-outlet-mall-rta-bus-66-67",
    outletId: "dubai-outlet-mall",
    transportType: "bus",
    title: "RTA Buses 66 & 67 from Al Ghubaiba",
    duration: "",
    cost: "",
    tip: "Take RTA bus 66 or 67 from Al Ghubaiba Bus Station and alight at Dubai Outlet Mall 01 near the mall’s easternmost entrance. Check the current route, timetable and fare with RTA before travel.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "dubai-outlet-mall-free-hotel-shuttle",
    outletId: "dubai-outlet-mall",
    transportType: "shuttle",
    title: "Free Hotel Shuttle",
    duration: "",
    cost: "Free",
    tip: "Dubai Outlet Mall states that it operates a free shuttle service to various hotels in and around Dubai. Contact the mall’s Tourism Department to confirm the current participating hotel, pickup point, timetable, reservation requirements and return service.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "dubai-outlet-mall-car-parking",
    outletId: "dubai-outlet-mall",
    transportType: "car",
    title: "Car / Parking",
    duration: "",
    cost: "",
    tip: "Drive to Dubai Outlet Mall on Dubai–Al Ain Road, Route 66. The official mall FAQ confirms ample parking facilities; check current access and parking conditions before travel.",
    status: "active",
    displayOrder: "3",
  },
];
