export const unitedArabEmiratesTransportation = [
  {
    transportationId: "dubai-outlet-mall-rta-bus-66",
    outletId: "dubai-outlet-mall",
    transportType: "bus",
    title: "RTA Bus 66 from Al Ghubaiba",
    duration: "",
    cost: "Approx. AED 5–7.50",
    tip: "Take RTA Bus 66 from Al Ghubaiba Bus Station toward Faqa, Terminus and alight at Dubai Outlet Mall 01 near the mall’s easternmost entrance. Confirm the current timetable, return service and nol Silver Card fare with RTA before travel.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "dubai-outlet-mall-free-hotel-shuttle",
    outletId: "dubai-outlet-mall",
    transportType: "shuttle",
    title: "Free Hotel Shuttle",
    duration: "",
    cost: "Free when confirmed with the mall",
    tip: "Dubai Outlet Mall states that it operates a free shuttle service to various hotels in and around Dubai, but participating hotels vary. Contact the mall Tourism Department to confirm the current hotel, pickup point, timetable, reservation requirements and return service before relying on it.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "dubai-outlet-mall-car-parking",
    outletId: "dubai-outlet-mall",
    transportType: "car",
    title: "Car / Parking",
    duration: "",
    cost: "",
    tip: "Drive to Dubai Outlet Mall on Dubai–Al Ain Road, Route 66. The official mall FAQ confirms ample parking facilities; check current access and parking conditions before travel.",
    status: "active",
    displayOrder: "3",
  },
];
