export const unitedArabEmiratesTransportation = [
  {
    transportationId: "dubai-outlet-mall-rta-bus-66",
    outletId: "dubai-outlet-mall",
    transportType: "bus",
    title: "RTA Bus 66 from Al Ghubaiba",
    duration: "",
    cost: "Approx. AED 5–7.50",
    tip: "Take RTA Bus 66 from Al Ghubaiba Bus Station toward Faqa, Terminus and alight at Dubai Outlet Mall 01 near the mall’s easternmost entrance. Confirm the current timetable, return service and nol Silver Card fare with RTA before travel.",
    status: "active",
    displayOrder: "1",
  },
  {
    transportationId: "dubai-outlet-mall-free-hotel-shuttle",
    outletId: "dubai-outlet-mall",
    transportType: "shuttle",
    title: "Free Hotel Shuttle",
    duration: "",
    cost: "Free when confirmed with the mall",
    tip: "Dubai Outlet Mall states that it operates a free shuttle service to various hotels in and around Dubai, but participating hotels vary. Contact the mall Tourism Department to confirm the current hotel, pickup point, timetable, reservation requirements and return service before relying on it.",
    status: "active",
    displayOrder: "2",
  },
  {
    transportationId: "dubai-outlet-mall-car-parking",
    outletId: "dubai-outlet-mall",
    transportType: "car",
    title: "Car / Parking",
    duration: "",
    cost: "",
    tip: "Drive to Dubai Outlet Mall on Dubai–Al Ain Road, Route 66. The official mall FAQ confirms ample parking facilities; check current access and parking conditions before travel.",
    status: "active",
    displayOrder: "3",
  },
  {
    transportationId: "the-outlet-village-car-parking", outletId: "the-outlet-village", transportType: "car",
    title: "Car / Parking", duration: "Approx. 25–65 min from DWC, Ibn Battuta or central Dubai; traffic varies", cost: "Parking is available; fuel and rental costs vary", tip: "Drive to Dubai Parks and Resorts in Jebel Ali and follow signs for The Outlet Village; parking is available at the destination.",
    status: "active", displayOrder: "1",
  },
  {
    transportationId: "the-outlet-village-taxi", outletId: "the-outlet-village", transportType: "taxi",
    title: "Taxi / Ride-hailing", duration: "Approx. 25–65 min, depending on origin and traffic", cost: "Approx. AED 55–190, depending on origin; app fares vary", tip: "Use the official destination pin and confirm the estimated fare before departure; journey time varies materially with Dubai traffic.",
    status: "active", displayOrder: "2",
  },
  {
    transportationId: "the-outlet-village-ibn-battuta-connection", outletId: "the-outlet-village", transportType: "bus",
    title: "Ibn Battuta public-transport connection", duration: "Approx. 35–55 min after boarding; verify current timetable", cost: "Approx. AED 5–7.50 with a standard nol card; confirm current zones/fare", tip: "The official mall FAQ identifies buses from Ibn Battuta Mall Metro Station. Verify the current RTA connection and timetable before travel because the mall does not publish a route number.",
    status: "active", displayOrder: "3",
  },
  {
    transportationId: "the-outlet-village-hotel-shuttle", outletId: "the-outlet-village", transportType: "shuttle",
    title: "Participating hotel shuttle", duration: "Depends on participating hotel, route and stops", cost: "Confirm with participating hotel; inclusion or fee varies", tip: "Some hotels offer a shuttle to the destination. Confirm participation, booking, pickup and return directly with your hotel before relying on it.",
    status: "active", displayOrder: "4",
  },
];
