import type { TransportationGuide } from "./index";

export const austriaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "vienna-to-parndorf-shuttle",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "vienna-city-center",
    transportationType: "shuttle",
    title: "Vienna to Designer Outlet Parndorf by Shuttle Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Designer Outlet Parndorf shuttle page for current Vienna departures, prices, and return times." },
      { order: 2, description: "Go to the confirmed Vienna pickup point; official outlet pages identify downtown Vienna at the State Opera for shuttle services." },
      { order: 3, description: "Board the shuttle bus to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the return shuttle departure time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "vienna-to-parndorf-train-bus",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "vienna-city-center",
    transportationType: "train",
    title: "Vienna to Designer Outlet Parndorf by Train and Station Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check ÖBB train times from Vienna to Parndorf Ort before travelling." },
      { order: 2, description: "Travel by train to Parndorf Ort station." },
      { order: 3, description: "Use the official train-station bus from Parndorf Ort to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the station-bus and train return times before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "vienna-airport-to-parndorf-car",
    outletId: "designer-outlet-parndorf",
    originType: "airport",
    originId: "vienna-airport",
    transportationType: "taxi",
    title: "Vienna Airport to Designer Outlet Parndorf by Car",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Vienna Airport to Designer Outlet Straße 1, 7111 Parndorf." },
      { order: 2, description: "Use a taxi, rental car, or transfer and confirm the fare before departure." },
      { order: 3, description: "Use the official free parking zones in and around the centre on arrival." },
      { order: 4, description: "Confirm return pickup or onward transport before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "bratislava-to-parndorf-shuttle",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "bratislava-city-center",
    transportationType: "shuttle",
    title: "Bratislava to Designer Outlet Parndorf by Shuttle Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Designer Outlet Parndorf shuttle page for Bratislava service dates, pickup point, price, and return time." },
      { order: 2, description: "Go to the confirmed Bratislava pickup point." },
      { order: 3, description: "Board the shuttle bus to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the return shuttle departure before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "budapest-to-parndorf-flixbus",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "budapest-city-center",
    transportationType: "bus",
    title: "Budapest to Designer Outlet Parndorf by FlixBus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official FlixBus timetable and Designer Outlet Parndorf travel page before booking." },
      { order: 2, description: "Book only a service confirmed for Designer Outlet Parndorf or a suitable Parndorf stop." },
      { order: 3, description: "On arrival, follow outlet signs to the centre entrance." },
      { order: 4, description: "Confirm the return coach stop and departure time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
];
