import type { TransportationGuide } from "./index";

export const austriaTransportationGuides: TransportationGuide[] = [
{
guideId: "vienna-to-parndorf-shuttle",
outletId: "designer-outlet-parndorf",
originType: "city_center",
originId: "vienna-city-center",
transportationType: "shuttle",
title: "Vienna City Center to Designer Outlet Parndorf by Shuttle",
estimatedDuration: "40-50 min",
estimatedCost: "€15-20",
recommended: true,
steps: [
{ order: 1, description: "Check the official Designer Outlet Parndorf shuttle timetable before your trip." },
{ order: 2, description: "Go to the Vienna pickup point near the State Opera / city center." },
{ order: 3, description: "Arrive at least 10 minutes before departure." },
{ order: 4, description: "Take the direct shuttle towards Designer Outlet Parndorf." },
{ order: 5, description: "Save the return departure time before you start shopping." },
],
updatedAt: "2026-06-29",
},
{
guideId: "vienna-to-parndorf-train",
outletId: "designer-outlet-parndorf",
originType: "city_center",
originId: "vienna-city-center",
transportationType: "train",
title: "Vienna to Parndorf by Train + Local Transfer",
estimatedDuration: "45-70 min",
estimatedCost: "€8-15",
recommended: false,
steps: [
{ order: 1, description: "Go to a main Vienna rail station with connections towards Parndorf." },
{ order: 2, description: "Take a regional train towards Parndorf Ort or Neusiedl am See." },
{ order: 3, description: "From the station, continue by local bus, taxi, or outlet transfer when available." },
{ order: 4, description: "Get off near Designer Outlet Parndorf." },
{ order: 5, description: "Check return train times before closing time." },
],
updatedAt: "2026-06-29",
},
{
guideId: "vienna-airport-to-parndorf",
outletId: "designer-outlet-parndorf",
originType: "airport",
originId: "vienna-airport",
transportationType: "taxi",
title: "Vienna Airport to Designer Outlet Parndorf",
estimatedDuration: "25-35 min",
estimatedCost: "€60-90",
recommended: false,
steps: [
{ order: 1, description: "From Vienna Airport, choose taxi, private transfer, or rental car." },
{ order: 2, description: "Set Designer Outlet Parndorf as the destination." },
{ order: 3, description: "Confirm the fare estimate before departure." },
{ order: 4, description: "Travel east towards Parndorf." },
{ order: 5, description: "Use the main drop-off point or parking area." },
],
updatedAt: "2026-06-29",
},
{
guideId: "bratislava-to-parndorf",
outletId: "designer-outlet-parndorf",
originType: "city_center",
originId: "bratislava-city-center",
transportationType: "taxi",
title: "Bratislava to Designer Outlet Parndorf by Car / Taxi",
estimatedDuration: "25-40 min",
estimatedCost: "€70-110",
recommended: false,
steps: [
{ order: 1, description: "Start from Bratislava city center or Bratislava Airport." },
{ order: 2, description: "Book a taxi, private transfer, or rental car towards Parndorf." },
{ order: 3, description: "Confirm cross-border fare and waiting policy if using a taxi." },
{ order: 4, description: "Follow signs for Designer Outlet Parndorf." },
{ order: 5, description: "Plan the return transfer in advance during weekends." },
],
updatedAt: "2026-06-29",
},
];
