import type { TransportationGuide } from "./index";

export const austriaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "vienna-to-parndorf-shuttle",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "vienna-city-center",
    transportationType: "shuttle",
    title: "Vienna to Designer Outlet Parndorf by Shuttle Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Designer Outlet Parndorf shuttle page for current Vienna departures, prices, and return times." },
      { order: 2, description: "Go to the confirmed Vienna pickup point; official outlet pages identify downtown Vienna at the State Opera for shuttle services." },
      { order: 3, description: "Board the shuttle bus to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the return shuttle departure time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "vienna-to-parndorf-train-bus",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "vienna-city-center",
    transportationType: "train",
    title: "Vienna to Designer Outlet Parndorf by Train and Station Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check ÖBB train times from Vienna to Parndorf Ort before travelling." },
      { order: 2, description: "Travel by train to Parndorf Ort station." },
      { order: 3, description: "Use the official train-station bus from Parndorf Ort to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the station-bus and train return times before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "vienna-airport-to-parndorf-car",
    outletId: "designer-outlet-parndorf",
    originType: "airport",
    originId: "vienna-airport",
    transportationType: "taxi",
    title: "Vienna Airport to Designer Outlet Parndorf by Car",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Vienna Airport to Designer Outlet Straße 1, 7111 Parndorf." },
      { order: 2, description: "Use a taxi, rental car, or transfer and confirm the fare before departure." },
      { order: 3, description: "Use the official free parking zones in and around the centre on arrival." },
      { order: 4, description: "Confirm return pickup or onward transport before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "vienna-to-parndorf-car",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "vienna-city-center",
    transportationType: "taxi",
    title: "Vienna to Designer Outlet Parndorf by Car",
    estimatedDuration: "About 40 minutes",
    estimatedCost: "Free centre parking; road, fuel, rental or taxi costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Designer Outlet Straße 1, 7111 Parndorf and allow time for traffic leaving Vienna." },
      { order: 2, description: "Follow the signed route to Designer Outlet Parndorf and use the free parking zones in and around the centre." },
      { order: 3, description: "If charging an electric vehicle, use the official EV charging areas near car park P1 or opposite adidas when available." },
      { order: 4, description: "For the return trip, re-check traffic toward Vienna before leaving the car park." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "bratislava-to-parndorf-shuttle",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "bratislava-city-center",
    transportationType: "shuttle",
    title: "Bratislava to Designer Outlet Parndorf by Shuttle Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Designer Outlet Parndorf shuttle page for Bratislava service dates, pickup point, price, and return time." },
      { order: 2, description: "Go to the confirmed Bratislava pickup point." },
      { order: 3, description: "Board the shuttle bus to Designer Outlet Parndorf." },
      { order: 4, description: "Confirm the return shuttle departure before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "budapest-to-parndorf-flixbus",
    outletId: "designer-outlet-parndorf",
    originType: "city_center",
    originId: "budapest-city-center",
    transportationType: "bus",
    title: "Budapest to Designer Outlet Parndorf by FlixBus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official FlixBus timetable and Designer Outlet Parndorf travel page before booking." },
      { order: 2, description: "Book only a service confirmed for Designer Outlet Parndorf or a suitable Parndorf stop." },
      { order: 3, description: "On arrival, follow outlet signs to the centre entrance." },
      { order: 4, description: "Confirm the return coach stop and departure time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "salzburg-city-to-designer-outlet-salzburg-bus",
    outletId: "designer-outlet-salzburg",
    originType: "city_center",
    originId: "salzburg-city-center",
    transportationType: "bus",
    title: "Salzburg City Centre to Designer Outlet Salzburg by Bus",
    estimatedDuration: "About 15 minutes by bus; check official timetable",
    estimatedCost: "Check official Salzburg Verkehr fare before travel",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Designer Outlet Salzburg access page and Salzburg Verkehr timetable for bus lines serving DOC Himmelreich before travel." },
      { order: 2, description: "From central Salzburg, use the confirmed line such as trolleybus 2 from Hauptbahnhof / Mirabellplatz or line 10 from the old-town side when it fits the current timetable." },
      { order: 3, description: "Get off at DOC Himmelreich / the outlet bus stop and follow the signed entrance into Designer Outlet Salzburg." },
      { order: 4, description: "Before shopping, check the official return timetable and fare so you do not rely on an expired or last departure." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "salzburg-airport-to-designer-outlet-salzburg-walk",
    outletId: "designer-outlet-salzburg",
    originType: "airport",
    originId: "salzburg-airport",
    transportationType: "walking",
    title: "Salzburg Airport to Designer Outlet Salzburg Last-Mile Walk",
    estimatedDuration: "Short last-mile walk; check map before travel",
    estimatedCost: "Free on foot",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the pedestrian route from Salzburg Airport to Designer Outlet Salzburg before leaving the terminal." },
      { order: 2, description: "Use signed pavements and crossings only; the outlet is near the airport but road layouts can make the exact walking route important." },
      { order: 3, description: "If carrying luggage or travelling in poor weather, use an official taxi or the Salzburg public-transport planner instead of walking." },
      { order: 4, description: "For the return to the airport, leave extra time for security and re-check the walking route or local bus option." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "salzburg-to-designer-outlet-salzburg-car-parking",
    outletId: "designer-outlet-salzburg",
    originType: "city_center",
    originId: "salzburg-city-center",
    transportationType: "taxi",
    title: "Driving or Taxi to Designer Outlet Salzburg with Parking",
    estimatedDuration: "About 10 minutes from Salzburg; check traffic",
    estimatedCost: "Check official parking terms; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Designer Outlet Salzburg, Kasernenstraße 1, Wals-Himmelreich, and check current traffic before departure." },
      { order: 2, description: "Follow the outlet's official road directions to the parking garage or signed parking areas." },
      { order: 3, description: "If using the P+R option, check Salzburg.info and Salzburg Verkehr rules for the current combo ticket, validity and participating bus lines before parking." },
      { order: 4, description: "If using a taxi or airport transfer, confirm fare and pickup point before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
];
