import type { TransportationGuide } from "./index";

export const czechRepublicTransportationGuides: TransportationGuide[] = [
  {
    guideId: "prague-centre-to-fashion-arena-metro-shuttle",
    outletId: "fashion-arena-prague-outlet",
    originType: "city_center",
    originId: "prague-city-center",
    transportationType: "metro",
    title: "Prague City Centre to Fashion Arena by Metro A and Bus 238",
    estimatedDuration: "≈30-45 min from central Prague (estimated)",
    estimatedCost: "Check official PID/DPP fare",
    recommended: true,
    steps: [
      { order: 1, description: "From central Prague, take metro line A toward Depo Hostivař, the final station on line A." },
      { order: 2, description: "At Depo Hostivař, follow signs to the official Fashion Arena shuttle/public bus 238 stop." },
      { order: 3, description: "Ride bus 238 via Malešická továrna, Na Homoli and Průmyslová to Fashion Arena Štěrboholy, as listed by the outlet." },
      { order: 4, description: "For the return, use bus 238 back to Depo Hostivař and transfer to metro line A toward the city centre." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "prague-airport-to-fashion-arena-public-transport",
    outletId: "fashion-arena-prague-outlet",
    originType: "airport",
    originId: "prague-vaclav-havel-airport",
    transportationType: "bus",
    title: "Václav Havel Airport Prague to Fashion Arena by Public Transport or Car",
    estimatedDuration: "≈35-50 min by car; ≈60-80 min by public transport (estimated)",
    estimatedCost: "Check official PID/DPP fare; taxi/transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From the airport, use official Prague Airport/PID information to reach the metro network, then connect to metro line A." },
      { order: 2, description: "Travel on metro line A to Depo Hostivař." },
      { order: 3, description: "Transfer to bus 238 and ride to Fashion Arena Štěrboholy." },
      { order: 4, description: "For the return to the airport, check the full PID/DPP itinerary before leaving and allow extra time for terminal security." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "prague-main-station-to-fashion-arena-metro-bus",
    outletId: "fashion-arena-prague-outlet",
    originType: "station",
    originId: "prague-main-station",
    transportationType: "train",
    title: "Prague Main Station to Fashion Arena by Metro and Bus 238",
    estimatedDuration: "≈35-50 min from Praha hlavní nádraží (estimated)",
    estimatedCost: "Check official PID/DPP fare; rail fare separate if arriving from outside Prague",
    recommended: true,
    steps: [
      { order: 1, description: "Arrive at Praha hlavní nádraží and follow signs to the Prague metro network." },
      { order: 2, description: "Use the metro to connect to line A toward Depo Hostivař, validating the correct PID/DPP ticket for your journey." },
      { order: 3, description: "At Depo Hostivař, board bus 238 to Fashion Arena Štěrboholy." },
      { order: 4, description: "For the return to the station, ride bus 238 back to Depo Hostivař and allow transfer time across the metro network." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "fashion-arena-prague-car-parking-guide",
    outletId: "fashion-arena-prague-outlet",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Free Parking at Fashion Arena Prague Outlet",
    estimatedDuration: "≈20-30 min from central Prague; ≈35-50 min from airport (estimated)",
    estimatedCost: "Free parking; road costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Fashion Arena Prague Outlet, Zamenhofova 440, Praha-Štěrboholy, 108 00." },
      { order: 2, description: "Drive toward Štěrboholy and check live Prague ring-road and city traffic before departure." },
      { order: 3, description: "Use the outlet's official free parking on arrival; the practical information page also lists e-car charging." },
      { order: 4, description: "For the return drive, re-check traffic toward central Prague, the airport or your hotel before leaving the car park." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "fashion-arena-prague-return-trip",
    outletId: "fashion-arena-prague-outlet",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "bus",
    title: "Return Trip from Fashion Arena to Prague Centre, Station or Airport",
    estimatedDuration: "≈30-45 min to central Prague by bus/metro; airport timing ≈60-80 min (estimated)",
    estimatedCost: "Check official PID/DPP fare; taxi/transfer fare varies",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official bus 238 timetable for departures from Fashion Arena Štěrboholy back to Depo Hostivař." },
      { order: 2, description: "At Depo Hostivař, transfer to metro line A for central Prague or onward metro/bus links." },
      { order: 3, description: "If returning to Praha hlavní nádraží or Václav Havel Airport, plan the full PID/DPP route before leaving the outlet." },
      { order: 4, description: "If driving or taking a taxi, use the official free parking/drop-off area and check live Prague traffic before departure." },
    ],
    updatedAt: "2026-07-03",
  },
];
