import type { TransportationGuide } from "./index";

export const estoniaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "tallinn-center-to-t1-outlet-tram",
    outletId: "t1-tallinn-outlet",
    originType: "city_center",
    originId: "tallinn-city-center",
    transportationType: "bus",
    title: "Tallinn City Center to T1 Tallinn Outlet by Tram, Bus, or Train",
    estimatedDuration: "≈10-20 min (estimated)",
    estimatedCost: "Check official Tallinn public transport fare",
    recommended: true,
    steps: [
      { order: 1, description: "From central Tallinn, use the official Tallinn public transport planner for a tram toward Ülemiste / airport that stops at Ülemiste jaam or another T1-adjacent stop." },
      { order: 2, description: "Ride to the T1 / Ülemiste area; T1's official access page states the centre is at a transport hub reachable by tram, bus, and train." },
      { order: 3, description: "Follow signs from the stop toward T1 Tallinn and the outlet shops inside the centre." },
      { order: 4, description: "Validate a Tallinn public transport ticket unless you are entitled to free travel under official city rules." },
      { order: 5, description: "For the return, use the same nearby tram stop toward the city center and check live departures before leaving T1." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "tallinn-airport-to-t1-outlet-tram-walk",
    outletId: "t1-tallinn-outlet",
    originType: "airport",
    originId: "tallinn-airport",
    transportationType: "walking",
    title: "Tallinn Airport to T1 Tallinn Outlet",
    estimatedDuration: "≈5-10 min by tram or taxi; ≈15-20 min walk (estimated)",
    estimatedCost: "Walk free; check official public transport fare",
    recommended: true,
    steps: [
      { order: 1, description: "From Tallinn Airport terminal, choose the official tram connection toward Ülemiste / city center, a short taxi, or the signposted pedestrian route toward T1." },
      { order: 2, description: "If using tram, validate a ticket and ride one stop toward the T1 / Ülemiste area when service is operating." },
      { order: 3, description: "If walking, use the airport-area pedestrian crossings and paths toward Peterburi tee and T1 Tallinn; allow more time with luggage or in winter weather." },
      { order: 4, description: "Enter T1 Tallinn and follow internal signs to the outlet area." },
      { order: 5, description: "For the return to the airport, confirm tram departures or allow enough time to walk back through the terminal approach before your flight." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "ulemiste-station-to-t1-outlet-train",
    outletId: "t1-tallinn-outlet",
    originType: "station",
    originId: "ulemiste-station",
    transportationType: "train",
    title: "Ülemiste Station to T1 Tallinn Outlet",
    estimatedDuration: "≈5-10 min walk (estimated)",
    estimatedCost: "Walk free after train arrival",
    recommended: false,
    steps: [
      { order: 1, description: "Arrive at Ülemiste railway station using an official Elron train service and check live train times before travelling." },
      { order: 2, description: "Exit the station toward T1 Tallinn / Peterburi tee, following the signed pedestrian route to the shopping centre." },
      { order: 3, description: "Walk into T1 Tallinn and continue to the outlet shops." },
      { order: 4, description: "For the return, check Elron departures from Ülemiste before leaving the outlet so you can time the short walk back to the platform." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "tallinn-center-to-t1-outlet-car-parking",
    outletId: "t1-tallinn-outlet",
    originType: "city_center",
    originId: "tallinn-city-center",
    transportationType: "taxi",
    title: "Tallinn City Center to T1 Tallinn Outlet by Car or Taxi",
    estimatedDuration: "≈10-20 min (estimated)",
    estimatedCost: "Parking terms check T1; taxi or ride-hail fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to T1 Tallinn, Peterburi tee 2, Tallinn." },
      { order: 2, description: "Drive or take a licensed taxi / ride-hail east from the city center toward Ülemiste and Peterburi tee." },
      { order: 3, description: "Use T1's official parking access and check the current parking terms on arrival." },
      { order: 4, description: "For the return, confirm the pickup point with your driver or note the car-park level before entering the shops." },
    ],
    updatedAt: "2026-07-03",
  },
];
