import type { TransportationGuide } from "./index";

export const franceTransportationGuides: TransportationGuide[] = [
  {
    guideId: "paris-to-la-vallee-rer-a",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "train",
    title: "Paris City Center to La Vallée Village by RER A",
    estimatedDuration: "Less than 1 hour",
    estimatedCost: "≈€5 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Start at a central Paris RER A station served by RER A, such as Châtelet-Les Halles, Auber, Charles de Gaulle-Étoile, or Nation, and confirm live service on RATP, Île-de-France Mobilités, or SNCF before travelling." },
      { order: 2, description: "Take RER A towards Marne-la-Vallée Chessy." },
      { order: 3, description: "Get off at Val d'Europe/Serris-Montévrain, one stop before Marne-la-Vallée Chessy / Parcs Disneyland." },
      { order: 4, description: "On leaving the station, turn right and walk through the Val d'Europe shopping centre." },
      { order: 5, description: "Continue to La Vallée Village; the official outlet guidance describes this as a 10-minute walk from the station." },
      { order: 6, description: "For the return trip, use the same Val d'Europe/Serris-Montévrain RER A station and confirm the Paris-bound timetable before leaving the Village." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-la-vallee-shopping-express",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "shuttle",
    title: "Paris City Center to La Vallée Village by Shopping Express® Shuttle",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Book Shopping Express® tickets online before travelling; the official page says reservation is required and tickets cannot be bought on board." },
      { order: 2, description: "Go to Hotel Pullman Paris Bercy, 1 rue de Libourne, 75012 Paris." },
      { order: 3, description: "Use metro line 14 to Cour St Emilion, exits 1-2, or bus lines 24, 111, or 109 to Terroirs de France." },
      { order: 4, description: "Meet the representative with a Paris City Vision sign outside the hotel." },
      { order: 5, description: "Confirm the selected half-day or full-day departure and return times on the official booking page before you go." },
      { order: 6, description: "Return on your booked Shopping Express® service from La Vallée Village; do not assume seats are available without a reservation." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "cdg-to-la-vallee-tgv-rer",
    outletId: "la-vallee-village",
    originType: "airport",
    originId: "charles-de-gaulle-airport",
    transportationType: "train",
    title: "Charles de Gaulle Airport to La Vallée Village by Rail",
    estimatedDuration: "≈25-45 min (estimated)",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "At Paris Charles de Gaulle Airport, follow airport signs to the SNCF/TGV railway station at Terminal 2." },
      { order: 2, description: "Check SNCF for TGV services to Marne-la-Vallée Chessy / Parcs Disneyland before buying a ticket." },
      { order: 3, description: "From Marne-la-Vallée Chessy, continue one stop by RER A to Val d'Europe/Serris-Montévrain when service is operating, or confirm another official local connection." },
      { order: 4, description: "At Val d'Europe/Serris-Montévrain, turn right after exiting and walk through the Val d'Europe shopping centre to La Vallée Village." },
      { order: 5, description: "For the return trip, confirm both the RER A and SNCF/TGV timetables before leaving the Village." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "disneyland-to-la-vallee-local-shuttle",
    outletId: "la-vallee-village",
    originType: "station",
    originId: "disneyland-paris",
    transportationType: "shuttle",
    title: "Disneyland Paris Area to La Vallée Village",
    estimatedDuration: "10 min from Disneyland Paris area",
    estimatedCost: "€6 adult return / €3 child return",
    recommended: false,
    steps: [
      { order: 1, description: "Start in the Disneyland Paris / Marne-la-Vallée Chessy area." },
      { order: 2, description: "Ask your Disney Resort hotel concierge or the La Vallée Village Welcome Center to book the regular shuttle bus." },
      { order: 3, description: "Confirm the current return-ticket price and departure time with the booking point before boarding." },
      { order: 4, description: "Use the return shuttle booked through the hotel concierge or Welcome Center; confirm the final return time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-la-vallee-car-parking",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Paris City Center to La Vallée Village by Car or Taxi",
    estimatedDuration: "40 min from Paris",
    estimatedCost: "Parking free; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to La Vallée Village, 3 Cours de la Garonne, 77700 Serris, France." },
      { order: 2, description: "Confirm traffic conditions before leaving Paris; official outlet guidance describes the drive as about 40 minutes from Paris." },
      { order: 3, description: "Use the official La Vallée Village parking areas; the outlet states that parking is free and ample." },
      { order: 4, description: "For taxi or ride-hail returns, confirm pickup availability and fare with the provider before the Village closes." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "paris-to-troyes-train",
    outletId: "designer-outlet-troyes",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "train",
    title: "Paris City Center to Designer Outlet Troyes by Train",
    estimatedDuration: "1h29 train + ≈20-30 min local transfer (estimated)",
    estimatedCost: "TER fare from €3-21 when available; local fare check TCAT",
    recommended: true,
    steps: [
      { order: 1, description: "Go to Paris Est station and check SNCF Connect or TER Fluo Grand Est for Paris to Troyes services." },
      { order: 2, description: "Take the official SNCF/TER service to Troyes; do not rely on a fixed departure time without checking the timetable." },
      { order: 3, description: "Arrive at Troyes station." },
      { order: 4, description: "Continue to Designer Outlet Troyes in Pont-Sainte-Marie by TCAT bus, demand-responsive transport when available, or taxi." },
      { order: 5, description: "For the return trip, confirm the Troyes to Paris Est train timetable before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "troyes-station-to-designer-outlet-troyes-bus",
    outletId: "designer-outlet-troyes",
    originType: "station",
    originId: "troyes-station",
    transportationType: "bus",
    title: "Troyes Station to Designer Outlet Troyes by Public Transport",
    estimatedDuration: "≈20-30 min (estimated)",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Exit Troyes station and use the official TCAT journey planner or station intermodal information." },
      { order: 2, description: "Look for TCAT services towards Pont-Sainte-Marie; official station information lists TCAT line 1 towards Pont Ste Marie/Ste Savine, and the outlet services page also notes lines 1 and 12 to the Magasins stop." },
      { order: 3, description: "Ride to the Magasins stop or the closest stop confirmed by TCAT for Designer Outlet Troyes, Voie du Bois, 10150 Pont-Sainte-Marie." },
      { order: 4, description: "If regular bus service is not convenient, confirm TCAT transport-on-demand availability or take an official taxi." },
      { order: 5, description: "For the return trip, check TCAT times from Pont-Sainte-Marie back to Troyes station before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-troyes-car-parking",
    outletId: "designer-outlet-troyes",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Paris City Center to Designer Outlet Troyes by Car",
    estimatedDuration: "≈2h00-2h20 (estimated)",
    estimatedCost: "Parking free; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Designer Outlet Troyes, Voie du Bois, 10150 Pont-Sainte-Marie." },
      { order: 2, description: "Follow official road navigation towards Troyes / Pont-Sainte-Marie and confirm traffic before departure." },
      { order: 3, description: "Use the outlet's on-site parking areas; the official services page states parking is free with no time limit and electric charging is available." },
      { order: 4, description: "For the return trip to Paris, confirm motorway conditions and any taxi or ride-service fare with the provider." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "marseille-to-provence-train-bus",
    outletId: "designer-outlet-provence",
    originType: "city_center",
    originId: "marseille-city-center",
    transportationType: "train",
    title: "Marseille City Center to Designer Outlet Provence by Train and Local Transfer",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "≈€13-14 train + local transfer (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Go to Marseille Saint-Charles station and check SNCF Connect or TER/ZOU! for services to Miramas." },
      { order: 2, description: "Take the train to Miramas when a suitable official service is available." },
      { order: 3, description: "At Miramas station, confirm the local bus, shopping shuttle when offered by McArthurGlen, or taxi option to McArthurGlen Provence before continuing." },
      { order: 4, description: "Travel to McArthurGlen Provence - Village de Marques, Mas de la Péronne, Miramas 13140." },
      { order: 5, description: "For the return trip, confirm both the local transfer back to Miramas station and the SNCF/TER timetable to Marseille." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "marseille-airport-to-provence-train",
    outletId: "designer-outlet-provence",
    originType: "airport",
    originId: "marseille-airport",
    transportationType: "train",
    title: "Marseille Provence Airport to Designer Outlet Provence by Train and Local Transfer",
    estimatedDuration: "≈45-70 min (estimated)",
    estimatedCost: "€1.20 airport-station bus + ≈€8-15 train/local transfer (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "At Marseille Provence Airport, go to bus station platform 5 and use the official lebus+ 13 link to Vitrolles-Aéroport Marseille Provence (VAMP) station; the airport states this link takes about 5 minutes." },
      { order: 2, description: "Check SNCF Connect for TER train options from Vitrolles-Aéroport Marseille Provence towards Miramas." },
      { order: 3, description: "At Miramas station, confirm the local bus, shopping shuttle when offered by McArthurGlen, or taxi connection to McArthurGlen Provence." },
      { order: 4, description: "For the return trip, confirm the Miramas to Vitrolles-Aéroport Marseille Provence train and the lebus+ 13 airport-station shuttle before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "marseille-airport-to-provence-car",
    outletId: "designer-outlet-provence",
    originType: "airport",
    originId: "marseille-airport",
    transportationType: "taxi",
    title: "Marseille Provence Airport to Designer Outlet Provence by Car or Taxi",
    estimatedDuration: "35-45 min from nearby cities",
    estimatedCost: "Parking free; taxi fare confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Exit Marseille Provence Airport and set the destination to McArthurGlen Provence - Village de Marques, Mas de la Péronne, Miramas 13140." },
      { order: 2, description: "Confirm traffic and fare with the taxi, ride-service, or rental-car provider before departure." },
      { order: 3, description: "Follow official navigation to Miramas and the outlet access roads." },
      { order: 4, description: "Use the outlet parking areas and confirm electric-vehicle charging or accessibility needs with Guest Services before travelling." },
      { order: 5, description: "For the return trip to the airport, confirm pickup time and fare with the provider before the outlet closes." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "provence-direct-shuttle-confirm",
    outletId: "designer-outlet-provence",
    originType: "city_center",
    originId: "marseille-city-center",
    transportationType: "shuttle",
    title: "Designer Outlet Provence Shuttle or Direct Bus Confirmation",
    estimatedDuration: "Check official timetable",
    estimatedCost: "From €15 return when official shuttle offer is available",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official McArthurGlen Provence 'By shuttle' section before travelling, because shuttle availability can change." },
      { order: 2, description: "Only use a shuttle or direct coach if it is listed by McArthurGlen Provence or an official transport operator for your travel date." },
      { order: 3, description: "Confirm the departure point, return point, fare, and timetable with the provider before booking; recent official McArthurGlen shuttle promotions list Marseille or Aix-en-Provence shopping shuttles from €15 return." },
      { order: 4, description: "If no official shuttle is available, use the train to Miramas plus a confirmed local bus or taxi transfer." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "strasbourg-to-roppenheim-official-shuttle",
    outletId: "roppenheim-the-style-outlets",
    originType: "city_center",
    originId: "strasbourg-city-center",
    transportationType: "shuttle",
    title: "Strasbourg to Roppenheim The Style Outlets by Official Shuttle",
    estimatedDuration: "≈45-60 min (estimated); check official shuttle booking",
    estimatedCost: "Free when offered; reservation required",
    recommended: true,
    steps: [
      { order: 1, description: "Open Roppenheim The Style Outlets' official Strasbourg shuttle page and reserve your seat for the shopping date; do not rely on walk-up availability." },
      { order: 2, description: "Go to the Strasbourg departure point shown on the current official booking confirmation and arrive early enough for boarding." },
      { order: 3, description: "Board the official shuttle to Roppenheim The Style Outlets, 1 Route de l'Europe, 67480 Roppenheim." },
      { order: 4, description: "On arrival, note the shuttle drop-off point and the confirmed same-day return departure before shopping." },
      { order: 5, description: "Return on the booked shuttle; if you miss it, check SNCF/TER rail options from Roppenheim station or arrange a licensed taxi." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "strasbourg-to-roppenheim-train-walk",
    outletId: "roppenheim-the-style-outlets",
    originType: "station",
    originId: "strasbourg-station",
    transportationType: "train",
    title: "Strasbourg Station to Roppenheim The Style Outlets by Train",
    estimatedDuration: "≈45 min train + ≈20-30 min walk/taxi (estimated)",
    estimatedCost: "Check official SNCF / TER fare",
    recommended: false,
    steps: [
      { order: 1, description: "At Strasbourg station, check SNCF Connect or TER Grand Est for trains toward Roppenheim." },
      { order: 2, description: "Take the official train to Roppenheim station when a convenient service is available." },
      { order: 3, description: "From Roppenheim station, continue to the outlet by local taxi or walk only if conditions are suitable; the outlet is outside the village center." },
      { order: 4, description: "For the return, check the Roppenheim to Strasbourg rail timetable before leaving the outlet and allow time to reach the station." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "strasbourg-airport-to-roppenheim-rail-transfer",
    outletId: "roppenheim-the-style-outlets",
    originType: "airport",
    originId: "strasbourg-airport",
    transportationType: "train",
    title: "Strasbourg Airport to Roppenheim The Style Outlets by Rail and Shuttle",
    estimatedDuration: "≈1h15-1h45 (estimated)",
    estimatedCost: "Check official SNCF / TER fare; shuttle free when reserved",
    recommended: false,
    steps: [
      { order: 1, description: "At Strasbourg Airport, use the official airport rail link from Entzheim-Aéroport station to Strasbourg station." },
      { order: 2, description: "From Strasbourg station, either join the reserved official Roppenheim shuttle if its timetable fits, or take an SNCF/TER train to Roppenheim." },
      { order: 3, description: "If arriving by train at Roppenheim, use a local taxi or suitable walking route to reach 1 Route de l'Europe." },
      { order: 4, description: "For the return to the airport, confirm the shuttle or TER times back to Strasbourg and the airport rail connection before leaving the outlet." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "strasbourg-to-roppenheim-car-parking",
    outletId: "roppenheim-the-style-outlets",
    originType: "city_center",
    originId: "strasbourg-city-center",
    transportationType: "taxi",
    title: "Strasbourg to Roppenheim The Style Outlets by Car",
    estimatedDuration: "≈35-50 min (estimated)",
    estimatedCost: "Parking free; taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Roppenheim The Style Outlets, 1 Route de l'Europe, 67480 Roppenheim." },
      { order: 2, description: "Drive north from Strasbourg toward Roppenheim and confirm traffic before departure." },
      { order: 3, description: "Use the outlet's visitor parking areas and note the parking row for your return." },
      { order: 4, description: "If using a taxi or private transfer, agree the return pickup time and exact meeting point before entering the outlet." },
    ],
    updatedAt: "2026-07-03",
  },


  {
    guideId: "paris-to-paris-giverny-designer-outlet-shuttle",
    outletId: "paris-giverny-designer-outlet",
    originType: "city_center",
    originId: "paris-pullman-tour-eiffel",
    transportationType: "shuttle",
    title: "Paris to Designer Outlet Paris-Giverny by Official Shuttle",
    estimatedDuration: "check official shuttle timetable",
    estimatedCost: "check official shuttle fare and promo terms",
    recommended: true,
    steps: [
      { order: 1, description: "Book the official McArthurGlen / shuttle-operator service from Pullman Paris Tour Eiffel and check the current operating days before travel." },
      { order: 2, description: "Arrive at the confirmed Paris departure point early with the booking confirmation." },
      { order: 3, description: "Take the direct shuttle to McArthurGlen Designer Outlet Paris-Giverny and note the drop-off point on arrival." },
      { order: 4, description: "Before shopping, confirm the same-day return departure time and meeting point shown by the official shuttle operator." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "paris-saint-lazare-to-paris-giverny-designer-outlet-train-shuttle",
    outletId: "paris-giverny-designer-outlet",
    originType: "station",
    originId: "paris-saint-lazare-station",
    transportationType: "train",
    title: "Paris Saint-Lazare to Designer Outlet Paris-Giverny by Train and Local Shuttle",
    estimatedDuration: "check official SNCF and shuttle timetable",
    estimatedCost: "check official SNCF fare; shuttle fare check official operator",
    recommended: false,
    steps: [
      { order: 1, description: "From Paris Saint-Lazare, check official SNCF / TER Nomad train departures to Vernon-Giverny." },
      { order: 2, description: "At Vernon-Giverny station, check the official local shuttle or bus connection toward Giverny / McArthurGlen Paris-Giverny before leaving the station." },
      { order: 3, description: "Use the confirmed local shuttle, bus, or licensed taxi for the last-mile transfer to the outlet." },
      { order: 4, description: "For the return, check both the local transfer and SNCF train timetable before leaving the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "paris-airport-to-paris-giverny-designer-outlet-transfer",
    outletId: "paris-giverny-designer-outlet",
    originType: "airport",
    originId: "paris-cdg-airport",
    transportationType: "train",
    title: "Paris Charles de Gaulle Airport to Designer Outlet Paris-Giverny by Rail and Transfer",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official rail fares; taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "At Paris Charles de Gaulle Airport, use official airport rail information to reach Paris Saint-Lazare via central Paris connections." },
      { order: 2, description: "From Paris Saint-Lazare, check official SNCF / TER Nomad trains to Vernon-Giverny." },
      { order: 3, description: "At Vernon-Giverny, continue by official local shuttle, bus, or licensed taxi to Designer Outlet Paris-Giverny." },
      { order: 4, description: "For the return to the airport, check official rail and last-mile times and allow a flight check-in buffer." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "paris-giverny-designer-outlet-car-parking-guide",
    outletId: "paris-giverny-designer-outlet",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Designer Outlet Paris-Giverny by Car or Taxi",
    estimatedDuration: "45 min from Paris / Versailles / Rouen area (official outlet positioning); check traffic",
    estimatedCost: "parking check official outlet terms; taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to McArthurGlen Designer Outlet Paris-Giverny, Avenue du Capitaine Vandière de Vitrac, Douains." },
      { order: 2, description: "Use the official outlet driving guidance via the A13 / A14 corridor and confirm traffic before departure." },
      { order: 3, description: "Park in the official visitor parking area and note the entrance used." },
      { order: 4, description: "If using a taxi or private transfer, agree the return pickup point and fare before entering the outlet." },
    ],
    updatedAt: "2026-07-04",
  },

  {
    guideId: "paris-montparnasse-to-one-nation-paris-train-bus",
    outletId: "one-nation-paris",
    originType: "city_center",
    originId: "paris-montparnasse",
    transportationType: "train",
    title: "Paris Montparnasse to One Nation Paris by Train and Bus",
    estimatedDuration: "check official Transilien Line N and bus 5101 timetables",
    estimatedCost: "check official Île-de-France Mobilités fare before travel",
    recommended: true,
    steps: [
      { order: 1, description: "At Paris Montparnasse, check the official Transilien Line N timetable toward Plaisir Grignon or Mantes-la-Jolie and confirm it stops at Villepreux-les-Clayes." },
      { order: 2, description: "Take the confirmed Line N train to Villepreux-les-Clayes." },
      { order: 3, description: "From Villepreux-les-Clayes, either walk about 10 minutes as the outlet describes, or take official bus 5101 to the One Nation Paris Outlet stop if the timetable works." },
      { order: 4, description: "Before shopping, check both the bus 5101 and Line N return timetables to Paris." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "villepreux-les-clayes-to-one-nation-paris-walk",
    outletId: "one-nation-paris",
    originType: "station",
    originId: "villepreux-les-clayes-station",
    transportationType: "walking",
    title: "Villepreux-les-Clayes Station to One Nation Paris on Foot",
    estimatedDuration: "about 10 minutes on foot according to the outlet",
    estimatedCost: "free walk; check rail fare separately",
    recommended: true,
    steps: [
      { order: 1, description: "Exit Villepreux-les-Clayes station and confirm the pedestrian route to One Nation Paris before leaving the station area." },
      { order: 2, description: "Walk the official last-mile route toward 1 avenue du Président Kennedy / One Nation Paris Outlet; the outlet describes the station as about 10 minutes on foot." },
      { order: 3, description: "Use crossings and signed pedestrian paths rather than cutting through car parks or roadways." },
      { order: 4, description: "For the return, leave enough time to walk back and check the official Line N departure before leaving the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "villepreux-les-clayes-to-one-nation-paris-bus-5101",
    outletId: "one-nation-paris",
    originType: "station",
    originId: "villepreux-les-clayes-station",
    transportationType: "bus",
    title: "Villepreux-les-Clayes Station to One Nation Paris by Bus 5101",
    estimatedDuration: "first stop from Villepreux-les-Clayes according to the outlet; check official timetable",
    estimatedCost: "check official Île-de-France Mobilités fare before travel",
    recommended: false,
    steps: [
      { order: 1, description: "At Villepreux-les-Clayes station, check the official Île-de-France Mobilités timetable for bus line 5101." },
      { order: 2, description: "Board bus 5101 only if the official timetable confirms service; the outlet says the first stop is One Nation Paris Outlet." },
      { order: 3, description: "Alight at One Nation Paris Outlet and note the stop location for the return." },
      { order: 4, description: "Before shopping, confirm the return 5101 and Line N connections so you are not left with only a walking option." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "paris-to-one-nation-paris-car-parking",
    outletId: "one-nation-paris",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Paris to One Nation Paris by Car or Taxi",
    estimatedDuration: "check traffic; official route via A13 then A12/N12",
    estimatedCost: "parking check outlet terms; taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to One Nation Paris, 1 avenue du Président Kennedy, 78340 Les Clayes-sous-Bois." },
      { order: 2, description: "Follow the official road guidance via the A13 motorway, then A12/N12 toward Dreux, taking the Plaisir / Centre Commercial Regional exit and signs for One Nation Paris Outlet." },
      { order: 3, description: "Use the official visitor parking area and note your parking sector." },
      { order: 4, description: "If using a taxi or private transfer, confirm the fare and return pickup before entering the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
];
