import type { TransportationGuide } from "./index";

export const franceTransportationGuides: TransportationGuide[] = [
  {
    guideId: "paris-to-la-vallee-rer-a",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "train",
    title: "Paris City Center to La Vallée Village by RER A",
    estimatedDuration: "Less than 1 hour",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Start at a central Paris RER A station and confirm live service on RATP, Île-de-France Mobilités, or SNCF before travelling." },
      { order: 2, description: "Take RER A towards Marne-la-Vallée Chessy." },
      { order: 3, description: "Get off at Val d'Europe/Serris-Montévrain, one stop before Marne-la-Vallée Chessy / Parcs Disneyland." },
      { order: 4, description: "On leaving the station, turn right and walk through the Val d'Europe shopping centre." },
      { order: 5, description: "Continue to La Vallée Village; the official outlet guidance describes this as a 10-minute walk from the station." },
      { order: 6, description: "For the return trip, use the same Val d'Europe/Serris-Montévrain RER A station and confirm the Paris-bound timetable before leaving the Village." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-la-vallee-shopping-express",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "shuttle",
    title: "Paris City Center to La Vallée Village by Shopping Express® Shuttle",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Book Shopping Express® tickets online before travelling; the official page says reservation is required and tickets cannot be bought on board." },
      { order: 2, description: "Go to Hotel Pullman Paris Bercy, 1 rue de Libourne, 75012 Paris." },
      { order: 3, description: "Use metro line 14 to Cour St Emilion, exits 1-2, or bus lines 24, 111, or 109 to Terroirs de France." },
      { order: 4, description: "Meet the representative with a Paris City Vision sign outside the hotel." },
      { order: 5, description: "Confirm the selected half-day or full-day departure and return times on the official booking page before you go." },
      { order: 6, description: "Return on your booked Shopping Express® service from La Vallée Village; do not assume seats are available without a reservation." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "cdg-to-la-vallee-tgv-rer",
    outletId: "la-vallee-village",
    originType: "airport",
    originId: "charles-de-gaulle-airport",
    transportationType: "train",
    title: "Charles de Gaulle Airport to La Vallée Village by Rail",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "At Paris Charles de Gaulle Airport, follow airport signs to the SNCF/TGV railway station." },
      { order: 2, description: "Check SNCF for TGV services to Marne-la-Vallée Chessy / Parcs Disneyland before buying a ticket." },
      { order: 3, description: "From Marne-la-Vallée Chessy, continue one stop by RER A to Val d'Europe/Serris-Montévrain when service is operating, or confirm another official local connection." },
      { order: 4, description: "At Val d'Europe/Serris-Montévrain, turn right after exiting and walk through the Val d'Europe shopping centre to La Vallée Village." },
      { order: 5, description: "For the return trip, confirm both the RER A and SNCF/TGV timetables before leaving the Village." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "disneyland-to-la-vallee-local-shuttle",
    outletId: "la-vallee-village",
    originType: "station",
    originId: "disneyland-paris",
    transportationType: "shuttle",
    title: "Disneyland Paris Area to La Vallée Village",
    estimatedDuration: "10 min from Disneyland Paris area",
    estimatedCost: "€6 adult return / €3 child return",
    recommended: false,
    steps: [
      { order: 1, description: "Start in the Disneyland Paris / Marne-la-Vallée Chessy area." },
      { order: 2, description: "Ask your Disney Resort hotel concierge or the La Vallée Village Welcome Center to book the regular shuttle bus." },
      { order: 3, description: "Confirm the current return-ticket price and departure time with the booking point before boarding." },
      { order: 4, description: "Use the return shuttle booked through the hotel concierge or Welcome Center; confirm the final return time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-la-vallee-car-parking",
    outletId: "la-vallee-village",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Paris City Center to La Vallée Village by Car or Taxi",
    estimatedDuration: "40 min from Paris",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to La Vallée Village, 3 Cours de la Garonne, 77700 Serris, France." },
      { order: 2, description: "Confirm traffic conditions before leaving Paris; official outlet guidance describes the drive as about 40 minutes from Paris." },
      { order: 3, description: "Use the official La Vallée Village parking areas; the outlet states that parking is free and ample." },
      { order: 4, description: "For taxi or ride-hail returns, confirm pickup availability and fare with the provider before the Village closes." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "paris-to-troyes-train",
    outletId: "designer-outlet-troyes",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "train",
    title: "Paris City Center to Designer Outlet Troyes by Train",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Go to Paris Est station and check SNCF Connect or TER Fluo Grand Est for Paris to Troyes services." },
      { order: 2, description: "Take the official SNCF/TER service to Troyes; do not rely on a fixed departure time without checking the timetable." },
      { order: 3, description: "Arrive at Troyes station." },
      { order: 4, description: "Continue to Designer Outlet Troyes in Pont-Sainte-Marie by TCAT bus, demand-responsive transport when available, or taxi." },
      { order: 5, description: "For the return trip, confirm the Troyes to Paris Est train timetable before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "troyes-station-to-designer-outlet-troyes-bus",
    outletId: "designer-outlet-troyes",
    originType: "station",
    originId: "troyes-station",
    transportationType: "bus",
    title: "Troyes Station to Designer Outlet Troyes by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Exit Troyes station and use the official TCAT journey planner or station intermodal information." },
      { order: 2, description: "Look for TCAT services towards Pont-Sainte-Marie, including line 1 when shown in official station information." },
      { order: 3, description: "Confirm the stop closest to Designer Outlet Troyes, Voie du Bois, 10150 Pont-Sainte-Marie, before boarding." },
      { order: 4, description: "If regular bus service is not convenient, confirm TCAT transport-on-demand availability or take an official taxi." },
      { order: 5, description: "For the return trip, check TCAT times from Pont-Sainte-Marie back to Troyes station before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "paris-to-troyes-car-parking",
    outletId: "designer-outlet-troyes",
    originType: "city_center",
    originId: "paris-city-center",
    transportationType: "taxi",
    title: "Paris City Center to Designer Outlet Troyes by Car",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Designer Outlet Troyes, Voie du Bois, 10150 Pont-Sainte-Marie." },
      { order: 2, description: "Follow official road navigation towards Troyes / Pont-Sainte-Marie and confirm traffic before departure." },
      { order: 3, description: "Use the outlet's on-site parking areas and confirm parking conditions on the official outlet page before travelling." },
      { order: 4, description: "For the return trip to Paris, confirm motorway conditions and any taxi or ride-service fare with the provider." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "marseille-to-provence-train-bus",
    outletId: "designer-outlet-provence",
    originType: "city_center",
    originId: "marseille-city-center",
    transportationType: "train",
    title: "Marseille City Center to Designer Outlet Provence by Train and Local Transfer",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Go to Marseille Saint-Charles station and check SNCF Connect or TER for services to Miramas." },
      { order: 2, description: "Take the train to Miramas when a suitable official service is available." },
      { order: 3, description: "At Miramas station, confirm the local bus, shuttle, or taxi option to McArthurGlen Provence before continuing." },
      { order: 4, description: "Travel to McArthurGlen Provence - Village de Marques, Mas de la Péronne, Miramas 13140." },
      { order: 5, description: "For the return trip, confirm both the local transfer back to Miramas station and the SNCF/TER timetable to Marseille." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "marseille-airport-to-provence-train",
    outletId: "designer-outlet-provence",
    originType: "airport",
    originId: "marseille-airport",
    transportationType: "train",
    title: "Marseille Provence Airport to Designer Outlet Provence by Train and Local Transfer",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "At Marseille Provence Airport, go to the airport bus station and use the official lebus+ 13 link to Vitrolles-Aéroport Marseille Provence (VAMP) station." },
      { order: 2, description: "Check SNCF Connect for TER train options from Vitrolles-Aéroport Marseille Provence towards Miramas." },
      { order: 3, description: "At Miramas station, confirm the local bus, shuttle, or taxi connection to McArthurGlen Provence." },
      { order: 4, description: "For the return trip, confirm the Miramas to Vitrolles-Aéroport Marseille Provence train and the lebus+ 13 airport-station shuttle before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "marseille-airport-to-provence-car",
    outletId: "designer-outlet-provence",
    originType: "airport",
    originId: "marseille-airport",
    transportationType: "taxi",
    title: "Marseille Provence Airport to Designer Outlet Provence by Car or Taxi",
    estimatedDuration: "35-45 min from nearby cities",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Exit Marseille Provence Airport and set the destination to McArthurGlen Provence - Village de Marques, Mas de la Péronne, Miramas 13140." },
      { order: 2, description: "Confirm traffic and fare with the taxi, ride-service, or rental-car provider before departure." },
      { order: 3, description: "Follow official navigation to Miramas and the outlet access roads." },
      { order: 4, description: "Use the outlet parking areas and confirm electric-vehicle charging or accessibility needs with Guest Services before travelling." },
      { order: 5, description: "For the return trip to the airport, confirm pickup time and fare with the provider before the outlet closes." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "provence-direct-shuttle-confirm",
    outletId: "designer-outlet-provence",
    originType: "city_center",
    originId: "marseille-city-center",
    transportationType: "shuttle",
    title: "Designer Outlet Provence Shuttle or Direct Bus Confirmation",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official McArthurGlen Provence 'By shuttle' section before travelling, because shuttle availability can change." },
      { order: 2, description: "Only use a shuttle or direct coach if it is listed by McArthurGlen Provence or an official transport operator for your travel date." },
      { order: 3, description: "Confirm the departure point, return point, fare, and timetable with the provider before booking." },
      { order: 4, description: "If no official shuttle is available, use the train to Miramas plus a confirmed local bus or taxi transfer." },
    ],
    updatedAt: "2026-07-01",
  },
];
