import type { TransportationGuide } from "./index";

const updatedAt = "2026-07-01";

export const germanyTransportationGuides: TransportationGuide[] = [
{
guideId: "stuttgart-city-center-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "train",
title: "Stuttgart city center to Outletcity Metzingen by train",
estimatedDuration: "≈40-55 min (estimated)",
estimatedCost: "≈€10-15 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use Deutsche Bahn or bwegt for Stuttgart Hbf to Metzingen (Württ); Outletcity lists Metzingen (Württ) station as the train access point." },
{ order: 2, description: "Board a regional connection toward Metzingen, changing at Reutlingen or Tübingen only if the official planner requires it for your departure." },
{ order: 3, description: "At Metzingen (Württ), follow signs toward Outletcity; the walk to Hugo-Boss-Platz and the main shopping streets is about 10-15 minutes." },
{ order: 4, description: "For the return, check the evening DB/bwegt departure from Metzingen before shopping and allow time to walk back to the station." },
{ order: 5, description: "Use DB/bwegt on the day and do not rely on historic schedules because regional train transfers can change." },
{ order: 6, description: "Before checkout, confirm you are walking 10-15 minutes back to Metzingen (Württ) station; if you miss the final planned connection, use the official operator app for the next train/bus or ask Outletcity guest services about taxi/private transfer options." },
],
updatedAt,
},
{
guideId: "stuttgart-airport-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "airport",
originId: "stuttgart-airport",
transportationType: "shuttle",
title: "Stuttgart Airport to Outletcity Metzingen",
estimatedDuration: "≈35-50 min (estimated)",
estimatedCost: "€10 round-trip advance / €12 on bus / €8.50 one-way (official shuttle fare)",
recommended: true,
steps: [
{ order: 1, description: "Check the official Outletcity Shopping Shuttle Line 1 timetable for Stuttgart Airport and surrounding stops before booking." },
{ order: 2, description: "Book online where possible; Outletcity states advance round-trip tickets cost €10, while onboard purchase is €12 round-trip or €8.50 one-way." },
{ order: 3, description: "Board at the airport pickup point shown on the official booking/timetable and ride directly to Outletcity Metzingen." },
{ order: 4, description: "Keep the return departure time from Outletcity available; if the shuttle does not run for your flight time, use DB/bwegt via Stuttgart Hbf or a taxi/private transfer." },
],
updatedAt,
},
{
guideId: "metzingen-station-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "station",
originId: "metzingen-station",
transportationType: "walking",
title: "Metzingen station to Outletcity Metzingen",
estimatedDuration: "≈10-15 min (estimated)",
estimatedCost: "Free",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Metzingen (Württ), the station named by Outletcity for train arrivals." },
{ order: 2, description: "Exit toward central Metzingen and follow pedestrian signs/navigation to Hugo-Boss-Platz 4 and the Outletcity shopping streets." },
{ order: 3, description: "Use a taxi only if you have heavy luggage or accessibility needs; the normal last-mile route is a short walk." },
{ order: 4, description: "For the return, leave the shops early enough for the 10-15 minute walk and recheck your DB/bwegt platform." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-direct-shuttle",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "shuttle",
title: "Stuttgart direct Shopping Shuttle to Outletcity Metzingen",
estimatedDuration: "≈35-50 min (estimated)",
estimatedCost: "€10 round-trip advance / €12 on bus / €8.50 one-way (official shuttle fare)",
recommended: true,
steps: [
{ order: 1, description: "Open the official Outletcity Shopping Shuttle page and choose Line 2 from Stuttgart city center to Outletcity Metzingen and back." },
{ order: 2, description: "Book online in advance where possible for the €10 round-trip fare; confirm the exact pickup point and operating day on the timetable." },
{ order: 3, description: "Arrive at the confirmed Stuttgart pickup point early and keep your booking ready for boarding." },
{ order: 4, description: "On arrival, note the Outletcity return stop and departure time before entering the shops." },
{ order: 5, description: "If Line 2 is not operating on your date, use the Stuttgart Hbf to Metzingen (Württ) train guide instead." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-public-transport",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "bus",
title: "Public transport and bus options to Outletcity Metzingen",
estimatedDuration: "≈40-60 min (estimated)",
estimatedCost: "≈€8-15 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use bwegt or DB for regional train options and the official Outletcity page for bus links, including eXpresso and Swiss Eurobus where relevant." },
{ order: 2, description: "Enter Metzingen (Württ) or Outletcity Metzingen as the destination and select the connection that matches your shopping hours." },
{ order: 3, description: "If routed by rail, walk from Metzingen station; if routed by bus, get off only at the stop named in the official timetable." },
{ order: 4, description: "Buy the correct operator ticket before boarding and keep enough time for the final walk or stop transfer." },
{ order: 5, description: "Recheck the last return connection on DB/bwegt or the bus operator before checkout." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-by-car",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "taxi",
title: "Driving to Outletcity Metzingen",
estimatedDuration: "≈30 min (official from Stuttgart, traffic-dependent)",
estimatedCost: "Parking: P4/P4.1 free; other car parks confirm on site",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to OUTLETCITY METZINGEN, Hugo-Boss-Platz 4, 72555 Metzingen, the address on the official arrival page." },
{ order: 2, description: "Drive from Stuttgart toward Metzingen and follow local Outletcity parking signs on arrival." },
{ order: 3, description: "Choose the official car park closest to your shops: P0, P1, P2, P3, or the free P4/P4.1 parking spaces listed by Outletcity." },
{ order: 4, description: "For the return, save your parking location, check live traffic toward Stuttgart, and follow the signed exit route rather than stopping near store entrances." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-parking",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "walking",
title: "Parking guidance for Outletcity Metzingen",
estimatedDuration: "On site",
estimatedCost: "P4/P4.1 free (official); other parking confirm on site",
recommended: false,
steps: [
{ order: 1, description: "Check the official parking list before driving; Outletcity lists garages P0-P3, free spaces P4 and P4.1, and e-charging at several car parks." },
{ order: 2, description: "Follow signs to the designated visitor car park instead of stopping at Hugo-Boss-Platz or shop entrances." },
{ order: 3, description: "If you need EV charging, choose one of the official e-charging locations and confirm availability on arrival." },
{ order: 4, description: "Keep any ticket/payment instructions and note the pedestrian route from your car park back to the shops and later to your return exit." },
],
updatedAt,
},
{
guideId: "munich-city-center-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "shuttle",
title: "Munich city center to Ingolstadt Village by Shopping Express",
estimatedDuration: "≈45 min (official)",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Use the official Ingolstadt Village Getting Here page and book the Shopping Express seat before travel." },
{ order: 2, description: "Board at the Munich pickup point shown on the official booking confirmation; the Village states the Shopping Express runs Munich to Ingolstadt Village and back Monday to Saturday." },
{ order: 3, description: "Ride directly to Ingolstadt Village, then check the return stop and departure time before shopping." },
{ order: 4, description: "If your date is sold out or the coach is not operating, use the train plus bus 22 route instead." },
],
updatedAt,
},
{
guideId: "munich-city-center-to-ingolstadt-village-train-bus",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "train",
title: "Munich city center to Ingolstadt Village by train and bus",
estimatedDuration: "≈1 hr 25 min-1 hr 50 min (estimated)",
estimatedCost: "≈€20-35 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use Deutsche Bahn for München Hbf to Ingolstadt Hbf and VGI for the Ingolstadt local bus leg." },
{ order: 2, description: "At Ingolstadt Hbf, take VGI bus 22 directly to Ingolstadt Village; the official Village train page gives the bus time as about 25 minutes and says it stops in front of the Village." },
{ order: 3, description: "Keep a valid DB ticket for the rail leg and buy the required VGI local ticket for the bus if it is not included." },
{ order: 4, description: "For the return, check bus 22 back to Ingolstadt Hbf before leaving the boutiques, then connect to a Munich-bound train." },
{ order: 5, description: "Use DB for long-distance/regional train tickets and VGI for buses 20 and 22; confirm the last bus from Ingolstadt Village before shopping, especially if returning through Ingolstadt Hbf, ZOB or Nordbahnhof." },
{ order: 6, description: "Keep separate ticket rules in mind, including VGI Airport Express restrictions if your wider itinerary uses the airport coach; if you miss the planned return, ask Concierge Services to help confirm the next VGI/DB option or a private transfer." },
],
updatedAt,
},
{
guideId: "munich-airport-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "airport",
originId: "munich-airport",
transportationType: "bus",
title: "Munich Airport to Ingolstadt Village",
estimatedDuration: "≈1 hr 25 min-1 hr 55 min (estimated)",
estimatedCost: "≈€15-30 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use the official VGI Airport Express between Munich Airport and Ingolstadt; VGI lists stops at Munich Airport Center and Terminal 2 and Ingolstadt Nordbahnhof/ZOB." },
{ order: 2, description: "From Ingolstadt Nordbahnhof or ZOB, change to VGI bus 20 for Ingolstadt Village, as listed on the official Village Getting Here page." },
{ order: 3, description: "If your connection uses Ingolstadt Hbf instead, continue by VGI bus 22 directly to the Village." },
{ order: 4, description: "Before shopping, confirm the Airport Express return timetable because airport tickets and regional tickets can have separate rules." },
],
updatedAt,
},
{
guideId: "ingolstadt-hbf-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "station",
originId: "ingolstadt-hbf",
transportationType: "bus",
title: "Ingolstadt Hbf to Ingolstadt Village",
estimatedDuration: "≈25 min (official)",
estimatedCost: "≈€3-5 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Exit Ingolstadt Hbf and find the VGI bus stop for line 22 toward Ingolstadt Village." },
{ order: 2, description: "Take bus 22; the official Ingolstadt Village train page states the journey takes approximately 25 minutes and stops right in front of the Village." },
{ order: 3, description: "Check the VGI real-time display or timetable for the exact departure and return times." },
{ order: 4, description: "For the return, board bus 22 at the Village stop back toward Ingolstadt Hbf." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-by-car",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "taxi",
title: "Driving to Ingolstadt Village",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "Parking free (official)",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Ingolstadt Village, Otto-Hahn-Straße 1, 85055 Ingolstadt." },
{ order: 2, description: "Drive from Munich via the A9 toward Ingolstadt and follow local signs to the Village." },
{ order: 3, description: "The official Village visit page states the centre is directly on the A9 and offers complimentary parking and EV charging points." },
{ order: 4, description: "For the return, check live motorway traffic before leaving the car park." },
],
updatedAt,
},
{
guideId: "frankfurt-city-center-to-wertheim-village",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "shuttle",
title: "Frankfurt city center to Wertheim Village by Shopping Express",
estimatedDuration: "≈45 min (official by car/shuttle)",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Use the official Wertheim Village visit page and Shopping Express booking link; the Village says it is 45 minutes from Frankfurt and next to the A3." },
{ order: 2, description: "Book the Frankfurt Shopping Express in advance and confirm the exact city-center pickup point and operating day." },
{ order: 3, description: "Ride directly to Wertheim Village and note the return stop before shopping." },
{ order: 4, description: "If the coach is unavailable, use DB from Frankfurt toward Wertheim/Würzburg and a local bus or taxi for the final leg." },
{ order: 5, description: "Reserve before travel and confirm fare, pickup point, luggage rules, and the return departure time with the Shopping Express provider." },
],
updatedAt,
},
{
guideId: "frankfurt-airport-to-wertheim-village",
outletId: "wertheim-village",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "train",
title: "Frankfurt Airport to Wertheim Village",
estimatedDuration: "≈1 hr 30 min-2 hr 15 min (estimated)",
estimatedCost: "≈€20-40 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use DB from Frankfurt Flughafen Fernbahnhof/Regionalbahnhof toward Wertheim, usually changing through Frankfurt Hbf, Aschaffenburg, Würzburg, or Lauda depending on the timetable." },
{ order: 2, description: "From Wertheim station, use the official local connection shown by the planner or take a short taxi to Wertheim Village." },
{ order: 3, description: "For airport returns, choose a connection with extra buffer for rail changes and security." },
{ order: 4, description: "If travelling on a Shopping Express operating day, compare the airport-to-city transfer plus coach with the rail option before booking." },
],
updatedAt,
},
{
guideId: "wertheim-station-to-wertheim-village",
outletId: "wertheim-village",
originType: "station",
originId: "wertheim-station",
transportationType: "bus",
title: "Wertheim station to Wertheim Village",
estimatedDuration: "≈10-20 min (estimated)",
estimatedCost: "≈€3-15 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Wertheim station and check the official local transport planner for the next bus to Wertheim Village or Almosenberg." },
{ order: 2, description: "If no suitable bus is due, take a short local taxi to the Village." },
{ order: 3, description: "Get off at the Village/Almosenberg stop named by the operator and follow pedestrian signs to the boutiques." },
{ order: 4, description: "For the return, check the last bus or pre-book a taxi before leaving the shops." },
],
updatedAt,
},
{
guideId: "wertheim-village-public-transport",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt to Wertheim Village by train and local transfer",
estimatedDuration: "≈1 hr 45 min-2 hr 30 min (estimated)",
estimatedCost: "≈€20-35 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use DB for Frankfurt Hbf to Wertheim; the official Village page confirms train access from Frankfurt and Würzburg." },
{ order: 2, description: "Change only as shown in the official planner, commonly via Aschaffenburg, Würzburg, or Lauda depending on departure." },
{ order: 3, description: "At Wertheim station, continue by the official local bus if it matches your arrival, or use a taxi for the short last mile." },
{ order: 4, description: "Buy rail and local tickets according to the operator rules and recheck the return before shopping." },
{ order: 5, description: "Use the official Village page for Shopping Express context, DB for rail, and the local operator for the Wertheim station last mile; keep separate tickets for coach, rail, and local bus where required." },
{ order: 6, description: "Confirm the last useful bus/taxi from Wertheim Village before shopping; if you miss the planned return, ask Concierge/Guest Services to help confirm the next DB/local bus option or a taxi." },
],
updatedAt,
},
{
guideId: "wertheim-village-by-car",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "taxi",
title: "Driving to Wertheim Village",
estimatedDuration: "≈45 min (official, traffic-dependent)",
estimatedCost: "Parking free (official)",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Wertheim Village, Almosenberg, 97877 Wertheim." },
{ order: 2, description: "Drive from Frankfurt via the A3 toward Wertheim; the official page says the Village is next to the A3 motorway." },
{ order: 3, description: "Follow signs to the complimentary Village car parks and EV charging points." },
{ order: 4, description: "For the return, save your car park area and check live A3 traffic toward Frankfurt before leaving." },
],
updatedAt,
},
{
guideId: "wertheim-village-parking",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "walking",
title: "Parking guidance for Wertheim Village",
estimatedDuration: "On site",
estimatedCost: "Free (official)",
recommended: false,
steps: [
{ order: 1, description: "Use the official Visit page before arrival; Wertheim Village states parking is complimentary and EV charging points are available." },
{ order: 2, description: "Follow the signed visitor parking route and parking attendants if present." },
{ order: 3, description: "If you need accessible, reserved, or EV parking, confirm current availability with Guest Services before travel." },
{ order: 4, description: "Note your parking zone and pedestrian entrance for a simple return after shopping." },
],
updatedAt,
},
{
guideId: "berlin-city-center-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "shuttle",
title: "Berlin city center to Designer Outlet Berlin by free shuttle",
estimatedDuration: "30 min (official)",
estimatedCost: "Free (official)",
recommended: true,
steps: [
{ order: 1, description: "Use the official Designer Outlet Berlin directions page before departure." },
{ order: 2, description: "On Fridays, Saturdays and event days, board the free shuttle at Kurfürstendamm 225/Hard Rock Café at the listed time." },
{ order: 3, description: "Ride the non-stop shuttle to Designer Outlet Berlin; the official page states the journey is 30 minutes." },
{ order: 4, description: "Check the same official shuttle section for the return time to Berlin before you start shopping." },
],
updatedAt,
},
{
guideId: "berlin-city-center-to-designer-outlet-berlin-train",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "train",
title: "Berlin city center to Designer Outlet Berlin by train and shuttle",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "≈€4-8 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use the official VBB/DB journey planner from central Berlin to Wustermark station." },
{ order: 2, description: "At Wustermark station, use the outlet-confirmed free shuttle/local transfer or continue by taxi if the shuttle is not running." },
{ order: 3, description: "Allow extra time on Sundays or event days because shuttle times can differ." },
{ order: 4, description: "For the return, confirm both the Wustermark connection and the final Berlin train before leaving the outlet." },
],
updatedAt,
},
{
guideId: "berlin-airport-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "airport",
originId: "berlin-airport",
transportationType: "train",
title: "Berlin Brandenburg Airport to Designer Outlet Berlin",
estimatedDuration: "≈1 hr 30 min-2 hr 10 min (estimated)",
estimatedCost: "≈€5-12 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use the official VBB/DB planner from BER Airport to Wustermark station or Designer Outlet Berlin." },
{ order: 2, description: "Change in Berlin as instructed by the planner, then continue toward Wustermark." },
{ order: 3, description: "From Wustermark, use the outlet shuttle/local connection or taxi to the centre." },
{ order: 4, description: "Check the return route before shopping to protect airport check-in time." },
],
updatedAt,
},
{
guideId: "wustermark-station-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "station",
originId: "wustermark-station",
transportationType: "shuttle",
title: "Wustermark station to Designer Outlet Berlin",
estimatedDuration: "≈10-15 min (estimated)",
estimatedCost: "Free if outlet shuttle operates; taxi ≈€12-20 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Wustermark station and check the outlet directions page or station notices for the free shuttle connection." },
{ order: 2, description: "Board only the current outlet-confirmed shuttle or use a local taxi if no shuttle is available." },
{ order: 3, description: "Keep the return shuttle time available before entering the shops." },
{ order: 4, description: "If returning late, check the VBB/DB train departure from Wustermark first." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-by-car",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlet Berlin",
estimatedDuration: "30 min from downtown Berlin (official)",
estimatedCost: "Parking free (official)",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Designer Outlet Berlin, Alter Spandauer Weg 1, 14641 Wustermark." },
{ order: 2, description: "Follow the B5 toward Wustermark; the official directions page states the outlet is directly on the B5 and about 30 minutes from downtown Berlin." },
{ order: 3, description: "Use the visitor parking in front of the entrance; the official page lists 3,000 free spaces, disabled parking and 10 EV charging stations." },
{ order: 4, description: "For the return, check live B5 and Berlin traffic before leaving." },
],
updatedAt,
},
{
guideId: "hamburg-city-center-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "train",
title: "Hamburg city center to Designer Outlet Neumünster",
estimatedDuration: "≈55-80 min (estimated)",
estimatedCost: "≈€12-25 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB/NAH.SH from Hamburg Hbf to Neumünster station and the official McArthurGlen visit page for the centre address." },
{ order: 2, description: "From Neumünster station, continue by local bus/taxi to Oderstraße 10." },
{ order: 3, description: "The official centre page says the outlet is 30 minutes from Hamburg north and 45 minutes from Hamburg, so allow more time from the city centre by public transport." },
{ order: 4, description: "Check the return train and last local bus/taxi availability before shopping." },
],
updatedAt,
},
{
guideId: "hamburg-airport-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "airport",
originId: "hamburg-airport",
transportationType: "train",
title: "Hamburg Airport to Designer Outlet Neumünster",
estimatedDuration: "≈1 hr 20 min-1 hr 50 min (estimated)",
estimatedCost: "≈€12-25 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use HVV/DB from Hamburg Airport to Hamburg Hbf, then a train to Neumünster." },
{ order: 2, description: "At Neumünster station, continue to Oderstraße 10 by local bus or taxi." },
{ order: 3, description: "Allow buffer time for the airport-to-Hbf transfer and confirm the date-specific train timetable." },
{ order: 4, description: "For the return, check the Hamburg Airport connection before leaving the centre." },
],
updatedAt,
},
{
guideId: "neumunster-station-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "station",
originId: "neumunster-station",
transportationType: "bus",
title: "Neumünster station to Designer Outlet Neumünster",
estimatedDuration: "≈15-25 min (estimated)",
estimatedCost: "≈€3-5 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Neumünster station and use the local operator journey planner for buses toward Oderstraße/Designer Outlet." },
{ order: 2, description: "If the next bus is not convenient, take a taxi for the short last-mile trip." },
{ order: 3, description: "Get off at the stop shown by the official local timetable for Designer Outlet Neumünster/Oderstraße." },
{ order: 4, description: "Check the return bus or taxi plan before shopping." },
],
updatedAt,
},
{
guideId: "designer-outlet-neumunster-by-car",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlet Neumünster",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Designer Outlet Neumünster, Oderstraße 10, 24539 Neumünster." },
{ order: 2, description: "Use the official McArthurGlen plan-your-visit page and route planner link before departure." },
{ order: 3, description: "The official page states the centre is 30 minutes from Hamburg north and Kiel; allow longer from central Hamburg and during A7 traffic." },
{ order: 4, description: "Follow on-site parking signs and confirm current parking conditions with the outlet before arrival." },
],
updatedAt,
},
{
guideId: "hannover-city-center-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "train",
title: "Hannover city center to Designer Outlets Wolfsburg",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "≈€15-30 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB from Hannover Hbf to Wolfsburg Hauptbahnhof." },
{ order: 2, description: "On arrival, walk from Wolfsburg Hauptbahnhof; the official outlet access page states the station is only two minutes on foot from the outlets." },
{ order: 3, description: "The outlets are next to the central station and opposite Autostadt, so follow signs toward An der Vorburg." },
{ order: 4, description: "For return, check DB departures from Wolfsburg Hbf before leaving the centre." },
],
updatedAt,
},
{
guideId: "hannover-airport-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "airport",
originId: "hannover-airport",
transportationType: "train",
title: "Hannover Airport to Designer Outlets Wolfsburg",
estimatedDuration: "≈1 hr 15 min-1 hr 45 min (estimated)",
estimatedCost: "≈€18-35 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use GVH/DB from Hannover Airport to Hannover Hbf, then DB to Wolfsburg Hbf." },
{ order: 2, description: "Walk about two minutes from Wolfsburg Hbf to Designer Outlets Wolfsburg." },
{ order: 3, description: "Confirm airport return connections before shopping because the airport leg requires a transfer in Hannover." },
{ order: 4, description: "Allow extra time for evening flights." },
],
updatedAt,
},
{
guideId: "wolfsburg-hbf-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "station",
originId: "wolfsburg-hbf",
transportationType: "walking",
title: "Wolfsburg Hauptbahnhof to Designer Outlets Wolfsburg",
estimatedDuration: "2 min (official)",
estimatedCost: "Free",
recommended: true,
steps: [
{ order: 1, description: "Exit Wolfsburg Hauptbahnhof toward the city centre/Autostadt side." },
{ order: 2, description: "Walk to Designer Outlets Wolfsburg at An der Vorburg 1; the official access page says the main station is only two minutes away on foot." },
{ order: 3, description: "For local buses, the official page says all public buses serve Wolfsburg central bus station only a few metres from the centre toward Porschestraße." },
{ order: 4, description: "For the return, use Wolfsburg Hbf or the central bus station and check live departures." },
],
updatedAt,
},
{
guideId: "designer-outlets-wolfsburg-by-car",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlets Wolfsburg",
estimatedDuration: "≈60-85 min (estimated)",
estimatedCost: "Parking from €1 first 2 hr; then from €0.50/hr (official)",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Designer Outlets Wolfsburg, An der Vorburg 1, 38440 Wolfsburg, or the official coordinates 52.4284, 10.7956." },
{ order: 2, description: "From the A39, take the Wolfsburg Zentrum exit and follow signs for Designer Outlets." },
{ order: 3, description: "Use the on-site paid parking; the official access page lists about 1,000 spaces and a 1.90 m height limit for the tunnel/underground garages." },
{ order: 4, description: "The first 20 minutes are free; 0-120 minutes cost €1.00, with higher hourly charges after that." },
],
updatedAt,
},
{
guideId: "cologne-city-center-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "train",
title: "Cologne city center to City Outlet Bad Münstereifel",
estimatedDuration: "≈1 hr 20 min-1 hr 50 min (estimated)",
estimatedCost: "≈€10-20 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB/VRS from Köln Hbf to Euskirchen on RB24, as listed on the official outlet directions page." },
{ order: 2, description: "At Euskirchen, change to the S23 toward Bad Münstereifel." },
{ order: 3, description: "Walk from Bad Münstereifel station to the pedestrian zone; the official outlet page says the station is about 150 metres from the pedestrian zone." },
{ order: 4, description: "For the return, check S23 and RB24 times before shopping because a missed connection can add a long wait." },
],
updatedAt,
},
{
guideId: "cologne-airport-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "airport",
originId: "cologne-airport",
transportationType: "train",
title: "Cologne Bonn Airport to City Outlet Bad Münstereifel",
estimatedDuration: "≈1 hr 45 min-2 hr 20 min (estimated)",
estimatedCost: "≈€10-25 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use DB/VRS from Cologne Bonn Airport toward Köln Hbf or another official connection point, then continue by RB24 to Euskirchen." },
{ order: 2, description: "Change at Euskirchen to S23 for Bad Münstereifel." },
{ order: 3, description: "Walk the final 150 metres from Bad Münstereifel station to the pedestrian zone as described by the official outlet page." },
{ order: 4, description: "Confirm the airport return connection before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "bad-munstereifel-station-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "station",
originId: "bad-munstereifel-station",
transportationType: "walking",
title: "Bad Münstereifel station to City Outlet Bad Münstereifel",
estimatedDuration: "≈2-5 min (official distance 150 m)",
estimatedCost: "Free",
recommended: true,
steps: [
{ order: 1, description: "Exit Bad Münstereifel station toward the town centre." },
{ order: 2, description: "Walk about 150 metres to the pedestrian zone; the official outlet directions page states the station is only about 150 metres away." },
{ order: 3, description: "Use the pedestrian-zone entrances for the outlet stores throughout the historic town centre." },
{ order: 4, description: "For the return, walk back to the same station and check S23 departures toward Euskirchen." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-public-transport",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "bus",
title: "Regional bus options to City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "VRS/NRW ticket accepted where valid (official)",
recommended: false,
steps: [
{ order: 1, description: "Use train as the primary route from Cologne; the official page lists RB24 to Euskirchen and S23 to Bad Münstereifel." },
{ order: 2, description: "For regional bus alternatives, check VRS/DB for district buses 801 and connections from Rheinbach and Mechernich, which are listed by the official outlet." },
{ order: 3, description: "Use only date-specific operator timetables because rural bus frequencies vary." },
{ order: 4, description: "For return travel, confirm the last bus or use the S23/RB24 rail route." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-by-car",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "taxi",
title: "Driving to City Outlet Bad Münstereifel",
estimatedDuration: "≈55-80 min (estimated)",
estimatedCost: "Confirm parking locally",
recommended: false,
steps: [
{ order: 1, description: "Drive toward Bad Münstereifel and use exit 112 Bad Münstereifel/Mechernich, as stated on the official outlet directions page." },
{ order: 2, description: "Follow signs toward Bad Münstereifel; after the town sign on L165, continue downhill and follow parking-lot signs." },
{ order: 3, description: "Use official parking areas including station parking and further spaces toward Schleidtal under the underpass bridge." },
{ order: 4, description: "For the return, save the car park location and check live traffic toward Cologne." },
],
updatedAt,
},
{
guideId: "frankfurt-city-center-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt city center to Montabaur The Style Outlets by train",
estimatedDuration: "≈35-55 min (estimated)",
estimatedCost: "≈€18-35 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB for Frankfurt (Main) Hbf to Montabaur; choose an ICE connection where available because the outlet is beside Montabaur ICE station." },
{ order: 2, description: "Arrive at Montabaur station and follow pedestrian signs/navigation to Montabaur The Style Outlets." },
{ order: 3, description: "The last-mile walk is short, but allow extra time with luggage or mobility needs." },
{ order: 4, description: "For the return, recheck the DB platform and any seat reservation before leaving the outlet." },
{ order: 5, description: "Use DB for outbound and return trains to Montabaur; fares vary significantly between ICE and regional options, so check whether your ticket is train-specific and whether a seat reservation is useful at peak times." },
{ order: 6, description: "Allow 5-10 minutes to walk back to Montabaur station before checkout; if you miss the planned train, use DB for the next valid connection before considering taxi or car-share options." },
],
updatedAt,
},
{
guideId: "frankfurt-airport-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "train",
title: "Frankfurt Airport to Montabaur The Style Outlets",
estimatedDuration: "≈35-60 min (estimated)",
estimatedCost: "≈€18-35 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB from Frankfurt Flughafen Fernbahnhof to Montabaur and select a direct ICE when available." },
{ order: 2, description: "At Montabaur station, exit toward the outlet and walk to the signed entrance." },
{ order: 3, description: "For airport returns, choose a train that leaves enough buffer for airline check-in and security." },
{ order: 4, description: "If no convenient ICE is available, compare a DB connection via Limburg/Koblenz with a pre-booked taxi or rental car." },
],
updatedAt,
},
{
guideId: "montabaur-station-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "station",
originId: "montabaur-station",
transportationType: "walking",
title: "Montabaur station to Montabaur The Style Outlets",
estimatedDuration: "≈5-10 min (estimated)",
estimatedCost: "Free",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Montabaur ICE station and exit toward the outlet side of the station area." },
{ order: 2, description: "Follow pedestrian signs/navigation to Montabaur The Style Outlets; the centre is adjacent to the station area." },
{ order: 3, description: "Use a taxi only for accessibility needs, heavy luggage, or bad weather." },
{ order: 4, description: "For the return, allow 5-10 minutes to walk back and check the DB departure board." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-by-car",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "taxi",
title: "Driving to Montabaur The Style Outlets",
estimatedDuration: "≈55-75 min (estimated)",
estimatedCost: "Parking: confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Montabaur The Style Outlets, using the official outlet location near Montabaur ICE station and the A3 corridor." },
{ order: 2, description: "Drive from Frankfurt via the A3 toward Montabaur and follow local outlet/ICE station signs." },
{ order: 3, description: "On arrival, use signed visitor parking and confirm any time limits or validation requirements on site." },
{ order: 4, description: "For the return, check live A3 traffic toward Frankfurt before leaving the car park." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-parking",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "walking",
title: "Parking guidance for Montabaur The Style Outlets",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official outlet information for current parking rules because the outlet sits next to Montabaur ICE station." },
{ order: 2, description: "Follow visitor parking signs rather than station commuter parking unless the outlet directs you there." },
{ order: 3, description: "Confirm any free-period, ticket validation, EV charging, or accessibility parking rules on arrival." },
{ order: 4, description: "Save your parking location and the pedestrian route to the shops for the return." },
],
updatedAt,
},
{
guideId: "saarbrucken-city-center-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "train",
title: "Saarbrücken city center to Zweibrücken Fashion Outlet",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "≈€8-15 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Use DB/VRN or SaarVV for Saarbrücken Hbf to Zweibrücken Hbf, then the official local bus connection toward Fashion Outlet." },
{ order: 2, description: "At Zweibrücken Hbf or the city bus stop shown by the planner, connect to the outlet bus; VIA Outlets states the centre has a bus connection with Zweibrücken Monday to Saturday." },
{ order: 3, description: "Get off at Zweibrücken Fashion Outlet/Londoner Bogen and follow signs to the entrances." },
{ order: 4, description: "For the return, check the last bus back to Zweibrücken before shopping and leave enough time for the rail connection to Saarbrücken." },
{ order: 5, description: "Use DB/VRN/SaarVV for date-specific trains and buses, confirm the Monday-Saturday city bus connection before relying on it for the return, and recheck the next bus from Fashion Outlet to Zweibrücken before checkout." },
{ order: 6, description: "If you miss the final useful public transport option, use an official taxi provider or ask centre information for help confirming a ride." },
],
updatedAt,
},
{
guideId: "saarbrucken-airport-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "airport",
originId: "saarbrucken-airport",
transportationType: "bus",
title: "Saarbrücken Airport to Zweibrücken Fashion Outlet",
estimatedDuration: "≈55-90 min (estimated)",
estimatedCost: "≈€8-20 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Use the official airport/local transport planner from Saarbrücken Airport to Saarbrücken Hbf or directly toward Zweibrücken if available." },
{ order: 2, description: "Continue by DB/VRN to Zweibrücken Hbf and change to the local bus for Fashion Outlet." },
{ order: 3, description: "If travelling with luggage or during gaps in the bus timetable, compare the public transport route with a pre-booked taxi." },
{ order: 4, description: "For the return to the airport, confirm the airport bus and outlet-city bus times before shopping." },
],
updatedAt,
},
{
guideId: "zweibrucken-hbf-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "station",
originId: "zweibrucken-hbf",
transportationType: "bus",
title: "Zweibrücken Hbf to Zweibrücken Fashion Outlet",
estimatedDuration: "≈5-15 min (estimated)",
estimatedCost: "≈€3-5 (estimated)",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Zweibrücken Hbf and check the Stadtbus/VRN departure for Fashion Outlet or Londoner Bogen." },
{ order: 2, description: "Board the bus only if it matches your shopping and return time; VIA Outlets confirms city bus connectivity Monday to Saturday." },
{ order: 3, description: "Get off at the Fashion Outlet stop and walk into the centre." },
{ order: 4, description: "For the return, check the stop timetable before entering the shops; take a taxi if the next bus is not practical." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-public-transport",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "bus",
title: "Public transport to Zweibrücken Fashion Outlet",
estimatedDuration: "≈45-70 min (estimated)",
estimatedCost: "≈€8-15 (estimated)",
recommended: false,
steps: [
{ order: 1, description: "Plan the full route in DB/VRN/SaarVV from Saarbrücken to Zweibrücken Fashion Outlet rather than relying on a copied fixed timetable." },
{ order: 2, description: "Use the train to Zweibrücken Hbf when fastest, then the local city bus to the outlet." },
{ order: 3, description: "Check if your fare covers both the rail and local bus legs; buy a separate local ticket if the planner requires it." },
{ order: 4, description: "Recheck the return on the day because the official operator note limits the city bus connection to Monday-Saturday." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-by-car",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "taxi",
title: "Driving to Zweibrücken Fashion Outlet",
estimatedDuration: "≈25-40 min (estimated)",
estimatedCost: "Parking free (official press information)",
recommended: false,
steps: [
{ order: 1, description: "Set navigation to Zweibrücken Fashion Outlet, Londoner Bogen 10-90, 66482 Zweibrücken, the address on the official centre page." },
{ order: 2, description: "Drive via the A8 toward exit 34 Contwig; official VIA Outlets information says the centre is directly at exit 34." },
{ order: 3, description: "Follow parking signs on site; official press information states the centre has 2,900 free parking spaces." },
{ order: 4, description: "For the return, save the car park location and check live traffic toward Saarbrücken before leaving." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-parking",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "walking",
title: "Parking guidance for Zweibrücken Fashion Outlet",
estimatedDuration: "On site",
estimatedCost: "Free (official press information)",
recommended: false,
steps: [
{ order: 1, description: "Use the official Parking & Route page for the address and route; the centre amenities include parking and EV charging." },
{ order: 2, description: "Follow signed visitor parking after leaving the A8 at Contwig, not delivery or staff routes." },
{ order: 3, description: "Official press information states 2,900 free parking spaces; confirm EV charging or accessible spaces on arrival if needed." },
{ order: 4, description: "Note your parking row and the closest entrance so you can return easily after shopping." },
],
updatedAt,
},

{
guideId: "halle-leipzig-style-outlets-saturday-shuttle",
outletId: "halle-leipzig-the-style-outlets",
originType: "city_center",
originId: "leipzig-city-center",
transportationType: "shuttle",
title: "Leipzig or Halle Main Station to Halle Leipzig The Style Outlets by Free Saturday Shuttle",
estimatedDuration: "Check official shuttle timetable",
estimatedCost: "Free shuttle; reservation/timetable check required",
recommended: true,
steps: [
{ order: 1, description: "Open Halle Leipzig The Style Outlets' official how-to-get-there page and check the free Saturday shuttle booking link and departure times." },
{ order: 2, description: "Go to the confirmed Leipzig main station or Halle bus station pickup point early with any required reservation." },
{ order: 3, description: "Ride the free shuttle to Berliner Straße 1, 06796 Sandersdorf-Brehna, and note the outlet return stop on arrival." },
{ order: 4, description: "Before shopping, confirm the same-day return shuttle departure; if it is not operating, use the train route via Brehna." },
],
updatedAt: "2026-07-03",
},
{
guideId: "halle-leipzig-style-outlets-train-brehna",
outletId: "halle-leipzig-the-style-outlets",
originType: "station",
originId: "brehna-station",
transportationType: "train",
title: "Halle or Leipzig to Halle Leipzig The Style Outlets by S-Bahn to Brehna",
estimatedDuration: "13 min train from Halle to Brehna; Leipzig connections vary",
estimatedCost: "Check official DB/MDV fare",
recommended: false,
steps: [
{ order: 1, description: "Check official DB or MDV times to Brehna before leaving; the outlet lists S-Bahn S8 from Halle toward Lutherstadt Wittenberg, Bitterfeld, or Dessau to Brehna." },
{ order: 2, description: "From Halle, board the S8 to Brehna; from Leipzig, use the official planner for the best connection via Halle, Bitterfeld, or another interchange." },
{ order: 3, description: "At Brehna station, continue to the outlet by the signed local route or a short taxi if preferred." },
{ order: 4, description: "For the return, check the last Brehna train connection before shopping and allow time to reach the station." },
],
updatedAt: "2026-07-03",
},
{
guideId: "halle-leipzig-style-outlets-airport-car",
outletId: "halle-leipzig-the-style-outlets",
originType: "airport",
originId: "leipzig-halle-airport",
transportationType: "taxi",
title: "Leipzig/Halle Airport to Halle Leipzig The Style Outlets by Car or Taxi",
estimatedDuration: "≈20–30 min (estimated)",
estimatedCost: "Taxi/private transfer confirm with provider; parking complimentary",
recommended: false,
steps: [
{ order: 1, description: "From Leipzig/Halle Airport, use a licensed taxi, rental car, or pre-booked transfer to Sandersdorf-Brehna." },
{ order: 2, description: "Follow motorway/local road signs toward the A9/Brehna area and Halle Leipzig The Style Outlets." },
{ order: 3, description: "Use the outlet parking areas at Berliner Straße 1 or agree a main-entrance drop-off point." },
{ order: 4, description: "For a return flight, book pickup before shopping and allow extra time for traffic and airport procedures." },
],
updatedAt: "2026-07-03",
},
{
guideId: "halle-leipzig-style-outlets-car-parking",
outletId: "halle-leipzig-the-style-outlets",
originType: "city_center",
originId: "halle-leipzig-city-center",
transportationType: "taxi",
title: "Leipzig or Halle to Halle Leipzig The Style Outlets by Car with Parking",
estimatedDuration: "≈25–40 min from Leipzig or Halle (estimated)",
estimatedCost: "Parking complimentary; fuel/taxi/private transfer costs vary",
recommended: false,
steps: [
{ order: 1, description: "Check the outlet's official directions and parking information before travel." },
{ order: 2, description: "Drive toward Sandersdorf-Brehna and follow signs for Halle Leipzig The Style Outlets, Berliner Straße 1." },
{ order: 3, description: "Park in the outlet customer parking areas and note your zone before entering the centre." },
{ order: 4, description: "If using a taxi/private transfer, confirm the return pickup point and fare before shopping." },
{ order: 5, description: "For the return, allow additional time around A9 traffic, Saturdays, and sale periods." },
],
updatedAt: "2026-07-03",
},
];
