import type { TransportationGuide } from "./index";

const updatedAt = "2026-07-01";

export const germanyTransportationGuides: TransportationGuide[] = [
{
guideId: "stuttgart-city-center-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "train",
title: "Stuttgart city center to Outletcity Metzingen",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Outletcity Metzingen travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Stuttgart city center towards Metzingen station." },
{ order: 3, description: "Continue from Metzingen station to Outletcity Metzingen by train, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official outlet travel page confirms car, bus, train, parking and airport shuttle options; confirm current shuttle booking before travel." },
],
updatedAt,
},
{
guideId: "stuttgart-airport-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "airport",
originId: "stuttgart-airport",
transportationType: "train",
title: "Stuttgart Airport to Outletcity Metzingen",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Stuttgart Airport, use the airport rail/bus pages or railway planner to find the current connection toward Metzingen station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Metzingen station, continue to Outletcity Metzingen by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "metzingen-station-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "station",
originId: "metzingen-station",
transportationType: "bus",
title: "Metzingen station to Outletcity Metzingen",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Metzingen station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Outletcity Metzingen." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-direct-shuttle",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "shuttle",
title: "Stuttgart direct shuttle to Outletcity Metzingen",
estimatedDuration: "Check official shuttle timetable",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Open the official Outletcity Metzingen shuttle or getting-here page." },
{ order: 2, description: "Book or reserve only through the official outlet/operator link when required." },
{ order: 3, description: "Arrive at the confirmed Stuttgart pickup point early." },
{ order: 4, description: "Ride directly to Outletcity Metzingen and keep the return departure time available." },
{ order: 5, description: "If the shuttle is not operating on your date, use the train/public transport guide instead." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-public-transport",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "bus",
title: "Public transport to Outletcity Metzingen",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Stuttgart to Outletcity Metzingen." },
{ order: 2, description: "Enter Metzingen station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-by-car",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "taxi",
title: "Driving to Outletcity Metzingen",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Outletcity Metzingen address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-parking",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "walking",
title: "Parking guidance for Outletcity Metzingen",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Outletcity Metzingen parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "outletcity-metzingen-tickets-and-return",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Outletcity Metzingen",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "munich-city-center-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "train",
title: "Munich city center to Ingolstadt Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Ingolstadt Village travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Munich city center towards Ingolstadt Hbf." },
{ order: 3, description: "Continue from Ingolstadt Hbf to Ingolstadt Village by bus, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official Village pages confirm Shopping Express from Munich and back Monday to Saturday, train access, complimentary parking and EV charging; train page confirms bus 22 from Hbf and bus 20 from ZOB/North Station." },
],
updatedAt,
},
{
guideId: "munich-airport-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "airport",
originId: "munich-airport",
transportationType: "train",
title: "Munich Airport to Ingolstadt Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Munich Airport, use the airport rail/bus pages or railway planner to find the current connection toward Ingolstadt Hbf." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Ingolstadt Hbf, continue to Ingolstadt Village by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "ingolstadt-hbf-to-ingolstadt-village",
outletId: "ingolstadt-village",
originType: "station",
originId: "ingolstadt-hbf",
transportationType: "bus",
title: "Ingolstadt Hbf to Ingolstadt Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Ingolstadt Hbf and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Ingolstadt Village." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-direct-shuttle",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "shuttle",
title: "Munich direct shuttle to Ingolstadt Village",
estimatedDuration: "Check official shuttle timetable",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Open the official Ingolstadt Village shuttle or getting-here page." },
{ order: 2, description: "Book or reserve only through the official outlet/operator link when required." },
{ order: 3, description: "Arrive at the confirmed Munich pickup point early." },
{ order: 4, description: "Ride directly to Ingolstadt Village and keep the return departure time available." },
{ order: 5, description: "If the shuttle is not operating on your date, use the train/public transport guide instead." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-public-transport",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "bus",
title: "Public transport to Ingolstadt Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Munich to Ingolstadt Village." },
{ order: 2, description: "Enter Ingolstadt Hbf or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-by-car",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "taxi",
title: "Driving to Ingolstadt Village",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Ingolstadt Village address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-parking",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "walking",
title: "Parking guidance for Ingolstadt Village",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Ingolstadt Village parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "ingolstadt-village-tickets-and-return",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Ingolstadt Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "frankfurt-city-center-to-wertheim-village",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt city center to Wertheim Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Wertheim Village travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Frankfurt city center towards Wertheim station." },
{ order: 3, description: "Continue from Wertheim station to Wertheim Village by bus, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official Village pages confirm Shopping Express from Frankfurt and back, train access from Frankfurt/Würzburg, complimentary parking and EV charging; exact local connections must be checked with operators." },
],
updatedAt,
},
{
guideId: "frankfurt-airport-to-wertheim-village",
outletId: "wertheim-village",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "train",
title: "Frankfurt Airport to Wertheim Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Frankfurt Airport, use the airport rail/bus pages or railway planner to find the current connection toward Wertheim station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Wertheim station, continue to Wertheim Village by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "wertheim-station-to-wertheim-village",
outletId: "wertheim-village",
originType: "station",
originId: "wertheim-station",
transportationType: "bus",
title: "Wertheim station to Wertheim Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Wertheim station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Wertheim Village." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "wertheim-village-direct-shuttle",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "shuttle",
title: "Frankfurt direct shuttle to Wertheim Village",
estimatedDuration: "Check official shuttle timetable",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Open the official Wertheim Village shuttle or getting-here page." },
{ order: 2, description: "Book or reserve only through the official outlet/operator link when required." },
{ order: 3, description: "Arrive at the confirmed Frankfurt pickup point early." },
{ order: 4, description: "Ride directly to Wertheim Village and keep the return departure time available." },
{ order: 5, description: "If the shuttle is not operating on your date, use the train/public transport guide instead." },
],
updatedAt,
},
{
guideId: "wertheim-village-public-transport",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "bus",
title: "Public transport to Wertheim Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Frankfurt to Wertheim Village." },
{ order: 2, description: "Enter Wertheim station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "wertheim-village-by-car",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "taxi",
title: "Driving to Wertheim Village",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Wertheim Village address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "wertheim-village-parking",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "walking",
title: "Parking guidance for Wertheim Village",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Wertheim Village parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "wertheim-village-tickets-and-return",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Wertheim Village",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "berlin-city-center-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "shuttle",
title: "Berlin city center to Designer Outlet Berlin",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Designer Outlet Berlin travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Berlin city center towards Wustermark station." },
{ order: 3, description: "Continue from Wustermark station to Designer Outlet Berlin by shuttle, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official directions page confirms public transport, a free shuttle bus, car access from the B5, 3,000 free parking spaces and EV charging." },
],
updatedAt,
},
{
guideId: "berlin-airport-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "airport",
originId: "berlin-airport",
transportationType: "train",
title: "Berlin Brandenburg Airport to Designer Outlet Berlin",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Berlin Brandenburg Airport, use the airport rail/bus pages or railway planner to find the current connection toward Wustermark station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Wustermark station, continue to Designer Outlet Berlin by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "wustermark-station-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "station",
originId: "wustermark-station",
transportationType: "shuttle",
title: "Wustermark station to Designer Outlet Berlin",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Wustermark station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Designer Outlet Berlin." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-direct-shuttle",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "shuttle",
title: "Berlin direct shuttle to Designer Outlet Berlin",
estimatedDuration: "Check official shuttle timetable",
estimatedCost: "Confirm with provider",
recommended: true,
steps: [
{ order: 1, description: "Open the official Designer Outlet Berlin shuttle or getting-here page." },
{ order: 2, description: "Book or reserve only through the official outlet/operator link when required." },
{ order: 3, description: "Arrive at the confirmed Berlin pickup point early." },
{ order: 4, description: "Ride directly to Designer Outlet Berlin and keep the return departure time available." },
{ order: 5, description: "If the shuttle is not operating on your date, use the train/public transport guide instead." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-public-transport",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "bus",
title: "Public transport to Designer Outlet Berlin",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Berlin to Designer Outlet Berlin." },
{ order: 2, description: "Enter Wustermark station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-by-car",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlet Berlin",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Designer Outlet Berlin address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-parking",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "walking",
title: "Parking guidance for Designer Outlet Berlin",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Designer Outlet Berlin parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "designer-outlet-berlin-tickets-and-return",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Designer Outlet Berlin",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "hamburg-city-center-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "train",
title: "Hamburg city center to Designer Outlet Neumünster",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Designer Outlet Neumünster travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Hamburg city center towards Neumünster station." },
{ order: 3, description: "Continue from Neumünster station to Designer Outlet Neumünster by bus, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official McArthurGlen page confirms the centre address, car directions and public transport section; use operator timetables for exact bus/train times." },
],
updatedAt,
},
{
guideId: "hamburg-airport-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "airport",
originId: "hamburg-airport",
transportationType: "train",
title: "Hamburg Airport to Designer Outlet Neumünster",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Hamburg Airport, use the airport rail/bus pages or railway planner to find the current connection toward Neumünster station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Neumünster station, continue to Designer Outlet Neumünster by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "neumunster-station-to-designer-outlet-neumunster",
outletId: "designer-outlet-neumunster",
originType: "station",
originId: "neumunster-station",
transportationType: "bus",
title: "Neumünster station to Designer Outlet Neumünster",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Neumünster station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Designer Outlet Neumünster." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "designer-outlet-neumunster-public-transport",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "bus",
title: "Public transport to Designer Outlet Neumünster",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Hamburg to Designer Outlet Neumünster." },
{ order: 2, description: "Enter Neumünster station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "designer-outlet-neumunster-by-car",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlet Neumünster",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Designer Outlet Neumünster address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "designer-outlet-neumunster-parking",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "walking",
title: "Parking guidance for Designer Outlet Neumünster",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Designer Outlet Neumünster parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "designer-outlet-neumunster-tickets-and-return",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Designer Outlet Neumünster",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "hannover-city-center-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "train",
title: "Hannover city center to Designer Outlets Wolfsburg",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Designer Outlets Wolfsburg travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Hannover city center towards Wolfsburg Hauptbahnhof." },
{ order: 3, description: "Continue from Wolfsburg Hauptbahnhof to Designer Outlets Wolfsburg by walking, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official outlet travel page confirms parking details and height restrictions; official outlet news confirms Wolfsburg Hauptbahnhof is a short walk from the outlet." },
],
updatedAt,
},
{
guideId: "hannover-airport-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "airport",
originId: "hannover-airport",
transportationType: "train",
title: "Hannover Airport to Designer Outlets Wolfsburg",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Hannover Airport, use the airport rail/bus pages or railway planner to find the current connection toward Wolfsburg Hauptbahnhof." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Wolfsburg Hauptbahnhof, continue to Designer Outlets Wolfsburg by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "wolfsburg-hbf-to-designer-outlets-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "station",
originId: "wolfsburg-hbf",
transportationType: "walking",
title: "Wolfsburg Hauptbahnhof to Designer Outlets Wolfsburg",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Wolfsburg Hauptbahnhof and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Designer Outlets Wolfsburg." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "designer-outlets-wolfsburg-public-transport",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "bus",
title: "Public transport to Designer Outlets Wolfsburg",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Hannover to Designer Outlets Wolfsburg." },
{ order: 2, description: "Enter Wolfsburg Hauptbahnhof or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "designer-outlets-wolfsburg-by-car",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "taxi",
title: "Driving to Designer Outlets Wolfsburg",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Designer Outlets Wolfsburg address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "designer-outlets-wolfsburg-parking",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "walking",
title: "Parking guidance for Designer Outlets Wolfsburg",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Designer Outlets Wolfsburg parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "designer-outlets-wolfsburg-tickets-and-return",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Designer Outlets Wolfsburg",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "cologne-city-center-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "train",
title: "Cologne city center to City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official City Outlet Bad Münstereifel travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Cologne city center towards Bad Münstereifel station." },
{ order: 3, description: "Continue from Bad Münstereifel station to City Outlet Bad Münstereifel by walking, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official outlet directions confirm car access via exit 112, parking areas, Bad Münstereifel station about 150 m from the pedestrian zone, S23 from Euskirchen and RB24 from Cologne to Euskirchen." },
],
updatedAt,
},
{
guideId: "cologne-airport-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "airport",
originId: "cologne-airport",
transportationType: "train",
title: "Cologne Bonn Airport to City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Cologne Bonn Airport, use the airport rail/bus pages or railway planner to find the current connection toward Bad Münstereifel station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Bad Münstereifel station, continue to City Outlet Bad Münstereifel by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "bad-munstereifel-station-to-city-outlet-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "station",
originId: "bad-munstereifel-station",
transportationType: "walking",
title: "Bad Münstereifel station to City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Bad Münstereifel station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to City Outlet Bad Münstereifel." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-public-transport",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "bus",
title: "Public transport to City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Cologne to City Outlet Bad Münstereifel." },
{ order: 2, description: "Enter Bad Münstereifel station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-by-car",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "taxi",
title: "Driving to City Outlet Bad Münstereifel",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official City Outlet Bad Münstereifel address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-parking",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "walking",
title: "Parking guidance for City Outlet Bad Münstereifel",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official City Outlet Bad Münstereifel parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "city-outlet-bad-munstereifel-tickets-and-return",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "train",
title: "Tickets, timetables and return from City Outlet Bad Münstereifel",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "frankfurt-city-center-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt city center to Montabaur The Style Outlets",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Montabaur The Style Outlets travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Frankfurt city center towards Montabaur station." },
{ order: 3, description: "Continue from Montabaur station to Montabaur The Style Outlets by walking, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official outlet site identifies the centre; use DB and local operator journey planners for train/timetable confirmation and confirm parking rules with the outlet before arrival." },
],
updatedAt,
},
{
guideId: "frankfurt-airport-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "train",
title: "Frankfurt Airport to Montabaur The Style Outlets",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Frankfurt Airport, use the airport rail/bus pages or railway planner to find the current connection toward Montabaur station." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Montabaur station, continue to Montabaur The Style Outlets by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "montabaur-station-to-montabaur-the-style-outlets",
outletId: "montabaur-the-style-outlets",
originType: "station",
originId: "montabaur-station",
transportationType: "walking",
title: "Montabaur station to Montabaur The Style Outlets",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Montabaur station and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Montabaur The Style Outlets." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-public-transport",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "bus",
title: "Public transport to Montabaur The Style Outlets",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Frankfurt to Montabaur The Style Outlets." },
{ order: 2, description: "Enter Montabaur station or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-by-car",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "taxi",
title: "Driving to Montabaur The Style Outlets",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Montabaur The Style Outlets address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-parking",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "walking",
title: "Parking guidance for Montabaur The Style Outlets",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Montabaur The Style Outlets parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "montabaur-the-style-outlets-tickets-and-return",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Montabaur The Style Outlets",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
{
guideId: "saarbrucken-city-center-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "train",
title: "Saarbrücken city center to Zweibrücken Fashion Outlet",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Check the official Zweibrücken Fashion Outlet travel page and the relevant public transport operator before departure." },
{ order: 2, description: "Travel from Saarbrücken city center towards Zweibrücken Hbf." },
{ order: 3, description: "Continue from Zweibrücken Hbf to Zweibrücken Fashion Outlet by bus, taxi, or the outlet-confirmed transfer option." },
{ order: 4, description: "Confirm the final stop, platform, pickup point, and return service before you leave." },
{ order: 5, description: "Official centre page confirms Parking & Route address and parking service; VIA Outlets official page confirms A8 exit 34 visibility and bus connection with Zweibrücken Monday to Saturday." },
],
updatedAt,
},
{
guideId: "saarbrucken-airport-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "airport",
originId: "saarbrucken-airport",
transportationType: "train",
title: "Saarbrücken Airport to Zweibrücken Fashion Outlet",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "From Saarbrücken Airport, use the airport rail/bus pages or railway planner to find the current connection toward Zweibrücken Hbf." },
{ order: 2, description: "Change as shown by the official journey planner; do not rely on fixed transfer times." },
{ order: 3, description: "From Zweibrücken Hbf, continue to Zweibrücken Fashion Outlet by the official public transport, shuttle, walking, taxi, or car option." },
{ order: 4, description: "Confirm airport return timing before shopping, especially for evening flights." },
],
updatedAt,
},
{
guideId: "zweibrucken-hbf-to-zweibrucken-fashion-outlet",
outletId: "zweibrucken-fashion-outlet",
originType: "station",
originId: "zweibrucken-hbf",
transportationType: "bus",
title: "Zweibrücken Hbf to Zweibrücken Fashion Outlet",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: true,
steps: [
{ order: 1, description: "Arrive at Zweibrücken Hbf and check the live departure board or operator app." },
{ order: 2, description: "Use the outlet-confirmed last-mile option to Zweibrücken Fashion Outlet." },
{ order: 3, description: "Get off at the stop or entrance named by the official timetable or outlet page." },
{ order: 4, description: "For the return, check the last service before you start shopping." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-public-transport",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "bus",
title: "Public transport to Zweibrücken Fashion Outlet",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Use the official railway/local transport planner for Saarbrücken to Zweibrücken Fashion Outlet." },
{ order: 2, description: "Enter Zweibrücken Hbf or the outlet stop as shown on the official outlet page." },
{ order: 3, description: "Check whether a bus, shuttle, or walk is needed for the final leg." },
{ order: 4, description: "Buy the correct ticket from the transport operator and validate if required." },
{ order: 5, description: "Recheck return services on the day of travel." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-by-car",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "taxi",
title: "Driving to Zweibrücken Fashion Outlet",
estimatedDuration: "Check traffic conditions",
estimatedCost: "Parking/tolls: confirm locally",
recommended: false,
steps: [
{ order: 1, description: "Use the official Zweibrücken Fashion Outlet address from the outlet travel page in your navigation." },
{ order: 2, description: "Follow motorway/local road signs and current traffic restrictions." },
{ order: 3, description: "On arrival, follow outlet parking signs rather than stopping at store entrances." },
{ order: 4, description: "For return, save your parking location and check live traffic before leaving." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-parking",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "walking",
title: "Parking guidance for Zweibrücken Fashion Outlet",
estimatedDuration: "On site",
estimatedCost: "Confirm with outlet",
recommended: false,
steps: [
{ order: 1, description: "Before driving, check the official Zweibrücken Fashion Outlet parking information for current rules, height limits, EV charging and accessibility spaces." },
{ order: 2, description: "Follow signs to the designated visitor car parks." },
{ order: 3, description: "Do not assume parking is free unless the official outlet page confirms it for your date." },
{ order: 4, description: "Keep payment/ticket instructions handy and note the pedestrian route back to the shops." },
],
updatedAt,
},
{
guideId: "zweibrucken-fashion-outlet-tickets-and-return",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "saarbrucken-city-center",
transportationType: "train",
title: "Tickets, timetables and return from Zweibrücken Fashion Outlet",
estimatedDuration: "Check official timetable",
estimatedCost: "Check official fare",
recommended: false,
steps: [
{ order: 1, description: "Confirm outbound and return times with official railway, local transport, airport, shuttle, or outlet pages." },
{ order: 2, description: "Do not rely on historic schedules; check the date-specific timetable." },
{ order: 3, description: "If using a shuttle or coach, confirm whether advance booking is required." },
{ order: 4, description: "Before checkout, recheck the final return connection and allow time to reach the stop or station." },
{ order: 5, description: "If the final connection is missed, use the official operator app, outlet guest services, taxi, or private transfer information." },
],
updatedAt,
},
];
