import type { TransportationGuide } from "./index";

export const germanyTransportationGuides: TransportationGuide[] = [
{
guideId: "munich-to-ingolstadt-shopping-express",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "shuttle",
title: "Munich City Center to Ingolstadt Village by Shopping Express",
estimatedDuration: "60-75 min",
estimatedCost: "€20-25",
recommended: true,
steps: [
{ order: 1, description: "Check the official Shopping Express timetable before your trip." },
{ order: 2, description: "Arrive at the Munich pickup point at least 10 minutes early." },
{ order: 3, description: "Take the direct Shopping Express coach towards Ingolstadt Village." },
{ order: 4, description: "Get off at the Village coach stop." },
{ order: 5, description: "Save the return departure time before you start shopping." },
],
updatedAt: "2026-06-29",
},
{
guideId: "munich-to-ingolstadt-train",
outletId: "ingolstadt-village",
originType: "city_center",
originId: "munich-city-center",
transportationType: "train",
title: "Munich to Ingolstadt Village by Train + Local Transfer",
estimatedDuration: "70-95 min",
estimatedCost: "€20-35",
recommended: false,
steps: [
{ order: 1, description: "Take a regional or intercity train from Munich towards Ingolstadt Hbf." },
{ order: 2, description: "Get off at Ingolstadt Hbf." },
{ order: 3, description: "Continue by local bus, taxi, or ride-share towards Ingolstadt Village." },
{ order: 4, description: "Ask to be dropped near the main entrance or guest services." },
{ order: 5, description: "Check return train connections before late shopping hours." },
],
updatedAt: "2026-06-29",
},
{
guideId: "munich-airport-to-ingolstadt",
outletId: "ingolstadt-village",
originType: "airport",
originId: "munich-airport",
transportationType: "taxi",
title: "Munich Airport to Ingolstadt Village",
estimatedDuration: "50-75 min",
estimatedCost: "€120-200",
recommended: false,
steps: [
{ order: 1, description: "From Munich Airport, choose private transfer, rental car, taxi, or a connection via Munich city center." },
{ order: 2, description: "If using public transport, first connect to Munich city center or Ingolstadt Hbf." },
{ order: 3, description: "Continue by train/local transfer or taxi to Ingolstadt Village." },
{ order: 4, description: "Confirm fare and pickup point in advance if using taxi/private transfer." },
{ order: 5, description: "Allow extra time during weekend shopping traffic." },
],
updatedAt: "2026-06-29",
},
{
guideId: "frankfurt-to-wertheim-shopping-express",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "shuttle",
title: "Frankfurt City Center to Wertheim Village by Shopping Express",
estimatedDuration: "60-75 min",
estimatedCost: "€20-25",
recommended: true,
steps: [
{ order: 1, description: "Check the official Shopping Express timetable before your trip." },
{ order: 2, description: "Arrive at the Frankfurt pickup point at least 10 minutes early." },
{ order: 3, description: "Take the direct Shopping Express coach towards Wertheim Village." },
{ order: 4, description: "Get off at the Village coach stop." },
{ order: 5, description: "Save the return departure time before you start shopping." },
],
updatedAt: "2026-06-29",
},
{
guideId: "frankfurt-to-wertheim-train",
outletId: "wertheim-village",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt to Wertheim Village by Train + Local Transfer",
estimatedDuration: "90-130 min",
estimatedCost: "€20-40",
recommended: false,
steps: [
{ order: 1, description: "Take a train from Frankfurt towards Wertheim or a suitable connecting station." },
{ order: 2, description: "Check whether a change is required before boarding." },
{ order: 3, description: "From Wertheim station, continue by local bus, taxi, or ride-share to Wertheim Village." },
{ order: 4, description: "Get off near the Village entrance or guest services." },
{ order: 5, description: "Check return train connections before late shopping hours." },
],
updatedAt: "2026-06-29",
},
{
guideId: "frankfurt-airport-to-wertheim",
outletId: "wertheim-village",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "taxi",
title: "Frankfurt Airport to Wertheim Village",
estimatedDuration: "60-90 min",
estimatedCost: "€140-230",
recommended: false,
steps: [
{ order: 1, description: "From Frankfurt Airport, choose private transfer, rental car, taxi, or a connection via Frankfurt city center." },
{ order: 2, description: "If using public transport, first connect to Frankfurt city center." },
{ order: 3, description: "Continue by Shopping Express or train + local transfer to Wertheim Village." },
{ order: 4, description: "If using taxi/private transfer, confirm fare and pickup point in advance." },
{ order: 5, description: "Allow extra time during weekend shopping traffic." },
],
updatedAt: "2026-06-29",
},
{
guideId: "stuttgart-to-outletcity-metzingen-shuttle",
outletId: "outletcity-metzingen",
originType: "city_center",
originId: "stuttgart-city-center",
transportationType: "shuttle",
title: "Stuttgart City Center to Outletcity Metzingen by Shopping Shuttle",
estimatedDuration: "40 min",
estimatedCost: "From €10",
recommended: true,
steps: [
{ order: 1, description: "Go to the Shopping Shuttle departure point in Stuttgart city center." },
{ order: 2, description: "Board the Outletcity Metzingen Shopping Shuttle." },
{ order: 3, description: "Travel directly to Outletcity Metzingen." },
{ order: 4, description: "Get off near the Welcome Centre and follow signs to the main shopping area." },
],
updatedAt: "2026-07-01",
},
{
guideId: "stuttgart-hbf-to-outletcity-metzingen-train",
outletId: "outletcity-metzingen",
originType: "station",
originId: "stuttgart-hbf",
transportationType: "train",
title: "Stuttgart Central Station to Outletcity Metzingen by Train",
estimatedDuration: "35-45 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Go to Stuttgart Hauptbahnhof." },
{ order: 2, description: "Take a regional train towards Metzingen." },
{ order: 3, description: "Get off at Metzingen station." },
{ order: 4, description: "Walk approximately 10 minutes to Outletcity Metzingen or use a local transfer if available." },
],
updatedAt: "2026-07-01",
},
{
guideId: "stuttgart-airport-to-outletcity-metzingen",
outletId: "outletcity-metzingen",
originType: "airport",
originId: "stuttgart-airport",
transportationType: "taxi",
title: "Stuttgart Airport to Outletcity Metzingen by Taxi or Car",
estimatedDuration: "25-35 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Exit Stuttgart Airport and follow signs for taxis, rental cars, or ride services." },
{ order: 2, description: "Travel via B27 and B312 towards Metzingen." },
{ order: 3, description: "Follow signs for Outletcity Metzingen." },
{ order: 4, description: "Use one of the official Outletcity parking areas." },
],
updatedAt: "2026-07-01",
},
{
guideId: "berlin-city-center-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "city_center",
originId: "berlin-city-center",
transportationType: "shuttle",
title: "Berlin City Center to Designer Outlet Berlin",
estimatedDuration: "35-45 min",
estimatedCost: "€10-15",
recommended: true,
steps: [
{ order: 1, description: "Go to the official shopping shuttle departure point." },
{ order: 2, description: "Board the shuttle to Designer Outlet Berlin." },
{ order: 3, description: "Travel directly to Wustermark." },
{ order: 4, description: "Arrive at the main entrance." }
],
updatedAt: "2026-07-01",
},
{
guideId: "berlin-airport-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "airport",
originId: "berlin-airport",
transportationType: "taxi",
title: "Berlin Brandenburg Airport to Designer Outlet Berlin",
estimatedDuration: "45-60 min",
estimatedCost: "€60-90",
recommended: true,
steps: [
{ order: 1, description: "Exit Berlin Brandenburg Airport." },
{ order: 2, description: "Take a taxi, rental car or ride service." },
{ order: 3, description: "Drive towards Wustermark." },
{ order: 4, description: "Follow signs to Designer Outlet Berlin." }
],
updatedAt: "2026-07-01",
},
{
guideId: "wustermark-station-to-designer-outlet-berlin",
outletId: "designer-outlet-berlin",
originType: "station",
originId: "wustermark-station",
transportationType: "bus",
title: "Wustermark Station to Designer Outlet Berlin",
estimatedDuration: "10-15 min",
estimatedCost: "€2-4",
recommended: true,
steps: [
{ order: 1, description: "Exit Wustermark station." },
{ order: 2, description: "Take the local bus towards the outlet." },
{ order: 3, description: "Get off at Designer Outlet Berlin." }
],
updatedAt: "2026-07-01",
},
{
guideId: "hamburg-to-neumunster-train",
outletId: "designer-outlet-neumunster",
originType: "city_center",
originId: "hamburg-city-center",
transportationType: "train",
title: "Hamburg City Center to Designer Outlet Neumünster",
estimatedDuration: "60-75 min",
estimatedCost: "€15-30",
recommended: true,
steps: [
{ order: 1, description: "Go to Hamburg Hauptbahnhof." },
{ order: 2, description: "Take a regional train towards Neumünster." },
{ order: 3, description: "Get off at Neumünster station." },
{ order: 4, description: "Continue to the outlet by local bus or taxi." }
],
updatedAt: "2026-07-01",
},
{
guideId: "hamburg-airport-to-neumunster",
outletId: "designer-outlet-neumunster",
originType: "airport",
originId: "hamburg-airport",
transportationType: "taxi",
title: "Hamburg Airport to Designer Outlet Neumünster",
estimatedDuration: "50-70 min",
estimatedCost: "€100-160",
recommended: true,
steps: [
{ order: 1, description: "Exit Hamburg Airport." },
{ order: 2, description: "Take a taxi, rental car or private transfer." },
{ order: 3, description: "Drive north towards Neumünster." },
{ order: 4, description: "Follow signs to Designer Outlet Neumünster." }
],
updatedAt: "2026-07-01",
},
{
guideId: "neumunster-station-to-outlet",
outletId: "designer-outlet-neumunster",
originType: "station",
originId: "neumunster-station",
transportationType: "bus",
title: "Neumünster Station to Designer Outlet Neumünster",
estimatedDuration: "10-20 min",
estimatedCost: "€2-5",
recommended: true,
steps: [
{ order: 1, description: "Exit Neumünster station." },
{ order: 2, description: "Take a local bus or taxi towards the outlet." },
{ order: 3, description: "Arrive at Designer Outlet Neumünster." }
],
updatedAt: "2026-07-01",
},
{
guideId: "frankfurt-to-montabaur",
outletId: "montabaur-the-style-outlets",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt to Montabaur The Style Outlets",
estimatedDuration: "60-75 min",
estimatedCost: "€20-40",
recommended: true,
steps: [
{ order: 1, description: "Go to Frankfurt Hauptbahnhof." },
{ order: 2, description: "Take an ICE train to Montabaur." },
{ order: 3, description: "Continue by taxi or local bus to the outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "frankfurt-airport-to-montabaur",
outletId: "montabaur-the-style-outlets",
originType: "airport",
originId: "frankfurt-airport",
transportationType: "taxi",
title: "Frankfurt Airport to Montabaur",
estimatedDuration: "60 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Leave Frankfurt Airport." },
{ order: 2, description: "Drive or take a taxi to Montabaur." }
],
updatedAt: "2026-07-01",
},
{
guideId: "frankfurt-to-zweibrucken",
outletId: "zweibrucken-fashion-outlet",
originType: "city_center",
originId: "frankfurt-city-center",
transportationType: "train",
title: "Frankfurt to Zweibrücken Fashion Outlet",
estimatedDuration: "70-90 min",
estimatedCost: "€15-30",
recommended: true,
steps: [
{ order: 1, description: "Take a train towards Zweibrücken." },
{ order: 2, description: "Continue by local bus to the outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "saarbrucken-airport-to-zweibrucken",
outletId: "zweibrucken-fashion-outlet",
originType: "airport",
originId: "saarbrucken-airport",
transportationType: "taxi",
title: "Saarbrücken Airport to Zweibrücken Fashion Outlet",
estimatedDuration: "35-45 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Exit Saarbrücken Airport." },
{ order: 2, description: "Take a taxi or rental car to the outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "cologne-to-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "city_center",
originId: "cologne-city-center",
transportationType: "train",
title: "Cologne to City Outlet Bad Münstereifel",
estimatedDuration: "70-90 min",
estimatedCost: "€15-30",
recommended: true,
steps: [
{ order: 1, description: "Take a train from Cologne towards Euskirchen." },
{ order: 2, description: "Transfer to Bad Münstereifel." },
{ order: 3, description: "Walk to the outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "cologne-airport-to-bad-munstereifel",
outletId: "city-outlet-bad-munstereifel",
originType: "airport",
originId: "cologne-airport",
transportationType: "taxi",
title: "Cologne Airport to City Outlet Bad Münstereifel",
estimatedDuration: "60-70 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Take a taxi or rental car from Cologne Bonn Airport." },
{ order: 2, description: "Drive directly to Bad Münstereifel." }
],
updatedAt: "2026-07-01",
},
{
guideId: "hannover-to-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "city_center",
originId: "hannover-city-center",
transportationType: "train",
title: "Hannover to Designer Outlets Wolfsburg",
estimatedDuration: "60-80 min",
estimatedCost: "€15-30",
recommended: true,
steps: [
{ order: 1, description: "Take a train to Wolfsburg Hauptbahnhof." },
{ order: 2, description: "Walk a few minutes to the outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "hannover-airport-to-wolfsburg",
outletId: "designer-outlets-wolfsburg",
originType: "airport",
originId: "hannover-airport",
transportationType: "taxi",
title: "Hannover Airport to Designer Outlets Wolfsburg",
estimatedDuration: "60-70 min",
estimatedCost: "Varies",
recommended: true,
steps: [
{ order: 1, description: "Take a taxi or rental car from Hannover Airport." },
{ order: 2, description: "Drive directly to Designer Outlets Wolfsburg." }
],
updatedAt: "2026-07-01",
},
];
