import type { TransportationGuide } from "./index";

export const greeceTransportationGuides: TransportationGuide[] = [
  {
    guideId: "designer-outlet-athens-city-center-car",
    outletId: "designer-outlet-athens",
    originType: "city_center",
    originId: "athens-city-center",
    transportationType: "taxi",
    title: "Athens City Centre to Designer Outlet Athens by Car or Taxi",
    estimatedDuration: "",
    estimatedCost: "Approx. EUR 35–55",
    recommended: false,
    steps: [
      { order: 1, description: "Board a licensed taxi at Syntagma Square and confirm that the meter is operating before leaving." },
      { order: 2, description: "Drive or take a licensed taxi/private transfer toward Spata and the Yalou commercial area, following signs for Designer Outlet Athens." },
      { order: 3, description: "The fare estimate covers the taxi from Syntagma Square; waiting, night, booking, toll and luggage supplements may vary, and free parking is excluded." },
      { order: 4, description: "If using a taxi or app ride, agree a return pickup point near the main entrance before shopping." },
      { order: 5, description: "For the return to Athens, allow extra time for Attiki Odos and city-centre traffic." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "designer-outlet-athens-airport-car",
    outletId: "designer-outlet-athens",
    originType: "airport",
    originId: "athens-airport",
    transportationType: "taxi",
    title: "Athens Airport to Designer Outlet Athens by Taxi or Rental Car",
    estimatedDuration: "15 min from Athens Airport",
    estimatedCost: "Taxi/private transfer confirm with provider; parking complimentary",
    recommended: false,
    steps: [
      { order: 1, description: "From Athens International Airport, use an official taxi, rental car, or pre-booked transfer; the outlet operator describes the centre as about 15 minutes from the airport." },
      { order: 2, description: "Follow road signs toward Spata, Yalou, and Designer Outlet Athens." },
      { order: 3, description: "Park in the outlet customer parking or agree a clearly signed drop-off point with your driver." },
      { order: 4, description: "For a flight connection after shopping, arrange the return taxi or car pickup before entering the shops and allow airport security/check-in time." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "designer-outlet-athens-metro-bus",
    outletId: "designer-outlet-athens",
    originType: "city_center",
    originId: "athens-city-center",
    transportationType: "metro",
    title: "Syntagma to Designer Outlet Athens by Metro and Bus 319",
    estimatedDuration: "",
    estimatedCost: "Approx. EUR 1.20–2.40",
    recommended: true,
    steps: [
      { order: 1, description: "At Syntagma, validate an OASA adult ticket and take Metro Line 3 toward Doukissis Plakentias." },
      { order: 2, description: "At Doukissis Plakentias, transfer from STASY Metro Line 3 to OSY Bus 319." },
      { order: 3, description: "Ride Bus 319 to the officially published Εκπτωτικό Χωριό (Designer Outlet) stop." },
      { order: 4, description: "The fare allows for a second standard ticket if the complete journey exceeds the first ticket's 90-minute validity; final pedestrian access is free." },
      { order: 5, description: "Check OASA Telematics for the current Bus 319 departure and return service before travel." },
    ],
    updatedAt: "2026-08-04",
  },
];
