import type { TransportationGuide } from "./index";

export const greeceTransportationGuides: TransportationGuide[] = [
  {
    guideId: "designer-outlet-athens-city-center-car",
    outletId: "designer-outlet-athens",
    originType: "city_center",
    originId: "athens-city-center",
    transportationType: "taxi",
    title: "Athens City Centre to Designer Outlet Athens by Car or Taxi",
    estimatedDuration: "30 min from Athens centre",
    estimatedCost: "Parking complimentary; taxi/private transfer confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Check Designer Outlet Athens' official centre information for current access details and opening hours before leaving." },
      { order: 2, description: "Drive or take a licensed taxi/private transfer toward Spata and the Yalou commercial area, following signs for Designer Outlet Athens." },
      { order: 3, description: "Use the outlet's customer parking areas on arrival and note the entrance nearest your parking zone." },
      { order: 4, description: "If using a taxi or app ride, agree a return pickup point near the main entrance before shopping." },
      { order: 5, description: "For the return to Athens, allow extra time for Attiki Odos and city-centre traffic." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "designer-outlet-athens-airport-car",
    outletId: "designer-outlet-athens",
    originType: "airport",
    originId: "athens-airport",
    transportationType: "taxi",
    title: "Athens Airport to Designer Outlet Athens by Taxi or Rental Car",
    estimatedDuration: "15 min from Athens Airport",
    estimatedCost: "Taxi/private transfer confirm with provider; parking complimentary",
    recommended: true,
    steps: [
      { order: 1, description: "From Athens International Airport, use an official taxi, rental car, or pre-booked transfer; the outlet operator describes the centre as about 15 minutes from the airport." },
      { order: 2, description: "Follow road signs toward Spata, Yalou, and Designer Outlet Athens." },
      { order: 3, description: "Park in the outlet customer parking or agree a clearly signed drop-off point with your driver." },
      { order: 4, description: "For a flight connection after shopping, arrange the return taxi or car pickup before entering the shops and allow airport security/check-in time." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "designer-outlet-athens-metro-bus",
    outletId: "designer-outlet-athens",
    originType: "station",
    originId: "athens-public-transport",
    transportationType: "bus",
    title: "Athens Public Transport to Designer Outlet Athens",
    estimatedDuration: "≈60–90 min from central Athens (estimated)",
    estimatedCost: "Check official OASA fare and timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official OASA journey planner for the current metro, suburban rail, and bus combination to the Spata/Yalou area before you travel." },
      { order: 2, description: "From central Athens, travel by metro or suburban rail toward an eastern Athens interchange such as Doukissis Plakentias, Pallini, or the airport corridor as directed by OASA." },
      { order: 3, description: "Transfer to the official local bus connection shown by OASA for Designer Outlet Athens or the nearest signed Spata/Yalou stop." },
      { order: 4, description: "Walk only on signed pedestrian routes from the stop to the outlet entrance." },
      { order: 5, description: "Before shopping, check the return bus and metro times; use a taxi back to the airport or Athens if the last public transport connection is too early." },
    ],
    updatedAt: "2026-07-03",
  },
];
