import type { TransportationGuide } from "./index";

export const irelandTransportationGuides: TransportationGuide[] = [
  {
    guideId: "kildare-village-dublin-heuston-train-shuttle",
    outletId: "kildare-village",
    originType: "city_center",
    originId: "dublin-city-center",
    transportationType: "train",
    title: "Dublin Heuston to Kildare Village by Irish Rail and Complimentary Shuttle",
    estimatedDuration: "35 min train from Dublin Heuston plus short complimentary shuttle",
    estimatedCost: "Check official Irish Rail fare; Village station shuttle is complimentary",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Kildare Village train guidance and Irish Rail timetable for Dublin Heuston to Kildare on your shopping date." },
      { order: 2, description: "Travel from Dublin city centre to Dublin Heuston and board an Irish Rail service to Kildare; the Village notes the train journey takes 35 minutes from Heuston with frequent services." },
      { order: 3, description: "At Kildare station, use the complimentary Kildare Village shuttle or follow the signed local last-mile option to the Village entrance." },
      { order: 4, description: "On arrival, note the shuttle drop-off point and Guest Services location before shopping." },
      { order: 5, description: "For the return, confirm the last practical shuttle back to Kildare station and your Irish Rail departure to Dublin before leaving the shops." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "kildare-village-dublin-airport-coach",
    outletId: "kildare-village",
    originType: "airport",
    originId: "dublin-airport",
    transportationType: "bus",
    title: "Dublin Airport to Kildare Village by Coach or via Dublin Heuston",
    estimatedDuration: "≈60–90 min direct coach or ≈90–120 min via Dublin Heuston (estimated)",
    estimatedCost: "Check official coach or Irish Rail fare",
    recommended: false,
    steps: [
      { order: 1, description: "Use Kildare Village's official coach guidance and the current airport coach operator timetable before travel; services and pickup points can change." },
      { order: 2, description: "If a direct airport coach fits your flight, board at the signed Dublin Airport coach stop with your booking or payment method ready." },
      { order: 3, description: "If no direct coach fits, take an official airport bus to Dublin city centre or Heuston, then use Irish Rail to Kildare station and the complimentary Village shuttle." },
      { order: 4, description: "Keep luggage manageable and confirm where coaches or taxis drop off at Kildare Village." },
      { order: 5, description: "For the return to the airport, book the coach or rail-and-airport-bus connection before shopping and allow a flight check-in buffer." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "kildare-village-car-parking",
    outletId: "kildare-village",
    originType: "city_center",
    originId: "dublin-city-center",
    transportationType: "taxi",
    title: "Dublin to Kildare Village by Car with Complimentary Parking",
    estimatedDuration: "60 min from central Dublin",
    estimatedCost: "Parking complimentary; fuel/tolls vary",
    recommended: false,
    steps: [
      { order: 1, description: "Follow Kildare Village's official car guidance toward Nurney Road, Kildare Town, using the M7 and the signed Kildare access route." },
      { order: 2, description: "Use the Village's complimentary parking areas on arrival and note your car park zone before entering the open-air streets." },
      { order: 3, description: "If using a taxi or private transfer, agree the fare, waiting terms, and return pickup point before leaving the vehicle." },
      { order: 4, description: "For the return to Dublin, allow extra time for M7 and city-centre traffic, especially weekends and sale periods." },
    ],
    updatedAt: "2026-07-03",
  },
];
