import type { TransportationGuide } from "./index";

export const italyTransportationGuides: TransportationGuide[] = [
  {
    guideId: "barberino-florence-smn-shuttle",
    outletId: "barberino",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "shuttle",
    title: "Florence Santa Maria Novella to Barberino Outlet by Official Shuttle",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Barberino shuttle page for the current seasonal schedule before leaving." },
      { order: 2, description: "Go to Firenze Santa Maria Novella station and reach the Sightseeing Visitor Center in the main ticket salesroom at least 20 minutes before departure." },
      { order: 3, description: "Board the official Florence shuttle to Barberino Outlet; the outlet also notes a combined train + shuttle ticket option." },
      { order: 4, description: "On arrival, follow outlet signs from the shuttle stop to the shops and services." },
      { order: 5, description: "Before shopping, confirm the same-day return shuttle time for the current season." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "barberino-bologna-weekend-shuttle",
    outletId: "barberino",
    originType: "city_center",
    originId: "bologna-city-center",
    transportationType: "shuttle",
    title: "Bologna Bus Station to Barberino Outlet by Weekend Shuttle",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Tickets must be purchased online",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the official Barberino Bologna shuttle is operating on your travel date; the outlet lists it for Saturdays, Sundays, and public holidays." },
      { order: 2, description: "Buy the ticket online through the official link before travel." },
      { order: 3, description: "Go to Bologna bus station at Piazza XX Settembre 6, next to Bologna Centrale, and look for the departure near platform 25." },
      { order: 4, description: "Take the direct shuttle to Barberino Outlet." },
      { order: 5, description: "Confirm the fixed return departure from Barberino Outlet before you start shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "barberino-florence-airport-car",
    outletId: "barberino",
    originType: "airport",
    originId: "florence-airport",
    transportationType: "taxi",
    title: "Florence Airport to Barberino Outlet by Taxi or Private Transfer",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence Airport, choose a taxi, rental car, or pre-booked private transfer." },
      { order: 2, description: "Confirm the fare, meeting point, and return pickup with the provider before departure." },
      { order: 3, description: "Travel toward Barberino di Mugello and follow road signs for Barberino Outlet." },
      { order: 4, description: "Use the outlet parking or the agreed drop-off point near the main entrance." },
      { order: 5, description: "For a public-transport option, first reach Firenze Santa Maria Novella and use the official Barberino shuttle timetable." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "castel-romano-termini-shuttle",
    outletId: "castel-romano",
    originType: "city_center",
    originId: "rome-city-center",
    transportationType: "shuttle",
    title: "Rome Termini to Castel Romano by Official Shuttle",
    estimatedDuration: "About 30 minutes by road; check official timetable",
    estimatedCost: "€18 round trip adult; confirm official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Castel Romano shuttle service page for current times and ticket conditions." },
      { order: 2, description: "Go to the Termini shuttle departure point at Via Giolitti 48." },
      { order: 3, description: "Board the Castel Romano shuttle for the direct trip to Via Ponte di Piscina Cupa 64." },
      { order: 4, description: "On arrival, follow signs from the shuttle stop to the main entrance." },
      { order: 5, description: "Before shopping, confirm the official return departures to Termini and keep your ticket available." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "castel-romano-eur-fermi-shuttle",
    outletId: "castel-romano",
    originType: "city_center",
    originId: "rome-eur-fermi",
    transportationType: "shuttle",
    title: "EUR Fermi to Castel Romano by Official Shuttle",
    estimatedDuration: "Check official timetable",
    estimatedCost: "€13 round trip adult; confirm official ticket details",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official shuttle timetable for the EUR Fermi route on your shopping date." },
      { order: 2, description: "Go to the EUR Fermi shuttle departure point on Viale America 266, above EUR Fermi station." },
      { order: 3, description: "Board the official shuttle to Castel Romano Designer Outlet." },
      { order: 4, description: "Get off at the outlet stop and follow signs to the shops." },
      { order: 5, description: "Confirm the same-day return departures to EUR Fermi before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "castel-romano-airport-car",
    outletId: "castel-romano",
    originType: "airport",
    originId: "rome-airports",
    transportationType: "taxi",
    title: "Rome Airports to Castel Romano by Taxi, Rental Car, or Private Transfer",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Fiumicino or Ciampino, choose taxi, rental car, or an official/private transfer provider." },
      { order: 2, description: "Confirm the fare, meeting point, luggage capacity, and return pickup before departure." },
      { order: 3, description: "Travel toward Castel Romano; the outlet official page notes access from Rome by Via Pontina or Via di Trigoria." },
      { order: 4, description: "Use the outlet parking areas or the agreed drop-off point at Via Ponte di Piscina Cupa 64." },
      { order: 5, description: "If avoiding a direct road transfer, first reach Rome city center and use the official Termini or EUR Fermi shuttle." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "fidenza-milan-shopping-express",
    outletId: "fidenza-village",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "shuttle",
    title: "Milan to Fidenza Village by Official Shopping Express",
    estimatedDuration: "About 90 minutes each way; check official timetable",
    estimatedCost: "Adults €10; children 5-11 €5; infants 0-4 free",
    recommended: true,
    steps: [
      { order: 1, description: "Check and book the official Fidenza Village Shopping Express before travel." },
      { order: 2, description: "Go to Piazza della Repubblica 5 at the corner with Via Turati, in front of the newsstand and near MM3." },
      { order: 3, description: "Board the Shopping Express from Milan to Fidenza Village." },
      { order: 4, description: "On arrival, follow Village signs from the coach stop to the entrance and guest services." },
      { order: 5, description: "Use the booked return from Fidenza Village to Piazza della Repubblica, allowing for traffic variation." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "fidenza-train-local-transfer",
    outletId: "fidenza-village",
    originType: "station",
    originId: "fidenza-station",
    transportationType: "train",
    title: "Fidenza Station to Fidenza Village by Local Transfer",
    estimatedDuration: "Confirm with local provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Take a train to Fidenza station using the official rail timetable for your starting city." },
      { order: 2, description: "At Fidenza station, confirm the current local bus, taxi, or Village transfer option before leaving the station." },
      { order: 3, description: "Continue to Fidenza Village by the confirmed local transfer." },
      { order: 4, description: "On arrival, note where the return transfer leaves from." },
      { order: 5, description: "Check the last return connection to Fidenza station before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "fidenza-airports-via-milan",
    outletId: "fidenza-village",
    originType: "airport",
    originId: "milan-airports",
    transportationType: "shuttle",
    title: "Milan Airports to Fidenza Village via Milan Shopping Express",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check airport transfer plus Shopping Express ticket",
    recommended: false,
    steps: [
      { order: 1, description: "From Milan Malpensa, Linate, or Bergamo, first use the official airport connection to reach Milan city center." },
      { order: 2, description: "Allow enough transfer time to reach Piazza della Repubblica 5 for the Shopping Express departure." },
      { order: 3, description: "Book and take the official Shopping Express to Fidenza Village." },
      { order: 4, description: "For the return, confirm both the Shopping Express arrival time in Milan and your onward airport connection." },
      { order: 5, description: "If the coach timing does not fit your flight, confirm a private transfer or rail connection with the provider." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "la-reggia-naples-public-transport",
    outletId: "la-reggia",
    originType: "city_center",
    originId: "naples-city-center",
    transportationType: "train",
    title: "Naples to La Reggia by Public Transport",
    estimatedDuration: "Confirm official timetable",
    estimatedCost: "Confirm with rail and local bus providers",
    recommended: true,
    steps: [
      { order: 1, description: "Use the official La Reggia plan-your-visit page to confirm public-transport guidance before travel." },
      { order: 2, description: "Check the official rail timetable from Naples toward Caserta or Marcianise for your travel date." },
      { order: 3, description: "At the arrival station, confirm the current local bus, taxi, or private-transfer option to La Reggia Designer Outlet." },
      { order: 4, description: "Travel to S.P. 336 ex-Sannitica, 81025 Marcianise, and follow signs to the outlet entrance." },
      { order: 5, description: "Before shopping, confirm the last local return connection to your station and Naples." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "la-reggia-naples-car",
    outletId: "la-reggia",
    originType: "city_center",
    originId: "naples-city-center",
    transportationType: "taxi",
    title: "Naples to La Reggia by Car, Taxi, or Private Transfer",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Choose rental car, taxi, or private transfer from Naples." },
      { order: 2, description: "Confirm the fare, pickup point, motorway toll handling, and return pickup before departure." },
      { order: 3, description: "Travel toward Marcianise; the official outlet page places La Reggia adjacent to the A1 motorway at the Caserta Sud exit." },
      { order: 4, description: "Use the outlet parking area or the agreed drop-off at S.P. 336 ex-Sannitica." },
      { order: 5, description: "Allow extra time for motorway and shopping-period traffic on the return." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "la-reggia-naples-airport-transfer",
    outletId: "la-reggia",
    originType: "airport",
    originId: "naples-airport",
    transportationType: "taxi",
    title: "Naples Airport to La Reggia by Taxi or Private Transfer",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Naples Airport, choose taxi, rental car, or private transfer." },
      { order: 2, description: "Confirm the fare, meeting point, luggage space, and return pickup with the provider." },
      { order: 3, description: "Travel toward Marcianise and the A1 Caserta Sud area noted on the official outlet page." },
      { order: 4, description: "Use La Reggia parking or the agreed drop-off point at the outlet." },
      { order: 5, description: "If returning to the airport, reconfirm pickup time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "noventa-venice-atvo-direct-bus",
    outletId: "noventa",
    originType: "city_center",
    originId: "venice-city-center",
    transportationType: "bus",
    title: "Venice Piazzale Roma to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "About 90 minutes; check official timetable",
    estimatedCost: "Book online and confirm current fare",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official ATVO Noventa di Piave Designer Outlet timetable and book your seat online; booking is required." },
      { order: 2, description: "Go to the ATVO departure stop at Venezia Piazzale Roma." },
      { order: 3, description: "Board the direct bus to McArthurGlen Designer Outlet Noventa di Piave; the route also serves Mestre railway station and Marco Polo Airport." },
      { order: 4, description: "Get off at the outlet stop and follow signs to the main entrance." },
      { order: 5, description: "Before shopping, confirm your booked return departure to Venezia Piazzale Roma." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "noventa-mestre-atvo-direct-bus",
    outletId: "noventa",
    originType: "station",
    originId: "mestre-station",
    transportationType: "bus",
    title: "Mestre Railway Station to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "About 75 minutes; check official timetable",
    estimatedCost: "Book online and confirm current fare",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official ATVO timetable and reserve the Noventa di Piave Designer Outlet bus." },
      { order: 2, description: "Go to the Mestre railway station ATVO stop shown in the official schedule." },
      { order: 3, description: "Take the direct ATVO bus to McArthurGlen Designer Outlet Noventa di Piave." },
      { order: 4, description: "On arrival, note the exact return stop at the outlet." },
      { order: 5, description: "Use the booked return bus to Mestre railway station and allow for traffic." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "noventa-marco-polo-airport-atvo",
    outletId: "noventa",
    originType: "airport",
    originId: "venice-marco-polo-airport",
    transportationType: "bus",
    title: "Venice Marco Polo Airport to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "About 60 minutes; check official timetable",
    estimatedCost: "Book online and confirm current fare",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official ATVO timetable because the direct outlet bus allows boarding and alighting at Marco Polo Airport." },
      { order: 2, description: "Book your ticket and seat online before travel." },
      { order: 3, description: "Go to the ATVO stop at Marco Polo Airport for the Noventa di Piave Designer Outlet service." },
      { order: 4, description: "Ride directly to the outlet and follow signs from the bus stop to the entrance." },
      { order: 5, description: "Confirm the booked return bus to Marco Polo Airport before shopping, especially if connecting to a flight." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "serravalle-milan-official-shuttle",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "shuttle",
    title: "Milan to Serravalle Designer Outlet by Official Partner Shuttle",
    estimatedDuration: "About 60 minutes by road; check official timetable",
    estimatedCost: "Confirm with official partner",
    recommended: true,
    steps: [
      { order: 1, description: "Check Serravalle's official bus connection page for current partner shuttles, pickup points, fares, and return times." },
      { order: 2, description: "Choose an official partner listed by the outlet, such as Zani Viaggi or Frigerio Viaggi." },
      { order: 3, description: "Go to the confirmed Milan pickup point shown on the partner ticket or timetable." },
      { order: 4, description: "Take the direct shuttle to Serravalle Designer Outlet." },
      { order: 5, description: "Confirm the return departure and any flexible-return conditions with the partner before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "serravalle-train-bus",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "train",
    title: "Milan to Serravalle by Train + Bus or Local Transfer",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Confirm with rail and local provider",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official Serravalle plan-your-visit page and rail timetable to confirm the current train + bus option before travel." },
      { order: 2, description: "Take a train from Milan toward the station indicated by the official connection for Serravalle Designer Outlet." },
      { order: 3, description: "At the station, confirm the current bus, shuttle, or taxi connection to the outlet before leaving the rail area." },
      { order: 4, description: "Continue to Serravalle Designer Outlet and note the return stop." },
      { order: 5, description: "Check the last return bus and train connection before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "serravalle-genoa-car",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "genoa-city-center",
    transportationType: "taxi",
    title: "Genoa to Serravalle Designer Outlet by Car or Taxi",
    estimatedDuration: "About 45 minutes by road; confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Genoa, choose rental car, taxi, or private transfer." },
      { order: 2, description: "Confirm fare, pickup point, motorway tolls, and return pickup with the provider." },
      { order: 3, description: "Travel toward Serravalle Scrivia; the official outlet page notes Genoa is about 45 minutes by car." },
      { order: 4, description: "Follow signs to Serravalle Designer Outlet and use the outlet parking or agreed drop-off point." },
      { order: 5, description: "Allow extra time for motorway traffic on the return." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "serravalle-milan-airports-via-city",
    outletId: "serravalle-designer-outlet",
    originType: "airport",
    originId: "milan-airports",
    transportationType: "shuttle",
    title: "Milan Airports to Serravalle via Milan Partner Shuttle",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check airport transfer plus official partner ticket",
    recommended: false,
    steps: [
      { order: 1, description: "From Milan Malpensa, Linate, or Bergamo, first reach Milan city center using the official airport connection for your airport." },
      { order: 2, description: "Check Serravalle's official bus connection page and book an official partner shuttle from Milan." },
      { order: 3, description: "Allow enough transfer time between the airport connection and the shuttle pickup point." },
      { order: 4, description: "Take the partner shuttle to Serravalle Designer Outlet." },
      { order: 5, description: "For the return, confirm both the shuttle arrival time in Milan and your onward airport connection." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "the-mall-firenze-florence-direct-bus",
    outletId: "the-mall-firenze",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "bus",
    title: "Florence to The Mall Firenze by Official Direct Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Open The Mall Firenze visit page or the official Busitalia The Mall by Bus page to confirm today's timetable and buy tickets." },
      { order: 2, description: "Go to the Florence departure point shown by the official bus provider, near Firenze Santa Maria Novella at the Piazzale Montelungo bus terminal." },
      { order: 3, description: "Board the direct bus to The Mall Firenze." },
      { order: 4, description: "Get off at The Mall Firenze, Via Europa 8, Leccio Reggello, and follow signs to the boutiques." },
      { order: 5, description: "Before shopping, confirm the return bus departure time and whether your ticket is one-way or round-trip." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "the-mall-firenze-florence-airport-via-city",
    outletId: "the-mall-firenze",
    originType: "airport",
    originId: "florence-airport",
    transportationType: "bus",
    title: "Florence Airport to The Mall Firenze via Florence Direct Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check airport transfer plus official bus ticket",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence Airport, first reach central Florence or Firenze Santa Maria Novella using the official airport connection or a taxi." },
      { order: 2, description: "Check The Mall Firenze or Busitalia official direct-bus timetable before leaving the airport." },
      { order: 3, description: "Go to the official Florence direct-bus departure point near Firenze Santa Maria Novella." },
      { order: 4, description: "Take the direct bus to The Mall Firenze, Via Europa 8, Leccio Reggello." },
      { order: 5, description: "Confirm the return bus to Florence and your onward airport connection before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "the-mall-firenze-car-transfer",
    outletId: "the-mall-firenze",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "taxi",
    title: "Florence to The Mall Firenze by Car, Taxi, or Private Transfer",
    estimatedDuration: "Confirm with provider",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Choose rental car, taxi, or private transfer from Florence." },
      { order: 2, description: "Confirm the fare, pickup point, luggage capacity, and return pickup with the provider." },
      { order: 3, description: "Travel to The Mall Firenze at Via Europa 8, 50066 Leccio Reggello (FI)." },
      { order: 4, description: "Use the outlet parking area or agreed drop-off point." },
      { order: 5, description: "If returning by direct bus instead, check the official timetable before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
];
