import type { TransportationGuide } from "./index";

export const italyTransportationGuides: TransportationGuide[] = [
  {
    guideId: "barberino-florence-smn-shuttle",
    outletId: "barberino",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "shuttle",
    title: "Florence SMN to Barberino Outlet by Official Shuttle",
    estimatedDuration: "≈30–40 min (estimated); check official timetable",
    estimatedCost: "Check official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Open Barberino's official shuttle information and confirm the current Florence schedule, ticket rules, and return departures before you travel." },
      { order: 2, description: "Go to Firenze Santa Maria Novella and reach the MySightseeing/Sightseeing Visitor Center meeting point in the station ticket-hall area at least 15–20 minutes before departure." },
      { order: 3, description: "Board the official shuttle to Barberino Designer Outlet and keep your ticket or booking available for inspection." },
      { order: 4, description: "On arrival, follow the outlet signs from the shuttle stop to Guest Services and the shops." },
      { order: 5, description: "Before shopping, confirm the same-day return shuttle time and boarding point so you do not miss the last service back to Florence." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "barberino-bologna-weekend-shuttle",
    outletId: "barberino",
    originType: "city_center",
    originId: "bologna-city-center",
    transportationType: "shuttle",
    title: "Bologna Bus Station to Barberino Outlet by Official Weekend Shuttle",
    estimatedDuration: "≈60–75 min (estimated); check official timetable",
    estimatedCost: "Check official ticket details",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm on Barberino's official access page that the Bologna shuttle is operating on your date; it is normally a limited Saturday, Sunday, and public-holiday service." },
      { order: 2, description: "Buy the ticket through the official booking link before travel, because on-board availability is not guaranteed." },
      { order: 3, description: "Go to Bologna Autostazione at Piazza XX Settembre 6, next to Bologna Centrale, and use the platform shown on the current ticket or timetable." },
      { order: 4, description: "Take the direct shuttle to Barberino Designer Outlet and follow signs from the coach stop to the shopping area." },
      { order: 5, description: "Confirm the fixed return departure from Barberino before shopping, allowing extra time to reach the coach stop." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "barberino-florence-airport-car",
    outletId: "barberino",
    originType: "airport",
    originId: "florence-airport",
    transportationType: "taxi",
    title: "Florence Airport to Barberino Outlet by Taxi, Rental Car, or Private Transfer",
    estimatedDuration: "≈25–40 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence Airport, use a licensed taxi, rental car, or pre-booked private transfer; confirm the fare and luggage space before departure." },
      { order: 2, description: "Travel north toward Barberino di Mugello, following motorway or road signs for Barberino Designer Outlet." },
      { order: 3, description: "Use the outlet parking areas if driving, or agree a drop-off point close to the main entrance with your driver." },
      { order: 4, description: "If returning to the airport, pre-arrange the pickup time before shopping and allow extra time for A1 traffic." },
      { order: 5, description: "For a lower-cost public option, first reach Firenze Santa Maria Novella and use the official outlet shuttle from the station area." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "barberino-florence-car-parking",
    outletId: "barberino",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "taxi",
    title: "Florence to Barberino Outlet by Car with Outlet Parking",
    estimatedDuration: "≈30–45 min (estimated)",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Leave central Florence toward the A1 northbound and follow signs for Barberino di Mugello and Barberino Designer Outlet." },
      { order: 2, description: "Use the official outlet parking on arrival; note your parking area before entering the shops." },
      { order: 3, description: "If using a taxi or private transfer, confirm the fare, waiting policy, and exact return pickup location before leaving the vehicle." },
      { order: 4, description: "For the return, allow extra time at weekends, during sales, and around Florence evening traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "castel-romano-termini-shuttle",
    outletId: "castel-romano",
    originType: "city_center",
    originId: "rome-city-center",
    transportationType: "shuttle",
    title: "Rome Termini to Castel Romano by Official Shuttle",
    estimatedDuration: "About 30 min by road; check official timetable",
    estimatedCost: "€18 round trip adult; confirm official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Check Castel Romano's official shuttle page for current Termini times, ticket conditions, and return departures." },
      { order: 2, description: "Go to the Termini departure point at Via Giolitti 48 and arrive early enough for boarding." },
      { order: 3, description: "Board the official shuttle to Castel Romano Designer Outlet at Via Ponte di Piscina Cupa 64." },
      { order: 4, description: "On arrival, follow signs from the shuttle stop to the main entrance and Guest Services." },
      { order: 5, description: "Before shopping, confirm the return shuttle departure to Termini and keep your ticket available." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "castel-romano-eur-fermi-shuttle",
    outletId: "castel-romano",
    originType: "city_center",
    originId: "rome-eur-fermi",
    transportationType: "shuttle",
    title: "EUR Fermi to Castel Romano by Official Shuttle",
    estimatedDuration: "≈25–35 min (estimated); check official timetable",
    estimatedCost: "€13 round trip adult; under-25 EUR Fermi shuttle noted as free by outlet services; confirm official ticket details",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Castel Romano shuttle timetable for the EUR Fermi route on your shopping date." },
      { order: 2, description: "Go to the EUR Fermi departure point on Viale America 266, above EUR Fermi metro station." },
      { order: 3, description: "Board the official shuttle to Castel Romano Designer Outlet and keep your booking or ticket ready." },
      { order: 4, description: "Get off at the outlet stop and follow signs to the shops." },
      { order: 5, description: "Confirm the same-day return departures to EUR Fermi before shopping." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "castel-romano-airport-car",
    outletId: "castel-romano",
    originType: "airport",
    originId: "rome-airports",
    transportationType: "taxi",
    title: "Rome Airports to Castel Romano by Taxi, Rental Car, or Private Transfer",
    estimatedDuration: "≈20–35 min from Ciampino or ≈25–45 min from Fiumicino (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Fiumicino or Ciampino, choose a licensed taxi, rental car, or pre-booked transfer and confirm the fare, luggage space, meeting point, and return pickup." },
      { order: 2, description: "Travel toward Castel Romano; the outlet's official access guidance notes routes from Rome via Via Pontina or Via di Trigoria." },
      { order: 3, description: "Use the outlet parking areas if driving, or agree a drop-off point at Via Ponte di Piscina Cupa 64." },
      { order: 4, description: "If connecting to a flight after shopping, book the return pickup before entering the outlet and allow a traffic buffer." },
      { order: 5, description: "If avoiding a direct road transfer, first reach Rome city center and use the official Termini or EUR Fermi shuttle." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "castel-romano-rome-car-parking",
    outletId: "castel-romano",
    originType: "city_center",
    originId: "rome-city-center",
    transportationType: "taxi",
    title: "Rome to Castel Romano by Car with Outlet Parking",
    estimatedDuration: "About 30 min by road",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Leave Rome toward Castel Romano using Via Pontina or Via di Trigoria, as indicated by the outlet's official access page." },
      { order: 2, description: "Drive to Via Ponte di Piscina Cupa 64 and follow the outlet signs for visitor parking." },
      { order: 3, description: "Park in the outlet car parks and note the area or entrance for your return." },
      { order: 4, description: "For taxi or private transfer, confirm the fare and exact return pickup point before leaving the vehicle." },
      { order: 5, description: "Allow additional time for Rome ring-road, Pontina, and weekend shopping traffic on the return." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "fidenza-milan-shopping-express",
    outletId: "fidenza-village",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "shuttle",
    title: "Milan to Fidenza Village by Official Shopping Express",
    estimatedDuration: "90 min each way",
    estimatedCost: "Adults €10; children 5-11 €5; infants 0-4 free",
    recommended: true,
    steps: [
      { order: 1, description: "Book the official Fidenza Village Shopping Express and confirm the timetable; tickets must be purchased at least five minutes before departure." },
      { order: 2, description: "Go to Piazza della Repubblica 5, at the corner with Via Turati and in front of the newsstand near MM3, at least 15 minutes before the 9:45 departure." },
      { order: 3, description: "Board the Shopping Express to Fidenza Village; the official schedule shows arrival at 11:15." },
      { order: 4, description: "On arrival, follow Village signs from the coach stop to the entrance and Concierge/Guest Services." },
      { order: 5, description: "Use the official 17:00 return from Fidenza Village, with arrival at Piazza della Repubblica around 18:30 subject to traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "fidenza-train-local-transfer",
    outletId: "fidenza-village",
    originType: "station",
    originId: "fidenza-station",
    transportationType: "train",
    title: "Fidenza Station to Fidenza Village by Local Transfer",
    estimatedDuration: "≈10–15 min from Fidenza station by local transfer (estimated); rail time varies by origin",
    estimatedCost: "≈€8–15 local taxi (estimated); rail fare check official rail timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official rail timetable to travel to Fidenza station from Milan, Bologna, Parma, or your starting city." },
      { order: 2, description: "At Fidenza station, use the station taxi rank or confirm the current local bus/transfer option to Via Federico Fellini 1 before leaving the station area." },
      { order: 3, description: "Continue to Fidenza Village and ask the driver or local provider where the return pickup will be." },
      { order: 4, description: "Before shopping, check the last practical return transfer to Fidenza station and your onward train." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "fidenza-airports-via-milan",
    outletId: "fidenza-village",
    originType: "airport",
    originId: "milan-airports",
    transportationType: "shuttle",
    title: "Milan Airports to Fidenza Village via Milan Shopping Express",
    estimatedDuration: "≈3–4 hr total one way including airport-city transfer and Shopping Express (estimated)",
    estimatedCost: "Shopping Express €10 adult plus official airport transfer fare",
    recommended: false,
    steps: [
      { order: 1, description: "From Malpensa, Linate, or Bergamo, use the official airport train or coach connection to reach central Milan." },
      { order: 2, description: "Allow enough buffer to reach Piazza della Repubblica 5 at least 15 minutes before the official Shopping Express departure." },
      { order: 3, description: "Take the booked Shopping Express to Fidenza Village." },
      { order: 4, description: "For the return, confirm the Shopping Express arrival in Milan and book an onward official airport connection that leaves enough time for traffic and check-in." },
      { order: 5, description: "If the coach timing does not fit your flight, use the official chauffeur/private-transfer contact or a rail route confirmed through official operators." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "fidenza-milan-car-parking",
    outletId: "fidenza-village",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "taxi",
    title: "Milan to Fidenza Village by Car with Free Parking",
    estimatedDuration: "≈70–90 min (estimated)",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); chauffeur/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Drive from Milan toward Fidenza Village at Via Federico Fellini 1, 43036 Fidenza." },
      { order: 2, description: "Use the Village's official free parking; electric car charging points are also noted by the Village." },
      { order: 3, description: "If using the official chauffeur/private-transfer option, contact Concierge at least 24 hours in advance and confirm pickup, fare, and return details." },
      { order: 4, description: "For the return to Milan, allow extra time for motorway traffic and sales-period congestion." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "la-reggia-naples-shuttle",
    outletId: "la-reggia",
    originType: "city_center",
    originId: "naples-city-center",
    transportationType: "shuttle",
    title: "Naples to La Reggia by Official Shuttle Service",
    estimatedDuration: "≈45–70 min (estimated); check official timetable",
    estimatedCost: "Check official ticket details",
    recommended: true,
    steps: [
      { order: 1, description: "Open La Reggia's official plan-your-visit page and confirm the Naples shuttle timetable and pickup points for your date." },
      { order: 2, description: "Use the official Naples stop shown for your departure, such as central Naples/port/hotel pickup points if listed in the current schedule." },
      { order: 3, description: "Board the shuttle to La Reggia Designer Outlet at S.P. 336 ex-Sannitica, Marcianise." },
      { order: 4, description: "On arrival, note the return shuttle stop before entering the shops." },
      { order: 5, description: "Confirm the last return to Naples before shopping, because older printed schedules may not reflect current operations." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "la-reggia-naples-public-transport",
    outletId: "la-reggia",
    originType: "city_center",
    originId: "naples-city-center",
    transportationType: "train",
    title: "Naples to La Reggia by Train plus Local Bus or Taxi",
    estimatedDuration: "≈60–90 min total (estimated)",
    estimatedCost: "≈€8–15 total with local transfer (estimated); confirm official rail and local fares",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official rail timetable from Napoli Centrale toward Caserta or Marcianise for your travel date." },
      { order: 2, description: "On arrival at Caserta or Marcianise, confirm the current local bus or taxi connection to La Reggia Designer Outlet before leaving the station." },
      { order: 3, description: "Travel to S.P. 336 ex-Sannitica, 81025 Marcianise, and follow signs to the outlet entrance." },
      { order: 4, description: "Before shopping, confirm both the local return transfer to the station and the onward train back to Naples." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "la-reggia-naples-car",
    outletId: "la-reggia",
    originType: "city_center",
    originId: "naples-city-center",
    transportationType: "taxi",
    title: "Naples to La Reggia by Car, Taxi, or Private Transfer",
    estimatedDuration: "≈25–40 min (estimated)",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Choose a rental car, taxi, or private transfer from Naples and confirm fare, pickup point, motorway toll handling, and return pickup before departure." },
      { order: 2, description: "Travel toward Marcianise; the official outlet page places La Reggia adjacent to the A1 motorway at the Caserta Sud exit." },
      { order: 3, description: "Use the outlet parking area or the agreed drop-off at S.P. 336 ex-Sannitica." },
      { order: 4, description: "For the return, allow extra time for A1, Caserta Sud, and shopping-period traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "la-reggia-naples-airport-transfer",
    outletId: "la-reggia",
    originType: "airport",
    originId: "naples-airport",
    transportationType: "taxi",
    title: "Naples Airport to La Reggia by Taxi, Rental Car, or Private Transfer",
    estimatedDuration: "≈20–35 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Naples Airport, choose a licensed taxi, rental car, or pre-booked private transfer and confirm fare, meeting point, luggage space, and return pickup." },
      { order: 2, description: "Travel toward Marcianise and the A1 Caserta Sud area noted on the outlet's official access page." },
      { order: 3, description: "Use La Reggia parking if driving, or agree a drop-off point near the entrance." },
      { order: 4, description: "If returning to the airport, reconfirm pickup time before shopping and leave a buffer for security and traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "noventa-venice-atvo-direct-bus",
    outletId: "noventa",
    originType: "city_center",
    originId: "venice-city-center",
    transportationType: "bus",
    title: "Venice Piazzale Roma to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "About 90 min; check official timetable",
    estimatedCost: "Return ticket €9.20; children under 6 free",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official McArthurGlen/ATVO Noventa bus page and book if required; the outlet lists daily ATVO connections from Venice Piazzale Roma." },
      { order: 2, description: "Go to the ATVO departure stop at Venezia Piazzale Roma for the direct Noventa di Piave Designer Outlet service." },
      { order: 3, description: "Board the no-change bus; the outlet notes runs from Venice at 9:10 and 13:05, subject to the current timetable." },
      { order: 4, description: "Get off at the outlet stop at Via Marco Polo 1 and follow signs to the main entrance." },
      { order: 5, description: "Before shopping, confirm your return departure; the outlet notes no-change returns at 16:10 and 19:40, subject to the current timetable." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "noventa-mestre-atvo-direct-bus",
    outletId: "noventa",
    originType: "station",
    originId: "mestre-station",
    transportationType: "bus",
    title: "Mestre Railway Station to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "≈60–75 min (estimated); check official timetable",
    estimatedCost: "Return ticket €9.20; children under 6 free",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official ATVO/McArthurGlen timetable for the Mestre railway station stop before travel." },
      { order: 2, description: "Go to the Mestre Bus Terminal/Railway Station ATVO stop shown in the current schedule." },
      { order: 3, description: "Take the ATVO bus toward Noventa di Piave Designer Outlet; the route also links Venice Piazzale Roma and Marco Polo Airport." },
      { order: 4, description: "On arrival, note the exact outlet return stop before entering the shops." },
      { order: 5, description: "Use the booked or confirmed return bus to Mestre railway station and allow for traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "noventa-marco-polo-airport-atvo",
    outletId: "noventa",
    originType: "airport",
    originId: "venice-marco-polo-airport",
    transportationType: "bus",
    title: "Venice Marco Polo Airport to Noventa di Piave by ATVO Direct Bus",
    estimatedDuration: "≈45–60 min (estimated); check official timetable",
    estimatedCost: "Return ticket €9.20; children under 6 free",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official ATVO/McArthurGlen timetable because the direct outlet bus includes Marco Polo International Airport as an intermediate stop." },
      { order: 2, description: "Book or confirm your ticket before travel, then go to the ATVO stop at Marco Polo Airport." },
      { order: 3, description: "Ride directly to Noventa di Piave Designer Outlet and follow signs from the bus stop to the entrance." },
      { order: 4, description: "Confirm the return bus to Marco Polo Airport before shopping, especially if connecting to a flight." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "noventa-venice-car-parking",
    outletId: "noventa",
    originType: "city_center",
    originId: "venice-city-center",
    transportationType: "taxi",
    title: "Venice Area to Noventa di Piave by Car with Outlet Parking",
    estimatedDuration: "≈35–50 min (estimated)",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From the Venice mainland or Mestre, drive toward Noventa di Piave Designer Outlet at Via Marco Polo 1." },
      { order: 2, description: "Follow motorway signs for the Noventa di Piave area and the outlet, then use the official visitor parking." },
      { order: 3, description: "During special parking operations, follow the outlet's current extra-parking signs and any free parking shuttle instructions." },
      { order: 4, description: "For taxi or private transfer, confirm fare, tolls, and the exact return pickup point before shopping." },
      { order: 5, description: "Allow extra time on the return for A4/E70 and Venice access traffic." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "serravalle-milan-official-shuttle",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "shuttle",
    title: "Milan to Serravalle Designer Outlet by Official Partner Shuttle",
    estimatedDuration: "90 min from Milan by Zani Viaggi; McArthurGlen notes about 60 min by road",
    estimatedCost: "Zani Viaggi from €25 return; confirm Frigerio fare with official partner",
    recommended: true,
    steps: [
      { order: 1, description: "Check Serravalle's official bus connection page for current daily partner shuttles, pickup points, fares, and return times." },
      { order: 2, description: "Book an official partner listed by the outlet, such as Zani Viaggi or Frigerio Viaggi; Zani departures are from Milano Centrale railway station and Largo Cairoli, while Frigerio also lists Piazza IV Novembre, Via Fatebenefratelli/Piazza San Marco, and Via Paleocapa." },
      { order: 3, description: "Arrive at the exact Milan pickup point on your ticket at least 15 minutes before departure, because seats and return options depend on the selected partner service." },
      { order: 4, description: "Ride the direct partner shuttle to Serravalle Designer Outlet and follow signs from the coach stop to the shops and Guest Services." },
      { order: 5, description: "Before shopping, confirm the same-day return departure: current official examples include Zani returns at 16:15, 17:15, and 19:15, and Frigerio around 18:30, subject to the ticket you booked." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "serravalle-train-bus",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "train",
    title: "Milan to Serravalle by Trenitalia Train + Serravalle Outlet Link Bus",
    estimatedDuration: "≈90–120 min total (estimated); check official rail timetable",
    estimatedCost: "Official Outlet Link bus €2 each way plus rail fare",
    recommended: false,
    steps: [
      { order: 1, description: "Use Trenitalia and select 'Serravalle Outlet' as the arrival or departure location so the train and dedicated Outlet Link bus can be purchased together." },
      { order: 2, description: "Travel by official rail service from Milan toward the Turin-Genoa regional line, using the itinerary Trenitalia offers via Arquata Scrivia, Serravalle Scrivia, or Novi Ligure." },
      { order: 3, description: "At the interchange station, look for the dedicated-livery bus waiting in front of the station and board for Serravalle Designer Outlet." },
      { order: 4, description: "Keep the combined ticket available; Trenitalia states the station-to-outlet bus supplement is €2 one way, with children aged 4–12 free on that bus fare." },
      { order: 5, description: "Before shopping, check the last Outlet Link bus back to your station and the onward train to Milan, because the bus timetable follows outlet opening days and may vary." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "serravalle-genoa-bus-or-car",
    outletId: "serravalle-designer-outlet",
    originType: "city_center",
    originId: "genoa-city-center",
    transportationType: "bus",
    title: "Genoa to Serravalle by Officially Listed FlixBus or Car",
    estimatedDuration: "≈60–75 min by listed coach (estimated); about 45 min by car",
    estimatedCost: "Confirm FlixBus fare; car fuel/tolls ≈€8–15 each way (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "Check Serravalle's official bus connection page for the currently listed Genoa service and book through the official FlixBus link if the times suit your shopping day." },
      { order: 2, description: "Use the listed Genova Fanti d'Italia departure point and confirm the outlet-bound stop on your ticket before travel." },
      { order: 3, description: "Ride to Serravalle Designer Outlet, then note the arrival stop for your return." },
      { order: 4, description: "Before shopping, confirm the available return departures; the outlet page lists examples such as 13:16 and 21:16 from Serravalle, subject to current booking availability." },
      { order: 5, description: "If driving instead, follow the A7 toward Serravalle Scrivia; McArthurGlen notes Genoa is about 45 minutes by car, and visitor parking is available at the centre." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "serravalle-milan-airports-via-city",
    outletId: "serravalle-designer-outlet",
    originType: "airport",
    originId: "milan-airports",
    transportationType: "shuttle",
    title: "Milan Airports to Serravalle via Milan Partner Shuttle",
    estimatedDuration: "≈2–3 hr total one way including airport-city transfer (estimated)",
    estimatedCost: "Official airport transfer fare plus Zani Viaggi from €25 return or partner fare",
    recommended: false,
    steps: [
      { order: 1, description: "From Malpensa, Linate, or Bergamo, use the official airport train or coach connection to reach central Milan with enough buffer for luggage and traffic." },
      { order: 2, description: "Book the official Serravalle partner shuttle that best matches your airport arrival; current outlet-listed Milan pickups include Centrale, Largo Cairoli, Brera/San Marco, Cadorna, Navigli, and Corso Buenos Aires depending on partner." },
      { order: 3, description: "Go to the exact pickup point shown on your partner ticket and board the direct shuttle to Serravalle Designer Outlet." },
      { order: 4, description: "For the return, confirm both the fixed shuttle return time to Milan and your onward official airport connection before shopping." },
      { order: 5, description: "If the schedules do not protect your flight time, use a licensed taxi, rental car, or pre-booked transfer and confirm the fare directly with the provider." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "the-mall-firenze-florence-direct-bus",
    outletId: "the-mall-firenze",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "bus",
    title: "Florence to The Mall Firenze by Official The Mall by Bus",
    estimatedDuration: "≈35–50 min (estimated); check official timetable",
    estimatedCost: "One way €9.50; round trip €18; reduced one way €5 / round trip €9; under 4 free",
    recommended: true,
    steps: [
      { order: 1, description: "Open The Mall Firenze visit page and Busitalia's official The Mall by Bus page to confirm the current timetable and ticket rules for your shopping date." },
      { order: 2, description: "Go to the Piazzale Montelungo bus terminal, a few minutes' walk from Firenze Santa Maria Novella station, and arrive before departure; online tickets receive priority boarding." },
      { order: 3, description: "Board the direct Busitalia The Mall by Bus service from Florence to The Mall Firenze at Via Europa 8, Leccio Reggello." },
      { order: 4, description: "Keep the ticket available; Busitalia lists tickets online, on board without a price increase, through Trenitalia channels, and through supported ticket apps." },
      { order: 5, description: "Before shopping, choose a same-day return; current official examples include returns from The Mall Firenze at 09:45, 10:10, 13:00, 14:00, 14:30, 15:00, 16:00, 17:00, 18:00, 19:20, and seasonal 20:20." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "the-mall-firenze-florence-airport-via-city",
    outletId: "the-mall-firenze",
    originType: "airport",
    originId: "florence-airport",
    transportationType: "bus",
    title: "Florence Airport to The Mall Firenze via Florence Direct Bus",
    estimatedDuration: "≈60–90 min total one way including airport-city transfer (estimated)",
    estimatedCost: "Official airport transfer fare plus bus one way €9.50 or round trip €18",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence Airport, use the official airport tram, taxi, or licensed transfer to reach Firenze Santa Maria Novella / central Florence." },
      { order: 2, description: "Walk from SMN to the Piazzale Montelungo bus terminal and allow enough buffer for the next official The Mall by Bus departure." },
      { order: 3, description: "Buy or show your Busitalia ticket and take the direct bus to The Mall Firenze, Via Europa 8, Leccio Reggello." },
      { order: 4, description: "For the return, confirm both the direct bus back to Florence and your onward airport connection before shopping, especially for evening flights." },
      { order: 5, description: "If the bus timetable does not fit your flight, use a licensed taxi, rental car, or pre-booked private transfer and confirm the fare with the provider." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "the-mall-firenze-train-local-transfer",
    outletId: "the-mall-firenze",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "train",
    title: "Florence to The Mall Firenze by Train plus Local Transfer",
    estimatedDuration: "≈60–90 min total (estimated)",
    estimatedCost: "≈€8–15 total with local transfer (estimated); confirm official rail and local fares",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official rail timetable from Firenze Santa Maria Novella to the Valdarno/Reggello area only if the direct Busitalia The Mall by Bus timetable does not suit you." },
      { order: 2, description: "Book the train shown by the official rail operator and confirm the practical arrival station for a taxi or local bus toward Leccio Reggello before leaving Florence." },
      { order: 3, description: "At the arrival station, use an official local taxi rank or confirmed local bus connection to The Mall Firenze, Via Europa 8." },
      { order: 4, description: "Ask the local provider where to meet for the return transfer and keep enough time for your onward train to Florence." },
      { order: 5, description: "For most travellers, prefer the official direct bus because it is purpose-built for The Mall Firenze and avoids an unconfirmed local transfer." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "the-mall-firenze-car-transfer",
    outletId: "the-mall-firenze",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "taxi",
    title: "Florence to The Mall Firenze by Car, Taxi, or Private Transfer",
    estimatedDuration: "≈35–50 min (estimated)",
    estimatedCost: "≈€8–15 fuel/tolls each way (estimated); taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence, take the A1 motorway in the direction of Rome, as described by The Mall Firenze's official visit page." },
      { order: 2, description: "Leave the motorway at the Incisa-Reggello exit, keep right toward Pontassieve, and continue as far as Leccio." },
      { order: 3, description: "Drive to The Mall Firenze at Via Europa 8, 50066 Leccio Reggello (FI), then use the outlet parking area or your agreed drop-off point." },
      { order: 4, description: "If using a taxi or private transfer, confirm the fare, tolls, luggage capacity, waiting policy, and exact return pickup point before leaving the vehicle." },
      { order: 5, description: "For the return to Florence, allow extra time for A1 traffic; if switching to the direct bus, check the official Busitalia return timetable before shopping." },
    ],
    updatedAt: "2026-07-02",
  },

  {
    guideId: "valdichiana-village-florence-car",
    outletId: "valdichiana-village",
    originType: "city_center",
    originId: "florence-city-center",
    transportationType: "taxi",
    title: "Florence to Valdichiana Village by Car",
    estimatedDuration: "60 min from Florence",
    estimatedCost: "Parking complimentary; fuel/tolls/taxi costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Check Valdichiana Designer Village's official directions page for current access information and opening hours." },
      { order: 2, description: "Drive south from Florence toward Foiano della Chiana; the outlet states it is about a 60-minute drive from Florence." },
      { order: 3, description: "Follow signs to Via Enzo Ferrari 5, 52045 Foiano della Chiana, and use the Village parking areas." },
      { order: 4, description: "If using a taxi or private transfer, confirm the round-trip fare, waiting policy, and pickup point before leaving the vehicle." },
      { order: 5, description: "For the return to Florence, allow extra time for A1 traffic and weekend shopping peaks." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "valdichiana-village-arezzo-train-bus",
    outletId: "valdichiana-village",
    originType: "station",
    originId: "arezzo-station",
    transportationType: "bus",
    title: "Arezzo Station to Valdichiana Village by Tiemme Bus LS5",
    estimatedDuration: "50 min by bus from Arezzo Terminal Tiemme",
    estimatedCost: "Check official Tiemme fare; rail fare check Trenitalia",
    recommended: false,
    steps: [
      { order: 1, description: "Use Trenitalia to reach Arezzo station, then confirm the current Tiemme Line LS5 timetable from Arezzo Terminal Tiemme." },
      { order: 2, description: "Walk from Arezzo station to the Tiemme bus terminal and board Line LS5 toward Foiano/Bettolle." },
      { order: 3, description: "Ride to the Valdichiana Designer Village stop; the outlet's official page lists a 50-minute bus journey." },
      { order: 4, description: "Follow the signed pedestrian route from the bus stop to the Village entrance." },
      { order: 5, description: "Before shopping, check the last LS5 return to Arezzo Terminal Tiemme and your onward Trenitalia connection." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "valdichiana-village-florence-airport-car",
    outletId: "valdichiana-village",
    originType: "airport",
    originId: "florence-airport",
    transportationType: "taxi",
    title: "Florence Airport to Valdichiana Village by Rental Car or Transfer",
    estimatedDuration: "≈70–90 min (estimated)",
    estimatedCost: "Confirm taxi/private transfer provider; parking complimentary",
    recommended: false,
    steps: [
      { order: 1, description: "From Florence Airport, pick up a rental car or meet your pre-booked transfer and confirm luggage space and return pickup." },
      { order: 2, description: "Travel via the Florence motorway network toward the A1 south and Foiano della Chiana." },
      { order: 3, description: "Arrive at Valdichiana Designer Village, Via Enzo Ferrari 5, and use the marked parking or drop-off area." },
      { order: 4, description: "For the return to the airport, set the pickup before shopping and add a traffic and check-in buffer." },
    ],
    updatedAt: "2026-07-03",
  },

  {
    guideId: "udine-to-palmanova-designer-village-car",
    outletId: "palmanova-designer-village",
    originType: "city_center",
    originId: "udine-city-center",
    transportationType: "taxi",
    title: "Udine to Palmanova Designer Village by Car or Taxi",
    estimatedDuration: "25 min from Udine",
    estimatedCost: "Parking free; taxi/private transfer confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Set the destination to Palmanova Designer Village, Aiello del Friuli, by the A4 Palmanova exit." },
      { order: 2, description: "Drive south from Udine toward the A4 / Palmanova area; the official directions page states the Village is about 25 minutes from Udine." },
      { order: 3, description: "Follow the outlet and A4 Palmanova exit signs to the visitor parking areas." },
      { order: 4, description: "For a taxi or private transfer, agree the return pickup point and fare before entering the shops." },
      { order: 5, description: "For the return to Udine, allow extra time around weekend and sale-period traffic near the motorway exit." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "trieste-to-palmanova-designer-village-train-taxi",
    outletId: "palmanova-designer-village",
    originType: "city_center",
    originId: "trieste-city-center",
    transportationType: "train",
    title: "Trieste to Palmanova Designer Village by Train and Local Transfer",
    estimatedDuration: "≈60-90 min (estimated)",
    estimatedCost: "Check official Trenitalia fare + local taxi/bus fare",
    recommended: false,
    steps: [
      { order: 1, description: "From Trieste Centrale, check official Trenitalia services toward Cervignano-Aquileia-Grado or Palmanova, depending on the best current connection." },
      { order: 2, description: "Take the confirmed train and continue from the nearest practical station by local bus when available or licensed taxi to Palmanova Designer Village." },
      { order: 3, description: "If using regional buses, verify the Arriva Udine / TPL FVG stop and timetable before travel, because the Village is outside the historic town center." },
      { order: 4, description: "For the return, book or confirm the local transfer back to the station before shopping, then check the Trenitalia timetable to Trieste." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "venice-airport-to-palmanova-designer-village-car",
    outletId: "palmanova-designer-village",
    originType: "airport",
    originId: "venice-marco-polo-airport",
    transportationType: "taxi",
    title: "Venice Marco Polo Airport to Palmanova Designer Village by Car",
    estimatedDuration: "≈1h10-1h30 (estimated)",
    estimatedCost: "Parking free; taxi/private transfer confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Venice Marco Polo Airport, use a rental car, licensed taxi, or pre-booked transfer and confirm the fare, luggage space, and pickup point." },
      { order: 2, description: "Follow the A4 motorway east toward Trieste and exit at Palmanova, as highlighted by the official Village directions." },
      { order: 3, description: "Continue to Palmanova Designer Village visitor parking in Aiello del Friuli." },
      { order: 4, description: "For the return to the airport, pre-book pickup or allow a motorway traffic buffer before your flight." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "cervignano-station-to-palmanova-designer-village-local-transfer",
    outletId: "palmanova-designer-village",
    originType: "station",
    originId: "cervignano-aquileia-grado-station",
    transportationType: "bus",
    title: "Cervignano-Aquileia-Grado Station to Palmanova Designer Village by Local Transfer",
    estimatedDuration: "≈10-20 min (estimated)",
    estimatedCost: "Check official TPL FVG / Arriva Udine fare; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Arrive at Cervignano-Aquileia-Grado station after checking official Trenitalia times; Palmanova Designer Village officially lists this station for public transport access." },
      { order: 2, description: "Use the official TPL FVG / Arriva Udine timetable to confirm any bus toward Aiello del Friuli / Palmanova outlet area, or take a licensed taxi for the official 12 km / 13 minute onward transfer." },
      { order: 3, description: "Travel to Palmanova Designer Village and confirm the nearest safe stop or taxi drop-off with the driver." },
      { order: 4, description: "For the return, check the last local bus or arrange a taxi back to Cervignano-Aquileia-Grado station before entering the shops." },
    ],
    updatedAt: "2026-07-03",
  },


  {
    guideId: "brescia-station-to-franciacorta-designer-village-bus",
    outletId: "franciacorta-designer-village",
    originType: "station",
    originId: "brescia-station",
    transportationType: "bus",
    title: "Brescia Station to Franciacorta Designer Village by Bus",
    estimatedDuration: "25 min bus (official outlet estimate)",
    estimatedCost: "check official bus fare",
    recommended: true,
    steps: [
      { order: 1, description: "Travel to Brescia railway station and walk to the SIA / Arriva bus area serving the Franciacorta routes." },
      { order: 2, description: "Check the official bus operator timetable for Line LS029 from Brescia toward Ome / Monticelli Brusati before boarding." },
      { order: 3, description: "Ride the confirmed bus toward Franciacorta Designer Village / Rodengo Saiano and get off at the outlet stop when served." },
      { order: 4, description: "Before shopping, check official LS029 return departures to Brescia because evening and holiday service may differ." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "milan-to-franciacorta-designer-village-train-bus",
    outletId: "franciacorta-designer-village",
    originType: "city_center",
    originId: "milan-city-center",
    transportationType: "train",
    title: "Milan to Franciacorta Designer Village by Train and Bus",
    estimatedDuration: "46 min train to Brescia + 25 min bus (official outlet estimates)",
    estimatedCost: "check official Trenitalia and bus fares",
    recommended: false,
    steps: [
      { order: 1, description: "From Milano Centrale, check official Trenitalia departures to Brescia; the outlet access page lists Milan to Brescia by train as 46 minutes." },
      { order: 2, description: "At Brescia, continue from the bus station area on official Line LS029 toward Ome / Monticelli Brusati when the timetable fits." },
      { order: 3, description: "Get off at Franciacorta Designer Village / the closest official outlet stop and follow pedestrian signs into the centre." },
      { order: 4, description: "For the return, check both the official bus timetable to Brescia and Trenitalia departures back to Milan before leaving the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "verona-to-franciacorta-designer-village-train-bus",
    outletId: "franciacorta-designer-village",
    originType: "city_center",
    originId: "verona-city-center",
    transportationType: "train",
    title: "Verona to Franciacorta Designer Village by Train and Bus",
    estimatedDuration: "30 min train to Brescia + 25 min bus (official outlet estimates)",
    estimatedCost: "check official Trenitalia and bus fares",
    recommended: false,
    steps: [
      { order: 1, description: "From Verona Porta Nuova, check official Trenitalia departures to Brescia; the outlet access page lists Verona to Brescia by train as 30 minutes." },
      { order: 2, description: "At Brescia, check official Line LS029 from the SIA / Arriva bus station area toward Ome / Monticelli Brusati." },
      { order: 3, description: "Ride the bus to the outlet area and follow signs into Franciacorta Designer Village." },
      { order: 4, description: "Check official return times for the bus to Brescia and the train to Verona before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "franciacorta-designer-village-car-parking-guide",
    outletId: "franciacorta-designer-village",
    originType: "city_center",
    originId: "brescia-city-center",
    transportationType: "taxi",
    title: "Franciacorta Designer Village by Car or Taxi",
    estimatedDuration: "check traffic",
    estimatedCost: "parking free; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Franciacorta Designer Village, Rodengo Saiano, and confirm the current road approach before departure." },
      { order: 2, description: "Use the A4 / A35 and local road guidance shown by the official outlet access page or official motorway operators." },
      { order: 3, description: "Park in the visitor parking area and note the entrance used for your return." },
      { order: 4, description: "If using a taxi or private transfer, confirm the return pickup point and fare before entering the shops." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "mantova-station-to-mantova-village-bus",
    outletId: "mantova-village",
    originType: "station",
    originId: "mantova-station",
    transportationType: "bus",
    title: "Mantova Station to Mantova Village by Bus",
    estimatedDuration: "20 min bus without traffic (official outlet estimate)",
    estimatedCost: "check official APAM fare",
    recommended: true,
    steps: [
      { order: 1, description: "Arrive at Mantova station and use the official outlet directions to walk about 600 m to the Line 31A stop at Viale Piave 4A." },
      { order: 2, description: "Check the official APAM timetable for Line 31A before boarding toward Mantova Village." },
      { order: 3, description: "Ride Line 31A to the Mantova Village / Fashion Outlet Village stop and follow the pedestrian route into the Village." },
      { order: 4, description: "Before shopping, check official APAM return departures to Mantova station." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "verona-to-mantova-village-train-bus",
    outletId: "mantova-village",
    originType: "city_center",
    originId: "verona-city-center",
    transportationType: "train",
    title: "Verona to Mantova Village by Train and Bus",
    estimatedDuration: "check official timetable + 20 min bus without traffic",
    estimatedCost: "check official Trenitalia and APAM fares",
    recommended: false,
    steps: [
      { order: 1, description: "From Verona Porta Nuova, check official Trenitalia trains to Mantova station." },
      { order: 2, description: "At Mantova station, follow the official outlet directions to the Viale Piave 4A stop for APAM Line 31A." },
      { order: 3, description: "Take Line 31A to Mantova Village after checking the official APAM timetable." },
      { order: 4, description: "For the return, check APAM Line 31A and Trenitalia departures before leaving the Village." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "mantova-village-car-parking-guide",
    outletId: "mantova-village",
    originType: "city_center",
    originId: "mantova-city-center",
    transportationType: "taxi",
    title: "Mantova Village by Car or Taxi",
    estimatedDuration: "check traffic",
    estimatedCost: "parking free; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Mantova Village in Bagnolo San Vito and confirm the route before departure." },
      { order: 2, description: "Follow official road signs to the Village and use the visitor parking areas on arrival." },
      { order: 3, description: "If travelling by taxi or private transfer, confirm the fare and return pickup point before shopping." },
      { order: 4, description: "Allow extra time around sale periods or weekends before returning to Mantova station or the motorway." },
    ],
    updatedAt: "2026-07-04",
  },

  {
    guideId: "milan-to-vicolungo-style-outlets-shuttle",
    outletId: "vicolungo-the-style-outlets",
    originType: "city_center",
    originId: "milan-centrale",
    transportationType: "shuttle",
    title: "Milan to Vicolungo The Style Outlets by Shuttle Bus",
    estimatedDuration: "Check official shuttle timetable",
    estimatedCost: "Check official shuttle fare before booking",
    recommended: true,
    steps: [
      { order: 1, description: "Open Vicolungo The Style Outlets' official Shuttle Service page and confirm the current Milan operating days, reservation rules, fare and return time." },
      { order: 2, description: "Go to the confirmed Milan Central Station pickup point early with your reservation or payment method accepted by the operator." },
      { order: 3, description: "Ride the shuttle to Vicolungo The Style Outlets and note the return stop when you arrive." },
      { order: 4, description: "Before shopping, confirm the official return departure; seasonal promotions and timetables can change." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "turin-to-vicolungo-style-outlets-shuttle",
    outletId: "vicolungo-the-style-outlets",
    originType: "city_center",
    originId: "turin-city-center",
    transportationType: "shuttle",
    title: "Turin to Vicolungo The Style Outlets by Shuttle Bus",
    estimatedDuration: "Check official shuttle timetable",
    estimatedCost: "Check official operator fare before travel",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Vicolungo shuttle page and the named operator booking page for Turin pickup points, operating dates and fare." },
      { order: 2, description: "Use only the pickup point confirmed for your date, such as Porta Nuova, Porta Susa or another official stop listed by the operator." },
      { order: 3, description: "Ride the shuttle to Vicolungo The Style Outlets and verify the return stop on arrival." },
      { order: 4, description: "Before shopping, check the return time and whether booking is mandatory or recommended for that service." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "vicolungo-style-outlets-car-parking-guide",
    outletId: "vicolungo-the-style-outlets",
    originType: "city_center",
    originId: "milan-or-turin-city-center",
    transportationType: "taxi",
    title: "Driving or Taxi to Vicolungo The Style Outlets",
    estimatedDuration: "Check traffic",
    estimatedCost: "Check official parking terms; taxi/private transfer fare varies",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Vicolungo The Style Outlets and check the official access page before departure." },
      { order: 2, description: "Approach via the motorway route recommended by the outlet and current road operator information." },
      { order: 3, description: "Follow on-site parking signs and check current parking or EV charging information when you arrive." },
      { order: 4, description: "If using a taxi or private transfer, confirm the fare and return pickup point before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "bologna-to-castel-guelfo-style-outlets-bus",
    outletId: "castel-guelfo-the-style-outlets",
    originType: "city_center",
    originId: "bologna-city-center",
    transportationType: "bus",
    title: "Bologna to Castel Guelfo The Style Outlets by Bus and Last-Mile Shuttle",
    estimatedDuration: "Check official TPER timetable",
    estimatedCost: "Check official TPER fare before travel",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official TPER journey planner for Bologna to Castel San Pietro Terme / Castel Guelfo The Style Outlets before travel." },
      { order: 2, description: "Board only the bus connection shown by TPER for your date, allowing time for any transfer at Castel San Pietro Terme." },
      { order: 3, description: "For the final leg, use the official local shuttle or bus stop listed in the current timetable and walk only on marked pedestrian routes." },
      { order: 4, description: "Before shopping, check the return bus or shuttle timetable because evening and holiday service can differ." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "castel-san-pietro-to-castel-guelfo-style-outlets-last-mile",
    outletId: "castel-guelfo-the-style-outlets",
    originType: "station",
    originId: "castel-san-pietro-terme-station",
    transportationType: "bus",
    title: "Castel San Pietro Terme Station to Castel Guelfo The Style Outlets",
    estimatedDuration: "Check official local shuttle or bus timetable",
    estimatedCost: "Check official local fare before travel",
    recommended: true,
    steps: [
      { order: 1, description: "Arrive at Castel San Pietro Terme station and check the official local bus or shuttle timetable to the Castel Guelfo outlet area." },
      { order: 2, description: "Use the confirmed stop for Castel Guelfo industrial zone / The Style Outlets, checking the direction before boarding." },
      { order: 3, description: "After alighting, follow marked paths and outlet signs to the entrance." },
      { order: 4, description: "Check the return time to the station before shopping, especially on Sundays, holidays or evenings." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "castel-guelfo-style-outlets-car-parking-guide",
    outletId: "castel-guelfo-the-style-outlets",
    originType: "city_center",
    originId: "bologna-city-center",
    transportationType: "taxi",
    title: "Driving or Taxi to Castel Guelfo The Style Outlets",
    estimatedDuration: "About 20 minutes from Bologna when traffic is clear; check traffic",
    estimatedCost: "Check official parking terms; taxi/private transfer fare varies",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Castel Guelfo The Style Outlets, Via del Commercio 4/2, and check the official access page before departure." },
      { order: 2, description: "Use the A14 toward the Castel San Pietro Terme exit when it is the confirmed best route for current traffic." },
      { order: 3, description: "Follow on-site parking signs and check current parking rules on arrival." },
      { order: 4, description: "If using a taxi or private transfer from Bologna or the airport, confirm fare and return pickup before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
];
