import type { TransportationGuide } from "./index";
export const japanTransportationGuides: TransportationGuide[] = [
  { guideId: "tokyo-station-to-gotemba-premium-outlets-bus", outletId: "gotemba-premium-outlets", originType: "station", originId: "tokyo-station", transportationType: "bus", title: "Tokyo Station to Gotemba Premium Outlets by direct highway bus", estimatedDuration: "Approx. 1 hr 40 min; timetable and traffic vary", estimatedCost: "JPY 1,900–2,200 one way when booked in advance; same-day purchase +JPY 100; onboard fare JPY 2,500", recommended: true, steps: [
    { order: 1, description: "Go to Tokyo Station Yaesu South Exit." }, { order: 2, description: "Use the direct highway bus for Gotemba Premium Outlets." }, { order: 3, description: "Confirm the selected departure's fare because weekday, weekend and specific-day prices differ." }, { order: 4, description: "Reserve in advance where possible." }, { order: 5, description: "Alight directly at Gotemba Premium Outlets." },
  ], updatedAt: "2026-08-10" },
  { guideId: "shinjuku-highway-bus-terminal-to-gotemba-premium-outlets-bus", outletId: "gotemba-premium-outlets", originType: "station", originId: "shinjuku-highway-bus-terminal", transportationType: "bus", title: "Shinjuku Highway Bus Terminal to Gotemba Premium Outlets by direct highway bus", estimatedDuration: "Approx. 1 hr 40–1 hr 50 min; timetable and traffic vary", estimatedCost: "JPY 1,900–2,200 one way on JR Bus depending on day/service; Odakyu Bus JPY 2,000 one way", recommended: true, steps: [
    { order: 1, description: "Go to Shinjuku Highway Bus Terminal." }, { order: 2, description: "Choose a current direct Gotemba Premium Outlets departure." }, { order: 3, description: "Confirm the JR or Odakyu operator and fare." }, { order: 4, description: "Reserve in advance where possible." }, { order: 5, description: "Travel directly without transfer." },
  ], updatedAt: "2026-08-10" },
  { guideId: "jr-gotemba-station-to-gotemba-premium-outlets-shuttle", outletId: "gotemba-premium-outlets", originType: "station", originId: "jr-gotemba-station", transportationType: "shuttle", title: "JR Gotemba Station to Gotemba Premium Outlets by free shuttle", estimatedDuration: "Approx. 10–20 min; traffic varies", estimatedCost: "Free", recommended: true, steps: [
    { order: 1, description: "Exit JR Gotemba Station at Otomeguchi Exit." }, { order: 2, description: "Use the official free shuttle." }, { order: 3, description: "Current normal departures are at :00, :15, :30 and :45 each hour." }, { order: 4, description: "Ride via Tomei Gotemba IC to the outlet." }, { order: 5, description: "Confirm the day's service around opening and closing time because first and last buses depend on outlet hours." },
  ], updatedAt: "2026-08-10" },
];
