import type { TransportationGuide } from "./index";

export const latviaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "riga-to-via-jurmala-outlet-village-bus",
    outletId: "via-jurmala-outlet-village",
    originType: "city_center",
    originId: "riga-city-center",
    transportationType: "bus",
    title: "Riga to Via Jurmala Outlet Village by Bus",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official fare",
    recommended: true,
    steps: [
      { order: 1, description: "From Riga, check the official Rīgas satiksme timetable for Bus Route 4 or Route 32 toward Piņķi / Via Jurmala Outlet Village." },
      { order: 2, description: "Board the confirmed service from the listed Riga stop only after checking the official timetable for the shopping date." },
      { order: 3, description: "Get off at the stop serving Piņķi / Via Jurmala Outlet Village, then follow the outlet signs to the shopping village." },
      { order: 4, description: "Before shopping, check the official return timetable for Route 4 or Route 32 back toward Riga." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "babite-station-to-via-jurmala-outlet-village-bus",
    outletId: "via-jurmala-outlet-village",
    originType: "station",
    originId: "babite-station",
    transportationType: "bus",
    title: "Babīte Station to Via Jurmala Outlet Village by Bus",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official fare",
    recommended: false,
    steps: [
      { order: 1, description: "Arrive at Babīte by official passenger train after checking the Vivi / Latvian rail timetable from Riga or Jūrmala." },
      { order: 2, description: "At Babīte, check the official Route 4 timetable toward Piņķi / Via Jurmala Outlet Village." },
      { order: 3, description: "Board Route 4 when it fits your train arrival, or use a licensed taxi if the official bus timetable does not work." },
      { order: 4, description: "For the return, check both the Route 4 bus timetable and the onward train timetable before leaving the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "jurmala-to-via-jurmala-outlet-village-train-bus",
    outletId: "via-jurmala-outlet-village",
    originType: "city_center",
    originId: "jurmala-city-center",
    transportationType: "train",
    title: "Jūrmala to Via Jurmala Outlet Village by Train and Bus",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official train and bus fares",
    recommended: false,
    steps: [
      { order: 1, description: "From Jūrmala, check official Vivi / Latvian rail services toward Babīte." },
      { order: 2, description: "Travel by train to Babīte, then connect to official Bus Route 4 toward Piņķi / Via Jurmala Outlet Village if the timetable fits." },
      { order: 3, description: "Complete the last-mile bus ride or use a licensed taxi from Babīte when no convenient official bus is available." },
      { order: 4, description: "Check official return bus and train times before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "via-jurmala-outlet-village-car-parking-guide",
    outletId: "via-jurmala-outlet-village",
    originType: "city_center",
    originId: "riga-city-center",
    transportationType: "taxi",
    title: "Via Jurmala Outlet Village by Car or Taxi",
    estimatedDuration: "check traffic",
    estimatedCost: "parking at outlet; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Follow the official outlet driving directions from Riga or Jūrmala toward Piņķi, Saliena and Exupery International School." },
      { order: 2, description: "Use the Via Jurmala Outlet Village parking lot indicated by the official access page." },
      { order: 3, description: "If using Smile Taxi or another licensed taxi, confirm the fare and return pickup point before shopping." },
      { order: 4, description: "For the return by car, re-check the official route because missed turns near the Jūrmala approach may require a turnaround." },
    ],
    updatedAt: "2026-07-04",
  },
];
