import type { TransportationGuide } from "./index";

export const netherlandsTransportationGuides: TransportationGuide[] = [
  {
    guideId: "amsterdam-to-roermond-train",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "amsterdam-city-center",
    transportationType: "train",
    title: "Amsterdam to Designer Outlet Roermond by Train",
    estimatedDuration: "≈2 hr 5-20 min (estimated)",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Use the NS journey planner for Amsterdam Centraal to Roermond and buy the ticket or check in with a valid OV payment method." },
      { order: 2, description: "Travel by NS train to Roermond station; most journeys require a connection, so confirm the platform and transfer in the planner before departure." },
      { order: 3, description: "From Roermond station, follow the signed walking route to Designer Outlet Roermond; allow about 10-15 minutes on foot." },
      { order: 4, description: "For the return, check NS live departures from Roermond before leaving the outlet, especially late in the evening or during works." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "eindhoven-airport-to-roermond-car",
    outletId: "designer-outlet-roermond",
    originType: "airport",
    originId: "eindhoven-airport",
    transportationType: "taxi",
    title: "Eindhoven Airport to Designer Outlet Roermond by Car",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Eindhoven Airport, follow the signed road route toward the A2/A73 corridor and Roermond, checking current traffic before departure." },
      { order: 2, description: "Use a taxi, rental car, or pre-booked transfer; confirm the fare with the provider before leaving the airport." },
      { order: 3, description: "Navigate to Stadsweide 2, 6041 TD Roermond and follow Designer Outlet Roermond parking signs on arrival." },
      { order: 4, description: "Use the official parking guidance: the first 30 minutes are free, standard parking is €7 per day, and premium parking is €12.50 per day if booked/available." },
      { order: 5, description: "If not driving yourself, agree the return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "flixbus-to-roermond-outlet",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "regional-city-centres",
    transportationType: "bus",
    title: "Regional Cities to Designer Outlet Roermond by FlixBus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check FlixBus for current services from your departure city to Roermond Station or directly to Designer Outlet Roermond." },
      { order: 2, description: "Book only after confirming the exact arrival stop, departure time, luggage rules, and return time on FlixBus." },
      { order: 3, description: "If your coach arrives at Roermond Station, follow the signed walking route to Designer Outlet Roermond; allow about 10-15 minutes on foot." },
      { order: 4, description: "If your coach stops directly at Designer Outlet Roermond, confirm the return stop location before entering the centre." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "rotterdam-to-roosendaal-train-bus",
    outletId: "designer-outlet-roosendaal",
    originType: "city_center",
    originId: "rotterdam-city-center",
    transportationType: "train",
    title: "Rotterdam to Designer Outlet Roosendaal by Train and Bus",
    estimatedDuration: "≈55-75 min (estimated)",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Use the NS journey planner for Rotterdam Centraal to Roosendaal and confirm live train times before departure." },
      { order: 2, description: "Travel by NS train to Roosendaal station." },
      { order: 3, description: "At Roosendaal station, continue by the official local bus connection to the Designer Outlet stop; the outlet states the bus ride takes about 5 minutes." },
      { order: 4, description: "Use the outlet-listed bus routes 112 (daily) or 104 (Monday to Friday), and verify the current Arriva/Bravo or 9292 timetable before boarding." },
      { order: 5, description: "For the return, check both the bus departure from Designer Outlet Roosendaal and the onward NS train from Roosendaal station before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "rotterdam-airport-to-roosendaal-car",
    outletId: "designer-outlet-roosendaal",
    originType: "airport",
    originId: "rotterdam-airport",
    transportationType: "taxi",
    title: "Rotterdam The Hague Airport to Designer Outlet Roosendaal by Car",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Rotterdam The Hague Airport, check current traffic and follow the signed motorway route toward Roosendaal." },
      { order: 2, description: "Use a taxi, rental car, or pre-booked transfer; confirm the fare with the provider before leaving the airport." },
      { order: 3, description: "Navigate to Rosada 70, 4703 TB Roosendaal and follow Designer Outlet Roosendaal parking signs on arrival." },
      { order: 4, description: "Use the official Roosendaal parking guidance: standard parking costs €5 per day and is payable by card or cash." },
      { order: 5, description: "If not driving yourself, agree the return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
];
