import type { TransportationGuide } from "./index";

export const netherlandsTransportationGuides: TransportationGuide[] = [
  {
    guideId: "amsterdam-to-roermond-train",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "amsterdam-city-center",
    transportationType: "train",
    title: "Amsterdam to Designer Outlet Roermond by Train",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check NS for current services from Amsterdam Centraal to Roermond." },
      { order: 2, description: "Travel by train to Roermond station." },
      { order: 3, description: "Continue from Roermond station to Designer Outlet Roermond by the signed walking route, public transport, or taxi." },
      { order: 4, description: "Check NS return trains before shopping; use official outlet offers only if still available." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "eindhoven-airport-to-roermond-car",
    outletId: "designer-outlet-roermond",
    originType: "airport",
    originId: "eindhoven-airport",
    transportationType: "taxi",
    title: "Eindhoven Airport to Designer Outlet Roermond by Car",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Eindhoven Airport to Designer Outlet Roermond." },
      { order: 2, description: "Use a taxi, rental car, or transfer and confirm the fare before departure." },
      { order: 3, description: "Use the official Roermond parking guidance; the first 30 minutes are free and a full-day parking fee applies." },
      { order: 4, description: "Confirm return pickup or onward public transport before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "flixbus-to-roermond-outlet",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "regional-city-centres",
    transportationType: "bus",
    title: "Regional Cities to Designer Outlet Roermond by FlixBus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check FlixBus official routes, stops, times, and prices before booking." },
      { order: 2, description: "Book only if the service stops at Roermond Station or directly at Designer Outlet Roermond." },
      { order: 3, description: "If arriving at Roermond Station, continue to the outlet by the signed route, public transport, or taxi." },
      { order: 4, description: "Confirm the return coach stop and departure time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "rotterdam-to-roosendaal-train-bus",
    outletId: "designer-outlet-roosendaal",
    originType: "city_center",
    originId: "rotterdam-city-center",
    transportationType: "train",
    title: "Rotterdam to Designer Outlet Roosendaal by Train and Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check NS services from Rotterdam Centraal to Roosendaal." },
      { order: 2, description: "Travel by train to Roosendaal station." },
      { order: 3, description: "From Roosendaal station, take the official local bus connection to Designer Outlet Roosendaal." },
      { order: 4, description: "Use bus route 112 daily or route 104 Monday to Friday only after confirming the current timetable." },
      { order: 5, description: "Check return bus and train times before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "rotterdam-airport-to-roosendaal-car",
    outletId: "designer-outlet-roosendaal",
    originType: "airport",
    originId: "rotterdam-airport",
    transportationType: "taxi",
    title: "Rotterdam The Hague Airport to Designer Outlet Roosendaal by Car",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Rotterdam The Hague Airport to Designer Outlet Roosendaal." },
      { order: 2, description: "Use a taxi, rental car, or transfer and confirm the fare before departure." },
      { order: 3, description: "Use the official Roosendaal parking guidance; a full-day parking fee applies." },
      { order: 4, description: "Confirm return pickup or public transport connections before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
];
