import type { TransportationGuide } from "./index";

export const netherlandsTransportationGuides: TransportationGuide[] = [
  {
    guideId: "amsterdam-to-roermond-train",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "amsterdam-city-center",
    transportationType: "train",
    title: "Amsterdam to Designer Outlet Roermond via Roermond",
    estimatedDuration: "",
    estimatedCost: "Check current NS fare",
    recommended: true,
    steps: [
      { order: 1, description: "Check the Amsterdam Centraal–Roermond connection with NS." },
      { order: 2, description: "Travel to Roermond using the current NS connection." },
      { order: 3, description: "Alight at Roermond." },
      { order: 4, description: "Use the official approximately 15-minute walking connection." },
      { order: 5, description: "Check the return train before shopping." },
    ],
    updatedAt: "2026-08-03",
  },
  {
    guideId: "eindhoven-airport-to-roermond-car",
    outletId: "designer-outlet-roermond",
    originType: "airport",
    originId: "eindhoven-airport",
    transportationType: "taxi",
    title: "Eindhoven Airport to Designer Outlet Roermond by Car",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Eindhoven Airport, follow the signed road route toward the A2/A73 corridor and Roermond, checking current traffic before departure." },
      { order: 2, description: "Use a taxi, rental car, or pre-booked transfer; confirm the fare with the provider before leaving the airport." },
      { order: 3, description: "Navigate to Stadsweide 2, 6041 TD Roermond and follow Designer Outlet Roermond parking signs on arrival." },
      { order: 4, description: "Use the official parking guidance: the first 30 minutes are free, standard parking is €7 per day, and premium parking is €12.50 per day if booked/available." },
      { order: 5, description: "If not driving yourself, agree the return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "flixbus-to-roermond-outlet",
    outletId: "designer-outlet-roermond",
    originType: "city_center",
    originId: "regional-city-centres",
    transportationType: "bus",
    title: "Regional Cities to Designer Outlet Roermond by FlixBus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check FlixBus for current services from your departure city to Roermond Station or directly to Designer Outlet Roermond." },
      { order: 2, description: "Book only after confirming the exact arrival stop, departure time, luggage rules, and return time on FlixBus." },
      { order: 3, description: "If your coach arrives at Roermond Station, follow the signed walking route to Designer Outlet Roermond; allow about 10-15 minutes on foot." },
      { order: 4, description: "If your coach stops directly at Designer Outlet Roermond, confirm the return stop location before entering the centre." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "rotterdam-to-roosendaal-train-bus",
    outletId: "designer-outlet-roosendaal",
    originType: "city_center",
    originId: "rotterdam-city-center",
    transportationType: "train",
    title: "Rotterdam to Designer Outlet Roosendaal via Roosendaal",
    estimatedDuration: "",
    estimatedCost: "Check current NS and Bravo fares",
    recommended: true,
    steps: [
      { order: 1, description: "Check the Rotterdam Centraal–Roosendaal train with NS." },
      { order: 2, description: "Travel to Roosendaal with NS." },
      { order: 3, description: "At Roosendaal, check the current Bravo Line 161 connection." },
      { order: 4, description: "Continue to the Designer Outlet Roosendaal stop." },
      { order: 5, description: "Check the return bus and train before shopping." },
    ],
    updatedAt: "2026-08-03",
  },
  {
    guideId: "rotterdam-airport-to-roosendaal-car",
    outletId: "designer-outlet-roosendaal",
    originType: "airport",
    originId: "rotterdam-airport",
    transportationType: "taxi",
    title: "Rotterdam The Hague Airport to Designer Outlet Roosendaal by Car",
    estimatedDuration: "≈45-60 min (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "From Rotterdam The Hague Airport, check current traffic and follow the signed motorway route toward Roosendaal." },
      { order: 2, description: "Use a taxi, rental car, or pre-booked transfer; confirm the fare with the provider before leaving the airport." },
      { order: 3, description: "Navigate to Rosada 70, 4703 TB Roosendaal and follow Designer Outlet Roosendaal parking signs on arrival." },
      { order: 4, description: "Use the official Roosendaal parking guidance: standard parking costs €5 per day and is payable by card or cash." },
      { order: 5, description: "If not driving yourself, agree the return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "amsterdam-centraal-to-amsterdam-style-outlets-train-walk",
    outletId: "amsterdam-the-style-outlets",
    originType: "city_center",
    originId: "amsterdam-centraal",
    transportationType: "train",
    title: "Amsterdam Centraal to Amsterdam The Style Outlets via Halfweg-Zwanenburg",
    estimatedDuration: "",
    estimatedCost: "Check current NS fare",
    recommended: true,
    steps: [
      { order: 1, description: "Check the Amsterdam Centraal–Halfweg-Zwanenburg train." },
      { order: 2, description: "Travel to Halfweg-Zwanenburg with NS." },
      { order: 3, description: "Alight at Halfweg-Zwanenburg." },
      { order: 4, description: "Follow the direct pedestrian connection from the station toward the outlet." },
      { order: 5, description: "Check the return train before shopping." },
    ],
    updatedAt: "2026-08-03",
  },
  {
    guideId: "amsterdam-style-outlets-car-parking-guide",
    outletId: "amsterdam-the-style-outlets",
    originType: "city_center",
    originId: "amsterdam-city-center",
    transportationType: "taxi",
    title: "Driving or Taxi to Amsterdam The Style Outlets with Parking",
    estimatedDuration: "Check traffic",
    estimatedCost: "Check official outlet/SugarCity parking fees; taxi fare varies",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Amsterdam The Style Outlets, SugarCity Ring 1, Halfweg, and check the official outlet and SugarCity parking pages before travel." },
      { order: 2, description: "Drive or take a licensed taxi/private transfer to Halfweg, allowing extra time during weekends and holidays." },
      { order: 3, description: "Use the car park under the outlet when available; SugarCity notes overflow parking can be used during peak periods, with different fees possible." },
      { order: 4, description: "If using a taxi, confirm the fare and return pickup point before shopping." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "amsterdam-to-batavia-stad-shuttle-bus",
    outletId: "batavia-stad-fashion-outlet",
    originType: "city_center",
    originId: "amsterdam-north-overhoeksplein",
    transportationType: "shuttle",
    title: "Amsterdam to Batavia Stad Fashion Outlet by Official Shuttle Bus",
    estimatedDuration: "Check official shuttle timetable",
    estimatedCost: "Check official Batavia Stad shuttle fare before booking",
    recommended: false,
    steps: [
      { order: 1, description: "Open Batavia Stad Fashion Outlet's official shuttle bus page and confirm the Amsterdam pickup point, operating dates, fare and return time." },
      { order: 2, description: "Go to the confirmed Amsterdam North / Overhoeksplein pickup point early with your reservation." },
      { order: 3, description: "Ride the shuttle to Batavia Stad Fashion Outlet and note the return pickup location at the Information Centre or current official stop." },
      { order: 4, description: "Before shopping, confirm the same-day return departure; do not rely on old timetable screenshots." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "amsterdam-to-batavia-stad-train-bus",
    outletId: "batavia-stad-fashion-outlet",
    originType: "city_center",
    originId: "amsterdam-centraal",
    transportationType: "train",
    title: "Amsterdam to Batavia Stad via Lelystad Centrum",
    estimatedDuration: "",
    estimatedCost: "Check current NS and RRReis fares",
    recommended: true,
    steps: [
      { order: 1, description: "Check the Amsterdam Centraal–Lelystad Centrum train with NS." },
      { order: 2, description: "Travel to Lelystad Centrum with NS." },
      { order: 3, description: "At Lelystad Centrum, check the current RRReis Line 13 connection." },
      { order: 4, description: "Take Line 13 to the Batavia Stad stop." },
      { order: 5, description: "Check the return bus and train before shopping." },
    ],
    updatedAt: "2026-08-03",
  },
  {
    guideId: "batavia-stad-car-parking-guide",
    outletId: "batavia-stad-fashion-outlet",
    originType: "city_center",
    originId: "amsterdam-city-center",
    transportationType: "taxi",
    title: "Driving or Taxi to Batavia Stad Fashion Outlet",
    estimatedDuration: "Check traffic",
    estimatedCost: "Check official parking terms; taxi/private transfer fare varies",
    recommended: false,
    steps: [
      { order: 1, description: "Set navigation to Batavia Stad Fashion Outlet, Bataviaplein 267, Lelystad, and check current traffic before departure." },
      { order: 2, description: "Use a rental car, licensed taxi or private transfer only after confirming the fare or rental terms." },
      { order: 3, description: "Follow official Batavia Stad parking signs on arrival and check on-site or official parking information for current rules." },
      { order: 4, description: "If not driving yourself, agree the return pickup point before entering the outlet." },
    ],
    updatedAt: "2026-07-04",
  },
];
