import type { TransportationGuide } from "./index";

export const polandTransportationGuides: TransportationGuide[] = [
  {
    guideId: "warsaw-centre-to-factory-ursus-train-walk",
    outletId: "factory-ursus",
    originType: "city_center",
    originId: "warsaw-city-center",
    transportationType: "train",
    title: "Warsaw City Centre to Factory Ursus by Train and Walk",
    estimatedDuration: "≈20-30 min by train plus ≈10 min walk (estimated)",
    estimatedCost: "Check official ZTM/Koleje Mazowieckie fare",
    recommended: true,
    steps: [
      { order: 1, description: "From Warszawa Centralna, Warszawa Śródmieście or another central stop, plan a suburban rail trip with the official Warsaw public transport or Koleje Mazowieckie planner toward Warszawa Ursus Północny or Warszawa Ursus." },
      { order: 2, description: "Ride the selected SKM or Koleje Mazowieckie service to the Ursus area; keep the ticket valid for the chosen operator and zone." },
      { order: 3, description: "Walk from the station toward Factory Ursus at Plac Czerwca 1976 r. 6, following local pedestrian signs and map directions." },
      { order: 4, description: "For the return trip, check the next rail departure before leaving the shops because evening and weekend frequencies can differ." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "warsaw-chopin-airport-to-factory-ursus-car-public-transport",
    outletId: "factory-ursus",
    originType: "airport",
    originId: "warsaw-chopin-airport",
    transportationType: "taxi",
    title: "Warsaw Chopin Airport to Factory Ursus by Taxi or Public Transport",
    estimatedDuration: "≈15-25 min by car/taxi; ≈35-55 min by public transport (estimated)",
    estimatedCost: "Taxi/ride-hail ≈PLN 35-70 (estimated); public transport fare check ZTM",
    recommended: false,
    steps: [
      { order: 1, description: "From Warsaw Chopin Airport, choose taxi, ride-hail, rental car, or the official ZTM rail/bus planner depending on luggage and traffic." },
      { order: 2, description: "By car or taxi, set Factory Ursus, Plac Czerwca 1976 r. 6, and compare the S2/S8 or local-road routing in live traffic." },
      { order: 3, description: "By public transport, use official ZTM routing from the airport toward Ursus, normally combining rail and/or bus with a final walk to the outlet." },
      { order: 4, description: "For the return to the airport, leave extra buffer time for security and possible road congestion around Warsaw." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "warsaw-public-transport-to-factory-ursus-bus-train",
    outletId: "factory-ursus",
    originType: "station",
    originId: "warsaw-public-transport",
    transportationType: "bus",
    title: "Warsaw Public Transport to Factory Ursus by Bus or Train",
    estimatedDuration: "≈30-45 min from central Warsaw depending on route (estimated)",
    estimatedCost: "Check official ZTM fare",
    recommended: false,
    steps: [
      { order: 1, description: "Open the official ZTM Warszawa journey planner and enter Factory Ursus or Plac Czerwca 1976 r. 6 as the destination." },
      { order: 2, description: "Choose between rail to an Ursus station and bus connections to the Ursus-Ratusz / Plac Czerwca 1976 r. area." },
      { order: 3, description: "After alighting, follow the marked pedestrian route to the shopping entrances and note the stop name for the return journey." },
      { order: 4, description: "Before finishing shopping, check the official timetable for the last useful bus or train back toward central Warsaw." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "factory-ursus-car-parking-guide",
    outletId: "factory-ursus",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Parking at Factory Ursus",
    estimatedDuration: "≈20-30 min from central Warsaw (estimated)",
    estimatedCost: "Parking check centre signage; fuel/ride-hail costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Factory Ursus, Plac Czerwca 1976 r. 6, 02-495 Warszawa." },
      { order: 2, description: "Use the official outlet access page or Google Maps routing to compare S8, Aleje Jerozolimskie and local Ursus approaches." },
      { order: 3, description: "Park in the centre car park; the official Factory Ursus parking page lists 888 car spaces and 28 bicycle spaces." },
      { order: 4, description: "For the return drive, check traffic before leaving the car park, especially at weekday peaks and sale periods." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "factory-ursus-return-trip",
    outletId: "factory-ursus",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "train",
    title: "Return Trip from Factory Ursus to Warsaw Centre or Airport",
    estimatedDuration: "≈20-30 min by train to central Warsaw; airport times vary (estimated)",
    estimatedCost: "Check official ZTM/Koleje Mazowieckie fare; taxi costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "If returning by rail, walk back to the selected Ursus station and confirm the platform and operator before boarding." },
      { order: 2, description: "If returning by bus, use the official ZTM planner from the nearest Ursus stop to your destination." },
      { order: 3, description: "If returning to Warsaw Chopin Airport, add a transfer buffer and compare taxi travel time against public transport." },
      { order: 4, description: "If driving, exit the car park toward the current fastest route and re-check live traffic before joining main roads." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "warsaw-centre-to-factory-annopol-metro-tram",
    outletId: "factory-annopol",
    originType: "city_center",
    originId: "warsaw-city-center",
    transportationType: "metro",
    title: "Warsaw City Centre to Factory Annopol by Metro, Tram or Walk",
    estimatedDuration: "≈20 min by M2 to Bródno plus ≈8 min walk from Bródno (official outlet news)",
    estimatedCost: "Check official ZTM fare",
    recommended: true,
    steps: [
      { order: 1, description: "From central Warsaw, take Metro M2 toward Bródno using the official ZTM timetable or journey planner." },
      { order: 2, description: "The official Factory Annopol news page states the outlet is about 600 m from Bródno metro station and around 20 minutes by M2 from the city centre." },
      { order: 3, description: "From Bródno, walk about 600 m to Factory Annopol or use a short ZTM tram/bus connection if it fits the timetable." },
      { order: 4, description: "For the return trip, check the M2 and any tram/bus connection times before leaving the centre." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "warsaw-chopin-airport-to-factory-annopol-taxi-transit",
    outletId: "factory-annopol",
    originType: "airport",
    originId: "warsaw-chopin-airport",
    transportationType: "taxi",
    title: "Warsaw Chopin Airport to Factory Annopol by Taxi or Public Transport",
    estimatedDuration: "≈30-45 min by car/taxi; ≈50-75 min by public transport (estimated)",
    estimatedCost: "Taxi/ride-hail ≈PLN 70-120 (estimated); public transport fare check ZTM",
    recommended: false,
    steps: [
      { order: 1, description: "From Warsaw Chopin Airport, decide between taxi/ride-hail, rental car, or official ZTM public transport via central Warsaw." },
      { order: 2, description: "By car, set Factory Annopol, Annopol 2, 03-236 Warszawa, and check live routing via S8/Trasa Toruńska or alternative city roads." },
      { order: 3, description: "By public transport, use ZTM routing from the airport to Metro M2 and continue toward Bródno, Annopol or Toruńska stops." },
      { order: 4, description: "For the airport return, allow a larger buffer than the scheduled journey time because cross-city transfers can be delayed." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "warsaw-public-transport-to-factory-annopol-bus-tram",
    outletId: "factory-annopol",
    originType: "station",
    originId: "warsaw-public-transport",
    transportationType: "bus",
    title: "Warsaw Public Transport to Factory Annopol by Metro, Tram or Bus",
    estimatedDuration: "≈30-45 min from central Warsaw (estimated)",
    estimatedCost: "Check official ZTM fare",
    recommended: false,
    steps: [
      { order: 1, description: "Use the official ZTM Warszawa planner for Factory Annopol, Annopol 2, or nearby Annopol / Toruńska / Inowłodzka stops." },
      { order: 2, description: "Select the best current combination of Metro M2, tram and bus; construction and timetable changes can alter the preferred stop." },
      { order: 3, description: "After alighting, follow pedestrian crossings and signs to the outlet entrance rather than walking across roadways informally." },
      { order: 4, description: "Before returning, check the official timetable for the next service back to Metro M2 or central Warsaw." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "factory-annopol-car-parking-guide",
    outletId: "factory-annopol",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Parking at Factory Annopol",
    estimatedDuration: "≈20-35 min from central Warsaw (estimated)",
    estimatedCost: "Parking check centre signage; fuel/ride-hail costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Factory Annopol, Annopol 2, 03-236 Warszawa." },
      { order: 2, description: "Use the official outlet access page or Google Maps routing to choose between S8/Trasa Toruńska and local Warsaw approaches." },
      { order: 3, description: "Follow on-site signs to customer parking and note the entrance or parking section for an easier return." },
      { order: 4, description: "For the return drive, check traffic toward central Warsaw, the airport, or S8 before leaving the parking area." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "factory-annopol-return-trip",
    outletId: "factory-annopol",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "metro",
    title: "Return Trip from Factory Annopol to Warsaw Centre or Airport",
    estimatedDuration: "≈20 min M2 from Bródno to the centre plus walk/transfer; airport times vary (estimated)",
    estimatedCost: "Check official ZTM fare; taxi costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "If returning by metro, walk or connect back to Bródno and board Metro M2 toward central Warsaw." },
      { order: 2, description: "If returning by tram or bus, confirm the stop direction and the next official ZTM departure before leaving the outlet." },
      { order: 3, description: "If returning to Warsaw Chopin Airport, compare public transport against a taxi and leave airport check-in buffer time." },
      { order: 4, description: "If driving, exit toward the selected route and re-check S8/Trasa Toruńska traffic before committing." },
    ],
    updatedAt: "2026-07-03",
  },
];
