import type { TransportationGuide } from "./index";

export const portugalTransportationGuides: TransportationGuide[] = [
  {
    guideId: "lisbon-to-freeport-lisboa-shuttle",
    outletId: "freeport-lisboa-fashion-outlet",
    originType: "city_center",
    originId: "lisbon-city-center",
    transportationType: "shuttle",
    title: "Lisbon City Centre to Freeport Lisboa Fashion Outlet by Official Shuttle",
    estimatedDuration: "≈30 min each way (estimated)",
    estimatedCost: "€14 return; free for children under 12",
    recommended: true,
    steps: [
      { order: 1, description: "Go to the official Cityrama kiosk at Marquês de Pombal, the Freeport Outlet Shuttle sales point listed by the outlet." },
      { order: 2, description: "Buy the official return shuttle ticket before boarding; the outlet lists the ticket at €14 return, with children under 12 travelling free." },
      { order: 3, description: "Ride the direct shuttle from central Lisbon to Freeport Lisboa Fashion Outlet in Alcochete, allowing about 30 minutes in normal traffic." },
      { order: 4, description: "On arrival, note the coach drop-off area and confirm the same-day return departure time before shopping." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "lisbon-airport-to-freeport-lisboa-car",
    outletId: "freeport-lisboa-fashion-outlet",
    originType: "airport",
    originId: "lisbon-airport",
    transportationType: "taxi",
    title: "Lisbon Airport to Freeport Lisboa Fashion Outlet by Car or Taxi",
    estimatedDuration: "≈25-35 min by road (estimated)",
    estimatedCost: "Taxi/ride-hail ≈€30-50 (estimated); rental car costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "From Lisbon Airport, continue by taxi, ride-hail, rental car, or pre-booked transfer toward Alcochete." },
      { order: 2, description: "Use the Vasco da Gama Bridge route when traffic makes it practical, then follow navigation to Av. Euro 2004, 2890-154 Alcochete." },
      { order: 3, description: "Allow about 25-35 minutes in normal traffic; check current road conditions before leaving the terminal." },
      { order: 4, description: "For the return trip to the airport, book pickup in advance and leave extra time for bridge and airport traffic." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "lisbon-to-freeport-lisboa-carris-bus",
    outletId: "freeport-lisboa-fashion-outlet",
    originType: "station",
    originId: "lisbon-public-transport",
    transportationType: "bus",
    title: "Lisbon to Freeport Lisboa Fashion Outlet by Carris Metropolitana Bus",
    estimatedDuration: "Check official Carris Metropolitana timetable",
    estimatedCost: "Check official Carris Metropolitana fare",
    recommended: false,
    steps: [
      { order: 1, description: "Plan the trip on Carris Metropolitana before departure; the outlet highlights Freeport access by lines 4501, 4504, 4600 and reinforced 4702 services." },
      { order: 2, description: "Travel from Lisbon to the confirmed Freeport / Alcochete stop shown in the official timetable." },
      { order: 3, description: "After alighting, follow pedestrian signs or the short walking route to the outlet entrance." },
      { order: 4, description: "Before shopping, check the return timetable and last useful bus back toward Lisbon so you do not miss the connection." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "freeport-lisboa-car-parking",
    outletId: "freeport-lisboa-fashion-outlet",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Parking at Freeport Lisboa Fashion Outlet",
    estimatedDuration: "≈30 min from central Lisbon (estimated)",
    estimatedCost: "Free parking; fuel and tolls vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Freeport Lisboa Fashion Outlet, Av. Euro 2004, 2890-154 Alcochete." },
      { order: 2, description: "From Lisbon, use the current fastest route, commonly via the Vasco da Gama Bridge, and follow Alcochete / Freeport signs." },
      { order: 3, description: "Park in the official outlet car park and note your parking section before entering the centre." },
      { order: 4, description: "For the return drive, check traffic toward Lisbon and bridge conditions before leaving the car park." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "freeport-lisboa-return-trip",
    outletId: "freeport-lisboa-fashion-outlet",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "bus",
    title: "Return Trip from Freeport Lisboa Fashion Outlet to Lisbon",
    estimatedDuration: "≈30 min by shuttle/car; bus times vary (estimated)",
    estimatedCost: "Included with official shuttle return ticket; public bus fares vary",
    recommended: false,
    steps: [
      { order: 1, description: "If you arrived by official shuttle, confirm the return pickup point and departure time when you arrive at Freeport." },
      { order: 2, description: "If you arrived by Carris Metropolitana bus, re-check the live or official timetable before the final hour of shopping." },
      { order: 3, description: "If returning by taxi or ride-hail, request pickup at the outlet entrance or the designated drop-off area and allow for evening traffic." },
      { order: 4, description: "Keep your shuttle ticket, public transport card, or ride booking ready until you are back in Lisbon." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "porto-to-vila-do-conde-fashion-outlet-metro",
    outletId: "vila-do-conde-porto-fashion-outlet",
    originType: "city_center",
    originId: "porto-city-center",
    transportationType: "train",
    title: "Porto City Centre to Vila do Conde Porto Fashion Outlet by Metro",
    estimatedDuration: "30 min by direct metro line",
    estimatedCost: "Check official Metro do Porto / Andante fare",
    recommended: true,
    steps: [
      { order: 1, description: "From central Porto, use Metro do Porto toward the VC Fashion Outlet / Modivas stop, following the official metro journey planner for the next departure." },
      { order: 2, description: "The outlet operator states the centre has a direct metro line to Porto in 30 minutes." },
      { order: 3, description: "Exit at VC Fashion Outlet / Modivas and follow the signed pedestrian access directly to the outlet." },
      { order: 4, description: "For the return trip, check the next Metro do Porto departure toward Porto before leaving the shops." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "porto-airport-to-vila-do-conde-fashion-outlet-car",
    outletId: "vila-do-conde-porto-fashion-outlet",
    originType: "airport",
    originId: "porto-airport",
    transportationType: "taxi",
    title: "Porto Airport to Vila do Conde Porto Fashion Outlet by Car or Taxi",
    estimatedDuration: "10 min by road",
    estimatedCost: "Taxi/ride-hail ≈€12-25 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "From Porto Airport, take a taxi, ride-hail, rental car, or pre-booked transfer toward Modivas." },
      { order: 2, description: "The outlet operator lists the centre as 10 minutes from Porto International Airport." },
      { order: 3, description: "Use Avenida Fonte Cova, 4485-592 Modivas, and follow signs for Vila do Conde Porto Fashion Outlet." },
      { order: 4, description: "For the return airport trip, book pickup early and allow extra time for baggage, terminal access, and traffic." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "porto-to-vila-do-conde-fashion-outlet-public-transport",
    outletId: "vila-do-conde-porto-fashion-outlet",
    originType: "station",
    originId: "porto-trindade-station",
    transportationType: "metro",
    title: "Porto Trindade to Vila do Conde Porto Fashion Outlet by Public Transport",
    estimatedDuration: "≈30-35 min (official/estimated)",
    estimatedCost: "Check official Andante fare",
    recommended: true,
    steps: [
      { order: 1, description: "Start at Porto Trindade or another convenient Metro do Porto station and validate the correct Andante ticket before boarding." },
      { order: 2, description: "Take the direct metro service toward VC Fashion Outlet / Modivas; the operator advertises a 30-minute direct metro connection from Porto." },
      { order: 3, description: "Leave the station at VC Fashion Outlet / Modivas and use the direct pedestrian access to the shopping centre." },
      { order: 4, description: "For the return, confirm the platform and next departure toward Porto on the official Metro do Porto information before exiting the centre." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "vila-do-conde-fashion-outlet-car-parking",
    outletId: "vila-do-conde-porto-fashion-outlet",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Parking at Vila do Conde Porto Fashion Outlet",
    estimatedDuration: "20 min from central Porto; 10 min from Porto Airport",
    estimatedCost: "Free parking",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Vila do Conde Porto Fashion Outlet, Avenida Fonte Cova, 4485-592 Modivas." },
      { order: 2, description: "Use the A28 / Modivas access according to current navigation; the operator highlights direct A28 motorway access." },
      { order: 3, description: "Park in the official free parking area and note the entrance used for an easier return to your car." },
      { order: 4, description: "Before leaving, check A28 traffic toward Porto, Vila do Conde, the cruise terminal, or the airport." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "vila-do-conde-fashion-outlet-return-trip",
    outletId: "vila-do-conde-porto-fashion-outlet",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "metro",
    title: "Return Trip from Vila do Conde Porto Fashion Outlet to Porto",
    estimatedDuration: "30 min by direct metro; road times vary",
    estimatedCost: "Check official Andante fare; road costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "For metro returns, walk back to VC Fashion Outlet / Modivas and check the next departure toward Porto before leaving the centre." },
      { order: 2, description: "Validate or keep your Andante ticket ready for inspection on Metro do Porto." },
      { order: 3, description: "For car, taxi, or ride-hail returns, use the official parking or pickup area and check current A28 traffic." },
      { order: 4, description: "If connecting to Porto Airport or the cruise terminal, leave a buffer beyond the advertised 10-15 minute road access times." },
    ],
    updatedAt: "2026-07-03",
  },
];
