import type { TransportationGuide } from "./index";

export const romaniaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "bucharest-center-to-fashion-house-militari-car",
    outletId: "fashion-house-outlet-centre-bucharest",
    originType: "city_center",
    originId: "bucharest-city-center",
    transportationType: "taxi",
    title: "Bucharest City Center to Fashion House Outlet Centre Bucharest by Car or Taxi",
    estimatedDuration: "≈30-45 min (estimated)",
    estimatedCost: "Parking free; taxi or ride-hail fare confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Set the destination to Fashion House Outlet Centre Bucharest, Strada Comerțului 7-13, Domnești, Ilfov, in West Park Militari." },
      { order: 2, description: "Leave central Bucharest toward Militari and the A1 motorway; the official contact page places the outlet in West Park Militari, and operator information describes direct A1 / ring-road access." },
      { order: 3, description: "Confirm traffic before departure because the A1 and western ring-road approaches can slow at peak times." },
      { order: 4, description: "Use the West Park / outlet visitor parking areas on arrival and note the entrance or parking zone for your return." },
      { order: 5, description: "For the return trip, book the taxi or ride-hail pickup before the outlet closes and allow extra time for evening traffic back into Bucharest." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "bucharest-center-to-fashion-house-militari-public-transport",
    outletId: "fashion-house-outlet-centre-bucharest",
    originType: "city_center",
    originId: "bucharest-city-center",
    transportationType: "bus",
    title: "Bucharest City Center to Fashion House Outlet Centre Bucharest by Metro and Bus",
    estimatedDuration: "≈45-70 min (estimated)",
    estimatedCost: "Check official STB / Metrorex fares",
    recommended: false,
    steps: [
      { order: 1, description: "From central Bucharest, take Metrorex line M3 toward Preciziei and get off at Păcii or Preciziei, whichever has the best onward bus connection on the official planner." },
      { order: 2, description: "Transfer to an official STB metropolitan bus serving the West Park / Fashion House area, commonly via Militari / A1 corridor stops; confirm the live route and stop name before boarding." },
      { order: 3, description: "Get off at the West Park / Fashion House stop closest to Strada Comerțului 7-13 and walk to the outlet entrance." },
      { order: 4, description: "Buy or validate both metro and STB tickets according to the official fare rules before travel." },
      { order: 5, description: "For the return, check the last STB bus from West Park toward Păcii or Preciziei before shopping, then continue by metro back to the city center." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "otp-airport-to-fashion-house-militari-transfer",
    outletId: "fashion-house-outlet-centre-bucharest",
    originType: "airport",
    originId: "bucharest-henri-coanda-airport",
    transportationType: "taxi",
    title: "Bucharest Henri Coandă Airport to Fashion House Outlet Centre Bucharest",
    estimatedDuration: "≈35-60 min (estimated)",
    estimatedCost: "Taxi or ride-hail fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "At Henri Coandă Airport, use an official taxi, ride-hail pickup, rental car, or pre-booked transfer and confirm luggage space and fare before leaving the terminal." },
      { order: 2, description: "Travel toward Bucharest's western side and West Park Militari, then set the final destination to Strada Comerțului 7-13, Domnești, Ilfov." },
      { order: 3, description: "If using public transport from the airport, first use the official airport rail link to București Nord, then continue across the city by metro and bus; this is usually slower than a direct road transfer." },
      { order: 4, description: "For the return to the airport, pre-book pickup from the outlet and allow a generous traffic buffer for flights." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "gara-de-nord-to-fashion-house-militari-public-transport",
    outletId: "fashion-house-outlet-centre-bucharest",
    originType: "station",
    originId: "bucharest-north-station",
    transportationType: "train",
    title: "Bucharest North Station to Fashion House Outlet Centre Bucharest",
    estimatedDuration: "≈50-75 min (estimated)",
    estimatedCost: "Check official Metrorex / STB fares",
    recommended: false,
    steps: [
      { order: 1, description: "From București Nord, use Metrorex to reach the M3 corridor toward Păcii or Preciziei, changing lines as required by the official journey planner." },
      { order: 2, description: "At Păcii or Preciziei, transfer to the official STB bus connection toward West Park / Fashion House on Strada Comerțului." },
      { order: 3, description: "Walk from the West Park / Fashion House stop to the outlet entrance." },
      { order: 4, description: "For the return, check the STB bus frequency before leaving the outlet, then reconnect to Metrorex for București Nord." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "bucharest-to-fashion-house-pallady-car-a2-cernica",
    outletId: "fashion-house-outlet-centre-pallady",
    originType: "city_center",
    originId: "bucharest-city-center",
    transportationType: "taxi",
    title: "Bucharest to Fashion House Outlet Centre Pallady by Car",
    estimatedDuration: "Check current map directions",
    estimatedCost: "Not specified by official source",
    recommended: true,
    steps: [
      { order: 1, description: "Set the destination to Fashion House Outlet Centre Pallady, Intrarea pe A2, km 15, Cernica, Ilfov." },
      { order: 2, description: "Travel toward Autostrada Soarelui A2 and use the Cernica exit area identified by the official Pallady page." },
      { order: 3, description: "Follow current road signs and map navigation for the final approach to the outlet entrance." },
    ],
    updatedAt: "2026-07-05",
  }
];
