import type { TransportationGuide } from "./index";

export const slovakiaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "bratislava-to-voderady-car",
    outletId: "voderady-designer-outlet",
    originType: "city_center",
    originId: "bratislava-city-center",
    transportationType: "taxi",
    title: "Bratislava to Voderady Designer Outlet by Car",
    estimatedDuration: "About 20-30 minutes",
    estimatedCost: "Parking included; motorway vignette, fuel, rental or taxi costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to ONE Fashion Outlet, Voderady 440, 919 42 Voderady." },
      { order: 2, description: "Drive east from Bratislava on the D1 motorway toward Trnava." },
      { order: 3, description: "Leave at the Voderady exit; the official outlet page places the centre about 1,500 metres from the D1 exit ramp." },
      { order: 4, description: "Follow local signs to the outlet parking areas." },
      { order: 5, description: "For the return trip, re-check D1 traffic toward Bratislava before leaving the car park." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "bratislava-airport-to-voderady-car",
    outletId: "voderady-designer-outlet",
    originType: "airport",
    originId: "bratislava-airport",
    transportationType: "taxi",
    title: "Bratislava Airport to Voderady Designer Outlet by Car or Taxi",
    estimatedDuration: "About 25-35 minutes",
    estimatedCost: "Taxi, rental and fuel costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "From Bratislava Airport, use an official taxi, ride-hailing service, pre-booked transfer or rental car." },
      { order: 2, description: "Join the D1 motorway eastbound toward Trnava and Voderady." },
      { order: 3, description: "Exit at Voderady and continue the short signed local approach to the outlet." },
      { order: 4, description: "Confirm your return pickup point with the driver before shopping if you are not using a rental car." },
      { order: 5, description: "For the return trip to the airport, allow extra time for motorway traffic and security." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "trnava-station-to-voderady-bus",
    outletId: "voderady-designer-outlet",
    originType: "station",
    originId: "trnava-railway-station",
    transportationType: "bus",
    title: "Trnava Railway Station to Voderady Designer Outlet by Bus",
    estimatedDuration: "About 20 minutes by outlet-listed bus service",
    estimatedCost: "Check official regional bus fare",
    recommended: true,
    steps: [
      { order: 1, description: "Travel by train to Trnava railway station using the official Slovak rail timetable." },
      { order: 2, description: "Go to the bus stop near Trnava railway station listed by the outlet for the regular bus service to Voderady." },
      { order: 3, description: "Board the regional bus toward ONE Fashion Outlet Voderady; the outlet describes five stops along the way and about 20 minutes of travel time." },
      { order: 4, description: "Get off directly at or beside the outlet and follow pedestrian signs to the shops." },
      { order: 5, description: "For the return trip, check the current regional bus time back to Trnava before shopping, then connect to your train." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "trnava-to-voderady-car-parking",
    outletId: "voderady-designer-outlet",
    originType: "city_center",
    originId: "trnava-city-center",
    transportationType: "taxi",
    title: "Trnava to Voderady Designer Outlet by Car",
    estimatedDuration: "About 10 minutes",
    estimatedCost: "Parking included; fuel or taxi costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "From Trnava, drive toward Voderady and the D1 Voderady exit area." },
      { order: 2, description: "Follow signs to ONE Fashion Outlet, Voderady 440." },
      { order: 3, description: "Use the outlet customer parking areas on arrival." },
      { order: 4, description: "If using a taxi, agree on a return pickup time because local taxi availability can be limited." },
      { order: 5, description: "Return by the same road route toward Trnava and re-check traffic before leaving." },
    ],
    updatedAt: "2026-07-03",
  },
];
