import type { TransportationGuide } from "./index";

export const southKoreaTransportationGuides: TransportationGuide[] = [
  {
    guideId: "seoul-express-bus-terminal-to-yeoju-premium-outlets",
    outletId: "yeoju-premium-outlets",
    originType: "station",
    originId: "seoul-express-bus-terminal",
    transportationType: "bus",
    title: "Seoul Express Bus Terminal to Yeoju Premium Outlets by Direct Express Bus",
    estimatedDuration: "Approx. 1h 10min",
    estimatedCost: "KRW 6,400 one way",
    recommended: true,
    steps: [
      { order: 1, description: "Go to Express Bus Terminal Station and follow signs for Seoul Express Bus Terminal." },
      { order: 2, description: "Board the direct Yeoju Premium Outlets express bus at Seoul Express Bus Terminal Platform 29." },
      { order: 3, description: "The official one-way fare is KRW 6,400." },
      { order: 4, description: "Weekday departures from Gangnam: 09:00, 10:00, 11:00, 13:00, 14:00, 15:00, 17:00, 19:00." },
      { order: 5, description: "Weekday departures from Yeoju: 11:00, 12:00, 13:00, 15:00, 16:00, 17:00, 19:00, 21:00." },
      { order: 6, description: "Weekend and public-holiday departures from Gangnam: 09:00, 10:00, 11:00, 12:00, 13:00, 14:00, 15:00, 17:00, 18:00, 19:00." },
      { order: 7, description: "Weekend and public-holiday departures from Yeoju: 11:00, 12:00, 13:00, 14:00, 15:00, 16:00, 17:00, 19:00, 20:00, 21:00." },
      { order: 8, description: "Ride the express bus for approximately 1 hour 10 minutes to Yeoju Premium Outlets." },
      { order: 9, description: "Confirm the current timetable on the official Yeoju Premium Outlets directions page before travel: https://app.premiumoutlets.co.kr/rpage/en/map/index/01" },
    ],
    updatedAt: "2026-08-13",
  },
  {
    guideId: "myeongdong-to-yeoju-premium-outlets-subway-bus",
    outletId: "yeoju-premium-outlets",
    originType: "station",
    originId: "myeongdong-station",
    transportationType: "bus",
    title: "Myeongdong Station to Yeoju Premium Outlets by Subway and Bus",
    estimatedDuration: "Approx. 2h 30min",
    estimatedCost: "",
    recommended: false,
    steps: [
      { order: 1, description: "Start at Myeongdong Station." },
      { order: 2, description: "Reach Gangnam Station either by Bus 471 from Exit 3 (approximately 30 minutes), or take Line 4 to Sadang Station (approximately 25 minutes) and transfer to Line 2 for Gangnam Station (approximately 14 minutes)." },
      { order: 3, description: "Take the Shinbundang Line from Gangnam Station to Pangyo Station (approximately 20 minutes)." },
      { order: 4, description: "Transfer to the Gyeonggang Line and travel to Yeoju Station (approximately 60 minutes)." },
      { order: 5, description: "Leave Yeoju Station through Exit 4." },
      { order: 6, description: "Take Bus 912, 912-2, or 912-5 to Yeoju Premium Outlets (approximately 15 minutes)." },
      { order: 7, description: "Allow approximately 2 hours 30 minutes for the complete journey." },
      { order: 8, description: "Confirm the current route on the official Yeoju Premium Outlets directions page before travel: https://app.premiumoutlets.co.kr/rpage/en/map/index/01" },
    ],
    updatedAt: "2026-08-13",
  },
  {
    guideId: "hongik-university-to-yeoju-premium-outlets-subway-bus",
    outletId: "yeoju-premium-outlets",
    originType: "station",
    originId: "hongik-university-station",
    transportationType: "bus",
    title: "Hongik University Station to Yeoju Premium Outlets by Subway and Bus",
    estimatedDuration: "Approx. 2h 30min",
    estimatedCost: "",
    recommended: false,
    steps: [
      { order: 1, description: "Start at Hongik University Station." },
      { order: 2, description: "Take Line 2 to Wangsimni Station (approximately 20 minutes)." },
      { order: 3, description: "Transfer to the Suin-Bundang Line and travel to Imae Station (approximately 40 minutes)." },
      { order: 4, description: "Transfer to the Gyeonggang Line and travel to Yeoju Station (approximately 45 minutes)." },
      { order: 5, description: "Leave Yeoju Station through Exit 4." },
      { order: 6, description: "Take Bus 912, 912-2, or 912-5 to Yeoju Premium Outlets (approximately 15 minutes)." },
      { order: 7, description: "Allow approximately 2 hours 30 minutes for the complete journey." },
      { order: 8, description: "Confirm the current route on the official Yeoju Premium Outlets directions page before travel: https://app.premiumoutlets.co.kr/rpage/en/map/index/01" },
    ],
    updatedAt: "2026-08-13",
  },
];
