import type { TransportationGuide } from "./index";

export const spainTransportationGuides: TransportationGuide[] = [
  {
    guideId: "malaga-centro-to-designer-outlet-train",
    outletId: "designer-outlet-malaga",
    originType: "city_center",
    originId: "malaga-city-center",
    transportationType: "train",
    title: "Málaga City Centre to Designer Outlet Málaga by Train",
    estimatedDuration: "≈15 min (official centre estimate)",
    estimatedCost: "≈€1.80–3 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Start at Málaga Centro-Alameda or Málaga-María Zambrano and check the official Renfe Cercanías C1 departures towards Fuengirola." },
      { order: 2, description: "Take the C1 train to Plaza Mayor; Designer Outlet Málaga is next to the station." },
      { order: 3, description: "Follow signs from Plaza Mayor station through the Plaza Mayor retail area to Designer Outlet Málaga." },
      { order: 4, description: "For the return, use Plaza Mayor station and confirm the next C1 train back towards Málaga Centro-Alameda before leaving the centre." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "malaga-airport-to-designer-outlet-train",
    outletId: "designer-outlet-malaga",
    originType: "airport",
    originId: "malaga-airport",
    transportationType: "train",
    title: "Málaga Airport to Designer Outlet Málaga",
    estimatedDuration: "One train stop / ≈5 min (official centre estimate by car)",
    estimatedCost: "≈€1.80–3 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "At Málaga-Costa del Sol Airport station, check official Renfe Cercanías C1 departures towards Fuengirola." },
      { order: 2, description: "Take the C1 train one stop to Plaza Mayor; the centre describes this as an on-site train link from the airport." },
      { order: 3, description: "Exit at Plaza Mayor and walk directly to Designer Outlet Málaga, which is next to the station." },
      { order: 4, description: "For the return to the airport, confirm the next C1 departure from Plaza Mayor before shopping." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "malaga-to-designer-outlet-bus",
    outletId: "designer-outlet-malaga",
    originType: "city_center",
    originId: "malaga-city-center",
    transportationType: "bus",
    title: "Málaga City Centre to Designer Outlet Málaga by Bus",
    estimatedDuration: "≈25–35 min (estimated)",
    estimatedCost: "≈€1.40–2 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "From central Málaga, check the official EMT Málaga Line 5 timetable from Alameda Principal / Córdoba towards Plaza Mayor or Parque de Ocio." },
      { order: 2, description: "Board Line 5 towards Plaza Mayor / Parque de Ocio." },
      { order: 3, description: "Get off at Plaza Mayor stop #2267, which the centre lists as right next to Designer Outlet Málaga." },
      { order: 4, description: "Before shopping, confirm the return Line 5 departure from Plaza Mayor back towards central Málaga." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "madrid-moncloa-to-las-rozas-bus",
    outletId: "las-rozas-village",
    originType: "city_center",
    originId: "madrid-moncloa",
    transportationType: "bus",
    title: "Madrid Moncloa to Las Rozas Village by Bus",
    estimatedDuration: "About 30 min (official)",
    estimatedCost: "≈€2–5 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "At Madrid Moncloa Interchange, check the official CRTM timetable for interurban bus lines 625, 628, or 629 towards Las Rozas." },
      { order: 2, description: "Board the confirmed Moncloa service; Las Rozas Village states these lines reach the Village in about 30 minutes." },
      { order: 3, description: "Get off at the stop directly in front of Las Rozas Village." },
      { order: 4, description: "Check the return 625, 628, or 629 departure from the Village stop before shopping." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "madrid-atocha-to-las-rozas-train",
    outletId: "las-rozas-village",
    originType: "city_center",
    originId: "madrid-atocha",
    transportationType: "train",
    title: "Madrid Atocha to Las Rozas Village by Train and Taxi",
    estimatedDuration: "25 min train plus local transfer (official train duration)",
    estimatedCost: "≈€8–15 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "Check official Renfe Cercanías Madrid services from Atocha to El Pinar de Las Rozas before travelling." },
      { order: 2, description: "Take a Cercanías train towards El Pinar de Las Rozas; Las Rozas Village lists the train journey from Madrid as 25 minutes." },
      { order: 3, description: "At El Pinar de Las Rozas, take a local taxi or rideshare for the final 3 km to Las Rozas Village." },
      { order: 4, description: "For the return, arrange the short taxi transfer back to El Pinar de Las Rozas and confirm the next Cercanías departure to Madrid." },
    ],
    updatedAt: "2026-07-02",
  },
  {
    guideId: "madrid-airport-to-las-rozas-car",
    outletId: "las-rozas-village",
    originType: "airport",
    originId: "madrid-airport",
    transportationType: "taxi",
    title: "Madrid-Barajas Airport to Las Rozas Village by Car",
    estimatedDuration: "≈30–40 min (estimated)",
    estimatedCost: "≈€35–55 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "From Adolfo Suárez Madrid-Barajas Airport, confirm pickup at your terminal and the road route to Las Rozas Village before departure." },
      { order: 2, description: "Use a taxi, chauffeur, or rental car; central Madrid taxis are officially listed at roughly €35, so confirm the airport fare before you travel." },
      { order: 3, description: "Arrive by road and use the official Las Rozas Village parking guidance; parking is complimentary for Village guests." },
      { order: 4, description: "Confirm return pickup or onward travel before shopping, especially for evening airport transfers." },
    ],
    updatedAt: "2026-07-02",
  },

  {
    guideId: "barcelona-to-viladecans-style-outlets-train",
    outletId: "viladecans-the-style-outlets",
    originType: "city_center",
    originId: "barcelona-city-center",
    transportationType: "train",
    title: "Barcelona to Viladecans The Style Outlets by Train",
    estimatedDuration: "check official timetable; station is less than 100 m from the centre",
    estimatedCost: "check official Rodalies fare",
    recommended: true,
    steps: [
      { order: 1, description: "From Barcelona Sants, Passeig de Gràcia or another served station, check the official Rodalies timetable for trains to Viladecans." },
      { order: 2, description: "Take the confirmed Rodalies service to Viladecans station." },
      { order: 3, description: "Exit Viladecans station and walk the signed route to Viladecans The Style Outlets, which official tourism information places less than 100 m from the entrance." },
      { order: 4, description: "Before shopping, check official Rodalies return departures to Barcelona." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "barcelona-airport-to-viladecans-style-outlets-bus",
    outletId: "viladecans-the-style-outlets",
    originType: "airport",
    originId: "barcelona-el-prat-airport",
    transportationType: "bus",
    title: "Barcelona Airport to Viladecans The Style Outlets by Bus",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official AMB fare",
    recommended: true,
    steps: [
      { order: 1, description: "At Barcelona-El Prat Airport, check the official AMB / Baixbus timetable for Line L99 serving Viladecans and the outlet area." },
      { order: 2, description: "Board the confirmed L99 airport bus only after checking the official stop and timetable for your terminal." },
      { order: 3, description: "Get off at the stop serving Viladecans The Style Outlets and follow the pedestrian route to Ctra. de la Vila, 90." },
      { order: 4, description: "Check the official return timetable to the airport before shopping, especially for evening flights." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "barcelona-to-viladecans-style-outlets-bus",
    outletId: "viladecans-the-style-outlets",
    originType: "city_center",
    originId: "barcelona-placa-espanya",
    transportationType: "bus",
    title: "Barcelona Plaça Espanya to Viladecans The Style Outlets by Bus",
    estimatedDuration: "check official timetable",
    estimatedCost: "check official AMB fare",
    recommended: false,
    steps: [
      { order: 1, description: "From Plaça Espanya / Gran Via, check official AMB or Baixbus timetables for lines serving Viladecans and the outlet area." },
      { order: 2, description: "Board the confirmed bus toward Viladecans and verify the stop closest to Ctra. de la Vila, 90." },
      { order: 3, description: "Walk from the confirmed stop to Viladecans The Style Outlets using signed pedestrian routes." },
      { order: 4, description: "Before shopping, check official return departures to Barcelona." },
    ],
    updatedAt: "2026-07-04",
  },
  {
    guideId: "viladecans-style-outlets-car-parking-guide",
    outletId: "viladecans-the-style-outlets",
    originType: "city_center",
    originId: "barcelona-city-center",
    transportationType: "taxi",
    title: "Viladecans The Style Outlets by Car or Taxi",
    estimatedDuration: "15 min from Barcelona / 10 min from airport (official tourism estimate); check traffic",
    estimatedCost: "more than 1,700 free parking spaces; taxi fare confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set the destination to Viladecans The Style Outlets, Ctra. de la Vila, 90, Viladecans." },
      { order: 2, description: "Use the official access guidance via C-32 exit 50 and follow signs to the centre." },
      { order: 3, description: "Park in the official visitor car park; official tourism information lists more than 1,700 free spaces." },
      { order: 4, description: "If using a taxi, use the on-site taxi rank for the return or confirm a licensed pickup point before shopping." },
    ],
    updatedAt: "2026-07-04",
  },

];
