import type { TransportationGuide } from "./index";

export const spainTransportationGuides: TransportationGuide[] = [
  {
    guideId: "malaga-centro-to-designer-outlet-train",
    outletId: "designer-outlet-malaga",
    originType: "city_center",
    originId: "malaga-city-center",
    transportationType: "train",
    title: "Málaga City Centre to Designer Outlet Málaga by Train",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check the RENFE Cercanías C1 timetable before travelling." },
      { order: 2, description: "Take the C1 line towards Plaza Mayor station." },
      { order: 3, description: "Get off at Plaza Mayor, located next to Designer Outlet Málaga." },
      { order: 4, description: "Check the return C1 timetable before leaving the centre." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "malaga-airport-to-designer-outlet-train",
    outletId: "designer-outlet-malaga",
    originType: "airport",
    originId: "malaga-airport",
    transportationType: "train",
    title: "Málaga Airport to Designer Outlet Málaga",
    estimatedDuration: "One train stop",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "At Málaga Airport, check RENFE Cercanías C1 departures to Plaza Mayor." },
      { order: 2, description: "Take the C1 train one stop to Plaza Mayor." },
      { order: 3, description: "Walk from Plaza Mayor station to Designer Outlet Málaga." },
      { order: 4, description: "For a car or taxi, confirm the fare and use the official centre parking guidance." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "malaga-to-designer-outlet-bus",
    outletId: "designer-outlet-malaga",
    originType: "city_center",
    originId: "malaga-city-center",
    transportationType: "bus",
    title: "Málaga City Centre to Designer Outlet Málaga by Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official EMT Málaga timetable for Line 5 towards Plaza Mayor." },
      { order: 2, description: "Take Line 5 towards Plaza Mayor." },
      { order: 3, description: "Get off at stop #2267, Plaza Mayor, next to the centre." },
      { order: 4, description: "Confirm the return Line 5 departure before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "madrid-moncloa-to-las-rozas-bus",
    outletId: "las-rozas-village",
    originType: "city_center",
    originId: "madrid-moncloa",
    transportationType: "bus",
    title: "Madrid Moncloa to Las Rozas Village by Bus",
    estimatedDuration: "About 30 min",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Madrid regional bus timetable for lines 625, 628, or 629 from Moncloa." },
      { order: 2, description: "Board the confirmed service from the Moncloa interchange." },
      { order: 3, description: "Get off at the stop in front of Las Rozas Village." },
      { order: 4, description: "Check the return bus timetable from Las Rozas Village before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "madrid-atocha-to-las-rozas-train",
    outletId: "las-rozas-village",
    originType: "city_center",
    originId: "madrid-atocha",
    transportationType: "train",
    title: "Madrid Atocha to Las Rozas Village by Train and Taxi",
    estimatedDuration: "25 min train plus local transfer",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check RENFE Cercanías services C8A, C8B, or C10 to El Pinar de Las Rozas." },
      { order: 2, description: "Travel from Madrid Atocha to El Pinar de Las Rozas." },
      { order: 3, description: "From El Pinar de Las Rozas, take a taxi for the remaining 3 km to Las Rozas Village." },
      { order: 4, description: "Confirm train and taxi availability for the return trip before leaving the Village." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "madrid-airport-to-las-rozas-car",
    outletId: "las-rozas-village",
    originType: "airport",
    originId: "madrid-airport",
    transportationType: "taxi",
    title: "Madrid-Barajas Airport to Las Rozas Village by Car",
    estimatedDuration: "Less than 30 min",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Adolfo Suárez Madrid-Barajas Airport to Las Rozas Village." },
      { order: 2, description: "Use a taxi, chauffeur, or rental car and confirm the fare before departure." },
      { order: 3, description: "Use the official Las Rozas Village parking guidance; parking is free." },
      { order: 4, description: "Confirm return pickup or onward travel before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
];
