import type { TransportationGuide } from "./index";

export const swedenTransportationGuides: TransportationGuide[] = [
  {
    guideId: "gothenburg-to-hede-fashion-outlet-train-walk",
    outletId: "hede-fashion-outlet",
    originType: "city_center",
    originId: "gothenburg-city-center",
    transportationType: "train",
    title: "Gothenburg City Centre to Hede Fashion Outlet by Train and Walk",
    estimatedDuration: "≈20-25 min train to Hede plus ≈8-10 min walk (estimated)",
    estimatedCost: "Check official Västtrafik fare",
    recommended: true,
    steps: [
      { order: 1, description: "From Göteborg Central, use the official Västtrafik planner for trains toward Kungsbacka and choose a service stopping at Hede station." },
      { order: 2, description: "Ride to Hede station, keeping your Västtrafik ticket active for the selected zones." },
      { order: 3, description: "Walk from Hede station to Hede Fashion Outlet, Kungsparksvägen 80, following pedestrian routes and local signs." },
      { order: 4, description: "For the return trip, check the next Västtrafik train toward Göteborg Central before leaving the shops." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "gothenburg-landvetter-airport-to-hede-fashion-outlet",
    outletId: "hede-fashion-outlet",
    originType: "airport",
    originId: "gothenburg-landvetter-airport",
    transportationType: "taxi",
    title: "Gothenburg Landvetter Airport to Hede Fashion Outlet by Car or Transit",
    estimatedDuration: "45 min by road from Gothenburg Landvetter Airport (official VIA Outlets); public transport varies",
    estimatedCost: "Taxi/transfer fare check provider; public transport fare check operators",
    recommended: false,
    steps: [
      { order: 1, description: "From Gothenburg Landvetter Airport, choose rental car, taxi, pre-booked transfer, or airport coach plus Västtrafik connections." },
      { order: 2, description: "By road, set Hede Fashion Outlet, Kungsparksvägen 80, 434 39 Kungsbacka; VIA Outlets lists the centre 45 minutes from the airport." },
      { order: 3, description: "By public transport, use official airport coach information to reach Gothenburg and the official Västtrafik planner for the train onward to Hede." },
      { order: 4, description: "For the return to Landvetter, pre-check coach, train and transfer times and allow airport security buffer time." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "vasttrafik-to-hede-fashion-outlet-train-bus",
    outletId: "hede-fashion-outlet",
    originType: "station",
    originId: "gothenburg-central-station",
    transportationType: "train",
    title: "Västtrafik Public Transport to Hede Fashion Outlet",
    estimatedDuration: "≈20-25 min train plus walk; bus alternatives check official timetable (estimated)",
    estimatedCost: "Check official Västtrafik fare",
    recommended: true,
    steps: [
      { order: 1, description: "Plan the complete journey in the official Västtrafik app or website, selecting Hede station or the nearest Kungsbacka/Hede bus stop." },
      { order: 2, description: "Use the train when available for the most direct trip from Gothenburg; choose bus alternatives from Kungsbacka or nearby suburbs when the planner recommends them." },
      { order: 3, description: "From the station or stop, follow the walking route to Kungsparksvägen 80 and the outlet entrances." },
      { order: 4, description: "Before shopping late, save the return itinerary in Västtrafik so you know the last practical connection." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "hede-fashion-outlet-car-parking-guide",
    outletId: "hede-fashion-outlet",
    originType: "city_center",
    originId: "driving",
    transportationType: "taxi",
    title: "Driving and Parking at Hede Fashion Outlet",
    estimatedDuration: "30 min from Gothenburg city; 45 min from Gothenburg Landvetter Airport (official VIA Outlets)",
    estimatedCost: "Parking check centre signage; road costs vary",
    recommended: true,
    steps: [
      { order: 1, description: "Set navigation to Hede Fashion Outlet, Kungsparksvägen 80, 434 39 Kungsbacka." },
      { order: 2, description: "VIA Outlets lists Hede Fashion Outlet 30 minutes from Gothenburg city and 45 minutes from Gothenburg Landvetter Airport; check live E6 traffic before departure." },
      { order: 3, description: "Use the official centre route/parking information and follow on-site parking signs when you arrive." },
      { order: 4, description: "For the return drive, check E6 conditions toward Gothenburg, Kungsbacka or Landvetter before leaving the car park." },
    ],
    updatedAt: "2026-07-03",
  },
  {
    guideId: "hede-fashion-outlet-return-trip",
    outletId: "hede-fashion-outlet",
    originType: "city_center",
    originId: "return-trip",
    transportationType: "train",
    title: "Return Trip from Hede Fashion Outlet to Gothenburg or Landvetter Airport",
    estimatedDuration: "≈20-25 min train to Göteborg Central plus walk; 45 min by road to Landvetter (estimated/official road time)",
    estimatedCost: "Check official Västtrafik fare; taxi/transfer costs vary",
    recommended: false,
    steps: [
      { order: 1, description: "If returning by train, walk back to Hede station and board the planned Västtrafik service toward Göteborg Central." },
      { order: 2, description: "If returning by the official seasonal free shopping bus, confirm that it is operating and note the Heden, Bohusgatan drop-off in central Gothenburg." },
      { order: 3, description: "If returning to Gothenburg Landvetter Airport, compare taxi/transfer timing with train plus airport coach and leave extra airport buffer time." },
      { order: 4, description: "If driving, exit the outlet car park and re-check E6 and airport-route traffic before starting the return journey." },
    ],
    updatedAt: "2026-07-03",
  },
];
