import type { TransportationGuide } from "./index";

export const ukTransportationGuides: TransportationGuide[] = [
  {
    guideId: "london-marylebone-to-bicester-train",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-marylebone",
    transportationType: "train",
    title: "London Marylebone to Bicester Village by Train",
    estimatedDuration: "Less than 60 min",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Go to London Marylebone station and check the Chiltern Railways timetable before travelling." },
      { order: 2, description: "Use the Bicester Village train-station kiosk for assistance when staffed." },
      { order: 3, description: "Take the direct train from London Marylebone to Bicester Village station." },
      { order: 4, description: "Exit at Bicester Village station and follow the signed route to the Village entrance." },
      { order: 5, description: "Confirm the last suitable return train before shopping, especially for evening visits." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-victoria-to-bicester-coach",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-victoria",
    transportationType: "bus",
    title: "London to Bicester Village by Official Coach",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Bicester Village coach page and operator timetable before booking." },
      { order: 2, description: "Go to the confirmed Evan Evans Tours departure point in London." },
      { order: 3, description: "Board the direct coach service to Bicester Village." },
      { order: 4, description: "Confirm the same-day return departure time with the operator before leaving the coach." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "heathrow-to-bicester-public-transport",
    outletId: "bicester-village",
    originType: "airport",
    originId: "heathrow-airport",
    transportationType: "train",
    title: "Heathrow Airport to Bicester Village by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check Heathrow, Transport for London, and Chiltern Railways journey planners for the current route." },
      { order: 2, description: "Travel from Heathrow to London and connect to London Marylebone." },
      { order: 3, description: "Take a Chiltern Railways train from London Marylebone to Bicester Village station." },
      { order: 4, description: "Follow signs from Bicester Village station to the Village entrance." },
      { order: 5, description: "For the return trip, confirm the last train connection back through London before you travel." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-bicester-car",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "taxi",
    title: "London to Bicester Village by Car or Chauffeur",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set Bicester Village, 50 Pingle Drive, Bicester OX26 6WD as the destination." },
      { order: 2, description: "Confirm traffic, fare, luggage capacity, and waiting policy with the chauffeur or taxi provider." },
      { order: 3, description: "Use the official Village parking guidance on arrival; complimentary parking and EV charging are available." },
      { order: 4, description: "Agree a return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "liverpool-to-cheshire-oaks-train-bus",
    outletId: "cheshire-oaks",
    originType: "city_center",
    originId: "liverpool-city-center",
    transportationType: "train",
    title: "Liverpool to Cheshire Oaks by Train and Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check National Rail and the local bus operator timetable for services to Ellesmere Port and Cheshire Oaks." },
      { order: 2, description: "Travel by train from Liverpool towards Ellesmere Port." },
      { order: 3, description: "Continue from Ellesmere Port by the confirmed local bus route or taxi to Cheshire Oaks Designer Outlet." },
      { order: 4, description: "Confirm the return bus and train times before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "liverpool-airport-to-cheshire-oaks-car",
    outletId: "cheshire-oaks",
    originType: "airport",
    originId: "liverpool-airport",
    transportationType: "taxi",
    title: "Liverpool Airport to Cheshire Oaks by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Liverpool John Lennon Airport to Kinsey Road, Ellesmere Port CH65 9JJ." },
      { order: 2, description: "Use a taxi, pre-booked transfer, or rental car and confirm the fare before departure." },
      { order: 3, description: "Follow official Cheshire Oaks parking signs on arrival." },
      { order: 4, description: "Book or confirm the return transfer before closing time." },
    ],
    updatedAt: "2026-07-01",
  },

  {
    guideId: "ashford-international-to-ashford-designer-outlet-walk",
    outletId: "ashford-designer-outlet",
    originType: "station",
    originId: "ashford-international-station",
    transportationType: "walking",
    title: "Ashford International to Ashford Designer Outlet on Foot",
    estimatedDuration: "≈10 min walk (estimated)",
    estimatedCost: "Free",
    recommended: true,
    steps: [
      { order: 1, description: "Check the official Ashford Designer Outlet visit page before travel for current walking and cycling guidance." },
      { order: 2, description: "Arrive at Ashford International, which the outlet identifies as the closest rail access for visitors." },
      { order: 3, description: "Follow signed pedestrian routes from the station area to Kimberley Way and the outlet entrances." },
      { order: 4, description: "For the return trip, allow time to walk back to Ashford International and check the official rail timetable." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-ashford-designer-outlet-train",
    outletId: "ashford-designer-outlet",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "train",
    title: "London to Ashford Designer Outlet by Train",
    estimatedDuration: "38 min train ride from London",
    estimatedCost: "≈£15–35 rail fare (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Use the official outlet page and National Rail planner to confirm a Southeastern high-speed service from London St Pancras International to Ashford International." },
      { order: 2, description: "Travel by train to Ashford International." },
      { order: 3, description: "Walk from Ashford International to Ashford Designer Outlet via the signed route to Kimberley Way." },
      { order: 4, description: "Before shopping, check the return train time from Ashford International to London." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "ashford-designer-outlet-car-parking",
    outletId: "ashford-designer-outlet",
    originType: "city_center",
    originId: "ashford-city-center",
    transportationType: "taxi",
    title: "Ashford to Ashford Designer Outlet by Car or Taxi",
    estimatedDuration: "≈5–10 min drive from Ashford town centre (estimated)",
    estimatedCost: "Parking £3 every four hours; local taxi ≈£8–12 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "Set Ashford Designer Outlet, Kimberley Way, Kent TN24 0SD as the destination." },
      { order: 2, description: "Approach via the M20 Junction 9, Junction 10, Junction 10a, A20, A2070 or A28 as advised by the official outlet page." },
      { order: 3, description: "Use the outlet car parks; parking is free for up to 30 minutes, for blue badge holders and after 5 pm." },
      { order: 4, description: "Confirm a return taxi pickup point at the outlet entrances or check onward travel before leaving the centre." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "york-to-york-designer-outlet-car",
    outletId: "york-designer-outlet",
    originType: "city_center",
    originId: "york-city-center",
    transportationType: "taxi",
    title: "York to York Designer Outlet by Car or Taxi",
    estimatedDuration: "15 min drive from York",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for York Designer Outlet before setting off." },
      { order: 2, description: "Set St Nicholas Avenue, Fulford, York YO19 4TA as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "york-to-york-designer-outlet-public-transport",
    outletId: "york-designer-outlet",
    originType: "city_center",
    originId: "york-city-center",
    transportationType: "bus",
    title: "York to York Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for York Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "York station is a 15 minute bus ride from York Designer Outlet." },
      { order: 3, description: "Arriva 42 and 415, First York 7 and East Yorkshire 18 serve the outlet from York city centre or Selby." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-york-designer-outlet-transfer",
    outletId: "york-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to York Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official York Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "Leeds Bradford Airport is a 45 minute drive from the outlet." },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gloucester-to-gloucester-quays-car",
    outletId: "gloucester-quays",
    originType: "city_center",
    originId: "gloucester-city-center",
    transportationType: "taxi",
    title: "Gloucester to Gloucester Quays by Car or Taxi",
    estimatedDuration: "≈5–10 min drive from Gloucester city centre (estimated)",
    estimatedCost: "Taxi ≈£8–12 (estimated); confirm official car park tariff",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official Gloucester Quays getting-here page before setting off." },
      { order: 2, description: "Set GL1 5SH as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Ticketless and cashless parking; confirm tariff." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gloucester-to-gloucester-quays-public-transport",
    outletId: "gloucester-quays",
    originType: "city_center",
    originId: "gloucester-city-center",
    transportationType: "bus",
    title: "Gloucester to Gloucester Quays by Public Transport",
    estimatedDuration: "≈10–20 min by local bus or ≈20 min walk from Gloucester station (estimated)",
    estimatedCost: "Stagecoach Gloucester dayrider £5 adult",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official Gloucester Quays getting-here page, Stagecoach Gloucester Quays offer page and current operator timetable before travel." },
      { order: 2, description: "Arrive at Gloucester rail station or Transport Hub, then use a local Stagecoach service towards Gloucester Quays or walk via the city centre and docks." },
      { order: 3, description: "Alight at Gloucester Quays or the closest confirmed stop and follow signs to the outlet entrances." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-gloucester-quays-transfer",
    outletId: "gloucester-quays",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Gloucester Quays by Transfer",
    estimatedDuration: "≈60–75 min by road from Bristol Airport (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Gloucester Quays getting-here page and Bristol Airport onward travel guidance before booking." },
      { order: 2, description: "Use an airport taxi, pre-booked transfer or rental car to Gloucester Quays, GL1 5SH." },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "street-to-clarks-village-car",
    outletId: "clarks-village",
    originType: "city_center",
    originId: "street-city-center",
    transportationType: "taxi",
    title: "Street to Clarks Village by Car or Taxi",
    estimatedDuration: "≈5 min drive or ≈10 min walk from Street town centre (estimated)",
    estimatedCost: "Taxi ≈£6–10 (estimated); confirm official parking charges",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official Clarks Village getting-here and parking pages before setting off." },
      { order: 2, description: "Set Clarks Village, Street as the destination and follow official road signs on approach." },
      { order: 3, description: "Use one of the official Clarks Village car parks and check the current car park charges on arrival." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "street-to-clarks-village-public-transport",
    outletId: "clarks-village",
    originType: "city_center",
    originId: "street-city-center",
    transportationType: "bus",
    title: "Street to Clarks Village by Public Transport",
    estimatedDuration: "≈35–50 min from Castle Cary by bus/taxi connection (estimated)",
    estimatedCost: "≈£8–15 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official Clarks Village getting-here page, National Rail train updates and operator bus times before travel." },
      { order: 2, description: "Travel by rail to Castle Cary, then continue towards Street using the confirmed local bus service or a pre-booked taxi." },
      { order: 3, description: "Alight at the closest confirmed Street stop for Clarks Village and follow pedestrian signs to the outlet entrances." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-clarks-village-transfer",
    outletId: "clarks-village",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Clarks Village by Transfer",
    estimatedDuration: "≈55–70 min by road from Bristol Airport (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Clarks Village getting-here page and Bristol Airport onward travel guidance before booking." },
      { order: 2, description: "Use an airport taxi, pre-booked transfer or rental car to Clarks Village, Street." },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "durham-to-dalton-park-car",
    outletId: "dalton-park",
    originType: "city_center",
    originId: "durham-city-center",
    transportationType: "taxi",
    title: "Durham to Dalton Park by Car or Taxi",
    estimatedDuration: "20 min drive from Durham",
    estimatedCost: "Taxi ≈£35–50 (estimated)",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official Dalton Park getting-here page before setting off." },
      { order: 2, description: "Set Murton, Co Durham SR7 9HU as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking; 1,500 spaces." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "durham-to-dalton-park-public-transport",
    outletId: "dalton-park",
    originType: "city_center",
    originId: "durham-city-center",
    transportationType: "bus",
    title: "Durham to Dalton Park by Public Transport",
    estimatedDuration: "≈45–60 min by bus from Durham, or train to Seaham plus ≈5 min taxi (estimated)",
    estimatedCost: "≈£4–10 (estimated)",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official Dalton Park getting-here page plus Go North East and Arriva timetable pages before travel." },
      { order: 2, description: "Use Seaham station as the nearest rail station, then take a short taxi; alternatively start from Durham rail station, which the outlet lists as about 20 minutes by car." },
      { order: 3, description: "Use Go North East X6, X10, X1A, 61, 65 or Arriva 22 to the Dalton Park stop as current timetables allow." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-dalton-park-transfer",
    outletId: "dalton-park",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Dalton Park by Transfer",
    estimatedDuration: "≈30–45 min by road from Newcastle International Airport; ≈35–50 min from Teesside International Airport (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Dalton Park getting-here page and airport onward travel guidance before booking." },
      { order: 2, description: "Newcastle International Airport is 25 miles north; Teesside International Airport is 29 miles south." },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "leeds-to-junction-32-outlet-car",
    outletId: "junction-32-outlet",
    originType: "city_center",
    originId: "leeds-city-center",
    transportationType: "taxi",
    title: "Leeds to Junction 32 Outlet Shopping Village by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Junction 32 Outlet Shopping Village before setting off." },
      { order: 2, description: "Set WF10 4FR as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking; 1,400 spaces." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "leeds-to-junction-32-outlet-public-transport",
    outletId: "junction-32-outlet",
    originType: "city_center",
    originId: "leeds-city-center",
    transportationType: "bus",
    title: "Leeds to Junction 32 Outlet Shopping Village by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Junction 32 Outlet Shopping Village and the relevant public transport operator before travel." },
      { order: 2, description: "Use rail to Castleford or the official current nearest station guidance, then continue by confirmed local bus or taxi." },
      { order: 3, description: "Check official bus timetable for services to the outlet." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-junction-32-outlet-transfer",
    outletId: "junction-32-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Junction 32 Outlet Shopping Village by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Junction 32 Outlet Shopping Village page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-caledonia-park-car",
    outletId: "caledonia-park",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "taxi",
    title: "Gretna to Caledonia Park by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Caledonia Park before setting off." },
      { order: 2, description: "Set Gretna DG16 as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking and dedicated coach parking." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-caledonia-park-public-transport",
    outletId: "caledonia-park",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "bus",
    title: "Gretna to Caledonia Park by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Caledonia Park and the relevant public transport operator before travel." },
      { order: 2, description: "Use Gretna Green or Carlisle rail connections, then continue by confirmed bus or taxi." },
      { order: 3, description: "Use on-site bus stops for most local buses; Stagecoach buses use the Glasgow Road stop." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-caledonia-park-transfer",
    outletId: "caledonia-park",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Caledonia Park by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Caledonia Park page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-gretna-gateway-outlet-village-car",
    outletId: "gretna-gateway-outlet-village",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "taxi",
    title: "Gretna to Gretna Gateway Outlet Village by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Gretna Gateway Outlet Village before setting off." },
      { order: 2, description: "Set Gretna DG16 as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking and dedicated coach parking." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-gretna-gateway-outlet-village-public-transport",
    outletId: "gretna-gateway-outlet-village",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "bus",
    title: "Gretna to Gretna Gateway Outlet Village by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Gretna Gateway Outlet Village and the relevant public transport operator before travel." },
      { order: 2, description: "Use Gretna Green or Carlisle rail connections, then continue by confirmed bus or taxi." },
      { order: 3, description: "Use on-site bus stops for most local buses; Stagecoach buses use the Glasgow Road stop." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-gretna-gateway-outlet-village-transfer",
    outletId: "gretna-gateway-outlet-village",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Gretna Gateway Outlet Village by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Gretna Gateway Outlet Village page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "portsmouth-to-gunwharf-quays-car",
    outletId: "gunwharf-quays",
    originType: "city_center",
    originId: "portsmouth-city-center",
    transportationType: "taxi",
    title: "Portsmouth to Gunwharf Quays by Car or Taxi",
    estimatedDuration: "≈5–15 min drive from Portsmouth city centre (estimated)",
    estimatedCost: "Taxi ≈£8–15 (estimated); car park from £3.50 up to 2 hours",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official Gunwharf Quays getting-here and parking pages before setting off." },
      { order: 2, description: "Set Gunwharf Quays House, Portsmouth PO1 3TZ as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: 24-hour car park; check official tariff." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "portsmouth-to-gunwharf-quays-public-transport",
    outletId: "gunwharf-quays",
    originType: "city_center",
    originId: "portsmouth-city-center",
    transportationType: "bus",
    title: "Portsmouth to Gunwharf Quays by Public Transport",
    estimatedDuration: "≈5 min walk from Portsmouth Harbour station; local bus/ferry times vary",
    estimatedCost: "≈£2–5 local transport fare (estimated); Park & Ride day ticket £4–5",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official Gunwharf Quays getting-here page, Portsmouth Harbour rail information, local bus/ferry operators and Portsmouth Park & Ride before travel." },
      { order: 2, description: "Use Portsmouth Harbour station or The Hard Interchange, then follow the signed pedestrian route to Gunwharf Quays." },
      { order: 3, description: "If driving from outside Portsmouth, consider Portsmouth Park & Ride to The Hard/Gunwharf Quays and confirm the same-day return times." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-gunwharf-quays-transfer",
    outletId: "gunwharf-quays",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Gunwharf Quays by Transfer",
    estimatedDuration: "≈25–40 min by road from Southampton Airport (estimated)",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Gunwharf Quays getting-here page and Southampton Airport onward travel guidance before booking." },
      { order: 2, description: "Use an airport taxi, pre-booked transfer or rental car to Gunwharf Quays House, Portsmouth PO1 3TZ." },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "hatfield-to-the-galleria-outlet-car",
    outletId: "the-galleria-outlet",
    originType: "city_center",
    originId: "hatfield-city-center",
    transportationType: "taxi",
    title: "Hatfield to The Galleria Outlet Shopping by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for The Galleria Outlet Shopping before setting off." },
      { order: 2, description: "Set AL10 9TF as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: From £1.30 weekdays; £3 all day Sat/Sun/Bank Holidays; free after 6 pm." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "hatfield-to-the-galleria-outlet-public-transport",
    outletId: "the-galleria-outlet",
    originType: "city_center",
    originId: "hatfield-city-center",
    transportationType: "bus",
    title: "Hatfield to The Galleria Outlet Shopping by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for The Galleria Outlet Shopping and the relevant public transport operator before travel." },
      { order: 2, description: "Direct trains from Kings Cross take 20 minutes to Hatfield Station; continue by walking, bus or taxi." },
      { order: 3, description: "Bus from Hatfield station takes about 10 minutes; confirm fare and timetable." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-the-galleria-outlet-transfer",
    outletId: "the-galleria-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to The Galleria Outlet Shopping by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official The Galleria Outlet Shopping page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "spalding-to-springfields-outlet-car",
    outletId: "springfields-outlet",
    originType: "city_center",
    originId: "spalding-city-center",
    transportationType: "taxi",
    title: "Spalding to Springfields Outlet Shopping & Leisure by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Springfields Outlet Shopping & Leisure before setting off." },
      { order: 2, description: "Set Springfields, Spalding as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Confirm official parking information." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "spalding-to-springfields-outlet-public-transport",
    outletId: "springfields-outlet",
    originType: "city_center",
    originId: "spalding-city-center",
    transportationType: "bus",
    title: "Spalding to Springfields Outlet Shopping & Leisure by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Springfields Outlet Shopping & Leisure and the relevant public transport operator before travel." },
      { order: 2, description: "Use official train updates to Spalding, then continue by confirmed walking route, bus or taxi." },
      { order: 3, description: "Use official bus times for services to Springfields." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-springfields-outlet-transfer",
    outletId: "springfields-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Springfields Outlet Shopping & Leisure by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Springfields Outlet Shopping & Leisure page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "banbridge-to-the-boulevard-banbridge-car",
    outletId: "the-boulevard-banbridge",
    originType: "city_center",
    originId: "banbridge-city-center",
    transportationType: "taxi",
    title: "Banbridge to The Boulevard Banbridge by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for The Boulevard Banbridge before setting off." },
      { order: 2, description: "Set Outlet Park, Banbridge BT32 4LF as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Confirm official parking information." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "banbridge-to-the-boulevard-banbridge-public-transport",
    outletId: "the-boulevard-banbridge",
    originType: "city_center",
    originId: "banbridge-city-center",
    transportationType: "bus",
    title: "Banbridge to The Boulevard Banbridge by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for The Boulevard Banbridge and the relevant public transport operator before travel." },
      { order: 2, description: "Use Belfast-Dublin, Belfast-Portadown or nearby Lisburn, Portadown, Lurgan, Moira or Newry rail services, then continue by dedicated bus or taxi." },
      { order: 3, description: "Use Translink to Banbridge, Outlet Park (The Boulevard); from the Republic of Ireland check Bus Eireann." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-the-boulevard-banbridge-transfer",
    outletId: "the-boulevard-banbridge",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to The Boulevard Banbridge by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official The Boulevard Banbridge page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "cardiff-to-bridgend-designer-outlet-car",
    outletId: "bridgend-designer-outlet",
    originType: "city_center",
    originId: "cardiff-city-center",
    transportationType: "taxi",
    title: "Cardiff to Bridgend Designer Outlet by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Bridgend Designer Outlet before setting off." },
      { order: 2, description: "Set Derwen, Bridgend as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Confirm official parking information." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "cardiff-to-bridgend-designer-outlet-public-transport",
    outletId: "bridgend-designer-outlet",
    originType: "city_center",
    originId: "cardiff-city-center",
    transportationType: "bus",
    title: "Cardiff to Bridgend Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Bridgend Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "Check official rail timetable to Bridgend, then continue by confirmed local bus or taxi." },
      { order: 3, description: "Check official bus timetable to Bridgend Designer Outlet." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-bridgend-designer-outlet-transfer",
    outletId: "bridgend-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Bridgend Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Bridgend Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "nottingham-to-east-midlands-designer-outlet-car",
    outletId: "east-midlands-designer-outlet",
    originType: "city_center",
    originId: "nottingham-city-center",
    transportationType: "taxi",
    title: "Nottingham to East Midlands Designer Outlet by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for East Midlands Designer Outlet before setting off." },
      { order: 2, description: "Set Mansfield Road, South Normanton as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "nottingham-to-east-midlands-designer-outlet-public-transport",
    outletId: "east-midlands-designer-outlet",
    originType: "city_center",
    originId: "nottingham-city-center",
    transportationType: "bus",
    title: "Nottingham to East Midlands Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for East Midlands Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "Check official rail timetable to nearby stations, then continue by confirmed bus or taxi." },
      { order: 3, description: "Check official bus timetable for services to East Midlands Designer Outlet." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-east-midlands-designer-outlet-transfer",
    outletId: "east-midlands-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to East Midlands Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official East Midlands Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "East Midlands Airport route: confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "swindon-to-swindon-designer-outlet-car",
    outletId: "swindon-designer-outlet",
    originType: "city_center",
    originId: "swindon-city-center",
    transportationType: "taxi",
    title: "Swindon to Swindon Designer Outlet by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Swindon Designer Outlet before setting off." },
      { order: 2, description: "Set Kemble Drive, Swindon SN2 2DY as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Confirm official parking information." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "swindon-to-swindon-designer-outlet-public-transport",
    outletId: "swindon-designer-outlet",
    originType: "city_center",
    originId: "swindon-city-center",
    transportationType: "bus",
    title: "Swindon to Swindon Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Swindon Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "Use Swindon station, then follow official walking, bus or taxi guidance to the outlet." },
      { order: 3, description: "Check official bus timetable for services to Swindon Designer Outlet." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-swindon-designer-outlet-transfer",
    outletId: "swindon-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Swindon Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Swindon Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "birmingham-to-west-midlands-designer-outlet-car",
    outletId: "west-midlands-designer-outlet",
    originType: "city_center",
    originId: "birmingham-city-center",
    transportationType: "taxi",
    title: "Birmingham to West Midlands Designer Outlet by Car or Taxi",
    estimatedDuration: "30 min drive from Birmingham City Centre",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for West Midlands Designer Outlet before setting off." },
      { order: 2, description: "Set Eastern Way, Cannock WS11 7JZ as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking; 26 EV charging bays." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "birmingham-to-west-midlands-designer-outlet-public-transport",
    outletId: "west-midlands-designer-outlet",
    originType: "city_center",
    originId: "birmingham-city-center",
    transportationType: "bus",
    title: "Birmingham to West Midlands Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for West Midlands Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "Use official train guidance to Cannock, then continue by confirmed bus, taxi or walking route." },
      { order: 3, description: "Check official bus timetable for services to Designer Outlet West Midlands." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-west-midlands-designer-outlet-transfer",
    outletId: "west-midlands-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to West Midlands Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official West Midlands Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-icon-outlet-at-the-o2-car",
    outletId: "icon-outlet-at-the-o2",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "taxi",
    title: "London to Outlet Shopping at The O2 by Car or Taxi",
    estimatedDuration: "15 min from central London by tube",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Outlet Shopping at The O2 before setting off." },
      { order: 2, description: "Set The O2, North Greenwich as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Confirm official parking information." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-icon-outlet-at-the-o2-public-transport",
    outletId: "icon-outlet-at-the-o2",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "bus",
    title: "London to Outlet Shopping at The O2 by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Outlet Shopping at The O2 and the relevant public transport operator before travel." },
      { order: 2, description: "Take the Jubilee line to North Greenwich for The O2." },
      { order: 3, description: "Use official bus or Uber Boat by Thames Clippers guidance; river bus stops at North Greenwich Pier." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-icon-outlet-at-the-o2-transfer",
    outletId: "icon-outlet-at-the-o2",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Outlet Shopping at The O2 by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Outlet Shopping at The O2 page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "doncaster-to-lakeside-village-car",
    outletId: "lakeside-village",
    originType: "city_center",
    originId: "doncaster-city-center",
    transportationType: "taxi",
    title: "Doncaster to Lakeside Village Outlet Shopping by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for Lakeside Village Outlet Shopping before setting off." },
      { order: 2, description: "Set DN4 5PH as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Free parking for Lakeside Village shoppers only." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "doncaster-to-lakeside-village-public-transport",
    outletId: "lakeside-village",
    originType: "city_center",
    originId: "doncaster-city-center",
    transportationType: "bus",
    title: "Doncaster to Lakeside Village Outlet Shopping by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for Lakeside Village Outlet Shopping and the relevant public transport operator before travel." },
      { order: 2, description: "Use Doncaster rail station, then continue by confirmed bus, taxi or walking route." },
      { order: 3, description: "Check official bus timetable for services to Lakeside Village." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-lakeside-village-transfer",
    outletId: "lakeside-village",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to Lakeside Village Outlet Shopping by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official Lakeside Village Outlet Shopping page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-london-designer-outlet-car",
    outletId: "london-designer-outlet",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "taxi",
    title: "London to London Designer Outlet by Car or Taxi",
    estimatedDuration: "9 min train from London Marylebone",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Review the official getting-here or plan-your-visit page for London Designer Outlet before setting off." },
      { order: 2, description: "Set Wembley Park Boulevard, HA9 0FD as the destination and follow official road signs on approach." },
      { order: 3, description: "Use the official parking guidance on arrival: Use Wembley Park Red Car Park; event-day tariffs may apply." },
      { order: 4, description: "Confirm a safe return pickup point or check traffic before leaving." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-london-designer-outlet-public-transport",
    outletId: "london-designer-outlet",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "bus",
    title: "London to London Designer Outlet by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Review the official getting-here or travel page for London Designer Outlet and the relevant public transport operator before travel." },
      { order: 2, description: "Travel from London Marylebone to Wembley Stadium or use Tube/rail to Wembley Park; LDO is about 10 minutes walk from Wembley Park or Wembley Stadium stations." },
      { order: 3, description: "Use routes 18, 83, 92, 182, 206, 223, 224 or 297 as current TfL timetables allow." },
      { order: 4, description: "Before shopping, confirm the last suitable return service and any interchange needed." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "airport-to-london-designer-outlet-transfer",
    outletId: "london-designer-outlet",
    originType: "airport",
    originId: "nearest-airport",
    transportationType: "taxi",
    title: "Nearest Airport to London Designer Outlet by Transfer",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Check whether the official London Designer Outlet page lists airport or private transport guidance before booking." },
      { order: 2, description: "Confirm with provider" },
      { order: 3, description: "Confirm fare, luggage capacity, pickup point and return arrangements with the provider." },
      { order: 4, description: "On arrival, follow official signs to guest services, entrances and parking or drop-off areas." },
    ],
    updatedAt: "2026-07-01",
  },
];
