import type { TransportationGuide } from "./index";

export const ukTransportationGuides: TransportationGuide[] = [
{
guideId: "london-to-bicester-train",
outletId: "bicester-village",
originType: "city_center",
originId: "london-marylebone",
transportationType: "train",
title: "London City Center to Bicester Village by Train",
estimatedDuration: "45-60 min",
estimatedCost: "£15-35",
recommended: true,
steps: [
{ order: 1, description: "Go to London Marylebone station." },
{ order: 2, description: "Take a direct Chiltern Railways train towards Bicester Village station." },
{ order: 3, description: "Get off at Bicester Village station." },
{ order: 4, description: "Follow signs from the station to the Village entrance." },
{ order: 5, description: "Check return train times before late shopping hours." },
],
updatedAt: "2026-06-29",
},
{
guideId: "heathrow-to-bicester-train",
outletId: "bicester-village",
originType: "airport",
originId: "heathrow-airport",
transportationType: "train",
title: "Heathrow Airport to Bicester Village",
estimatedDuration: "90-120 min",
estimatedCost: "£25-55",
recommended: false,
steps: [
{ order: 1, description: "From Heathrow, travel to central London by Elizabeth line, Heathrow Express, or Underground." },
{ order: 2, description: "Connect to London Marylebone station." },
{ order: 3, description: "Take a Chiltern Railways train to Bicester Village." },
{ order: 4, description: "Walk from Bicester Village station to the shopping area." },
{ order: 5, description: "For heavy luggage, consider a private transfer." },
],
updatedAt: "2026-06-29",
},
{
guideId: "gatwick-to-bicester-train",
outletId: "bicester-village",
originType: "airport",
originId: "gatwick-airport",
transportationType: "train",
title: "Gatwick Airport to Bicester Village",
estimatedDuration: "120-160 min",
estimatedCost: "£35-70",
recommended: false,
steps: [
{ order: 1, description: "Take a train from Gatwick Airport towards central London." },
{ order: 2, description: "Connect across London to Marylebone station." },
{ order: 3, description: "Take the train to Bicester Village station." },
{ order: 4, description: "Walk to the Village entrance." },
{ order: 5, description: "Allow extra time for cross-London transfers." },
],
updatedAt: "2026-06-29",
},
{
guideId: "london-to-bicester-taxi",
outletId: "bicester-village",
originType: "city_center",
originId: "london-city-center",
transportationType: "taxi",
title: "London to Bicester Village by Taxi / Private Transfer",
estimatedDuration: "70-100 min",
estimatedCost: "£90-160",
recommended: false,
steps: [
{ order: 1, description: "Book a taxi or private transfer and set Bicester Village as the destination." },
{ order: 2, description: "Confirm pickup location, fare estimate, and luggage space." },
{ order: 3, description: "Travel via M40 depending on traffic." },
{ order: 4, description: "Ask to be dropped near the main entrance or guest services." },
{ order: 5, description: "Book return pickup before closing time during busy weekends." },
],
updatedAt: "2026-06-29",
},
{
guideId: "liverpool-to-cheshire-oaks-train",
outletId: "cheshire-oaks",
originType: "city_center",
originId: "liverpool-city-center",
transportationType: "train",
title: "Liverpool City Center to Cheshire Oaks",
estimatedDuration: "35-50 min",
estimatedCost: "£6-15",
recommended: true,
steps: [
{ order: 1, description: "Go to Liverpool Central or Liverpool Lime Street." },
{ order: 2, description: "Travel towards Ellesmere Port." },
{ order: 3, description: "Continue by bus or taxi to Cheshire Oaks." },
{ order: 4, description: "Arrive at the main entrance." }
],
updatedAt: "2026-07-01",
},
{
guideId: "liverpool-airport-to-cheshire-oaks",
outletId: "cheshire-oaks",
originType: "airport",
originId: "liverpool-airport",
transportationType: "taxi",
title: "Liverpool Airport to Cheshire Oaks",
estimatedDuration: "35-45 min",
estimatedCost: "£35-55",
recommended: true,
steps: [
{ order: 1, description: "Exit Liverpool John Lennon Airport." },
{ order: 2, description: "Take a taxi, ride service or rental car." },
{ order: 3, description: "Drive towards Ellesmere Port." },
{ order: 4, description: "Follow signs to Cheshire Oaks Designer Outlet." }
],
updatedAt: "2026-07-01",
},
{
guideId: "ellesmere-port-station-to-cheshire-oaks",
outletId: "cheshire-oaks",
originType: "station",
originId: "ellesmere-port-station",
transportationType: "walking",
title: "Ellesmere Port Station to Cheshire Oaks",
estimatedDuration: "20-25 min",
estimatedCost: "Free",
recommended: true,
steps: [
{ order: 1, description: "Exit Ellesmere Port railway station." },
{ order: 2, description: "Walk towards Cheshire Oaks Designer Outlet or use a local bus." },
{ order: 3, description: "Arrive at the outlet entrance." }
],
updatedAt: "2026-07-01",
},
];
