import type { TransportationGuide } from "./index";

export const ukTransportationGuides: TransportationGuide[] = [
  {
    guideId: "london-marylebone-to-bicester-train",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-marylebone",
    transportationType: "train",
    title: "London Marylebone to Bicester Village by Train",
    estimatedDuration: "Less than 60 min",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Go to London Marylebone station and check the Chiltern Railways timetable before travelling." },
      { order: 2, description: "Use the Bicester Village train-station kiosk for assistance when staffed." },
      { order: 3, description: "Take the direct train from London Marylebone to Bicester Village station." },
      { order: 4, description: "Exit at Bicester Village station and follow the signed route to the Village entrance." },
      { order: 5, description: "Confirm the last suitable return train before shopping, especially for evening visits." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-victoria-to-bicester-coach",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-victoria",
    transportationType: "bus",
    title: "London to Bicester Village by Official Coach",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check the official Bicester Village coach page and operator timetable before booking." },
      { order: 2, description: "Go to the confirmed Evan Evans Tours departure point in London." },
      { order: 3, description: "Board the direct coach service to Bicester Village." },
      { order: 4, description: "Confirm the same-day return departure time with the operator before leaving the coach." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "heathrow-to-bicester-public-transport",
    outletId: "bicester-village",
    originType: "airport",
    originId: "heathrow-airport",
    transportationType: "train",
    title: "Heathrow Airport to Bicester Village by Public Transport",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: false,
    steps: [
      { order: 1, description: "Check Heathrow, Transport for London, and Chiltern Railways journey planners for the current route." },
      { order: 2, description: "Travel from Heathrow to London and connect to London Marylebone." },
      { order: 3, description: "Take a Chiltern Railways train from London Marylebone to Bicester Village station." },
      { order: 4, description: "Follow signs from Bicester Village station to the Village entrance." },
      { order: 5, description: "For the return trip, confirm the last train connection back through London before you travel." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-bicester-car",
    outletId: "bicester-village",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "taxi",
    title: "London to Bicester Village by Car or Chauffeur",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Set Bicester Village, 50 Pingle Drive, Bicester OX26 6WD as the destination." },
      { order: 2, description: "Confirm traffic, fare, luggage capacity, and waiting policy with the chauffeur or taxi provider." },
      { order: 3, description: "Use the official Village parking guidance on arrival; complimentary parking and EV charging are available." },
      { order: 4, description: "Agree a return pickup point and time before shopping." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "liverpool-to-cheshire-oaks-train-bus",
    outletId: "cheshire-oaks",
    originType: "city_center",
    originId: "liverpool-city-center",
    transportationType: "train",
    title: "Liverpool to Cheshire Oaks by Train and Bus",
    estimatedDuration: "Check official timetable",
    estimatedCost: "Check official timetable",
    recommended: true,
    steps: [
      { order: 1, description: "Check National Rail and the local bus operator timetable for services to Ellesmere Port and Cheshire Oaks." },
      { order: 2, description: "Travel by train from Liverpool towards Ellesmere Port." },
      { order: 3, description: "Continue from Ellesmere Port by the confirmed local bus route or taxi to Cheshire Oaks Designer Outlet." },
      { order: 4, description: "Confirm the return bus and train times before leaving the outlet." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "liverpool-airport-to-cheshire-oaks-car",
    outletId: "cheshire-oaks",
    originType: "airport",
    originId: "liverpool-airport",
    transportationType: "taxi",
    title: "Liverpool Airport to Cheshire Oaks by Car or Taxi",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: false,
    steps: [
      { order: 1, description: "Confirm the current road route from Liverpool John Lennon Airport to Kinsey Road, Ellesmere Port CH65 9JJ." },
      { order: 2, description: "Use a taxi, pre-booked transfer, or rental car and confirm the fare before departure." },
      { order: 3, description: "Follow official Cheshire Oaks parking signs on arrival." },
      { order: 4, description: "Book or confirm the return transfer before closing time." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "ashford-to-ashford-designer-outlet",
    outletId: "ashford-designer-outlet",
    originType: "city_center",
    originId: "ashford-city-center",
    transportationType: "train",
    title: "Ashford City Center to Ashford Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Ashford city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "cardiff-to-bridgend-designer-outlet",
    outletId: "bridgend-designer-outlet",
    originType: "city_center",
    originId: "cardiff-city-center",
    transportationType: "train",
    title: "Cardiff City Center to Bridgend Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Cardiff city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-caledonia-park",
    outletId: "caledonia-park",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "train",
    title: "Gretna City Center to Caledonia Park Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Gretna city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "street-to-clarks-village",
    outletId: "clarks-village",
    originType: "city_center",
    originId: "street-city-center",
    transportationType: "train",
    title: "Street City Center to Clarks Village",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Street city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "durham-to-dalton-park",
    outletId: "dalton-park",
    originType: "city_center",
    originId: "durham-city-center",
    transportationType: "train",
    title: "Durham City Center to Dalton Park Outlet Shopping Destination",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Durham city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "nottingham-to-east-midlands-designer-outlet",
    outletId: "east-midlands-designer-outlet",
    originType: "city_center",
    originId: "nottingham-city-center",
    transportationType: "train",
    title: "Nottingham City Center to East Midlands Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Nottingham city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gloucester-to-gloucester-quays",
    outletId: "gloucester-quays",
    originType: "city_center",
    originId: "gloucester-city-center",
    transportationType: "train",
    title: "Gloucester City Center to Gloucester Quays",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Gloucester city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "gretna-to-gretna-gateway-outlet-village",
    outletId: "gretna-gateway-outlet-village",
    originType: "city_center",
    originId: "gretna-city-center",
    transportationType: "train",
    title: "Gretna City Center to Gretna Gateway Outlet Village",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Gretna city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "portsmouth-to-gunwharf-quays",
    outletId: "gunwharf-quays",
    originType: "city_center",
    originId: "portsmouth-city-center",
    transportationType: "train",
    title: "Portsmouth City Center to Gunwharf Quays",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Portsmouth city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-icon-outlet-at-the-o2",
    outletId: "icon-outlet-at-the-o2",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "train",
    title: "London City Center to Icon Outlet at The O2",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from London city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "leeds-to-junction-32-outlet",
    outletId: "junction-32-outlet",
    originType: "city_center",
    originId: "leeds-city-center",
    transportationType: "train",
    title: "Leeds City Center to Junction 32 Outlet Shopping Village",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Leeds city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "doncaster-to-lakeside-village",
    outletId: "lakeside-village",
    originType: "city_center",
    originId: "doncaster-city-center",
    transportationType: "train",
    title: "Doncaster City Center to Lakeside Village Outlet Shopping",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Doncaster city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "london-to-london-designer-outlet",
    outletId: "london-designer-outlet",
    originType: "city_center",
    originId: "london-city-center",
    transportationType: "train",
    title: "London City Center to London Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from London city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "spalding-to-springfields-outlet",
    outletId: "springfields-outlet",
    originType: "city_center",
    originId: "spalding-city-center",
    transportationType: "train",
    title: "Spalding City Center to Springfields Outlet Shopping & Leisure",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Spalding city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "swindon-to-swindon-designer-outlet",
    outletId: "swindon-designer-outlet",
    originType: "city_center",
    originId: "swindon-city-center",
    transportationType: "train",
    title: "Swindon City Center to Swindon Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Swindon city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "banbridge-to-the-boulevard-banbridge",
    outletId: "the-boulevard-banbridge",
    originType: "city_center",
    originId: "banbridge-city-center",
    transportationType: "train",
    title: "Banbridge City Center to The Boulevard Banbridge",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Banbridge city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "hatfield-to-the-galleria-outlet",
    outletId: "the-galleria-outlet",
    originType: "city_center",
    originId: "hatfield-city-center",
    transportationType: "train",
    title: "Hatfield City Center to The Galleria Outlet Shopping",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Hatfield city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "birmingham-to-west-midlands-designer-outlet",
    outletId: "west-midlands-designer-outlet",
    originType: "city_center",
    originId: "birmingham-city-center",
    transportationType: "train",
    title: "Birmingham City Center to West Midlands Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from Birmingham city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
  {
    guideId: "york-to-york-designer-outlet",
    outletId: "york-designer-outlet",
    originType: "city_center",
    originId: "york-city-center",
    transportationType: "train",
    title: "York City Center to York Designer Outlet",
    estimatedDuration: "Check official route planner",
    estimatedCost: "Confirm with provider",
    recommended: true,
    steps: [
      { order: 1, description: "Open the outlet official getting-here or plan-your-visit page before travel." },
      { order: 2, description: "Confirm the current rail, bus, coach or driving option from York city centre." },
      { order: 3, description: "Follow official signs to the outlet entrance, guest services and parking areas on arrival." },
    ],
    updatedAt: "2026-07-01",
  },
];
