export const estoniaRestaurants = [
  {
    restaurantId: "t1-tallinn-bad-habits",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Bad Habits",
    category: "Restaurant • Street food",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "t1-tallinn-boost-juice-bar",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Boost Juice Bar",
    category: "Juice Bar",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "t1-tallinn-claudz-family-restaurant-and-cafe",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Claudz – family restaurant and café",
    category: "Restaurant • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "t1-tallinn-crudo-pizza-pasta",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Crudo Pizza & Pasta",
    category: "Pizza • Pasta",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "t1-tallinn-doner-hesekebab-gyros",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Döner HeseKebab® & Gyros",
    category: "Kebab • Gyros",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "t1-tallinn-garage-sushi-burger",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Garage Sushi & Burger",
    category: "Sushi • Burgers",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "t1-tallinn-hesburger",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Hesburger",
    category: "Fast Food",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "t1-tallinn-monk-restoran",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Monk Restoran",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "t1-tallinn-mumm-lounge-baar",
    outletId: "t1-tallinn-outlet",
    restaurantName: "MUMM Lounge baar",
    category: "Bar • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "t1-tallinn-osay-bubble-tea",
    outletId: "t1-tallinn-outlet",
    restaurantName: "OSAY Bubble Tea",
    category: "Bubble Tea",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "t1-tallinn-pann-kook",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Pann & Kook",
    category: "Restaurant • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "t1-tallinn-panorama-lounge",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Panorama Lounge",
    category: "Restaurant • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "t1-tallinn-pelm-deli",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Pelm Deli",
    category: "Lunch",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "t1-tallinn-pelmen-kasitoo-kohvik",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Pelmen Käsitöö Kohvik",
    category: "Restaurant • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "t1-tallinn-puffid-bakery",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Puffid Bakery",
    category: "Bakery • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "t1-tallinn-restoran-pelm",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Restoran Pelm",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "t1-tallinn-restoran-ribi",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Restoran RIBI",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "t1-tallinn-roberts-coffee",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Robert’s Coffee",
    category: "Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "t1-tallinn-susi-grill-chill",
    outletId: "t1-tallinn-outlet",
    restaurantName: "SÜSI Grill & Chill",
    category: "Grill • Street food",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "t1-tallinn-tokumaru",
    outletId: "t1-tallinn-outlet",
    restaurantName: "TOKUMARU",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "t1-tallinn-zumin-lounge-resto",
    outletId: "t1-tallinn-outlet",
    restaurantName: "Zumin Lounge resto",
    category: "Restaurant • Cafe",
    priceLevel: "€€",
    website: "https://t1tallinn.com/en/catering-category/restaurants/",
    status: "active",
    displayOrder: "21",
  },
];
