export const greeceRestaurants = [
  {
    restaurantId: "designer-outlet-athens-everest-exclusive",
    outletId: "designer-outlet-athens",
    restaurantName: "Everest Exclusive",
    category: "Cafe • Quick Service",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "designer-outlet-athens-goodys-burger-house",
    outletId: "designer-outlet-athens",
    restaurantName: "Goody's Burger House",
    category: "Burgers",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "designer-outlet-athens-il-barretto",
    outletId: "designer-outlet-athens",
    restaurantName: "Il Barretto",
    category: "Cafe • Italian",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "designer-outlet-athens-its-all-greek",
    outletId: "designer-outlet-athens",
    restaurantName: "Ιt’s All Greek",
    category: "Greek",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "designer-outlet-athens-la-pasteria",
    outletId: "designer-outlet-athens",
    restaurantName: "La Pasteria",
    category: "Italian • Pasta",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "designer-outlet-athens-mikel-coffee",
    outletId: "designer-outlet-athens",
    restaurantName: "Mikel Coffee",
    category: "Coffee",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "designer-outlet-athens-nueces",
    outletId: "designer-outlet-athens",
    restaurantName: "Nueces",
    category: "Dessert • Nuts",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "designer-outlet-athens-petite-fleur",
    outletId: "designer-outlet-athens",
    restaurantName: "Petite Fleur",
    category: "Cafe",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "designer-outlet-athens-starbucks",
    outletId: "designer-outlet-athens",
    restaurantName: "Starbucks®",
    category: "Coffee",
    priceLevel: "€€",
    website: "https://designeroutletathens.gr/en/restaurants-cafe",
    status: "active",
    displayOrder: "9",
  },
];
