export const irelandRestaurants = [
  {
    restaurantId: "kildare-village-mani-pizza",
    outletId: "kildare-village",
    restaurantName: "Mani Pizza",
    category: "Pizza",
    priceLevel: "€€",
    website: "https://www.thebicestercollection.com/kildare-village/en/dine/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "kildare-village-oakberry",
    outletId: "kildare-village",
    restaurantName: "Oakberry",
    category: "On the go",
    priceLevel: "€€",
    website: "https://www.thebicestercollection.com/kildare-village/en/dine/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "kildare-village-pret-a-manger",
    outletId: "kildare-village",
    restaurantName: "Pret A Manger",
    category: "Coffee",
    priceLevel: "€€",
    website: "https://www.thebicestercollection.com/kildare-village/en/dine/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "kildare-village-saba",
    outletId: "kildare-village",
    restaurantName: "Saba",
    category: "Asian cuisine",
    priceLevel: "€€",
    website:
      "https://www.thebicestercollection.com/kildare-village/en/dine/saba/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "kildare-village-sprout-and-co",
    outletId: "kildare-village",
    restaurantName: "Sprout & Co.",
    category: "All-day dining",
    priceLevel: "€€",
    website: "https://www.thebicestercollection.com/kildare-village/en/dine/",
    status: "active",
    displayOrder: "5",
  },
];
