const alKhiranRestaurants = [
  { name: "% Arabica", website: "https://arabica.coffee/en/location/arabica-kuwait/" },
  { name: "Baskin-Robbins", website: "https://www.baskinrobbinsmea.com/en/kw/store-locator" },
  { name: "Burger King", website: "https://www.burgerking.com.kw/" },
  { name: "Chili's", website: "https://www.chilis.com.kw/" },
  { name: "Chocomelt", website: "https://chocomelt.net/" },
  { name: "Cold Stone Creamery", website: "https://www.coldstonecreamery.com/stores/kuwait/" },
  { name: "Five Guys", website: "https://restaurants.fiveguys.com.kw/" },
  { name: "Hardee's", website: "https://www.hardees.com.kw/" },
  { name: "Jollibee", website: "https://www.jollibee.com.kw/store-locator/" },
  { name: "Joe & The Juice", website: "https://www.joejuice.com/stores" },
  { name: "KFC", website: "https://www.kfc.com.kw/" },
  { name: "Lavazza", website: "https://www.lavazza.com/en/coffee-shops" },
  { name: "MADO", website: "https://mado.com.tr/" },
  { name: "Papa John's", website: "https://www.papajohns.com.kw/" },
  { name: "Pizza Hut", website: "https://www.kuwait.pizzahut.me/" },
  { name: "Pret A Manger", website: "https://www.pret.com/en-KW/find-a-pret" },
  { name: "Starbucks", website: "https://locations.starbucks.com.kw/directory/al-ahmadi/al-khiran-hybrid-outlet-mall" },
  { name: "Subway", website: "https://restaurants.subway.com/kuwait" },
  { name: "Taco Bell", website: "https://www.tacobell.com.kw/" },
  { name: "Tim Hortons", website: "https://timhortonsgcc.com/locations/" },
  { name: "Toby's Estate", website: "https://www.tobysestate.com.kw/" },
] as const;

export const kuwaitRestaurants = alKhiranRestaurants.map(({ name: restaurantName, website }, index) => ({
  restaurantId: `al-khiran-hybrid-outlet-mall-${restaurantName.toLowerCase().replace(/&/g, "and").replace(/'/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
  outletId: "al-khiran-hybrid-outlet-mall",
  restaurantName,
  category: "",
  priceLevel: "",
  website,
  status: "active",
  displayOrder: String(index + 1),
}));
