export const latviaRestaurants = [
  {
    restaurantId: "via-jurmala-casa-mia",
    outletId: "via-jurmala-outlet-village",
    restaurantName: "Casa Mia",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://viajurmala.com/en/restaurants-2/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "via-jurmala-gan-bei",
    outletId: "via-jurmala-outlet-village",
    restaurantName: "Gan Bei",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://viajurmala.com/en/restaurants-2/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "via-jurmala-kafijas-banka",
    outletId: "via-jurmala-outlet-village",
    restaurantName: "Kafijas Banka",
    category: "Cafe",
    priceLevel: "€€",
    website: "https://viajurmala.com/en/restaurants-2/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "via-jurmala-vandal",
    outletId: "via-jurmala-outlet-village",
    restaurantName: "VANDAL",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://viajurmala.com/en/restaurants-2/",
    status: "active",
    displayOrder: "4",
  },
];
