export const polandRestaurants = [
  {
    restaurantId: "factory-ursus-costa-coffee",
    outletId: "factory-ursus",
    restaurantName: "Costa Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://ursus.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "factory-ursus-goraco-polecam",
    outletId: "factory-ursus",
    restaurantName: "Gorąco Polecam",
    category: "Bakery • Cafe",
    priceLevel: "€€",
    website: "https://ursus.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "factory-ursus-love-it",
    outletId: "factory-ursus",
    restaurantName: "Love It",
    category: "Pizza • Italian",
    priceLevel: "€€",
    website: "https://ursus.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "factory-ursus-so-coffee",
    outletId: "factory-ursus",
    restaurantName: "So Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://ursus.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "factory-annopol-grycan-lody-od-pokolen",
    outletId: "factory-annopol",
    restaurantName: "Grycan Lody od Pokoleń",
    category: "Ice Cream • Dessert",
    priceLevel: "€€",
    website: "https://annopol.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "factory-annopol-popolo-pizza-i-pasta",
    outletId: "factory-annopol",
    restaurantName: "Popolo Pizza i Pasta",
    category: "Pizza • Italian",
    priceLevel: "€€",
    website: "https://annopol.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "factory-annopol-so-coffee",
    outletId: "factory-annopol",
    restaurantName: "So Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://annopol.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "factory-annopol-sphinx",
    outletId: "factory-annopol",
    restaurantName: "Sphinx",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://annopol.factory.pl/en/restaurants/restaurants",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-in-asia",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "In Asia",
    category: "Asian • Restaurant",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants/in-asia",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-krasnolod",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "Krasnolód",
    category: "Ice Cream • Dessert",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-pasibus",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "Pasibus",
    category: "Burgers • Restaurant",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants/pasibus-outlet",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-so-coffee",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "So! Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants/so-coffee-outlet",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-starbucks",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "Starbucks",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/news-next/starbucks-i-pasibus",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-tutti-santi",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "Tutti Santi",
    category: "Pizza • Italian",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants/so-coffee-outlet",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "wroclaw-fashion-outlet-wagozercy",
    outletId: "wroclaw-fashion-outlet",
    restaurantName: "Wagożercy",
    category: "Polish • Restaurant",
    priceLevel: "€€",
    website: "https://www.wroclawfashionoutlet.com/en/restaurants/wagozercy",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "designer-outlet-gdansk-da-mere",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Da Mere",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "designer-outlet-gdansk-goraco-polecam",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Gorąco Polecam",
    category: "Bakery • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "designer-outlet-gdansk-kebaya",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Kebaya",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "designer-outlet-gdansk-kuchnia-smaku",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Kuchnia Smaku",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "designer-outlet-gdansk-papa-gyros",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Papa Gyros",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "designer-outlet-gdansk-so-coffee",
    outletId: "designer-outlet-gdansk",
    restaurantName: "So Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "designer-outlet-gdansk-thai-express",
    outletId: "designer-outlet-gdansk",
    restaurantName: "Thai Express",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletgdansk.pl/en/shopping/restaurants",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-thai-express",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Thai Express",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-kuchnia-smaku",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Kuchnia Smaku",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-so-coffee",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "So Coffee",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-goraco-polecam",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Gorąco Polecam",
    category: "Bakery • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-kebaya-kebab",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Kebaya Kebab",
    category: "Kebab • Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-carte-dor",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Carte d'Or",
    category: "Dessert",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "designer-outlet-sosnowiec-big-beef-burger",
    outletId: "designer-outlet-sosnowiec",
    restaurantName: "Big Beef Burger",
    category: "Burger • Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletsosnowiec.pl/en/centre/restaurants",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "designer-outlet-warszawa-green-caffe-nero",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Green Caffè Nero",
    category: "Coffee • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "designer-outlet-warszawa-goraco-polecam",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Gorąco Polecam",
    category: "Bakery • Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "designer-outlet-warszawa-kuchnia-smaku",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Kuchnia Smaku",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "designer-outlet-warszawa-los-santos-bar",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Los Santos Bar",
    category: "Bar • Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "designer-outlet-warszawa-subway",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Subway",
    category: "Sandwiches • Fast Food",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "designer-outlet-warszawa-thai-express",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Thai Express",
    category: "Thai • Restaurant",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "designer-outlet-warszawa-vita-cafe",
    outletId: "designer-outlet-warszawa",
    restaurantName: "Vita Cafe",
    category: "Cafe",
    priceLevel: "€€",
    website: "https://www.designeroutletwarszawa.pl/en/discover/food-drink",
    status: "active",
    displayOrder: "7",
  },
];
