export const romaniaRestaurants = [
  {
    restaurantId: "fashion-house-bucharest-5-to-go",
    outletId: "fashion-house-outlet-centre-bucharest",
    restaurantName: "5 To Go",
    category: "Cafe",
    priceLevel: "€",
    website: "https://fashionhouse.ro/militari/brands/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "fashion-house-bucharest-maroon",
    outletId: "fashion-house-outlet-centre-bucharest",
    restaurantName: "Maroon",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://fashionhouse.ro/militari/brands/maroon/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "fashion-house-bucharest-shan-xi-food-coffee",
    outletId: "fashion-house-outlet-centre-bucharest",
    restaurantName: "Shan-Xi Food & Coffee",
    category: "Cafe • Restaurant",
    priceLevel: "€€",
    website: "https://fashionhouse.ro/militari/brands/shan-xi-food-coffee/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "fashion-house-bucharest-teds-coffee-co",
    outletId: "fashion-house-outlet-centre-bucharest",
    restaurantName: "TED’s Coffee CO",
    category: "Cafe",
    priceLevel: "€€",
    website: "https://fashionhouse.ro/militari/brands/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "fashion-house-outlet-centre-pallady-fornetti",
    outletId: "fashion-house-outlet-centre-pallady",
    restaurantName: "FORNETTI",
    category: "Bakery • Cafe",
    priceLevel: "€",
    website: "https://fashionhouse.ro/pallady/brands/fornetti/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "fashion-house-outlet-centre-pallady-maroon-restaurant",
    outletId: "fashion-house-outlet-centre-pallady",
    restaurantName: "Maroon Restaurant",
    category: "Restaurant",
    priceLevel: "€€",
    website: "https://fashionhouse.ro/pallady/brands/maroon-restaurant/",
    status: "active",
    displayOrder: "2",
  },
];
