export const turkeyRestaurants = [
  {
    restaurantId: "viaport-asia-outlet-shopping-agazade-cag-kebabi",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Ağazade Cağ Kebabı",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-arbys",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Arby's",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-baydoner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Baydöner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-bereket-doner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Bereket Döner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-burger-yiyelim",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Burger Yiyelim",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-bottega",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Bottega",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-burger-king",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-burger-king-2",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Burger King - 2",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-cajun-corner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Cajun Corner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-captain-burger",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Captain Burger",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-colombia-coffee",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Colombia Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-chef-kavurma",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Chef Kavurma",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-durumle",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-dml-turk-kahvesi",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "DML Türk Kahvesi",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-doyuyo",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Doyuyo",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-firuz-baklava",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Firuz Baklava",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-gunaydin-kofte-doner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Günaydın Köfte & Döner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-green-salads",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-greenwich-coffee",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Greenwich Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-happy-moons",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Happy Moon's",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-hd-iskender",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "HD İskender",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-hd-iskender-2",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "HD İskender - 2",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-helvaci-ali",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Helvacı Ali",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-kazan-kofte",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Kazan Köfte",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-kavale",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Kavale",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-captain-doner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Captain Döner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "26",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-ziyafe-kayseri-mutfagi",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Ziyafe Kayseri Mutfağı",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "27",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-krispy-kreme",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Krispy Kreme",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "28",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-magnolia-shop",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Magnolia Shop",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "29",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-makarnam",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Makarnam",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "30",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-maydonoz-doner",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Maydonoz Döner",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "31",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-mado",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Mado",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "32",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-mcdonalds",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "McDonald's",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "33",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-pep-fries",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Pep&Fries",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "34",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-pidem",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "35",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-popeyes",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "36",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-saloon-burger",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "37",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-starbucks",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Starbucks",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "38",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-serander-cafe",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Serander Cafe",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "39",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-simit-sarayi",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Simit Sarayı",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "40",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-simit-sarayi-2",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Simit Sarayı - 2",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "41",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-simit-sarayi-3",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Simit Sarayı - 3",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "42",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-sutliye",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Sütliye",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "43",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-tavuk-dunyasi",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "44",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-the-co-coffee",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "The Co Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "45",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-usta-donerci-sbarro",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Usta Dönerci Sbarro",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "46",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-pilav-tanem",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Pilav Tanem",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "47",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-islak-burger",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "Islak Burger",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "48",
  },
  {
    restaurantId: "viaport-asia-outlet-shopping-1401-coffee",
    outletId: "viaport-asia-outlet-shopping",
    restaurantName: "1401 Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.viaport.com.tr/tr/magazalar",
    status: "active",
    displayOrder: "49",
  },
  {
    restaurantId: "olivium-outlet-center-burger-king",
    outletId: "olivium-outlet-center",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "olivium-outlet-center-popeyes",
    outletId: "olivium-outlet-center",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "olivium-outlet-center-arbys",
    outletId: "olivium-outlet-center",
    restaurantName: "Arby's",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "olivium-outlet-center-pidem",
    outletId: "olivium-outlet-center",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "olivium-outlet-center-bursa-kebap-evi",
    outletId: "olivium-outlet-center",
    restaurantName: "Bursa Kebap Evi",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "olivium-outlet-center-terra-pizza",
    outletId: "olivium-outlet-center",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "olivium-outlet-center-tavuk-dunyasi",
    outletId: "olivium-outlet-center",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "olivium-outlet-center-hd-iskender",
    outletId: "olivium-outlet-center",
    restaurantName: "HD İskender",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "olivium-outlet-center-green-salads",
    outletId: "olivium-outlet-center",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "olivium-outlet-center-saloon-burger",
    outletId: "olivium-outlet-center",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "olivium-outlet-center-durumle",
    outletId: "olivium-outlet-center",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "olivium-outlet-center-cajun-corner",
    outletId: "olivium-outlet-center",
    restaurantName: "Cajun Corner",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "olivium-outlet-center-kumpirbox",
    outletId: "olivium-outlet-center",
    restaurantName: "Kumpirbox",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "olivium-outlet-center-chef-salads",
    outletId: "olivium-outlet-center",
    restaurantName: "Chef Salads",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "olivium-outlet-center-asli-cafe",
    outletId: "olivium-outlet-center",
    restaurantName: "Aslı Cafe",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "olivium-outlet-center-caribou-coffee",
    outletId: "olivium-outlet-center",
    restaurantName: "Caribou Coffee",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "olivium-outlet-center-kofte-piyaz-kadirgali",
    outletId: "olivium-outlet-center",
    restaurantName: "Köfte Piyaz Kadırgalı",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "olivium-outlet-center-my-donuts",
    outletId: "olivium-outlet-center",
    restaurantName: "My Donut's",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "olivium-outlet-center-richards-coffee",
    outletId: "olivium-outlet-center",
    restaurantName: "Richard's Coffee",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "olivium-outlet-center-caffe-nero",
    outletId: "olivium-outlet-center",
    restaurantName: "Caffè Nero",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "olivium-outlet-center-cilgin-waffle",
    outletId: "olivium-outlet-center",
    restaurantName: "Çılgın Waffle",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "olivium-outlet-center-usta-doner",
    outletId: "olivium-outlet-center",
    restaurantName: "Usta Döner",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "olivium-outlet-center-sbarro",
    outletId: "olivium-outlet-center",
    restaurantName: "Sbarro",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "olivium-outlet-center-barrels-oil",
    outletId: "olivium-outlet-center",
    restaurantName: "Barrels & Oil",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "olivium-outlet-center-kasap-doner",
    outletId: "olivium-outlet-center",
    restaurantName: "Kasap Döner",
    category: "",
    priceLevel: "",
    website: "https://olivium.com.tr/tr/foods",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "starcity-outlet-alacati-muhallebicisi",
    outletId: "starcity-outlet",
    restaurantName: "Alaçatı Muhallebicisi",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "starcity-outlet-arbys",
    outletId: "starcity-outlet",
    restaurantName: "Arbys",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "starcity-outlet-baydoner",
    outletId: "starcity-outlet",
    restaurantName: "Baydöner",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "starcity-outlet-bereket-doner",
    outletId: "starcity-outlet",
    restaurantName: "Bereket Döner",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "starcity-outlet-big-bubble-tea",
    outletId: "starcity-outlet",
    restaurantName: "Big Bubble Tea",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "starcity-outlet-burger-king",
    outletId: "starcity-outlet",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "starcity-outlet-bursa-kebap-evi",
    outletId: "starcity-outlet",
    restaurantName: "Bursa Kebap Evi",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "starcity-outlet-caribou-coffee",
    outletId: "starcity-outlet",
    restaurantName: "Caribou Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "starcity-outlet-carls-jr",
    outletId: "starcity-outlet",
    restaurantName: "Carl’s Jr.",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "starcity-outlet-doyuyo",
    outletId: "starcity-outlet",
    restaurantName: "Doyuyo",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "starcity-outlet-durumle",
    outletId: "starcity-outlet",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "starcity-outlet-green-salads",
    outletId: "starcity-outlet",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "starcity-outlet-hd-iskender",
    outletId: "starcity-outlet",
    restaurantName: "Hd İskender",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "starcity-outlet-kahve-dunyasi",
    outletId: "starcity-outlet",
    restaurantName: "Kahve Dünyası",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "starcity-outlet-pidem",
    outletId: "starcity-outlet",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "starcity-outlet-popeyes",
    outletId: "starcity-outlet",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "starcity-outlet-saloon-burger",
    outletId: "starcity-outlet",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "starcity-outlet-sbarro",
    outletId: "starcity-outlet",
    restaurantName: "Sbarro",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "starcity-outlet-sokak-simiti",
    outletId: "starcity-outlet",
    restaurantName: "Sokak Simit'i",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "starcity-outlet-starbucks",
    outletId: "starcity-outlet",
    restaurantName: "Starbucks",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "starcity-outlet-tavuk-dunyasi",
    outletId: "starcity-outlet",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "starcity-outlet-tea-more",
    outletId: "starcity-outlet",
    restaurantName: "Tea&more",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "starcity-outlet-terra-pizza",
    outletId: "starcity-outlet",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "starcity-outlet-usta-donerci",
    outletId: "starcity-outlet",
    restaurantName: "Usta Dönerci",
    category: "",
    priceLevel: "",
    website: "https://www.starcity.com.tr/app/index.php",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "venezia-mega-outlet-pidem",
    outletId: "venezia-mega-outlet",
    restaurantName: "Pidem",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "venezia-mega-outlet-saloon-burger",
    outletId: "venezia-mega-outlet",
    restaurantName: "Saloon Burger",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "venezia-mega-outlet-arbys",
    outletId: "venezia-mega-outlet",
    restaurantName: "Arby's",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "venezia-mega-outlet-burger-king",
    outletId: "venezia-mega-outlet",
    restaurantName: "Burger King",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "venezia-mega-outlet-popeyes",
    outletId: "venezia-mega-outlet",
    restaurantName: "Popeyes",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "venezia-mega-outlet-doyuyo",
    outletId: "venezia-mega-outlet",
    restaurantName: "Doyuyo!",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "venezia-mega-outlet-terra-pizza",
    outletId: "venezia-mega-outlet",
    restaurantName: "Terra Pizza",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "venezia-mega-outlet-durumle",
    outletId: "venezia-mega-outlet",
    restaurantName: "Dürümle",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "venezia-mega-outlet-harbi-burger",
    outletId: "venezia-mega-outlet",
    restaurantName: "Harbi Burger",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "venezia-mega-outlet-burger-yiyelim",
    outletId: "venezia-mega-outlet",
    restaurantName: "Burger Yiyelim",
    category: "Fast Food",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "venezia-mega-outlet-kibris-limonatacisi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Kıbrıs Limonatacısı",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "venezia-mega-outlet-cafe-del-nord",
    outletId: "venezia-mega-outlet",
    restaurantName: "Cafe Del Nord",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "venezia-mega-outlet-dawn-cafe",
    outletId: "venezia-mega-outlet",
    restaurantName: "Dawn Cafe",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "venezia-mega-outlet-faruk-gulluoglu",
    outletId: "venezia-mega-outlet",
    restaurantName: "Faruk Güllüoğlu",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "venezia-mega-outlet-dilek-pastanesi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Dilek Pastanesi",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "venezia-mega-outlet-usta-donerci",
    outletId: "venezia-mega-outlet",
    restaurantName: "Usta Dönerci",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "venezia-mega-outlet-gonul-kahvesi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Gönül Kahvesi",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "venezia-mega-outlet-starbucks-avm-kati",
    outletId: "venezia-mega-outlet",
    restaurantName: "Starbucks - AVM Katı",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "venezia-mega-outlet-mado",
    outletId: "venezia-mega-outlet",
    restaurantName: "Mado",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "venezia-mega-outlet-kayseri-mutfagi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Kayseri Mutfağı",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "venezia-mega-outlet-kahve-dunyasi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Kahve Dünyası",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "venezia-mega-outlet-green-salads",
    outletId: "venezia-mega-outlet",
    restaurantName: "Green Salads",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "venezia-mega-outlet-starbucks-cadde-kati",
    outletId: "venezia-mega-outlet",
    restaurantName: "Starbucks - Cadde Katı",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "venezia-mega-outlet-vitamin-juice",
    outletId: "venezia-mega-outlet",
    restaurantName: "Vitamin Juice",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "venezia-mega-outlet-tavuk-dunyasi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Tavuk Dünyası",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "venezia-mega-outlet-hd-iskender",
    outletId: "venezia-mega-outlet",
    restaurantName: "HD İskender",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "26",
  },
  {
    restaurantId: "venezia-mega-outlet-krispy-kreme",
    outletId: "venezia-mega-outlet",
    restaurantName: "Krispy Kreme",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "27",
  },
  {
    restaurantId: "venezia-mega-outlet-levent-borek",
    outletId: "venezia-mega-outlet",
    restaurantName: "Levent Börek",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "28",
  },
  {
    restaurantId: "venezia-mega-outlet-big-bubble-tea",
    outletId: "venezia-mega-outlet",
    restaurantName: "Big Bubble Tea",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "29",
  },
  {
    restaurantId: "venezia-mega-outlet-tchibo",
    outletId: "venezia-mega-outlet",
    restaurantName: "Tchibo",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "30",
  },
  {
    restaurantId: "venezia-mega-outlet-oses-cigkofte",
    outletId: "venezia-mega-outlet",
    restaurantName: "Oses Çiğköfte",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "31",
  },
  {
    restaurantId: "venezia-mega-outlet-afyon-lokum-atolyesi",
    outletId: "venezia-mega-outlet",
    restaurantName: "Afyon Lokum Atölyesi",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "32",
  },
  {
    restaurantId: "venezia-mega-outlet-hello-sweetie",
    outletId: "venezia-mega-outlet",
    restaurantName: "Hello Sweetie",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "33",
  },
  {
    restaurantId: "venezia-mega-outlet-helvaci-ali",
    outletId: "venezia-mega-outlet",
    restaurantName: "Helvacı Ali",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "34",
  },
  {
    restaurantId: "venezia-mega-outlet-bi-dilim",
    outletId: "venezia-mega-outlet",
    restaurantName: "Bi Dilim",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "35",
  },
  {
    restaurantId: "venezia-mega-outlet-mr-cheesy",
    outletId: "venezia-mega-outlet",
    restaurantName: "Mr. Cheesy",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "36",
  },
  {
    restaurantId: "venezia-mega-outlet-vesca-cikolata",
    outletId: "venezia-mega-outlet",
    restaurantName: "Vesca Çikolata",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "37",
  },
  {
    restaurantId: "venezia-mega-outlet-cold-stone",
    outletId: "venezia-mega-outlet",
    restaurantName: "Cold Stone",
    category: "Restaurant & Cafe",
    priceLevel: "",
    website: "https://veneziamegaoutlet.com/index.php/foods",
    status: "active",
    displayOrder: "38",
  },
];
