const oliviumRestaurants = [
  "ARBY'S",
  "BARRELS AND OIL",
  "BURGER KING",
  "BURSA KEBAP EVİ",
  "CAJUN CORNER",
  "CARIBOU COFFEE",
  "CHEF SALADS",
  "ÇILGIN WAFFLE",
  "DÜRÜMLE",
  "GREEN SALADS",
  "HD İSKENDER",
  "KASAP DÖNER",
  "KÖFTE PİYAZ KADIRGALİ",
  "KUMPİRBOX",
  "PİDEM",
  "POPEYES",
  "SALOON BURGER",
  "SBARRO",
  "TALİMHANE",
  "TAVUK DÜNYASI",
  "TERRA PİZZA",
  "USTA DÖNER",
  "ASLI CAFE",
  "CAFFÈ NERO",
  "MY DONUTS",
  "RICHARD'S COFFEE",
  "JOJO EXPRESS DONDURMA",
  "O SES ÇİĞKÖFTE",
  "HARPUT DİBEK KAHVE",
  "KAFKAS",
] as const;

const starCityRestaurants = [
  "Alaçatı Muhallebicisi",
  "Arbys",
  "Baydöner",
  "Bereket Döner",
  "Big Bubble Tea",
  "Burger King",
  "Bursa Kebap Evi",
  "Caribou Coffee",
  "Carl’s Jr.",
  "Doyuyo",
  "Dürümle",
  "Green Salads",
  "Hd İskender",
  "Kahve Dünyası",
  "Nb Corn",
  "Pidem",
  "Popeyes",
  "Saloon Burger",
  "Sbarro",
  "Sokak Simit'i",
  "Starbucks",
  "Tavuk Dünyası",
  "Tea&more",
  "Terra Pizza",
  "Usta Dönerci",
] as const;

const istanbulOptimumRestaurants = [
  "ARBY'S",
  "Asur Kahvesi",
  "BAY DÖNER",
  "BOSTON DONUTS",
  "BURGER KING",
  "BURSA KEBAP EVİ",
  "ÇÖPS",
  "DÜRÜMLE",
  "GREEN SALADS",
  "Kaffee Schütz",
  "KAHVE DÜNYASI",
  "KAYSERİ MUTFAĞI",
  "MACARONI EXPRESS",
  "ÖZSÜT",
  "PİDEM",
  "POPEYES",
  "SALOON BURGER",
  "SARAY MUHALLEBİCİSİ",
  "STARBUCKS",
  "SUBWAY",
  "SÜTLÜ",
  "TAVUK DÜNYASI",
  "TERRA PIZZA",
  "THE CORNER TANTUNİ",
  "USTA DÖNERCİ",
] as const;

const izmirOptimumRestaurants = [
  "ARBY'S",
  "BAY DÖNER",
  "BIG BUBBLE TEA",
  "BISQUITTE",
  "BOMBACI ZEYDAN",
  "BURGER KING",
  "BURGER YİYELİM",
  "BURSA İSHAK BEY",
  "BURSA KEBAP EVİ",
  "CAJUN CORNER",
  "CHOCNETTE",
  "COOKSHOP",
  "ÇÖPS",
  "DOYUYO",
  "DÜRÜMLE",
  "EL ELE CAFE",
  "FRUITBOX",
  "GLORİA JEANS",
  "GREEN SALADS",
  "HAPPY MOON'S",
  "HD İSKENDER",
  "HELLO SWEETIE",
  "HELVACI ALİ",
  "HİSARÖNÜ SÜTLÜ 1942",
  "İKBAL",
  "KAHVE DİYARI",
  "KAHVE DÜNYASI",
  "KFC",
  "MACARONI",
  "MACARONI EXPRESS",
  "MADO",
  "MC DONALD´S",
  "MEŞHUR HİSARÖNÜ ŞAMBALİCİSİ",
  "MR KUMPİR",
  "OHANNES BURGER",
  "ÖZSÜT",
  "PAŞA FIRINI",
  "PASAPORT PİZZA",
  "PİDE BY PİDE",
  "PİDEM",
  "PİQ CAFE",
  "POPEYES",
  "REYHAN PASTANESİ",
  "SBARRO",
  "STARBUCKS",
  "TANTUNİZM",
  "TAVUK DÜNYASI",
  "TERRA PİZZA",
  "TUCK COFFEE",
  "USTA DÖNERCİ",
  "VONGOLE HOT DOG&STREET FOODS",
  "YOBABA",
  "YOMUMU",
] as const;

function records(outletId: string, names: readonly string[], website: string) {
  return names.map((restaurantName, index) => ({
    restaurantId: `${outletId}-${restaurantName
      .toLocaleLowerCase("tr-TR")
      .replace(/ı/g, "i")
      .replace(/ç/g, "c")
      .replace(/ğ/g, "g")
      .replace(/ö/g, "o")
      .replace(/ş/g, "s")
      .replace(/ü/g, "u")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")}`,
    outletId,
    restaurantName,
    category: "",
    priceLevel: "",
    website,
    status: "active",
    displayOrder: String(index + 1),
  }));
}

export const turkeyRestaurants = [
  ...records(
    "olivium-outlet-center",
    oliviumRestaurants,
    "https://www.olivium.com.tr/tr/magazalar",
  ),
  ...records(
    "starcity-outlet",
    starCityRestaurants,
    "https://www.starcity.com.tr/magazalar",
  ),
  ...records(
    "optimum-premium-outlet-istanbul",
    istanbulOptimumRestaurants,
    "https://www.optimumistanbul.com/magazalar",
  ),
  ...records(
    "izmir-optimum",
    izmirOptimumRestaurants,
    "https://www.izmiroptimum.com/magazalar",
  ),
];
