// Named food-service tenants from the official outlet directories.
export const turkeyRestaurants = [
  {
    restaurantId: "olivium-outlet-center-arbys",
    outletId: "olivium-outlet-center",
    restaurantName: "Arby’s",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "olivium-outlet-center-asl-cafe",
    outletId: "olivium-outlet-center",
    restaurantName: "Aslı Cafe",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "olivium-outlet-center-barrels-and-oil",
    outletId: "olivium-outlet-center",
    restaurantName: "Barrels and Oil",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "olivium-outlet-center-burger-king",
    outletId: "olivium-outlet-center",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "olivium-outlet-center-bursa-kebap-evi",
    outletId: "olivium-outlet-center",
    restaurantName: "Bursa Kebap Evi",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "olivium-outlet-center-caffe-nero",
    outletId: "olivium-outlet-center",
    restaurantName: "Caffè Nero",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "olivium-outlet-center-cajun-corner",
    outletId: "olivium-outlet-center",
    restaurantName: "Cajun Corner",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "olivium-outlet-center-caribou-coffee",
    outletId: "olivium-outlet-center",
    restaurantName: "Caribou Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "olivium-outlet-center-chef-salads",
    outletId: "olivium-outlet-center",
    restaurantName: "Chef Salads",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "olivium-outlet-center-clgn-waffle",
    outletId: "olivium-outlet-center",
    restaurantName: "Çılgın Waffle",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "olivium-outlet-center-durumle",
    outletId: "olivium-outlet-center",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "olivium-outlet-center-green-salads",
    outletId: "olivium-outlet-center",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "olivium-outlet-center-harput-dibek-kahve",
    outletId: "olivium-outlet-center",
    restaurantName: "Harput Dibek Kahve",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "olivium-outlet-center-hd-iskender",
    outletId: "olivium-outlet-center",
    restaurantName: "HD İskender",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "olivium-outlet-center-kasap-doner",
    outletId: "olivium-outlet-center",
    restaurantName: "Kasap Döner",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "olivium-outlet-center-kofte-piyaz-kadral",
    outletId: "olivium-outlet-center",
    restaurantName: "Köfte Piyaz Kadıralı",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "olivium-outlet-center-kumpirbox",
    outletId: "olivium-outlet-center",
    restaurantName: "Kumpirbox",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "olivium-outlet-center-my-donuts",
    outletId: "olivium-outlet-center",
    restaurantName: "My Donuts",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "olivium-outlet-center-o-ses-cigkofte",
    outletId: "olivium-outlet-center",
    restaurantName: "O Ses Çiğköfte",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "olivium-outlet-center-pidem",
    outletId: "olivium-outlet-center",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "olivium-outlet-center-popeyes",
    outletId: "olivium-outlet-center",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "olivium-outlet-center-richards-coffee",
    outletId: "olivium-outlet-center",
    restaurantName: "Richards Coffee",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "olivium-outlet-center-saloon-burger",
    outletId: "olivium-outlet-center",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "olivium-outlet-center-sbarro",
    outletId: "olivium-outlet-center",
    restaurantName: "Sbarro",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "olivium-outlet-center-talimhane",
    outletId: "olivium-outlet-center",
    restaurantName: "TalimHane",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "olivium-outlet-center-tavuk-dunyas",
    outletId: "olivium-outlet-center",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "26",
  },
  {
    restaurantId: "olivium-outlet-center-terra-pizza",
    outletId: "olivium-outlet-center",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "27",
  },
  {
    restaurantId: "olivium-outlet-center-usta-doner",
    outletId: "olivium-outlet-center",
    restaurantName: "Usta Döner",
    category: "",
    priceLevel: "",
    website: "https://www.olivium.com.tr/tr/",
    status: "active",
    displayOrder: "28",
  },
  {
    restaurantId: "starcity-outlet-alacat-muhallebicisi",
    outletId: "starcity-outlet",
    restaurantName: "Alaçatı Muhallebicisi",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "starcity-outlet-arbys",
    outletId: "starcity-outlet",
    restaurantName: "Arbys",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "starcity-outlet-baydoner",
    outletId: "starcity-outlet",
    restaurantName: "Baydöner",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "starcity-outlet-bereket-doner",
    outletId: "starcity-outlet",
    restaurantName: "Bereket Döner",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "starcity-outlet-big-bubble-tea",
    outletId: "starcity-outlet",
    restaurantName: "Big Bubble Tea",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "starcity-outlet-burger-king",
    outletId: "starcity-outlet",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "starcity-outlet-bursa-kebap-evi",
    outletId: "starcity-outlet",
    restaurantName: "Bursa Kebap Evi",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "starcity-outlet-caribou-coffee",
    outletId: "starcity-outlet",
    restaurantName: "Caribou Coffee",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "starcity-outlet-carls-jr",
    outletId: "starcity-outlet",
    restaurantName: "Carl’s Jr.",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "starcity-outlet-doyuyo",
    outletId: "starcity-outlet",
    restaurantName: "Doyuyo",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "starcity-outlet-durumle",
    outletId: "starcity-outlet",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "starcity-outlet-green-salads",
    outletId: "starcity-outlet",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "starcity-outlet-hd-iskender",
    outletId: "starcity-outlet",
    restaurantName: "HD İskender",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "starcity-outlet-kahve-dunyas",
    outletId: "starcity-outlet",
    restaurantName: "Kahve Dünyası",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "starcity-outlet-nb-corn",
    outletId: "starcity-outlet",
    restaurantName: "NB Corn",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "starcity-outlet-pidem",
    outletId: "starcity-outlet",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "starcity-outlet-popeyes",
    outletId: "starcity-outlet",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "starcity-outlet-saloon-burger",
    outletId: "starcity-outlet",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "starcity-outlet-sbarro",
    outletId: "starcity-outlet",
    restaurantName: "Sbarro",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "starcity-outlet-sokak-simiti",
    outletId: "starcity-outlet",
    restaurantName: "Sokak Simit’i",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "starcity-outlet-starbucks",
    outletId: "starcity-outlet",
    restaurantName: "Starbucks",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "starcity-outlet-tavuk-dunyas",
    outletId: "starcity-outlet",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "starcity-outlet-tea-more",
    outletId: "starcity-outlet",
    restaurantName: "Tea&more",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "starcity-outlet-terra-pizza",
    outletId: "starcity-outlet",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "starcity-outlet-usta-donerci",
    outletId: "starcity-outlet",
    restaurantName: "Usta Dönerci",
    category: "",
    priceLevel: "",
    website: "http://www.starcity.com.tr/",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-arbys",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Arby’s",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-asur-kahvesi",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Asur Kahvesi",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-bay-doner",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Bay Döner",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-boston-donuts",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Boston Donuts",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-burger-king",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Burger King",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-bursa-kebap-evi",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Bursa Kebap Evi",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-cops",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Çöps",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-durumle",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-green-salads",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-haribo",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Haribo",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-kaffee-schutz",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Kaffee Schütz",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-kahve-dunyas",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Kahve Dünyası",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-kayseri-mutfag",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Kayseri Mutfağı",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-macaroni-express",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Macaroni Express",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-ozsut",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Özsüt",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-pidem",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-popeyes",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-saloon-burger",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Saloon Burger",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-saray-muhallebicisi",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Saray Muhallebicisi",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-starbucks",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Starbucks",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-subway",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Subway",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-sutlu",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Sütlü",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-tavuk-dunyas",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-terra-pizza",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-the-corner-tantuni",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "The Corner Tantuni",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "optimum-premium-outlet-istanbul-usta-donerci",
    outletId: "optimum-premium-outlet-istanbul",
    restaurantName: "Usta Dönerci",
    category: "",
    priceLevel: "",
    website: "https://optimumistanbul.com/tr/",
    status: "active",
    displayOrder: "26",
  },
  {
    restaurantId: "izmir-optimum-cookshop",
    outletId: "izmir-optimum",
    restaurantName: "Cookshop",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "1",
  },
  {
    restaurantId: "izmir-optimum-cops",
    outletId: "izmir-optimum",
    restaurantName: "Çöps",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "2",
  },
  {
    restaurantId: "izmir-optimum-doyuyo",
    outletId: "izmir-optimum",
    restaurantName: "Doyuyo",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "3",
  },
  {
    restaurantId: "izmir-optimum-durumle",
    outletId: "izmir-optimum",
    restaurantName: "Dürümle",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "4",
  },
  {
    restaurantId: "izmir-optimum-el-ele-cafe",
    outletId: "izmir-optimum",
    restaurantName: "El Ele Cafe",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "5",
  },
  {
    restaurantId: "izmir-optimum-fruitbox",
    outletId: "izmir-optimum",
    restaurantName: "Fruitbox",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "6",
  },
  {
    restaurantId: "izmir-optimum-gloria-jeans",
    outletId: "izmir-optimum",
    restaurantName: "Gloria Jeans",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "7",
  },
  {
    restaurantId: "izmir-optimum-green-salads",
    outletId: "izmir-optimum",
    restaurantName: "Green Salads",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "8",
  },
  {
    restaurantId: "izmir-optimum-happy-moons",
    outletId: "izmir-optimum",
    restaurantName: "Happy Moon’s",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "9",
  },
  {
    restaurantId: "izmir-optimum-hd-iskender",
    outletId: "izmir-optimum",
    restaurantName: "HD İskender",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "10",
  },
  {
    restaurantId: "izmir-optimum-hello-sweetie",
    outletId: "izmir-optimum",
    restaurantName: "Hello Sweetie",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "11",
  },
  {
    restaurantId: "izmir-optimum-helvac-ali",
    outletId: "izmir-optimum",
    restaurantName: "Helvacı Ali",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "12",
  },
  {
    restaurantId: "izmir-optimum-hisaronu-sutlu-1942",
    outletId: "izmir-optimum",
    restaurantName: "Hisarönü Sütlü 1942",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "13",
  },
  {
    restaurantId: "izmir-optimum-ikbal",
    outletId: "izmir-optimum",
    restaurantName: "İkbal",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "14",
  },
  {
    restaurantId: "izmir-optimum-kahve-diyar",
    outletId: "izmir-optimum",
    restaurantName: "Kahve Diyarı",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "15",
  },
  {
    restaurantId: "izmir-optimum-kahve-dunyas",
    outletId: "izmir-optimum",
    restaurantName: "Kahve Dünyası",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "16",
  },
  {
    restaurantId: "izmir-optimum-kfc",
    outletId: "izmir-optimum",
    restaurantName: "KFC",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "17",
  },
  {
    restaurantId: "izmir-optimum-macaroni",
    outletId: "izmir-optimum",
    restaurantName: "Macaroni",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "18",
  },
  {
    restaurantId: "izmir-optimum-macaroni-express",
    outletId: "izmir-optimum",
    restaurantName: "Macaroni Express",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "19",
  },
  {
    restaurantId: "izmir-optimum-mado",
    outletId: "izmir-optimum",
    restaurantName: "Mado",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "20",
  },
  {
    restaurantId: "izmir-optimum-mcdonalds",
    outletId: "izmir-optimum",
    restaurantName: "McDonald’s",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "21",
  },
  {
    restaurantId: "izmir-optimum-meshur-hisaronu-sambalicisi",
    outletId: "izmir-optimum",
    restaurantName: "Meşhur Hisarönü Şambalicisi",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "22",
  },
  {
    restaurantId: "izmir-optimum-mr-kumpir",
    outletId: "izmir-optimum",
    restaurantName: "Mr Kumpir",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "23",
  },
  {
    restaurantId: "izmir-optimum-ohannes-burger",
    outletId: "izmir-optimum",
    restaurantName: "Ohannes Burger",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "24",
  },
  {
    restaurantId: "izmir-optimum-ozsut",
    outletId: "izmir-optimum",
    restaurantName: "Özsüt",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "25",
  },
  {
    restaurantId: "izmir-optimum-pasaport-pizza",
    outletId: "izmir-optimum",
    restaurantName: "Pasaport Pizza",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "26",
  },
  {
    restaurantId: "izmir-optimum-pasa-frn",
    outletId: "izmir-optimum",
    restaurantName: "Paşa Fırını",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "27",
  },
  {
    restaurantId: "izmir-optimum-pide-by-pide",
    outletId: "izmir-optimum",
    restaurantName: "Pide by Pide",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "28",
  },
  {
    restaurantId: "izmir-optimum-pidem",
    outletId: "izmir-optimum",
    restaurantName: "Pidem",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "29",
  },
  {
    restaurantId: "izmir-optimum-piq-cafe",
    outletId: "izmir-optimum",
    restaurantName: "Piq Cafe",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "30",
  },
  {
    restaurantId: "izmir-optimum-popeyes",
    outletId: "izmir-optimum",
    restaurantName: "Popeyes",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "31",
  },
  {
    restaurantId: "izmir-optimum-reyhan-pastanesi",
    outletId: "izmir-optimum",
    restaurantName: "Reyhan Pastanesi",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "32",
  },
  {
    restaurantId: "izmir-optimum-sbarro",
    outletId: "izmir-optimum",
    restaurantName: "Sbarro",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "33",
  },
  {
    restaurantId: "izmir-optimum-starbucks",
    outletId: "izmir-optimum",
    restaurantName: "Starbucks",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "34",
  },
  {
    restaurantId: "izmir-optimum-tantunizm",
    outletId: "izmir-optimum",
    restaurantName: "Tantunizm",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "35",
  },
  {
    restaurantId: "izmir-optimum-tavuk-dunyas",
    outletId: "izmir-optimum",
    restaurantName: "Tavuk Dünyası",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "36",
  },
  {
    restaurantId: "izmir-optimum-terra-pizza",
    outletId: "izmir-optimum",
    restaurantName: "Terra Pizza",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "37",
  },
  {
    restaurantId: "izmir-optimum-tuck-coffee",
    outletId: "izmir-optimum",
    restaurantName: "Tuck Coffee",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "38",
  },
  {
    restaurantId: "izmir-optimum-usta-donerci",
    outletId: "izmir-optimum",
    restaurantName: "Usta Dönerci",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "39",
  },
  {
    restaurantId: "izmir-optimum-vongole-hot-dog-street-foods",
    outletId: "izmir-optimum",
    restaurantName: "Vongole Hot Dog & Street Foods",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "40",
  },
  {
    restaurantId: "izmir-optimum-yobaba",
    outletId: "izmir-optimum",
    restaurantName: "Yobaba",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "41",
  },
  {
    restaurantId: "izmir-optimum-yomumu",
    outletId: "izmir-optimum",
    restaurantName: "Yomumu",
    category: "",
    priceLevel: "",
    website: "https://izmiroptimum.com/en/contact",
    status: "active",
    displayOrder: "42",
  },
];
