import { localizeExpansionPlace } from "./expansionPlaceNames";
import { expansionRoutes, type ExpansionRoute } from "./expansionTransportationData";
import { expansionOutletMetadata } from "./expansionOutletMetadata";
import type { TransportationGuide } from "./transportationGuides";
import type { LocalizedGuideCopy, TargetContentLanguage } from "./targetOutletLocalization";

type L = TargetContentLanguage;
const languages: L[] = ["en", "tr", "es", "fr", "de", "ar", "ru", "zh"];
const dictionary = (values: string[]): Record<L, string> => Object.fromEntries(languages.map((l, i) => [l, values[i]])) as Record<L, string>;
const words = {
 approx: dictionary(["Approx.", "Yaklaşık", "Aprox.", "Env.", "Ca.", "حوالي", "Примерно", "约"]),
 minutes: dictionary(["min", "dk", "min", "min", "Min.", "دقيقة", "мин", "分钟"]),
 oneWay: dictionary(["adult, one way", "yetişkin, tek yön", "adulto, solo ida", "adulte, aller simple", "Erwachsene, einfache Fahrt", "للبالغ، اتجاه واحد", "взрослый, в одну сторону", "成人单程"]),
 roundTrip: dictionary(["adult, round trip", "yetişkin, gidiş-dönüş", "adulto, ida y vuelta", "adulte, aller-retour", "Erwachsene, Hin- und Rückfahrt", "للبالغ، ذهاب وعودة", "взрослый, туда и обратно", "成人往返"]),
 from: dictionary(["from", "başlangıç", "desde", "à partir de", "ab", "ابتداءً من", "от", "起价"]),
 vehicle: dictionary(["per vehicle, one way", "araç başına, tek yön", "por vehículo, solo ida", "par véhicule, aller simple", "pro Fahrzeug, einfache Fahrt", "للسيارة، اتجاه واحد", "за машину, в одну сторону", "每车单程"]),
 free: dictionary(["Free", "Ücretsiz", "Gratis", "Gratuit", "Kostenlos", "مجانًا", "Бесплатно", "免费"]),
 board: dictionary(["Board {line} at {from}; alight at {to}.", "{from} noktasından {line} hattına bin; {to} noktasında in.", "Sube a {line} en {from}; baja en {to}.", "Prenez {line} à {from} ; descendez à {to}.", "Steigen Sie bei {from} in {line} ein und bei {to} aus.", "اركب {line} من {from}، وانزل عند {to}.", "Сядьте на {line} на остановке {from}; выйдите на {to}.", "在{from}乘坐{line}，到{to}下车。"]),
 transfer: dictionary(["Transfer: ", "Aktarma: ", "Transbordo: ", "Correspondance : ", "Umstieg: ", "الانتقال: ", "Пересадка: ", "换乘："]),
 finish: dictionary(["Follow the pedestrian signs to the outlet entrance.", "Outlet girişine yönlendiren yaya tabelalarını takip et.", "Sigue las señales peatonales hasta la entrada del outlet.", "Suivez les panneaux piétons jusqu’à l’entrée de l’outlet.", "Folgen Sie den Fußwegweisern zum Outlet-Eingang.", "اتبع لافتات المشاة إلى مدخل الأوتلت.", "Следуйте пешеходным указателям ко входу в аутлет.", "沿步行指示牌前往奥特莱斯入口。"]),
 verify: dictionary(["Check the operator’s timetable and last return before departure. Journey ranges are planning estimates and include walking/transfer allowance; long waits and heavy traffic can add time.", "Yola çıkmadan operatörün tarifesini ve son dönüş saatini kontrol et. Süre aralıkları yürüyüş/aktarma payı içeren planlama tahminidir; uzun bekleme ve yoğun trafik süreyi uzatabilir.", "Comprueba el horario y la última vuelta antes de salir. Las duraciones son estimaciones con margen para caminar y transbordar; las esperas y el tráfico pueden alargarlas.", "Vérifiez les horaires et le dernier retour avant le départ. Les durées sont indicatives et prévoient marche et correspondances ; l’attente et la circulation peuvent les prolonger.", "Prüfen Sie Fahrplan und letzte Rückfahrt vor der Abfahrt. Die Zeitspannen sind Planungswerte mit Geh- und Umsteigezeit; längere Wartezeiten und Stau können hinzukommen.", "تحقق من جدول المشغّل وآخر رحلة عودة قبل المغادرة. المدد تقديرية وتشمل وقتًا للمشي والانتقال؛ وقد تزيد بسبب الانتظار والازدحام.", "Перед выездом проверьте расписание и последний обратный рейс. Время ориентировочное, с запасом на переходы и пересадки; ожидание и пробки могут его увеличить.", "出发前确认运营方时刻表和末班返程。时间范围为含步行和换乘余量的估算，长时间等候或堵车可能延长行程。"]),
 official: dictionary(["Operator / official route", "Operatör / resmî rota", "Operador / ruta oficial", "Opérateur / trajet officiel", "Betreiber / offizielle Route", "المشغّل / المسار الرسمي", "Перевозчик / официальный маршрут", "运营方／官方路线"]),
 daily: dictionary(["Daily", "Her gün", "Todos los días", "Tous les jours", "Täglich", "يوميًا", "Ежедневно", "每天"]),
 monSat: dictionary(["Mon–Sat", "Pzt–Cmt", "Lun–sáb", "Lun–sam", "Mo–Sa", "الاثنين–السبت", "Пн–сб", "周一至周六"]),
 sunday: dictionary(["Sun", "Paz", "Dom", "Dim", "So", "الأحد", "Вс", "周日"]),
 holidays: dictionary(["Holiday and individual store hours may vary.", "Tatil günleri ve mağaza saatleri değişebilir.", "Los festivos y los horarios de cada tienda pueden variar.", "Les horaires des jours fériés et des boutiques peuvent varier.", "Feiertags- und einzelne Ladenöffnungszeiten können abweichen.", "قد تختلف المواعيد في العطلات ومن متجر لآخر.", "В праздники и у отдельных магазинов часы могут отличаться.", "节假日及各店铺营业时间可能不同。"]),
 parking: dictionary(["On-site parking; check current conditions and charges.", "Tesis bünyesinde otopark; güncel koşul ve ücretleri kontrol et.", "Aparcamiento en el recinto; consulta condiciones y tarifas.", "Parking sur place ; consultez les conditions et tarifs.", "Parkplätze vor Ort; aktuelle Bedingungen und Gebühren prüfen.", "مواقف داخل الموقع؛ تحقق من الشروط والرسوم الحالية.", "Парковка на территории; уточняйте условия и стоимость.", "设有停车场，请确认当前规定与收费。"]),
 count: dictionary(["listed brands", "listelenen marka", "marcas listadas", "marques répertoriées", "gelistete Marken", "علامة تجارية مدرجة", "представленных брендов", "个已列出品牌"]),
 straight: dictionary(["straight-line distance", "kuş uçuşu mesafe", "distancia en línea recta", "distance à vol d’oiseau", "Luftlinie", "مسافة بخط مستقيم", "расстояние по прямой", "直线距离"]),
};
const notes: Record<string, Record<L, string>> = {
 reserve: dictionary(["Reserve the outbound and return journey in advance; use the pickup details in your booking confirmation.", "Gidiş ve dönüşü önceden ayırt; rezervasyon onayındaki biniş noktasını kullan.", "Reserva la ida y la vuelta con antelación y sigue el punto de recogida de la confirmación.", "Réservez l’aller et le retour à l’avance et suivez le lieu de prise en charge confirmé.", "Buchen Sie Hin- und Rückfahrt vorab; maßgeblich ist der bestätigte Abholort.", "احجز الذهاب والعودة مسبقًا واتبع نقطة الالتقاء في تأكيد الحجز.", "Заранее забронируйте поездку в обе стороны; место посадки указано в подтверждении.", "提前预订去程和返程，并以预订确认中的上车地点为准。"]),
 arrive15: dictionary(["Arrive 15 minutes before departure. The outlet return pickup is Bus Plaza 2.", "Kalkıştan 15 dakika önce gel. Outlet dönüş binişi Bus Plaza 2 noktasındadır.", "Llega 15 minutos antes. La vuelta sale de Bus Plaza 2.", "Arrivez 15 minutes avant le départ. Le retour part de Bus Plaza 2.", "Seien Sie 15 Minuten früher da. Die Rückfahrt startet an Bus Plaza 2.", "احضر قبل المغادرة بـ15 دقيقة. نقطة العودة هي Bus Plaza 2.", "Приходите за 15 минут. Обратная посадка — Bus Plaza 2.", "提前15分钟到达。返程在Bus Plaza 2上车。"]),
 bookingFees: dictionary(["The displayed price is the advertised base ticket; booking fees, taxes and optional extras may increase the total.", "Gösterilen tutar ilan edilen temel bilettir; rezervasyon ücreti, vergi ve ek hizmetler toplamı artırabilir.", "El precio indicado es la tarifa base; tasas, impuestos y extras pueden aumentar el total.", "Le prix affiché est le tarif de base ; frais de réservation, taxes et options peuvent s’ajouter.", "Angezeigt wird der Grundpreis; Buchungsgebühren, Steuern und Extras können hinzukommen.", "السعر المعروض أساسي؛ قد تضاف رسوم حجز وضرائب وخدمات اختيارية.", "Указан базовый тариф; сборы, налоги и дополнительные услуги могут увеличить сумму.", "显示价格为基础票价，预订费、税费及附加服务可能另计。"]),
 exactCash: dictionary(["Carry exact cash or use the operator’s accepted pass/payment method; drivers may not give change.", "Tam tutarda nakit veya operatörün kabul ettiği kart/bileti kullan; sürücü para üstü vermeyebilir.", "Lleva el importe exacto o un medio de pago aceptado; puede que no haya cambio.", "Prévoyez l’appoint ou un titre accepté ; le conducteur peut ne pas rendre la monnaie.", "Halten Sie passendes Bargeld oder ein akzeptiertes Ticket bereit; Wechselgeld ist eventuell nicht möglich.", "جهّز المبلغ النقدي بالضبط أو وسيلة دفع مقبولة؛ قد لا يتوفر باقي نقدي.", "Подготовьте точную сумму или принимаемый проездной; сдачи может не быть.", "请准备准确现金或运营方接受的车票／支付方式，司机可能不找零。"]),
 loop: dictionary(["This is a circulating downtown shuttle. Check today’s operating hours and the direction of the loop for the return trip.", "Şehir merkezinde ring seferidir. Güncel çalışma saatini ve dönüş için ring yönünü kontrol et.", "Es una lanzadera circular por el centro. Comprueba el horario y el sentido para volver.", "Cette navette suit une boucle en centre-ville. Vérifiez les horaires et le sens pour le retour.", "Der Shuttle fährt einen Rundkurs durch die Innenstadt. Prüfen Sie Betriebszeiten und Rückfahrtrichtung.", "هذه حافلة دائرية في وسط المدينة. تحقق من ساعات التشغيل واتجاه مسار العودة.", "Шаттл ходит по кругу в центре города. Проверьте часы работы и направление обратной поездки.", "这是市中心循环接驳车，请确认当天运营时间及返程方向。"]),
 anaheim: dictionary(["Departure is from Anaheim, not Palm Springs. Tours currently run Wednesday and Saturday; pickup is around 08:30–08:45. The full shopping excursion takes about 9 hours.", "Kalkış Anaheim’dandır. Turlar şu anda çarşamba ve cumartesi; otelden alım yaklaşık 08:30–08:45. Alışveriş dahil tam tur yaklaşık 9 saat sürer.", "La salida es desde Anaheim. Actualmente opera miércoles y sábados, con recogida sobre las 08:30–08:45. La excursión completa dura unas 9 horas.", "Le départ se fait d’Anaheim. Départs actuels mercredi et samedi, prise en charge vers 08:30–08:45. L’excursion complète dure environ 9 heures.", "Abfahrt in Anaheim. Derzeit mittwochs und samstags, Abholung etwa 08:30–08:45. Der gesamte Einkaufsausflug dauert rund 9 Stunden.", "الانطلاق من Anaheim. الرحلات حاليًا الأربعاء والسبت، والاستلام نحو 08:30–08:45. تستغرق الجولة كاملة حوالي 9 ساعات.", "Отправление из Anaheim. Сейчас туры по средам и субботам, сбор около 08:30–08:45. Вся поездка с покупками занимает около 9 часов.", "从Anaheim出发。目前周三和周六运营，约08:30–08:45接客。含购物的完整行程约9小时。"]),
 bartExtra: dictionary(["The quoted fare covers Wheels route 14 only. Travel to Dublin/Pleasanton on BART costs extra; Clipper transfer credit may reduce the bus fare. Wheels’ adult day pass is USD 4.", "Ücret yalnızca Wheels 14 içindir. Dublin/Pleasanton’a BART yolculuğu ayrıca ödenir; Clipper aktarma indirimi otobüs ücretini düşürebilir. Wheels yetişkin günlük bileti USD 4.", "La tarifa solo incluye Wheels 14. BART se paga aparte; Clipper puede aplicar descuento de transbordo. El pase diario adulto de Wheels cuesta USD 4.", "Le tarif couvre seulement Wheels 14. BART est en supplément ; Clipper peut réduire le coût du bus. Le pass journalier adulte Wheels coûte USD 4.", "Der Preis gilt nur für Wheels 14. BART kostet zusätzlich; Clipper kann einen Umstiegsrabatt gewähren. Wheels-Tageskarte für Erwachsene: USD 4.", "السعر يخص Wheels 14 فقط. رحلة BART منفصلة وقد يخفّض Clipper أجرة الانتقال. تذكرة Wheels اليومية للبالغ USD 4.", "Тариф только на Wheels 14. BART оплачивается отдельно; Clipper может дать скидку на пересадку. Дневной билет Wheels для взрослого — USD 4.", "票价仅含Wheels 14路。前往Dublin/Pleasanton的BART车费另付，Clipper可能提供换乘优惠。Wheels成人一日票为USD 4。"]),
 siam: dictionary(["Outbound: 10:00 / 14:00; return: 12:00 / 16:00, as checked. Book through LINE @tripcs or +66 80 924 3300 and reconfirm the chosen return.", "Kontrol edilen seferler: gidiş 10:00 / 14:00, dönüş 12:00 / 16:00. LINE @tripcs veya +66 80 924 3300 üzerinden rezervasyon yapıp dönüşü teyit et.", "Salidas: 10:00 / 14:00; vueltas: 12:00 / 16:00. Reserva en LINE @tripcs o +66 80 924 3300 y confirma la vuelta.", "Départs : 10:00 / 14:00 ; retours : 12:00 / 16:00. Réservez via LINE @tripcs ou +66 80 924 3300 et confirmez le retour.", "Hinfahrt: 10:00 / 14:00; Rückfahrt: 12:00 / 16:00. Buchen Sie über LINE @tripcs oder +66 80 924 3300 und bestätigen Sie die Rückfahrt.", "الذهاب 10:00 / 14:00، والعودة 12:00 / 16:00. احجز عبر LINE @tripcs أو +66 80 924 3300 وأكد وقت العودة.", "Туда: 10:00 / 14:00; обратно: 12:00 / 16:00. Бронируйте через LINE @tripcs или +66 80 924 3300 и подтвердите обратный рейс.", "已核对班次：去程10:00／14:00，返程12:00／16:00。通过LINE @tripcs或+66 80 924 3300预订并确认返程。"]),
 s1: dictionary(["The fare estimate is for S1. S64 is an alternative mentioned by the outlet, with its own fare and timetable; check the operator before choosing it.", "Ücret tahmini S1 içindir. Outletin belirttiği S64 alternatifinin ayrı tarifesi vardır; seçmeden operatörden kontrol et.", "La estimación corresponde a S1. S64 es otra opción citada por el outlet, con tarifa y horario propios.", "L’estimation concerne S1. S64 est une alternative indiquée par l’outlet, avec ses propres tarifs et horaires.", "Die Schätzung gilt für S1. S64 wird als Alternative genannt, hat aber einen eigenen Tarif und Fahrplan.", "التقدير يخص S1. أما S64 فهو بديل مذكور وله أجرة وجدول مستقلان.", "Оценка стоимости относится к S1. У альтернативного S64 свои тариф и расписание.", "估价适用于S1。奥特莱斯另提到S64，其票价及时刻表不同，请向运营方确认。"]),
 mtrTicket: dictionary(["Adult fare range: HKD 24.30 with Octopus/contactless; HKD 28 for a single journey ticket. Use Tung Chung Line, not Airport Express.", "Yetişkin ücret aralığı: Octopus/temassız ödeme ile HKD 24,30; tek kullanımlık bilet HKD 28. Tung Chung hattını kullan; Airport Express bu rota değildir.", "Adulto: HKD 24,30 con Octopus/sin contacto; HKD 28 con billete sencillo. Usa Tung Chung Line, no Airport Express.", "Adulte : HKD 24,30 avec Octopus/sans contact ; HKD 28 en billet simple. Prenez Tung Chung Line, pas Airport Express.", "Erwachsene: HKD 24,30 mit Octopus/kontaktlos, HKD 28 als Einzelticket. Nehmen Sie die Tung Chung Line, nicht Airport Express.", "للبالغ HKD 24.30 ببطاقة Octopus/الدفع اللاتلامسي، أو HKD 28 للتذكرة المفردة. استخدم Tung Chung Line وليس Airport Express.", "Взрослый: HKD 24,30 по Octopus/бесконтактно, HKD 28 за разовый билет. Нужна Tung Chung Line, а не Airport Express.", "成人票价：八达通／非接触支付HKD 24.30，单程票HKD 28。乘东涌线，不要乘机场快线。"]),
 commuter: dictionary(["Use a Commuter train that stops at A9. Express trains skip A9; if already on an Express, change at A8 to a Commuter train heading to A9.", "A9’da duran Commuter trenine bin. Express trenler A9’u atlar; Express’e bindiysen A8’de A9’a giden Commuter trenine aktarma yap.", "Toma un tren Commuter que pare en A9. Los Express no paran; cambia en A8 a un Commuter hacia A9 si es necesario.", "Prenez un train Commuter desservant A9. Les Express ne s’y arrêtent pas ; à A8, changez pour un Commuter vers A9 si nécessaire.", "Nehmen Sie einen Commuter-Zug mit Halt A9. Expresszüge halten dort nicht; steigen Sie gegebenenfalls in A8 in einen Commuter Richtung A9 um.", "اركب قطار Commuter المتوقف في A9. قطارات Express لا تتوقف هناك؛ بدّل في A8 إلى Commuter باتجاه A9 عند الحاجة.", "Нужен поезд Commuter с остановкой A9. Express её пропускает; при необходимости пересаживайтесь на A8 на Commuter в сторону A9.", "乘坐停靠A9的普通车。直达车不停A9；若已乘直达车，请在A8换乘往A9方向的普通车。"]),
 linkouWalk: dictionary(["From A9, allow 5–10 minutes to walk to the outlet; follow signs for the correct building.", "A9’dan outlet için 5–10 dakika yürüyüş payı bırak; ilgili bina tabelalarını takip et.", "Desde A9, calcula 5–10 minutos a pie y sigue las señales del edificio correspondiente.", "Depuis A9, prévoyez 5–10 minutes à pied et suivez les indications du bâtiment souhaité.", "Ab A9 etwa 5–10 Minuten Fußweg; folgen Sie den Schildern zum gewünschten Gebäude.", "خصص 5–10 دقائق للمشي من A9 واتبع لافتات المبنى المطلوب.", "От A9 заложите 5–10 минут пешком; следуйте указателям к нужному корпусу.", "从A9步行约5–10分钟，按指示前往所需馆别。"]),
 budgetTransit: dictionary(["This is a planning budget for the full route, not a guaranteed through fare. Payment method, distance supplements and transfer discounts affect the amount; airport/express tickets can be separate.", "Bu tutar tüm rota için bütçe tahminidir. Ödeme yöntemi, mesafe farkı ve aktarma indirimi tutarı değiştirir; havalimanı/ekspres biletleri ayrıca alınabilir.", "Es un presupuesto orientativo de la ruta completa. El pago, la distancia y los descuentos de transbordo cambian el total; algunos billetes se compran aparte.", "Il s’agit d’un budget indicatif pour tout le trajet. Paiement, distance et réductions de correspondance influent sur le total ; certains billets sont séparés.", "Dies ist ein Planungsbudget für die gesamte Route. Zahlungsart, Entfernungszuschläge und Umstiegsrabatte beeinflussen den Preis; einzelne Tickets können separat nötig sein.", "هذا تقدير لميزانية المسار كاملًا. تتغير التكلفة حسب الدفع والمسافة وخصومات الانتقال؛ وقد تُشترى تذاكر المطار أو السريع منفصلة.", "Это ориентировочный бюджет всего маршрута. Итог зависит от оплаты, расстояния и скидок на пересадки; отдельные билеты могут оплачиваться дополнительно.", "此为全程预算估算。支付方式、里程附加费和换乘优惠会影响总价，机场或高速巴士可能需单独购票。"]),
 awana: dictionary(["Walk from Awana Bus Terminal to the outlet in the same mid-hill complex. A cable-car ticket is not needed for this visit.", "Awana Otobüs Terminali’nden aynı orta yamaç kompleksindeki outlete yürü. Outlet ziyareti için teleferik bileti gerekmez.", "Camina desde Awana hasta el outlet del mismo complejo. No necesitas billete de teleférico.", "Rejoignez à pied l’outlet dans le même complexe qu’Awana. Aucun billet de téléphérique n’est nécessaire.", "Gehen Sie vom Awana Bus Terminal zum Outlet im selben Komplex. Eine Seilbahnfahrkarte ist dafür nicht nötig.", "امشِ من محطة Awana إلى الأوتلت في المجمع نفسه. لا تحتاج إلى تذكرة تلفريك لهذه الزيارة.", "От терминала Awana пройдите к аутлету в том же комплексе. Билет на канатную дорогу не требуется.", "从Awana巴士总站步行前往同一半山综合区内的奥特莱斯，本次购物无需缆车票。"]),
 taxiQuote: dictionary(["Indicative price per vehicle; tolls, waiting and surge pricing may be extra. Obtain a confirmed quote before boarding.", "Araç başına tahmini tutardır; otoyol, bekleme ve yoğunluk farkı eklenebilir. Binmeden toplam fiyatı teyit et.", "Precio orientativo por vehículo; peajes, espera y alta demanda pueden cobrarse aparte. Confirma el total antes de subir.", "Prix indicatif par véhicule ; péages, attente et majorations peuvent s’ajouter. Confirmez le total avant de monter.", "Richtpreis pro Fahrzeug; Maut, Wartezeit und Nachfragezuschläge können hinzukommen. Bestätigen Sie den Gesamtpreis vor Fahrtbeginn.", "سعر تقديري للسيارة؛ قد تضاف رسوم طرق وانتظار وازدحام. أكد السعر الإجمالي قبل الركوب.", "Оценка за машину; платные дороги, ожидание и повышенный спрос могут оплачиваться отдельно. Уточните итог до посадки.", "每车参考价，过路费、等候费及高峰加价可能另计，上车前确认总价。"]),
};
export function expansionDistanceLabel(language: string): string { return words.straight[languages.includes(language as L) ? language as L : "en"]; }
export function expansionGuideCopy(route: ExpansionRoute, language: L): LocalizedGuideCopy {
 const n = (value: number) => new Intl.NumberFormat(language).format(value);
 const range = (a: number, b: number) => a === b ? n(a) : `${n(a)}–${n(b)}`;
 const unit = route.fareUnit === "roundTripFrom" ? words.roundTrip[language] : words[route.fareUnit][language];
 const fare = route.fareMax === 0 ? words.free[language] : [route.fareAccuracy === "estimated" ? words.approx[language] : "", route.fareUnit === "roundTripFrom" ? words.from[language] : "", route.currency, range(route.fareMin, route.fareMax), `(${unit})`].filter(Boolean).join(" ");
 const routeNotes = route.notes.map(key => notes[key]?.[language]).filter((s): s is string => !!s);
 const legs = route.legs.map((leg, i) => (i ? words.transfer[language] : "") + words.board[language].replace("{line}", leg.line).replace("{from}", leg.fromStop).replace("{to}", leg.toStop));
 return {
  title: `${route.legs[0].fromStop} → ${route.legs[route.legs.length - 1].toStop}`,
  estimatedDuration: `${words.approx[language]} ${range(route.durationMin, route.durationMax)} ${words.minutes[language]}`,
  estimatedCost: fare,
  steps: [...legs, words.finish[language], [...routeNotes, words.verify[language]].join(" ")],
  routeNote: [...routeNotes, words.verify[language]].join(" "), officialLinkLabel: words.official[language],
 };
}
export function localizeExpansionGuide(guide: TransportationGuide, language: L): LocalizedGuideCopy | undefined {
 const route = expansionRoutes.find(r => r.guideId === guide.guideId);
 return route ? expansionGuideCopy(route, language) : undefined;
}
const services: Record<string, Record<L, string>> = {
 "Customer Service": dictionary(["Customer Service", "Müşteri Hizmetleri", "Atención al cliente", "Service clientèle", "Kundenservice", "خدمة العملاء", "Служба поддержки", "客户服务"]),
 Dining: dictionary(["Dining", "Yeme İçme", "Restauración", "Restauration", "Gastronomie", "المطاعم", "Рестораны и кафе", "餐饮"]),
 Parking: dictionary(["Parking", "Otopark", "Aparcamiento", "Parking", "Parkplätze", "مواقف السيارات", "Парковка", "停车场"]),
 "Free Wi-Fi": dictionary(["Free Wi-Fi", "Ücretsiz Wi-Fi", "Wi-Fi gratis", "Wi-Fi gratuit", "Kostenloses WLAN", "واي فاي مجاني", "Бесплатный Wi-Fi", "免费Wi-Fi"]),
 "Prayer Room": dictionary(["Prayer Room", "Mescit", "Sala de oración", "Salle de prière", "Gebetsraum", "مصلى", "Молитвенная комната", "祈祷室"]),
 "Nursing Room": dictionary(["Nursing Room", "Bebek Bakım Odası", "Sala de lactancia", "Espace allaitement", "Stillraum", "غرفة الرضاعة", "Комната матери и ребёнка", "母婴室"]),
};
export function expansionQuickInfo(outletId: string, language: L) {
 const m = expansionOutletMetadata[outletId as keyof typeof expansionOutletMetadata];
 if (!m) return undefined;
 return { openingHours: `${m.sundayHours ? `${words.monSat[language]} ${m.hours}; ${words.sunday[language]} ${m.sundayHours}` : `${words.daily[language]} ${m.hours}`}. ${words.holidays[language]}`,
 parking: words.parking[language], services: m.services.map(s => services[s]?.[language] ?? s), storesCountText: `${m.count} ${words.count[language]}`, cityCenterName: localizeExpansionPlace(m.city, language), airportNames: {} as Record<string, string> };
}
