import {
  finalExpansionStoreDirectories,
  type FinalExpansionStoreDirectory,
} from "./finalExpansionStoreDirectories";

// Current official-directory corrections applied after the broad expansion
// snapshot. Keep these explicit so stale/historical tenants cannot silently
// survive merely because a minimum-count validator passes.
const jerseyGardensCurrentRetailStores = [
  "Abercrombie & Fitch Outlet",
  "abercrombie Outlet",
  "adidas Outlet Store",
  "Aerie",
  "Aeropostale",
  "Against All Odds",
  "ALDO Outlet",
  "American Eagle",
  "Ann Taylor Factory",
  "Armani Exchange Outlet",
  "AT&T",
  "Banana Republic Factory Store",
  "Banter by Piercing Pagoda",
  "Bath & Body Works",
  "Big Apple Designs",
  "Birkenstock",
  "Bloomingdale's - The Outlet Store",
  "BOSS Outlet",
  "Brooklyn Industries",
  "Brooks Brothers Factory Store",
  "Burlington",
  "Burlington Shoes",
  "Calvin Klein",
  "Camille La Vie",
  "Canada Weather Gear",
  "Carter's",
  "Champs Sports",
  "Claire's",
  "Clarks",
  "Coach Men's Factory Store",
  "Coach Outlet",
  "Cohen's Fashion Optical",
  "Cohoes",
  "Cole Haan Outlet",
  "Columbia Factory Store",
  "Converse",
  "Crocs",
  "Custom Tees",
  "Diamond Crown",
  "Disney Store Outlet",
  "Express Factory Outlet",
  "Famous Footwear Outlet",
  "Five Below",
  "Foot Locker",
  "Fragrance Outlet",
  "Freedom News",
  "G by GUESS",
  "G-Star RAW",
  "Gabriel Jewelers II",
  "Gap Factory",
  "Garage",
  "Generation Tux",
  "GUESS Accessories",
  "GUESS Factory",
  "H & M",
  "Helzberg",
  "HEYDUDE",
  "Hollister Co. Outlet",
  "Hot Topic",
  "House of K Beauty",
  "Humen",
  "J.Crew Factory",
  "JD",
  "Jewelers on Fifth Jewelry Exchange",
  "Journeys",
  "Journeys Kidz",
  "Karl Lagerfeld Paris",
  "Kate Spade Outlet",
  "Kay Jewelers",
  "Kids Foot Locker",
  "Kipling",
  "La Perfumerie",
  "Laced Up",
  "LACOSTE Outlet",
  "LEGO® Store",
  "Levi's® Outlet Store",
  "Lids",
  "LOFT Outlet",
  "Lovisa",
  "Lucky Brand Outlet",
  "Marc Jacobs",
  "Marshalls",
  "Mavi Jeans",
  "Metro Mart",
  "Michael Kors Mens",
  "Michael Kors Outlet",
  "MINISO",
  "Modern Design",
  "Movado Company Store",
  "Nautica Factory Store",
  "New Balance Factory Store",
  "NIKE Factory Store",
  "Old Navy Outlet",
  "Original Penguin",
  "Oscar's Fine Jewelry",
  "Pandora",
  "Parfum Europa",
  "Perfumania",
  "Perfumes 4U",
  "Perry Ellis",
  "PINK",
  "Polo Ralph Lauren Children",
  "Polo Ralph Lauren Factory Store",
  "Pop Mart",
  "Portabella",
  "Pottery Barn Outlet",
  "Prato Fine Men's Wear",
  "Primark",
  "Psycho Bunny",
  "PUMA Outlet",
  "QL Shop",
  "Reebok Outlet",
  "Royal Jewelry",
  "Runway NY",
  "Samsonite",
  "Scrubs & Beyond",
  "Sephora",
  "Showtime Sneaker Boutique",
  "Skechers",
  "snipes",
  "Spencer's",
  "Stacy Adams Shoes",
  "Steps NY",
  "Steve Madden Outlet",
  "Sunglass Hut",
  "Swarovski",
  "T-Mobile",
  "The Children’s Place Outlet/Gymboree",
  "The Cosmetics Company Store",
  "The Next Exit",
  "The North Face Outlets",
  "Timberland Outlet",
  "Tommy Hilfiger",
  "Tory Burch",
  "True Religion Outlet",
  "TUMI",
  "U.S. Polo Assn.",
  "UGG",
  "Ulta",
  "Under Armour Factory House",
  "Uniqlo",
  "Vans Outlet",
  "Victoria's Secret Outlet",
  "Vineyard Vines",
  "Vitamin World",
  "Watch Express",
  "Windsor",
  "Zales Outlet",
  "Zumiez",
] as const;

const overrides: Record<string, Pick<FinalExpansionStoreDirectory, "storeNames" | "minimumRetailStoreCount" | "checkedAt">> = {
  "the-mills-at-jersey-gardens": {
    storeNames: jerseyGardensCurrentRetailStores,
    minimumRetailStoreCount: 145,
    checkedAt: "2026-09-16",
  },
};

export const effectiveFinalExpansionStoreDirectories: readonly FinalExpansionStoreDirectory[] =
  finalExpansionStoreDirectories.map((directory) => ({
    ...directory,
    ...(overrides[directory.outletId] ?? {}),
  }));
