import type { ExpansionRoute } from "./expansionTransportationDataBase";

export const japanExpansionRoutes: ExpansionRoute[] = [
  {
    guideId: "narita-airport-to-shisui-premium-outlets-direct-bus",
    outletId: "shisui-premium-outlets",
    originType: "airport",
    originId: "narita-international-airport",
    mode: "bus",
    provider: "Narita Airport / Shisui Premium Outlets direct bus",
    legs: [
      {
        line: "Direct bus",
        fromStop: "Narita Airport Terminal 2 1F No.3 / Terminal 1 1F No.30",
        toStop: "Shisui Premium Outlets",
      },
    ],
    durationMin: 15,
    durationMax: 20,
    fareMin: 500,
    fareMax: 500,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Current official Shisui access pages publish the Narita Airport direct bus at JPY 500 one way. The English access overview shows approximately 20 minutes while the Japanese detailed bus page shows approximately 15 minutes, so the planning estimate is 15–20 minutes.",
    sources: ["https://www.premiumoutlets.co.jp/en/shisui/access/"],
    officialProviderUrl: "https://www.premiumoutlets.co.jp/en/shisui/access/",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
  {
    guideId: "tokyo-station-to-shisui-premium-outlets-direct-bus",
    outletId: "shisui-premium-outlets",
    originType: "station",
    originId: "tokyo-station",
    mode: "bus",
    provider: "Direct highway bus",
    legs: [
      {
        line: "Direct highway bus",
        fromStop: "Bus Terminal Tokyo Yaesu No.A02",
        toStop: "Shisui Premium Outlets",
      },
    ],
    durationMin: 50,
    durationMax: 50,
    fareMin: 1300,
    fareMax: 1300,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Official Shisui Premium Outlets access information publishes the Tokyo Station direct bus at JPY 1,300 one way and approximately 50 minutes.",
    sources: ["https://www.premiumoutlets.co.jp/en/shisui/access/"],
    officialProviderUrl: "https://www.premiumoutlets.co.jp/en/shisui/access/",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
  {
    guideId: "sannomiya-to-kobe-sanda-premium-outlets-direct-bus",
    outletId: "kobe-sanda-premium-outlets",
    originType: "city_center",
    originId: "sannomiya-station",
    mode: "bus",
    provider: "Shinki Bus",
    legs: [
      {
        line: "Shinki Bus direct service",
        fromStop: "Shinki Bus Kobe-Sannomiya Bus Terminal",
        toStop: "Kobe-Sanda Premium Outlets",
      },
    ],
    durationMin: 50,
    durationMax: 50,
    fareMin: 700,
    fareMax: 700,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Official Kobe-Sanda Premium Outlets timetable publishes JPY 700 adult one-way fare and approximately 50 minutes from Sannomiya.",
    sources: ["https://www.premiumoutlets.co.jp/en/kobesanda/access/bus_schedule_root2.html"],
    officialProviderUrl: "https://www.premiumoutlets.co.jp/en/kobesanda/access/bus_schedule_root2.html",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
  {
    guideId: "kansai-airport-to-kobe-sanda-premium-outlets-bus",
    outletId: "kobe-sanda-premium-outlets",
    originType: "airport",
    originId: "kansai-international-airport",
    mode: "bus",
    provider: "Kansai Airport Limousine Bus + Shinki Bus",
    legs: [
      {
        line: "Airport Limousine Bus",
        fromStop: "Kansai International Airport",
        toStop: "Kobe Sannomiya",
      },
      {
        line: "Shinki Bus direct service",
        fromStop: "Kobe Sannomiya",
        toStop: "Kobe-Sanda Premium Outlets",
      },
    ],
    durationMin: 120,
    durationMax: 140,
    fareMin: 2900,
    fareMax: 2900,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Combined current adult one-way fares are JPY 2,200 for the Kansai Airport–Kobe Sannomiya airport limousine plus JPY 700 for the Sannomiya–Kobe-Sanda Premium Outlets Shinki Bus, totaling JPY 2,900. The 120–140 minute planning range includes transfer allowance.",
    sources: ["https://www.premiumoutlets.co.jp/en/kobesanda/access/"],
    officialProviderUrl: "https://www.premiumoutlets.co.jp/en/kobesanda/access/",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
  {
    guideId: "tokyo-station-to-sano-premium-outlets-direct-bus",
    outletId: "sano-premium-outlets",
    originType: "station",
    originId: "tokyo-station",
    mode: "bus",
    provider: "JR Bus Kanto Marronnier Tokyo",
    legs: [
      {
        line: "Marronnier Tokyo highway bus + 3 min walk",
        fromStop: "Tokyo Station Yaesu South Exit",
        toStop: "Sano Premium Outlets via Sano Shintoshin Bus Terminal",
      },
    ],
    durationMin: 90,
    durationMax: 95,
    fareMin: 1600,
    fareMax: 1600,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Current official Sano Premium Outlets information publishes the Marronnier Tokyo highway bus at approximately 90 minutes and JPY 1,600 one way per person. Since January 2026, passengers use Sano Shintoshin Bus Terminal, approximately three minutes on foot from the outlet; the upper planning bound includes that walk.",
    sources: ["https://www.premiumoutlets.co.jp/sano/information/info210.html"],
    officialProviderUrl: "https://www.premiumoutlets.co.jp/sano/information/info210.html",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
  {
    guideId: "haneda-airport-to-sano-premium-outlets-direct-bus",
    outletId: "sano-premium-outlets",
    originType: "airport",
    originId: "haneda-airport",
    mode: "bus",
    provider: "Kanto Bus / Tokyo Airport Transportation Marronnier airport bus",
    legs: [
      {
        line: "Marronnier airport bus + 3 min walk",
        fromStop: "Haneda Airport terminal bus stop",
        toStop: "Sano Premium Outlets via Sano Shintoshin Bus Terminal",
      },
    ],
    durationMin: 100,
    durationMax: 145,
    fareMin: 4600,
    fareMax: 4600,
    currency: "JPY",
    fareAccuracy: "exact",
    fareUnit: "oneWay",
    fareBasis: "Current Kanto Bus fare effective July 1, 2026 is JPY 4,600 adult between Haneda Airport and Sano Shintoshin Bus Terminal. Current schedules vary by terminal and service; Sano Premium Outlets summarizes the bus journey as approximately 120 minutes. The 100–145 minute planning range includes terminal/service variation and the final approximately three-minute walk.",
    sources: ["https://www.kantobus.co.jp/airport/maronie02.html"],
    officialProviderUrl: "https://www.kantobus.co.jp/airport/maronie02.html",
    notes: [],
    recommended: true,
    checkedAt: "2026-08-14",
  },
];
