export const outlets = [
  {
    outletId: "la-vallee-village",
    name: "La Vallée Village",
    slug: "la-vallee-village",
    countryId: "france",
    cityId: "paris",
    address: "3 Cours de la Garonne, 77700 Serris, France",
    latitude: 48.8556,
    longitude: 2.7832,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "110+ Stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Personal Shopping",
    ],
    restaurants: [
      "Art Café",
      "Wild & The Moon",
      "Amorino",
      "Ladurée",
      "Momus",
      "Pierre Hermé Paris",
    ],
    taxFreeAvailable: true,
    vatRate: 20,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "100.01 EUR",
    taxFreeOperator: "PABLO / EU customs validation",
    taxFreeOfficeInfo:
      "Eligible non-EU visitors can request a tax refund form in participating boutiques when the purchase exceeds €100.01. Validate the form at customs or a PABLO kiosk when leaving the EU. The estimated refund is usually lower than the full VAT rate because processing fees may apply.",
    cityCenterDistanceKm: 40,
    airportDistanceKm: 35,
    airports: [
      {
        code: "CDG",
        name: "Paris Charles de Gaulle Airport",
        distanceKm: 35,
      },
      {
        code: "ORY",
        name: "Paris Orly Airport",
        distanceKm: 45,
      },
    ],
    cityCenterInfo: {
      name: "Paris City Center",
      distanceKm: 40,
      recommendedRoute: "RER A to Val d'Europe",
    },
    nearby: [
      {
        name: "Disneyland Paris",
        distanceKm: 5,
      },
      {
        name: "Val d'Europe",
        distanceKm: 1,
      },
    ],
    websiteUrl: "https://www.thebicestercollection.com/la-vallee-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=La+Vallee+Village",
    appleMapsUrl: "http://maps.apple.com/?q=La+Vallee+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=La%20Vallee%20Village",
  },
  {
    outletId: "bicester-village",
    name: "Bicester Village",
    slug: "bicester-village",
    countryId: "united-kingdom",
    cityId: "london",
    address: "50 Pingle Drive, Bicester, Oxfordshire OX26 6WD, United Kingdom",
    latitude: 51.8916,
    longitude: -1.1561,
    openingHours: "09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "150+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Guest Services",
      "Restaurants & Cafes",
      "Train Station Nearby",
      "Hands-free Shopping",
      "Personal Shopping",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Tax Free Info",
    ],
    restaurants: [
      "Cecconi's",
      "Ottolenghi",
      "La Tua Pasta",
      "Shan Shui",
      "The Double Red Duke",
      "Ralph's Coffee",
    ],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo:
      "Tourist VAT refunds for goods carried in personal luggage are generally not available for in-store purchases in Great Britain. Check official UK rules and the boutique before planning a tax-free refund.",
    cityCenterDistanceKm: 95,
    airportDistanceKm: 85,
    airports: [
      {
        code: "LHR",
        name: "London Heathrow Airport",
        distanceKm: 85,
      },
      {
        code: "LGW",
        name: "London Gatwick Airport",
        distanceKm: 110,
      },
    ],
    cityCenterInfo: {
      name: "London City Center",
      distanceKm: 95,
      recommendedRoute: "Train from London Marylebone to Bicester Village",
    },
    nearby: [
      {
        name: "Oxford",
        distanceKm: 25,
      },
      {
        name: "Bicester Town Centre",
        distanceKm: 2,
      },
    ],
    websiteUrl: "https://www.thebicestercollection.com/bicester-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Bicester+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Bicester+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Bicester%20Village",
  },
  {
    outletId: "serravalle-designer-outlet",
    name: "Serravalle Designer Outlet",
    slug: "serravalle-designer-outlet",
    countryId: "italy",
    cityId: "milan",
    address: "Via della Moda 1, 15069 Serravalle Scrivia AL, Italy",
    latitude: 44.7359,
    longitude: 8.8367,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "230+ Stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Personal Shopping",
    ],
    restaurants: [
      "Eataly",
      "Obicà",
      "Bonetti",
      "Farinella",
      "La Piadineria",
      "McDonald's",
    ],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo:
      "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the Italian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 95,
    airportDistanceKm: 95,
    airports: [
      {
        code: "LIN",
        name: "Milan Linate Airport",
        distanceKm: 95,
      },
      {
        code: "MXP",
        name: "Milan Malpensa Airport",
        distanceKm: 120,
      },
      {
        code: "GOA",
        name: "Genoa Cristoforo Colombo Airport",
        distanceKm: 55,
      },
    ],
    cityCenterInfo: {
      name: "Milan City Center",
      distanceKm: 95,
      recommendedRoute: "Shuttle or train + bus via Serravalle Scrivia",
    },
    nearby: [
      {
        name: "Genoa",
        distanceKm: 55,
      },
      {
        name: "Novi Ligure",
        distanceKm: 7,
      },
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-serravalle/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Serravalle+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Serravalle+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Serravalle%20Designer%20Outlet",
  },

  {
    outletId: "designer-outlet-parndorf",
    name: "Designer Outlet Parndorf",
    slug: "designer-outlet-parndorf",
    countryId: "austria",
    cityId: "vienna",
    address: "Designer-Outlet-Straße 1, 7111 Parndorf, Austria",
    latitude: 47.9807,
    longitude: 16.8425,
    openingHours: "09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "160+ Stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Personal Shopping",
      "Luggage Drop-off",
    ],
    restaurants: [
      "Vapiano",
      "Starbucks",
      "Nordsee",
      "Burger King",
      "Café Sacher",
      "Dean & David",
    ],
    taxFreeAvailable: true,
    vatRate: 20,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "75.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo:
      "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the Austrian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 45,
    airportDistanceKm: 40,
    airports: [
      {
        code: "VIE",
        name: "Vienna International Airport",
        distanceKm: 40,
      },
      {
        code: "BTS",
        name: "Bratislava Airport",
        distanceKm: 45,
      },
    ],
    cityCenterInfo: {
      name: "Vienna City Center",
      distanceKm: 45,
      recommendedRoute: "Shuttle bus from Vienna / State Opera",
    },
    nearby: [
      {
        name: "Bratislava",
        distanceKm: 35,
      },
      {
        name: "Neusiedl am See",
        distanceKm: 8,
      },
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/at/designer-outlet-parndorf/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Parndorf",
    appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Parndorf",
    yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Parndorf",
  },
  {
    outletId: "fidenza-village",
    name: "Fidenza Village",
    slug: "fidenza-village",
    countryId: "italy",
    cityId: "milan",
    address: "Via San Michele Campagna, 43036 Fidenza PR, Italy",
    latitude: 44.8637,
    longitude: 10.0616,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "120+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Hands-free Shopping",
      "Personal Shopping",
      "VIP Lounge",
    ],
    restaurants: [
      "Ca'puccino",
      "Obicà",
      "Parma Menù",
      "Bistrò Fidenza",
      "Lindt Café",
      "Venchi",
    ],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo:
      "Eligible non-EU visitors can request a tax refund form in participating boutiques when the purchase exceeds the Italian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 110,
    airportDistanceKm: 110,
    airports: [
      {
        code: "LIN",
        name: "Milan Linate Airport",
        distanceKm: 110,
      },
      {
        code: "MXP",
        name: "Milan Malpensa Airport",
        distanceKm: 150,
      },
      {
        code: "BLQ",
        name: "Bologna Guglielmo Marconi Airport",
        distanceKm: 115,
      },
    ],
    cityCenterInfo: {
      name: "Milan City Center",
      distanceKm: 110,
      recommendedRoute: "Train to Fidenza + local transfer",
    },
    nearby: [
      {
        name: "Parma",
        distanceKm: 30,
      },
      {
        name: "Bologna",
        distanceKm: 115,
      },
    ],
    websiteUrl: "https://www.thebicestercollection.com/fidenza-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Fidenza+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Fidenza+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Fidenza%20Village",
  },
{
    outletId: "ingolstadt-village",
    name: "Ingolstadt Village",
    slug: "ingolstadt-village",
    countryId: "germany",
    cityId: "munich",
    address: "Otto-Hahn-Straße 1, 85055 Ingolstadt, Germany",
    latitude: 48.7832,
    longitude: 11.4699,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "110+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shopping Express", "Wi-Fi", "Gift Cards", "Accessibility", "Hands-free Shopping", "Personal Shopping"],
    restaurants: ["Ladurée Salon de Thé", "Bollicine&Co. Champagne Bar", "Mancini", "Mr. Smash & Co.", "Indochine", "Coffee Fellows"],
    taxFreeAvailable: true,
    vatRate: 19,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "50.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating boutiques when the purchase exceeds the German minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 80,
    airportDistanceKm: 75,
    airports: [{ code: "MUC", name: "Munich Airport", distanceKm: 75 }, { code: "NUE", name: "Nuremberg Airport", distanceKm: 95 }],
    cityCenterInfo: { name: "Munich City Center", distanceKm: 80, recommendedRoute: "Shopping Express or train via Ingolstadt Hbf" },
    nearby: [{ name: "Ingolstadt City Center", distanceKm: 6 }, { name: "Audi Forum Ingolstadt", distanceKm: 8 }],
    websiteUrl: "https://www.thebicestercollection.com/ingolstadt-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Ingolstadt+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Ingolstadt+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Ingolstadt%20Village",
  },
  {
    outletId: "wertheim-village",
    name: "Wertheim Village",
    slug: "wertheim-village",
    countryId: "germany",
    cityId: "frankfurt",
    address: "Almosenberg, 97877 Wertheim, Germany",
    latitude: 49.7582,
    longitude: 9.5115,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "110+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shopping Express", "Wi-Fi", "Gift Cards", "Accessibility", "Hands-free Shopping", "Personal Shopping", "VIP Parking"],
    restaurants: ["The Coffee Corner", "Elaine's TakeAway", "Mon Amour", "La Piazza", "Lindt Café", "Gardens Café"],
    taxFreeAvailable: true,
    vatRate: 19,
    estimatedRefundRate: 11,
    minimumTaxFreeSpend: "50.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating boutiques when the purchase exceeds the German minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 80,
    airportDistanceKm: 90,
    airports: [{ code: "FRA", name: "Frankfurt Airport", distanceKm: 90 }, { code: "NUE", name: "Nuremberg Airport", distanceKm: 125 }],
    cityCenterInfo: { name: "Frankfurt City Center", distanceKm: 80, recommendedRoute: "Shopping Express or train + local transfer via Wertheim" },
    nearby: [{ name: "Wertheim Town Center", distanceKm: 8 }, { name: "Frankfurt", distanceKm: 80 }],
    websiteUrl: "https://www.thebicestercollection.com/wertheim-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Wertheim+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Wertheim+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Wertheim%20Village",
  },
{
    outletId: "the-mall-firenze",
    name: "The Mall Firenze",
    slug: "the-mall-firenze",
    countryId: "italy",
    cityId: "florence",
    address: "Via Europa 8, 50066 Leccio Reggello FI, Italy",
    latitude: 43.6936,
    longitude: 11.4656,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "40+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Direct Bus", "Wi-Fi", "Gift Cards", "Accessibility", "Personal Shopping", "VIP Services"],
    restaurants: ["Gucci Caffè", "ToscaNino", "Bistro", "Caffè La Corte", "Food Lounge", "Gelateria"],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating boutiques when the purchase exceeds the Italian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 35,
    airportDistanceKm: 45,
    airports: [
      { code: "FLR", name: "Florence Airport", distanceKm: 45 },
      { code: "PSA", name: "Pisa International Airport", distanceKm: 120 },
      { code: "BLQ", name: "Bologna Airport", distanceKm: 125 },
    ],
    cityCenterInfo: { name: "Florence City Center", distanceKm: 35, recommendedRoute: "Direct bus or car via A1" },
    nearby: [{ name: "Reggello", distanceKm: 8 }, { name: "Florence", distanceKm: 35 }],
    websiteUrl: "https://firenze.themall.it/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=The+Mall+Firenze",
    appleMapsUrl: "http://maps.apple.com/?q=The+Mall+Firenze",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Mall%20Firenze",
  },
  {
    outletId: "barberino",
    name: "Barberino Designer Outlet",
    slug: "barberino",
    countryId: "italy",
    cityId: "florence",
    address: "Via Meucci, 50031 Barberino di Mugello FI, Italy",
    latitude: 44.0069,
    longitude: 11.2141,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "130+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shuttle / Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
    restaurants: ["Antica Focacceria San Francesco", "La Piadineria", "Lindt", "Poke House", "McDonald's", "Caffè"],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the Italian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 30,
    airports: [
      { code: "FLR", name: "Florence Airport", distanceKm: 30 },
      { code: "BLQ", name: "Bologna Airport", distanceKm: 75 },
      { code: "PSA", name: "Pisa International Airport", distanceKm: 105 },
    ],
    cityCenterInfo: { name: "Florence City Center", distanceKm: 30, recommendedRoute: "Shuttle or car via A1" },
    nearby: [{ name: "Barberino di Mugello", distanceKm: 4 }, { name: "Florence", distanceKm: 30 }],
    websiteUrl: "https://www.barberinooutlet.com/en/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Barberino+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Barberino+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Barberino%20Designer%20Outlet",
  },
  {
    outletId: "noventa",
    name: "Noventa di Piave Designer Outlet",
    slug: "noventa",
    countryId: "italy",
    cityId: "venice",
    address: "Via Marco Polo 1, 30020 Noventa di Piave VE, Italy",
    latitude: 45.6734,
    longitude: 12.5446,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "170+ Stores",
    rating: 4.6,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shuttle / Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
    restaurants: ["Sutto Caffè", "Signorvino", "Venchi", "Baccalà Divino", "McDonald's", "Poke House"],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "EU customs validation / tax refund operators",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the Italian minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
    cityCenterDistanceKm: 45,
    airportDistanceKm: 30,
    airports: [
      { code: "VCE", name: "Venice Marco Polo Airport", distanceKm: 30 },
      { code: "TSF", name: "Treviso Airport", distanceKm: 35 },
      { code: "VRN", name: "Verona Airport", distanceKm: 145 },
    ],
    cityCenterInfo: { name: "Venice City Center", distanceKm: 45, recommendedRoute: "Shuttle, bus, or car via A4" },
    nearby: [{ name: "Noventa di Piave", distanceKm: 2 }, { name: "Venice", distanceKm: 45 }],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-noventa-di-piave/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Noventa+di+Piave+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Noventa+di+Piave+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Noventa%20di%20Piave%20Designer%20Outlet",
  },

  {
outletId: "outletcity-metzingen",
name: "Outletcity Metzingen",
slug: "outletcity-metzingen",
countryId: "germany",
cityId: "stuttgart",
address: "Hugo-Boss-Platz 4, 72555 Metzingen, Germany",
latitude: 48.5359,
longitude: 9.2812,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "130+ Stores",
rating: 4.6,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shopping Shuttle", "Wi-Fi", "Gift Cards", "Accessibility", "Tax Free Counter", "Personal Shopping"],
restaurants: ["L'Osteria", "Marché Mövenpick", "Starbucks", "Amorino", "Frittenwerk", "Brauwerk"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "Global Blue / Planet / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax-free shopping form in participating stores. Outletcity Metzingen has a Tax Free Counter in the Welcome Centre where eligible forms and receipts can be checked before customs validation when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
cityCenterDistanceKm: 35,
airportDistanceKm: 25,
airports: [
{ code: "STR", name: "Stuttgart Airport", distanceKm: 25 },
{ code: "FRA", name: "Frankfurt Airport", distanceKm: 215 },
{ code: "MUC", name: "Munich Airport", distanceKm: 220 },
],
cityCenterInfo: { name: "Stuttgart City Center", distanceKm: 35, recommendedRoute: "Shopping Shuttle, train via Metzingen, or car via B27/B312" },
nearby: [{ name: "Metzingen Town Center", distanceKm: 1 }, { name: "Stuttgart", distanceKm: 35 }],
websiteUrl: "https://www.outletcity.com/en/metzingen/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Outletcity+Metzingen",
appleMapsUrl: "http://maps.apple.com/?q=Outletcity+Metzingen",
yandexMapsUrl: "https://yandex.com/maps/?text=Outletcity%20Metzingen",
},

{
outletId: "designer-outlet-troyes",
name: "Designer Outlet Troyes",
slug: "designer-outlet-troyes",
countryId: "france",
cityId: "paris",
address: "Voie du Bois, 10150 Pont-Sainte-Marie, France",
latitude: 48.3126,
longitude: 4.0941,
openingHours: "10:00 - 19:00",
heroImage: "",
galleryImages: [],
storesCountText: "110+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Columbus Café", "La Croissanterie", "Il Ristorante", "Maison Caffet", "McDonald's", "Paul"],
taxFreeAvailable: true,
vatRate: 20,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "100.01 EUR",
taxFreeOperator: "EU customs validation / tax refund operators",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the French minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
cityCenterDistanceKm: 170,
airportDistanceKm: 165,
airports: [
{ code: "ORY", name: "Paris Orly Airport", distanceKm: 165 },
{ code: "CDG", name: "Paris Charles de Gaulle Airport", distanceKm: 180 },
],
cityCenterInfo: { name: "Paris City Center", distanceKm: 170, recommendedRoute: "Train to Troyes + local bus or taxi" },
nearby: [{ name: "Troyes City Center", distanceKm: 5 }, { name: "Reims", distanceKm: 125 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/fr/designer-outlet-troyes/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Troyes",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Troyes",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Troyes",
},

{
outletId: "designer-outlet-provence",
name: "Designer Outlet Provence",
slug: "designer-outlet-provence",
countryId: "france",
cityId: "marseille",
address: "McArthurGlen Provence - Village de Marques, Mas de la Péronne, 13140 Miramas, France",
latitude: 43.5808,
longitude: 5.0068,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "110+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Starbucks", "Columbus Café", "Maison Caffet", "La Croissanterie", "McDonald's", "Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 20,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "100.01 EUR",
taxFreeOperator: "EU customs validation / tax refund operators",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund when spending at least €100.01 in participating stores on the same day. The refund can be processed through the Guest Services desk and validated when leaving the EU.",
cityCenterDistanceKm: 55,
airportDistanceKm: 35,
airports: [
{ code: "MRS", name: "Marseille Provence Airport", distanceKm: 35 },
{ code: "AVN", name: "Avignon Provence Airport", distanceKm: 55 },
],
cityCenterInfo: { name: "Marseille City Center", distanceKm: 55, recommendedRoute: "Car, train via Miramas, or regional bus" },
nearby: [{ name: "Miramas", distanceKm: 5 }, { name: "Aix-en-Provence", distanceKm: 45 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/fr/designer-outlet-provence/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Provence+Miramas",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Provence+Miramas",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Provence%20Miramas",
},
{
outletId: "designer-outlet-roermond",
name: "Designer Outlet Roermond",
slug: "designer-outlet-roermond",
countryId: "netherlands",
cityId: "amsterdam",
address: "Stadsweide 2, 6041 TD Roermond, Netherlands",
latitude: 51.1994,
longitude: 5.9883,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "200+ Stores",
rating: 4.6,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Starbucks", "La Place", "McDonald's", "Wagamama", "The Burger Federation", "Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 21,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "50.00 EUR",
taxFreeOperator: "Global Blue / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €50 in the same store on the same day. Guest Services can assist with tax-free information before customs validation when leaving the EU.",
cityCenterDistanceKm: 180,
airportDistanceKm: 60,
airports: [
{ code: "EIN", name: "Eindhoven Airport", distanceKm: 60 },
{ code: "DUS", name: "Düsseldorf Airport", distanceKm: 65 },
{ code: "AMS", name: "Amsterdam Schiphol Airport", distanceKm: 180 },
],
cityCenterInfo: { name: "Amsterdam City Center", distanceKm: 180, recommendedRoute: "Train to Roermond, then walk 10-15 minutes" },
nearby: [{ name: "Roermond City Center", distanceKm: 1 }, { name: "Düsseldorf", distanceKm: 65 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/nl/designer-outlet-roermond/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Roermond",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Roermond",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Roermond",
},
{
outletId: "castel-romano",
name: "Castel Romano Designer Outlet",
slug: "castel-romano",
countryId: "italy",
cityId: "rome",
address: "Via Ponte di Piscina Cupa 64, 00128 Castel Romano, Roma, Italy",
latitude: 41.7169,
longitude: 12.4446,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "150+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shuttle / Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
restaurants: ["Obicà", "Wagamama", "Lindt", "McDonald's", "Farinella", "Caffè"],
taxFreeAvailable: true,
vatRate: 22,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "70.01 EUR",
taxFreeOperator: "Forexchange / Global Blue / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €70.01 in the same store on the same day. Castel Romano has an onsite Forexchange Tax Refund Office where eligible visitors can receive assistance before customs validation when leaving the EU.",
cityCenterDistanceKm: 25,
airportDistanceKm: 25,
airports: [
{ code: "FCO", name: "Rome Fiumicino Airport", distanceKm: 25 },
{ code: "CIA", name: "Rome Ciampino Airport", distanceKm: 25 },
],
cityCenterInfo: { name: "Rome City Center", distanceKm: 25, recommendedRoute: "Shuttle bus from Rome Termini or car via Via Pontina" },
nearby: [{ name: "Rome EUR", distanceKm: 18 }, { name: "Pomezia", distanceKm: 10 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-castel-romano/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Castel+Romano+Designer+Outlet",
appleMapsUrl: "http://maps.apple.com/?q=Castel+Romano+Designer+Outlet",
yandexMapsUrl: "https://yandex.com/maps/?text=Castel%20Romano%20Designer%20Outlet",
},
{
outletId: "cheshire-oaks",
name: "Cheshire Oaks Designer Outlet",
slug: "cheshire-oaks",
countryId: "united-kingdom",
cityId: "liverpool",
address: "Kinsey Road, Ellesmere Port, Cheshire CH65 9JJ, United Kingdom",
latitude: 53.2654,
longitude: -2.8842,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "140+ Stores",
rating: 4.6,
reviewCount: 0,
services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
restaurants: ["Wagamama", "Comptoir Libanais", "YO! Sushi", "Starbucks", "Joe & The Juice", "GAIL's Bakery"],
taxFreeAvailable: false,
vatRate: 20,
estimatedRefundRate: 0,
minimumTaxFreeSpend: "Not available",
taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Visitors should check official UK rules and individual stores before planning any tax-free shopping.",
cityCenterDistanceKm: 25,
airportDistanceKm: 40,
airports: [
{ code: "LPL", name: "Liverpool John Lennon Airport", distanceKm: 40 },
{ code: "MAN", name: "Manchester Airport", distanceKm: 55 },
],
cityCenterInfo: { name: "Liverpool City Center", distanceKm: 25, recommendedRoute: "Train to Ellesmere Port or bus via Chester / Liverpool" },
nearby: [{ name: "Chester", distanceKm: 12 }, { name: "Ellesmere Port", distanceKm: 3 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-cheshire-oaks/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Cheshire+Oaks+Designer+Outlet",
appleMapsUrl: "http://maps.apple.com/?q=Cheshire+Oaks+Designer+Outlet",
yandexMapsUrl: "https://yandex.com/maps/?text=Cheshire%20Oaks%20Designer%20Outlet",
},
{
outletId: "designer-outlet-berlin",
name: "Designer Outlet Berlin",
slug: "designer-outlet-berlin",
countryId: "germany",
cityId: "berlin",
address: "Alter Spandauer Weg 1, 14641 Wustermark, Germany",
latitude: 52.5478,
longitude: 12.9942,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "100+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shuttle / Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Five Guys", "Starbucks", "Lindt", "Nordsee", "Dean & David", "Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "EU customs validation / tax refund operators",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the German minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
cityCenterDistanceKm: 30,
airportDistanceKm: 55,
airports: [
{ code: "BER", name: "Berlin Brandenburg Airport", distanceKm: 55 },
],
cityCenterInfo: { name: "Berlin City Center", distanceKm: 30, recommendedRoute: "Shuttle bus, regional train, or car via B5" },
nearby: [{ name: "Wustermark", distanceKm: 5 }, { name: "Potsdam", distanceKm: 30 }],
websiteUrl: "https://www.designeroutletberlin.com/en/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Berlin",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Berlin",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Berlin",
},
{
outletId: "designer-outlet-neumunster",
name: "Designer Outlet Neumünster",
slug: "designer-outlet-neumunster",
countryId: "germany",
cityId: "hamburg",
address: "Oderstraße 10, 24539 Neumünster, Germany",
latitude: 54.1031,
longitude: 9.9966,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "130+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Starbucks", "Nordsee", "Lindt", "Dean & David", "Restaurant & Café", "Caffè"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "EU customs validation / tax refund operators",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when the purchase exceeds the German minimum spend. Validate the form when leaving the EU. Estimated refunds are usually lower than the full VAT rate because operator fees may apply.",
cityCenterDistanceKm: 65,
airportDistanceKm: 60,
airports: [
{ code: "HAM", name: "Hamburg Airport", distanceKm: 60 },
],
cityCenterInfo: { name: "Hamburg City Center", distanceKm: 65, recommendedRoute: "Train to Neumünster, then local bus or taxi" },
nearby: [{ name: "Neumünster City Center", distanceKm: 5 }, { name: "Kiel", distanceKm: 35 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/de/designer-outlet-neumuenster/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Neumunster",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Neumunster",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Neumunster",
},
{
outletId: "designer-outlet-roosendaal",
name: "Designer Outlet Roosendaal",
slug: "designer-outlet-roosendaal",
countryId: "netherlands",
cityId: "rotterdam",
address: "Rosada 70, 4703 TB Roosendaal, Netherlands",
latitude: 51.5365,
longitude: 4.4777,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "100+ Stores",
rating: 4.4,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "Kids Area", "Personal Shopping"],
restaurants: ["Starbucks", "La Place", "McDonald's", "Restaurant & Café", "Caffè", "Snack Bar"],
taxFreeAvailable: true,
vatRate: 21,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "50.00 EUR",
taxFreeOperator: "Global Blue / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €50 in the same store on the same day. Validate the form when leaving the EU.",
cityCenterDistanceKm: 65,
airportDistanceKm: 65,
airports: [
{ code: "RTM", name: "Rotterdam The Hague Airport", distanceKm: 65 },
{ code: "AMS", name: "Amsterdam Schiphol Airport", distanceKm: 115 },
{ code: "BRU", name: "Brussels Airport", distanceKm: 105 },
],
cityCenterInfo: { name: "Rotterdam City Center", distanceKm: 65, recommendedRoute: "Train to Roosendaal, then local bus or taxi" },
nearby: [{ name: "Roosendaal City Center", distanceKm: 3 }, { name: "Antwerp", distanceKm: 45 }],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/nl/designer-outlet-roosendaal/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Roosendaal",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Roosendaal",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Roosendaal",
},
{
outletId: "la-reggia",
name: "La Reggia Designer Outlet",
slug: "la-reggia",
countryId: "italy",
cityId: "naples",
address: "S.S. Sannitica 87, 81025 Marcianise (CE), Italy",
latitude: 41.0286,
longitude: 14.3092,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "140+ Stores",
rating: 4.6,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Shuttle / Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
restaurants: ["Rossopomodoro", "McDonald's", "Lindt", "Caffè Vergnano", "Spicchio Pizza", "La Piadineria"],
taxFreeAvailable: true,
vatRate: 22,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "70.01 EUR",
taxFreeOperator: "Forexchange / Global Blue / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €70.01 in the same store on the same day. Tax refund services are available at the outlet before customs validation when leaving the EU.",
cityCenterDistanceKm: 30,
airportDistanceKm: 20,
airports: [
{ code: "NAP", name: "Naples International Airport", distanceKm: 20 }
],
cityCenterInfo: {
name: "Naples City Center",
distanceKm: 30,
recommendedRoute: "Shuttle bus or car via A1"
},
nearby: [
{ name: "Caserta", distanceKm: 10 },
{ name: "Naples", distanceKm: 30 }
],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-la-reggia/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=La+Reggia+Designer+Outlet",
appleMapsUrl: "http://maps.apple.com/?q=La+Reggia+Designer+Outlet",
yandexMapsUrl: "https://yandex.com/maps/?text=La%20Reggia%20Designer%20Outlet",
},
{
outletId: "designer-outlet-malaga",
name: "McArthurGlen Designer Outlet Málaga",
slug: "designer-outlet-malaga",
countryId: "spain",
cityId: "malaga",
address: "Calle Alfonso Ponce de León 3, 29004 Málaga, Spain",
latitude: 36.6738,
longitude: -4.4899,
openingHours: "10:00 - 22:00",
heroImage: "",
galleryImages: [],
storesCountText: "100+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking", "Tax Free", "Guest Services", "Restaurants & Cafes", "Transport Info", "Wi-Fi", "Gift Cards", "Accessibility", "ATM", "Kids Area", "Personal Shopping"],
restaurants: ["Starbucks", "Five Guys", "Gusto", "Lindt", "Dunkin'", "Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 21,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "90.16 EUR",
taxFreeOperator: "Global Blue / Planet / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form when purchases exceed the Spanish minimum spend. Tax-free assistance is available at Guest Services before customs validation when leaving the EU.",
cityCenterDistanceKm: 8,
airportDistanceKm: 3,
airports: [
{ code: "AGP", name: "Málaga-Costa del Sol Airport", distanceKm: 3 }
],
cityCenterInfo: {
name: "Málaga City Center",
distanceKm: 8,
recommendedRoute: "Train, bus or taxi"
},
nearby: [
{ name: "Málaga Airport", distanceKm: 3 },
{ name: "Torremolinos", distanceKm: 6 }
],
websiteUrl: "https://www.mcarthurglen.com/en/outlets/es/designer-outlet-malaga/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=McArthurGlen+Designer+Outlet+Malaga",
appleMapsUrl: "http://maps.apple.com/?q=McArthurGlen+Designer+Outlet+Malaga",
yandexMapsUrl: "https://yandex.com/maps/?text=McArthurGlen%20Designer%20Outlet%20Malaga",
},
{
outletId: "montabaur-the-style-outlets",
name: "Montabaur The Style Outlets",
slug: "montabaur-the-style-outlets",
countryId: "germany",
cityId: "frankfurt",
address: "Am Fashion Outlet 72, 56410 Montabaur, Germany",
latitude: 50.4307,
longitude: 7.8238,
openingHours: "10:00 - 20:00",
heroImage: "",
galleryImages: [],
storesCountText: "70+ Stores",
rating: 4.4,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Transport Info","Wi-Fi","Gift Cards","Accessibility","Kids Area"],
restaurants: ["Starbucks","Dean & David","Lindt","Restaurant & Café","BackWerk","Coffee Bar"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "Global Blue / Planet / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form when purchases exceed the German minimum spend.",
cityCenterDistanceKm: 90,
airportDistanceKm: 95,
airports: [
{ code: "FRA", name: "Frankfurt Airport", distanceKm: 95 },
{ code: "CGN", name: "Cologne Bonn Airport", distanceKm: 100 }
],
cityCenterInfo: {
name: "Frankfurt City Center",
distanceKm: 90,
recommendedRoute: "ICE to Montabaur + taxi"
},
nearby: [
{ name: "Montabaur", distanceKm: 2 },
{ name: "Koblenz", distanceKm: 25 }
],
websiteUrl: "https://www.montabaurthestyleoutlets.com/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Montabaur+The+Style+Outlets",
appleMapsUrl: "http://maps.apple.com/?q=Montabaur+The+Style+Outlets",
yandexMapsUrl: "https://yandex.com/maps/?text=Montabaur%20The%20Style%20Outlets",
},

{
outletId: "zweibrucken-fashion-outlet",
name: "Zweibrücken Fashion Outlet",
slug: "zweibrucken-fashion-outlet",
countryId: "germany",
cityId: "frankfurt",
address: "Londoner Bogen 10-90, 66482 Zweibrücken, Germany",
latitude: 49.2522,
longitude: 7.3698,
openingHours: "10:00 - 19:00",
heroImage: "",
galleryImages: [],
storesCountText: "120+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Transport Info","Wi-Fi","Gift Cards","Accessibility","Kids Area","Personal Shopping"],
restaurants: ["Starbucks","Pizza Hut","Nordsee","Lindt","Restaurant & Café","Coffee Bar"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "Global Blue / Planet / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form when purchases exceed the German minimum spend.",
cityCenterDistanceKm: 140,
airportDistanceKm: 35,
airports: [
{ code: "SCN", name: "Saarbrücken Airport", distanceKm: 35 },
{ code: "FRA", name: "Frankfurt Airport", distanceKm: 140 }
],
cityCenterInfo: {
name: "Frankfurt City Center",
distanceKm: 140,
recommendedRoute: "Train + regional transfer"
},
nearby: [
{ name: "Zweibrücken", distanceKm: 2 },
{ name: "Saarbrücken", distanceKm: 35 }
],
websiteUrl: "https://www.fashion-outlet-zweibruecken.com/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Zweibrucken+Fashion+Outlet",
appleMapsUrl: "http://maps.apple.com/?q=Zweibrucken+Fashion+Outlet",
yandexMapsUrl: "https://yandex.com/maps/?text=Zweibrucken%20Fashion%20Outlet",
},
{
outletId: "maasmechelen-village",
name: "Maasmechelen Village",
slug: "maasmechelen-village",
countryId: "belgium",
cityId: "brussels",
address: "Zetellaan 100, 3630 Maasmechelen, Belgium",
latitude: 50.9862,
longitude: 5.6995,
openingHours: "10:00 - 19:00",
heroImage: "",
galleryImages: [],
storesCountText: "100+ Boutiques",
rating: 4.6,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Shuttle / Transport Info","Wi-Fi","Gift Cards","Accessibility","Personal Shopping","Hands-free Shopping"],
restaurants: ["Le Petit Belge","Ellis Gourmet Burger","Starbucks","Liu Jo Café","Neuhaus","Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 21,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "125.00 EUR",
taxFreeOperator: "Global Blue / Planet",
taxFreeOfficeInfo: "Eligible non-EU visitors may request tax-free documentation in participating boutiques and validate documents before leaving the EU.",
cityCenterDistanceKm: 95,
airportDistanceKm: 95,
airports: [
{ code: "BRU", name: "Brussels Airport", distanceKm: 95 },
{ code: "MST", name: "Maastricht Aachen Airport", distanceKm: 20 }
],
cityCenterInfo: {
name: "Brussels City Center",
distanceKm: 95,
recommendedRoute: "Shopping Express or car"
},
nearby: [
{ name: "Maastricht", distanceKm: 20 },
{ name: "Genk", distanceKm: 18 }
],
websiteUrl: "https://www.thebicestercollection.com/maasmechelen-village/en",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Maasmechelen+Village",
appleMapsUrl: "http://maps.apple.com/?q=Maasmechelen+Village",
yandexMapsUrl: "https://yandex.com/maps/?text=Maasmechelen%20Village",
},

{
outletId: "las-rozas-village",
name: "Las Rozas Village",
slug: "las-rozas-village",
countryId: "spain",
cityId: "madrid",
address: "Calle Juan Ramón Jiménez 3, 28232 Las Rozas, Madrid, Spain",
latitude: 40.5037,
longitude: -3.8968,
openingHours: "10:00 - 21:00",
heroImage: "",
galleryImages: [],
storesCountText: "100+ Boutiques",
rating: 4.6,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Transport Info","Wi-Fi","Gift Cards","Accessibility","Hands-free Shopping","Personal Shopping"],
restaurants: ["Cristina Oria","Starbucks","Joselito's","Ham! Fresh Burger","Lindt","Restaurant & Café"],
taxFreeAvailable: true,
vatRate: 21,
estimatedRefundRate: 12,
minimumTaxFreeSpend: "90.16 EUR",
taxFreeOperator: "Global Blue / Planet",
taxFreeOfficeInfo: "Eligible non-EU visitors may request tax-free forms when purchases exceed the Spanish minimum threshold.",
cityCenterDistanceKm: 25,
airportDistanceKm: 35,
airports: [
{ code: "MAD", name: "Madrid-Barajas Airport", distanceKm: 35 }
],
cityCenterInfo: {
name: "Madrid City Center",
distanceKm: 25,
recommendedRoute: "Bus, taxi or car"
},
nearby: [
{ name: "Las Rozas", distanceKm: 2 },
{ name: "Madrid", distanceKm: 25 }
],
websiteUrl: "https://www.thebicestercollection.com/las-rozas-village/en",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Las+Rozas+Village",
appleMapsUrl: "http://maps.apple.com/?q=Las+Rozas+Village",
yandexMapsUrl: "https://yandex.com/maps/?text=Las%20Rozas%20Village",
},
{
outletId: "city-outlet-bad-munstereifel",
name: "City Outlet Bad Münstereifel",
slug: "city-outlet-bad-munstereifel",
countryId: "germany",
cityId: "cologne",
address: "Orchheimer Straße 1, 53902 Bad Münstereifel, Germany",
latitude: 50.5557,
longitude: 6.7646,
openingHours: "10:00 - 19:00",
heroImage: "",
galleryImages: [],
storesCountText: "40+ Stores",
rating: 4.4,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Transport Info","Wi-Fi","Gift Cards","Accessibility"],
restaurants: ["Café","Restaurant & Café","Bakery","Ice Cream","Coffee Bar","Snack Bar"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "Global Blue / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request tax-free forms in participating stores with Global Blue tax-free shopping signs.",
cityCenterDistanceKm: 65,
airportDistanceKm: 80,
airports: [
{ code: "CGN", name: "Cologne Bonn Airport", distanceKm: 80 },
{ code: "DUS", name: "Düsseldorf Airport", distanceKm: 115 }
],
cityCenterInfo: {
name: "Cologne City Center",
distanceKm: 65,
recommendedRoute: "Train to Bad Münstereifel via Euskirchen"
},
nearby: [
{ name: "Euskirchen", distanceKm: 20 },
{ name: "Bonn", distanceKm: 45 }
],
websiteUrl: "https://www.cityoutletbadmuenstereifel.com/en/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=City+Outlet+Bad+Munstereifel",
appleMapsUrl: "http://maps.apple.com/?q=City+Outlet+Bad+Munstereifel",
yandexMapsUrl: "https://yandex.com/maps/?text=City%20Outlet%20Bad%20Munstereifel",
},
{
outletId: "designer-outlets-wolfsburg",
name: "Designer Outlets Wolfsburg",
slug: "designer-outlets-wolfsburg",
countryId: "germany",
cityId: "hannover",
address: "An der Vorburg 1, 38440 Wolfsburg, Germany",
latitude: 52.4294,
longitude: 10.7936,
openingHours: "10:00 - 19:00",
heroImage: "",
galleryImages: [],
storesCountText: "90+ Stores",
rating: 4.5,
reviewCount: 0,
services: ["Parking","Tax Free","Guest Services","Restaurants & Cafes","Transport Info","Wi-Fi","Gift Cards","Accessibility","Kids Area"],
restaurants: ["Starbucks","Dean & David","Nordsee","Lindt","Restaurant & Café","Coffee Bar"],
taxFreeAvailable: true,
vatRate: 19,
estimatedRefundRate: 11,
minimumTaxFreeSpend: "50.01 EUR",
taxFreeOperator: "Global Blue / Planet / EU customs validation",
taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when purchases exceed the German minimum spend.",
cityCenterDistanceKm: 90,
airportDistanceKm: 95,
airports: [
{ code: "HAJ", name: "Hannover Airport", distanceKm: 95 },
{ code: "BER", name: "Berlin Brandenburg Airport", distanceKm: 230 }
],
cityCenterInfo: {
name: "Hannover City Center",
distanceKm: 90,
recommendedRoute: "Train to Wolfsburg Hbf, then walk 2 minutes"
},
nearby: [
{ name: "Wolfsburg Hauptbahnhof", distanceKm: 1 },
{ name: "Autostadt Wolfsburg", distanceKm: 1 }
],
websiteUrl: "https://www.designeroutlets-wolfsburg.de/en/",
status: "active",
googleMapsUrl: "https://maps.google.com/?q=Designer+Outlets+Wolfsburg",
appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlets+Wolfsburg",
yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlets%20Wolfsburg",
},
];