import type { TransportationGuide } from "./transportationGuides";

/** Player-facing locales configured by src/translations/locale.ts. */
export const targetContentLanguages = ["en", "tr", "es", "fr", "de", "ar", "ru", "zh"] as const;
export type TargetContentLanguage = (typeof targetContentLanguages)[number];

type QuickInfo = { openingHours: string; parking: string; services: string[]; storesCountText: string; cityCenterName: string; airportNames: Record<string, string> };
type OutletCopy = Record<TargetContentLanguage, QuickInfo>;

const serviceNames: Record<TargetContentLanguage, Record<string, string>> = {
  en: {},
  tr: { "Customer Service":"Müşteri Hizmetleri", Dining:"Yeme İçme", Parking:"Otopark", "Waterfront Promenade":"Sahil Yürüyüş Yolu", ATM:"ATM", "Free Wi-Fi":"Ücretsiz Wi-Fi", "Prayer Room":"Mescit", Lockers:"Dolaplar", "Information Center":"Danışma", "Tax-Free Shopping":"Tax Free Alışveriş", "Currency Exchange":"Döviz Bürosu", "Free Shuttle Bus":"Ücretsiz Servis", "Nursing Room":"Bebek Bakım Odası", "Wheelchair Rental":"Tekerlekli Sandalye Kiralama", "Stroller Rental":"Bebek Arabası Kiralama" },
  de: { "Customer Service":"Kundenservice", Dining:"Gastronomie", Parking:"Parkplätze", "Waterfront Promenade":"Uferpromenade", ATM:"Geldautomat", "Free Wi-Fi":"Kostenloses WLAN", "Prayer Room":"Gebetsraum", Lockers:"Schließfächer", "Information Center":"Information", "Tax-Free Shopping":"Tax-Free-Einkauf", "Currency Exchange":"Geldwechsel", "Free Shuttle Bus":"Kostenloser Shuttlebus", "Nursing Room":"Stillraum", "Wheelchair Rental":"Rollstuhlverleih", "Stroller Rental":"Kinderwagenverleih" },
  fr: { "Customer Service":"Service clientèle", Dining:"Restauration", Parking:"Parking", "Waterfront Promenade":"Promenade du front de mer", ATM:"Distributeur", "Free Wi-Fi":"Wi-Fi gratuit", "Prayer Room":"Salle de prière", Lockers:"Casiers", "Information Center":"Point d’information", "Tax-Free Shopping":"Achats détaxés", "Currency Exchange":"Bureau de change", "Free Shuttle Bus":"Navette gratuite", "Nursing Room":"Espace allaitement", "Wheelchair Rental":"Prêt de fauteuil roulant", "Stroller Rental":"Prêt de poussette" },
  es: { "Customer Service":"Atención al cliente", Dining:"Restauración", Parking:"Aparcamiento", "Waterfront Promenade":"Paseo marítimo", ATM:"Cajero automático", "Free Wi-Fi":"Wi-Fi gratis", "Prayer Room":"Sala de oración", Lockers:"Taquillas", "Information Center":"Información", "Tax-Free Shopping":"Compras libres de impuestos", "Currency Exchange":"Cambio de divisas", "Free Shuttle Bus":"Lanzadera gratuita", "Nursing Room":"Sala de lactancia", "Wheelchair Rental":"Préstamo de sillas de ruedas", "Stroller Rental":"Préstamo de cochecitos" },
  ar: { "Customer Service":"خدمة العملاء", Dining:"المطاعم", Parking:"مواقف السيارات", "Waterfront Promenade":"ممشى الواجهة البحرية", ATM:"جهاز صراف آلي", "Free Wi-Fi":"واي فاي مجاني", "Prayer Room":"مصلى", Lockers:"خزائن الأمتعة", "Information Center":"مركز المعلومات", "Tax-Free Shopping":"التسوق المعفى من الضرائب", "Currency Exchange":"صرافة العملات", "Free Shuttle Bus":"حافلة نقل مجانية", "Nursing Room":"غرفة الرضاعة", "Wheelchair Rental":"استعارة كرسي متحرك", "Stroller Rental":"استعارة عربة أطفال" },
  ru: { "Customer Service":"Служба поддержки", Dining:"Рестораны и кафе", Parking:"Парковка", "Waterfront Promenade":"Набережная", ATM:"Банкомат", "Free Wi-Fi":"Бесплатный Wi‑Fi", "Prayer Room":"Молитвенная комната", Lockers:"Камеры хранения", "Information Center":"Информационный центр", "Tax-Free Shopping":"Покупки Tax Free", "Currency Exchange":"Обмен валюты", "Free Shuttle Bus":"Бесплатный шаттл", "Nursing Room":"Комната матери и ребёнка", "Wheelchair Rental":"Прокат инвалидных колясок", "Stroller Rental":"Прокат детских колясок" },
  zh: { "Customer Service":"客户服务", Dining:"餐饮", Parking:"停车场", "Waterfront Promenade":"滨水步道", ATM:"自动取款机", "Free Wi-Fi":"免费 Wi-Fi", "Prayer Room":"祈祷室", Lockers:"储物柜", "Information Center":"服务中心", "Tax-Free Shopping":"免税购物", "Currency Exchange":"外币兑换", "Free Shuttle Bus":"免费接驳巴士", "Nursing Room":"母婴室", "Wheelchair Rental":"轮椅租借", "Stroller Rental":"婴儿车租借" },
};
const extendedServiceKeys = ["Baby Care Room", "Baby Changing Room", "Baby Carts", "Car Wash", "Customer Services", "Dedicated Toilets", "First Aid Room", "Gift Vouchers", "Internet Cafes", "Lost & Found Property", "Lost Child Assistance", "Luggage Storage", "Mall Directory", "Mobile Charging Stations", "Money Exchange", "Outlet Plus Card", "Photo Studio", "Valet Parking", "Wheelchair", "Lost & Found", "Welcome Center", "Telephone Interpreting", "Taxi", "Baby Changing", "First Aid / AED", "Barrier-Free Access", "Delivery Service", "EV Charging", "Pet-Friendly Areas", "Smoking Areas", "General Information", "Tourist Information", "Tax-Free Counter", "Foreign Currency Exchange", "Free Coin Lockers", "Free Baggage Storage", "AED", "Accessible Toilets", "Pet-Friendly Facilities"] as const;
const extendedServiceValues: Record<Exclude<TargetContentLanguage, "en">, readonly string[]> = {
 tr: ["Bebek Bakım Odası", "Bebek Alt Değiştirme Odası", "Bebek Arabaları", "Oto Yıkama", "Müşteri Hizmetleri", "Özel Tuvaletler", "İlk Yardım Odası", "Hediye Çekleri", "İnternet Kafeler", "Kayıp Eşya", "Kayıp Çocuk Yardımı", "Bagaj Muhafazası", "AVM Rehberi", "Mobil Şarj İstasyonları", "Döviz Bürosu", "Outlet Plus Kartı", "Fotoğraf Stüdyosu", "Vale Otopark", "Tekerlekli Sandalye", "Kayıp Eşya", "Karşılama Merkezi", "Telefonla Tercüme", "Taksi", "Bebek Alt Değiştirme", "İlk Yardım / AED", "Engelsiz Erişim", "Teslimat Hizmeti", "Elektrikli Araç Şarjı", "Evcil Hayvan Dostu Alanlar", "Sigara İçme Alanları", "Genel Danışma", "Turist Danışma", "Tax Free Bankosu", "Döviz Bürosu", "Ücretsiz Jetonlu Dolaplar", "Ücretsiz Bagaj Muhafazası", "AED", "Erişilebilir Tuvaletler", "Evcil Hayvan Dostu Olanaklar"],
 es: ["Sala de cuidado del bebé", "Sala para cambiar bebés", "Carritos para bebés", "Lavado de coches", "Atención al cliente", "Aseos exclusivos", "Sala de primeros auxilios", "Vales regalo", "Cibercafés", "Objetos perdidos", "Asistencia para niños perdidos", "Consigna de equipaje", "Directorio del centro", "Estaciones de carga para móviles", "Cambio de divisas", "Tarjeta Outlet Plus", "Estudio fotográfico", "Aparcacoches", "Silla de ruedas", "Objetos perdidos", "Centro de bienvenida", "Interpretación telefónica", "Taxi", "Cambiador para bebés", "Primeros auxilios / DEA", "Acceso sin barreras", "Servicio de entrega", "Carga de vehículos eléctricos", "Zonas para mascotas", "Zonas para fumadores", "Información general", "Información turística", "Mostrador Tax Free", "Cambio de moneda extranjera", "Taquillas gratuitas con moneda", "Consigna de equipaje gratuita", "DEA", "Aseos accesibles", "Instalaciones para mascotas"],
 fr: ["Espace bébé", "Espace à langer", "Poussettes pour bébés", "Lavage automobile", "Service clientèle", "Toilettes dédiées", "Salle de premiers secours", "Chèques-cadeaux", "Cybercafés", "Objets trouvés", "Aide aux enfants perdus", "Consigne à bagages", "Plan du centre", "Bornes de recharge mobile", "Bureau de change", "Carte Outlet Plus", "Studio photo", "Voiturier", "Fauteuil roulant", "Objets trouvés", "Centre d’accueil", "Interprétation téléphonique", "Taxi", "Table à langer", "Premiers secours / DAE", "Accès sans obstacles", "Service de livraison", "Recharge pour véhicules électriques", "Espaces acceptant les animaux", "Espaces fumeurs", "Information générale", "Information touristique", "Comptoir Tax Free", "Change de devises", "Casiers gratuits à pièces", "Consigne à bagages gratuite", "DAE", "Toilettes accessibles", "Équipements acceptant les animaux"],
 de: ["Babyraum", "Wickelraum", "Babywagen", "Autowäsche", "Kundenservice", "Separate Toiletten", "Erste-Hilfe-Raum", "Geschenkgutscheine", "Internetcafés", "Fundbüro", "Hilfe für vermisste Kinder", "Gepäckaufbewahrung", "Center-Verzeichnis", "Ladestationen für Mobilgeräte", "Geldwechsel", "Outlet Plus Card", "Fotostudio", "Valet-Parken", "Rollstuhl", "Fundbüro", "Welcome Center", "Telefondolmetschen", "Taxi", "Wickelmöglichkeit", "Erste Hilfe / AED", "Barrierefreier Zugang", "Lieferservice", "E-Auto-Ladestationen", "Haustierfreundliche Bereiche", "Raucherbereiche", "Allgemeine Information", "Touristeninformation", "Tax-Free-Schalter", "Fremdwährungswechsel", "Kostenlose Münzschließfächer", "Kostenlose Gepäckaufbewahrung", "AED", "Barrierefreie Toiletten", "Haustierfreundliche Einrichtungen"],
 ar: ["غرفة رعاية الأطفال", "غرفة تغيير ملابس الأطفال", "عربات أطفال", "غسيل السيارات", "خدمة العملاء", "دورات مياه مخصصة", "غرفة إسعافات أولية", "قسائم هدايا", "مقاهي إنترنت", "المفقودات", "مساعدة الأطفال المفقودين", "حفظ الأمتعة", "دليل المركز", "محطات شحن الهواتف", "صرافة العملات", "بطاقة أوتلت بلس", "استوديو تصوير", "خدمة صف السيارات", "كرسي متحرك", "المفقودات", "مركز الترحيب", "ترجمة عبر الهاتف", "سيارة أجرة", "تغيير ملابس الأطفال", "إسعافات أولية / جهاز AED", "وصول بلا عوائق", "خدمة توصيل", "شحن المركبات الكهربائية", "مناطق صديقة للحيوانات", "مناطق تدخين", "معلومات عامة", "معلومات سياحية", "كاونتر الإعفاء الضريبي", "صرف العملات الأجنبية", "خزائن مجانية تعمل بالعملة", "حفظ أمتعة مجاني", "جهاز AED", "دورات مياه ميسّرة", "مرافق صديقة للحيوانات"],
 ru: ["Комната ухода за ребёнком", "Комната для пеленания", "Детские коляски", "Автомойка", "Служба поддержки", "Специальные туалеты", "Пункт первой помощи", "Подарочные сертификаты", "Интернет-кафе", "Бюро находок", "Помощь потерявшимся детям", "Камера хранения багажа", "Схема центра", "Станции зарядки телефонов", "Обмен валюты", "Карта Outlet Plus", "Фотостудия", "Парковка с парковщиком", "Инвалидная коляска", "Бюро находок", "Центр приветствия", "Перевод по телефону", "Такси", "Пеленальный столик", "Первая помощь / AED", "Безбарьерный доступ", "Доставка", "Зарядка электромобилей", "Зоны для посетителей с животными", "Места для курения", "Общая информация", "Туристическая информация", "Стойка Tax Free", "Обмен иностранной валюты", "Бесплатные монетные шкафчики", "Бесплатная камера хранения", "AED", "Доступные туалеты", "Удобства для посетителей с животными"],
 zh: ["婴儿护理室", "婴儿更衣室", "婴儿车", "洗车服务", "客户服务", "专用卫生间", "急救室", "礼品券", "网吧", "失物招领", "走失儿童协助", "行李寄存", "商场导览", "手机充电站", "货币兑换", "Outlet Plus 卡", "照相馆", "代客泊车", "轮椅", "失物招领", "迎宾中心", "电话翻译", "出租车", "婴儿更衣设施", "急救 / AED", "无障碍通行", "配送服务", "电动汽车充电", "宠物友好区域", "吸烟区", "综合咨询", "旅游咨询", "退税柜台", "外币兑换", "免费投币储物柜", "免费行李寄存", "AED", "无障碍卫生间", "宠物友好设施"],
};
for (const language of targetContentLanguages) {
 if (language === "en") continue;
 Object.assign(serviceNames[language], Object.fromEntries(extendedServiceKeys.map((key,index)=>[key,extendedServiceValues[language][index]])));
}
const translateServices = (language: TargetContentLanguage, values: string[]) => values.map((value) => serviceNames[language][value] ?? value);

const schedules: Record<TargetContentLanguage, [string,string,string]> = {
 en:["Sun–Wed 10:00–22:00; Thu–Sat 10:00–23:00.","Sun–Thu 10:00–22:00; Fri–Sat 10:00–00:00.","Mon–Thu 10:00–22:00; Fri–Sun 10:00–23:00."],
 tr:["Paz–Çar 10:00–22:00; Per–Cmt 10:00–23:00.","Paz–Per 10:00–22:00; Cum–Cmt 10:00–00:00.","Pzt–Per 10:00–22:00; Cum–Paz 10:00–23:00."],
 es:["Dom–mié 10:00–22:00; jue–sáb 10:00–23:00.","Dom–jue 10:00–22:00; vie–sáb 10:00–00:00.","Lun–jue 10:00–22:00; vie–dom 10:00–23:00."],
 fr:["Dim–mer 10:00–22:00 ; jeu–sam 10:00–23:00.","Dim–jeu 10:00–22:00 ; ven–sam 10:00–00:00.","Lun–jeu 10:00–22:00 ; ven–dim 10:00–23:00."],
 de:["So–Mi 10:00–22:00; Do–Sa 10:00–23:00.","So–Do 10:00–22:00; Fr–Sa 10:00–00:00.","Mo–Do 10:00–22:00; Fr–So 10:00–23:00."],
 ar:["الأحد–الأربعاء 10:00–22:00؛ الخميس–السبت 10:00–23:00.","الأحد–الخميس 10:00–22:00؛ الجمعة–السبت 10:00–00:00.","الاثنين–الخميس 10:00–22:00؛ الجمعة–الأحد 10:00–23:00."],
 ru:["Вс–ср 10:00–22:00; чт–сб 10:00–23:00.","Вс–чт 10:00–22:00; пт–сб 10:00–00:00.","Пн–чт 10:00–22:00; пт–вс 10:00–23:00."],
 zh:["周日至周三 10:00–22:00；周四至周六 10:00–23:00。","周日至周四 10:00–22:00；周五至周六 10:00–00:00。","周一至周四 10:00–22:00；周五至周日 10:00–23:00。"],
};

const japanHours:Record<TargetContentLanguage,[string,string,string]>={
 en:["Shops 10:00–20:00; restaurants 11:00–21:00; café 09:30–20:00.","Mar–Nov 10:00–20:00; Dec–Feb 10:00–19:00.","Shops 10:00–20:00; restaurants 11:00–21:00; food court 10:30–21:00; café 09:30–21:00."],
 tr:["Mağazalar 10:00–20:00; restoranlar 11:00–21:00; kafe 09:30–20:00.","Mart–Kasım 10:00–20:00; Aralık–Şubat 10:00–19:00.","Mağazalar 10:00–20:00; restoranlar 11:00–21:00; yemek alanı 10:30–21:00; kafe 09:30–21:00."],
 de:["Geschäfte 10:00–20:00; Restaurants 11:00–21:00; Café 09:30–20:00.","März–Nov. 10:00–20:00; Dez.–Feb. 10:00–19:00.","Geschäfte 10:00–20:00; Restaurants 11:00–21:00; Foodcourt 10:30–21:00; Café 09:30–21:00."],
 fr:["Boutiques 10:00–20:00 ; restaurants 11:00–21:00 ; café 09:30–20:00.","Mars–nov. 10:00–20:00 ; déc.–fév. 10:00–19:00.","Boutiques 10:00–20:00 ; restaurants 11:00–21:00 ; aire de restauration 10:30–21:00 ; café 09:30–21:00."],
 es:["Tiendas 10:00–20:00; restaurantes 11:00–21:00; cafetería 09:30–20:00.","Marzo–nov. 10:00–20:00; dic.–feb. 10:00–19:00.","Tiendas 10:00–20:00; restaurantes 11:00–21:00; zona de comidas 10:30–21:00; cafetería 09:30–21:00."],
 ar:["المتاجر 10:00–20:00؛ المطاعم 11:00–21:00؛ المقهى 09:30–20:00.","مارس–نوفمبر 10:00–20:00؛ ديسمبر–فبراير 10:00–19:00.","المتاجر 10:00–20:00؛ المطاعم 11:00–21:00؛ ردهة الطعام 10:30–21:00؛ المقهى 09:30–21:00."],
 ru:["Магазины 10:00–20:00; рестораны 11:00–21:00; кафе 09:30–20:00.","Март–ноябрь 10:00–20:00; декабрь–февраль 10:00–19:00.","Магазины 10:00–20:00; рестораны 11:00–21:00; фуд-корт 10:30–21:00; кафе 09:30–21:00."],
 zh:["商店 10:00–20:00；餐厅 11:00–21:00；咖啡店 09:30–20:00。","3月至11月 10:00–20:00；12月至2月 10:00–19:00。","商店 10:00–20:00；餐厅 11:00–21:00；美食广场 10:30–21:00；咖啡店 09:30–21:00。"]
};
const openingCaveats: Record<TargetContentLanguage, [string,string,string,string,string,string]> = {
 en:["Tenant hours commonly published for the mall are Sun–Wed 10:00–22:00 and Thu–Sat 10:00–23:00; mall-wide and holiday hours may vary.","Sun–Thu 10:00–22:00; Fri–Sat 10:00–00:00. Ramadan and festive-season hours may vary; use the official mall schedule for current hours.","Mon–Thu 10:00–22:00; Fri–Sun 10:00–23:00. Public-holiday and seasonal hours may vary; use the official destination schedule for current hours.","Shops 10:00–20:00; restaurants 11:00–21:00; café 09:30–20:00. Individual-store, seasonal and special-date hours may vary.","Mar–Nov 10:00–20:00; Dec–Feb 10:00–19:00. Closed once yearly; the next scheduled closure is February 25, 2027. Seasonal and special hours may vary.","Shops 10:00–20:00; restaurants 11:00–21:00; food court 10:30–21:00; café 09:30–21:00. Closure days are not fixed; individual-shop and special-date hours may vary."],
 tr:["Yaygın olarak yayımlanan kiracı saatleri Paz–Çar 10:00–22:00 ve Per–Cmt 10:00–23:00’dır; genel alışveriş merkezi ve tatil saatleri değişebilir.","Paz–Per 10:00–22:00; Cum–Cmt 10:00–00:00. Ramazan ve bayram dönemi saatleri değişebilir; güncel saatler için alışveriş merkezinin resmî programını kullanın.","Pzt–Per 10:00–22:00; Cum–Paz 10:00–23:00. Resmî tatil ve sezon saatleri değişebilir; güncel saatler için tesisin resmî programını kullanın.","Mağazalar 10:00–20:00; restoranlar 11:00–21:00; kafe 09:30–20:00. Mağaza, sezon ve özel gün saatleri değişebilir.","Mart–Kasım 10:00–20:00; Aralık–Şubat 10:00–19:00. Yılda bir kez kapalıdır; sıradaki planlı kapanış 25 Şubat 2027’dir. Sezon ve özel gün saatleri değişebilir.","Mağazalar 10:00–20:00; restoranlar 11:00–21:00; yemek alanı 10:30–21:00; kafe 09:30–21:00. Sabit kapanış günü yoktur; mağaza ve özel gün saatleri değişebilir."],
 es:["El horario habitual publicado de los locales es dom.–mié. 10:00–22:00 y jue.–sáb. 10:00–23:00; el horario general y de festivos puede variar.","Dom.–jue. 10:00–22:00; vie.–sáb. 10:00–00:00. El horario de Ramadán y festividades puede variar; consulte el horario oficial del centro.","Lun.–jue. 10:00–22:00; vie.–dom. 10:00–23:00. El horario de festivos y temporada puede variar; consulte el horario oficial del destino.","Tiendas 10:00–20:00; restaurantes 11:00–21:00; cafetería 09:30–20:00. Los horarios por tienda, temporada y fechas especiales pueden variar.","Marzo–noviembre 10:00–20:00; diciembre–febrero 10:00–19:00. Cierra una vez al año; el próximo cierre programado es el 25 de febrero de 2027. Los horarios especiales y de temporada pueden variar.","Tiendas 10:00–20:00; restaurantes 11:00–21:00; zona de comidas 10:30–21:00; cafetería 09:30–21:00. No hay día de cierre fijo; los horarios de tiendas y fechas especiales pueden variar."],
 fr:["Les horaires habituellement publiés des enseignes sont dim.–mer. 10:00–22:00 et jeu.–sam. 10:00–23:00 ; les horaires généraux et fériés peuvent varier.","Dim.–jeu. 10:00–22:00 ; ven.–sam. 10:00–00:00. Les horaires du Ramadan et des fêtes peuvent varier ; consultez le programme officiel du centre.","Lun.–jeu. 10:00–22:00 ; ven.–dim. 10:00–23:00. Les horaires saisonniers et jours fériés peuvent varier ; consultez le programme officiel de la destination.","Boutiques 10:00–20:00 ; restaurants 11:00–21:00 ; café 09:30–20:00. Les horaires par boutique, saison et dates spéciales peuvent varier.","Mars–novembre 10:00–20:00 ; décembre–février 10:00–19:00. Fermé une fois par an ; la prochaine fermeture prévue est le 25 février 2027. Les horaires saisonniers et spéciaux peuvent varier.","Boutiques 10:00–20:00 ; restaurants 11:00–21:00 ; aire de restauration 10:30–21:00 ; café 09:30–21:00. Aucun jour de fermeture fixe ; les horaires des boutiques et dates spéciales peuvent varier."],
 de:["Die üblicherweise veröffentlichten Mieterzeiten sind So–Mi 10:00–22:00 und Do–Sa 10:00–23:00; allgemeine und Feiertagsöffnungszeiten können abweichen.","So–Do 10:00–22:00; Fr–Sa 10:00–00:00. Öffnungszeiten während Ramadan und Festzeiten können abweichen; nutzen Sie den offiziellen Center-Zeitplan.","Mo–Do 10:00–22:00; Fr–So 10:00–23:00. Feiertags- und Saisonzeiten können abweichen; nutzen Sie den offiziellen Zeitplan des Ziels.","Geschäfte 10:00–20:00; Restaurants 11:00–21:00; Café 09:30–20:00. Zeiten einzelner Geschäfte sowie Saison- und Sonderzeiten können abweichen.","März–November 10:00–20:00; Dezember–Februar 10:00–19:00. Einmal jährlich geschlossen; die nächste geplante Schließung ist am 25. Februar 2027. Saison- und Sonderzeiten können abweichen.","Geschäfte 10:00–20:00; Restaurants 11:00–21:00; Foodcourt 10:30–21:00; Café 09:30–21:00. Kein fester Schließtag; Geschäfts- und Sonderzeiten können abweichen."],
 ar:["ساعات المستأجرين المنشورة عادةً: الأحد–الأربعاء 10:00–22:00 والخميس–السبت 10:00–23:00؛ وقد تختلف ساعات المركز والعطلات.","الأحد–الخميس 10:00–22:00؛ الجمعة–السبت 10:00–00:00. قد تختلف ساعات رمضان والمواسم الاحتفالية؛ استخدم جدول المركز الرسمي للساعات الحالية.","الاثنين–الخميس 10:00–22:00؛ الجمعة–الأحد 10:00–23:00. قد تختلف ساعات العطلات والمواسم؛ استخدم الجدول الرسمي للوجهة.","المتاجر 10:00–20:00؛ المطاعم 11:00–21:00؛ المقهى 09:30–20:00. قد تختلف ساعات المتاجر والمواسم والتواريخ الخاصة.","مارس–نوفمبر 10:00–20:00؛ ديسمبر–فبراير 10:00–19:00. يغلق مرة سنويًا؛ الإغلاق المجدول التالي في 25 فبراير 2027. قد تختلف الساعات الموسمية والخاصة.","المتاجر 10:00–20:00؛ المطاعم 11:00–21:00؛ ردهة الطعام 10:30–21:00؛ المقهى 09:30–21:00. لا يوجد يوم إغلاق ثابت؛ قد تختلف ساعات المتاجر والتواريخ الخاصة."],
 ru:["Обычно публикуемые часы арендаторов: вс–ср 10:00–22:00 и чт–сб 10:00–23:00; общие часы центра и праздников могут меняться.","Вс–чт 10:00–22:00; пт–сб 10:00–00:00. Часы в Рамадан и праздничные периоды могут меняться; используйте официальный график центра.","Пн–чт 10:00–22:00; пт–вс 10:00–23:00. Праздничные и сезонные часы могут меняться; используйте официальный график комплекса.","Магазины 10:00–20:00; рестораны 11:00–21:00; кафе 09:30–20:00. Часы отдельных магазинов, сезонные и особые даты могут отличаться.","Март–ноябрь 10:00–20:00; декабрь–февраль 10:00–19:00. Закрыт один раз в год; следующее плановое закрытие — 25 февраля 2027 года. Сезонные и особые часы могут меняться.","Магазины 10:00–20:00; рестораны 11:00–21:00; фуд-корт 10:30–21:00; кафе 09:30–21:00. Фиксированного дня закрытия нет; часы магазинов и особых дат могут меняться."],
 zh:["商户通常公布的营业时间为周日至周三 10:00–22:00、周四至周六 10:00–23:00；商场整体及节假日时间可能调整。","周日至周四 10:00–22:00；周五至周六 10:00–00:00。斋月及节庆期间时间可能调整；请使用商场官方营业时间表。","周一至周四 10:00–22:00；周五至周日 10:00–23:00。公共假日及季节性时间可能调整；请使用目的地官方时间表。","商店 10:00–20:00；餐厅 11:00–21:00；咖啡店 09:30–20:00。各店、季节及特殊日期营业时间可能不同。","3月至11月 10:00–20:00；12月至2月 10:00–19:00。每年闭馆一次；下次计划闭馆日期为2027年2月25日。季节及特殊时间可能调整。","商店 10:00–20:00；餐厅 11:00–21:00；美食广场 10:30–21:00；咖啡店 09:30–21:00。无固定闭馆日；各店及特殊日期营业时间可能不同。"],
};
const targetServices: Record<string,string[]> = {
 "al-khiran-hybrid-outlet-mall":["Customer Service","Dining","Parking","Waterfront Promenade"],
 "dubai-outlet-mall":["ATM","Baby Care Room","Baby Changing Room","Baby Carts","Car Wash","Customer Services","Dedicated Toilets","First Aid Room","Free Wi-Fi","Gift Vouchers","Internet Cafes","Lost & Found Property","Lost Child Assistance","Luggage Storage","Mall Directory","Mobile Charging Stations","Money Exchange","Outlet Plus Card","Parking","Photo Studio","Prayer Room","Valet Parking","Wheelchair"],
 "the-outlet-village":["ATM","Baby Changing Room","Customer Service","Free Wi-Fi","Lost & Found","Parking","Prayer Room","Valet Parking","Wheelchair"],
 "rinku-premium-outlets":["Information Center","Tax-Free Shopping","Free Wi-Fi","ATM","Lockers","Prayer Room","Nursing Room","Stroller Rental","Wheelchair Rental","Parking"],
 "gotemba-premium-outlets":["Information Center","Welcome Center","Tax-Free Shopping","Free Wi-Fi","ATM","Currency Exchange","Lockers","Prayer Room","Telephone Interpreting","Free Shuttle Bus","Taxi","Nursing Room","Baby Changing","First Aid / AED","Stroller Rental","Wheelchair Rental","Barrier-Free Access","Delivery Service","Parking","EV Charging","Pet-Friendly Areas","Smoking Areas"],
 "mitsui-outlet-park-kisarazu":["General Information","Tourist Information","Tax-Free Counter","Free Wi-Fi","Foreign Currency Exchange","ATM","Free Coin Lockers","Free Baggage Storage","Delivery Service","AED","Wheelchair Rental","Accessible Toilets","Stroller Rental","Nursing Room","Baby Changing","Prayer Room","Parking","Valet Parking","EV Charging","Smoking Areas","Pet-Friendly Facilities"],
};
const quickText: Record<TargetContentLanguage,{parking:string; stores:string}> = {
 en:{parking:"On-site parking is available.",stores:"stores"},tr:{parking:"Tesis bünyesinde otopark mevcuttur.",stores:"mağaza"},de:{parking:"Parkplätze sind vor Ort verfügbar.",stores:"Geschäfte"},fr:{parking:"Un parking est disponible sur place.",stores:"boutiques"},es:{parking:"Hay aparcamiento en el recinto.",stores:"tiendas"},ar:{parking:"تتوفر مواقف للسيارات في الموقع.",stores:"متجرًا"},ru:{parking:"На территории есть парковка.",stores:"магазинов"},zh:{parking:"设有场内停车场。",stores:"家门店"}
};
const counts:Record<string,number>={"al-khiran-hybrid-outlet-mall":284,"dubai-outlet-mall":340,"the-outlet-village":100,"rinku-premium-outlets":213,"gotemba-premium-outlets":290,"mitsui-outlet-park-kisarazu":330};
const airportNames: Record<TargetContentLanguage, Record<string, string>> = {
 en:{KWI:"Kuwait International Airport",DXB:"Dubai International Airport",DWC:"Al Maktoum International Airport",KIX:"Kansai International Airport",HND:"Haneda Airport",NRT:"Narita International Airport"},
 tr:{KWI:"Kuveyt Uluslararası Havalimanı",DXB:"Dubai Uluslararası Havalimanı",DWC:"Al Maktoum Uluslararası Havalimanı",KIX:"Kansai Uluslararası Havalimanı",HND:"Haneda Havalimanı",NRT:"Narita Uluslararası Havalimanı"},
 es:{KWI:"Aeropuerto Internacional de Kuwait",DXB:"Aeropuerto Internacional de Dubái",DWC:"Aeropuerto Internacional Al Maktoum",KIX:"Aeropuerto Internacional de Kansai",HND:"Aeropuerto de Haneda",NRT:"Aeropuerto Internacional de Narita"},
 fr:{KWI:"Aéroport international de Koweït",DXB:"Aéroport international de Dubaï",DWC:"Aéroport international Al Maktoum",KIX:"Aéroport international du Kansai",HND:"Aéroport de Haneda",NRT:"Aéroport international de Narita"},
 de:{KWI:"Internationaler Flughafen Kuwait",DXB:"Internationaler Flughafen Dubai",DWC:"Internationaler Flughafen Al Maktoum",KIX:"Internationaler Flughafen Kansai",HND:"Flughafen Haneda",NRT:"Internationaler Flughafen Narita"},
 ar:{KWI:"مطار الكويت الدولي",DXB:"مطار دبي الدولي",DWC:"مطار آل مكتوم الدولي",KIX:"مطار كانساي الدولي",HND:"مطار هانيدا",NRT:"مطار ناريتا الدولي"},
 ru:{KWI:"Международный аэропорт Кувейт",DXB:"Международный аэропорт Дубай",DWC:"Международный аэропорт Аль-Мактум",KIX:"Международный аэропорт Кансай",HND:"Аэропорт Ханэда",NRT:"Международный аэропорт Нарита"},
 zh:{KWI:"科威特国际机场",DXB:"迪拜国际机场",DWC:"阿勒马克图姆国际机场",KIX:"关西国际机场",HND:"羽田机场",NRT:"成田国际机场"},
};
const outletOrder=Object.keys(targetServices);
export const targetOutletQuickInfo: Record<string, OutletCopy> = Object.fromEntries(outletOrder.map((id,index)=>[id,Object.fromEntries(targetContentLanguages.map(language=>[language,{openingHours:openingCaveats[language][index],parking:quickText[language].parking,services:translateServices(language,targetServices[id]),storesCountText:id==="the-outlet-village"?"100+ stores":`${counts[id]} stores`,cityCenterName:id==="al-khiran-hybrid-outlet-mall"?"Kuwait City / Kuwait Towers":id.includes("dubai")||id==="the-outlet-village"?"Downtown Dubai / Burj Khalifa":id.startsWith("rinku")?"Rinku Town Station":id.startsWith("gotemba")?"JR Gotemba Station":"JR Kisarazu Station",airportNames:airportNames[language]}]))])) as unknown as Record<string,OutletCopy>;

export type LocalizedGuideCopy={title:string;estimatedDuration:string;estimatedCost:string;steps:string[];routeNote?:string;officialLinkLabel?:string};
type Route={title:string;start:string;service:string;end:string;walk:string};
const routes:Record<string,Route>={
 "al-ghubaiba-to-dubai-outlet-mall-rta-bus-66":{title:"Dubai Outlet Mall",start:"Al Ghubaiba Bus Station",service:"RTA Bus 66 toward Faqa, Terminus",end:"Dubai Outlet Mall 01",walk:"Dubai Outlet Mall entrance"},
 "downtown-dubai-to-dubai-outlet-mall-taxi":{title:"Dubai Outlet Mall",start:"Downtown Dubai",service:"licensed taxi",end:"Dubai Outlet Mall taxi drop-off",walk:"Dubai Outlet Mall entrance"},
 "dxb-to-dubai-outlet-mall-taxi":{title:"Dubai Outlet Mall",start:"DXB {{officialTaxiRank}}",service:"metered airport taxi",end:"Dubai Outlet Mall taxi drop-off",walk:"Dubai Outlet Mall entrance"},
 "downtown-dubai-to-the-outlet-village-taxi":{title:"The Outlet Village",start:"Downtown Dubai",service:"licensed taxi",end:"The Outlet Village {{taxiDropOff}}",walk:"The Outlet Village entrance"}, "dxb-to-the-outlet-village-taxi":{title:"The Outlet Village",start:"DXB {{officialTaxiRank}}",service:"metered airport taxi",end:"The Outlet Village {{taxiDropOff}}",walk:"The Outlet Village entrance"}, "dwc-to-the-outlet-village-taxi":{title:"The Outlet Village",start:"DWC {{officialTaxiRank}}",service:"metered airport taxi",end:"The Outlet Village {{taxiDropOff}}",walk:"The Outlet Village entrance"},
 "kuwait-city-to-al-khiran-hybrid-outlet-mall-taxi":{title:"Al Khiran Hybrid Outlet Mall",start:"Kuwait City",service:"licensed taxi or ride-hailing car",end:"Al Khiran Hybrid Outlet Mall taxi point",walk:"main entrance"}, "kwi-to-al-khiran-hybrid-outlet-mall-taxi":{title:"Al Khiran Hybrid Outlet Mall",start:"KWI {{officialTaxiRank}}",service:"official airport taxi",end:"Al Khiran Hybrid Outlet Mall taxi point",walk:"main entrance"},
 "rinku-town-station-to-rinku-premium-outlets-walk":{title:"Rinku Premium Outlets",start:"Rinku Town Station",service:"signed pedestrian route",end:"Rinku Premium Outlets",walk:"outlet entrance"}, "kansai-airport-to-rinku-premium-outlets-train":{title:"Rinku Premium Outlets",start:"Kansai International Airport Station",service:"JR Kansai Airport Rapid or Nankai Airport {{train}}",end:"Rinku Town Station",walk:"Rinku Premium Outlets"},
 "tokyo-station-to-gotemba-premium-outlets-bus":{title:"Gotemba Premium Outlets",start:"Tokyo Station Yaesu {{southExit}}",service:"direct highway bus",end:"Gotemba Premium Outlets",walk:"outlet entrance"}, "shinjuku-highway-bus-terminal-to-gotemba-premium-outlets-bus":{title:"Gotemba Premium Outlets",start:"Busta Shinjuku",service:"direct JR Bus or Odakyu Bus",end:"Gotemba Premium Outlets",walk:"outlet entrance"}, "jr-gotemba-station-to-gotemba-premium-outlets-shuttle":{title:"Gotemba Premium Outlets",start:"JR Gotemba Station {{otomeguchiExit}}",service:"official free shuttle",end:"Gotemba Premium Outlets",walk:"outlet entrance"},
 "tokyo-station-to-mitsui-outlet-park-kisarazu-bus":{title:"Mitsui Outlet Park Kisarazu",start:"Bus Terminal Tokyo Yaesu",service:"direct express bus",end:"Mitsui Outlet Park Kisarazu",walk:"outlet entrance"}, "shinjuku-highway-bus-terminal-to-mitsui-outlet-park-kisarazu-bus":{title:"Mitsui Outlet Park Kisarazu",start:"Busta Shinjuku",service:"direct express bus",end:"Mitsui Outlet Park Kisarazu",walk:"outlet entrance"}, "haneda-airport-to-mitsui-outlet-park-kisarazu-bus":{title:"Mitsui Outlet Park Kisarazu",start:"Haneda Airport {{busStop}}",service:"direct Keikyu/Kominato airport bus",end:"Mitsui Outlet Park Kisarazu",walk:"outlet entrance"}, "jr-sodegaura-station-to-mitsui-outlet-park-kisarazu-bus":{title:"Mitsui Outlet Park Kisarazu",start:"JR Sodegaura Station {{northExit}}",service:"local bus",end:"Mitsui Outlet Park Kisarazu",walk:"outlet entrance"}, "jr-kisarazu-station-to-mitsui-outlet-park-kisarazu-bus":{title:"Mitsui Outlet Park Kisarazu",start:"JR Kisarazu Station {{westExit}}",service:"local bus",end:"Mitsui Outlet Park Kisarazu",walk:"outlet entrance"}
};
type StepSpec={action:"start"|"board"|"ride"|"alight"|"walk"|"pay"|"select"|"return"|"exit"|"timing";detail:string};
const stepSpecs:Record<string,StepSpec[]>={
 "al-ghubaiba-to-dubai-outlet-mall-rta-bus-66":[{action:"start",detail:"Al Ghubaiba Bus Station • RTA Bus 66 → Faqa, Terminus"},{action:"board",detail:"RTA Bus 66 → Faqa, Terminus • {{anonymous}} nol Silver Card • AED 5–7.50 • {{zoneFare}}"},{action:"ride",detail:"Bus 66 • Dubai–Al Ain Road → Dubai Outlet Mall 01"},{action:"alight",detail:"Dubai Outlet Mall 01"},{action:"walk",detail:"Dubai Outlet Mall 01 → Dubai Outlet Mall {{eastEntrance}}"},{action:"return",detail:"Dubai Outlet Mall 02 • Bus 66 → Al Ghubaiba Bus Station"}],
 "downtown-dubai-to-dubai-outlet-mall-taxi":[{action:"start",detail:"Downtown Dubai • {{taxiRideHailing}}"},{action:"select",detail:"Dubai Outlet Mall • Dubai–Al Ain Road"},{action:"ride",detail:"Dubai–Al Ain Road → Dubai Outlet Mall {{taxiDropOff}}"}],
 "dxb-to-dubai-outlet-mall-taxi":[{action:"start",detail:"DXB {{arrivals}} → {{officialTaxiRank}}"},{action:"select",detail:"Dubai Outlet Mall • Dubai–Al Ain Road"},{action:"ride",detail:"{{meteredAirportTaxi}} → Dubai Outlet Mall {{taxiDropOff}}"}],
 "downtown-dubai-to-the-outlet-village-taxi":[{action:"start",detail:"Downtown Dubai • {{taxiRideHailing}}"},{action:"select",detail:"The Outlet Village • Dubai Parks and Resorts"},{action:"ride",detail:"{{meteredTaxi}} / {{appFare}} → The Outlet Village {{entrance}}"}],
 "dxb-to-the-outlet-village-taxi":[{action:"start",detail:"DXB {{arrivals}} → {{officialTaxiRank}}"},{action:"select",detail:"The Outlet Village • Dubai Parks and Resorts • Jebel Ali"},{action:"ride",detail:"{{meteredAirportTaxi}} → The Outlet Village {{taxiDropOff}}"}],
 "dwc-to-the-outlet-village-taxi":[{action:"start",detail:"DWC {{arrivals}} → {{officialTaxiRank}}"},{action:"select",detail:"The Outlet Village • Dubai Parks and Resorts"},{action:"ride",detail:"{{meteredTaxi}} → The Outlet Village {{taxiDropOff}}"}],
 "kuwait-city-to-al-khiran-hybrid-outlet-mall-taxi":[{action:"start",detail:"Kuwait City • {{taxiRideHailing}}"},{action:"select",detail:"Al Khiran Hybrid Outlet Mall {{waterfrontPin}} ≠ Khiran Square / Norma Mall"},{action:"return",detail:"{{appFare}} / {{taxiMeter}} • Al Khiran Hybrid Outlet Mall {{mainTaxiPickup}}"}],
 "kwi-to-al-khiran-hybrid-outlet-mall-taxi":[{action:"start",detail:"KWI {{arrivals}} • {{officialAirportTaxi}} / {{rideHailing}}"},{action:"select",detail:"KWI → {{saved}} Al Khiran Hybrid Outlet Mall {{destinationPin}}"},{action:"return",detail:"{{airportTaxiFare}} • Al Khiran Hybrid Outlet Mall {{mainTaxiPickup}}"}],
 "rinku-town-station-to-rinku-premium-outlets-walk":[{action:"exit",detail:"Rinku Town Station"},{action:"walk",detail:"Rinku Town Station → Rinku Premium Outlets {{pedestrianSigns}}"},{action:"timing",detail:"{{extraTime}}: {{luggage}} / {{fartherEntrance}}"}],
 "kansai-airport-to-rinku-premium-outlets-train":[{action:"board",detail:"Kansai International Airport Station • JR Kansai Airport Rapid / Nankai Airport {{train}} → Rinku Town"},{action:"ride",detail:"{{oneStop}} • {{airportBridge}} → Rinku Town Station"},{action:"alight",detail:"Rinku Town Station"},{action:"walk",detail:"Rinku Town Station → Rinku Premium Outlets {{pedestrianSigns}}"}],
 "tokyo-station-to-gotemba-premium-outlets-bus":[{action:"start",detail:"Tokyo Station Yaesu South Exit"},{action:"board",detail:"{{directHighwayBus}} → Gotemba Premium Outlets"},{action:"pay",detail:"JPY 1,900–2,200 {{advance}} • +JPY 100 {{sameDay}} • JPY 2,500 {{onboard}}"},{action:"ride",detail:"{{sameBus}} • {{noTransfer}}"},{action:"alight",detail:"Gotemba Premium Outlets"}],
 "shinjuku-highway-bus-terminal-to-gotemba-premium-outlets-bus":[{action:"start",detail:"Shinjuku Highway Bus Terminal (Busta Shinjuku)"},{action:"board",detail:"JR Bus / Odakyu Bus → Gotemba Premium Outlets • {{direct}}"},{action:"pay",detail:"JR Bus JPY 1,900–2,200 / Odakyu Bus JPY 2,000"},{action:"ride",detail:"{{sameBus}} • {{noTransfer}}"},{action:"ride",detail:"{{direct}} • {{noTransfer}}"}],
 "jr-gotemba-station-to-gotemba-premium-outlets-shuttle":[{action:"exit",detail:"JR Gotemba Station • {{otomeguchiExit}}"},{action:"board",detail:"Gotemba Premium Outlets {{officialFreeShuttle}}"},{action:"timing",detail:":00 / :15 / :30 / :45 {{eachDaytimeHour}}"},{action:"ride",detail:"Tomei Gotemba IC → Gotemba Premium Outlets"},{action:"return",detail:"Gotemba Premium Outlets {{shuttleStop}} • :10 / :25 / :40 / :55"}],
 "tokyo-station-to-mitsui-outlet-park-kisarazu-bus":[{action:"start",detail:"Bus Terminal Tokyo Yaesu • {{beneath}} Tokyo Midtown Yaesu"},{action:"board",detail:"{{directBus}} → Mitsui Outlet Park Kisarazu"},{action:"pay",detail:"JPY 1,500 {{adult}} / JPY 750 {{child}} • {{supportedPayment}}"},{action:"ride",detail:"Tokyo Bay Aqua-Line • {{direct}}"},{action:"alight",detail:"Mitsui Outlet Park Kisarazu"}],
 "shinjuku-highway-bus-terminal-to-mitsui-outlet-park-kisarazu-bus":[{action:"start",detail:"Busta Shinjuku"},{action:"board",detail:"{{directExpressBus}} → Mitsui Outlet Park Kisarazu"},{action:"pay",detail:"JPY 1,600 {{adult}} / JPY 800 {{child}}"},{action:"ride",detail:"Tokyo Bay Aqua-Line • {{direct}}"},{action:"alight",detail:"Mitsui Outlet Park Kisarazu"}],
 "haneda-airport-to-mitsui-outlet-park-kisarazu-bus":[{action:"start",detail:"Haneda Airport {{terminal}} • {{limousineBusStop}} / {{ticketFacility}}"},{action:"select",detail:"Haneda Airport → Mitsui Outlet Park Kisarazu • {{direct}}"},{action:"pay",detail:"JPY 1,400 {{adult}} / JPY 700 {{child}}"},{action:"board",detail:"Keikyu / Kominato • {{direct}}"},{action:"alight",detail:"Tokyo Bay Aqua-Line → Mitsui Outlet Park Kisarazu"}],
 "jr-sodegaura-station-to-mitsui-outlet-park-kisarazu-bus":[{action:"exit",detail:"JR Sodegaura Station → {{northExit}}"},{action:"board",detail:"{{localBus}} → Mitsui Outlet Park Kisarazu"},{action:"pay",detail:"JPY 200 {{cash}} / JPY 199 {{icCard}}"},{action:"ride",detail:"{{duration10}}"},{action:"alight",detail:"Mitsui Outlet Park Kisarazu"}],
 "jr-kisarazu-station-to-mitsui-outlet-park-kisarazu-bus":[{action:"exit",detail:"JR Kisarazu Station → {{westExit}}"},{action:"board",detail:"{{localBus}} → Mitsui Outlet Park Kisarazu"},{action:"pay",detail:"JPY 360 {{cash}} / JPY 356 {{icCard}}"},{action:"ride",detail:"{{duration20}}"},{action:"alight",detail:"Mitsui Outlet Park Kisarazu"}],
};
const stepTerms = {
 duration10:{tr:"10 dk",es:"10 min",fr:"10 min",de:"10 Min.",ar:"10 دقائق",ru:"10 мин",zh:"10 分钟"}, duration20:{tr:"20 dk",es:"20 min",fr:"20 min",de:"20 Min.",ar:"20 دقيقة",ru:"20 мин",zh:"20 分钟"}, anonymous:{tr:"anonim",es:"anónima",fr:"anonyme",de:"anonym",ar:"المجهولة",ru:"анонимной",zh:"匿名"},
 zoneFare:{tr:"bölge sayısına bağlı ücret",es:"tarifa según el número de zonas",fr:"tarif selon le nombre de zones",de:"Fahrpreis nach Zonenzahl",ar:"تعرفة تعتمد على عدد المناطق",ru:"тариф по числу зон",zh:"按分区数量计费"},
 eastEntrance:{tr:"doğu girişi",es:"entrada este",fr:"entrée est",de:"Osteingang",ar:"المدخل الشرقي",ru:"восточный вход",zh:"东侧入口"},
 taxiRideHailing:{tr:"taksi / araç çağırma",es:"taxi / VTC",fr:"taxi / VTC",de:"Taxi / Fahrdienst",ar:"سيارة أجرة / خدمة طلب سيارة",ru:"такси / заказ автомобиля",zh:"出租车 / 网约车"},
 taxiDropOff:{tr:"taksi indirme noktası",es:"zona de bajada de taxis",fr:"dépose-minute des taxis",de:"Taxi-Ausstieg",ar:"نقطة إنزال سيارات الأجرة",ru:"место высадки такси",zh:"出租车下客点"},
 arrivals:{tr:"gelen yolcu",es:"llegadas",fr:"arrivées",de:"Ankunft",ar:"صالة الوصول",ru:"зал прилёта",zh:"到达区"},
 officialTaxiRank:{tr:"resmî taksi durağı",es:"parada oficial de taxis",fr:"station de taxis officielle",de:"offizieller Taxistand",ar:"موقف سيارات الأجرة الرسمي",ru:"официальная стоянка такси",zh:"官方出租车候车点"},
 meteredAirportTaxi:{tr:"taksimetreli havalimanı taksisi",es:"taxi de aeropuerto con taxímetro",fr:"taxi d’aéroport avec compteur",de:"Flughafentaxi mit Taxameter",ar:"سيارة أجرة المطار بالعداد",ru:"аэропортовое такси по счётчику",zh:"打表机场出租车"},
 meteredTaxi:{tr:"taksimetreli taksi",es:"taxi con taxímetro",fr:"taxi avec compteur",de:"Taxi mit Taxameter",ar:"سيارة أجرة بالعداد",ru:"такси по счётчику",zh:"打表出租车"},
 appFare:{tr:"uygulamada gösterilen ücret",es:"tarifa mostrada en la aplicación",fr:"tarif affiché dans l’application",de:"in der App angezeigter Preis",ar:"السعر الظاهر في التطبيق",ru:"цена в приложении",zh:"应用内显示价格"},
 entrance:{tr:"giriş",es:"entrada",fr:"entrée",de:"Eingang",ar:"المدخل",ru:"вход",zh:"入口"},
 waterfrontPin:{tr:"sahil konum pini",es:"pin de ubicación frente al mar",fr:"repère cartographique côté mer",de:"Kartenmarkierung an der Uferseite",ar:"دبوس الموقع على الواجهة البحرية",ru:"метка у набережной",zh:"滨水区定位点"},
 taxiMeter:{tr:"taksimetre",es:"taxímetro",fr:"compteur du taxi",de:"Taxameter",ar:"عداد سيارة الأجرة",ru:"счётчик такси",zh:"出租车计价器"},
 mainTaxiPickup:{tr:"ana taksi noktasından dönüş alımı",es:"recogida de regreso en el punto principal de taxis",fr:"prise en charge retour au point taxi principal",de:"Rückfahrt-Abholung am Haupttaxipunkt",ar:"الاستلام للعودة من نقطة سيارات الأجرة الرئيسية",ru:"обратная посадка у главной точки такси",zh:"主出租车点返程上车"},
 officialAirportTaxi:{tr:"resmî havalimanı taksisi",es:"taxi oficial del aeropuerto",fr:"taxi officiel de l’aéroport",de:"offizielles Flughafentaxi",ar:"سيارة أجرة المطار الرسمية",ru:"официальное аэропортовое такси",zh:"官方机场出租车"},
 saved:{tr:"kayıtlı",es:"guardado",fr:"enregistré",de:"gespeicherte",ar:"المحفوظ",ru:"сохранённая",zh:"已保存的"}, destinationPin:{tr:"varış konum pini",es:"pin del destino",fr:"repère de destination",de:"Zielmarkierung",ar:"دبوس الوجهة",ru:"метка пункта назначения",zh:"目的地定位点"},
 pedestrianSigns:{tr:"yaya yönlendirmeleri",es:"señales peatonales",fr:"panneaux piétons",de:"Fußgängerbeschilderung",ar:"لوحات مسار المشاة",ru:"пешеходные указатели",zh:"步行指示牌"}, extraTime:{tr:"ek süre",es:"tiempo adicional",fr:"temps supplémentaire",de:"zusätzliche Zeit",ar:"وقت إضافي",ru:"дополнительное время",zh:"额外时间"}, luggage:{tr:"bagaj",es:"equipaje",fr:"bagages",de:"Gepäck",ar:"الأمتعة",ru:"багаж",zh:"行李"}, fartherEntrance:{tr:"daha uzaktaki outlet girişi",es:"entrada más alejada del outlet",fr:"entrée plus éloignée de l’outlet",de:"weiter entfernter Outlet-Eingang",ar:"مدخل الأوتلت الأبعد",ru:"более дальний вход в аутлет",zh:"较远的奥特莱斯入口"},
 oneStop:{tr:"1 durak",es:"1 parada",fr:"1 arrêt",de:"1 Haltestelle",ar:"محطة واحدة",ru:"1 остановка",zh:"1 站"}, airportBridge:{tr:"havalimanı köprüsü",es:"puente del aeropuerto",fr:"pont de l’aéroport",de:"Flughafenbrücke",ar:"جسر المطار",ru:"аэропортовый мост",zh:"机场大桥"},
 directHighwayBus:{tr:"direkt otoyol otobüsü",es:"autobús directo de autopista",fr:"autocar direct",de:"direkter Fernbus",ar:"حافلة طريق سريع مباشرة",ru:"прямой междугородний автобус",zh:"直达高速巴士"}, advance:{tr:"önceden",es:"anticipada",fr:"à l’avance",de:"im Voraus",ar:"مسبقًا",ru:"заранее",zh:"提前购买"}, sameDay:{tr:"aynı gün",es:"mismo día",fr:"le jour même",de:"am selben Tag",ar:"في اليوم نفسه",ru:"в день поездки",zh:"当日购买"}, onboard:{tr:"araçta",es:"a bordo",fr:"à bord",de:"an Bord",ar:"على متن الحافلة",ru:"на борту",zh:"车上购买"}, sameBus:{tr:"aynı otobüs",es:"el mismo autobús",fr:"le même autocar",de:"derselbe Bus",ar:"الحافلة نفسها",ru:"тот же автобус",zh:"同一班巴士"}, noTransfer:{tr:"aktarmasız",es:"sin transbordo",fr:"sans correspondance",de:"ohne Umstieg",ar:"من دون تبديل",ru:"без пересадки",zh:"无需换乘"},
 directExpressBus:{tr:"direkt ekspres otobüs",es:"autobús exprés directo",fr:"bus express direct",de:"direkter Expressbus",ar:"حافلة سريعة مباشرة",ru:"прямой экспресс-автобус",zh:"直达快速巴士"}, directBus:{tr:"direkt otobüs",es:"autobús directo",fr:"bus direct",de:"direkter Bus",ar:"حافلة مباشرة",ru:"прямой автобус",zh:"直达巴士"}, direct:{tr:"direkt",es:"directo",fr:"direct",de:"direkt",ar:"مباشر",ru:"напрямую",zh:"直达"}, officialFreeShuttle:{tr:"resmî ücretsiz servis",es:"lanzadera oficial gratuita",fr:"navette officielle gratuite",de:"offizieller kostenloser Shuttle",ar:"حافلة النقل الرسمية المجانية",ru:"официальный бесплатный шаттл",zh:"官方免费接驳车"}, eachDaytimeHour:{tr:"gündüz her saat",es:"cada hora durante el día",fr:"chaque heure en journée",de:"tagsüber stündlich",ar:"كل ساعة نهارًا",ru:"каждый час днём",zh:"白天每小时"},
 adult:{tr:"yetişkin",es:"adulto",fr:"adulte",de:"Erwachsene",ar:"للبالغ",ru:"взрослый",zh:"成人"}, child:{tr:"çocuk",es:"niño",fr:"enfant",de:"Kind",ar:"للطفل",ru:"детский",zh:"儿童"}, supportedPayment:{tr:"desteklenen ödeme yöntemi",es:"método de pago admitido",fr:"moyen de paiement accepté",de:"akzeptierte Zahlungsmethode",ar:"طريقة دفع مدعومة",ru:"поддерживаемый способ оплаты",zh:"支持的付款方式"}, limousineBusStop:{tr:"limuzin otobüsü durağı",es:"parada del autobús limusina",fr:"arrêt de limousine-bus",de:"Limousinenbus-Haltestelle",ar:"موقف حافلة الليموزين",ru:"остановка лимузин-автобуса",zh:"机场巴士站"}, ticketFacility:{tr:"bilet noktası",es:"punto de billetes",fr:"point de vente des billets",de:"Ticketschalter",ar:"مرفق التذاكر",ru:"билетная касса",zh:"售票处"}, localBus:{tr:"yerel otobüs",es:"autobús local",fr:"bus local",de:"Linienbus",ar:"حافلة محلية",ru:"местный автобус",zh:"本地巴士"}, cash:{tr:"nakit",es:"efectivo",fr:"espèces",de:"bar",ar:"نقدًا",ru:"наличными",zh:"现金"}, icCard:{tr:"IC kart",es:"tarjeta IC",fr:"carte IC",de:"IC-Karte",ar:"بطاقة IC",ru:"карта IC",zh:"IC 卡"}, northExit:{tr:"Kuzey Çıkışı",es:"Salida Norte",fr:"sortie nord",de:"Nordausgang",ar:"المخرج الشمالي",ru:"северный выход",zh:"北口"}, westExit:{tr:"Batı Çıkışı",es:"Salida Oeste",fr:"sortie ouest",de:"Westausgang",ar:"المخرج الغربي",ru:"западный выход",zh:"西口"}, otomeguchiExit:{tr:"Otomeguchi Çıkışı",es:"Salida Otomeguchi",fr:"sortie Otomeguchi",de:"Ausgang Otomeguchi",ar:"مخرج Otomeguchi",ru:"выход Otomeguchi",zh:"Otomeguchi（乙女口）"}, train:{tr:"treni",es:"tren",fr:"train",de:"Zug",ar:"قطار",ru:"поезд",zh:"列车"}, terminal:{tr:"terminali",es:"terminal",fr:"terminal",de:"Terminal",ar:"مبنى الركاب",ru:"терминал",zh:"航站楼"}, rideHailing:{tr:"araç çağırma",es:"VTC",fr:"VTC",de:"Fahrdienst",ar:"خدمة طلب سيارة",ru:"заказ автомобиля",zh:"网约车"}, shuttleStop:{tr:"servis durağı",es:"parada de la lanzadera",fr:"arrêt de la navette",de:"Shuttle-Haltestelle",ar:"موقف حافلة النقل",ru:"остановка шаттла",zh:"接驳车站"}, beneath:{tr:"altında",es:"debajo de",fr:"sous",de:"unter",ar:"أسفل",ru:"под",zh:"地下"}, airportTaxiFare:{tr:"havalimanı taksi ücreti",es:"tarifa del taxi del aeropuerto",fr:"tarif du taxi d’aéroport",de:"Flughafentaxipreis",ar:"تعرفة سيارة أجرة المطار",ru:"тариф аэропортового такси",zh:"机场出租车费"}
} as const;
type StepTerm=keyof typeof stepTerms;
const localizeStepDetail=(detail:string,language:Exclude<TargetContentLanguage,"en">)=>detail.replace(/\{\{([a-zA-Z0-9]+)\}\}/g,(_,term:string)=>stepTerms[term as StepTerm]?.[language]??term);
const stepVerbs:Record<TargetContentLanguage,Record<StepSpec["action"],(detail:string)=>string>>={
 en:{start:d=>`Start at ${d}.`,board:d=>`Board ${d}.`,ride:d=>`Travel ${d}.`,alight:d=>`Alight at ${d}.`,walk:d=>`Follow ${d}.`,pay:d=>`Pay/use ${d}.`,select:d=>`Set/request ${d} as the destination.`,return:d=>`For the return: ${d}.`,exit:d=>`Exit at ${d}.`,timing:d=>`${d[0].toUpperCase()}${d.slice(1)}.`},
 tr:{start:d=>`${d} noktasından başlayın.`,board:d=>`${d} aracına binin.`,ride:d=>`${d} yolculuk yapın.`,alight:d=>`${d} noktasında inin.`,walk:d=>`${d} yönlendirmelerini takip edin.`,pay:d=>`${d} ücretini/ödeme yöntemini kullanın.`,select:d=>`Varış noktası olarak ${d} seçin.`,return:d=>`Dönüş için: ${d}.`,exit:d=>`${d} çıkışını kullanın.`,timing:d=>`${d}.`},
 es:{start:d=>`Comience en ${d}.`,board:d=>`Suba a ${d}.`,ride:d=>`Viaje ${d}.`,alight:d=>`Baje en ${d}.`,walk:d=>`Siga ${d}.`,pay:d=>`Pague/utilice ${d}.`,select:d=>`Seleccione o solicite ${d} como destino.`,return:d=>`Para el regreso: ${d}.`,exit:d=>`Salga por ${d}.`,timing:d=>`${d}.`},
 fr:{start:d=>`Partez de ${d}.`,board:d=>`Montez à bord de ${d}.`,ride:d=>`Voyagez ${d}.`,alight:d=>`Descendez à ${d}.`,walk:d=>`Suivez ${d}.`,pay:d=>`Payez/utilisez ${d}.`,select:d=>`Choisissez ou demandez ${d} comme destination.`,return:d=>`Pour le retour : ${d}.`,exit:d=>`Sortez par ${d}.`,timing:d=>`${d}.`},
 de:{start:d=>`Starten Sie an ${d}.`,board:d=>`Steigen Sie in ${d} ein.`,ride:d=>`Fahren Sie ${d}.`,alight:d=>`Steigen Sie an ${d} aus.`,walk:d=>`Folgen Sie ${d}.`,pay:d=>`Bezahlen/nutzen Sie ${d}.`,select:d=>`Wählen oder nennen Sie ${d} als Ziel.`,return:d=>`Für die Rückfahrt: ${d}.`,exit:d=>`Nehmen Sie den Ausgang ${d}.`,timing:d=>`${d}.`},
 ar:{start:d=>`ابدأ من ${d}.`,board:d=>`استقل ${d}.`,ride:d=>`تابع الرحلة ${d}.`,alight:d=>`انزل عند ${d}.`,walk:d=>`اتبع ${d}.`,pay:d=>`ادفع/استخدم ${d}.`,select:d=>`اختر أو اطلب ${d} كوجهة.`,return:d=>`للعودة: ${d}.`,exit:d=>`اخرج من ${d}.`,timing:d=>`${d}.`},
 ru:{start:d=>`Начните у ${d}.`,board:d=>`Сядьте на ${d}.`,ride:d=>`Следуйте ${d}.`,alight:d=>`Выйдите у ${d}.`,walk:d=>`Следуйте ${d}.`,pay:d=>`Оплатите/используйте ${d}.`,select:d=>`Укажите ${d} как пункт назначения.`,return:d=>`Для обратной поездки: ${d}.`,exit:d=>`Выйдите через ${d}.`,timing:d=>`${d}.`},
 zh:{start:d=>`从${d}出发。`,board:d=>`乘坐${d}。`,ride:d=>`按${d}行驶。`,alight:d=>`在${d}下车。`,walk:d=>`按照${d}步行。`,pay:d=>`支付/使用${d}。`,select:d=>`将${d}设为目的地。`,return:d=>`返程：${d}。`,exit:d=>`从${d}出站。`,timing:d=>`${d}。`},
};
const bus66BoardingStep:Record<Exclude<TargetContentLanguage,"en">,string>={
 tr:"Faqa, Terminus yönündeki RTA Bus 66’ya binin. AED 5–7.50, anonim nol Silver Card ile bölge sayısına bağlı tahmini ücrettir.",
 es:"Suba al RTA Bus 66 hacia Faqa, Terminus. AED 5–7,50 es la tarifa estimada con una tarjeta nol Silver anónima y depende del número de zonas.",
 fr:"Montez à bord du RTA Bus 66 vers Faqa, Terminus. Le tarif estimé de AED 5–7,50 avec une carte nol Silver anonyme dépend du nombre de zones.",
 de:"Steigen Sie in den RTA Bus 66 Richtung Faqa, Terminus. Der geschätzte Fahrpreis von AED 5–7,50 mit anonymer nol Silver Card hängt von der Zonenzahl ab.",
 ar:"استقل RTA Bus 66 باتجاه Faqa, Terminus. مبلغ AED 5–7.50 هو تعرفة تقديرية ببطاقة nol Silver المجهولة وتعتمد على عدد المناطق.",
 ru:"Сядьте на RTA Bus 66 в направлении Faqa, Terminus. Ориентировочная стоимость AED 5–7,50 по анонимной карте nol Silver зависит от числа зон.",
 zh:"乘坐开往 Faqa, Terminus 的 RTA Bus 66。使用匿名 nol Silver 卡的估算票价为 AED 5–7.50，实际票价取决于跨越的分区数量。",
};
const localizeSteps=(guide:TransportationGuide,language:TargetContentLanguage)=>{const specs=stepSpecs[guide.guideId];if(!specs||specs.length!==guide.steps.length)return undefined;return specs.map((spec,index)=>guide.guideId==="al-ghubaiba-to-dubai-outlet-mall-rta-bus-66"&&index===1&&language!=="en"?bus66BoardingStep[language]:stepVerbs[language][spec.action](language==="en"?spec.detail:localizeStepDetail(spec.detail,language)));};
const originTerms:Record<"officialTaxiRank"|"busStop"|"southExit"|"northExit"|"westExit"|"otomeguchiExit",Record<TargetContentLanguage,string>>={
 officialTaxiRank:{en:"official taxi rank",tr:"resmî taksi durağı",es:"parada oficial de taxis",fr:"station de taxis officielle",de:"offizieller Taxistand",ar:"موقف سيارات الأجرة الرسمي",ru:"официальная стоянка такси",zh:"官方出租车候车点"},
 busStop:{en:"bus stop",tr:"otobüs durağı",es:"parada de autobús",fr:"arrêt de bus",de:"Bushaltestelle",ar:"موقف الحافلات",ru:"автобусная остановка",zh:"巴士站"},
 southExit:{en:"South Exit",tr:"Güney Çıkışı",es:"Salida Sur",fr:"sortie sud",de:"Südausgang",ar:"المخرج الجنوبي",ru:"южный выход",zh:"南口"},
 northExit:{en:"North Exit",tr:"Kuzey Çıkışı",es:"Salida Norte",fr:"sortie nord",de:"Nordausgang",ar:"المخرج الشمالي",ru:"северный выход",zh:"北口"},
 westExit:{en:"West Exit",tr:"Batı Çıkışı",es:"Salida Oeste",fr:"sortie ouest",de:"Westausgang",ar:"المخرج الغربي",ru:"западный выход",zh:"西口"},
 otomeguchiExit:{en:"Otomeguchi Exit",tr:"Otomeguchi Çıkışı",es:"Salida Otomeguchi",fr:"sortie Otomeguchi",de:"Ausgang Otomeguchi",ar:"مخرج Otomeguchi",ru:"выход Otomeguchi",zh:"Otomeguchi（乙女口）"},
};
const localizeRouteOrigin=(value:string,language:TargetContentLanguage)=>value.replace(/\{\{(officialTaxiRank|busStop|southExit|northExit|westExit|otomeguchiExit)\}\}/g,(_,term:string)=>originTerms[term as keyof typeof originTerms][language]);
const titleTemplates:Record<TargetContentLanguage,(r:Route)=>string>={en:r=>`From ${r.start} to ${r.title}`,tr:r=>`${r.start} noktasından ${r.title}’a`,de:r=>`Von ${r.start} nach ${r.title}`,fr:r=>`De ${r.start} à ${r.title}`,es:r=>`De ${r.start} a ${r.title}`,ar:r=>`من ${r.start} إلى ${r.title}`,ru:r=>`От ${r.start} до ${r.title}`,zh:r=>`从${r.start}前往${r.title}`};
const localizeEstimate=(value:string,l:TargetContentLanguage)=>{
  if(l==="en") return value;
  const words={tr:{approx:"Yaklaşık",free:"Ücretsiz",min:"dk",hour:"sa"},de:{approx:"Ca.",free:"Kostenlos",min:"Min.",hour:"Std."},fr:{approx:"Environ",free:"Gratuit",min:"min",hour:"h"},es:{approx:"Aprox.",free:"Gratis",min:"min",hour:"h"},ar:{approx:"حوالي",free:"مجانًا",min:"دقيقة",hour:"ساعة"},ru:{approx:"Около",free:"Бесплатно",min:"мин",hour:"ч"},zh:{approx:"约",free:"免费",min:"分钟",hour:"小时"}}[l];
  if(/^Free$/i.test(value)) return words.free;
  const currency=value.match(/\b(AED|KWD|JPY)\b/);
  const nums=[...value.matchAll(/\d[\d,.]*(?:\.\d+)?(?:[–-]\d[\d,.]*(?:\.\d+)?)?/g)].map(m=>m[0]);
  if(currency) return `${words.approx} ${currency[1]} ${nums[0]??""}`.trim();
  const hours=value.match(/(\d+(?:[–-]\d+)?)\s*hr/); const mins=value.match(/(\d+(?:[–-]\d+)?)\s*min/);
  return `${words.approx} ${hours?`${hours[1]} ${words.hour} `:""}${mins?`${mins[1]} ${words.min}`:nums[0]??""}`.trim();
};
const bus66Notes:Record<TargetContentLanguage,{note:string;link:string}>={
 en:{note:"AED 5–7.50 is an estimated anonymous nol Silver Card fare; the applicable fare depends on the journey’s zone count. Operating-day departures and the final return service vary.",link:"Open the official RTA / mall departure schedule"},
 tr:{note:"AED 5–7,50, anonim nol Silver Card için tahmini ücrettir; uygulanacak ücret yolculuğun bölge sayısına bağlıdır. İşletim günlerindeki seferler ve son dönüş servisi değişir.",link:"Resmî RTA / AVM sefer programını aç"},
 es:{note:"AED 5–7,50 es una tarifa estimada con tarjeta nol Silver anónima; la tarifa aplicable depende del número de zonas del trayecto. Las salidas por día de servicio y el último regreso varían.",link:"Abrir el horario oficial de salidas de RTA / centro"},
 fr:{note:"AED 5–7,50 est une estimation avec une carte nol Silver anonyme ; le tarif applicable dépend du nombre de zones du trajet. Les départs selon le jour de service et le dernier retour varient.",link:"Ouvrir les départs officiels RTA / centre"},
 de:{note:"AED 5–7,50 ist ein geschätzter Fahrpreis mit anonymer nol Silver Card; der anwendbare Preis hängt von der Zonenzahl ab. Betriebstage, Abfahrten und die letzte Rückfahrt variieren.",link:"Offiziellen RTA-/Center-Abfahrtsplan öffnen"},
 ar:{note:"AED 5–7.50 تقدير لتعرفة بطاقة nol Silver المجهولة؛ وتعتمد التعرفة المطبقة على عدد مناطق الرحلة. تختلف الرحلات حسب يوم التشغيل وموعد آخر رحلة عودة.",link:"فتح جدول رحلات RTA / المركز الرسمي"},
 ru:{note:"AED 5–7,50 — ориентировочная стоимость по анонимной карте nol Silver; применимый тариф зависит от числа зон поездки. Отправления по дням работы и последний обратный рейс различаются.",link:"Открыть официальный график RTA / центра"},
 zh:{note:"AED 5–7.50 是匿名 nol Silver 卡的估算票价；实际票价取决于行程跨越的分区数量。不同运营日的班次及末班返程时间会有变化。",link:"打开 RTA / 商场官方班次表"},
};
export function localizeTargetGuide(guide:TransportationGuide,language:TargetContentLanguage):LocalizedGuideCopy|undefined{const route=routes[guide.guideId];if(!route)return;const busNote=guide.guideId==="al-ghubaiba-to-dubai-outlet-mall-rta-bus-66"?bus66Notes[language]:undefined;return{title:titleTemplates[language]({...route,start:localizeRouteOrigin(route.start,language)}),estimatedDuration:localizeEstimate(guide.estimatedDuration,language),estimatedCost:localizeEstimate(guide.estimatedCost,language),steps:language==="en"?[...guide.steps].sort((a,b)=>a.order-b.order).map(step=>step.description):localizeSteps(guide,language)??[],routeNote:busNote?.note,officialLinkLabel:busNote?.link}}
export function getTargetQuickInfo(outletId:string,language:string){const copy=targetOutletQuickInfo[outletId];if(!copy)return;return copy[language as TargetContentLanguage] ?? copy.en;}
