/** Official Yeoju Premium Outlets store-directory snapshot supplied by the user on 2026-08-13. */
export type YeojuDirectoryRow = { sequence: number; category: string; categoryOrder: number; categorySequence: number; displayName: string; taxRefundAvailable: boolean; sourceScreenshot: string; canonicalBrandId: string; note?: string };
export const yeojuPremiumOutletsCategoryAudit = [
  {
    "category": "Luxury Boutique & Designer Collection",
    "declaredCount": 52,
    "observedCount": 52
  },
  {
    "category": "Contemporary",
    "declaredCount": 35,
    "observedCount": 35
  },
  {
    "category": "Women’s Fashion",
    "declaredCount": 26,
    "observedCount": 27
  },
  {
    "category": "Men’s Fashion",
    "declaredCount": 19,
    "observedCount": 19
  },
  {
    "category": "Jean & Casual & SPA",
    "declaredCount": 6,
    "observedCount": 6
  },
  {
    "category": "Shoes & Bags",
    "declaredCount": 18,
    "observedCount": 18
  },
  {
    "category": "Sports & Golf & Outdoor",
    "declaredCount": 47,
    "observedCount": 47
  },
  {
    "category": "Accessories",
    "declaredCount": 17,
    "observedCount": 17
  },
  {
    "category": "Kids",
    "declaredCount": 19,
    "observedCount": 19
  },
  {
    "category": "Living",
    "declaredCount": 3,
    "observedCount": 3
  },
  {
    "category": "Etc",
    "declaredCount": 19,
    "observedCount": 19
  }
] as const;
export const yeojuPremiumOutletsDirectory: YeojuDirectoryRow[] = [
  {
    "sequence": 1,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 1,
    "displayName": "ACNE STUDIOS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "FD31D25B-16F2-4D13-B044-AA3956A17B0D.png",
    "canonicalBrandId": "acne-studios"
  },
  {
    "sequence": 2,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 2,
    "displayName": "ARMANI STORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "FD31D25B-16F2-4D13-B044-AA3956A17B0D.png",
    "canonicalBrandId": "armani"
  },
  {
    "sequence": 3,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 3,
    "displayName": "Andersson Bell",
    "taxRefundAvailable": true,
    "sourceScreenshot": "FD31D25B-16F2-4D13-B044-AA3956A17B0D.png",
    "canonicalBrandId": "andersson-bell"
  },
  {
    "sequence": 4,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 4,
    "displayName": "BALENCIAGA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "FD31D25B-16F2-4D13-B044-AA3956A17B0D.png",
    "canonicalBrandId": "balenciaga"
  },
  {
    "sequence": 5,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 5,
    "displayName": "BALLY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C157396-1143-4D13-89BD-5BA4C1E70FD7.png",
    "canonicalBrandId": "bally"
  },
  {
    "sequence": 6,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 6,
    "displayName": "BOON THE SHOP",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C157396-1143-4D13-89BD-5BA4C1E70FD7.png",
    "canonicalBrandId": "boon-the-shop"
  },
  {
    "sequence": 7,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 7,
    "displayName": "BOSS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C157396-1143-4D13-89BD-5BA4C1E70FD7.png",
    "canonicalBrandId": "boss"
  },
  {
    "sequence": 8,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 8,
    "displayName": "BOTTEGA VENETA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C157396-1143-4D13-89BD-5BA4C1E70FD7.png",
    "canonicalBrandId": "bottega-veneta"
  },
  {
    "sequence": 9,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 9,
    "displayName": "BRUNELLO CUCINELLI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C157396-1143-4D13-89BD-5BA4C1E70FD7.png",
    "canonicalBrandId": "brunello-cucinelli"
  },
  {
    "sequence": 10,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 10,
    "displayName": "BURBERRY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4C881F95-2F1B-4EB1-9554-5CF6D56BA933.png",
    "canonicalBrandId": "burberry"
  },
  {
    "sequence": 11,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 11,
    "displayName": "Brioni",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4C881F95-2F1B-4EB1-9554-5CF6D56BA933.png",
    "canonicalBrandId": "brioni"
  },
  {
    "sequence": 12,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 12,
    "displayName": "COACH",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4C881F95-2F1B-4EB1-9554-5CF6D56BA933.png",
    "canonicalBrandId": "coach"
  },
  {
    "sequence": 13,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 13,
    "displayName": "CORNELIANI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4C881F95-2F1B-4EB1-9554-5CF6D56BA933.png",
    "canonicalBrandId": "corneliani"
  },
  {
    "sequence": 14,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 14,
    "displayName": "Chloe",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4C881F95-2F1B-4EB1-9554-5CF6D56BA933.png",
    "canonicalBrandId": "chloe"
  },
  {
    "sequence": 15,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 15,
    "displayName": "Etro",
    "taxRefundAvailable": true,
    "sourceScreenshot": "8E41D32E-381B-477A-BBF1-EDCBDE05DA17.png",
    "canonicalBrandId": "etro"
  },
  {
    "sequence": 16,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 16,
    "displayName": "FABIANA FILIPPI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "8E41D32E-381B-477A-BBF1-EDCBDE05DA17.png",
    "canonicalBrandId": "fabiana-filippi"
  },
  {
    "sequence": 17,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 17,
    "displayName": "FENDI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "8E41D32E-381B-477A-BBF1-EDCBDE05DA17.png",
    "canonicalBrandId": "fendi"
  },
  {
    "sequence": 18,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 18,
    "displayName": "GUCCI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "8E41D32E-381B-477A-BBF1-EDCBDE05DA17.png",
    "canonicalBrandId": "gucci"
  },
  {
    "sequence": 19,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 19,
    "displayName": "HERNO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "8E41D32E-381B-477A-BBF1-EDCBDE05DA17.png",
    "canonicalBrandId": "herno"
  },
  {
    "sequence": 20,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 20,
    "displayName": "JIMMY CHOO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85C88D86-B368-450D-AC04-6E6B30C6BE9A.png",
    "canonicalBrandId": "jimmy-choo"
  },
  {
    "sequence": 21,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 21,
    "displayName": "Jill Sander(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85C88D86-B368-450D-AC04-6E6B30C6BE9A.png",
    "canonicalBrandId": "jil-sander",
    "note": "Official display spelling preserved; (PES) scope marker not interpreted."
  },
  {
    "sequence": 22,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 22,
    "displayName": "KENZO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85C88D86-B368-450D-AC04-6E6B30C6BE9A.png",
    "canonicalBrandId": "kenzo"
  },
  {
    "sequence": 23,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 23,
    "displayName": "KITON",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85C88D86-B368-450D-AC04-6E6B30C6BE9A.png",
    "canonicalBrandId": "kiton"
  },
  {
    "sequence": 24,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 24,
    "displayName": "LANSMERE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85C88D86-B368-450D-AC04-6E6B30C6BE9A.png",
    "canonicalBrandId": "lansmere"
  },
  {
    "sequence": 25,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 25,
    "displayName": "LOEWE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F93A65FD-189D-4120-B2C0-068E4E9E6B97.png",
    "canonicalBrandId": "loewe"
  },
  {
    "sequence": 26,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 26,
    "displayName": "LORO PIANA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F93A65FD-189D-4120-B2C0-068E4E9E6B97.png",
    "canonicalBrandId": "loro-piana"
  },
  {
    "sequence": 27,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 27,
    "displayName": "Lanvin Collection",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F93A65FD-189D-4120-B2C0-068E4E9E6B97.png",
    "canonicalBrandId": "lanvin-collection"
  },
  {
    "sequence": 28,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 28,
    "displayName": "MARNI(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F93A65FD-189D-4120-B2C0-068E4E9E6B97.png",
    "canonicalBrandId": "marni",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 29,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 29,
    "displayName": "MAX MARA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F93A65FD-189D-4120-B2C0-068E4E9E6B97.png",
    "canonicalBrandId": "max-mara"
  },
  {
    "sequence": 30,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 30,
    "displayName": "MICHAEL KORS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "88755559-7192-4120-A4A4-5AC941467CED.png",
    "canonicalBrandId": "michael-kors"
  },
  {
    "sequence": 31,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 31,
    "displayName": "MONCLER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "88755559-7192-4120-A4A4-5AC941467CED.png",
    "canonicalBrandId": "moncler"
  },
  {
    "sequence": 32,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 32,
    "displayName": "MONTBLANC",
    "taxRefundAvailable": true,
    "sourceScreenshot": "88755559-7192-4120-A4A4-5AC941467CED.png",
    "canonicalBrandId": "montblanc"
  },
  {
    "sequence": 33,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 33,
    "displayName": "MOSCHINO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "88755559-7192-4120-A4A4-5AC941467CED.png",
    "canonicalBrandId": "moschino"
  },
  {
    "sequence": 34,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 34,
    "displayName": "MULBERRY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "88755559-7192-4120-A4A4-5AC941467CED.png",
    "canonicalBrandId": "mulberry"
  },
  {
    "sequence": 35,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 35,
    "displayName": "Maison Kitsune",
    "taxRefundAvailable": true,
    "sourceScreenshot": "69A65C4E-E709-4462-833A-DCC8356C642B.png",
    "canonicalBrandId": "maison-kitsune"
  },
  {
    "sequence": 36,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 36,
    "displayName": "Maison Margiela",
    "taxRefundAvailable": true,
    "sourceScreenshot": "69A65C4E-E709-4462-833A-DCC8356C642B.png",
    "canonicalBrandId": "maison-margiela"
  },
  {
    "sequence": 37,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 37,
    "displayName": "PAUL SMITH",
    "taxRefundAvailable": true,
    "sourceScreenshot": "69A65C4E-E709-4462-833A-DCC8356C642B.png",
    "canonicalBrandId": "paul-smith"
  },
  {
    "sequence": 38,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 38,
    "displayName": "PRADA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "69A65C4E-E709-4462-833A-DCC8356C642B.png",
    "canonicalBrandId": "prada"
  },
  {
    "sequence": 39,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 39,
    "displayName": "ROGER VIVIER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "69A65C4E-E709-4462-833A-DCC8356C642B.png",
    "canonicalBrandId": "roger-vivier"
  },
  {
    "sequence": 40,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 40,
    "displayName": "Rick Owens",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F2211797-3298-4224-B5F2-F4BC6F31CB3C.png",
    "canonicalBrandId": "rick-owens"
  },
  {
    "sequence": 41,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 41,
    "displayName": "S.T. DUPONT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F2211797-3298-4224-B5F2-F4BC6F31CB3C.png",
    "canonicalBrandId": "st-dupont"
  },
  {
    "sequence": 42,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 42,
    "displayName": "SAINT LAURENT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F2211797-3298-4224-B5F2-F4BC6F31CB3C.png",
    "canonicalBrandId": "saint-laurent"
  },
  {
    "sequence": 43,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 43,
    "displayName": "Salvatore Ferragamo",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F2211797-3298-4224-B5F2-F4BC6F31CB3C.png",
    "canonicalBrandId": "ferragamo"
  },
  {
    "sequence": 44,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 44,
    "displayName": "Stone Island",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F2211797-3298-4224-B5F2-F4BC6F31CB3C.png",
    "canonicalBrandId": "stone-island"
  },
  {
    "sequence": 45,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 45,
    "displayName": "TOD’S",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A3D8B2C9-5D55-439A-B779-33CEA4E9A377.png",
    "canonicalBrandId": "tods"
  },
  {
    "sequence": 46,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 46,
    "displayName": "TOM FORD",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A3D8B2C9-5D55-439A-B779-33CEA4E9A377.png",
    "canonicalBrandId": "tom-ford"
  },
  {
    "sequence": 47,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 47,
    "displayName": "TUMI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A3D8B2C9-5D55-439A-B779-33CEA4E9A377.png",
    "canonicalBrandId": "tumi"
  },
  {
    "sequence": 48,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 48,
    "displayName": "Thom Browne",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A3D8B2C9-5D55-439A-B779-33CEA4E9A377.png",
    "canonicalBrandId": "thom-browne"
  },
  {
    "sequence": 49,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 49,
    "displayName": "VALENTINO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A3D8B2C9-5D55-439A-B779-33CEA4E9A377.png",
    "canonicalBrandId": "valentino"
  },
  {
    "sequence": 50,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 50,
    "displayName": "VERSACE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DB39F11A-85F0-4E93-A6EC-85E67B9471D5.png",
    "canonicalBrandId": "versace"
  },
  {
    "sequence": 51,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 51,
    "displayName": "VIVIENNE WESTWOOD",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DB39F11A-85F0-4E93-A6EC-85E67B9471D5.png",
    "canonicalBrandId": "vivienne-westwood"
  },
  {
    "sequence": 52,
    "category": "Luxury Boutique & Designer Collection",
    "categoryOrder": 1,
    "categorySequence": 52,
    "displayName": "ZEGNA OUTLET STORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DB39F11A-85F0-4E93-A6EC-85E67B9471D5.png",
    "canonicalBrandId": "zegna"
  },
  {
    "sequence": 53,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 1,
    "displayName": "A.P.C.",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C5979085-05B1-438A-A49F-97445A4DE694.png",
    "canonicalBrandId": "a-p-c"
  },
  {
    "sequence": 54,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 2,
    "displayName": "Allsaints(P)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C5979085-05B1-438A-A49F-97445A4DE694.png",
    "canonicalBrandId": "allsaints",
    "note": "(P) scope marker preserved."
  },
  {
    "sequence": 55,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 3,
    "displayName": "Aspesi(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C5979085-05B1-438A-A49F-97445A4DE694.png",
    "canonicalBrandId": "aspesi",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 56,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 4,
    "displayName": "BEAKER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C5979085-05B1-438A-A49F-97445A4DE694.png",
    "canonicalBrandId": "beaker"
  },
  {
    "sequence": 57,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 5,
    "displayName": "Barbour",
    "taxRefundAvailable": true,
    "sourceScreenshot": "81766B6C-7E27-4FA7-AC1B-0B68DE477C6F.png",
    "canonicalBrandId": "barbour"
  },
  {
    "sequence": 58,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 6,
    "displayName": "Botticelli",
    "taxRefundAvailable": true,
    "sourceScreenshot": "81766B6C-7E27-4FA7-AC1B-0B68DE477C6F.png",
    "canonicalBrandId": "botticelli"
  },
  {
    "sequence": 59,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 7,
    "displayName": "C.P. COMPANY/C.P COMPANY U16",
    "taxRefundAvailable": true,
    "sourceScreenshot": "81766B6C-7E27-4FA7-AC1B-0B68DE477C6F.png",
    "canonicalBrandId": "cp-company",
    "note": "One combined directory row; the on-screen line break is represented with a slash."
  },
  {
    "sequence": 60,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 8,
    "displayName": "CLUB MONACO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "81766B6C-7E27-4FA7-AC1B-0B68DE477C6F.png",
    "canonicalBrandId": "club-monaco"
  },
  {
    "sequence": 61,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 9,
    "displayName": "DKNY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "81766B6C-7E27-4FA7-AC1B-0B68DE477C6F.png",
    "canonicalBrandId": "dkny"
  },
  {
    "sequence": 62,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 10,
    "displayName": "Eleventy",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E843403D-4F28-49CD-B051-096F31DE5746.png",
    "canonicalBrandId": "eleventy"
  },
  {
    "sequence": 63,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 11,
    "displayName": "GOLDEN GOOSE DELUXE BRAND",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E843403D-4F28-49CD-B051-096F31DE5746.png",
    "canonicalBrandId": "golden-goose"
  },
  {
    "sequence": 64,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 12,
    "displayName": "IRO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E843403D-4F28-49CD-B051-096F31DE5746.png",
    "canonicalBrandId": "iro"
  },
  {
    "sequence": 65,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 13,
    "displayName": "ISABEL MARANT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E843403D-4F28-49CD-B051-096F31DE5746.png",
    "canonicalBrandId": "isabel-marant"
  },
  {
    "sequence": 66,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 14,
    "displayName": "JILL STUART",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E843403D-4F28-49CD-B051-096F31DE5746.png",
    "canonicalBrandId": "jill-stuart"
  },
  {
    "sequence": 67,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 15,
    "displayName": "JuunJ",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6C8A03EF-6049-4C94-9984-F8A37AF1DF2E.png",
    "canonicalBrandId": "junn-j"
  },
  {
    "sequence": 68,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 16,
    "displayName": "KUHO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6C8A03EF-6049-4C94-9984-F8A37AF1DF2E.png",
    "canonicalBrandId": "kuho"
  },
  {
    "sequence": 69,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 17,
    "displayName": "LEBEIGE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6C8A03EF-6049-4C94-9984-F8A37AF1DF2E.png",
    "canonicalBrandId": "lebeige"
  },
  {
    "sequence": 70,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 18,
    "displayName": "MAJE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6C8A03EF-6049-4C94-9984-F8A37AF1DF2E.png",
    "canonicalBrandId": "maje"
  },
  {
    "sequence": 71,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 19,
    "displayName": "MAN ON THE BOON.",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6C8A03EF-6049-4C94-9984-F8A37AF1DF2E.png",
    "canonicalBrandId": "man-on-the-boon"
  },
  {
    "sequence": 72,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 20,
    "displayName": "MINE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4E95618E-CABE-421D-B5E9-D4538B2D4148.png",
    "canonicalBrandId": "mine"
  },
  {
    "sequence": 73,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 21,
    "displayName": "MOOSE KNUCKLES",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4E95618E-CABE-421D-B5E9-D4538B2D4148.png",
    "canonicalBrandId": "moose-knuckles"
  },
  {
    "sequence": 74,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 22,
    "displayName": "MUE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4E95618E-CABE-421D-B5E9-D4538B2D4148.png",
    "canonicalBrandId": "mue"
  },
  {
    "sequence": 75,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 23,
    "displayName": "Matin Kim",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4E95618E-CABE-421D-B5E9-D4538B2D4148.png",
    "canonicalBrandId": "matin-kim"
  },
  {
    "sequence": 76,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 24,
    "displayName": "S.I. Village",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4E95618E-CABE-421D-B5E9-D4538B2D4148.png",
    "canonicalBrandId": "s-i-village",
    "note": "Name may indicate adjacent-property scope; no property-boundary evidence was supplied."
  },
  {
    "sequence": 77,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 25,
    "displayName": "TIME HOMME",
    "taxRefundAvailable": true,
    "sourceScreenshot": "5647E745-89B4-492F-BD0D-634E73D15927.png",
    "canonicalBrandId": "time-homme"
  },
  {
    "sequence": 78,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 26,
    "displayName": "The Ilma",
    "taxRefundAvailable": true,
    "sourceScreenshot": "5647E745-89B4-492F-BD0D-634E73D15927.png",
    "canonicalBrandId": "theilma"
  },
  {
    "sequence": 79,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 27,
    "displayName": "Tom Greyhound",
    "taxRefundAvailable": true,
    "sourceScreenshot": "5647E745-89B4-492F-BD0D-634E73D15927.png",
    "canonicalBrandId": "tom-greyhound"
  },
  {
    "sequence": 80,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 28,
    "displayName": "VANESSABRUNO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "5647E745-89B4-492F-BD0D-634E73D15927.png",
    "canonicalBrandId": "vanessa-bruno"
  },
  {
    "sequence": 81,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 29,
    "displayName": "WOOYOUNGMI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "5647E745-89B4-492F-BD0D-634E73D15927.png",
    "canonicalBrandId": "wooyoungmi"
  },
  {
    "sequence": 82,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 30,
    "displayName": "SANDRO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7FF38560-4F92-4664-8182-B1E269CDB001.png",
    "canonicalBrandId": "sandro"
  },
  {
    "sequence": 83,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 31,
    "displayName": "SECOND RUN",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7FF38560-4F92-4664-8182-B1E269CDB001.png",
    "canonicalBrandId": "second-run"
  },
  {
    "sequence": 84,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 32,
    "displayName": "SHINSEGAE FACTORY STORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7FF38560-4F92-4664-8182-B1E269CDB001.png",
    "canonicalBrandId": "shinsegae-factory-store"
  },
  {
    "sequence": 85,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 33,
    "displayName": "THEORY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7FF38560-4F92-4664-8182-B1E269CDB001.png",
    "canonicalBrandId": "theory"
  },
  {
    "sequence": 86,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 34,
    "displayName": "TIME",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7FF38560-4F92-4664-8182-B1E269CDB001.png",
    "canonicalBrandId": "time"
  },
  {
    "sequence": 87,
    "category": "Contemporary",
    "categoryOrder": 2,
    "categorySequence": 35,
    "displayName": "ZADIG & VOLTAIRE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "36858712-A347-43E4-B39D-742F07735CE3.png",
    "canonicalBrandId": "zadig-and-voltaire"
  },
  {
    "sequence": 88,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 1,
    "displayName": "BENETTON",
    "taxRefundAvailable": true,
    "sourceScreenshot": "36858712-A347-43E4-B39D-742F07735CE3.png",
    "canonicalBrandId": "benetton"
  },
  {
    "sequence": 89,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 2,
    "displayName": "Bean Pole",
    "taxRefundAvailable": true,
    "sourceScreenshot": "36858712-A347-43E4-B39D-742F07735CE3.png",
    "canonicalBrandId": "beanpole"
  },
  {
    "sequence": 90,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 3,
    "displayName": "Brooks Brothers",
    "taxRefundAvailable": true,
    "sourceScreenshot": "36858712-A347-43E4-B39D-742F07735CE3.png",
    "canonicalBrandId": "brooks-brothers"
  },
  {
    "sequence": 91,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 4,
    "displayName": "DEWL",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C8973D37-1A80-4456-BB7E-4C471086FCB5.png",
    "canonicalBrandId": "dewl"
  },
  {
    "sequence": 92,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 5,
    "displayName": "Daks",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C8973D37-1A80-4456-BB7E-4C471086FCB5.png",
    "canonicalBrandId": "daks"
  },
  {
    "sequence": 93,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 6,
    "displayName": "EGOIST",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C8973D37-1A80-4456-BB7E-4C471086FCB5.png",
    "canonicalBrandId": "egoist"
  },
  {
    "sequence": 94,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 7,
    "displayName": "FROOPS(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C8973D37-1A80-4456-BB7E-4C471086FCB5.png",
    "canonicalBrandId": "froops",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 95,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 8,
    "displayName": "Hazzys",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F293D5F1-D30D-4330-B410-44BA3849A634.png",
    "canonicalBrandId": "hazzys"
  },
  {
    "sequence": 96,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 9,
    "displayName": "IZZAT BABA / IZZAT COLLECTION",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F293D5F1-D30D-4330-B410-44BA3849A634.png",
    "canonicalBrandId": "izzat-baba-izzat-collection",
    "note": "One combined directory row."
  },
  {
    "sequence": 97,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 10,
    "displayName": "JIGOTT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F293D5F1-D30D-4330-B410-44BA3849A634.png",
    "canonicalBrandId": "jigott"
  },
  {
    "sequence": 98,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 11,
    "displayName": "Juun.J Woman",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F293D5F1-D30D-4330-B410-44BA3849A634.png",
    "canonicalBrandId": "juun-j-woman"
  },
  {
    "sequence": 99,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 12,
    "displayName": "LUCKY CHOUETTE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F293D5F1-D30D-4330-B410-44BA3849A634.png",
    "canonicalBrandId": "lucky-chouette"
  },
  {
    "sequence": 100,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 13,
    "displayName": "Lacoste",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4059D0F2-493F-4597-8CC4-9D8C5893BE67.png",
    "canonicalBrandId": "lacoste"
  },
  {
    "sequence": 101,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 14,
    "displayName": "Le17septembre",
    "taxRefundAvailable": false,
    "sourceScreenshot": "4059D0F2-493F-4597-8CC4-9D8C5893BE67.png",
    "canonicalBrandId": "le17septembre",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 102,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 15,
    "displayName": "MICHAA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4059D0F2-493F-4597-8CC4-9D8C5893BE67.png",
    "canonicalBrandId": "michaa"
  },
  {
    "sequence": 103,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 16,
    "displayName": "MOJO.S.PHINE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4059D0F2-493F-4597-8CC4-9D8C5893BE67.png",
    "canonicalBrandId": "mojo-s-phine"
  },
  {
    "sequence": 104,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 17,
    "displayName": "Marithe Francois Girbaud(P)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7F2F537B-629F-432E-B80B-4BE9B661316B.png",
    "canonicalBrandId": "marithe-francois-girbaud",
    "note": "(P) scope marker preserved."
  },
  {
    "sequence": 105,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 18,
    "displayName": "Polo Ralph Lauren",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7F2F537B-629F-432E-B80B-4BE9B661316B.png",
    "canonicalBrandId": "polo-ralph-lauren"
  },
  {
    "sequence": 106,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 19,
    "displayName": "RECTO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7F2F537B-629F-432E-B80B-4BE9B661316B.png",
    "canonicalBrandId": "recto"
  },
  {
    "sequence": 107,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 20,
    "displayName": "SATUR",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7F2F537B-629F-432E-B80B-4BE9B661316B.png",
    "canonicalBrandId": "satur"
  },
  {
    "sequence": 108,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 21,
    "displayName": "SJSJ",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7F2F537B-629F-432E-B80B-4BE9B661316B.png",
    "canonicalBrandId": "sjsj"
  },
  {
    "sequence": 109,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 22,
    "displayName": "STUDIO TOMBOY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "0E2DDB4E-5875-4FA2-B13A-80AF37EF992D.png",
    "canonicalBrandId": "studio-tomboy"
  },
  {
    "sequence": 110,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 23,
    "displayName": "SYSTEM",
    "taxRefundAvailable": true,
    "sourceScreenshot": "0E2DDB4E-5875-4FA2-B13A-80AF37EF992D.png",
    "canonicalBrandId": "system"
  },
  {
    "sequence": 111,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 24,
    "displayName": "TOMMY HILFIGER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "0E2DDB4E-5875-4FA2-B13A-80AF37EF992D.png",
    "canonicalBrandId": "tommy-hilfiger"
  },
  {
    "sequence": 112,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 25,
    "displayName": "Thursday Island",
    "taxRefundAvailable": true,
    "sourceScreenshot": "0E2DDB4E-5875-4FA2-B13A-80AF37EF992D.png",
    "canonicalBrandId": "thursday-island"
  },
  {
    "sequence": 113,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 26,
    "displayName": "VOV",
    "taxRefundAvailable": true,
    "sourceScreenshot": "0E2DDB4E-5875-4FA2-B13A-80AF37EF992D.png",
    "canonicalBrandId": "vov"
  },
  {
    "sequence": 114,
    "category": "Women’s Fashion",
    "categoryOrder": 3,
    "categorySequence": 27,
    "displayName": "ZOOC",
    "taxRefundAvailable": true,
    "sourceScreenshot": "986F8F85-6B50-41C3-B5CF-B3DC2D8FBBFF.png",
    "canonicalBrandId": "zooc"
  },
  {
    "sequence": 115,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 1,
    "displayName": "Allegri",
    "taxRefundAvailable": true,
    "sourceScreenshot": "986F8F85-6B50-41C3-B5CF-B3DC2D8FBBFF.png",
    "canonicalBrandId": "allegri"
  },
  {
    "sequence": 116,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 2,
    "displayName": "Bean Pole",
    "taxRefundAvailable": true,
    "sourceScreenshot": "986F8F85-6B50-41C3-B5CF-B3DC2D8FBBFF.png",
    "canonicalBrandId": "beanpole"
  },
  {
    "sequence": 117,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 3,
    "displayName": "Brooks Brothers",
    "taxRefundAvailable": true,
    "sourceScreenshot": "986F8F85-6B50-41C3-B5CF-B3DC2D8FBBFF.png",
    "canonicalBrandId": "brooks-brothers"
  },
  {
    "sequence": 118,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 4,
    "displayName": "CAMBRIDGE MEMBERS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6BA62E87-025B-44C6-88EB-CCF45855A86B.png",
    "canonicalBrandId": "cambridge-members"
  },
  {
    "sequence": 119,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 5,
    "displayName": "CUSTOMELLOW",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6BA62E87-025B-44C6-88EB-CCF45855A86B.png",
    "canonicalBrandId": "customellow"
  },
  {
    "sequence": 120,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 6,
    "displayName": "Daks",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85B07E84-7801-4F9B-A9DF-59C7F78B7955.png",
    "canonicalBrandId": "daks"
  },
  {
    "sequence": 121,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 7,
    "displayName": "GALAXY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85B07E84-7801-4F9B-A9DF-59C7F78B7955.png",
    "canonicalBrandId": "galaxy"
  },
  {
    "sequence": 122,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 8,
    "displayName": "Hazzys",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85B07E84-7801-4F9B-A9DF-59C7F78B7955.png",
    "canonicalBrandId": "hazzys"
  },
  {
    "sequence": 123,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 9,
    "displayName": "Henry Cotton",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85B07E84-7801-4F9B-A9DF-59C7F78B7955.png",
    "canonicalBrandId": "henry-cotton"
  },
  {
    "sequence": 124,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 10,
    "displayName": "Lacoste",
    "taxRefundAvailable": true,
    "sourceScreenshot": "85B07E84-7801-4F9B-A9DF-59C7F78B7955.png",
    "canonicalBrandId": "lacoste"
  },
  {
    "sequence": 125,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 11,
    "displayName": "POTTERY",
    "taxRefundAvailable": false,
    "sourceScreenshot": "4662258F-8C90-4BF0-B76E-7F182F4B7A02.png",
    "canonicalBrandId": "pottery",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 126,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 12,
    "displayName": "Polo Ralph Lauren",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4662258F-8C90-4BF0-B76E-7F182F4B7A02.png",
    "canonicalBrandId": "polo-ralph-lauren"
  },
  {
    "sequence": 127,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 13,
    "displayName": "RECTO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4662258F-8C90-4BF0-B76E-7F182F4B7A02.png",
    "canonicalBrandId": "recto"
  },
  {
    "sequence": 128,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 14,
    "displayName": "SERIES",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4662258F-8C90-4BF0-B76E-7F182F4B7A02.png",
    "canonicalBrandId": "series"
  },
  {
    "sequence": 129,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 15,
    "displayName": "SOLID HOMME",
    "taxRefundAvailable": true,
    "sourceScreenshot": "4662258F-8C90-4BF0-B76E-7F182F4B7A02.png",
    "canonicalBrandId": "solid-homme"
  },
  {
    "sequence": 130,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 16,
    "displayName": "SONGZIO HOMME",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C315EC41-CEE3-40A9-9F93-F316B9555805.png",
    "canonicalBrandId": "songzio-homme"
  },
  {
    "sequence": 131,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 17,
    "displayName": "SYSTEM HOMME",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C315EC41-CEE3-40A9-9F93-F316B9555805.png",
    "canonicalBrandId": "system-homme"
  },
  {
    "sequence": 132,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 18,
    "displayName": "Sieg",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C315EC41-CEE3-40A9-9F93-F316B9555805.png",
    "canonicalBrandId": "sieg"
  },
  {
    "sequence": 133,
    "category": "Men’s Fashion",
    "categoryOrder": 4,
    "categorySequence": 19,
    "displayName": "TOMMY HILFIGER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C315EC41-CEE3-40A9-9F93-F316B9555805.png",
    "canonicalBrandId": "tommy-hilfiger"
  },
  {
    "sequence": 134,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 1,
    "displayName": "Calvin Klein Jeans/Underwear",
    "taxRefundAvailable": true,
    "sourceScreenshot": "336E97AF-CCDB-4918-A37F-647FE4C6FA68.png",
    "canonicalBrandId": "calvin-klein"
  },
  {
    "sequence": 135,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 2,
    "displayName": "GIORDANO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "336E97AF-CCDB-4918-A37F-647FE4C6FA68.png",
    "canonicalBrandId": "giordano"
  },
  {
    "sequence": 136,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 3,
    "displayName": "Guess",
    "taxRefundAvailable": true,
    "sourceScreenshot": "336E97AF-CCDB-4918-A37F-647FE4C6FA68.png",
    "canonicalBrandId": "guess"
  },
  {
    "sequence": 137,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 4,
    "displayName": "LEVI’S",
    "taxRefundAvailable": true,
    "sourceScreenshot": "336E97AF-CCDB-4918-A37F-647FE4C6FA68.png",
    "canonicalBrandId": "levis"
  },
  {
    "sequence": 138,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 5,
    "displayName": "LifeWork",
    "taxRefundAvailable": true,
    "sourceScreenshot": "57F392D4-9DD2-45D1-8665-CD64F516498A.png",
    "canonicalBrandId": "lifework"
  },
  {
    "sequence": 139,
    "category": "Jean & Casual & SPA",
    "categoryOrder": 5,
    "categorySequence": 6,
    "displayName": "ONITSUKA TIGER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "57F392D4-9DD2-45D1-8665-CD64F516498A.png",
    "canonicalBrandId": "onitsuka-tiger"
  },
  {
    "sequence": 140,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 1,
    "displayName": "Camper",
    "taxRefundAvailable": true,
    "sourceScreenshot": "57F392D4-9DD2-45D1-8665-CD64F516498A.png",
    "canonicalBrandId": "camper"
  },
  {
    "sequence": 141,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 2,
    "displayName": "Couronne",
    "taxRefundAvailable": true,
    "sourceScreenshot": "57F392D4-9DD2-45D1-8665-CD64F516498A.png",
    "canonicalBrandId": "couronne"
  },
  {
    "sequence": 142,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 3,
    "displayName": "Crocs",
    "taxRefundAvailable": true,
    "sourceScreenshot": "16D0C2A6-9040-407D-B101-74EE81EA566B.png",
    "canonicalBrandId": "crocs"
  },
  {
    "sequence": 143,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 4,
    "displayName": "Daks Acc",
    "taxRefundAvailable": true,
    "sourceScreenshot": "16D0C2A6-9040-407D-B101-74EE81EA566B.png",
    "canonicalBrandId": "daks"
  },
  {
    "sequence": 144,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 5,
    "displayName": "Ecco",
    "taxRefundAvailable": true,
    "sourceScreenshot": "16D0C2A6-9040-407D-B101-74EE81EA566B.png",
    "canonicalBrandId": "ecco"
  },
  {
    "sequence": 145,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 6,
    "displayName": "Helen Kaminski",
    "taxRefundAvailable": true,
    "sourceScreenshot": "16D0C2A6-9040-407D-B101-74EE81EA566B.png",
    "canonicalBrandId": "helen-kaminski"
  },
  {
    "sequence": 146,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 7,
    "displayName": "Heritage Kumkang",
    "taxRefundAvailable": true,
    "sourceScreenshot": "16D0C2A6-9040-407D-B101-74EE81EA566B.png",
    "canonicalBrandId": "heritage-kumkang",
    "note": "Badge was cropped in the supplied screenshot; TAX REFUND was verified on the official Yeoju directory."
  },
  {
    "sequence": 147,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 8,
    "displayName": "Joy Gryson",
    "taxRefundAvailable": true,
    "sourceScreenshot": "11D99151-8F6E-4B7B-8D73-EC0CF192E339.png",
    "canonicalBrandId": "joy-gryson"
  },
  {
    "sequence": 148,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 9,
    "displayName": "LOUIS QUATORZE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "11D99151-8F6E-4B7B-8D73-EC0CF192E339.png",
    "canonicalBrandId": "louis-quatorze"
  },
  {
    "sequence": 149,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 10,
    "displayName": "MANDARINA DUCK",
    "taxRefundAvailable": true,
    "sourceScreenshot": "11D99151-8F6E-4B7B-8D73-EC0CF192E339.png",
    "canonicalBrandId": "mandarina-duck"
  },
  {
    "sequence": 150,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 11,
    "displayName": "Misope",
    "taxRefundAvailable": true,
    "sourceScreenshot": "11D99151-8F6E-4B7B-8D73-EC0CF192E339.png",
    "canonicalBrandId": "misope"
  },
  {
    "sequence": 151,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 12,
    "displayName": "Rockport",
    "taxRefundAvailable": true,
    "sourceScreenshot": "AB44B403-2796-402C-9AFD-E88453EA3B93.png",
    "canonicalBrandId": "rockport"
  },
  {
    "sequence": 152,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 13,
    "displayName": "SAMSONITE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "AB44B403-2796-402C-9AFD-E88453EA3B93.png",
    "canonicalBrandId": "samsonite"
  },
  {
    "sequence": 153,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 14,
    "displayName": "Suecomma Bonnie",
    "taxRefundAvailable": true,
    "sourceScreenshot": "AB44B403-2796-402C-9AFD-E88453EA3B93.png",
    "canonicalBrandId": "suecomma-bonnie"
  },
  {
    "sequence": 154,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 15,
    "displayName": "Tandy",
    "taxRefundAvailable": true,
    "sourceScreenshot": "AB44B403-2796-402C-9AFD-E88453EA3B93.png",
    "canonicalBrandId": "tandy"
  },
  {
    "sequence": 155,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 16,
    "displayName": "UGG",
    "taxRefundAvailable": true,
    "sourceScreenshot": "AB44B403-2796-402C-9AFD-E88453EA3B93.png",
    "canonicalBrandId": "ugg"
  },
  {
    "sequence": 156,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 17,
    "displayName": "VANS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6DBA8C18-CA43-4151-83F5-E751F171EAE4.png",
    "canonicalBrandId": "vans"
  },
  {
    "sequence": 157,
    "category": "Shoes & Bags",
    "categoryOrder": 6,
    "categorySequence": 18,
    "displayName": "vunque",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6DBA8C18-CA43-4151-83F5-E751F171EAE4.png",
    "canonicalBrandId": "vunque"
  },
  {
    "sequence": 158,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 1,
    "displayName": "A.P.C. GOLF",
    "taxRefundAvailable": true,
    "sourceScreenshot": "6DBA8C18-CA43-4151-83F5-E751F171EAE4.png",
    "canonicalBrandId": "a-p-c-golf"
  },
  {
    "sequence": 159,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 2,
    "displayName": "ANEWGOLF",
    "taxRefundAvailable": true,
    "sourceScreenshot": "2F0028A0-CCB6-4B5F-910D-0819C1547487.png",
    "canonicalBrandId": "anewgolf"
  },
  {
    "sequence": 160,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 3,
    "displayName": "Adidas",
    "taxRefundAvailable": true,
    "sourceScreenshot": "2F0028A0-CCB6-4B5F-910D-0819C1547487.png",
    "canonicalBrandId": "adidas"
  },
  {
    "sequence": 161,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 4,
    "displayName": "AmazingCre",
    "taxRefundAvailable": true,
    "sourceScreenshot": "2F0028A0-CCB6-4B5F-910D-0819C1547487.png",
    "canonicalBrandId": "amazingcre"
  },
  {
    "sequence": 162,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 5,
    "displayName": "BLACKYAK",
    "taxRefundAvailable": true,
    "sourceScreenshot": "2F0028A0-CCB6-4B5F-910D-0819C1547487.png",
    "canonicalBrandId": "black-yak"
  },
  {
    "sequence": 163,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 6,
    "displayName": "Boss Golf",
    "taxRefundAvailable": true,
    "sourceScreenshot": "2F0028A0-CCB6-4B5F-910D-0819C1547487.png",
    "canonicalBrandId": "boss-golf"
  },
  {
    "sequence": 164,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 7,
    "displayName": "CHERVO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F961339A-8CDD-43B4-8E64-06F8A8878710.png",
    "canonicalBrandId": "chervo"
  },
  {
    "sequence": 165,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 8,
    "displayName": "COLUMBIA SPORTSWEAR",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F961339A-8CDD-43B4-8E64-06F8A8878710.png",
    "canonicalBrandId": "columbia"
  },
  {
    "sequence": 166,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 9,
    "displayName": "Callaway Golf",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F961339A-8CDD-43B4-8E64-06F8A8878710.png",
    "canonicalBrandId": "callaway-golf"
  },
  {
    "sequence": 167,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 10,
    "displayName": "Challenger",
    "taxRefundAvailable": false,
    "sourceScreenshot": "F961339A-8CDD-43B4-8E64-06F8A8878710.png",
    "canonicalBrandId": "challenger",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 168,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 11,
    "displayName": "DESCENTE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F961339A-8CDD-43B4-8E64-06F8A8878710.png",
    "canonicalBrandId": "descente"
  },
  {
    "sequence": 169,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 12,
    "displayName": "DESCENTE GOLF",
    "taxRefundAvailable": true,
    "sourceScreenshot": "228F81D3-44FE-4287-92B8-4036DBCB344B.png",
    "canonicalBrandId": "descente-golf"
  },
  {
    "sequence": 170,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 13,
    "displayName": "DISCOVERY",
    "taxRefundAvailable": true,
    "sourceScreenshot": "228F81D3-44FE-4287-92B8-4036DBCB344B.png",
    "canonicalBrandId": "discovery"
  },
  {
    "sequence": 171,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 14,
    "displayName": "DUNLOP",
    "taxRefundAvailable": true,
    "sourceScreenshot": "228F81D3-44FE-4287-92B8-4036DBCB344B.png",
    "canonicalBrandId": "dunlop"
  },
  {
    "sequence": 172,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 15,
    "displayName": "Dynafit(pes)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "228F81D3-44FE-4287-92B8-4036DBCB344B.png",
    "canonicalBrandId": "dynafit",
    "note": "(pes) scope marker preserved."
  },
  {
    "sequence": 173,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 16,
    "displayName": "EIDER",
    "taxRefundAvailable": true,
    "sourceScreenshot": "228F81D3-44FE-4287-92B8-4036DBCB344B.png",
    "canonicalBrandId": "eider"
  },
  {
    "sequence": 174,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 17,
    "displayName": "G/FORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "BDC2303D-D0B5-4418-ABCB-1DDFC24CE9ED.png",
    "canonicalBrandId": "g-fore"
  },
  {
    "sequence": 175,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 18,
    "displayName": "Helinox",
    "taxRefundAvailable": false,
    "sourceScreenshot": "BDC2303D-D0B5-4418-ABCB-1DDFC24CE9ED.png",
    "canonicalBrandId": "helinox",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 176,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 19,
    "displayName": "Hoka(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "BDC2303D-D0B5-4418-ABCB-1DDFC24CE9ED.png",
    "canonicalBrandId": "hoka",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 177,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 20,
    "displayName": "J.LINDEBERG",
    "taxRefundAvailable": true,
    "sourceScreenshot": "BDC2303D-D0B5-4418-ABCB-1DDFC24CE9ED.png",
    "canonicalBrandId": "j-lindeberg"
  },
  {
    "sequence": 178,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 21,
    "displayName": "K2",
    "taxRefundAvailable": true,
    "sourceScreenshot": "BDC2303D-D0B5-4418-ABCB-1DDFC24CE9ED.png",
    "canonicalBrandId": "k2"
  },
  {
    "sequence": 179,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 22,
    "displayName": "KOLON SPORT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F57E38F9-D8EC-4EFE-8A07-5A1D7352E0F8.png",
    "canonicalBrandId": "kolon-sport"
  },
  {
    "sequence": 180,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 23,
    "displayName": "LE COQ SPORTIF",
    "taxRefundAvailable": false,
    "sourceScreenshot": "F57E38F9-D8EC-4EFE-8A07-5A1D7352E0F8.png",
    "canonicalBrandId": "le-coq-sportif",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 181,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 24,
    "displayName": "LULULEMON",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F57E38F9-D8EC-4EFE-8A07-5A1D7352E0F8.png",
    "canonicalBrandId": "lululemon"
  },
  {
    "sequence": 182,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 25,
    "displayName": "Lanvin Blanc(P)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F57E38F9-D8EC-4EFE-8A07-5A1D7352E0F8.png",
    "canonicalBrandId": "lanvin-blanc",
    "note": "(P) scope marker preserved."
  },
  {
    "sequence": 183,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 26,
    "displayName": "MALBON GOLF",
    "taxRefundAvailable": true,
    "sourceScreenshot": "F57E38F9-D8EC-4EFE-8A07-5A1D7352E0F8.png",
    "canonicalBrandId": "malbon-golf"
  },
  {
    "sequence": 184,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 27,
    "displayName": "MARK&LONA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C212D6B4-0D05-4E17-AB5B-999B51159BC3.png",
    "canonicalBrandId": "mark-and-lona"
  },
  {
    "sequence": 185,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 28,
    "displayName": "MLB",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C212D6B4-0D05-4E17-AB5B-999B51159BC3.png",
    "canonicalBrandId": "mlb-korea"
  },
  {
    "sequence": 186,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 29,
    "displayName": "Masterbunny",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C212D6B4-0D05-4E17-AB5B-999B51159BC3.png",
    "canonicalBrandId": "master-bunny-edition"
  },
  {
    "sequence": 187,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 30,
    "displayName": "NEW BALANCE",
    "taxRefundAvailable": false,
    "sourceScreenshot": "C212D6B4-0D05-4E17-AB5B-999B51159BC3.png",
    "canonicalBrandId": "new-balance",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 188,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 31,
    "displayName": "NEW ERA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "C212D6B4-0D05-4E17-AB5B-999B51159BC3.png",
    "canonicalBrandId": "new-era"
  },
  {
    "sequence": 189,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 32,
    "displayName": "NIKE FACTORY STORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A9F75516-8DB8-4426-A46E-719C2BEF6692.png",
    "canonicalBrandId": "nike"
  },
  {
    "sequence": 190,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 33,
    "displayName": "NIKE GOLF",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A9F75516-8DB8-4426-A46E-719C2BEF6692.png",
    "canonicalBrandId": "nike-golf"
  },
  {
    "sequence": 191,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 34,
    "displayName": "National Geographic",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A9F75516-8DB8-4426-A46E-719C2BEF6692.png",
    "canonicalBrandId": "national-geographic-apparel"
  },
  {
    "sequence": 192,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 35,
    "displayName": "OFF/OUT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A9F75516-8DB8-4426-A46E-719C2BEF6692.png",
    "canonicalBrandId": "off-out"
  },
  {
    "sequence": 193,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 36,
    "displayName": "PATAGONIA",
    "taxRefundAvailable": true,
    "sourceScreenshot": "A9F75516-8DB8-4426-A46E-719C2BEF6692.png",
    "canonicalBrandId": "patagonia"
  },
  {
    "sequence": 194,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 37,
    "displayName": "PXG",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DBC5B33F-B28B-4897-943E-25EF940B9193.png",
    "canonicalBrandId": "pxg"
  },
  {
    "sequence": 195,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 38,
    "displayName": "Pearly Gates",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DBC5B33F-B28B-4897-943E-25EF940B9193.png",
    "canonicalBrandId": "pearly-gates"
  },
  {
    "sequence": 196,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 39,
    "displayName": "SALOMON",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DBC5B33F-B28B-4897-943E-25EF940B9193.png",
    "canonicalBrandId": "salomon"
  },
  {
    "sequence": 197,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 40,
    "displayName": "SOUTHCAPE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DBC5B33F-B28B-4897-943E-25EF940B9193.png",
    "canonicalBrandId": "southcape"
  },
  {
    "sequence": 198,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 41,
    "displayName": "ST ANDREWS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "DBC5B33F-B28B-4897-943E-25EF940B9193.png",
    "canonicalBrandId": "st-andrews"
  },
  {
    "sequence": 199,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 42,
    "displayName": "Snow peak(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9B538292-784D-48A1-8AFD-06861EC9C904.png",
    "canonicalBrandId": "snow-peak",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 200,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 43,
    "displayName": "THE NORTH FACE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9B538292-784D-48A1-8AFD-06861EC9C904.png",
    "canonicalBrandId": "the-north-face"
  },
  {
    "sequence": 201,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 44,
    "displayName": "Titleist",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9B538292-784D-48A1-8AFD-06861EC9C904.png",
    "canonicalBrandId": "titleist"
  },
  {
    "sequence": 202,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 45,
    "displayName": "Umbro(PES)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9B538292-784D-48A1-8AFD-06861EC9C904.png",
    "canonicalBrandId": "umbro",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 203,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 46,
    "displayName": "Under armour",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9B538292-784D-48A1-8AFD-06861EC9C904.png",
    "canonicalBrandId": "under-armour"
  },
  {
    "sequence": 204,
    "category": "Sports & Golf & Outdoor",
    "categoryOrder": 7,
    "categorySequence": 47,
    "displayName": "WAAC",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9746F9BB-78F2-4FD5-9432-52A45055D9C7.png",
    "canonicalBrandId": "waac"
  },
  {
    "sequence": 205,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 1,
    "displayName": "BARBARA/VIVIEN",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9746F9BB-78F2-4FD5-9432-52A45055D9C7.png",
    "canonicalBrandId": "barbara-vivien"
  },
  {
    "sequence": 206,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 2,
    "displayName": "Babara",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9746F9BB-78F2-4FD5-9432-52A45055D9C7.png",
    "canonicalBrandId": "babara",
    "note": "Official display spelling preserved."
  },
  {
    "sequence": 207,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 3,
    "displayName": "Foot Joy",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9746F9BB-78F2-4FD5-9432-52A45055D9C7.png",
    "canonicalBrandId": "footjoy"
  },
  {
    "sequence": 208,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 4,
    "displayName": "Golden Dew",
    "taxRefundAvailable": true,
    "sourceScreenshot": "19F7FA2B-BF96-4869-A091-D7FF2A9E6B17.png",
    "canonicalBrandId": "golden-dew"
  },
  {
    "sequence": 209,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 5,
    "displayName": "Helen Kaminski",
    "taxRefundAvailable": true,
    "sourceScreenshot": "19F7FA2B-BF96-4869-A091-D7FF2A9E6B17.png",
    "canonicalBrandId": "helen-kaminski"
  },
  {
    "sequence": 210,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 6,
    "displayName": "Hunter",
    "taxRefundAvailable": true,
    "sourceScreenshot": "19F7FA2B-BF96-4869-A091-D7FF2A9E6B17.png",
    "canonicalBrandId": "hunter"
  },
  {
    "sequence": 211,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 7,
    "displayName": "L'OCCITANE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "19F7FA2B-BF96-4869-A091-D7FF2A9E6B17.png",
    "canonicalBrandId": "l-occitane"
  },
  {
    "sequence": 212,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 8,
    "displayName": "Rayban",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1D1D24D2-0D96-4AA4-B429-44F7B2F1B7C2.png",
    "canonicalBrandId": "ray-ban"
  },
  {
    "sequence": 213,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 9,
    "displayName": "Rockport",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1D1D24D2-0D96-4AA4-B429-44F7B2F1B7C2.png",
    "canonicalBrandId": "rockport"
  },
  {
    "sequence": 214,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 10,
    "displayName": "RoseeDor",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1D1D24D2-0D96-4AA4-B429-44F7B2F1B7C2.png",
    "canonicalBrandId": "roseedor"
  },
  {
    "sequence": 215,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 11,
    "displayName": "S.I Beauty Club",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1D1D24D2-0D96-4AA4-B429-44F7B2F1B7C2.png",
    "canonicalBrandId": "s-i-beauty-club"
  },
  {
    "sequence": 216,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 12,
    "displayName": "SWAROVSKI",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1D1D24D2-0D96-4AA4-B429-44F7B2F1B7C2.png",
    "canonicalBrandId": "swarovski"
  },
  {
    "sequence": 217,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 13,
    "displayName": "Soda",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9D366ACF-1A40-4846-AC93-509E36CE0BB1.png",
    "canonicalBrandId": "soda"
  },
  {
    "sequence": 218,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 14,
    "displayName": "THE COSMETICS CLUB",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9D366ACF-1A40-4846-AC93-509E36CE0BB1.png",
    "canonicalBrandId": "the-cosmetics-club"
  },
  {
    "sequence": 219,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 15,
    "displayName": "THE COSMETICS COMPANY STORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9D366ACF-1A40-4846-AC93-509E36CE0BB1.png",
    "canonicalBrandId": "the-cosmetics-company-store"
  },
  {
    "sequence": 220,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 16,
    "displayName": "Triumph/Elle(pes)",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9D366ACF-1A40-4846-AC93-509E36CE0BB1.png",
    "canonicalBrandId": "triumph-elle",
    "note": "(pes) scope marker preserved."
  },
  {
    "sequence": 221,
    "category": "Accessories",
    "categoryOrder": 8,
    "categorySequence": 17,
    "displayName": "Venus/Wacoal",
    "taxRefundAvailable": true,
    "sourceScreenshot": "9D366ACF-1A40-4846-AC93-509E36CE0BB1.png",
    "canonicalBrandId": "venus-wacoal"
  },
  {
    "sequence": 222,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 1,
    "displayName": "BONPOINT",
    "taxRefundAvailable": true,
    "sourceScreenshot": "45E7FAEA-DAB1-4CFD-AB28-489411AA625D.png",
    "canonicalBrandId": "bonpoint"
  },
  {
    "sequence": 223,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 2,
    "displayName": "Burberry Children",
    "taxRefundAvailable": true,
    "sourceScreenshot": "45E7FAEA-DAB1-4CFD-AB28-489411AA625D.png",
    "canonicalBrandId": "burberry-children"
  },
  {
    "sequence": 224,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 3,
    "displayName": "Happyland House",
    "taxRefundAvailable": false,
    "sourceScreenshot": "45E7FAEA-DAB1-4CFD-AB28-489411AA625D.png",
    "canonicalBrandId": "happyland-house",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 225,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 4,
    "displayName": "Haribo Store",
    "taxRefundAvailable": false,
    "sourceScreenshot": "45E7FAEA-DAB1-4CFD-AB28-489411AA625D.png",
    "canonicalBrandId": "haribo",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 226,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 5,
    "displayName": "KANGOL KIDS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "45E7FAEA-DAB1-4CFD-AB28-489411AA625D.png",
    "canonicalBrandId": "kangol-kids"
  },
  {
    "sequence": 227,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 6,
    "displayName": "KENZO KIDS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "813D1F8D-3A9A-4DCA-B303-AB6262E7C480.png",
    "canonicalBrandId": "kenzo-kids"
  },
  {
    "sequence": 228,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 7,
    "displayName": "LEGO",
    "taxRefundAvailable": true,
    "sourceScreenshot": "813D1F8D-3A9A-4DCA-B303-AB6262E7C480.png",
    "canonicalBrandId": "lego"
  },
  {
    "sequence": 229,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 8,
    "displayName": "Lee Kids(P)",
    "taxRefundAvailable": false,
    "sourceScreenshot": "813D1F8D-3A9A-4DCA-B303-AB6262E7C480.png",
    "canonicalBrandId": "lee-kids",
    "note": "No TAX REFUND badge is shown; (P) scope marker preserved."
  },
  {
    "sequence": 230,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 9,
    "displayName": "Little Ground",
    "taxRefundAvailable": true,
    "sourceScreenshot": "813D1F8D-3A9A-4DCA-B303-AB6262E7C480.png",
    "canonicalBrandId": "little-ground"
  },
  {
    "sequence": 231,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 10,
    "displayName": "MAGIC EDITION",
    "taxRefundAvailable": true,
    "sourceScreenshot": "813D1F8D-3A9A-4DCA-B303-AB6262E7C480.png",
    "canonicalBrandId": "magic-edition"
  },
  {
    "sequence": 232,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 11,
    "displayName": "Marithe Kids",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7C647150-4B6A-4EF6-A822-7C771AD35082.png",
    "canonicalBrandId": "marithe-kids"
  },
  {
    "sequence": 233,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 12,
    "displayName": "NATIONAL GEOGRAPHIC KIDS",
    "taxRefundAvailable": true,
    "sourceScreenshot": "7C647150-4B6A-4EF6-A822-7C771AD35082.png",
    "canonicalBrandId": "national-geographic-kids"
  },
  {
    "sequence": 234,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 13,
    "displayName": "NBA Kids",
    "taxRefundAvailable": false,
    "sourceScreenshot": "7C647150-4B6A-4EF6-A822-7C771AD35082.png",
    "canonicalBrandId": "nba-kids",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 235,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 14,
    "displayName": "NEPA KIDS",
    "taxRefundAvailable": false,
    "sourceScreenshot": "7C647150-4B6A-4EF6-A822-7C771AD35082.png",
    "canonicalBrandId": "nepa-kids",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 236,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 15,
    "displayName": "NEW BALANCE KIDS",
    "taxRefundAvailable": false,
    "sourceScreenshot": "7C647150-4B6A-4EF6-A822-7C771AD35082.png",
    "canonicalBrandId": "new-balance-kids",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 237,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 16,
    "displayName": "Nike Kids Value Store",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C273C93-F7A3-4AC1-9559-E55681A2C0C1.png",
    "canonicalBrandId": "nike-kids-value-store"
  },
  {
    "sequence": 238,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 17,
    "displayName": "Off Label",
    "taxRefundAvailable": true,
    "sourceScreenshot": "1C273C93-F7A3-4AC1-9559-E55681A2C0C1.png",
    "canonicalBrandId": "off-label"
  },
  {
    "sequence": 239,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 18,
    "displayName": "TOEBOX",
    "taxRefundAvailable": false,
    "sourceScreenshot": "1C273C93-F7A3-4AC1-9559-E55681A2C0C1.png",
    "canonicalBrandId": "toebox",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 240,
    "category": "Kids",
    "categoryOrder": 9,
    "categorySequence": 19,
    "displayName": "Top10 Kids",
    "taxRefundAvailable": false,
    "sourceScreenshot": "1C273C93-F7A3-4AC1-9559-E55681A2C0C1.png",
    "canonicalBrandId": "top10-kids",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 241,
    "category": "Living",
    "categoryOrder": 10,
    "categorySequence": 1,
    "displayName": "B&O/B&W",
    "taxRefundAvailable": false,
    "sourceScreenshot": "E38932F0-B496-4E2D-8D68-97EF67EB6106.png",
    "canonicalBrandId": "bang-and-olufsen-bowers-and-wilkins",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 242,
    "category": "Living",
    "categoryOrder": 10,
    "categorySequence": 2,
    "displayName": "JAJU",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E38932F0-B496-4E2D-8D68-97EF67EB6106.png",
    "canonicalBrandId": "jaju"
  },
  {
    "sequence": 243,
    "category": "Living",
    "categoryOrder": 10,
    "categorySequence": 3,
    "displayName": "WINE&MORE",
    "taxRefundAvailable": true,
    "sourceScreenshot": "E38932F0-B496-4E2D-8D68-97EF67EB6106.png",
    "canonicalBrandId": "wine-and-more"
  },
  {
    "sequence": 244,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 1,
    "displayName": "ART CENTUM(PES)",
    "taxRefundAvailable": false,
    "sourceScreenshot": "9DFDED95-1C4C-4959-8498-F1A10020D274.png",
    "canonicalBrandId": "art-centum",
    "note": "No TAX REFUND badge is shown; (PES) scope marker preserved."
  },
  {
    "sequence": 245,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 2,
    "displayName": "B&O/B&W",
    "taxRefundAvailable": false,
    "sourceScreenshot": "9DFDED95-1C4C-4959-8498-F1A10020D274.png",
    "canonicalBrandId": "bang-and-olufsen-bowers-and-wilkins",
    "note": "No TAX REFUND badge is shown on the captured row."
  },
  {
    "sequence": 246,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 3,
    "displayName": "Fannie",
    "taxRefundAvailable": false,
    "sourceScreenshot": "9DFDED95-1C4C-4959-8498-F1A10020D274.png",
    "canonicalBrandId": "fannie",
    "note": "Mixed-use Etc listing; no TAX REFUND badge shown."
  },
  {
    "sequence": 247,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 4,
    "displayName": "Five Guys",
    "taxRefundAvailable": false,
    "sourceScreenshot": "9DFDED95-1C4C-4959-8498-F1A10020D274.png",
    "canonicalBrandId": "five-guys",
    "note": "Dining entry appears in the mixed Etc category; not a complete F&B export."
  },
  {
    "sequence": 248,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 5,
    "displayName": "HANSUNG POP-UP (PES)",
    "taxRefundAvailable": false,
    "sourceScreenshot": "9DFDED95-1C4C-4959-8498-F1A10020D274.png",
    "canonicalBrandId": "hansung-pop-up",
    "note": "(PES) scope marker preserved."
  },
  {
    "sequence": 249,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 6,
    "displayName": "Hwasoon",
    "taxRefundAvailable": false,
    "sourceScreenshot": "ED90883F-7157-47A0-9E01-5790035FD8D3.png",
    "canonicalBrandId": "hwasoon",
    "note": "Dining-like entry in the mixed Etc category."
  },
  {
    "sequence": 250,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 7,
    "displayName": "Igane topokki",
    "taxRefundAvailable": false,
    "sourceScreenshot": "ED90883F-7157-47A0-9E01-5790035FD8D3.png",
    "canonicalBrandId": "igane-topokki",
    "note": "Dining entry in the mixed Etc category."
  },
  {
    "sequence": 251,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 8,
    "displayName": "Jackson",
    "taxRefundAvailable": false,
    "sourceScreenshot": "ED90883F-7157-47A0-9E01-5790035FD8D3.png",
    "canonicalBrandId": "jackson",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 252,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 9,
    "displayName": "Jung Kwan Jang",
    "taxRefundAvailable": false,
    "sourceScreenshot": "ED90883F-7157-47A0-9E01-5790035FD8D3.png",
    "canonicalBrandId": "jung-kwan-jang",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 253,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 10,
    "displayName": "Kary Market",
    "taxRefundAvailable": false,
    "sourceScreenshot": "ED90883F-7157-47A0-9E01-5790035FD8D3.png",
    "canonicalBrandId": "kary-market",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 254,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 11,
    "displayName": "Onsen",
    "taxRefundAvailable": false,
    "sourceScreenshot": "92DE697B-29AF-4BFE-80DC-DF710F3CF0E4.png",
    "canonicalBrandId": "onsen",
    "note": "Dining entry in the mixed Etc category."
  },
  {
    "sequence": 255,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 12,
    "displayName": "Palseonsaeng",
    "taxRefundAvailable": false,
    "sourceScreenshot": "92DE697B-29AF-4BFE-80DC-DF710F3CF0E4.png",
    "canonicalBrandId": "palseonsaeng",
    "note": "Dining entry in the mixed Etc category."
  },
  {
    "sequence": 256,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 13,
    "displayName": "Pizzeria O",
    "taxRefundAvailable": false,
    "sourceScreenshot": "92DE697B-29AF-4BFE-80DC-DF710F3CF0E4.png",
    "canonicalBrandId": "pizzeria-o",
    "note": "Dining entry in the mixed Etc category."
  },
  {
    "sequence": 257,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 14,
    "displayName": "Shinsegae Outlet",
    "taxRefundAvailable": false,
    "sourceScreenshot": "92DE697B-29AF-4BFE-80DC-DF710F3CF0E4.png",
    "canonicalBrandId": "shinsegae-outlet",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 258,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 15,
    "displayName": "Taco bell",
    "taxRefundAvailable": false,
    "sourceScreenshot": "92DE697B-29AF-4BFE-80DC-DF710F3CF0E4.png",
    "canonicalBrandId": "taco-bell",
    "note": "Dining entry in the mixed Etc category."
  },
  {
    "sequence": 259,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 16,
    "displayName": "Twitzel",
    "taxRefundAvailable": false,
    "sourceScreenshot": "57136CD6-99BC-4252-8B24-2204E8098433.png",
    "canonicalBrandId": "twitzel",
    "note": "Dining-like entry in the mixed Etc category."
  },
  {
    "sequence": 260,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 17,
    "displayName": "YEOJU CERAMICS",
    "taxRefundAvailable": false,
    "sourceScreenshot": "57136CD6-99BC-4252-8B24-2204E8098433.png",
    "canonicalBrandId": "yeoju-ceramics",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 261,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 18,
    "displayName": "YEOJU MARKET PLACE",
    "taxRefundAvailable": false,
    "sourceScreenshot": "57136CD6-99BC-4252-8B24-2204E8098433.png",
    "canonicalBrandId": "yeoju-market-place",
    "note": "Mixed-use Etc listing."
  },
  {
    "sequence": 262,
    "category": "Etc",
    "categoryOrder": 11,
    "categorySequence": 19,
    "displayName": "ililhyang",
    "taxRefundAvailable": false,
    "sourceScreenshot": "57136CD6-99BC-4252-8B24-2204E8098433.png",
    "canonicalBrandId": "ililhyang",
    "note": "Dining entry in the mixed Etc category."
  }
];
export const yeojuPremiumOutletsNewBrandIds = [
  "lansmere",
  "rick-owens",
  "beaker",
  "cp-company",
  "club-monaco",
  "lebeige",
  "man-on-the-boon",
  "mine",
  "mue",
  "matin-kim",
  "s-i-village",
  "tom-greyhound",
  "second-run",
  "shinsegae-factory-store",
  "time",
  "dewl",
  "daks",
  "froops",
  "izzat-baba-izzat-collection",
  "jigott",
  "juun-j-woman",
  "lucky-chouette",
  "le17septembre",
  "michaa",
  "mojo-s-phine",
  "satur",
  "sjsj",
  "studio-tomboy",
  "system",
  "thursday-island",
  "cambridge-members",
  "galaxy",
  "henry-cotton",
  "pottery",
  "series",
  "solid-homme",
  "songzio-homme",
  "sieg",
  "lifework",
  "helen-kaminski",
  "heritage-kumkang",
  "joy-gryson",
  "louis-quatorze",
  "misope",
  "suecomma-bonnie",
  "tandy",
  "vunque",
  "a-p-c-golf",
  "anewgolf",
  "amazingcre",
  "boss-golf",
  "chervo",
  "challenger",
  "discovery",
  "dunlop",
  "dynafit",
  "helinox",
  "lanvin-blanc",
  "off-out",
  "southcape",
  "st-andrews",
  "titleist",
  "barbara-vivien",
  "babara",
  "footjoy",
  "golden-dew",
  "roseedor",
  "s-i-beauty-club",
  "soda",
  "the-cosmetics-club",
  "triumph-elle",
  "venus-wacoal",
  "burberry-children",
  "happyland-house",
  "kangol-kids",
  "lee-kids",
  "little-ground",
  "magic-edition",
  "marithe-kids",
  "national-geographic-kids",
  "nba-kids",
  "nike-kids-value-store",
  "off-label",
  "toebox",
  "top10-kids",
  "bang-and-olufsen-bowers-and-wilkins",
  "jaju",
  "wine-and-more",
  "art-centum",
  "fannie",
  "five-guys",
  "hansung-pop-up",
  "hwasoon",
  "igane-topokki",
  "jackson",
  "jung-kwan-jang",
  "kary-market",
  "onsen",
  "palseonsaeng",
  "pizzeria-o",
  "shinsegae-outlet",
  "taco-bell",
  "twitzel",
  "yeoju-ceramics",
  "yeoju-market-place",
  "ililhyang"
] as const;
export const yeojuPremiumOutletsTaxRefundEvidence = {
  officialDirectoryUrl: "https://app.premiumoutlets.co.kr/rpage/en/store/tax-refund/0/01",
  officialServicesUrl: "https://app.premiumoutlets.co.kr/rpage/en/services/index/01",
  officialFaqUrl: "https://app.premiumoutlets.co.kr/rpage/en/faq/index/06",
  participatingOperators: ["GLOBAL TAX FREE", "GLOBAL BLUE", "NICE TAX FREE"],
  minimumPurchase: "KRW 15,000", immediateRefundPerPurchaseLimit: "KRW 1,000,000", immediateRefundStayLimit: "KRW 5,000,000", downtownRefundLimit: "KRW 6,000,000", exportDeadline: "Within 3 months",
  kiosks: ["East Bus Stop", "West Information Center"],
} as const;
export const yeojuPremiumOutletsDirectoryTotals = { declaredMemberships: yeojuPremiumOutletsCategoryAudit.reduce((sum, row) => sum + row.declaredCount, 0), observedMemberships: yeojuPremiumOutletsDirectory.length, uniqueDisplayNames: new Set(yeojuPremiumOutletsDirectory.map(row => row.displayName)).size, taxRefundEligible: yeojuPremiumOutletsDirectory.filter(row => row.taxRefundAvailable).length, taxRefundIneligible: yeojuPremiumOutletsDirectory.filter(row => !row.taxRefundAvailable).length } as const;
