import type { PremiumOutletMap } from "./types";

/**
 * AUTO-GENERATED from authorized official vector-plan evidence. Do not hand-edit.
 * Generated by tools/generateAuthorizedPdfExactMaps.ts.
 */
export const generatedPdfExactMaps: Record<string, PremiumOutletMap> = {
  "outletcity-metzingen": {
    "schemaVersion": 1,
    "outletId": "outletcity-metzingen",
    "outletName": "Outletcity Metzingen",
    "center": [
      9.2812,
      48.5359
    ],
    "defaultBearing": 0,
    "defaultPitch": 48,
    "defaultZoom": 16.3,
    "spatialAccuracy": "licensed-plan-exact",
    "verificationStatus": "verified",
    "lastUpdated": "2026-09-04",
    "floors": [
      {
        "id": "plan-ground",
        "level": 0,
        "label": {
          "en": "Site plan",
          "tr": "Yerleşke planı",
          "es": "Plano del centro",
          "fr": "Plan du centre",
          "de": "Centerplan",
          "ar": "مخطط المركز",
          "ru": "План центра",
          "zh": "中心平面图"
        }
      }
    ],
    "stores": [
      {
        "id": "outletcity-metzingen:7-for-all-mankind:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "7-for-all-mankind",
        "brandName": "7 For All Mankind",
        "aliases": [
          "7 For All Mankind®",
          "7ForAllMankind",
          "Seven For All Mankind",
          "7FAM"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277475952128567,
          48.53779372284699
        ]
      },
      {
        "id": "outletcity-metzingen:adidas:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "adidas",
        "brandName": "Adidas",
        "aliases": [
          "adidas Outlet Store",
          "adidas Originals",
          "adidasOutletStore",
          "adidasOriginals",
          "adidas",
          "Adidas Outlet",
          "Adidas Outlet Store"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.285748854693344,
          48.53842658939088
        ]
      },
      {
        "id": "outletcity-metzingen:aigner:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "aigner",
        "brandName": "Aigner",
        "aliases": [
          "Etienne Aigner",
          "EtienneAigner"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27966295576338,
          48.534143365396304
        ]
      },
      {
        "id": "outletcity-metzingen:allsaints:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "allsaints",
        "brandName": "AllSaints",
        "aliases": [
          "All Saints"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277926730790162,
          48.53539289103359
        ]
      },
      {
        "id": "outletcity-metzingen:armani:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "armani",
        "brandName": "Armani",
        "aliases": [
          "Armani Outlet",
          "Giorgio Armani",
          "ArmaniOutlet",
          "GiorgioArmani"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276526229212418,
          48.53416595487845
        ]
      },
      {
        "id": "outletcity-metzingen:bahlsen:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "bahlsen",
        "brandName": "Bahlsen",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28288684226566,
          48.53607378238064
        ]
      },
      {
        "id": "outletcity-metzingen:balenciaga:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "balenciaga",
        "brandName": "Balenciaga",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.2757326031515,
          48.53402738833173
        ]
      },
      {
        "id": "outletcity-metzingen:bally:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "bally",
        "brandName": "Bally",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276399855813134,
          48.534825600328965
        ]
      },
      {
        "id": "outletcity-metzingen:balmain:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "balmain",
        "brandName": "Balmain",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276188663309268,
          48.53704528698443
        ]
      },
      {
        "id": "outletcity-metzingen:belstaff:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "belstaff",
        "brandName": "Belstaff",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276651631075005,
          48.537688160367146
        ]
      },
      {
        "id": "outletcity-metzingen:bogner:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "bogner",
        "brandName": "Bogner",
        "aliases": [],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278090324281155,
          48.538723808610214
        ]
      },
      {
        "id": "outletcity-metzingen:boss:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "boss",
        "brandName": "BOSS",
        "aliases": [
          "Boss",
          "BOSS Outlet",
          "BOSS Womenswear",
          "BOSSOutlet",
          "Hugo Boss",
          "HUGO BOSS",
          "HugoBoss",
          "HUGOBOSS"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.274077551775472,
          48.53864086854354
        ]
      },
      {
        "id": "outletcity-metzingen:boss-sample-store:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "boss-sample-store",
        "brandName": "BOSS Sample Store",
        "aliases": [
          "BOSSSampleStore"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.274077551775472,
          48.53864086854354
        ]
      },
      {
        "id": "outletcity-metzingen:bottega-veneta:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "bottega-veneta",
        "brandName": "Bottega Veneta",
        "aliases": [
          "BottegaVeneta"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276573785125695,
          48.53394259754173
        ]
      },
      {
        "id": "outletcity-metzingen:breitling:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "breitling",
        "brandName": "Breitling",
        "aliases": [],
        "categoryId": "jewelry-watches",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27715421006205,
          48.53697323211669
        ]
      },
      {
        "id": "outletcity-metzingen:burberry:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "burberry",
        "brandName": "Burberry",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278158464740471,
          48.536536872752144
        ]
      },
      {
        "id": "outletcity-metzingen:c-p-company:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "c-p-company",
        "brandName": "C.P. Company",
        "aliases": [
          "CP Company",
          "C P Company",
          "CPCompany"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276610850777189,
          48.53813412361458
        ]
      },
      {
        "id": "outletcity-metzingen:calvin-klein:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "calvin-klein",
        "brandName": "Calvin Klein",
        "aliases": [
          "Calvin Klein Jeans",
          "Calvin Klein Underwear",
          "CK",
          "Calvin Klein Outlet",
          "CalvinKlein",
          "CalvinKleinJeans",
          "CalvinKleinUnderwear",
          "CalvinKleinOutlet",
          "CALVİN KLEİN"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281262604406159,
          48.53593827722128
        ]
      },
      {
        "id": "outletcity-metzingen:coach:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "coach",
        "brandName": "Coach",
        "aliases": [
          "Coach Outlet",
          "Coach New York",
          "CoachOutlet",
          "CoachNewYork"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278001804896784,
          48.535268223173496
        ]
      },
      {
        "id": "outletcity-metzingen:columbia:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "columbia",
        "brandName": "Columbia",
        "aliases": [
          "Columbia Sportswear",
          "ColumbiaSportswear"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28543944449838,
          48.538617469557046
        ]
      },
      {
        "id": "outletcity-metzingen:crocs:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "crocs",
        "brandName": "Crocs",
        "aliases": [],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27990940732739,
          48.5347686889404
        ]
      },
      {
        "id": "outletcity-metzingen:dolce-and-gabbana:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "dolce-and-gabbana",
        "brandName": "Dolce & Gabbana",
        "aliases": [
          "Dolce and Gabbana",
          "D&G",
          "Dolce Gabbana",
          "DolceGabbana",
          "DolceandGabbana",
          "DandG",
          "D G",
          "DG"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278345181164052,
          48.533884769473325
        ]
      },
      {
        "id": "outletcity-metzingen:douglas:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "douglas",
        "brandName": "Douglas",
        "aliases": [],
        "categoryId": "beauty",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28490623157645,
          48.537313013182356
        ]
      },
      {
        "id": "outletcity-metzingen:dr-martens:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "dr-martens",
        "brandName": "Dr. Martens",
        "aliases": [
          "Doc Martens",
          "Dr Martens",
          "DrMartens",
          "DocMartens"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281143275096893,
          48.53837538225371
        ]
      },
      {
        "id": "outletcity-metzingen:dsquared2:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "dsquared2",
        "brandName": "Dsquared2",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276852828962427,
          48.53630138542394
        ]
      },
      {
        "id": "outletcity-metzingen:ferragamo:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "ferragamo",
        "brandName": "Ferragamo",
        "aliases": [
          "Salvatore Ferragamo",
          "SalvatoreFerragamo"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276340300254349,
          48.533012608176584
        ]
      },
      {
        "id": "outletcity-metzingen:g-star:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "g-star",
        "brandName": "G-Star",
        "aliases": [
          "G Star",
          "GStar"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27921746398541,
          48.53641117624674
        ]
      },
      {
        "id": "outletcity-metzingen:gucci:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "gucci",
        "brandName": "Gucci",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276277036334598,
          48.534404181468766
        ]
      },
      {
        "id": "outletcity-metzingen:guess:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "guess",
        "brandName": "Guess",
        "aliases": [
          "GUESS",
          "GUESS Factory",
          "GUESS Kids",
          "GUESSFactory"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.283545754257798,
          48.53655708401591
        ]
      },
      {
        "id": "outletcity-metzingen:haribo:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "haribo",
        "brandName": "HARIBO",
        "aliases": [
          "Haribo"
        ],
        "categoryId": "food-confectionery",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28310041781795,
          48.5362847331053
        ]
      },
      {
        "id": "outletcity-metzingen:hogan:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "hogan",
        "brandName": "Hogan",
        "aliases": [],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276690684695307,
          48.5328160429189
        ]
      },
      {
        "id": "outletcity-metzingen:hour-passion:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "hour-passion",
        "brandName": "Hour Passion",
        "aliases": [
          "HourPassion"
        ],
        "categoryId": "jewelry-watches",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27808518914402,
          48.53487912341495
        ]
      },
      {
        "id": "outletcity-metzingen:hugo:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "hugo",
        "brandName": "HUGO",
        "aliases": [
          "Hugo Boss HUGO",
          "HugoBossHUGO",
          "Hugo Boss",
          "Hugo"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.274077551775472,
          48.53864086854354
        ]
      },
      {
        "id": "outletcity-metzingen:hunkemoller:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "hunkemoller",
        "brandName": "Hunkemöller",
        "aliases": [
          "Hunkemoller"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27938221577801,
          48.535413290902284
        ]
      },
      {
        "id": "outletcity-metzingen:jack-and-jones:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "jack-and-jones",
        "brandName": "Jack & Jones",
        "aliases": [
          "Jack and Jones",
          "Jack Jones",
          "JACK&JONES",
          "Jack&Jones",
          "JackandJones",
          "JackJones",
          "JACK & JONES"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.288322448224529,
          48.537654177350866
        ]
      },
      {
        "id": "outletcity-metzingen:jil-sander:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "jil-sander",
        "brandName": "Jil Sander",
        "aliases": [
          "JilSander"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28522029562974,
          48.53828921434834
        ]
      },
      {
        "id": "outletcity-metzingen:joop:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "joop",
        "brandName": "JOOP!",
        "aliases": [
          "Joop",
          "Joop! Men",
          "Joop! Women",
          "JOOP",
          "JoopMen",
          "JoopWomen"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278838667034513,
          48.53703611539602
        ]
      },
      {
        "id": "outletcity-metzingen:kapten-and-son:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "kapten-and-son",
        "brandName": "Kapten & Son",
        "aliases": [
          "Kapten and Son",
          "Kapten Son",
          "KaptenSon"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277926730790162,
          48.53539289103359
        ]
      },
      {
        "id": "outletcity-metzingen:karl-lagerfeld:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "karl-lagerfeld",
        "brandName": "Karl Lagerfeld",
        "aliases": [
          "KARL LAGERFELD",
          "Karl",
          "KarlLagerfeld"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276018203514084,
          48.53414912772604
        ]
      },
      {
        "id": "outletcity-metzingen:kennel-and-schmenger:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "kennel-and-schmenger",
        "brandName": "Kennel & Schmenger",
        "aliases": [
          "Kennel and Schmenger",
          "Kennel Schmenger",
          "KennelSchmenger"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27941436897361,
          48.5346667692301
        ]
      },
      {
        "id": "outletcity-metzingen:kjus:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "kjus",
        "brandName": "KJUS",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28288684226566,
          48.53607378238064
        ]
      },
      {
        "id": "outletcity-metzingen:kneipp:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "kneipp",
        "brandName": "Kneipp",
        "aliases": [],
        "categoryId": "beauty",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.2757326031515,
          48.53402738833173
        ]
      },
      {
        "id": "outletcity-metzingen:l-occitane:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "l-occitane",
        "brandName": "L'Occitane",
        "aliases": [
          "LOccitane",
          "L Occitane",
          "L'Occitane en Provence",
          "L’Occitane",
          "L’Occitane en Provence",
          "L Occitane en Provence",
          "LOccitaneenProvence",
          "Loccitane"
        ],
        "categoryId": "beauty",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.280751853556366,
          48.5361120895392
        ]
      },
      {
        "id": "outletcity-metzingen:lacoste:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "lacoste",
        "brandName": "Lacoste",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277730554903437,
          48.535575204943356
        ]
      },
      {
        "id": "outletcity-metzingen:le-creuset:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "le-creuset",
        "brandName": "Le Creuset",
        "aliases": [
          "LE CREUSET",
          "LeCreuset"
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.286736007811726,
          48.53731675055374
        ]
      },
      {
        "id": "outletcity-metzingen:levis:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "levis",
        "brandName": "Levi's",
        "aliases": [
          "Levi s",
          "Levi s Outlet",
          "Levi Strauss",
          "Levi's",
          "Levi’s",
          "Levi's Clearance",
          "Levi's Outlet",
          "Levi’s Clearance",
          "Levi’s Outlet",
          "Levis",
          "LevisOutlet",
          "LeviStrauss",
          "LEVI'S"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281717002535805,
          48.537389007198826
        ]
      },
      {
        "id": "outletcity-metzingen:liebeskind-berlin:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "liebeskind-berlin",
        "brandName": "Liebeskind Berlin",
        "aliases": [
          "LiebeskindBerlin"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.274316980799261,
          48.53878892521144
        ]
      },
      {
        "id": "outletcity-metzingen:lindt:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "lindt",
        "brandName": "Lindt",
        "aliases": [
          "Lindt & Sprüngli",
          "Lindt and Sprungli",
          "Lindt & Sprungli",
          "Lindt and Sprüngli",
          "Lindt Sprüngli",
          "Lindt Sprungli",
          "LindtSprungli",
          "LindtandSprungli",
          "Lindt Chocolate",
          "Lindt Chocolates"
        ],
        "categoryId": "food-confectionery",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.280310954578962,
          48.53547720282693
        ]
      },
      {
        "id": "outletcity-metzingen:longchamp:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "longchamp",
        "brandName": "Longchamp",
        "aliases": [],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27715421006205,
          48.53697323211669
        ]
      },
      {
        "id": "outletcity-metzingen:lululemon:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "lululemon",
        "brandName": "lululemon",
        "aliases": [
          "Lululemon Athletica",
          "LululemonAthletica"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.280851265465403,
          48.535793440608366
        ]
      },
      {
        "id": "outletcity-metzingen:maison-margiela:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "maison-margiela",
        "brandName": "Maison Margiela",
        "aliases": [
          "Maison Martin Margiela",
          "MaisonMargiela",
          "MaisonMartinMargiela"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278094592936853,
          48.533593607166665
        ]
      },
      {
        "id": "outletcity-metzingen:mammut:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "mammut",
        "brandName": "Mammut",
        "aliases": [],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27808518914402,
          48.53487912341495
        ]
      },
      {
        "id": "outletcity-metzingen:marc-o-polo:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "marc-o-polo",
        "brandName": "Marc O'Polo",
        "aliases": [
          "Marc OPolo",
          "Marc O Polo",
          "Marc O’Polo",
          "MarcOPolo"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278153217364808,
          48.53513884138759
        ]
      },
      {
        "id": "outletcity-metzingen:max-mara:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "max-mara",
        "brandName": "Max Mara",
        "aliases": [
          "MaxMara"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278462615886967,
          48.536771802049245
        ]
      },
      {
        "id": "outletcity-metzingen:mcm:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "mcm",
        "brandName": "MCM",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278892343090245,
          48.534688113320954
        ]
      },
      {
        "id": "outletcity-metzingen:mey:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "mey",
        "brandName": "Mey",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.279726995475835,
          48.534937350846825
        ]
      },
      {
        "id": "outletcity-metzingen:michael-kors:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "michael-kors",
        "brandName": "Michael Kors",
        "aliases": [
          "Michael Kors Outlet",
          "MichaelKors",
          "MichaelKorsOutlet",
          "MK"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27778829130016,
          48.53575126974305
        ]
      },
      {
        "id": "outletcity-metzingen:missoni:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "missoni",
        "brandName": "Missoni",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.275931027400416,
          48.53752269516464
        ]
      },
      {
        "id": "outletcity-metzingen:miu-miu:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "miu-miu",
        "brandName": "Miu Miu",
        "aliases": [
          "MiuMiu"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281916855356707,
          48.53825374584368
        ]
      },
      {
        "id": "outletcity-metzingen:moncler:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "moncler",
        "brandName": "Moncler",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.275634595570924,
          48.536560821986036
        ]
      },
      {
        "id": "outletcity-metzingen:moose-knuckles:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "moose-knuckles",
        "brandName": "Moose Knuckles",
        "aliases": [
          "MooseKnuckles"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27584889214352,
          48.5345676043493
        ]
      },
      {
        "id": "outletcity-metzingen:motel-a-miio:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "motel-a-miio",
        "brandName": "Motel a Miio",
        "aliases": [
          "MotelaMiio"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.285682354712355,
          48.53696551967183
        ]
      },
      {
        "id": "outletcity-metzingen:moeve:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "moeve",
        "brandName": "Möve",
        "aliases": [
          "Move"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278918104077196,
          48.53539304610875
        ]
      },
      {
        "id": "outletcity-metzingen:name-it:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "name-it",
        "brandName": "Name It",
        "aliases": [
          "NAME IT",
          "NameIt",
          "NAMEIT"
        ],
        "categoryId": "children",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276340300254349,
          48.533012608176584
        ]
      },
      {
        "id": "outletcity-metzingen:new-balance:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "new-balance",
        "brandName": "New Balance",
        "aliases": [
          "NB",
          "New Balance Factory Store",
          "NewBalance"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.282946167062029,
          48.53690379736064
        ]
      },
      {
        "id": "outletcity-metzingen:nike:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "nike",
        "brandName": "Nike",
        "aliases": [
          "Nike Factory Store",
          "Nike Unite",
          "Nike Outlet",
          "NikeFactoryStore",
          "NikeUnite",
          "NikeOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28373388219311,
          48.53898395708109
        ]
      },
      {
        "id": "outletcity-metzingen:oakley:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "oakley",
        "brandName": "Oakley",
        "aliases": [],
        "categoryId": "eyewear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281996973013825,
          48.53583368710463
        ]
      },
      {
        "id": "outletcity-metzingen:olymp:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "olymp",
        "brandName": "OLYMP",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277726489174999,
          48.53781267554706
        ]
      },
      {
        "id": "outletcity-metzingen:only:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "only",
        "brandName": "ONLY",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28185255794459,
          48.53647410802448
        ]
      },
      {
        "id": "outletcity-metzingen:only-and-sons:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "only-and-sons",
        "brandName": "Only & Sons",
        "aliases": [
          "Only&Sons",
          "Only and Sons",
          "Only Sons",
          "OnlySons",
          "OnlyandSons"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28185255794459,
          48.53647410802448
        ]
      },
      {
        "id": "outletcity-metzingen:paul-and-shark:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "paul-and-shark",
        "brandName": "Paul & Shark",
        "aliases": [
          "Paul and Shark",
          "Paul Shark",
          "PaulShark",
          "PaulandShark"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27808518914402,
          48.53487912341495
        ]
      },
      {
        "id": "outletcity-metzingen:philipp-plein:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "philipp-plein",
        "brandName": "Philipp Plein",
        "aliases": [
          "PhilippPlein"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.282646840376422,
          48.53609535758737
        ]
      },
      {
        "id": "outletcity-metzingen:playmobil:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "playmobil",
        "brandName": "Playmobil",
        "aliases": [],
        "categoryId": "children",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276091197167352,
          48.5329701463208
        ]
      },
      {
        "id": "outletcity-metzingen:polo-ralph-lauren:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "polo-ralph-lauren",
        "brandName": "Polo Ralph Lauren",
        "aliases": [
          "Polo Ralph Lauren Factory Store",
          "Ralph Lauren",
          "PoloRalphLauren",
          "RalphLauren",
          "Polo"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.275765171180698,
          48.533697193186576
        ]
      },
      {
        "id": "outletcity-metzingen:porsche-design:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "porsche-design",
        "brandName": "Porsche Design",
        "aliases": [
          "PorscheDesign"
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27938221577801,
          48.535413290902284
        ]
      },
      {
        "id": "outletcity-metzingen:prada:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "prada",
        "brandName": "Prada",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.275239018511135,
          48.53293787691505
        ]
      },
      {
        "id": "outletcity-metzingen:puma:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "puma",
        "brandName": "PUMA",
        "aliases": [
          "Puma",
          "PUMA Outlet",
          "PUMAOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.284908907342958,
          48.53889713654278
        ]
      },
      {
        "id": "outletcity-metzingen:rag-and-bone:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "rag-and-bone",
        "brandName": "rag & bone",
        "aliases": [
          "Rag and Bone",
          "Rag & Bone",
          "rag and bone",
          "rag bone",
          "ragbone",
          "RagandBone",
          "Rag Bone",
          "RagBone"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27848712608776,
          48.53704430025133
        ]
      },
      {
        "id": "outletcity-metzingen:ravensburger:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "ravensburger",
        "brandName": "Ravensburger",
        "aliases": [],
        "categoryId": "children",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.287897258151506,
          48.53846680594986
        ]
      },
      {
        "id": "outletcity-metzingen:rituals:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "rituals",
        "brandName": "Rituals",
        "aliases": [
          "Rituals Cosmetics",
          "RitualsCosmetics"
        ],
        "categoryId": "beauty",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.279384998395598,
          48.534483001565484
        ]
      },
      {
        "id": "outletcity-metzingen:s-oliver:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "s-oliver",
        "brandName": "s.Oliver",
        "aliases": [
          "s Oliver",
          "sOliver"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.283924283632043,
          48.5371403504564
        ]
      },
      {
        "id": "outletcity-metzingen:samsonite:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "samsonite",
        "brandName": "Samsonite",
        "aliases": [],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278242433525962,
          48.535491112290984
        ]
      },
      {
        "id": "outletcity-metzingen:sandro:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "sandro",
        "brandName": "Sandro",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.286077636360337,
          48.53719320174958
        ]
      },
      {
        "id": "outletcity-metzingen:schiesser:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "schiesser",
        "brandName": "Schiesser",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.286688358515994,
          48.53616772500043
        ]
      },
      {
        "id": "outletcity-metzingen:seidensticker:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "seidensticker",
        "brandName": "Seidensticker",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281855097229048,
          48.537197991716106
        ]
      },
      {
        "id": "outletcity-metzingen:skechers:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "skechers",
        "brandName": "Skechers",
        "aliases": [
          "Skechers Outlet",
          "SkechersOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.281321066312726,
          48.536837744320955
        ]
      },
      {
        "id": "outletcity-metzingen:storck:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "storck",
        "brandName": "Storck",
        "aliases": [],
        "categoryId": "food",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.280182347184015,
          48.5356170794295
        ]
      },
      {
        "id": "outletcity-metzingen:strellson:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "strellson",
        "brandName": "Strellson",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.279657214538194,
          48.536233269704915
        ]
      },
      {
        "id": "outletcity-metzingen:sunglass-hut:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "sunglass-hut",
        "brandName": "Sunglass Hut",
        "aliases": [
          "SunglassHut"
        ],
        "categoryId": "eyewear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27766482173607,
          48.534219215713776
        ]
      },
      {
        "id": "outletcity-metzingen:superdry:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "superdry",
        "brandName": "Superdry",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27808518914402,
          48.53487912341495
        ]
      },
      {
        "id": "outletcity-metzingen:swarovski:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "swarovski",
        "brandName": "Swarovski",
        "aliases": [
          "SWAROVSKI"
        ],
        "categoryId": "jewelry-watches",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27939715697086,
          48.5352474287313
        ]
      },
      {
        "id": "outletcity-metzingen:tefal:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tefal",
        "brandName": "Tefal",
        "aliases": [
          "T-fal",
          "T fal",
          "Tfal"
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277194928404201,
          48.533504544325275
        ]
      },
      {
        "id": "outletcity-metzingen:the-cosmetics-company-store:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "the-cosmetics-company-store",
        "brandName": "The Cosmetics Company Store",
        "aliases": [
          "CCS",
          "Cosmetics Company Store",
          "TCCS",
          "THE COSMETICS COMPANY STORE",
          "The Cosmetics Company",
          "The ELC Company Store",
          "Estée Lauder Companies Store"
        ],
        "categoryId": "beauty",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.279731091733153,
          48.53586127970682
        ]
      },
      {
        "id": "outletcity-metzingen:the-north-face:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "the-north-face",
        "brandName": "The North Face",
        "aliases": [
          "North Face",
          "The North Face",
          "THE NORTH FACE",
          "The North Face Outlet",
          "TheNorthFace",
          "TheNorthFaceOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276888183200844,
          48.53889725329822
        ]
      },
      {
        "id": "outletcity-metzingen:thomas-sabo:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "thomas-sabo",
        "brandName": "Thomas Sabo",
        "aliases": [
          "ThomasSabo"
        ],
        "categoryId": "jewelry-watches",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.2784186201798,
          48.534726172598745
        ]
      },
      {
        "id": "outletcity-metzingen:timberland:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "timberland",
        "brandName": "Timberland",
        "aliases": [
          "Timberland Outlet",
          "TimberlandOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.282550707628218,
          48.53849807844383
        ]
      },
      {
        "id": "outletcity-metzingen:tods:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tods",
        "brandName": "TOD'S",
        "aliases": [
          "Tod's",
          "Tods",
          "TOD’S",
          "TOD S",
          "TODS",
          "Tod’s",
          "Tod s"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276690684695307,
          48.5328160429189
        ]
      },
      {
        "id": "outletcity-metzingen:tom-tailor:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tom-tailor",
        "brandName": "Tom Tailor",
        "aliases": [
          "TomTailor"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276747341806344,
          48.537453808261006
        ]
      },
      {
        "id": "outletcity-metzingen:tom-tailor-kids:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tom-tailor-kids",
        "brandName": "Tom Tailor Kids",
        "aliases": [
          "TomTailorKids"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276747341806344,
          48.537453808261006
        ]
      },
      {
        "id": "outletcity-metzingen:tommy-hilfiger:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tommy-hilfiger",
        "brandName": "Tommy Hilfiger",
        "aliases": [
          "Tommy",
          "Tommy Hilfiger",
          "Tommy Hilfiger Outlet",
          "TommyHilfiger",
          "TommyHilfigerOutlet"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28126193636244,
          48.535645800667545
        ]
      },
      {
        "id": "outletcity-metzingen:tory-burch:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tory-burch",
        "brandName": "Tory Burch",
        "aliases": [
          "Tory Burch Outlet",
          "ToryBurch",
          "ToryBurchOutlet"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.277076163879206,
          48.53456874436133
        ]
      },
      {
        "id": "outletcity-metzingen:tumi:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "tumi",
        "brandName": "TUMI",
        "aliases": [
          "Tumi"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.284699658810398,
          48.5366870759238
        ]
      },
      {
        "id": "outletcity-metzingen:ugg:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "ugg",
        "brandName": "UGG",
        "aliases": [
          "UGG Australia",
          "UGG Outlet",
          "UGGAustralia",
          "UGGOutlet"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.285633526463124,
          48.53732741960544
        ]
      },
      {
        "id": "outletcity-metzingen:under-armour:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "under-armour",
        "brandName": "Under Armour",
        "aliases": [
          "Under Armour Factory House",
          "Under Armour Outlet",
          "UnderArmour",
          "UnderArmourOutlet"
        ],
        "categoryId": "sportswear",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.286387198301792,
          48.53823632353793
        ]
      },
      {
        "id": "outletcity-metzingen:valentino-garavani:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "valentino-garavani",
        "brandName": "Valentino Garavani",
        "aliases": [
          "ValentinoGaravani"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.285940083105753,
          48.53802997417486
        ]
      },
      {
        "id": "outletcity-metzingen:vero-moda:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "vero-moda",
        "brandName": "Vero Moda",
        "aliases": [
          "VeroModa"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.288238694039103,
          48.537770288534496
        ]
      },
      {
        "id": "outletcity-metzingen:versace:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "versace",
        "brandName": "Versace",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.28151041181159,
          48.5364920512391
        ]
      },
      {
        "id": "outletcity-metzingen:vilebrequin:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "vilebrequin",
        "brandName": "Vilebrequin",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.286711164486979,
          48.538272248286894
        ]
      },
      {
        "id": "outletcity-metzingen:villeroy-and-boch:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "villeroy-and-boch",
        "brandName": "Villeroy & Boch",
        "aliases": [
          "Villeroy and Boch",
          "Villeroy Boch",
          "VilleroyBoch",
          "VilleroyandBoch"
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.285725646459474,
          48.536694513544326
        ]
      },
      {
        "id": "outletcity-metzingen:windsor:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "windsor",
        "brandName": "Windsor",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.278678795373109,
          48.53882537685673
        ]
      },
      {
        "id": "outletcity-metzingen:wmf:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "wmf",
        "brandName": "WMF",
        "aliases": [
          "W.M.F."
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.284276233127036,
          48.537578300089834
        ]
      },
      {
        "id": "outletcity-metzingen:woolrich:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "woolrich",
        "brandName": "Woolrich",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.284004532383761,
          48.53683003606732
        ]
      },
      {
        "id": "outletcity-metzingen:worst-behavior:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "worst-behavior",
        "brandName": "Worst Behavior",
        "aliases": [
          "WorstBehavior"
        ],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.275168483330585,
          48.53346320571664
        ]
      },
      {
        "id": "outletcity-metzingen:wrangler:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "wrangler",
        "brandName": "Wrangler",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.27746678897514,
          48.53754806761734
        ]
      },
      {
        "id": "outletcity-metzingen:zwilling:pdf:1",
        "outletId": "outletcity-metzingen",
        "brandId": "zwilling",
        "brandName": "Zwilling",
        "aliases": [
          "ZWILLING"
        ],
        "categoryId": "home",
        "floorId": "plan-ground",
        "openingHours": "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00",
        "geometryKind": "point",
        "center": [
          9.276782776856502,
          48.53593631692747
        ]
      }
    ],
    "pois": [],
    "environment": {
      "roads": [],
      "walkways": [],
      "landscapeAreas": [],
      "trees": []
    },
    "source": {
      "url": "https://www.outletcity.com/en/metzingen/map/",
      "host": "www.outletcity.com",
      "checkedOn": "2026-09-04",
      "purpose": "spatial-data",
      "redrawPolicy": "licensed-render",
      "redistributionStatus": "commercially-licensed",
      "dataLicense": "commercial-license",
      "commercialReuseAllowed": true,
      "coordinateBasis": "operator-plan-affine",
      "attribution": "Official OUTLETCITY AG vector plan"
    }
  },
  "the-mall-firenze": {
    "schemaVersion": 1,
    "outletId": "the-mall-firenze",
    "outletName": "The Mall Firenze",
    "center": [
      11.4656,
      43.6936
    ],
    "defaultBearing": 0,
    "defaultPitch": 48,
    "defaultZoom": 17.1,
    "spatialAccuracy": "licensed-plan-exact",
    "verificationStatus": "verified",
    "lastUpdated": "2026-09-04",
    "floors": [
      {
        "id": "plan-ground",
        "level": 0,
        "label": {
          "en": "Site plan",
          "tr": "Yerleşke planı",
          "es": "Plano del centro",
          "fr": "Plan du centre",
          "de": "Centerplan",
          "ar": "مخطط المركز",
          "ru": "План центра",
          "zh": "中心平面图"
        }
      }
    ],
    "stores": [
      {
        "id": "the-mall-firenze:alberta-ferretti:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "alberta-ferretti",
        "brandName": "Alberta Ferretti",
        "aliases": [
          "AlbertaFerretti"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.461562324884119,
          43.69346328391483
        ]
      },
      {
        "id": "the-mall-firenze:alexander-mcqueen:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "alexander-mcqueen",
        "brandName": "Alexander McQueen",
        "aliases": [
          "McQueen",
          "AlexanderMcQueen"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.468947613675033,
          43.692800500017185
        ]
      },
      {
        "id": "the-mall-firenze:armani:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "armani",
        "brandName": "Armani",
        "aliases": [
          "Armani Outlet",
          "Giorgio Armani",
          "ArmaniOutlet",
          "GiorgioArmani"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.467419671154781,
          43.692481943404346
        ]
      },
      {
        "id": "the-mall-firenze:balenciaga:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "balenciaga",
        "brandName": "Balenciaga",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251753823796,
          43.69312845759472
        ]
      },
      {
        "id": "the-mall-firenze:balmain:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "balmain",
        "brandName": "Balmain",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.464916177805371,
          43.69427341876049
        ]
      },
      {
        "id": "the-mall-firenze:bottega-veneta:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "bottega-veneta",
        "brandName": "Bottega Veneta",
        "aliases": [
          "BottegaVeneta"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.464697887847027,
          43.69494303329673
        ]
      },
      {
        "id": "the-mall-firenze:burberry:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "burberry",
        "brandName": "Burberry",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.467409342586215,
          43.69341035198072
        ]
      },
      {
        "id": "the-mall-firenze:celine:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "celine",
        "brandName": "Celine",
        "aliases": [
          "Céline"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.46894761401931,
          43.69264576567227
        ]
      },
      {
        "id": "the-mall-firenze:coach:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "coach",
        "brandName": "Coach",
        "aliases": [
          "Coach Outlet",
          "Coach New York",
          "CoachOutlet",
          "CoachNewYork"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.462240034096125,
          43.69278549695368
        ]
      },
      {
        "id": "the-mall-firenze:corneliani:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "corneliani",
        "brandName": "Corneliani",
        "aliases": [],
        "categoryId": "fashion",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.469637717978369,
          43.693821724107046
        ]
      },
      {
        "id": "the-mall-firenze:dolce-and-gabbana:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "dolce-and-gabbana",
        "brandName": "Dolce & Gabbana",
        "aliases": [
          "Dolce and Gabbana",
          "D&G",
          "Dolce Gabbana",
          "DolceGabbana",
          "DolceandGabbana",
          "DandG",
          "D G",
          "DG"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.464142407044376,
          43.69501543053285
        ]
      },
      {
        "id": "the-mall-firenze:ermenegildo-zegna:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "ermenegildo-zegna",
        "brandName": "Ermenegildo Zegna",
        "aliases": [
          "Zegna",
          "ErmenegildoZegna",
          "ZEGNA"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251796428075,
          43.69275412347061
        ]
      },
      {
        "id": "the-mall-firenze:etro:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "etro",
        "brandName": "Etro",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.46894761401931,
          43.69306434527797
        ]
      },
      {
        "id": "the-mall-firenze:fendi:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "fendi",
        "brandName": "Fendi",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466155436390917,
          43.69473819467095
        ]
      },
      {
        "id": "the-mall-firenze:ferragamo:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "ferragamo",
        "brandName": "Ferragamo",
        "aliases": [
          "Salvatore Ferragamo",
          "SalvatoreFerragamo"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251797546976,
          43.693323740521095
        ]
      },
      {
        "id": "the-mall-firenze:givenchy:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "givenchy",
        "brandName": "Givenchy",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.464089260141344,
          43.69384448195584
        ]
      },
      {
        "id": "the-mall-firenze:gucci:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "gucci",
        "brandName": "Gucci",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.462305360831285,
          43.694345190414595
        ]
      },
      {
        "id": "the-mall-firenze:hogan:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "hogan",
        "brandName": "Hogan",
        "aliases": [],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466804727945522,
          43.6946314586103
        ]
      },
      {
        "id": "the-mall-firenze:jil-sander:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "jil-sander",
        "brandName": "Jil Sander",
        "aliases": [
          "JilSander"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251796514145,
          43.692949155775615
        ]
      },
      {
        "id": "the-mall-firenze:jimmy-choo:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "jimmy-choo",
        "brandName": "Jimmy Choo",
        "aliases": [
          "JimmyChoo"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.46575096572796,
          43.69476993571949
        ]
      },
      {
        "id": "the-mall-firenze:kids-around:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "kids-around",
        "brandName": "Kids Around",
        "aliases": [
          "KidsAround"
        ],
        "categoryId": "children",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.469637804133692,
          43.693087972060304
        ]
      },
      {
        "id": "the-mall-firenze:loro-piana:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "loro-piana",
        "brandName": "Loro Piana",
        "aliases": [
          "LoroPiana"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.467414506569256,
          43.69286473811466
        ]
      },
      {
        "id": "the-mall-firenze:marni:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "marni",
        "brandName": "Marni",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.469637717548023,
          43.69351977531156
        ]
      },
      {
        "id": "the-mall-firenze:moschino:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "moschino",
        "brandName": "Moschino",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.461562195866309,
          43.69339810606558
        ]
      },
      {
        "id": "the-mall-firenze:roberto-cavalli:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "roberto-cavalli",
        "brandName": "Roberto Cavalli",
        "aliases": [
          "RobertoCavalli"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251968996929,
          43.69218456946716
        ]
      },
      {
        "id": "the-mall-firenze:saint-laurent:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "saint-laurent",
        "brandName": "Saint Laurent",
        "aliases": [
          "Yves Saint Laurent",
          "YSL",
          "Saint Laurent",
          "SaintLaurent",
          "YvesSaintLaurent"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.46476414404405,
          43.69320652066607
        ]
      },
      {
        "id": "the-mall-firenze:tods:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "tods",
        "brandName": "TOD'S",
        "aliases": [
          "Tod's",
          "Tods",
          "TOD’S",
          "TOD S",
          "TODS",
          "Tod’s",
          "Tod s"
        ],
        "categoryId": "shoes-bags",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466979855980943,
          43.69460440378645
        ]
      },
      {
        "id": "the-mall-firenze:tom-ford:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "tom-ford",
        "brandName": "Tom Ford",
        "aliases": [
          "TomFord"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466251925704094,
          43.692582906462334
        ]
      },
      {
        "id": "the-mall-firenze:valentino:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "valentino",
        "brandName": "Valentino",
        "aliases": [
          "Maison Valentino",
          "Valentino Garavani",
          "MaisonValentino",
          "ValentinoGaravani"
        ],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.466257950723941,
          43.692384803340566
        ]
      },
      {
        "id": "the-mall-firenze:versace:pdf:1",
        "outletId": "the-mall-firenze",
        "brandId": "versace",
        "brandName": "Versace",
        "aliases": [],
        "categoryId": "luxury",
        "floorId": "plan-ground",
        "openingHours": "10:00 - 20:00",
        "geometryKind": "point",
        "center": [
          11.468947571156821,
          43.69356170215383
        ]
      }
    ],
    "pois": [],
    "environment": {
      "roads": [],
      "walkways": [],
      "landscapeAreas": [],
      "trees": []
    },
    "source": {
      "url": "https://firenze.themall.it/pdf/The-Mall-Firenze-Map.pdf",
      "host": "firenze.themall.it",
      "checkedOn": "2026-09-04",
      "purpose": "spatial-data",
      "redrawPolicy": "licensed-render",
      "redistributionStatus": "commercially-licensed",
      "dataLicense": "commercial-license",
      "commercialReuseAllowed": true,
      "coordinateBasis": "operator-plan-affine",
      "attribution": "Official The Mall Luxury Outlets vector plan"
    }
  }
};
