import type { PremiumOutletMap } from "./types";

/**
 * Generated by tools/generatePremiumMapBatch2ExactMaps.ts.
 * Kept empty until the official-source capture/generation workflow completes.
 */
export const generatedMappedinExactMapsBatch2: Record<string, PremiumOutletMap> = {};
