"""Reviewed routes; fare bounds refer to the stated ticket unit. Planning budgets are explicitly estimated."""
import pathlib,json
ROOT=pathlib.Path(__file__).resolve().parent.parent
routes=[]
def add(gid,oid,origin,originid,mode,provider,legs,duration,fare,currency,url,notes=(),faretype='exact',unit='oneWay',recommended=True,sources=(),basis=''):
 routes.append(dict(guideId=gid,outletId=oid,originType=origin,originId=originid,mode=mode,provider=provider,legs=[dict(line=l,fromStop=f,toStop=t) for l,f,t in legs],durationMin=duration[0],durationMax=duration[1],fareMin=fare[0],fareMax=fare[1],currency=currency,fareAccuracy=faretype,fareUnit=unit,officialProviderUrl=url,notes=list(notes),recommended=recommended,checkedAt='2026-09-12',sources=list(dict.fromkeys([url,*sources])),fareBasis=basis))
add('new-york-to-woodbury-common-bus','woodbury-common-premium-outlets','city_center','new-york','shuttle','Woodbury Bus',[("Woodbury Common shuttle",'1651 Broadway / W 51st Street (McDonald’s)','Woodbury Common — Bus Plaza 2')],(60,90),(45,45),'USD','https://www.woodburybus.com/',['reserve','arrive15','bookingFees'],unit='roundTripFrom',basis='Operator advertises round-trip tickets starting at USD 45; booking fees and selected service can increase the total. The upper bound is not a price cap.')
add('fort-lauderdale-to-sawgrass-mills-bus-22','sawgrass-mills','station','fort-lauderdale-tri-rail','bus','Broward County Transit',[('22','Fort Lauderdale Tri-Rail Station','Sawgrass Mills — West Dining Pavilion / Marshalls')],(45,75),(2,2),'USD','https://www.broward.org/bct/Schedules',['exactCash'],sources=['https://www.browardcdn.org/api/public/content/5d0ce92381ce4f1f9f4429f85dfc5d5c?v=655f7345','https://webapps.broward.org/NewsRelease/View.aspx?intMessageID=16207'],basis='BCT regular adult one-way fare USD 2; the estimate covers route 22 from the station, not airport travel.')
add('international-drive-to-orlando-vineland-trolley','orlando-vineland-premium-outlets','city_center','international-drive','bus','I-RIDE Trolley',[('Red Line (southbound)','International Drive / SeaWorld','Orlando Vineland Premium Outlets')],(20,45),(2,2),'USD','https://www.internationaldriveorlando.com/iride-trolley/',['exactCash'],sources=['https://www.idrivedistrict.com/i-ride-trolley/'],basis='Adult single fare USD 2. Journey depends on the boarding stop; estimate starts in the SeaWorld section of International Drive.')
add('downtown-las-vegas-to-north-premium-outlets-loop','las-vegas-north-premium-outlets','city_center','downtown-las-vegas','shuttle','City of Las Vegas Downtown Loop',[('Downtown Loop','Fremont Street Experience / Main Street','Las Vegas North Premium Outlets — S Grand Central Parkway')],(15,35),(0,0),'USD','https://www.lasvegasnevada.gov/Residents/Parking-Transportation/Downtown-Loop',['loop'],basis='City-operated Downtown Loop is free; journey time depends on the loop and wait.')
add('anaheim-to-desert-hills-premium-outlets-tour','desert-hills-premium-outlets','city_center','anaheim','shuttle','Anaheim Tour Company',[('Desert Hills shopping tour','Anaheim hotel pickup (booking confirmation)','Desert Hills Premium Outlets')],(75,90),(79,79),'USD','https://anaheimtourcompany.com/la-hollywood-tours/desert-hills-premium-outlets-shopping-tour/',['reserve','anaheim','bookingFees'],unit='roundTrip',basis='Published adult round-trip tour price USD 79; child and group prices differ. One-way driving estimate; the full shopping excursion takes about nine hours.')
add('dublin-pleasanton-bart-to-san-francisco-premium-outlets','san-francisco-premium-outlets','station','dublin-pleasanton-bart','bus','Wheels (LAVTA)',[('14','Dublin/Pleasanton BART Station','San Francisco Premium Outlets / Livermore Outlets Drive')],(15,30),(2.5,2.5),'USD','https://www.wheelsbus.com/routes/route-14/',['bartExtra'],sources=['https://www.wheelsbus.com/fares/'],basis='Wheels adult cash single fare USD 2.50; BART travel to the station is separate. Transfer credit may reduce the fare with Clipper.')
add('siam-paragon-to-siam-premium-outlets-shuttle','siam-premium-outlets','city_center','siam-paragon','shuttle','Siam Premium Outlets / Trip CS',[('Siam Paragon shuttle','Siam Paragon — Gate 1, South Wing, G Floor (Lock Box / Bangkok Bank)','Siam Premium Outlets — 7-Eleven / Entrance A')],(60,90),(150,150),'THB','https://www.siampremiumoutlets.com/en/getting_there',['reserve','siam'],basis='Published THB 150 one-way fare. LINE @tripcs or +66 80 924 3300 for reservations. Outbound 10:00/14:00; return 12:00/16:00 at verification.')
add('hkg-to-citygate-outlets-bus','citygate-outlets','airport','HKG','bus','Citybus / Long Win Bus',[('S1','Hong Kong Airport — Terminal 1 (Cheong Tat Road)','Tung Chung Station / Citygate Outlets')],(10,20),(3.7,3.7),'HKD','https://www.citygateoutlets.com.hk/en/visit/get-here/',['s1'],faretype='estimated',sources=['https://hkbus.app/en/route/s1-1-tung-chung-station-airport-%28circular%29'],basis='Route confirmed by outlet; HKD 3.70 from current third-party route data. Fare is marked estimated pending direct operator confirmation; it is for S1 only, not S64.')
add('central-hong-kong-to-citygate-outlets-mtr','citygate-outlets','city_center','hong-kong-station','metro','MTR',[('Tung Chung Line','Hong Kong Station','Tung Chung Station — Exit C')],(30,40),(24.3,28),'HKD','https://www.mtr.com.hk/en/customer/tickets/index.php',['mtrTicket'],sources=['https://www.mtr.com.hk/archive/ch/pdf/1_Metro_Fare_Matrix_FAM2024_Master_v3.pdf','https://www.mtr.com.hk/archive/ch/pdf/fam2024/sjst_mtr_fare_2024.pdf'],basis='Adult Hong Kong–Tung Chung: HKD 24.30 Octopus/contactless, HKD 28 single journey ticket; official fare matrices page 7 currently linked from MTR fare pages.')
for gid,origin,originid,stop,cost,dur in [('tpe-to-mitsui-outlet-park-linkou-airport-mrt','airport','TPE','A12 Airport Terminal 1 / A13 Airport Terminal 2',60,(25,40)),('taipei-main-station-to-mitsui-outlet-park-linkou','city_center','taipei-main-station','A1 Taipei Main Station',75,(40,50))]:
 add(gid,'mitsui-outlet-park-linkou',origin,originid,'train','Taoyuan Metro',[('Airport MRT Commuter',stop,'A9 Linkou Station')],dur,(cost,cost),'TWD','https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/road.html',['commuter','linkouWalk'],sources=['https://www.tymetro.com.tw/tymetro-new/en/_images/document/travel-guide/price.pdf','https://www.mitsui-shopping-park.com.tw/mop/linkou/en/access.html'],basis='Official station fare matrix: A1–A9 TWD 75; A12/A13–A9 TWD 60. Duration includes 5–10 minutes walking; express trains skip A9, so use a commuter service.')
yurl='https://app.premiumoutlets.co.kr/rpage/en/map/index/01'
for sid,start,legs,dur in [('myeongdong','Myeongdong',[('Line 4','Myeongdong','Chungmuro'),('Line 3','Chungmuro','Express Bus Terminal')],(110,140)),('hongik-university','Hongik University',[('Line 2','Hongik University','Dangsan'),('Line 9','Dangsan','Express Bus Terminal')],(100,130)),('gangnam','Gangnam',[('Line 2','Gangnam','Gyodae'),('Line 3','Gyodae','Express Bus Terminal')],(100,130))]:
 add(sid+'-to-yeoju-premium-outlets','yeoju-premium-outlets','station',sid+'-station','bus','Seoul Metro / Seoul Express Bus Terminal',legs+[('Yeoju Premium Outlets express','Seoul Express Bus Terminal — Platform 29','Yeoju Premium Outlets')],dur,(8000,10000),'KRW',yurl,['reserve','budgetTransit'],faretype='estimated',basis='Planning budget combines the outlet-published KRW 6,400 express bus segment with the feeder metro fare and distance supplements. Not an operator through-ticket price.')
purl='https://app.premiumoutlets.co.kr/rpage/en/map/index/02'
add('hongik-university-to-paju-premium-outlets','paju-premium-outlets','station','hongik-university-station','bus','Gyeonggi Bus (G-Bus)',[('2200','Hongik University — Exit 1','Paju Premium Outlets')],(65,90),(3200,3400),'KRW',purl,['budgetTransit'],faretype='estimated',sources=['https://gits.gg.go.kr/'],basis='Planning range around the October 2025 Gyeonggi metropolitan-bus adult base fare KRW 3,200; payment method and future fare changes may differ.')
add('myeongdong-to-paju-premium-outlets','paju-premium-outlets','station','myeongdong-station','bus','Seoul Metro / Gyeonggi Bus',[('Line 4','Myeongdong','Seoul Station'),('AREX (all-stop)','Seoul Station','Hongik University — Exit 1'),('2200','Hongik University — Exit 1','Paju Premium Outlets')],(95,125),(4500,6000),'KRW',purl,['budgetTransit'],faretype='estimated',basis='Planning budget includes metro/AREX feeder travel plus bus 2200; Myeongdong is Line 4, not Line 2. Actual transfer/distance charges depend on payment method.')
add('incheon-airport-to-paju-premium-outlets','paju-premium-outlets','airport','ICN','bus','Airport Limousine / Gyeonggi Bus',[('6002','Incheon Airport — T1/T2 airport bus area','Hapjeong / Holt Children’s Welfare Society'),('2200','Hapjeong','Paju Premium Outlets')],(120,165),(20200,22000),'KRW',purl,['budgetTransit'],faretype='estimated',recommended=False,sources=['https://www.airportlimousine.co.kr/en/sub/sub02_01.php','https://www.airportlimousine.co.kr/en/sub/sub01.php?cat_no=2'],basis='Budget combines official KRW 17,000 airport limousine fare with around KRW 3,200 bus 2200; transfers are paid separately. Allow for terminal and traffic differences.')
burl='https://app.premiumoutlets.co.kr/rpage/en/map/index/03'
for gid,origin,oid,mode,legs,dur,fare in [
('bujeon','station','bujeon-station','train',[('Donghae Line','Bujeon','Jwacheon'),('302','Jwacheon','Busan Premium Outlets')],(75,105),(3500,5000)),
('haeundae','city_center','haeundae','bus',[('1003','Haeundae Beach','Gijang Telephone Office'),('8','Gijang Telephone Office','Busan Premium Outlets')],(80,110),(3500,5500)),
('gimhae-airport','airport','PUS','bus',[('307','Gimhae Airport','Dongnae'),('3008','Dongnae','Busan Premium Outlets')],(130,165),(4000,6500))]:
 add(gid+'-to-busan-premium-outlets','busan-premium-outlets',origin,oid,mode,'Busan Transit / KORAIL',legs,dur,fare,'KRW',burl,['budgetTransit'],faretype='estimated',recommended=gid=='bujeon',sources=['https://www.busan.go.kr/eng/index'],basis='Planning budget for the stated two-leg route, allowing separate cash fares and distance charges. Busan regular/express fares differ; transfer discounts may lower the total. Not a verified operator through fare.')
murl='https://www.premiumoutlets.com.my/genting-highlands-premium-outlets/directions'
add('kl-sentral-to-genting-highlands-premium-outlets','genting-highlands-premium-outlets','station','kl-sentral','bus','Genting Express',[('Genting Express','KL Sentral — Lower Ground Floor bus counter','Awana Bus Terminal')],(60,90),(10,10),'MYR',murl,['awana'],basis='Outlet-published adult one-way bus-only fare MYR 10; cable car is separate and is not needed to reach the outlet.')
add('klia-to-genting-highlands-premium-outlets','genting-highlands-premium-outlets','airport','KUL','bus','Genting Express',[('Genting Express','KLIA Terminal 1 / Terminal 2 bus counter','Awana Bus Terminal')],(120,180),(35,35),'MYR',murl,['awana'],recommended=False,basis='Outlet-published adult one-way fare MYR 35. Duration is a planning range including terminal differences and traffic.')
add('kuala-lumpur-to-genting-highlands-premium-outlets-taxi','genting-highlands-premium-outlets','city_center','kuala-lumpur','taxi','Licensed taxi / ride-hailing',[('Taxi / ride-hailing','Kuala Lumpur city centre','Genting Highlands Premium Outlets — Awana')],(45,90),(90,150),'MYR',murl,['taxiQuote'],faretype='estimated',unit='vehicle',recommended=False,sources=['https://www.rome2rio.com/s/Kuala-Lumpur/Genting-Highlands'],basis='Indicative vehicle budget, not a metered-fare promise; a third-party route estimate is around MYR 90–140. Rounded contingency upper bound MYR 150 excludes tolls, waiting and surge pricing.')
text='''import type { TransportationGuide, TransportationType } from "./transportationGuides";
export type ExpansionRoute = {
 guideId: string; outletId: string; originType: TransportationGuide["originType"]; originId: string;
 mode: TransportationType; provider: string; legs: { line: string; fromStop: string; toStop: string }[];
 durationMin: number; durationMax: number; fareMin: number; fareMax: number; currency: string;
 fareAccuracy: "exact" | "estimated"; fareUnit: "oneWay" | "roundTrip" | "roundTripFrom" | "vehicle";
 officialProviderUrl: string; notes: string[]; recommended: boolean; checkedAt: string; sources: string[]; fareBasis: string;
};
export const expansionRoutes: ExpansionRoute[] = '''+json.dumps(routes,ensure_ascii=False,indent=2)+';\n'
(ROOT/'src/constants/expansionTransportationData.ts').write_text(text)
(ROOT/'data-sources/outlet-expansion-2026-09/transportation-evidence.json').write_text(json.dumps(routes,ensure_ascii=False,indent=2)+'\n')
print(len(routes),'reviewed routes')
