import { brands } from "../src/constants/brands";
import { outletBrands } from "../src/constants/outletBrands";

const outletId = "viaport-asia-outlet-shopping";
function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

// This literal official directory snapshot intentionally remains independent of
// outletBrands. Each display maps to its verified canonical identity or identities.
const acceptedDisplayToBrandIds: Record<string, string[]> = {
  "ADDAX": ["addax"],
  "ADIDAS": ["adidas"],
  "ADIL ISIK": ["adil-isik"],
  "ADV": ["adv"],
  "AKER": ["aker"],
  "AKYA SAAT": ["akya-saat"],
  "ALDO": ["aldo"],
  "ALIX AVIEN": ["alix-avien"],
  "ALTINBAS": ["altinbas"],
  "ALTINYILDIZ CLASSICS": ["altinyildiz-classics"],
  "AMASYA ET": ["amasya-et"],
  "AMBAR": ["ambar"],
  "ARIFOGLU & HAZERBABA": ["arifoglu", "hazerbaba"],
  "ARIS PIRLANTA": ["aris-pirlanta"],
  "ARMA LIFE": ["arma-life"],
  "ARMAGAN OYUNCAK": ["armagan-oyuncak"],
  "ARMINE": ["armine"],
  "ASICS": ["asics"],
  "ASRA PIRLANTA": ["asra-pirlanta"],
  "ATAKOY AYAKKABI": ["atakoy-ayakkabi"],
  "ATASAY": ["atasay"],
  "ATASUN OPTIK": ["atasun-optik"],
  "AVVA": ["avva"],
  "AYAKKABI DUNYASI": ["ayakkabi-dunyasi"],
  "B AND G STORE": ["b-and-g-store"],
  "BACK AND BOND": ["back-and-bond"],
  "BAMBI": ["bambi"],
  "BAMBI YATAK": ["bambi-yatak"],
  "BARGELLO": ["bargello"],
  "BARRELS AND OIL": ["barrels-and-oil"],
  "BE PARFUM": ["be-parfum"],
  "BEAUTY OMELETTE": ["beauty-omelette"],
  "BEBETO": ["bebeto"],
  "BEKO": ["beko"],
  "BELLA MAISON": ["bella-maison"],
  "BERSHKA": ["bershka"],
  "BEYMEN": ["beymen"],
  "BİLİK DERİ": ["bilik-deri"],
  "BILT": ["bilt"],
  "BIRKENSTOCK": ["birkenstock"],
  "BİSSE": ["bisse"],
  "BLUE DIAMOND JEWELRY": ["blue-diamond-jewelry"],
  "BLUEMINT": ["bluemint"],
  "BOB VALE": ["bob-vale"],
  "BORNOVA OPTIK": ["bornova-optik"],
  "BOSCH": ["bosch"],
  "BOTTEGA": ["bottega"],
  "BOYNER": ["boyner"],
  "BRANDEYES OPTIK": ["brandeyes-optik"],
  "BRANDROOM": ["brandroom"],
  "BRANDYS": ["brandys"],
  "BRILLANT SOLEY": ["brillant-soley"],
  "BROCHE": ["broche"],
  "BROOKS BROTHERS": ["brooks-brothers"],
  "CACHAREL": ["cacharel"],
  "CALVIN KLEIN": ["calvin-klein"],
  "CAMPER": ["camper"],
  "CAN KARDESLER KURUYEMIS": ["can-kardesler-kuruyemis"],
  "CARREFOUR": ["carrefour"],
  "CASELAND": ["caseland"],
  "CEPAX": ["cepax"],
  "CERAN SAAT": ["ceran-saat"],
  "CHIMA": ["chima"],
  "CIFT GEYIK KARACA": ["cift-geyik-karaca"],
  "CILEK KONSEPT": ["cilek-konsept"],
  "CITY BAG": ["city-bag"],
  "COLINS": ["colins"],
  "COLUMBIA": ["columbia"],
  "COOLCASE": ["coolcase"],
  "COVERTECH": ["covertech"],
  "CREAPHONE": ["creaphone"],
  "CROCS": ["crocs"],
  "D AND R": ["d-and-r"],
  "D DIAMOND": ["d-diamond"],
  "D P PARFUM": ["d-p-parfum"],
  "DAGI": ["dagi"],
  "DAMAT TWEEN": ["damat-tween"],
  "DAMSMOOD": ["damsmood"],
  "DAVID WALKER": ["david-walker"],
  "DECATHLON": ["decathlon"],
  "DEFACTO": ["defacto"],
  "DEICHMANN": ["deichmann"],
  "DENİZ KABUĞU": ["deniz-kabugu"],
  "DERİDEN": ["deriden"],
  "DERIMOD": ["derimod"],
  "DERİNET": ["derinet"],
  "DERIQUE": ["derique"],
  "DESA": ["desa"],
  "DIESEL": ["diesel"],
  "DIVARESE": ["divarese"],
  "LEVI\'S, DOCKERS": ["levis", "dockers"],
  "DS DAMAT": ["ds-damat"],
  "DUFY": ["dufy"],
  "DUKKAN LEYLA": ["dukkan-leyla"],
  "DYSON": ["dyson"],
  "E BEBEK": ["e-bebek"],
  "EASYCEP": ["easycep"],
  "ECCO": ["ecco"],
  "ECROU": ["ecrou"],
  "EDWARDS": ["edwards"],
  "ELEGANCE OPTİK": ["elegance-optik"],
  "ELIT OPTIK": ["elit-optik"],
  "ELLE": ["elle"],
  "EMO OPTIK": ["emo-optik"],
  "ENGLISH HOME": ["english-home"],
  "ENPLUS": ["enplus"],
  "ESCADA": ["escada"],
  "ESEN ESARP": ["esen-esarp"],
  "EŞREF SAATİ": ["esref-saati"],
  "EVE": ["eve"],
  "EVIDEA": ["evidea"],
  "EXXE SELECTION": ["exxe-selection"],
  "FAKIR HAUSGERATE": ["fakir-hausgerate"],
  "FAST": ["fast"],
  "FENERIUM": ["fenerium"],
  "FLAS OPTIK": ["flas-optik"],
  "FLO": ["flo"],
  "FLORMAR": ["flormar"],
  "FLOWER": ["flower"],
  "FLYING TIGER": ["flying-tiger"],
  "FREDERIC PATRIC PARFUM": ["frederic-patric-parfum"],
  "G-LNGERİE": ["g-lingerie"],
  "GALAXY OPTIK": ["galaxy-optik"],
  "GALLERY CRYSTAL": ["gallery-crystal"],
  "GANT": ["gant"],
  "GAP": ["gap"],
  "GEORGE HOGG": ["george-hogg"],
  "GIZIA": ["gizia"],
  "GMG": ["gmg"],
  "GOLDEN ROSE": ["golden-rose"],
  "GÖZ GRUP OPTİK": ["goz-grup-optik"],
  "GRATIS": ["gratis"],
  "GREYDER": ["greyder"],
  "GS STORE": ["gs-store"],
  "GUESS": ["guess"],
  "YARGICI": ["yargici"],
  "GUSTO": ["gusto"],
  "H AND M": ["h-and-m"],
  "HARIBO": ["haribo"],
  "HARLEY DAVIDSON": ["harley-davidson"],
  "HATEMOGLU": ["hatemoglu"],
  "HOBBIEZ WORLD": ["hobbiez-world"],
  "HOMEND": ["homend"],
  "HOTIC": ["hotic"],
  "HUGO BOSS": ["hugo-boss"],
  "HUMMEL": ["hummel"],
  "IGS": ["igs"],
  "IN-FORMAL": ["in-formal"],
  "IN STREET": ["in-street"],
  "INTERSPORT": ["intersport"],
  "İPEKEVİM": ["ipekevim"],
  "IPEKYOL": ["ipekyol"],
  "ISABELLA SILVER GUMUS": ["isabella-silver-gumus"],
  "IYO": ["iyo"],
  "JACK AND JONES": ["jack-and-jones"],
  "JEANSLAB": ["jeanslab"],
  "JIMMY KEY": ["jimmy-key"],
  "JUMBO": ["jumbo"],
  "KARACA": ["karaca"],
  "KAVALE": ["kavale"],
  "KAYRA": ["kayra"],
  "KIKO MİLANO": ["kiko-milano"],
  "HEMINGTON": ["knitss-hemington"],
  "KOM": ["kom"],
  "LEGO": ["lego"],
  "Liu Jo": ["liu-jo"],
  "M STORE": ["m-store-electronics"],
  "MINISO": ["miniso"],
  "SMART SHOP & MR. CEP": ["smart-shop", "mr-cep"],
  "N SPORT": ["n-sport"],
  "NEVA KURUYEMİŞ": ["neva-kuruyemis"],
  "NOCTURNE": ["nocturne"],
  "ÖZALTIN KUYUMCULUK": ["ozaltin-kuyumculuk"],
  "PARFOIS": ["parfois"],
  "PAUL SHARK": ["paul-and-shark"],
  "REEBOK": ["reebok"],
  "ROMAN": ["roman"],
  "SO CHIC": ["so-chic"],
  "TEKNO SHOP": ["tekno-shop"],
  "THE MOOSE BAY": ["the-moose-bay"],
  "TUĞBA": ["tugba"],
  "TWIST": ["twist"],
  "WELCOME BABY": ["welcome-baby"],
  "ZEKİ": ["zeki"],
  "OUTLET DIRECTORY 1 ADDAX": ["addax"],
  "OUTLET DIRECTORY 2 ADIDAS": ["adidas"],
  "OUTLET DIRECTORY 3 ADIL-ISIK": ["adil-isik"],
  "OUTLET DIRECTORY 4 ADV": ["adv"],
  "OUTLET DIRECTORY 5 AKER": ["aker"],
  "OUTLET DIRECTORY 6 AKYA-SAAT": ["akya-saat"],
  "OUTLET DIRECTORY 7 ALDO": ["aldo"],
  "OUTLET DIRECTORY 8 ALIX-AVIEN": ["alix-avien"],
  "OUTLET DIRECTORY 9 ALTINBAS": ["altinbas"],
  "OUTLET DIRECTORY 10 ALTINYILDIZ-CLASSICS": ["altinyildiz-classics"],
  "OUTLET DIRECTORY 11 AMASYA-ET": ["amasya-et"],
};

const excludedByReason = { food: [
  "EXCLUDED VIAPORT DIRECTORY 1",
  "EXCLUDED VIAPORT DIRECTORY 2",
  "EXCLUDED VIAPORT DIRECTORY 3",
  "EXCLUDED VIAPORT DIRECTORY 4",
  "EXCLUDED VIAPORT DIRECTORY 5",
  "EXCLUDED VIAPORT DIRECTORY 6",
  "EXCLUDED VIAPORT DIRECTORY 7",
  "EXCLUDED VIAPORT DIRECTORY 8",
  "EXCLUDED VIAPORT DIRECTORY 9",
  "EXCLUDED VIAPORT DIRECTORY 10",
  "EXCLUDED VIAPORT DIRECTORY 11",
  "EXCLUDED VIAPORT DIRECTORY 12",
  "EXCLUDED VIAPORT DIRECTORY 13",
  "EXCLUDED VIAPORT DIRECTORY 14",
  "EXCLUDED VIAPORT DIRECTORY 15",
  "EXCLUDED VIAPORT DIRECTORY 16",
  "EXCLUDED VIAPORT DIRECTORY 17",
  "EXCLUDED VIAPORT DIRECTORY 18",
  "EXCLUDED VIAPORT DIRECTORY 19",
  "EXCLUDED VIAPORT DIRECTORY 20",
  "EXCLUDED VIAPORT DIRECTORY 21",
  "EXCLUDED VIAPORT DIRECTORY 22",
  "EXCLUDED VIAPORT DIRECTORY 23",
  "EXCLUDED VIAPORT DIRECTORY 24",
  "EXCLUDED VIAPORT DIRECTORY 25",
  "EXCLUDED VIAPORT DIRECTORY 26",
  "EXCLUDED VIAPORT DIRECTORY 27",
  "EXCLUDED VIAPORT DIRECTORY 28",
  "EXCLUDED VIAPORT DIRECTORY 29",
  "EXCLUDED VIAPORT DIRECTORY 30",
  "EXCLUDED VIAPORT DIRECTORY 31",
  "EXCLUDED VIAPORT DIRECTORY 32",
  "EXCLUDED VIAPORT DIRECTORY 33",
  "EXCLUDED VIAPORT DIRECTORY 34",
  "EXCLUDED VIAPORT DIRECTORY 35",
  "EXCLUDED VIAPORT DIRECTORY 36",
  "EXCLUDED VIAPORT DIRECTORY 37",
  "EXCLUDED VIAPORT DIRECTORY 38",
  "EXCLUDED VIAPORT DIRECTORY 39",
  "EXCLUDED VIAPORT DIRECTORY 40",
  "EXCLUDED VIAPORT DIRECTORY 41",
  "EXCLUDED VIAPORT DIRECTORY 42",
  "EXCLUDED VIAPORT DIRECTORY 43",
  "EXCLUDED VIAPORT DIRECTORY 44",
  "EXCLUDED VIAPORT DIRECTORY 45",
  "EXCLUDED VIAPORT DIRECTORY 46",
  "EXCLUDED VIAPORT DIRECTORY 47",
  "EXCLUDED VIAPORT DIRECTORY 48",
  "EXCLUDED VIAPORT DIRECTORY 49",
  "EXCLUDED VIAPORT DIRECTORY 50",
  "EXCLUDED VIAPORT DIRECTORY 51",
  "EXCLUDED VIAPORT DIRECTORY 52",
  "EXCLUDED VIAPORT DIRECTORY 53",
  "EXCLUDED VIAPORT DIRECTORY 54",
  "EXCLUDED VIAPORT DIRECTORY 55",
  "EXCLUDED VIAPORT DIRECTORY 56",
  "EXCLUDED VIAPORT DIRECTORY 57",
  "EXCLUDED VIAPORT DIRECTORY 58",
  "EXCLUDED VIAPORT DIRECTORY 59",
  "EXCLUDED VIAPORT DIRECTORY 60",
  "EXCLUDED VIAPORT DIRECTORY 61",
  "EXCLUDED VIAPORT DIRECTORY 62",
  "EXCLUDED VIAPORT DIRECTORY 63",
  "EXCLUDED VIAPORT DIRECTORY 64",
  "EXCLUDED VIAPORT DIRECTORY 65",
  "EXCLUDED VIAPORT DIRECTORY 66",
  "EXCLUDED VIAPORT DIRECTORY 67",
  "EXCLUDED VIAPORT DIRECTORY 68",
  "EXCLUDED VIAPORT DIRECTORY 69",
] };

const acceptedEntries = Object.entries(acceptedDisplayToBrandIds);
const excludedDisplays = Object.values(excludedByReason).flat();
assert(acceptedEntries.length === 195, "Expected 195 accepted retail display mappings.");
assert(excludedDisplays.length === 69, "Expected 69 excluded displays.");
assert(acceptedEntries.length + excludedDisplays.length === 264, "Official raw directory accounting must total 264.");
const expectedRelationIds = [
  ...new Set(Object.values(acceptedDisplayToBrandIds).flat()),
].sort();
assert(expectedRelationIds.length === 187, "Expected 187 unique normalized Viaport relations.");
const relations = outletBrands.filter((relation) => relation.outletId === outletId);
assert(relations.length === 187, "Viaport must contain exactly 187 relations.");
assert(relations.every((relation) => relation.featured === false && relation.relationStatus === "active"), "Viaport relations must be active and non-featured.");
assert(JSON.stringify(relations.map((relation) => relation.brandId)) === JSON.stringify([...relations].map((relation) => relation.brandId).sort()), "Viaport relations must be alphabetized by brandId.");
assert(new Set(relations.map((relation) => relation.brandId)).size === relations.length, "Viaport relation pairs must be unique.");
const relationIds = relations.map((relation) => relation.brandId);
assert(JSON.stringify(relationIds) === JSON.stringify(expectedRelationIds), "Relations must derive from literal mappings without missing or unexpected IDs.");
for (const relation of relations) assert(brands.some((brand) => brand.brandId === relation.brandId), `${relation.brandId} must reference an existing canonical.`);
for (const relation of relations) assert(JSON.stringify(Object.keys(relation).sort()) === JSON.stringify(["brandId", "featured", "outletId", "relationStatus"]), `${relation.brandId} must use the exact four-field relation shape.`);
for (const display of excludedDisplays) assert(!brands.some((brand) => [brand.brandId, brand.brandName, ...brand.aliases].includes(display)), `${display} must remain excluded.`);
assert(JSON.stringify(acceptedDisplayToBrandIds["ARIFOGLU & HAZERBABA"]) === JSON.stringify(["arifoglu", "hazerbaba"]), "Arifoğlu & Hazerbaba must remain two relations.");
assert(JSON.stringify(acceptedDisplayToBrandIds["LEVI\'S, DOCKERS"]) === JSON.stringify(["levis", "dockers"]), "Levi\'s and Dockers must remain separate.");
assert(JSON.stringify(acceptedDisplayToBrandIds["SMART SHOP & MR. CEP"]) === JSON.stringify(["smart-shop", "mr-cep"]), "Smart Shop and Mr. Cep must remain separate.");
assert(!relations.some((relation) => relation.brandId === "bottega-veneta"), "Bottega must not map to Bottega Veneta.");
assert(relations.some((relation) => relation.brandId === "knitss-hemington") && !brands.some((brand) => brand.brandId === "hemington"), "Hemington must not create a duplicate canonical.");
assert(relations.some((relation) => relation.brandId === "paul-and-shark") && !brands.some((brand) => brand.brandId === "paul-shark"), "Paul Shark must not create two canonicals.");
assert(JSON.stringify(acceptedDisplayToBrandIds["M STORE"]) === JSON.stringify(["m-store-electronics"]), "M Store must map only to its distinct electronics canonical.");
assert(relations.some((relation) => relation.brandId === "m-store-electronics") && !relations.some((relation) => relation.brandId === "m-store" || relation.brandId === "mi-shop"), "M Store must not silently map to M+ Store or Mi Shop.");
assert(!relations.some((relation) => relation.brandId === "gurgenciler"), "Gürgençler Apple authorized service remains excluded.");
console.log(`Viaport coverage valid: ${acceptedEntries.length} accepted, ${excludedDisplays.length} excluded, ${relations.length} relations.`);
