import { brands } from "../src/constants/brands";
import { outletBrands } from "../src/constants/outletBrands";

const outletId = "viaport-asia-outlet-shopping";

const acceptedDisplayToBrandIds: Record<string, string[]> = {
  "ARİŞ PIRLANTA": ["aris-pirlanta"],
  "ASICS MARLIN": ["asics"],
  "ALTINYILDIZ": ["altinyildiz-classics"],
  "AYAKKABI DUNYASI": ["ayakkabi-dunyasi"],
  "ARMA LIFE": ["arma-life"],
  "ATASAY": ["atasay"],
  "ATASAY-2": ["atasay"],
  "ATASUN - 2": ["atasun-optik"],
  "SOLARIS ATASUN STANDI": ["atasun-optik"],
  "AVVA": ["avva"],
  "ALTINBAŞ": ["altinbas"],
  "ADİDAS": ["adidas"],
  "AKER": ["aker"],
  "BAMBİ": ["bambi"],
  "BENETTON": ["united-colors-of-benetton"],
  "KARTAL YUVASI": ["kartal-yuvasi"],
  "BEYMEN": ["beymen"],
  "BEYMEN BUSINESS": ["beymen"],
  "BEYMEN CLUB": ["beymen"],
  "BG-STORE": ["b-and-g-store"],
  "BIRKENSTOCK": ["birkenstock"],
  "BLUE DIAMOND": ["blue-diamond-jewelry"],
  "BOYNER": ["boyner"],
  "BRANDY'S": ["brandys"],
  "BROOKS BROTHERS": ["brooks-brothers"],
  "CACHAREL": ["cacharel"],
  "CAMPER": ["camper"],
  "CALVİN KLEİN": ["calvin-klein"],
  "COLIN'S": ["colins"],
  "COLUMBİA": ["columbia"],
  "CHIMA": ["chima"],
  "ÇİFT GEYİK KARACA": ["cift-geyik-karaca"],
  "ÇİLEK KONSEPT": ["cilek-konsept"],
  "DAGİ": ["dagi"],
  "DAMAT TWEEN": ["damat-tween"],
  "D'S DAMAT": ["ds-damat"],
  "DEFACTO FİT": ["defacto"],
  "DEFACTO-2": ["defacto"],
  "DEICHMANN": ["deichmann"],
  "DERİMOD": ["derimod"],
  "DESA": ["desa"],
  "DECATHLON": ["decathlon"],
  "DUFY": ["dufy"],
  "D DIAMOND": ["d-diamond"],
  "D&R": ["d-and-r"],
  "D&P PERFUMUM": ["d-p-parfum"],
  "E-BEBEK": ["e-bebek"],
  "ELLE SHOES": ["elle"],
  "ENGLISH HOME": ["english-home"],
  "ECCO": ["ecco"],
  "EVİDEA": ["evidea"],
  "EVE SHOP": ["eve"],
  "FENERIUM": ["fenerium"],
  "FLO": ["flo"],
  "FLORMAR": ["flormar"],
  "FLYİNG TİGER": ["flying-tiger"],
  "GANT": ["gant"],
  "GOLDEN ROSE": ["golden-rose"],
  "GREYDER": ["greyder"],
  "GUESS": ["guess"],
  "GUESS AKSESUAR": ["guess"],
  "GRATİS": ["gratis"],
  "GS STORE": ["gs-store"],
  "HATEMOĞLU": ["hatemoglu"],
  "HUMMEL": ["hummel"],
  "IPEKYOL": ["ipekyol"],
  "INTERSPORT": ["intersport"],
  "JACK&JONES": ["jack-and-jones"],
  "KARACA CONTAINER": ["karaca"],
  "KARACA HOME": ["karaca"],
  "KOTON": ["koton"],
  "KİĞILI": ["kigili"],
  "TAMER TANCA": ["tamer-tanca"],
  "KOÇTAŞ": ["koctas"],
  "KOCAK": ["kocak"],
  "KONYALI SAAT": ["konyali-saat"],
  "LCW, LC WAIKIKI - 1, X-SIDE": ["lc-waikiki"],
  "LC WAIKIKI KİDS": ["lc-waikiki"],
  "LEE WRANGLER": ["lee", "wrangler"],
  "LES BENJAMİNS": ["les-benjamins"],
  "LITTLE BIG (LTB)": ["ltb"],
  "LİZAY": ["lizay"],
  "MANGO/MANGO MAN": ["mango"],
  "MADAME COCO": ["madame-coco"],
  "MAVİ JEANS - 1": ["mavi"],
  "MAVİ JEANS - 2": ["mavi"],
  "MİGROS": ["migros"],
  "MEDİA MARKT": ["media-markt"],
  "MUDO": ["mudo"],
  "NETWORK": ["network"],
  "NEW BALANCE": ["new-balance"],
  "NIKE": ["nike"],
  "OCCASİON": ["occasion"],
  "ÖZDİLEK": ["ozdilek"],
  "OPMAR OPTİK": ["opmar-optik"],
  "ADL": ["adil-isik"],
  "PANÇO": ["panco"],
  "PANDORA": ["pandora"],
  "PENTI": ["penti"],
  "PENTI - 2": ["penti"],
  "PERFUME POİNT": ["perfume-point"],
  "PERFUME POİNT 2": ["perfume-point"],
  "PIERRE CARDİN": ["pierre-cardin"],
  "PUMA": ["puma"],
  "RAMSEY-KIP": ["ramsey", "kip"],
  "ROSSMANN": ["rossmann"],
  "RÜZGAR ALAZ": ["ruzgar-alaz-aksesuar"],
  "SARAR": ["sarar"],
  "SAMSUNG": ["samsung"],
  "SAAT & SAAT": ["saat-saat"],
  "SAMSONITE": ["samsonite"],
  "SCHAFER": ["schafer"],
  "SÜVARİ": ["suvari"],
  "SUPERSTEP": ["superstep"],
  "SAVE THE DUCK": ["save-the-duck"],
  "SUWEN": ["suwen"],
  "SKECHERS-VAULT": ["skechers"],
  "SPORT IN STREET": ["in-street"],
  "SPX": ["spx"],
  "SUNGLASS HUT": ["sunglass-hut"],
  "SWAROVSKI": ["swarovski"],
  "VANS": ["vans"],
  "TOMMY HILFIGER": ["tommy-hilfiger"],
  "THE NORTH FACE": ["the-north-face"],
  "TERGAN": ["tergan"],
  "TEFAL HOME & COOK": ["tefal"],
  "THE COSMETICS": ["the-cosmetics-company-store"],
  "TURKCELL": ["turkcell"],
  "TOYZZ SHOP": ["toyzz-shop"],
  "U.S. POLO - 1": ["u-s-polo-assn"],
  "U.S. POLO - 2": ["u-s-polo-assn"],
  "U.S POLO KİDS": ["u-s-polo-assn"],
  "UNDER ARMOUR": ["under-armour"],
  "VAKKO": ["vakko"],
  "VODAFONE": ["vodafone"],
  "WATSONS": ["watsons"],
  "YATAŞ": ["yatas"],
  "YVES ROCHER": ["yves-rocher"],
  "YARGICI": ["yargici"],
  "ZEN PIRLANTA": ["zen-diamond"],
  "LUFİAN": ["lufian"],
  "MAD PERFUMEUR": ["mad-parfum"],
};

const excludedDisplays = [
  "1401 COFFEE",
  "ACTİON WORLD",
  "ARBY'S",
  "BAYDÖNER",
  "BEDESTEN TERZİ",
  "BEREKET DÖNER",
  "BOWLROOM",
  "BURGER KING",
  "BURGER KING - 2",
  "BURGER YİYELİM",
  "BURSA KEBAP EVİ",
  "CAJUN CORNER",
  "CAPTAIN BURGER",
  "CAPTAIN DONER",
  "CHEF KAVURMA",
  "COLOMBİA COFFEE",
  "DML TURK KAHVESI",
  "DOYUYO",
  "DRY SERVICE KURU TEMİZLEME",
  "DÜRÜMLE",
  "ECZANE VIAPORT",
  "ETS TUR",
  "FİRUZ BAKLAVA",
  "GARANTİ BBVA BANKASI",
  "GREEN SALADS",
  "GREENWICH COFFEE",
  "GÜNAYDIN KÖFTE & DÖNER",
  "GÜRGENÇLER APPLE YET. SERVİS SAĞ.",
  "HACIOĞLU",
  "HAPPY MOON'S",
  "HD İSKENDER - 2",
  "HELVACI ALİ",
  "HUQQABAZ",
  "ILGAZ EMANET",
  "ISLAK BURGER",
  "JOLLY TUR",
  "KRİSPY KREME",
  "MADO",
  "MAGNOLİA SHOP",
  "MAKARNAM",
  "MAYDONOZ DÖNER",
  "MC DONALD'S",
  "MISTIK USTA TATLI & DONDURMA",
  "PACKET BURGER",
  "PARİBU CINEVERSE",
  "POLİGONYA",
  "POPEYES",
  "POWER PLATE",
  "PİDEM",
  "PİLAV TANEM",
  "SALOON BURGER",
  "SAS WAX",
  "SERANDER CAFE",
  "SOĞANLIK DÖVİZ ALTIN",
  "STARBUCKS",
  "SÜTLİYE",
  "SİMİT SARAYI",
  "SİMİT SARAYI - 2",
  "SİMİT SARAYI - 3",
  "TAKSİ DURAĞI",
  "TAVUK DÜNYASI",
  "THE CO COFFEE",
  "THE CO COFFEE 2",
  "TOBACCO SHOP",
  "USTA ANAHTAR",
  "USTA DÖNERCİ SBARRO",
  "YAPI KREDI BANKASI",
  "ZİYAFE KAYSERİ MUTFAĞI",
  "ÇİKOLATA SARAYI & MAKARNA FIRINI",
] as const;

const unresolvedRetailDisplays = [
  "ASRA PIRLANTA",
  "ARIFOGLU & HAZERBABA",
  "BELLA MAISON",
  "BİLİK DERİ",
  "BİSSE",
  "BLUEMINT",
  "BOTTEGA",
  "BE PARFUM",
  "BROCHE",
  "ADDAX",
  "CROCS",
  "DENİZ KABUĞU",
  "DIESEL",
  "DERİDEN",
  "DERİNET",
  "ESCADA",
  "ELEGANCE OPTİK",
  "EŞREF SAATİ",
  "FLOWER",
  "GIZIA",
  "GÖZ GRUP OPTİK",
  "G-LNGERİE",
  "HUGO BOSS",
  "HEMINGTON",
  "HARIBO",
  "İPEKEVİM",
  "IN-FORMAL",
  "KAVALE",
  "KAYRA",
  "KOM",
  "KIKO MİLANO",
  "LEVI'S, DOCKERS",
  "BEBETO",
  "LEGO",
  "Liu Jo",
  "MINISO",
  "M STORE",
  "N SPORT",
  "NOCTURNE",
  "PAUL SHARK",
  "PARFOIS",
  "REEBOK",
  "ROMAN",
  "NEVA KURUYEMİŞ",
  "SO CHIC",
  "ÖZALTIN KUYUMCULUK",
  "SMART SHOP & MR. CEP",
  "TEKNO SHOP",
  "TWIST",
  "TUĞBA",
  "THE MOOSE BAY",
  "ZEKİ",
  "WELCOME BABY",
] as const;

const expectedRelationIds = [
  "adidas",
  "adil-isik",
  "aker",
  "altinbas",
  "altinyildiz-classics",
  "aris-pirlanta",
  "arma-life",
  "asics",
  "atasay",
  "atasun-optik",
  "avva",
  "ayakkabi-dunyasi",
  "b-and-g-store",
  "bambi",
  "beymen",
  "birkenstock",
  "blue-diamond-jewelry",
  "boyner",
  "brandys",
  "brooks-brothers",
  "cacharel",
  "calvin-klein",
  "camper",
  "chima",
  "cift-geyik-karaca",
  "cilek-konsept",
  "colins",
  "columbia",
  "d-and-r",
  "d-diamond",
  "d-p-parfum",
  "dagi",
  "damat-tween",
  "decathlon",
  "defacto",
  "deichmann",
  "derimod",
  "desa",
  "ds-damat",
  "dufy",
  "e-bebek",
  "ecco",
  "elle",
  "english-home",
  "eve",
  "evidea",
  "fenerium",
  "flo",
  "flormar",
  "flying-tiger",
  "gant",
  "golden-rose",
  "gratis",
  "greyder",
  "gs-store",
  "guess",
  "hatemoglu",
  "hummel",
  "in-street",
  "intersport",
  "ipekyol",
  "jack-and-jones",
  "karaca",
  "kartal-yuvasi",
  "kigili",
  "kip",
  "kocak",
  "koctas",
  "konyali-saat",
  "koton",
  "lc-waikiki",
  "lee",
  "les-benjamins",
  "lizay",
  "ltb",
  "lufian",
  "mad-parfum",
  "madame-coco",
  "mango",
  "mavi",
  "media-markt",
  "migros",
  "mudo",
  "network",
  "new-balance",
  "nike",
  "occasion",
  "opmar-optik",
  "ozdilek",
  "panco",
  "pandora",
  "penti",
  "perfume-point",
  "pierre-cardin",
  "puma",
  "ramsey",
  "rossmann",
  "ruzgar-alaz-aksesuar",
  "saat-saat",
  "samsonite",
  "samsung",
  "sarar",
  "save-the-duck",
  "schafer",
  "skechers",
  "spx",
  "sunglass-hut",
  "superstep",
  "suvari",
  "suwen",
  "swarovski",
  "tamer-tanca",
  "tefal",
  "tergan",
  "the-cosmetics-company-store",
  "the-north-face",
  "tommy-hilfiger",
  "toyzz-shop",
  "turkcell",
  "u-s-polo-assn",
  "under-armour",
  "united-colors-of-benetton",
  "vakko",
  "vans",
  "vodafone",
  "watsons",
  "wrangler",
  "yargici",
  "yatas",
  "yves-rocher",
  "zen-diamond",
] as const;

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function normalize(value: string): string {
  return value
    .toLocaleLowerCase("tr-TR")
    .replace(/ı/g, "i")
    .replace(/ç/g, "c")
    .replace(/ğ/g, "g")
    .replace(/ö/g, "o")
    .replace(/ş/g, "s")
    .replace(/ü/g, "u")
    .replace(/[’'´]/g, "")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const rawRows = [
  ...Object.keys(acceptedDisplayToBrandIds),
  ...excludedDisplays,
  ...unresolvedRetailDisplays,
];

assert(Object.keys(acceptedDisplayToBrandIds).length === 142, "Expected 142 mapped official display rows.");
assert(excludedDisplays.length === 69, "Expected 69 excluded official display rows.");
assert(unresolvedRetailDisplays.length === 53, "Expected 53 unresolved retail display rows.");
assert(rawRows.length === 264, "Expected exactly 264 official Viaport directory rows.");
assert(new Set(rawRows).size === 264, "Viaport snapshot display rows must remain unique.");

const mappingRelationIds = [...new Set(Object.values(acceptedDisplayToBrandIds).flat())].sort();
assert(mappingRelationIds.length === 131, "Expected 131 normalized verified relations.");
assert(
  JSON.stringify(mappingRelationIds) === JSON.stringify([...expectedRelationIds]),
  "Literal mapping and expected relation list diverged.",
);

const relations = outletBrands.filter((relation) => relation.outletId === outletId);
const relationIds = relations.map((relation) => relation.brandId);

assert(relations.length === 131, "Expected exactly 131 verified Viaport relations.");
assert(new Set(relationIds).size === relationIds.length, "Viaport relations must be unique.");
assert(
  JSON.stringify(relationIds) === JSON.stringify([...expectedRelationIds]),
  "Viaport relation IDs must exactly match the verified mapping.",
);
assert(
  JSON.stringify(relationIds) === JSON.stringify([...relationIds].sort()),
  "Viaport relation IDs must be alphabetically sorted.",
);

for (const relation of relations) {
  assert(relation.outletId === outletId, "Unexpected outlet ID in Viaport relation.");
  assert(relation.featured === false, `${relation.brandId} must not be featured.`);
  assert(relation.relationStatus === "active", `${relation.brandId} must be active.`);
  assert(
    JSON.stringify(Object.keys(relation).sort()) ===
      JSON.stringify(["brandId", "featured", "outletId", "relationStatus"]),
    `${relation.brandId} relation field set changed.`,
  );
  assert(
    brands.some((brand) => brand.brandId === relation.brandId),
    `${relation.brandId} does not reference an existing canonical brand.`,
  );
}

for (const forbidden of ["burger-king", "starbucks", "gurgenciler", "apple", "simit-sarayi"]) {
  assert(!relationIds.includes(forbidden), `Excluded service or food identity leaked: ${forbidden}.`);
}

const excludedIdentities = new Set(excludedDisplays.map(normalize));
for (const relation of relations) {
  const brand = brands.find((candidate) => candidate.brandId === relation.brandId)!;
  const identities = [brand.brandId, brand.brandName, ...(brand.aliases ?? [])].map(normalize);
  assert(
    identities.every((identity) => !excludedIdentities.has(identity)),
    `Excluded directory identity leaked into relations: ${brand.brandId}.`,
  );
}

for (const [id, expectedCount] of Object.entries({
  "olivium-outlet-center": 94,
  "starcity-outlet": 101,
  "optimum-premium-outlet-istanbul": 112,
  "izmir-optimum": 194,
  "viaport-asia-outlet-shopping": 131,
})) {
  assert(
    outletBrands.filter((relation) => relation.outletId === id).length === expectedCount,
    `${id} relation count changed.`,
  );
}

for (const id of ["212-outlet", "venezia-mega-outlet", "deepo-outlet-center"]) {
  assert(!outletBrands.some((relation) => relation.outletId === id), `${id} must remain empty.`);
}

console.log(
  `Viaport verified existing-canonical coverage valid: ` +
    `${rawRows.length} official rows, ` +
    `${Object.keys(acceptedDisplayToBrandIds).length} mapped displays, ` +
    `${excludedDisplays.length} exclusions, ` +
    `${unresolvedRetailDisplays.length} unresolved retail displays, ` +
    `${relations.length} relations.`,
);
