import assert from "node:assert/strict";
import { brands } from "../src/constants/brands";
import { cities } from "../src/constants/cities";
import { outlets } from "../src/constants/outlets";
import { outletBrands } from "../src/constants/outletBrands";
import { restaurants } from "../src/constants/restaurants";
import { transportation } from "../src/constants/transportation";
import { transportationGuides } from "../src/constants/transportationGuides";

const outletId = "gotemba-premium-outlets";
const azSource = [
  "A Bathing Ape Pirate Store",
  "A.P.C.",
  "Abahouse",
  "Abc-Mart",
  "Ace Bags & Luggage",
  "Acne Studios",
  "Adam et Rope",
  "Adidas",
  "Adidas Golf",
  "Adore",
  "Agete",
  "Agnès b",
  "Aigle",
  "Alexanderwang",
  "Ambush",
  "Ami Paris",
  "Amiri",
  "Anayi",
  "And Per Se",
  "And Wander",
  "Aquascutum",
  "Arc'teryx",
  "Armani",
  "As Know As",
  "Asics",
  "Balenciaga",
  "Bally",
  "Banana Republic",
  "Barbour",
  "Barneys New York",
  "Beams",
  "Blue Label / Black Label Crestbridge",
  "Bonaventura",
  "Bonpoint",
  "Boss",
  "Bottega Veneta",
  "Breitling",
  "Bric’s",
  "Briefing",
  "Brioni",
  "Brooks Brothers",
  "Brunello Cucinelli",
  "Burberry",
  "C.P.Company",
  "Callaway",
  "Calvin Klein",
  "Camper",
  "Canterbury",
  "Casio Watch",
  "Celine",
  "Champion",
  "Chloe",
  "Christian Louboutin",
  "Chums",
  "Ciaopanic",
  "Citizen",
  "Coach",
  "Cole Haan",
  "Coleman",
  "Columbia Sportswear",
  "Converse Tokyo",
  "Cosme Kitchen Village",
  "Cosmetics & Designer Fragrances",
  "Crocs（Push Cart)",
  "DeLonghi",
  "Descente",
  "Descente Store Golf",
  "Diana",
  "Diesel",
  "Dolce＆Gabbana",
  "Dressterior",
  "Dsquared2",
  "Dunhill",
  "Ecco",
  "Edifice",
  "Elendeek",
  "Emmi",
  "Enfold",
  "Etro",
  "Fendi",
  "Ferragamo",
  "Fragrance Outlet",
  "Francfranc",
  "Fray I.D",
  "Freak's Store",
  "Fred Perry",
  "Furla",
  "Gallardagalante",
  "Gap",
  "Gelato Pique",
  "Gianni Chiarini",
  "Ginza Maggy",
  "Givenchy",
  "Graniph",
  "Gucci",
  "Hamilton",
  "Helly Hansen",
  "Herno",
  "Hoka",
  "Iena",
  "Ined",
  "Isaia Napoli",
  "Issey Miyake",
  "Izone New York（Push Cart)",
  "J&M Davidson",
  "J.M.Weston",
  "J.Press",
  "Jil Sander",
  "Jimmy Choo",
  "John Smedley",
  "Journal Standard",
  "Jun",
  "Kaneko Optical",
  "Kanematsu",
  "Kate Spade New York",
  "Kenzo",
  "Kolor",
  "L.L.Bean",
  "Lacoste",
  "Le Creuset",
  "Lego",
  "Lephil",
  "Levi's",
  "Lily Brown",
  "Loewe",
  "Longchamp",
  "Longines",
  "Loro Piana",
  "Lowrys Farm",
  "Lululemon",
  "Mackintosh",
  "Maison Kitsuné",
  "Maison Margiela",
  "Maison Special",
  "Mammut",
  "Manolo Blahnik",
  "Marc Jacobs",
  "Margaret Howell",
  "Marimekko",
  "Mark & Lona",
  "Marni",
  "MaxMara",
  "McGregor",
  "McQueen",
  "Mezzo Piano",
  "Michael Kors",
  "Miki House",
  "Mila Owen",
  "Millet",
  "Molton Brown",
  "Moncler",
  "Montblanc",
  "Moorer",
  "Moussy",
  "Nano・Universe",
  "New Balance",
  "New Balance Golf",
  "Nike",
  "N°21",
  "Oakley",
  "Off-White",
  "Olive des Olive",
  "Onitsuka Tiger",
  "Orobianco",
  "Pandora",
  "Patou",
  "Paul Smith",
  "Pearly Gates",
  "Petit Bateau",
  "Ping",
  "Plaza",
  "Pokemon Store",
  "Polo Ralph Lauren",
  "Polo Ralph Lauren Children",
  "Prada Outlet（Prada/Miu Miu）",
  "Puma",
  "Ray-Ban",
  "Refa",
  "Regal",
  "Replay",
  "Roger Vivier",
  "Ron Herman",
  "Rope Picnic",
  "Royal Copenhagen",
  "Ryu(Push Cart)",
  "SN Nishikawa",
  "Sabon",
  "Saint Laurent",
  "Samantha Thavasa",
  "Samsonite",
  "Sanrio",
  "Scotch Grain",
  "Seiko",
  "Seven-Eleven",
  "Ships",
  "Skechers",
  "Sly",
  "Snidel",
  "Soccer Junky",
  "Spick & Span",
  "Star Jewelry",
  "Stella McCartney",
  "Stone Island",
  "Stressless",
  "Stylemixer",
  "Swarovski",
  "Swatch",
  "T-fal",
  "Tag Heuer",
  "Takashimaya",
  "Takeo Kikuchi",
  "Tasaki",
  "Tatras",
  "TaylorMade",
  "The Cosmetics Company Store",
  "The North Face",
  "Theory",
  "Thom Browne",
  "Three",
  "Timberland",
  "Tissot",
  "Tod's",
  "Tom Ford",
  "Tommy Hilfiger",
  "Tomorrowland",
  "Topologie",
  "Tory Burch",
  "Tradies",
  "Traditional Weatherwear",
  "Trinity(Push Cart)",
  "Triumph",
  "Tumi",
  "Ugg",
  "Un3d.",
  "Under Armour",
  "United Arrows",
  "Untitled",
  "Urban Research",
  "Valentino",
  "Vendome Aoyama",
  "Verite",
  "Versace",
  "Vivienne Westwood",
  "Wacoal",
  "Wedgwood",
  "Wilson",
  "Wind And Sea",
  "Woolrich",
  "Y-3",
  "Zegna",
  "Zero Halliburton",
  "Zwilling",
  "23Ku"
] as const;
const foodRetailSource = [
  "Enoteca & Cases",
  "Fauchon",
  "Godiva",
  "Haagen Dazs",
  "Kuzefukushouten",
  "Laduree",
  "Lindt Chocolat Café",
  "Pierre Marcolini"
] as const;
const expectedBrandIds = [
  "a-bathing-ape",
  "a-p-c",
  "abahouse",
  "abc-mart",
  "ace-bags-and-luggage",
  "acne-studios",
  "adam-et-rope",
  "adidas",
  "adidas-golf",
  "adore",
  "agete",
  "agnes-b",
  "aigle",
  "alexander-wang",
  "ambush",
  "ami-paris",
  "amiri",
  "anayi",
  "and-per-se",
  "and-wander",
  "aquascutum",
  "arcteryx",
  "armani",
  "as-know-as",
  "asics",
  "balenciaga",
  "bally",
  "banana-republic",
  "barbour",
  "barneys-new-york",
  "beams",
  "blue-label-black-label-crestbridge",
  "bonaventura",
  "bonpoint",
  "boss",
  "bottega-veneta",
  "breitling",
  "brics",
  "briefing",
  "brioni",
  "brooks-brothers",
  "brunello-cucinelli",
  "burberry",
  "c-p-company",
  "callaway-golf",
  "calvin-klein",
  "camper",
  "canterbury",
  "casio-watch",
  "celine",
  "champion",
  "chloe",
  "christian-louboutin",
  "chums",
  "ciaopanic",
  "citizen",
  "coach",
  "cole-haan",
  "coleman",
  "columbia",
  "converse-tokyo",
  "cosme-kitchen-village",
  "cosmetics-and-designer-fragrances",
  "crocs",
  "delonghi",
  "descente",
  "descente-store-golf",
  "diana",
  "diesel",
  "dolceandgabbana",
  "dressterior",
  "dsquared2",
  "dunhill",
  "ecco",
  "edifice",
  "elendeek",
  "emmi",
  "enfold",
  "etro",
  "fendi",
  "ferragamo",
  "fragrance-outlet",
  "francfranc",
  "fray-i-d",
  "freaks-store",
  "fred-perry",
  "furla",
  "gallardagalante",
  "gap",
  "gelato-pique",
  "gianni-chiarini",
  "ginza-maggy",
  "givenchy",
  "graniph",
  "gucci",
  "hamilton",
  "helly-hansen",
  "herno",
  "hoka",
  "iena",
  "ined",
  "isaia-napoli",
  "issey-miyake",
  "izone-new-york",
  "j-and-m-davidson",
  "jm-weston",
  "j-press",
  "jil-sander",
  "jimmy-choo",
  "john-smedley",
  "journal-standard",
  "jun",
  "kaneko-optical",
  "kanematsu",
  "kate-spade-new-york",
  "kenzo",
  "kolor",
  "l-l-bean",
  "lacoste",
  "le-creuset",
  "lego",
  "lephil",
  "levis",
  "lily-brown",
  "loewe",
  "longchamp",
  "longines",
  "loro-piana",
  "lowrys-farm",
  "lululemon",
  "mackintosh",
  "maison-kitsune",
  "maison-margiela",
  "maison-special",
  "mammut",
  "manolo-blahnik",
  "marc-jacobs",
  "margaret-howell",
  "marimekko",
  "mark-and-lona",
  "marni",
  "max-mara",
  "mcgregor",
  "alexander-mcqueen",
  "mezzo-piano",
  "michael-kors",
  "miki-house",
  "mila-owen",
  "millet",
  "molton-brown",
  "moncler",
  "montblanc",
  "moorer",
  "moussy",
  "nano-universe",
  "new-balance",
  "new-balance-golf",
  "nike",
  "n21",
  "oakley",
  "off-white",
  "olive-des-olive",
  "onitsuka-tiger",
  "orobianco",
  "pandora",
  "patou",
  "paul-smith",
  "pearly-gates",
  "petit-bateau",
  "ping",
  "plaza",
  "pokemon-store",
  "polo-ralph-lauren",
  "polo-ralph-lauren-children",
  "prada",
  "puma",
  "ray-ban",
  "refa",
  "regal",
  "replay",
  "roger-vivier",
  "ron-herman",
  "rope-picnic",
  "royal-copenhagen",
  "ryu",
  "sn-nishikawa",
  "sabon",
  "saint-laurent",
  "samantha-thavasa",
  "samsonite",
  "sanrio",
  "scotch-grain",
  "seiko",
  "seven-eleven",
  "ships",
  "skechers",
  "sly",
  "snidel",
  "soccer-junky",
  "spick-and-span",
  "star-jewelry",
  "stella-mccartney",
  "stone-island",
  "stressless",
  "stylemixer",
  "swarovski",
  "swatch",
  "tefal",
  "tag-heuer",
  "takashimaya",
  "takeo-kikuchi",
  "tasaki",
  "tatras",
  "taylormade",
  "the-cosmetics-company-store",
  "the-north-face",
  "theory",
  "thom-browne",
  "three",
  "timberland",
  "tissot",
  "tods",
  "tom-ford",
  "tommy-hilfiger",
  "tomorrowland",
  "topologie",
  "tory-burch",
  "tradies",
  "traditional-weatherwear",
  "trinity",
  "triumph",
  "tumi",
  "ugg",
  "un3d",
  "under-armour",
  "united-arrows",
  "untitled",
  "urban-research",
  "valentino",
  "vendome-aoyama",
  "verite",
  "versace",
  "vivienne-westwood",
  "wacoal",
  "wedgwood",
  "wilson",
  "wind-and-sea",
  "woolrich",
  "y-3",
  "zegna",
  "zero-halliburton",
  "zwilling",
  "23ku",
  "enoteca-and-cases",
  "fauchon",
  "godiva",
  "haagen-dazs",
  "kuzefukushouten",
  "laduree",
  "lindt",
  "pierre-marcolini"
] as const;
const expectedRestaurantNames = [
  "Atami Osakana Syokudou",
  "Benitora Kitchen",
  "Benitora Shaochi Ten",
  "Eggs 'n Things Coffee",
  "Fauchon",
  "Food Bazaar",
  "Fresh Juice Bar Karin（Kiosk）",
  "Fujiichi",
  "Futaba Fruits Parlor",
  "Gelato Pique Cafe",
  "Gelato Pique Cafe Creperie",
  "Godiva",
  "Godiva Chocolixer (Drink,Ice Cream)",
  "Gong Cha",
  "Gyukatsu Motomura",
  "Hyorokutei",
  "Idebok",
  "Kaneko Hannosuke",
  "Laduree",
  "Lemonede by Lemonica",
  "Philly's",
  "Pierre Marcolini",
  "Salon Ginza Sabou Komeshokudo",
  "San Grams Green Tea",
  "Sawayaka",
  "Shake Shack",
  "Shizuoka Gotouchi Gourmet Express",
  "Starbucks",
  "Tamura Ginkatsutei",
  "Tensei",
  "Trattoria Tavola",
  "Tully's Coffee & Tea (Hill Side)",
  "Tully's Coffee (East)",
  "Tully's Coffee (West Kiosk)",
  "Udon Noodles Fujiyama Saryou",
  "Uogashi",
  "Wood Burning Steak"
] as const;
const unique = <T>(values: T[]) => new Set(values).size === values.length;
const difference = <T>(left: readonly T[], right: readonly T[]) => [...new Set(left)].filter(value => !new Set(right).has(value));

assert.equal(azSource.length, 253); assert.equal(new Set(azSource).size, 253);
assert.equal(foodRetailSource.length, 8); assert.equal(new Set(foodRetailSource).size, 8);
assert.equal(expectedBrandIds.length, 261); assert.equal(new Set(expectedBrandIds).size, 261);
assert.equal(expectedRestaurantNames.length, 37); assert.equal(new Set(expectedRestaurantNames).size, 37);
assert.equal(outlets.filter(o => o.status === "active").length, 120);
const gotemba = outlets.filter(o => o.outletId === outletId); assert.equal(gotemba.length, 1); assert.equal(gotemba[0].countryId, "japan"); assert.equal(gotemba[0].cityId, "gotemba");
assert.equal(cities.filter(c => c.cityId === "gotemba" && c.countryId === "japan").length, 1);
assert.ok(unique(brands.map(b => b.brandId)), "duplicate global brandId");
for (const relation of outletBrands) assert.equal(brands.filter(b => b.brandId === relation.brandId).length, 1, `unresolved/duplicate brand ${relation.brandId}`);
assert.ok(unique(outletBrands.map(r => `${r.outletId}:${r.brandId}`)), "duplicate outletId + brandId");
assert.ok(unique(restaurants.map(r => r.restaurantId)), "duplicate restaurantId");
assert.ok(unique(transportation.map(r => r.transportationId)), "duplicate transportationId");
assert.ok(unique(transportationGuides.map(g => g.guideId)), "duplicate transportationGuideId");
const actualBrandIds = outletBrands.filter(r => r.outletId === outletId).map(r => r.brandId);
const actualRestaurantNames = restaurants.filter(r => r.outletId === outletId).map(r => r.restaurantName);
assert.equal(actualBrandIds.length, 261); assert.deepEqual(difference(expectedBrandIds, actualBrandIds), []); assert.deepEqual(difference(actualBrandIds, expectedBrandIds), []);
assert.equal(actualRestaurantNames.length, 37); assert.deepEqual(difference(expectedRestaurantNames, actualRestaurantNames), []); assert.deepEqual(difference(actualRestaurantNames, expectedRestaurantNames), []);
assert.equal(outletBrands.filter(r => r.outletId === "the-outlet-village").length, 73); assert.equal(restaurants.filter(r => r.outletId === "the-outlet-village").length, 10);
assert.equal(outletBrands.filter(r => r.outletId === "al-khiran-hybrid-outlet-mall").length, 44); assert.equal(restaurants.filter(r => r.outletId === "al-khiran-hybrid-outlet-mall").length, 21);
assert.equal(outletBrands.filter(r => r.outletId === "dubai-outlet-mall").length, 228);
console.log(`A-Z RETAIL SOURCE COUNT: ${azSource.length}`); console.log(`FOOD RETAIL SOURCE COUNT: ${foodRetailSource.length}`); console.log(`EXPECTED DIRECT RELATIONSHIPS: ${expectedBrandIds.length}`); console.log(`ACTUAL GOTEMBA RELATIONSHIPS: ${actualBrandIds.length}`); console.log("NORMALIZED EXPECTED - ACTUAL:", difference(expectedBrandIds, actualBrandIds)); console.log("ACTUAL - NORMALIZED EXPECTED:", difference(actualBrandIds, expectedBrandIds)); console.log(`RESTAURANT SOURCE COUNT: ${expectedRestaurantNames.length}`); console.log(`ACTUAL RESTAURANTS: ${actualRestaurantNames.length}`); console.log("RESTAURANT EXPECTED - ACTUAL:", difference(expectedRestaurantNames, actualRestaurantNames)); console.log("ACTUAL - RESTAURANT EXPECTED:", difference(actualRestaurantNames, expectedRestaurantNames));
console.log("Japan Gotemba integrity audit passed");
