import assert from 'node:assert/strict';
import { brands } from '../src/constants/brands'; import { cities } from '../src/constants/cities'; import { outlets } from '../src/constants/outlets'; import { outletBrands } from '../src/constants/outletBrands'; import { restaurants } from '../src/constants/restaurants'; import { transportationGuides } from '../src/constants/transportationGuides'; import { targetContentLanguages,getTargetQuickInfo,localizeTargetGuide } from '../src/constants/targetOutletLocalization'; import { taxFreeRules } from '../src/constants/taxFreeRules'; import { taxFreeCountryGuides } from '../src/constants/taxFreeGuides'; import { shanghaiVillageDirectory as directory,shanghaiVillageDining as dining,canonicalShanghaiName, shanghaiVillageNewBrandIds } from '../src/constants/shanghaiVillageSnapshot';
const normalizeIdentity=(value:string)=>value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[\u3400-\u9fff]/g,'').replace(/[^a-z0-9]/gi,'').toLowerCase();
const id='shanghai-village', outlet=outlets.find(x=>x.outletId===id); assert(outlet); assert.equal(outlet.countryId,'china');assert.equal(outlet.cityId,'shanghai');assert(cities.some(x=>x.cityId==='shanghai'&&x.countryId==='china'));assert.equal(outlet.latitude,31.1415024);assert.equal(outlet.longitude,121.675705);assert.equal(outlet.address,'88 Shendi East Road, Pudong, Shanghai');assert.equal(outlet.phone,'400-920-0088');assert.equal(outlet.email,'info-shv@valueretailchina.com');assert.equal(outlet.services.length,8);assert.deepEqual(outlet.galleryImages,[]);assert(!JSON.stringify(outlet).match(/Global Blue|Planet/i));
assert.equal(targetContentLanguages.length,8);for(const l of targetContentLanguages){const q=getTargetQuickInfo(id,l)!;assert(q.openingHours&&q.parking&&q.storesCountText&&q.services.length===8);assert(!JSON.stringify(q).includes('%{'));}
assert.equal(directory.length,200);assert.equal(new Set(directory).size,200);assert.equal(dining.length,20);assert.equal(new Set(dining).size,20);const overlap=directory.filter(x=>dining.includes(x));assert.equal(overlap.length,18);const retail=directory.filter(x=>!dining.includes(x));assert.equal(retail.length,182);const canonical=retail.flatMap(canonicalShanghaiName);assert.equal(new Set(canonical).size,182);assert.equal(new Set(brands.map(x=>x.brandId)).size,brands.length,'global duplicate brandId');const newBrandIds=new Set<string>(shanghaiVillageNewBrandIds);assert.equal(newBrandIds.size,61);const existingIdentities=new Map(brands.filter(x=>!newBrandIds.has(x.brandId)).map(x=>[normalizeIdentity(x.brandName),x.brandId]));const newIdentities=new Set<string>();for(const brand of brands.filter(x=>newBrandIds.has(x.brandId))){const key=normalizeIdentity(brand.brandName);assert(!existingIdentities.has(key),`new canonical brand duplicates ${existingIdentities.get(key)}`);assert(!newIdentities.has(key),`duplicate new canonical identity: ${brand.brandId}`);newIdentities.add(key)}const mappings=outletBrands.filter(x=>x.outletId===id);assert.equal(mappings.length,182);assert.equal(new Set(mappings.map(x=>x.brandId)).size,182);assert(mappings.every(x=>brands.some(b=>b.brandId===x.brandId)));const diningCanonical=new Set(dining.flatMap(canonicalShanghaiName));assert(mappings.every(m=>!diningCanonical.has(brands.find(b=>b.brandId===m.brandId)!.brandName)));
const rs=restaurants.filter(x=>x.outletId===id);assert.equal(rs.length,20);assert.deepEqual(rs.map(x=>x.restaurantName),dining);assert(rs.every(x=>!x.priceLevel&&!x.images?.length));assert(taxFreeRules.some(x=>x.countryId==='china'));assert(taxFreeCountryGuides.some(x=>x.countryId==='china'));assert(outlet.taxFreeAvailable&&outlet.taxFreeOfficeInfo.includes('021-2099-5888'));
assert.equal(new Set(transportationGuides.map(x=>x.guideId)).size,transportationGuides.length,'global duplicate guideId');const guides=transportationGuides.filter(x=>x.outletId===id);assert.equal(guides.length,3);for(const g of guides){assert(g.steps.length>=4);for(const l of targetContentLanguages){const c=localizeTargetGuide(g,l)!;assert(c.title&&c.estimatedDuration&&c.estimatedCost&&c.steps.length===g.steps.length);assert(!JSON.stringify(c).includes('%{'));}}assert(!JSON.stringify(guides[0]).match(/every \d|hourly|CNY \d/));
const baseline:Record<string,[number,number?]>={'al-khiran-hybrid-outlet-mall':[44],'dubai-outlet-mall':[228],'the-outlet-village':[73,10],'rinku-premium-outlets':[217,26],'gotemba-premium-outlets':[261,37],'mitsui-outlet-park-kisarazu':[262,37]};for(const [oid,[bc,rc]] of Object.entries(baseline)){assert.equal(outletBrands.filter(x=>x.outletId===oid&&x.relationStatus==='active').length,bc);if(rc!==undefined)assert.equal(restaurants.filter(x=>x.outletId===oid).length,rc)}
console.log(`raw directory count: ${directory.length}\nraw dining count: ${dining.length}\noverlap count: ${overlap.length}\nraw retail-source count: ${retail.length}\ncanonical mapping count: ${mappings.length}\nrestaurant count: ${rs.length}\ntransportation-guide count: ${guides.length}\nproduction-language count: ${targetContentLanguages.length}`);
