import { createHash } from "node:crypto";
import { brands } from "../src/constants/brands";
import { outletBrands } from "../src/constants/outletBrands";

const outletId = "venezia-mega-outlet";
const officialDirectoryByCategory: Record<string, readonly string[]> = {
  "Ayakkabı & Çanta": ["U.S. POLO ASSN.", "Derimod", "Skechers", "Elle", "Bambi", "Hotiç", "TAMER TANCA", "IN Street", "Flo", "Samsonite", "Sadık Yılmaz", "Greyder", "Ayakkabı Dünyası", "Vicco", "MATMAZEL", "Grande Çanta", "SuperStep"],
  "Beyaz Eşya & Elektronik & GSM": ["Kiit", "Teknosa", "Türk Telekom", "Samsung", "Vodafone", "REEDER", "Turkcell Kio"],
  "Çarşı Pazar": ["Çeyiz", "Çikolata / Lokum", "Parti Malzemeleri", "Nargile", "Hediyelik", "Saat", "Eşarp", "Cam Sanatı", "Valiz / Çanta", "Yöresel Kahve", "Para Transferi", "Gümüş", "Kırtasiye", "Lokma", "Seramik", "Dövme"],
  "Çocuk Giyim & Ayakkabı": ["B&G Store", "U.S. POLO ASSN. Kids", "Ebebek"],
  "Ev & Dekorasyon": ["Karaca", "Schafer", "Özdilek Ev Tekstili", "English Home", "Tedi", "Ecrou", "Madame Coco", "Pink & More", "MR.DIY", "Jumbo"],
  "Gıda": ["Amasya Et Ürünleri"],
  "Giyim": ["Defacto", "Loft", "Colin's", "İpekyol", "Roman", "Suwen", "Loya", "Aker", "Armalife", "Nocturne", "adL", "Kayra", "Gizia", "Guess", "Vakko Outlet", "Barrels&Oil", "Koton", "LCWAIKIKI", "Mavi", "Tuğba", "Suayşe", "Ltb", "Network", "Modanisa", "Guess - Kiosk", "Tudors", "D'S Damat", "Çift Geyik Karaca", "Parlé Paris", "Sarar", "İgs", "Altınyıldız Classics", "Kiğılı", "Süvari", "Fullamoda", "Lufian", "Dufy", "Crystalia Boutıque", "Penti", "Dagi", "Lamodameda", "BATİK", "PAULMARK", "VALENCE", "ARMİNE", "AVVA", "Beymen Business", "Pierre Cardin", "LOVE MY BODY", "Mizalle", "Back & Bond", "JACK & JONES", "KİP & Ramsey", "Boyner"],
  "Hizmet": ["Ertuğrul Köleoğlu & Sinan Köstekçi Kuaför", "Lostra Sepeti", "Terzi", "Tobacco Shop", "Dry Clean Express", "Fırat Erdi", "Çözüm Döviz"],
  "Hobi & Oyuncak & Eğlence": ["Galaxia Game Park", "Toyzz Shop", "Ced-Go"],
  "Market & Yapı Market": ["Tekzen", "CarrefourSA Süper"],
  "Optik & Aksesuar": ["Saat&Saat", "So CHIC...", "Bijulife", "Opmar Optik", "Atasun Optik", "Gif Accessories", "Çilek Konsept", "Charmains", "Global Optik", "SIRELLO ACCS", "Unzilee", "Pandora"],
  "Oto Yıkama": ["BEB Oto Yıkama"],
  "Sağlık & Kozmetik": ["Flormar - Cadde Katı", "Yves Rocher", "Watsons", "Golden Rose - Cadde Katı", "Shiffa Home", "Rossmann", "Eczane", "Gratis", "Flormar - AVM Katı", "Eve Shop", "D&P Perfumum", "Kiko", "THE COSMETICS COMPANY STORE", "Bargello Perfume", "MAD Parfumeur", "Golden Rose - AVM Katı"],
  "Sinema": ["Cinens Sinemaları"],
  "Spor": ["Nike", "Hummel", "Puma", "Adidas", "Maraton Sportswear", "Karizma Group", "SPX", "Merrell"],
};
const excludedDisplays = ["Çeyiz", "Çikolata / Lokum", "Parti Malzemeleri", "Nargile", "Hediyelik", "Saat", "Eşarp", "Cam Sanatı", "Valiz / Çanta", "Yöresel Kahve", "Para Transferi", "Gümüş", "Kırtasiye", "Lokma", "Seramik", "Dövme", "Ertuğrul Köleoğlu & Sinan Köstekçi Kuaför", "Lostra Sepeti", "Terzi", "Tobacco Shop", "Dry Clean Express", "Fırat Erdi", "Çözüm Döviz", "Galaxia Game Park", "Ced-Go", "Cinens Sinemaları", "BEB Oto Yıkama", "Eczane"] as const;
// Literal Issue #619 mapping; this is deliberately independent of outletBrands.
const acceptedDisplayToBrandIds: Record<string, string[]> = {
  "U.S. POLO ASSN.": ["u-s-polo-assn"],
  "Derimod": ["derimod"],
  "Skechers": ["skechers"],
  "Elle": ["elle"],
  "Bambi": ["bambi"],
  "Hotiç": ["hotic"],
  "TAMER TANCA": ["tamer-tanca"],
  "IN Street": ["in-street"],
  "Flo": ["flo"],
  "Samsonite": ["samsonite"],
  "Sadık Yılmaz": ["sadik-yilmaz"],
  "Greyder": ["greyder"],
  "Ayakkabı Dünyası": ["ayakkabi-dunyasi"],
  "Vicco": ["vicco"],
  "MATMAZEL": ["matmazel"],
  "Grande Çanta": ["grande-canta"],
  "SuperStep": ["superstep"],
  "Kiit": ["kiit-teknoloji"],
  "Teknosa": ["teknosa"],
  "Türk Telekom": ["turk-telekom"],
  "Samsung": ["samsung"],
  "Vodafone": ["vodafone"],
  "REEDER": ["reeder"],
  "Turkcell Kio": ["turkcell"],
  "B&G Store": ["b-and-g-store"],
  "U.S. POLO ASSN. Kids": ["u-s-polo-assn"],
  "Ebebek": ["e-bebek"],
  "Karaca": ["karaca"],
  "Schafer": ["schafer"],
  "Özdilek Ev Tekstili": ["ozdilek"],
  "English Home": ["english-home"],
  "Tedi": ["tedi"],
  "Ecrou": ["ecrou"],
  "Madame Coco": ["madame-coco"],
  "Pink & More": ["pink-and-more"],
  "MR.DIY": ["mr-diy"],
  "Jumbo": ["jumbo"],
  "Amasya Et Ürünleri": ["amasya-et"],
  "Defacto": ["defacto"],
  "Loft": ["loft"],
  "Colin's": ["colins"],
  "İpekyol": ["ipekyol"],
  "Roman": ["roman"],
  "Suwen": ["suwen"],
  "Loya": ["loya"],
  "Aker": ["aker"],
  "Armalife": ["arma-life"],
  "Nocturne": ["nocturne"],
  "adL": ["adil-isik"],
  "Kayra": ["kayra"],
  "Gizia": ["gizia"],
  "Guess": ["guess"],
  "Vakko Outlet": ["vakko"],
  "Barrels&Oil": ["barrels-and-oil"],
  "Koton": ["koton"],
  "LCWAIKIKI": ["lc-waikiki"],
  "Mavi": ["mavi"],
  "Tuğba": ["tugba"],
  "Suayşe": ["suayse"],
  "Ltb": ["ltb"],
  "Network": ["network"],
  "Modanisa": ["modanisa"],
  "Guess - Kiosk": ["guess"],
  "Tudors": ["tudors"],
  "D'S Damat": ["ds-damat"],
  "Çift Geyik Karaca": ["cift-geyik-karaca"],
  "Parlé Paris": ["parle-paris"],
  "Sarar": ["sarar"],
  "İgs": ["igs"],
  "Altınyıldız Classics": ["altinyildiz-classics"],
  "Kiğılı": ["kigili"],
  "Süvari": ["suvari"],
  "Fullamoda": ["fullamoda"],
  "Lufian": ["lufian"],
  "Dufy": ["dufy"],
  "Crystalia Boutıque": ["crystalia-boutique"],
  "Penti": ["penti"],
  "Dagi": ["dagi"],
  "Lamodameda": ["lamodameda"],
  "BATİK": ["batik"],
  "PAULMARK": ["paulmark"],
  "VALENCE": ["valence"],
  "ARMİNE": ["armine"],
  "AVVA": ["avva"],
  "Beymen Business": ["beymen"],
  "Pierre Cardin": ["pierre-cardin"],
  "LOVE MY BODY": ["love-my-body"],
  "Mizalle": ["mizalle"],
  "Back & Bond": ["back-and-bond"],
  "JACK & JONES": ["jack-and-jones"],
  "KİP & Ramsey": ["kip", "ramsey"],
  "Boyner": ["boyner"],
  "Toyzz Shop": ["toyzz-shop"],
  "Tekzen": ["tekzen"],
  "CarrefourSA Süper": ["carrefour"],
  "Saat&Saat": ["saat-saat"],
  "So CHIC...": ["so-chic"],
  "Bijulife": ["bijulife"],
  "Opmar Optik": ["opmar-optik"],
  "Atasun Optik": ["atasun-optik"],
  "Gif Accessories": ["gif-accessories"],
  "Çilek Konsept": ["cilek-konsept"],
  "Charmains": ["charmains"],
  "Global Optik": ["global-optik"],
  "SIRELLO ACCS": ["sirello-accs"],
  "Unzilee": ["unzilee"],
  "Pandora": ["pandora"],
  "Flormar - Cadde Katı": ["flormar"],
  "Yves Rocher": ["yves-rocher"],
  "Watsons": ["watsons"],
  "Golden Rose - Cadde Katı": ["golden-rose"],
  "Shiffa Home": ["shiffa-home"],
  "Rossmann": ["rossmann"],
  "Gratis": ["gratis"],
  "Flormar - AVM Katı": ["flormar"],
  "Eve Shop": ["eve"],
  "D&P Perfumum": ["d-p-parfum"],
  "Kiko": ["kiko-milano"],
  "THE COSMETICS COMPANY STORE": ["the-cosmetics-company-store"],
  "Bargello Perfume": ["bargello"],
  "MAD Parfumeur": ["mad-parfum"],
  "Golden Rose - AVM Katı": ["golden-rose"],
  "Nike": ["nike"],
  "Hummel": ["hummel"],
  "Puma": ["puma"],
  "Adidas": ["adidas"],
  "Maraton Sportswear": ["maraton"],
  "Karizma Group": ["karizma-group"],
  "SPX": ["spx"],
  "Merrell": ["merrell"],
};
const assert=(condition: unknown, message: string): asserts condition => { if (!condition) throw new Error(message); };
const hash=(value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const rows=Object.values(officialDirectoryByCategory).flat();
const accepted=Object.keys(acceptedDisplayToBrandIds);
assert(rows.length===158 && new Set(rows).size===158, "Official snapshot must contain 158 unique literal rows.");
assert(JSON.stringify(Object.fromEntries(Object.entries(officialDirectoryByCategory).map(([k,v])=>[k,v.length])))===JSON.stringify({"Ayakkabı & Çanta":17,"Beyaz Eşya & Elektronik & GSM":7,"Çarşı Pazar":16,"Çocuk Giyim & Ayakkabı":3,"Ev & Dekorasyon":10,"Gıda":1,"Giyim":54,"Hizmet":7,"Hobi & Oyuncak & Eğlence":3,"Market & Yapı Market":2,"Optik & Aksesuar":12,"Oto Yıkama":1,"Sağlık & Kozmetik":16,"Sinema":1,"Spor":8}), "Category counts changed.");
assert(excludedDisplays.length===28 && accepted.length===130 && excludedDisplays.every(x=>rows.includes(x)) && accepted.every(x=>rows.includes(x)), "Exclusion or accepted inventory changed.");
const expectedRelationIds=[...new Set(Object.values(acceptedDisplayToBrandIds).flat())].sort();
assert(expectedRelationIds.length===127, "Expected exactly 127 mapped relations.");
const relations=outletBrands.filter(x=>x.outletId===outletId); const ids=relations.map(x=>x.brandId);
assert(JSON.stringify(ids)===JSON.stringify(expectedRelationIds) && JSON.stringify(ids)===JSON.stringify([...ids].sort()), "Venezia relations must exactly equal the sorted literal mapping.");
assert(new Set(ids).size===127 && relations.every(x=>x.featured===false&&x.relationStatus==="active"&&JSON.stringify(Object.keys(x).sort())===JSON.stringify(["brandId","featured","outletId","relationStatus"])), "Relation shape or duplication changed.");
const canonicals=new Map(brands.map(x=>[x.brandId,x])); assert(ids.every(x=>canonicals.get(x)?.brandStatus==="active"), "Every relation needs an active canonical.");
const normalize=(value:string)=>value.toLocaleLowerCase("tr-TR").replace(/ı/g,"i").replace(/ç/g,"c").replace(/ğ/g,"g").replace(/ö/g,"o").replace(/ş/g,"s").replace(/ü/g,"u").replace(/[’'´]/g,"").replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
for(const excluded of excludedDisplays) for(const id of ids) { const b=canonicals.get(id)!; assert(![b.brandId,b.brandName,...b.aliases].map(normalize).includes(normalize(excluded)), `Excluded display leaked: ${excluded}`); }
for(const [display,id] of Object.entries({"Kiit":"kiit-teknoloji","Turkcell Kio":"turkcell","Özdilek Ev Tekstili":"ozdilek","adL":"adil-isik","Vakko Outlet":"vakko","Beymen Business":"beymen","ARMİNE":"armine","Kiko":"kiko-milano","Maraton Sportswear":"maraton","CarrefourSA Süper":"carrefour"})) assert(acceptedDisplayToBrandIds[display].join()==id, `Identity safeguard failed: ${display}`);
assert(acceptedDisplayToBrandIds["Karaca"].join()!==acceptedDisplayToBrandIds["Çift Geyik Karaca"].join() && acceptedDisplayToBrandIds["KİP & Ramsey"].length===2 && !expectedRelationIds.includes("guess-kiosk"), "Required distinct/merged identity decision changed.");
assert(hash(officialDirectoryByCategory)==="e1800d78505bd9869a50a445a94686b288dc6ec6c7ed08d8d0005f7bcb0f374a" && hash(acceptedDisplayToBrandIds)==="f5aca0009105d1bcb40114b73acbf17dd470add82f9bec61d1715db4ec021356" && hash(excludedDisplays)==="b5434b38d1cf02d932dc74e788e593e8af8d5524672ba5611badb36e91106cc0", "Literal inventory hash changed.");
console.log(`Venezia coverage valid: ${rows.length} rows, ${accepted.length} accepted displays, ${ids.length} relations.`);
