import assert from "node:assert/strict";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { supportedLanguageCodes } from "../src/translations/locale";
import { translations } from "../src/translations/translations";

const outputDirectory = path.resolve("src/translations/.generated-web");
const checkOnly = process.argv.includes("--check");

function moduleSource(dictionary: Record<string, string>): string {
  return `// Generated by tools/generateWebTranslationModules.ts. Do not edit.\nexport default ${JSON.stringify(dictionary, null, 2)};\n`;
}

async function main() {
  if (!checkOnly) {
    await rm(outputDirectory, { recursive: true, force: true });
    await mkdir(outputDirectory, { recursive: true });
  }

  for (const locale of supportedLanguageCodes) {
    const expected = moduleSource(translations[locale]);
    const outputPath = path.join(outputDirectory, `${locale}.generated.js`);

    if (checkOnly) {
      assert.equal(await readFile(outputPath, "utf8"), expected, `${locale} generated module is stale`);
    } else {
      await writeFile(outputPath, expected, "utf8");
    }

    const generated = JSON.parse(expected.slice(expected.indexOf("{")).replace(/;\n$/, ""));
    assert.deepEqual(generated, translations[locale], `${locale} generated dictionary differs from canonical source`);
  }

  console.log(`${checkOnly ? "Validated" : "Generated and validated"} ${supportedLanguageCodes.length} web translation modules.`);
}

void main();
