import type { OutletBrand } from "./index";

export const austriaOutletBrands: OutletBrand[] = [
  {
    outletId: "designer-outlet-parndorf",
    brandId: "7-for-all-mankind",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "alina-cosmetics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "alpha-tauri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "arcteryx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "babor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "berndorf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "breitling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "calvin-klein-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "calvin-klein-underwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "calzedonia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "carhartt-wip",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "corneliani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "dinoland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "douglas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "douglas-pop-up-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "dyson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "fissler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "freywille",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "guess-accessories",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "guess-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hoka",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "hogl",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "intimissimi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "jack-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "joop-men",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "joop-women",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "kate-spade",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "kneipp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "loreal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "le-creuset-pop-up",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "liujo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "laderach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "manner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "marc-cain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "mcqueen",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "moncler-grenoble",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "mountain-warehouse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "my-burgenland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "nespresso",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "odlo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "olymp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "peak-performance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "playmobil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "porsche-design",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "ravensburger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "red-bull-world",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "riedel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "rosenthal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "rosle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "santoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "seidensticker",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "sportalm",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "spyder",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "storck",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "the-body-shop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tommy-hilfiger-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "valentino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "waterdrop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "wellensteyn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "wutscher-optik",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "zegna",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-parndorf",
    brandId: "zwilling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "alina-cosmetics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "ara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "ardeco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "atomic",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "bassetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "betty-barclay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "brundl-bike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "brundl-sports",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "cecil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "camel-active",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "carhartt-wip",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "comma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "dyson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "home-and-cook",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "jack-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "jack-and-jones-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "jjxx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "joop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "kneipp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "levi-s",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "liebeskind",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "only-and-sons",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "protest",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "ravensburger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "rosenthal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "rosle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "schiesser",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "seidensticker",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "triumph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "vero-moda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "wellensteyn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "windsor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-salzburg",
    brandId: "wolford",
    featured: false,
    relationStatus: "active",
  },
];
