import type { OutletBrand } from "./index";

export const belgiumOutletBrands: OutletBrand[] = [
  {
    outletId: "maasmechelen-village",
    brandId: "7-for-all-mankind",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "anne-de-solene",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "aquanova",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "armani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "ba-and-sh",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "biotherm",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "bjorn-borg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "bobbi-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "calvin-klein-underwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "clinique",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "coach",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "demeyere",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "dkny",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "essentiel-antwerp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "estee-lauder",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "garcia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "guess-accessories",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "hackett-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "hoff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "home-and-cook",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "k-way",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kate-spade-new-york",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kiehls",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kipling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "kusmi-tea",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "lancome",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "leonidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "les-soeurs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "l-occitane",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "loreal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "mac-cosmetics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "marlies-dekkers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "max-mara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "my-jewellery",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "neuhaus",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "new-zealand-auckland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "nik-and-nik",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "nikkie",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "outly",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "polo-ralph-lauren-children",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "protest",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "river-woods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "schiesser",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "selected",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "the-society-shop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "watch-station",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "waterdrop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "xandres",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "zadig-and-voltaire",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "maasmechelen-village",
    brandId: "zwilling",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "designer-outlet-luxembourg",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "betty-barclay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "boss-orange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "calvin-klein-underwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "desforges",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "dim-outlet",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "essie",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "garcia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "garnier",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "geographical-norway",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "gil-bret",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "home-and-cook",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "jerem-paris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "jjxx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "krups",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "l-oreal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "lagostina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "maybelline-new-york",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "moulinex",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "nyx-professional-makeup",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "o-neill",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "only-and-sons",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "peluches-a-gogo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "petrol-industries",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "rowenta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "schiesser",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "state-of-art-menswear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "the-kooples",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "the-kooples-sport",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "tradition-des-vosges",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "trespass",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "vera-mont",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "vero-moda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "vila",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "wonderbra",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "yves-delorme",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-luxembourg",
    brandId: "zadig-and-voltaire",
    featured: false,
    relationStatus: "active",
  },
];
