import type { OutletBrand } from "./index";

export const croatiaOutletBrands: OutletBrand[] = [
  {
    outletId: "ros-designer-outlet",
    brandId: "ad-twenty",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "ara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "argentum",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "barbour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "braccialini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "brawns",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "calzedonia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "casio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "catch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "cesare-paciotti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "champion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "cluse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "corso-roma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "corso-roma-boutique",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "cromia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "cruyff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "david-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "douglas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "eastpak",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "elmas-phil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "europa-92-denim-bar",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "family",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "fashion-and-friends-outlet-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "fifty",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "five-star-fashion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "galileo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "good-bags",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "goorin-bros",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "hogl",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "home-and-cook",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "intimissimi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "intrend",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "jack-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "jacques-lemans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "jcout",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "jeordies",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "just-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "krups",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "la-martina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lagostina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lee",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lee-cooper",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lisca",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "liujo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lonsdale-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "lotto",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "ltb",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "mass",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "maya-maya",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "mercer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "meyba",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "moulinex",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "mylin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "nine-west",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "off-the-pitch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "optika-anda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "optotim",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "palmers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "parfois",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "patrizia-pepe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "pierre-cardin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "polaroid",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "police",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "ray-ban",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "reebok",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "retro-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "roberto-della-croce",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "rosefield",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "rowenta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "s-oliver",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "salsa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "scotch-and-soda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "shoetique",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "silhouette",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "silit",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "sport-vision",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "springfield",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "ted-baker",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "tisak",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "umbro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "united-colors-of-benetton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "us-polo-assn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "versace-jeans-couture",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "versus-versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "watch-center",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "wellensteyn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "womensecret",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "wrangler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "xyz-outlet",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ros-designer-outlet",
    brandId: "yamamay",
    featured: false,
    relationStatus: "active",
  },
];
