import type { OutletBrand } from "./index";

export const croatiaOutletBrands: OutletBrand[] = [
  { outletId: "ros-designer-outlet", brandId: "adidas", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "boss", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "bugatti", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "calvin-klein", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "desigual", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "fashion-and-friends-xyz", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "fred-perry", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "gap", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "guess", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "lacoste", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "mass", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "mustang", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "new-balance", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "nine-west", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "only", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "patrizia-pepe", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "puma", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "replay", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "s-oliver", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "skechers", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "sport-vision", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "tamaris", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "tom-tailor", featured: false, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "tommy-hilfiger", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "under-armour", featured: true, relationStatus: "active" },
  { outletId: "ros-designer-outlet", brandId: "us-polo-assn", featured: true, relationStatus: "active" },
];
