import type { OutletBrand } from "./index";

export const franceOutletBrands: OutletBrand[] = [
  {
    outletId: "la-vallee-village",
    brandId: "acne-studios",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "alexander-mcqueen",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "ami-paris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "bonpoint",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "bottega-veneta",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "brunello-cucinelli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "celine",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "charles-tyrwhitt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "christian-louboutin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "claudie-pierlot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "dior",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "diptyque",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "ermenegildo-zegna",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "fendi",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "ferragamo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "fred-perry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "gerard-darel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "golden-goose",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "isabel-marant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "joseph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "k-way",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "laduree",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "loewe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "lululemon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "max-mara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "moncler",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "paul-smith",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "petit-bateau",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "saint-laurent",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "sandro-ferrone",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "stone-island",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "the-kooples",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tissot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tory-burch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "valentino",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "zadig-and-voltaire",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-vallee-village",
    brandId: "zimmermann",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "designer-outlet-troyes",
    brandId: "aigle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "calvin-klein",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "claudie-pierlot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "gerard-darel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "lacoste",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "le-coq-sportif",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "mango",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "millet",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "petit-bateau",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "pierre-cardin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "playmobil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "quiksilver",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "swatch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "the-kooples",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-troyes",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "designer-outlet-provence",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "aubade",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "claudie-pierlot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "coach",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "new-era",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "petit-bateau",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "the-kooples",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "vanessa-bruno",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-provence",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
];
