import type { OutletBrand } from "./index";

export const germanyOutletBrands: OutletBrand[] = [
  {
    outletId: "outletcity-metzingen",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "babor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "belstaff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "bottega-veneta",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "hackett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "jil-sander",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "joop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "kenneth-cole",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "lululemon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "max-mara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "mcm",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "moncler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "moose-knuckles",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "oakley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "playmobil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "porsche-design",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "rag-and-bone",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tory-burch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "valentino",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "windsor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "wolford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "outletcity-metzingen",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "ingolstadt-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "arcteryx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "babor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "calvin-klein",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "coach",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "fred-perry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "karl-lagerfeld",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "lacoste",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "loewe",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "marc-cain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "mcm",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "tom-ford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "wellensteyn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "wolford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ingolstadt-village",
    brandId: "zero",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "wertheim-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "babor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "balenciaga",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "belstaff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "calvin-klein",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "coach",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "fissler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "fred-perry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "gucci",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "hackett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "joop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "joseph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "lululemon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "marc-cain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "mcm",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "odlo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "ray-ban",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "spyder",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "the-kooples",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tom-ford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tommy-hilfiger-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "wellensteyn",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "wolford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wertheim-village",
    brandId: "zero",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "designer-outlet-berlin",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "birkenstock",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "hugo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "joop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "playmobil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "rituals",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "the-north-face",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "ugg",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-berlin",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-neumunster",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "montabaur-the-style-outlets",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
];
