import type { OutletBrand } from "./index";

export const greeceOutletBrands: OutletBrand[] = [
  {
    outletId: "designer-outlet-athens",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "american-eagle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "calzedonia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "camel-active",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "cole-haan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "funky-buddha",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "galerie-de-beaute",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "intimissimi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "juicy-couture",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "marc-o-polo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "nespresso",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "scotch-and-soda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-athens",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
];
