import type { OutletBrand } from "../outletBrands";

export const italyOutletBrands: OutletBrand[] = [
  {
    outletId: "serravalle-designer-outlet",
    brandId: "acne-studios",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "ami-paris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "antony-morato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "aspesi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "benetton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "blumarine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "bonpoint",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "brioni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "canali",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "carhartt-wip",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "casadei",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "celine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "champion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "claudie-pierlot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "corneliani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "ermenegildo-zegna",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "fabiana-filippi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "fendi",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "ferragamo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "frette",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gazzarrini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "iceberg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "il-lanificio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "isaia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "ixos",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "k-way",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "kiton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "kocca",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "la-martina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "lanvin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "off-white",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "peserico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "rossignol",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "roy-rogers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "saint-laurent",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "sandro-ferrone",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "santoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "saucony",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "save-the-duck",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "sergio-rossi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "simonetta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "slowear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "sorbino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "spada",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "stella-mccartney",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "stone-island",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "the-bridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "tory-burch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "trussardi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "valentino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "serravalle-designer-outlet",
    brandId: "zimmermann",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "fidenza-village",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "aspesi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "blumarine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "borbonese",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "ermenegildo-zegna",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "fabiana-filippi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "ferragamo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "ferrari",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "frette",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "ixos",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "jil-sander",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "k-way",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "mandarina-duck",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "monnalisa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "moorer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "paul-smith",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "peserico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "roy-rogers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "stella-mccartney",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "the-bridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "trussardi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "valentino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fidenza-village",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "the-mall-firenze",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "alexander-mcqueen",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "bottega-veneta",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "celine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "corneliani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "fendi",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "jil-sander",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "off-white",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "saint-laurent",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "tom-ford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "valentino",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-mall-firenze",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },

  {
    outletId: "barberino",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "barberino",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "noventa",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "antony-morato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "armani-exchange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "balenciaga",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "blumarine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "borbonese",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "bottega-veneta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "ermenegildo-zegna",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "fendi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "frette",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "gas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "gucci",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "iceberg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "il-lanificio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "isaia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "ixos",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "moncler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "moorer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "off-white",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "paul-smith",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "peserico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "prada",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "valentino",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "noventa",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "castel-romano",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "antony-morato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "armani-exchange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "aspesi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "benetton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "blumarine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "etro",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "gas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "gazzarrini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "il-lanificio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "ixos",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "kappa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "kocca",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "monnalisa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "peserico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "refrigiwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "tommy-hilfiger",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "valentino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "castel-romano",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },

  {
    outletId: "la-reggia",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "alberta-ferretti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "antony-morato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "benetton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "blumarine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "brics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "desigual",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "frette",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "gas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "gazzarrini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "il-lanificio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "ixos",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "kappa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "kocca",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "monnalisa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "moschino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "peserico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "refrigiwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "roy-rogers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "sandro-ferrone",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "saucony",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "sisley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "spada",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "the-bridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "trussardi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "la-reggia",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
];
