import type { OutletBrand } from "./index";

// Direct Al Khiran stores corroborated through current operator or brand location pages.
const alKhiranBrandIds = [
  "adidas",
  "aldo",
  "american-eagle",
  "asics",
  "banana-republic",
  "bath-and-body-works",
  "beverly-hills-polo-club",
  "birkenstock",
  "boots",
  "boss",
  "calvin-klein",
  "charles-and-keith",
  "choice",
  "claires",
  "crocs",
  "daiso",
  "dune-london",
  "foot-locker",
  "flying-tiger",
  "geox",
  "h-and-m",
  "ikea",
  "intersport",
  "kipling",
  "lc-waikiki",
  "levis",
  "mothercare",
  "lulu-hypermarket",
  "new-balance",
  "nike",
  "ontime",
  "puma",
  "r-and-b",
  "reebok",
  "skechers",
  "smiggle",
  "the-body-shop",
  "the-childrens-place",
  "tommy-hilfiger",
  "victoria-s-secret",
  "vilebrequin",
  "xcite",
] as const;

export const kuwaitOutletBrands: OutletBrand[] = alKhiranBrandIds.map((brandId) => ({
  outletId: "al-khiran-hybrid-outlet-mall",
  brandId,
  featured: false,
  relationStatus: "active",
}));
