import type { OutletBrand } from "./index";

const outletParkVilniusBrandIds = [
  "given",
  "towmy",
  "sinsay",
  "skechers",
  "halfprice",
  "royal-smoke",
  "marabika",
  "grybai",
  "optio-optika",
  "donum",
  "inumbra-home",
  "daniele-donati",
  "wawa-outlet",
  "norre",
  "marc-and-andre",
  "drogas",
  "floyy",
  "ego-smart",
  "mos-professional-cosmetics",
  "crocs",
  "silver-fox",
  "kava",
  "trespass",
  "pako-lorente",
  "divo",
  "pro7",
  "este-outlet",
  "apranga-outlet",
  "outlet-space",
  "loois-outlet",
  "adidas",
  "ava-lingerie",
  "beauty-nail",
  "beardshop-lt",
  "puma",
  "nike",
  "artele-siuvykla",
  "keitykla",
  "halus",
  "regatta-great-outdoors",
  "vilniaus-juvelyrika",
  "familia-optica",
  "city-jeans",
  "eurokos",
  "devold",
  "denim-dream",
  "danija-outlet",
  "martina-outlet",
  "utenos",
  "sportland-outlet",
  "leva",
  "skiro",
  "triumph",
  "bags-and-more",
  "skinija",
] as const;

export const lithuaniaOutletBrands: OutletBrand[] = outletParkVilniusBrandIds.map((brandId) => ({
  outletId: "outlet-park-vilnius",
  brandId,
  featured: false,
  relationStatus: "active",
}));
