import type { OutletBrand } from "./index";

export const netherlandsOutletBrands: OutletBrand[] = [
  {
    outletId: "designer-outlet-roermond",
    brandId: "adenauer-and-co",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "aigner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "armani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "armani-exchange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "babor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "belstaff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "bottega-veneta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "breitling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "calvin-klein",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "carhartt-wip",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "dyson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "fendi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "fred-perry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "isabel-marant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "joop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "loewe",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "mackage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "moncler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "moose-knuckles",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "oakley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "off-white",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "oneill",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "porsche-design",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roermond",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },

  {
    outletId: "designer-outlet-roosendaal",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "betty-barclay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "brax",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "crocs",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "gucci",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "hunkemoller",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "invicta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "lacoste",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "new-balance",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "oakley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "oneill",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "prada",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-roosendaal",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
];
