import type { OutletBrand } from "./index";

const makeOutletBrands = (
  outletId: string,
  brandIds: string[],
): OutletBrand[] =>
  brandIds.map((brandId) => ({
    outletId,
    brandId,
    featured: false,
    relationStatus: "active",
  }));

const factoryUrsusBrandIds = [
  "4f",
  "adidas",
  "albione",
  "alpine-pro",
  "apart",
  "bagatelle",
  "big-star",
  "boss",
  "brand-collection",
  "brand-collection-for-ladies",
  "bytom",
  "calvin-klein",
  "calzedonia",
  "change-lingerie",
  "cloud-shop",
  "crocs",
  "cross-jeans",
  "d-s-damat",
  "dajar",
  "desigual",
  "digel",
  "diverse",
  "ecco",
  "empik",
  "etam",
  "family-optic",
  "franco-feruzzi",
  "gant",
  "gatta",
  "giacomo-conti",
  "guess",
  "guess-accessories",
  "haribo",
  "inmedio",
  "iqos",
  "italian-fashion",
  "jack-and-jones",
  "joop",
  "kamalion",
  "kubenz",
  "kulig",
  "lacoste",
  "lancerto",
  "lavard",
  "lee-cooper",
  "lee-wrangler",
  "levis",
  "lindt",
  "marc-opolo",
  "marilyn",
  "mastersport",
  "medicine",
  "mother-earth",
  "mountain-warehouse",
  "mustang",
  "new-balance",
  "nike",
  "ochnik",
  "only",
  "outly",
  "pako-lorente",
  "pandora",
  "pepe-jeans",
  "pierre-cardin",
  "puma",
  "regatta",
  "rossmann",
  "rylko",
  "salomon",
  "samsonite",
  "skechers",
  "smyk",
  "solar",
  "sorvella",
  "soul-converse",
  "sunset-suits",
  "tchibo",
  "tefal",
  "teletorium",
  "time-trend",
  "trespass",
  "triumph",
  "under-armour",
  "unisono",
  "vans",
  "venezia",
  "vistula",
  "volcano",
  "w-kruk",
  "wakacje-pl",
  "willsoor",
  "wittchen",
  "yes",
  "ziaja",
].sort();

const factoryAnnopolBrandIds = [
  "4f",
  "adidas",
  "adventure-sports-rossignol",
  "albione",
  "alpine-pro",
  "aw-fashion",
  "bagatelle",
  "big-star",
  "borgio",
  "bytom",
  "calvin-klein",
  "change-lingerie",
  "clarks",
  "converse",
  "crocs",
  "cross-jeans",
  "czas-na-herbate",
  "dajar",
  "digel",
  "diverse",
  "ecco",
  "empik",
  "family-optic",
  "filippo",
  "franco-feruzzi",
  "gatta",
  "giacomo-conti",
  "guess",
  "guess-accessories",
  "helly-hansen",
  "italian-fashion",
  "jack-and-jones",
  "jack-wolfskin",
  "kamalion",
  "kazar",
  "kubenz",
  "kulig",
  "lancerto",
  "lavard",
  "lee-cooper",
  "lee-wrangler",
  "levis",
  "lindt",
  "liquid-jungle",
  "marc-opolo",
  "mastersport-reebok",
  "medicine",
  "molton",
  "mother-earth",
  "mountain-warehouse",
  "mustang",
  "new-balance",
  "nike",
  "ochnik",
  "only",
  "outly",
  "pako-lorente",
  "pepe-jeans",
  "pierre-cardin",
  "puccini",
  "puma",
  "regatta",
  "rossmann",
  "rtv-euro-agd",
  "salewa",
  "samsonite",
  "skechers",
  "smyk",
  "sorvella",
  "sunset-suits",
  "tefal",
  "teletorium",
  "timberland",
  "time-trend",
  "trespass",
  "triumph",
  "under-armour",
  "vans",
  "venezia",
  "vestus",
  "villeroy-and-boch",
  "vistula",
  "volcano",
  "w-kruk",
  "wakacje-pl",
  "wittchen",
  "wittchen-travel",
  "yes",
  "ziaja",
].sort();

export const polandOutletBrands: OutletBrand[] = [
  ...makeOutletBrands("factory-annopol", factoryAnnopolBrandIds),
  ...makeOutletBrands("factory-ursus", factoryUrsusBrandIds),
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "ochnik",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "triumph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "levi-s",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "mustang",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "calzedonia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "apart",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "w-kruk",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "wroclaw-fashion-outlet",
    brandId: "trussardi",
    featured: false,
    relationStatus: "active",
  },
  ...makeOutletBrands(
    "designer-outlet-gdansk",
    [
      "4f",
      "4tel",
      "adidas",
      "adventure-sports-rossignol",
      "albione",
      "alpine-pro",
      "amora",
      "apart",
      "asics",
      "bajkowy-labirynt",
      "baldessarini",
      "big-star",
      "boss",
      "bytom",
      "calvin-klein",
      "castellani",
      "change-lingerie",
      "clinique",
      "columbia",
      "crocs",
      "cross-jeans",
      "d-s-damat",
      "dajar",
      "desigual",
      "digel",
      "diverse",
      "ecco",
      "esotiq",
      "estee-lauder",
      "fablu",
      "gabor",
      "gap",
      "giacomo-conti",
      "guess",
      "guess-accessories",
      "guess-kids",
      "italian-fashion",
      "izzi",
      "jack-wolfskin",
      "jack-and-jones",
      "karl-lagerfeld",
      "kazar",
      "kubenz",
      "kulig",
      "lancerto",
      "le-creuset",
      "lee",
      "lee-cooper",
      "levis",
      "lindt",
      "marc-opolo",
      "marilyn",
      "medicine",
      "molton",
      "mountain-warehouse",
      "mustang",
      "neonail",
      "new-balance",
      "nike",
      "ochnik",
      "only",
      "outly",
      "pako-lorente",
      "paris-optique",
      "patrizia-aryton",
      "pepe-jeans",
      "pierre-cardin",
      "pinko",
      "prochnik",
      "puma",
      "regatta-great-outdoors",
      "rylko",
      "salomon",
      "schiesser",
      "sizeer",
      "solar",
      "taranko",
      "tchibo",
      "tefal",
      "the-cosmetics-company-store",
      "tommy-hilfiger",
      "trespass",
      "triumph",
      "unisono",
      "venezia",
      "villeroy-and-boch",
      "vistula",
      "volcano",
      "w-kruk",
      "wittchen",
      "wrangler",
      "yes",
    ].sort(),
  ),
  ...makeOutletBrands("designer-outlet-sosnowiec", [
    "4f",
    "adidas",
    "alpine-pro",
    "amora",
    "apart",
    "asics",
    "bergson",
    "boss",
    "bytom",
    "calvin-klein",
    "change-lingerie",
    "crocs",
    "cross-jeans",
    "dajar-home-and-garden",
    "deni-cler",
    "desigual",
    "digel",
    "diverse",
    "ecco",
    "ellman",
    "gatta",
    "guess",
    "guess-kids",
    "himountain",
    "itaka",
    "italian-fashion",
    "jack-and-jones",
    "kazar",
    "kulig",
    "lancerto",
    "lavard",
    "lee",
    "lee-cooper",
    "levis",
    "marc-o-polo",
    "marshal",
    "mastersport",
    "medicine",
    "molton",
    "mountain-warehouse",
    "mustang",
    "new-balance",
    "nike",
    "ochnik",
    "only",
    "outly",
    "pako-lorente",
    "paris-optique",
    "patrizia-aryton",
    "pierre-cardin",
    "prochnik",
    "puma",
    "recman",
    "regatta-great-outdoors",
    "rylko",
    "salewa",
    "salomon",
    "samanta-lingerie",
    "silesia-jeans",
    "smyk",
    "studio-optyczne",
    "tantuum",
    "tefal",
    "the-cosmetics-company-store",
    "tommy-hilfiger",
    "tous",
    "triumph",
    "unisono",
    "venezia",
    "vestus",
    "villeroy-and-boch",
    "vip-collection",
    "vistula",
    "volcano",
    "w-kruk",
    "willsoor",
    "wittchen",
    "wrangler",
    "yes",
  ]),
  {
    outletId: "designer-outlet-warszawa",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "ochnik",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "kazar",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "4f",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "benetton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-warszawa",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
];
