import type { OutletBrand } from "./index";

const freeportBrandIds = [
  "adidas",
  "adolfo-dominguez",
  "aldo",
  "armani",
  "asics",
  "calvin-klein",
  "calvin-klein-underwear",
  "converse",
  "espaco-casa",
  "fila",
  "furla",
  "gato-preto",
  "home-and-cook",
  "hurley",
  "invicta",
  "karl-lagerfeld",
  "lacoste",
  "le-creuset",
  "lefties",
  "levis",
  "lion-of-porches",
  "longchamp",
  "lottusse",
  "mango",
  "michael-kors",
  "new-balance",
  "nike",
  "polo-ralph-lauren",
  "puma",
  "seaside",
  "skechers",
  "stockout",
  "sunglass-hut",
  "the-body-shop",
  "tommy-hilfiger",
  "tous",
  "vans",
  "zadig-voltaire",
];

const vilaDoCondeBrandIds = [
  "adidas",
  "american-tourister",
  "ambitious",
  "birkenstock",
  "boss",
  "fifty",
  "fred-perry",
  "karl-lagerfeld",
  "lemon-jelly",
  "lindt",
  "lottusse",
  "michael-kors",
  "nike",
  "rituals",
  "skin-travel",
  "the-press",
  "tommy-hilfiger",
  "tous",
  "urban-project",
  "zara-home",
  "zippy",
];

export const portugalOutletBrands: OutletBrand[] = [
  ...freeportBrandIds.map((brandId) => ({
    outletId: "freeport-lisboa-fashion-outlet",
    brandId,
    featured: ["adidas", "karl-lagerfeld", "michael-kors", "tommy-hilfiger"].includes(brandId),
    relationStatus: "active",
  })),
  ...vilaDoCondeBrandIds.map((brandId) => ({
    outletId: "vila-do-conde-porto-fashion-outlet",
    brandId,
    featured: ["adidas", "michael-kors", "tommy-hilfiger"].includes(brandId),
    relationStatus: "active",
  })),
];
