import type { OutletBrand } from "./index";

export const spainOutletBrands: OutletBrand[] = [
  {
    outletId: "designer-outlet-malaga",
    brandId: "adidas",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "adolfo-dominguez",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "alvaro-moreno",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "antony-morato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "aristocrazy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "beatriz-furest",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "bimba-y-lola",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "blue-banana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "boss-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "camper",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "ch-carolina-herrera",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "claudie-pierlot",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "dockers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "faconnable",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "g-star-raw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "givenchy-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "guess-men",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "hackett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "hawkers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "hoff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "home-and-cook",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "hugo-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "intrend",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "karl-lagerfeld-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "kenzo-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "krups",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "l-occitane",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "lola-casademunt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "marc-jacobs-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "michael-kors-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "moncler",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "moulinex",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "new-era",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "outly",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "pal-zileri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "pdpaola",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "pedro-del-hierro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "purificacion-garcia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "ray-ban",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "roberto-cavalli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "roberto-verino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "rowenta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "sabor-a-espana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "scalpers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "silbon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "simone-perele",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "simorra",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "sita-murt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "the-body-shop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "timberland-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "twinset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "volcom",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "designer-outlet-malaga",
    brandId: "zwilling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "adolfo-dominguez",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "aristocrazy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "ba-sh",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "bimani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "bimba-y-lola",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "breitling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "brownie",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "calvin-klein-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "calvin-klein-underwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "ch-carolina-herrera",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "cristina-oria",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "dockers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "dyson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "ecoalf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "el-ganso",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "elisabetta-franchi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "ferragamo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "flabelus",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "hackett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "herno",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "hoff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "isabel-marant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "l-occitane",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "loewe",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "loewe-perfumes",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "miu-miu",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "nude-project",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "pdpaola",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "polo-ralph-lauren-children",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "polo-ralph-lauren-men",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "polo-ralph-lauren-women",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "purificacion-garcia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "scalpers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "scalpers-woman",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "scuffers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "shiseido",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "silbon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "tory-burch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "tous",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "unode50",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "valentino-garavani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "versace",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "zadig-and-voltaire",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "las-rozas-village",
    brandId: "zwilling-ja-henckels",
    featured: false,
    relationStatus: "active",
  },
];
