import type { OutletBrand } from "./index";

const makeOutletBrands = (outletId: string, brandIds: string[]): OutletBrand[] =>
  brandIds.map((brandId) => ({
    outletId,
    brandId,
    featured: false,
    relationStatus: "active",
  }));

const hedeFashionOutletBrandIds = [
  "adidas",
  "aimn",
  "bjorn-borg",
  "boss",
  "bruun-stengade",
  "calvin-klein",
  "didriksons",
  "ecco",
  "eton",
  "filippa-k",
  "gant",
  "gina-tricot",
  "guess",
  "haglofs",
  "helly-hansen",
  "home-and-cook",
  "hunkemoller",
  "iittala",
  "inwear",
  "j-lindeberg",
  "jack-and-jones",
  "john-henric",
  "kari-traa",
  "lacoste",
  "le-creuset",
  "lee",
  "lee-wrangler",
  "lekia",
  "levis",
  "lexington",
  "lindt",
  "lyko",
  "lyle-scott",
  "marc-opolo",
  "matinique",
  "michael-kors",
  "morris",
  "name-it",
  "norrona",
  "only",
  "orrefors-kosta-boda",
  "oscar-jacobson",
  "peak-performance",
  "replay",
  "sail-racing",
  "samsoe-samsoe",
  "samsonite",
  "sand-copenhagen",
  "scorett",
  "selected",
  "skechers",
  "tommy-hilfiger",
  "triumph",
  "under-armour",
  "varg",
  "vero-moda",
  "zwilling",
].sort();

export const swedenOutletBrands: OutletBrand[] = [
  ...makeOutletBrands("hede-fashion-outlet", hedeFashionOutletBrandIds),
];
