import type { OutletBrand } from "./index";

export const switzerlandOutletBrands: OutletBrand[] = [
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "beldona",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "blackout",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "bogner",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "boxeur-des-rues",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "brandsloft",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "calida",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "camel-active",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "camp-david-soccx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "comma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "free-shop-perfumes-cosmetics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "kitchen-and-more",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "kuhn-rikon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "liebeskind-berlin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "liu-jo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "luxury-fashion-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "marc-o-polo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "max-mara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "modeva",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "ny-lab",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "odlo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "okaidi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "pierre-cardin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "pme-legend",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "roy-robson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "rukka",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "s-oliver",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "schiesser",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "schlossberg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "skiny",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "tom-tailor",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "watch-and-see",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "fashion-fish-factory-outlet",
    brandId: "we-fashion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "7-for-all-mankind",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "akris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "andre-maurice",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "angelico",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "armani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "aspesi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "aventurx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "baldinini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "bally",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "bassetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "belotti-otticaudito",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "blitz-for-eyes",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "boggi-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "borbonese",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "boxeur-des-rues",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "brics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "brooks-brothers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "brums",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "burberry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "c-p-company",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "calida",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "calzedonia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "camicissima",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "caroll",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "churchs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "cmp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "coccinelle",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "corneliani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "costume-national",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "damiani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "dockers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "dsquared2",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "ecco",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "elena-miro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "elmas-phil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "elmas-phil-collection",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "elmas-phil-uomo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "falke",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "fay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "ferragamo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "fiorella-rubino",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "flavio-castellani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "freddy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "free-shop-1",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "free-shop-2",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "freitag",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "furla",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "gaudi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "geox",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "hackett-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "hanro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "harmont-and-blaine-junior",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "icebreaker",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "il-lanificio",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "intimissimi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "jacadi-paris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "jaked",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "jerem",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "john-richmond",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "k-way",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "kid-space",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "kid-space-collection",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "kiko-milano",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "kiton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "la-martina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "lee",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "malo-italia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "mammut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "marc-opolo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "millefiori-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "miriade",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "modesto-bertotto",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "moorer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "morgan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "motivi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "nike",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "oakley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "odlo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "off-white",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "patrizia-pepe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "paul-and-shark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "peak-performance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "pepe-jeans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "peuterey",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "philipp-plein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "pinko",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "plein-sport",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "polo-ralph-lauren",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "prada",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "quiksilver",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "replay",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "rh-plus",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "sandro-ferrone",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "sbs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "simonetta",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "triumph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "trussardi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "vaude",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "vero-moda",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "wmf",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "wolford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "wrangler",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "foxtown-factory-stores",
    brandId: "zadig-and-voltaire",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "american-vintage",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "carhartt-wip",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "companys",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "corneliani",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "eleventy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "garcia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "laderach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "loop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "loreal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "name-it",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "only",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "rossignol",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "watch-and-see",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "landquart-fashion-outlet",
    brandId: "werder-sports",
    featured: false,
    relationStatus: "active",
  },
];
