import type { OutletBrand } from "./index";

export const ukOutletBrands: OutletBrand[] = [
  {
    outletId: "bicester-village",
    brandId: "acne-studios",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "acqua-di-parma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "aesop",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "alaia",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "alexander-mcqueen",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "allsaints",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ami-paris",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "annoushka",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "aquazzura",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "arcteryx",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "astrid-and-miyu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "axel-arigato",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ba-and-sh",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "balenciaga",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "bamford",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "bang-and-olufsen",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "barbour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "beaute-prestige-international",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "benefit-cosmetics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "bonpoint",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "boss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "bottega-veneta",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "breitling",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "bremont",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "brioni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "brunello-cucinelli",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "byredo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "canada-goose",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "carolina-herrera",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "celine",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "charles-tyrwhitt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "charlotte-tilbury",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "chloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "christian-louboutin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "coach",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "creed",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "currentbody-skin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "david-clulow-sunglasses",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "dior",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "diptyque",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "dolce-and-gabbana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "dunhill",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "dyson",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "elemis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "eleventy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "emma-bridgewater",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ermenegildo-zegna",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "etro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "fendi",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ferragamo",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "fortnum-and-mason",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ganni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "gina",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "golden-goose",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "guerlain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "hackett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "herno",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "hogan",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "hogan-at-tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "holland-cooper",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "isabel-marant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "jacob-cohen",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "jil-sander",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "jimmy-choo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "jo-malone-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "kate-spade-new-york",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "kenzo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "kiton",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "kurt-geiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "l-occitane",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "lalique",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "loewe",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "longchamp",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "loro-piana",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "lululemon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "maison-margiela",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "maje",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "manolo-blahnik",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "marc-jacobs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "max-mara",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "michael-kors",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "missoni",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "moncler",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "monica-vinader",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "montblanc",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "moose-knuckles",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "mulberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "n-peal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "neom",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "on-running",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "orlebar-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ottolenghi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "paige",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "paul-smith",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "penhaligons",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ralph-lauren-children",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "rixo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "roger-vivier",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "saint-laurent",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "sandro",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "self-portrait",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "shreeji-presents-the-village-news",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "stella-mccartney",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "stone-island",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "swatch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "sweaty-betty",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "the-white-company",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "thom-browne",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tods",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tommy-hilfiger-women-and-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tory-burch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "tumi",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "valentino",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "versace",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "vilebrequin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "vivienne-westwood",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "watchfinder-and-co",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "zimmermann",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bicester-village",
    brandId: "zwilling-ja-henckels",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "7-for-all-mankind",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "abercrombie-and-fitch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "allsaints",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "animal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "armani",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "armani-exchange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "asics",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "atelier-galleries",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "balmain",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "barbour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "beauty-outlet",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "bedeck",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "belstaff",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "ben-sherman",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "billieblush",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "birkenstock",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "boss-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "burberry",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "cadbury",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "carvela",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "castore",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "champion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "charles-tyrwhitt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "clarins",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "clogau-gold",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "coach",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "colmar",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "columbia",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "converse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "crew-clothing",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "crocs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "david-clulow",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "designer-exchange",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "diesel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "digby-and-champ",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "dior",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "dolce-and-gabbana",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "dr-martens",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "dune-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "espa",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "fendi",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "fossil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "fratelli-rossetti",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "fred-perry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "french-connection",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "gallo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "gant",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "givenchy",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "golf-apparel",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "gucci",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "guess",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "gutteridge",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hallmark",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "haribo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "harmont-and-blaine",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "havaianas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hobbs",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "holland-and-barrett",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hotel-chocolat",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hour-passion",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hugo",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "hugo-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "iris-galerie",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "jack-and-jones",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "jack-wolfskin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "jigsaw",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "joseph",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "joules",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "karl-lagerfeld",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "kate-spade-new-york",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "kenzo-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "kids-around",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "kurt-geiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "l-occitane",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "lacoste",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "le-creuset",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "lindt",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "lululemon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "michael-kors",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "miu-miu",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "mountain-warehouse",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "napapijri",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "new-balance",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "new-era",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "north-sails",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "oakley",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "original-penguin",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "osprey-london",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "pandora",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "paul-costelloe",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "paul-smith",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "playmobil",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "police",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "pollini",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "prada",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "puma",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "refrigiwear",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "rituals",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "salomon",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "samsonite",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "save-the-duck",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "schuh",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "sunglass-hut",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "superdry",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "swarovski",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "swatch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "tag-heuer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "tefal",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "the-cosmetics-company-store",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "the-north-face",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "timberland",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "timberland-kids",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "ugg",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "under-armour",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "vans",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "villeroy-and-boch",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "cheshire-oaks",
    brandId: "woolrich",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "ashford-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "bridgend-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "caledonia-park",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "clarks-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "dalton-park",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "east-midlands-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gloucester-quays",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gretna-gateway-outlet-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "gunwharf-quays",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "icon-outlet-at-the-o2",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "junction-32-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "lakeside-village",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "london-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "springfields-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "swindon-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-boulevard-banbridge",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "the-galleria-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "west-midlands-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "adidas",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "boss",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "calvin-klein",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "clarks",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "gap",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "levis",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "marks-and-spencer",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "molton-brown",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "next",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "nike",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "polo-ralph-lauren",
    featured: true,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "reiss",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "skechers",
    featured: false,
    relationStatus: "active",
  },
  {
    outletId: "york-designer-outlet",
    brandId: "tommy-hilfiger",
    featured: false,
    relationStatus: "active",
  },
];
