import type { Brand } from "../../types/brand";

/** Brand identities introduced by the Yeoju Store Info directory. */
export const yeojuBrands: Brand[] = [
  {
    brandId: "lansmere",
    brandName: "LANSMERE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "rick-owens",
    brandName: "Rick Owens",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "beaker",
    brandName: "BEAKER",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "club-monaco",
    brandName: "CLUB MONACO",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "lebeige",
    brandName: "LEBEIGE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "man-on-the-boon",
    brandName: "MAN ON THE BOON.",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "mine",
    brandName: "MINE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "mue",
    brandName: "MUE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "matin-kim",
    brandName: "Matin Kim",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "s-i-village",
    brandName: "S.I. Village",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "the-ilma",
    brandName: "The Ilma",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "tom-greyhound",
    brandName: "Tom Greyhound",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "second-run",
    brandName: "SECOND RUN",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "shinsegae-factory-store",
    brandName: "SHINSEGAE FACTORY STORE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "time",
    brandName: "TIME",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "dewl",
    brandName: "DEWL",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "daks",
    brandName: "Daks",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "froops",
    brandName: "FROOPS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "izzat-baba-izzat-collection",
    brandName: "IZZAT BABA / IZZAT COLLECTION",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "jigott",
    brandName: "JIGOTT",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "juun-j-woman",
    brandName: "Juun.J Woman",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "lucky-chouette",
    brandName: "LUCKY CHOUETTE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "le17septembre",
    brandName: "Le17septembre",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "michaa",
    brandName: "MICHAA",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "mojo-s-phine",
    brandName: "MOJO.S.PHINE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "satur",
    brandName: "SATUR",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "sjsj",
    brandName: "SJSJ",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "studio-tomboy",
    brandName: "STUDIO TOMBOY",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "system",
    brandName: "SYSTEM",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "thursday-island",
    brandName: "Thursday Island",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "cambridge-members",
    brandName: "CAMBRIDGE MEMBERS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "galaxy",
    brandName: "GALAXY",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "pottery",
    brandName: "POTTERY",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "series",
    brandName: "SERIES",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "solid-homme",
    brandName: "SOLID HOMME",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "songzio-homme",
    brandName: "SONGZIO HOMME",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "sieg",
    brandName: "Sieg",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "lifework",
    brandName: "LifeWork",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "helen-kaminski",
    brandName: "Helen Kaminski",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "heritage-kumkang",
    brandName: "Heritage Kumkang",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "joy-gryson",
    brandName: "Joy Gryson",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "louis-quatorze",
    brandName: "LOUIS QUATORZE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "misope",
    brandName: "Misope",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "suecomma-bonnie",
    brandName: "Suecomma Bonnie",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "tandy",
    brandName: "Tandy",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "vunque",
    brandName: "vunque",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "a-p-c-golf",
    brandName: "A.P.C. GOLF",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "anewgolf",
    brandName: "ANEWGOLF",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "amazingcre",
    brandName: "AmazingCre",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "boss-golf",
    brandName: "Boss Golf",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "chervo",
    brandName: "CHERVO",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "challenger",
    brandName: "Challenger",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "discovery",
    brandName: "DISCOVERY",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "dunlop",
    brandName: "DUNLOP",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "dynafit",
    brandName: "Dynafit",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "helinox",
    brandName: "Helinox",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "lanvin-blanc",
    brandName: "Lanvin Blanc",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "masterbunny",
    brandName: "Masterbunny",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "off-out",
    brandName: "OFF/OUT",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "southcape",
    brandName: "SOUTHCAPE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "st-andrews",
    brandName: "ST ANDREWS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "titleist",
    brandName: "Titleist",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "barbara-vivien",
    brandName: "BARBARA/VIVIEN",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "babara",
    brandName: "Babara",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "foot-joy",
    brandName: "Foot Joy",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "golden-dew",
    brandName: "Golden Dew",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "roseedor",
    brandName: "RoseeDor",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "s-i-beauty-club",
    brandName: "S.I Beauty Club",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "soda",
    brandName: "Soda",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "the-cosmetics-club",
    brandName: "THE COSMETICS CLUB",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "triumph-elle",
    brandName: "Triumph/Elle",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "venus-wacoal",
    brandName: "Venus/Wacoal",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "burberry-children",
    brandName: "Burberry Children",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "happyland-house",
    brandName: "Happyland House",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "kangol-kids",
    brandName: "KANGOL KIDS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "lee-kids",
    brandName: "Lee Kids",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "little-ground",
    brandName: "Little Ground",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "magic-edition",
    brandName: "MAGIC EDITION",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "marithe-kids",
    brandName: "Marithe Kids",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "national-geographic-kids",
    brandName: "NATIONAL GEOGRAPHIC KIDS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "nba-kids",
    brandName: "NBA Kids",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "nike-kids-value-store",
    brandName: "Nike Kids Value Store",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "off-label",
    brandName: "Off Label",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "toebox",
    brandName: "TOEBOX",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "top10-kids",
    brandName: "Top10 Kids",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "bang-and-olufsen-bowers-and-wilkins",
    brandName: "B&O/B&W",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "jaju",
    brandName: "JAJU",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "wine-and-more",
    brandName: "WINE&MORE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "art-centum",
    brandName: "ART CENTUM",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "fannie",
    brandName: "Fannie",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "five-guys",
    brandName: "Five Guys",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "hansung-pop-up",
    brandName: "HANSUNG POP-UP",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "hwasoon",
    brandName: "Hwasoon",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "igane-topokki",
    brandName: "Igane topokki",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "jackson",
    brandName: "Jackson",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "jung-kwan-jang",
    brandName: "Jung Kwan Jang",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "kary-market",
    brandName: "Kary Market",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "onsen",
    brandName: "Onsen",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "palseonsaeng",
    brandName: "Palseonsaeng",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "pizzeria-o",
    brandName: "Pizzeria O",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "shinsegae-outlet",
    brandName: "Shinsegae Outlet",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "taco-bell",
    brandName: "Taco bell",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "twitzel",
    brandName: "Twitzel",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "yeoju-ceramics",
    brandName: "YEOJU CERAMICS",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "yeoju-market-place",
    brandName: "YEOJU MARKET PLACE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "ililhyang",
    brandName: "ililhyang",
    aliases: [],
    categoryId: "food",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
];
