import type { Brand } from "../../types/brand";

export const brandsQT: Brand[] = [
  {
    brandId: "q-pot",
    brandName: "Q-pot.",
    aliases: ["Q-pot", "Q pot", "Qpot"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "fashion",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "quiksilver",
    brandName: "Quiksilver",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "rab",
    brandName: "Rab",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "rabanne",
    brandName: "Rabanne",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "luxury",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rack-room-shoes",
    brandName: "Rack Room Shoes",
    aliases: ["RackRoomShoes"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "radley",
    brandName: "Radley",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "rag-and-bone",
    brandName: "rag & bone",
    aliases: [
      "Rag and Bone",
      "Rag & Bone",
      "rag and bone",
      "rag bone",
      "ragbone",
      "RagandBone",
      "Rag Bone",
      "RagBone",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "rainbow",
    brandName: "Rainbow",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "rally-house",
    brandName: "Rally House",
    aliases: ["RallyHouse"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ralph-lauren-children",
    brandName: "Ralph Lauren Children",
    aliases: ["RalphLaurenChildren"],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "rampal-latour",
    brandName: "Rampal Latour",
    aliases: ["RampalLatour"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ravensburger",
    brandName: "Ravensburger",
    aliases: [],
    categoryId: "children",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ray-ban",
    brandName: "Ray-Ban",
    aliases: ["Ray Ban", "RayBan"],
    categoryId: "eyewear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 90,
    brandStatus: "active",
  },
  {
    brandId: "rebecca-minkoff",
    brandName: "Rebecca Minkoff",
    aliases: ["RebeccaMinkoff"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "rebel-queen",
    brandName: "Rebel Queen",
    aliases: ["RebelQueen"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "recto",
    brandName: "RECTO",
    aliases: ["Recto"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "south-korea",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "reebok",
    brandName: "Reebok",
    aliases: ["Reebok Outlet", "ReebokOutlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "refa",
    brandName: "ReFa",
    aliases: ["Refa"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "refrigiwear",
    brandName: "RefrigiWear",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "regal",
    brandName: "REGAL",
    aliases: ["Regal"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "regis",
    brandName: "Regis",
    aliases: [],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 58,
    brandStatus: "active",
  },
  {
    brandId: "reiss",
    brandName: "Reiss",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "rene-caovilla",
    brandName: "Rene Caovilla",
    aliases: ["Renè Caovilla", "René Caovilla", "ReneCaovilla"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "repetto",
    brandName: "Repetto",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "replay",
    brandName: "Replay",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "riani",
    brandName: "Riani",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "riedel",
    brandName: "Riedel",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "austria",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "rienda",
    brandName: "rienda",
    aliases: ["Rienda"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "fashion",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "rimowa",
    brandName: "RIMOWA",
    aliases: ["Rimowa"],
    categoryId: "home",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "rituals",
    brandName: "Rituals",
    aliases: ["Rituals Cosmetics", "RitualsCosmetics"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "rixo",
    brandName: "RIXO",
    aliases: ["Rixo"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "rm-williams",
    brandName: "R.M.Williams",
    aliases: [
      "R.M. Williams",
      "RM Williams",
      "R M Williams",
      "RMWilliams",
    ],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "australia",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "robert-graham",
    brandName: "Robert Graham",
    aliases: ["RobertGraham"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "roberto-cavalli",
    brandName: "Roberto Cavalli",
    aliases: ["RobertoCavalli"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "roberto-coin",
    brandName: "Roberto Coin",
    aliases: ["RobertoCoin"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "rockport",
    brandName: "Rockport",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "roger-vivier",
    brandName: "Roger Vivier",
    aliases: ["RogerVivier"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "luxury",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "rohan",
    brandName: "Rohan",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "roncato",
    brandName: "Roncato",
    aliases: [],
    categoryId: "accessories",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rope-picnic",
    brandName: "Rope Picnic",
    aliases: ["ROPE PICNIC", "RopePicnic", "ROPEPICNIC"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rossignol",
    brandName: "Rossignol",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "roxy",
    brandName: "Roxy",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "roy-rogers",
    brandName: "Roy Roger’s",
    aliases: [
      "Roy Roger's",
      "Roy Rogers",
      "Roy Roger s",
      "RoyRogers",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "rue21",
    brandName: "rue21",
    aliases: ["Rue21"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "rumi",
    brandName: "RUMI",
    aliases: ["Rumi"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "russell-athletic",
    brandName: "Russell Athletic",
    aliases: ["Russell", "RussellAthletic"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "rvca",
    brandName: "RVCA",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "rowenta",
    brandName: "Rowenta",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "premium",
    rankingWeight: 65,
    brandStatus: "active",
  },
  {
    brandId: "s-oliver",
    brandName: "s.Oliver",
    aliases: ["s Oliver", "sOliver"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "fashion",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "sabor-a-espana",
    brandName: "Sabor a España",
    aliases: ["Sabor a Espana", "SaboraEspana"],
    categoryId: "food",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "lifestyle",
    rankingWeight: 65,
    brandStatus: "active",
  },
  {
    brandId: "sacai",
    brandName: "sacai",
    aliases: ["Sacai"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "safety-1st",
    brandName: "Safety 1st",
    aliases: ["Safety1st"],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "sail-racing",
    brandName: "Sail Racing",
    aliases: ["SailRacing", "Sail Racing International", "Sail Racing Sportswear"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "sweden",
    luxuryLevel: "sports",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "saint-laurent",
    brandName: "Saint Laurent",
    aliases: [
      "Yves Saint Laurent",
      "YSL",
      "Saint Laurent",
      "SaintLaurent",
      "YvesSaintLaurent",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "luxury",
    rankingWeight: 96,
    brandStatus: "active",
  },
  {
    brandId: "saks-off-5th",
    brandName: "Saks OFF 5TH",
    aliases: [
      "Saks Fifth Avenue OFF 5TH",
      "Saks Off 5th",
      "SaksOFF5TH",
      "SaksOff5th",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "salomon",
    brandName: "Salomon",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "sports",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "samsonite",
    brandName: "Samsonite",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "sand-copenhagen",
    brandName: "Sand Copenhagen",
    aliases: ["SAND", "Sand", "SAND Copenhagen", "SandCopenhagen"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "denmark",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "sandro",
    brandName: "Sandro",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "sandro-ferrone",
    brandName: "Sandro Ferrone",
    aliases: ["SandroFerrone"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "sanrio",
    brandName: "Sanrio",
    aliases: [],
    categoryId: "children",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "santoni",
    brandName: "Santoni",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "sas-factory-shoe-store",
    brandName: "SAS Factory Shoe Store",
    aliases: [
      "SAS Shoes",
      "San Antonio Shoemakers",
      "SASFactoryShoeStore",
      "SASShoes",
      "SanAntonioShoemakers",
    ],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "sash-and-co",
    brandName: "Sash & Co",
    aliases: [
      "Sash and Co",
      "Sash Co",
      "SashCo",
      "SashandCo",
    ],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 55,
    brandStatus: "active",
  },
  {
    brandId: "saucony",
    brandName: "Saucony",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "save-the-duck",
    brandName: "Save The Duck",
    aliases: ["SaveTheDuck"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "scalpers",
    brandName: "Scalpers",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "scamp-and-dude",
    brandName: "Scamp & Dude",
    aliases: [
      "Scamp and Dude",
      "Scamp Dude",
      "ScampDude",
      "ScampandDude",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "scarpa",
    brandName: "SCARPA",
    aliases: ["Scarpa"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "schott",
    brandName: "Schott",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "schuh",
    brandName: "Schuh",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "scorett",
    brandName: "Scorett",
    aliases: ["Scorett Shoes", "Scorett Footwear", "Scorett Outlet"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "sweden",
    luxuryLevel: "fashion",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "scotch-and-soda",
    brandName: "Scotch & Soda",
    aliases: [
      "Scotch and Soda",
      "Scotch Soda",
      "ScotchSoda",
      "ScotchandSoda",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "scotch-grain",
    brandName: "Scotch Grain",
    aliases: ["ScotchGrain"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "seasalt",
    brandName: "Seasalt",
    aliases: ["Seasalt Cornwall", "SeasaltCornwall"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "seiko",
    brandName: "Seiko",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "self-portrait",
    brandName: "Self-Portrait",
    aliases: ["Self Portrait", "SelfPortrait"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "serge-blanco",
    brandName: "Serge Blanco",
    aliases: ["SergeBlanco"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sergio-rossi",
    brandName: "Sergio Rossi",
    aliases: ["SergioRossi"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "sessun",
    brandName: "Sessùn",
    aliases: ["Sessun"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "seventy",
    brandName: "Seventy",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "shinola",
    brandName: "Shinola",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "ships",
    brandName: "SHIPS",
    aliases: ["Ships"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "shiseido",
    brandName: "Shiseido",
    aliases: [],
    categoryId: "beauty",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "shoe-carnival",
    brandName: "Shoe Carnival",
    aliases: ["ShoeCarnival"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "shoe-dept",
    brandName: "SHOE DEPT.",
    aliases: [
      "Shoe Dept",
      "SHOE DEPT. ENCORE",
      "SHOE DEPT",
      "SHOEDEPT",
      "ShoeDept",
      "SHOE DEPT ENCORE",
      "SHOEDEPTENCORE",
    ],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "shoe-palace",
    brandName: "Shoe Palace",
    aliases: ["ShoePalace"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "shreeji-presents-the-village-news",
    brandName: "Shreeji Presents: The Village News",
    aliases: [
      "Shreeji",
      "The Village News",
      "Shreeji Presents The Village News",
      "TheVillageNews",
    ],
    categoryId: "home",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "sigg",
    brandName: "SIGG",
    aliases: ["Sigg"],
    categoryId: "home",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "premium",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "simone-perele",
    brandName: "Simone Pérèle",
    aliases: ["Simone Perele", "SimonePerele"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "simonetta",
    brandName: "Simonetta",
    aliases: [],
    categoryId: "children",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "sisley",
    brandName: "Sisley",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "sjyp",
    brandName: "SJYP",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "south-korea",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "skechers",
    brandName: "Skechers",
    aliases: ["Skechers Outlet", "SkechersOutlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "skullcandy",
    brandName: "Skullcandy",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "slowear",
    brandName: "Slowear",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "sly",
    brandName: "SLY",
    aliases: ["Sly"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "snidel",
    brandName: "SNIDEL",
    aliases: ["Snidel"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "snow-peak",
    brandName: "Snow Peak",
    aliases: ["SnowPeak"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "sony",
    brandName: "Sony",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "sorbino",
    brandName: "Sorbino",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "southern-marsh",
    brandName: "Southern Marsh",
    aliases: ["SouthernMarsh"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "spada",
    brandName: "Spada",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "spanx",
    brandName: "SPANX",
    aliases: ["Spanx"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "spencer-s",
    brandName: "Spencer’s",
    aliases: ["Spencer's", "Spencers", "Spencer s"],
    categoryId: "home",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "sperry",
    brandName: "Sperry",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "spick-and-span",
    brandName: "Spick & Span",
    aliases: [
      "Spick and Span",
      "Spick Span",
      "SpickSpan",
      "SpickandSpan",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "sports-direct",
    brandName: "Sports Direct",
    aliases: ["SportsDirect"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "sports",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "spyder",
    brandName: "Spyder",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "stag-london",
    brandName: "Stag London",
    aliases: ["StagLondon"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 58,
    brandStatus: "active",
  },
  {
    brandId: "st-john",
    brandName: "St. John",
    aliases: ["St John", "StJohn"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "luxury",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "stance",
    brandName: "Stance",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "star-jewelry",
    brandName: "STAR JEWELRY",
    aliases: ["Star Jewelry", "STARJEWELRY", "StarJewelry"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "stella-mccartney",
    brandName: "Stella McCartney",
    aliases: ["StellaMcCartney"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "luxury",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "steve-madden",
    brandName: "Steve Madden",
    aliases: ["SteveMadden"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "fashion",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "stone-island",
    brandName: "Stone Island",
    aliases: ["StoneIsland"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "street-one",
    brandName: "Street One",
    aliases: ["StreetOne"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "stuart-weitzman",
    brandName: "Stuart Weitzman",
    aliases: ["StuartWeitzman"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "luxury",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "suitsupply",
    brandName: "Suitsupply",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "sun-factory",
    brandName: "Sun Factory",
    aliases: ["SunFactory"],
    categoryId: "accessories",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sun-valley",
    brandName: "Sun Valley",
    aliases: ["SunValley"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sun68",
    brandName: "Sun68",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "suncoo",
    brandName: "Suncoo",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sundek",
    brandName: "Sundek",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sunglass-hut",
    brandName: "Sunglass Hut",
    aliases: ["SunglassHut"],
    categoryId: "eyewear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "sunspel",
    brandName: "Sunspel",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "superdry",
    brandName: "Superdry",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "swarovski",
    brandName: "Swarovski",
    aliases: ["SWAROVSKI"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "austria",
    luxuryLevel: "premium",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "swatch",
    brandName: "Swatch",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "fashion",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "sweaty-betty",
    brandName: "Sweaty Betty",
    aliases: ["SweatyBetty"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "system-homme",
    brandName: "System Homme",
    aliases: ["SystemHomme"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "south-korea",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "tachikichi",
    brandName: "Tachikichi",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "tag-heuer",
    brandName: "TAG Heuer",
    aliases: ["Tag Heuer", "TAGHeuer", "TagHeuer"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "luxury",
    rankingWeight: 90,
    brandStatus: "active",
  },
  {
    brandId: "t-m-lewin",
    brandName: "T.M.Lewin",
    aliases: [
      "T.M. Lewin",
      "TM Lewin",
      "T M Lewin",
      "TMLewin",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "tailor-club",
    brandName: "Tailor Club",
    aliases: ["TailorClub"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tailor-vintage",
    brandName: "Tailor Vintage",
    aliases: ["TailorVintage"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "takashimaya",
    brandName: "Takashimaya",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "takeo-kikuchi",
    brandName: "Takeo Kikuchi",
    aliases: ["TakeoKikuchi"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "talbots",
    brandName: "Talbots",
    aliases: ["Talbots Outlet", "TalbotsOutlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "fashion",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "tara-jarmon",
    brandName: "Tara Jarmon",
    aliases: ["TaraJarmon"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ted-baker",
    brandName: "Ted Baker",
    aliases: ["TedBaker"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "tefal",
    brandName: "Tefal",
    aliases: ["T-fal", "T fal", "Tfal"],
    categoryId: "home",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "teva",
    brandName: "Teva",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "sports",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "the-art-of-shaving",
    brandName: "The Art of Shaving",
    aliases: ["TheArtofShaving"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "the-body-shop",
    brandName: "The Body Shop",
    aliases: ["TheBodyShop"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "the-bridge",
    brandName: "The Bridge",
    aliases: ["TheBridge"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "the-childrens-place",
    brandName: "The Children's Place",
    aliases: [
      "The Childrens Place",
      "Children's Place Outlet",
      "The Children’s Place",
      "The Children s Place",
      "TheChildrensPlace",
      "Children’s Place Outlet",
      "Children s Place Outlet",
      "ChildrensPlaceOutlet",
    ],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "the-cosmetics-company-store",
    brandName: "The Cosmetics Company Store",
    aliases: [
      "Cosmetics Company Store",
      "CCS",
      "TCCS",
      "The Cosmetics Company",
    ],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "the-fragrance-shop",
    brandName: "The Fragrance Shop",
    aliases: ["TheFragranceShop"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "the-kooples",
    brandName: "The Kooples",
    aliases: ["TheKooples"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "premium",
    rankingWeight: 80,
    brandStatus: "active",
  },
  {
    brandId: "the-label-yard",
    brandName: "The Label Yard",
    aliases: ["TheLabelYard"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "premium",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-north-face",
    brandName: "The North Face",
    aliases: [
      "The North Face Outlet",
      "TheNorthFace",
      "TheNorthFaceOutlet",
      "North Face",
    ],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 92,
    brandStatus: "active",
  },
  {
    brandId: "the-potions-cauldron",
    brandName: "The Potions Cauldron",
    aliases: ["ThePotionsCauldron"],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 55,
    brandStatus: "active",
  },
  {
    brandId: "the-uniform-outlet",
    brandName: "The Uniform Outlet",
    aliases: ["TheUniformOutlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "theilma",
    brandName: "Theilma",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "south-korea",
    luxuryLevel: "premium",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "theory",
    brandName: "Theory",
    aliases: ["Theory Outlet", "TheoryOutlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "thom-browne",
    brandName: "Thom Browne",
    aliases: ["ThomBrowne"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "luxury",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "thun",
    brandName: "Thun",
    aliases: [],
    categoryId: "home",
    logo: "",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tillys",
    brandName: "Tillys",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "timberland",
    brandName: "Timberland",
    aliases: ["Timberland Outlet", "TimberlandOutlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 86,
    brandStatus: "active",
  },
  {
    brandId: "timberland-kids",
    brandName: "Timberland Kids",
    aliases: ["TimberlandKids"],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "time-homme",
    brandName: "Time Homme",
    aliases: ["TimeHomme"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "south-korea",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "tissot",
    brandName: "Tissot",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "premium",
    rankingWeight: 84,
    brandStatus: "active",
  },
  {
    brandId: "tods",
    brandName: "TOD'S",
    aliases: [
      "Tod's",
      "Tods",
      "TOD’S",
      "TOD S",
      "TODS",
      "Tod’s",
      "Tod s",
    ],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "luxury",
    rankingWeight: 90,
    brandStatus: "active",
  },
  {
    brandId: "tokyo-shirts",
    brandName: "Tokyo Shirts",
    aliases: ["TOKYO SHIRTS", "TokyoShirts", "TOKYOSHIRTS"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "fashion",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "toledo-72",
    brandName: "Toledo 72",
    aliases: ["Toledo72"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "tom-ford",
    brandName: "Tom Ford",
    aliases: ["TomFord"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "luxury",
    rankingWeight: 94,
    brandStatus: "active",
  },
  {
    brandId: "tom-tailor",
    brandName: "Tom Tailor",
    aliases: ["TomTailor"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "fashion",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "tommy-bahama",
    brandName: "Tommy Bahama",
    aliases: ["Tommy Bahama Outlet", "TommyBahama", "TommyBahamaOutlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "top-gift",
    brandName: "Top Gift",
    aliases: ["TopGift"],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "tommy-hilfiger",
    brandName: "Tommy Hilfiger",
    aliases: [
      "Tommy Hilfiger Outlet",
      "TommyHilfiger",
      "TommyHilfigerOutlet",
      "Tommy",
    ],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 92,
    brandStatus: "active",
  },
  {
    brandId: "tommy-hilfiger-kids",
    brandName: "Tommy Hilfiger Kids",
    aliases: ["TommyHilfigerKids"],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "tommy-hilfiger-women-and-kids",
    brandName: "Tommy Hilfiger Women & Kids",
    aliases: ["Tommy Hilfiger Women and Kids", "Tommy Hilfiger Women Kids"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "tomorrowland",
    brandName: "Tomorrowland",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "japan",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "torrid",
    brandName: "Torrid",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "fashion",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "tory-burch",
    brandName: "Tory Burch",
    aliases: ["Tory Burch Outlet", "ToryBurch", "ToryBurchOutlet"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 90,
    brandStatus: "active",
  },
  {
    brandId: "tous",
    brandName: "TOUS",
    aliases: ["Tous"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "premium",
    rankingWeight: 78,
    brandStatus: "active",
  },
  {
    brandId: "toys-n-motion",
    brandName: "Toys N Motion",
    aliases: ["ToysNMotion"],
    categoryId: "children",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "tradehome-shoes",
    brandName: "Tradehome Shoes",
    aliases: ["TradehomeShoes"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "tradition-des-vosges",
    brandName: "Tradition des Vosges",
    aliases: ["TraditiondesVosges"],
    categoryId: "home",
    logo: "",
    originCountryId: "france",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "travelpro",
    brandName: "Travelpro",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "trespass",
    brandName: "Trespass",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "sports",
    rankingWeight: 76,
    brandStatus: "active",
  },
  {
    brandId: "tripp",
    brandName: "Tripp",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "triumph",
    brandName: "Triumph",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "true-religion",
    brandName: "True Religion",
    aliases: ["True Religion Outlet", "TrueReligion", "TrueReligionOutlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "trussardi",
    brandName: "Trussardi",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "tumi",
    brandName: "TUMI",
    aliases: ["Tumi"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-states",
    luxuryLevel: "premium",
    rankingWeight: 88,
    brandStatus: "active",
  },
  {
    brandId: "twinset",
    brandName: "Twinset",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "premium",
    rankingWeight: 82,
    brandStatus: "active",
  },
  {
    brandId: "skopes",
    brandName: "Skopes",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 62,
    brandStatus: "active",
  },
  {
    brandId: "the-perfume-shop",
    brandName: "The Perfume Shop",
    aliases: ["ThePerfumeShop"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "the-works",
    brandName: "The Works",
    aliases: ["TheWorks"],
    categoryId: "books-stationery",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "value",
    rankingWeight: 58,
    brandStatus: "active",
  },
  {
    brandId: "quba-sails",
    brandName: "Quba Sails",
    aliases: ["QubaSails"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "raging-bull",
    brandName: "Raging Bull",
    aliases: ["RagingBull"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "regatta-great-outdoors",
    brandName: "Regatta Great Outdoors",
    aliases: ["RegattaGreatOutdoors"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "regatta-x-craghoppers",
    brandName: "Regatta x Craghoppers",
    aliases: ["Regatta x Craghoppers Outlet", "RegattaxCraghoppers"],
    categoryId: "outdoor",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rodd-and-gunn",
    brandName: "Rodd & Gunn",
    aliases: ["Rodd and Gunn", "Rodd Gunn", "RoddGunn"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "roman",
    brandName: "Roman",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "saltrock",
    brandName: "Saltrock",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sostrene-grene",
    brandName: "Søstrene Grene",
    aliases: ["SstreneGrene"],
    categoryId: "home",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "suit-direct",
    brandName: "Suit Direct",
    aliases: ["SuitDirect"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tempur",
    brandName: "Tempur",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-baggage-factory",
    brandName: "The Baggage Factory",
    aliases: ["TheBaggageFactory"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-entertainer",
    brandName: "The Entertainer",
    aliases: ["TheEntertainer"],
    categoryId: "toys",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-gift-company",
    brandName: "The Gift Company",
    aliases: ["TheGiftCompany"],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-range",
    brandName: "The Range",
    aliases: ["TheRange"],
    categoryId: "home",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "thomas-sabo",
    brandName: "Thomas Sabo",
    aliases: ["ThomasSabo"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tog24",
    brandName: "TOG24",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "serendipity",
    brandName: "Serendipity",
    aliases: [],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "skyl",
    brandName: "SKYL",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tk-maxx",
    brandName: "TK Maxx",
    aliases: ["TKMaxx", "T.K. Maxx", "T K Maxx"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "toytown",
    brandName: "Toytown",
    aliases: [],
    categoryId: "toys",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "retail-phone-accessories",
    brandName: "Retail Phone Accessories",
    aliases: [],
    categoryId: "electronics",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "russell-and-bromley",
    brandName: "Russell & Bromley",
    aliases: ["Russell and Bromley", "Russell Bromley", "RussellBromley"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "smiggle",
    brandName: "Smiggle",
    aliases: [],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "sole-trader",
    brandName: "Sole Trader",
    aliases: ["SoleTrader"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "sony-centre",
    brandName: "Sony Centre",
    aliases: ["SonyCentre"],
    categoryId: "electronics",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "the-sweet-emporium",
    brandName: "The Sweet Emporium",
    aliases: ["TheSweetEmporium"],
    categoryId: "accessories",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "lifestyle",
    rankingWeight: 50,
    brandStatus: "active",
  },
  {
    brandId: "refrigue",
    brandName: "Refrigue",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "portugal",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "suns-boards",
    brandName: "Suns Boards",
    aliases: ["SunsBoards"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "toys-con-te",
    brandName: "Toys Con Te",
    aliases: ["ToysConTe"],
    categoryId: "toys",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "roesle",
    brandName: "Rösle",
    aliases: ["Rosle"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "schiesser",
    brandName: "Schiesser",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "seidensticker",
    brandName: "Seidensticker",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sigikid",
    brandName: "Sigikid",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rosenthal",
    brandName: "Rosenthal",
    aliases: [],
    categoryId: "home",
    logo: "",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "roy-robson",
    brandName: "Roy Robson",
    aliases: ["RoyRobson"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "satch",
    brandName: "Satch",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "seagull",
    brandName: "Seagull",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "steiff",
    brandName: "Steiff",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "storck",
    brandName: "Storck",
    aliases: [],
    categoryId: "food",
    logo: "",
    luxuryLevel: "lifestyle",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "strellson",
    brandName: "Strellson",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sunglass-hut-lux",
    brandName: "Sunglass Hut Lux",
    aliases: ["SunglassHutLux"],
    categoryId: "eyewear",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rosle",
    brandName: "Rösle",
    aliases: ["Rosle"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "salewa",
    brandName: "Salewa",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "smashbox",
    brandName: "smashbox",
    aliases: [],
    categoryId: "beauty",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sportalm",
    brandName: "Sportalm",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tiger-of-sweden",
    brandName: "Tiger of Sweden",
    aliases: ["TigerofSweden"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tom-tailor-denim",
    brandName: "Tom Tailor Denim",
    aliases: ["TomTailorDenim"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tom-tailor-kids",
    brandName: "Tom Tailor Kids",
    aliases: ["TomTailorKids"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "too-faced",
    brandName: "Too Faced",
    aliases: ["TooFaced"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "river-woods",
    brandName: "River Woods",
    aliases: ["RiverWoods"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "selected",
    brandName: "Selected",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "the-society-shop",
    brandName: "The Society Shop",
    aliases: ["TheSocietyShop"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rado",
    brandName: "Rado",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "switzerland",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "salvatore-ferragamo",
    brandName: "Salvatore Ferragamo",
    aliases: ["SalvatoreFerragamo"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "italy",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "scents",
    brandName: "Scents",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "siebel",
    brandName: "Siebel",
    aliases: [],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "siebel-diamonds",
    brandName: "Siebel Diamonds",
    aliases: ["SiebelDiamonds"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sissy-boy",
    brandName: "Sissy Boy",
    aliases: ["SissyBoy"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "state-of-art",
    brandName: "State of Art",
    aliases: ["StateofArt"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "suit-supply",
    brandName: "Suitsupply",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "superdry-and-co",
    brandName: "Superdry & Co",
    aliases: ["Superdry and Co", "Superdry Co", "SuperdryCo"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "united-kingdom",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "topmerk-schoenen",
    brandName: "Topmerk Schoenen",
    aliases: ["TopmerkSchoenen"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "netherlands",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "roberto-verino",
    brandName: "Roberto Verino",
    aliases: ["RobertoVerino"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "premium",
    rankingWeight: 74,
    brandStatus: "active",
  },
  {
    brandId: "scalpers-woman",
    brandName: "Scalpers Woman",
    aliases: ["ScalpersWoman"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "scuffers",
    brandName: "Scuffers",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "fashion",
    rankingWeight: 68,
    brandStatus: "active",
  },
  {
    brandId: "silbon",
    brandName: "Silbon",
    aliases: ["SILBON"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "fashion",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "simorra",
    brandName: "Simorra",
    aliases: ["Javier Simorra", "JavierSimorra"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "premium",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "sita-murt",
    brandName: "Sita Murt",
    aliases: ["SitaMurt"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "spain",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "red-bull-world",
    brandName: "Red Bull World",
    aliases: ["Red Bull", "RedBullWorld", "RedBull"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "austria",
    luxuryLevel: "lifestyle",
    rankingWeight: 72,
    brandStatus: "active",
  },
  {
    brandId: "rh-plus",
    brandName: "Rh+",
    aliases: ["Rh+", "Rh"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rukka",
    brandName: "Rukka",
    aliases: ["Rukka Outlet", "RukkaOutlet"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sbs",
    brandName: "SBS",
    aliases: ["SBS"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "schlossberg",
    brandName: "Schlossberg",
    aliases: ["Schlossberg Outlet", "SchlossbergOutlet"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "skiny",
    brandName: "Skiny Hanro",
    aliases: ["Skiny Hanro Outlet", "SkinyHanro", "SkinyHanroOutlet"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tefal-official-store",
    brandName: "Tefal Official Store",
    aliases: ["TefalOfficialStore"],
    categoryId: "home",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ragwear",
    brandName: "Ragwear",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rich-and-royal",
    brandName: "Rich & Royal",
    aliases: ["Rich and Royal", "Rich Royal", "RichRoyal"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "schoffel",
    brandName: "Schöffel",
    aliases: ["Schoffel"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "ralph-lauren-home",
    brandName: "Ralph Lauren Home",
    aliases: ["RalphLaurenHome"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rene-lezard",
    brandName: "Rene Lezard",
    aliases: ["ReneLezard"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "roeckl",
    brandName: "Roeckl",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "secrid",
    brandName: "Secrid",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "sloggi",
    brandName: "Sloggi",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "tommy-jeans",
    brandName: "Tommy Jeans",
    aliases: ["TommyJeans", "Tommy Hilfiger Jeans"],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "premium",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rosendahl-design-group",
    brandName: "Rosendahl Design Group",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "denmark",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "royal-copenhagen",
    brandName: "Royal Copenhagen",
    aliases: [],
    categoryId: "home",
    logo: "",
    originCountryId: "denmark",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "samsoe-samsoe",
    brandName: "Samsøe Samsøe",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "denmark",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "signal",
    brandName: "Signal",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "denmark",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "seaside",
    brandName: "Seaside",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "portugal",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "skin-travel",
    brandName: "Skin Travel",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "portugal",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "stockout",
    brandName: "Stockout",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "portugal",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "the-press",
    brandName: "The Press",
    aliases: [],
    categoryId: "books-stationery",
    logo: "",
    originCountryId: "portugal",
    luxuryLevel: "fashion",
    rankingWeight: 70,
    brandStatus: "active",
  },
  {
    brandId: "rossmann",
    brandName: "Rossmann",
    aliases: ["Rossmann", "Rossmann", "Rossmann Outlet"],
    categoryId: "beauty",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rtv-euro-agd",
    brandName: "RTV Euro AGD",
    aliases: ["RTV Euro AGD", "RTVEuroAGD", "RTV Euro AGD Outlet"],
    categoryId: "electronics",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rylko",
    brandName: "Ryłko",
    aliases: ["Ryłko", "Ryłko", "Ryłko Outlet"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "smyk",
    brandName: "SMYK",
    aliases: ["SMYK", "SMYK", "SMYK Outlet"],
    categoryId: "children",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "solar",
    brandName: "Solar",
    aliases: ["Solar", "Solar", "Solar Outlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sorvella",
    brandName: "Sorvella",
    aliases: ["Sorvella", "Sorvella", "Sorvella Outlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "soul-converse",
    brandName: "Soul/Converse",
    aliases: ["Soul/Converse", "Soul/Converse", "Soul/Converse Outlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sunset-suits",
    brandName: "Sunset Suits",
    aliases: ["Sunset Suits", "SunsetSuits", "Sunset Suits Outlet"],
    categoryId: "fashion",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "tchibo",
    brandName: "Tchibo",
    aliases: ["Tchibo", "Tchibo", "Tchibo Outlet"],
    categoryId: "home",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sport-vision",
    brandName: "Sport Vision",
    aliases: ["SportVision", "Sport Vision Outlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "serbia",
    luxuryLevel: "sports",
    rankingWeight: 62,
    brandStatus: "active",
  },
  {
    brandId: "tamaris",
    brandName: "Tamaris",
    aliases: ["Tamaris Outlet"],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "germany",
    luxuryLevel: "lifestyle",
    rankingWeight: 66,
    brandStatus: "active",
  },
  {
    brandId: "teletorium",
    brandName: "Teletorium",
    aliases: ["Teletorium", "Teletorium", "Teletorium Outlet"],
    categoryId: "electronics",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "time-trend",
    brandName: "Time Trend",
    aliases: ["Time Trend", "TimeTrend", "Time Trend Outlet"],
    categoryId: "jewelry-watches",
    logo: "",
    originCountryId: "poland",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "swix",
    brandName: "Swix",
    aliases: ["Swix Outlet"],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "norway",
    luxuryLevel: "sports",
    rankingWeight: 70,
    brandStatus: "active",
  },

  {
    brandId: "reima",
    brandName: "Reima",
    aliases: ["Reima Outlet"],
    categoryId: "children",
    logo: "",
    originCountryId: "finland",
    luxuryLevel: "sports",
    rankingWeight: 68,
    brandStatus: "active",
  },


  {
    brandId: "skomax",
    brandName: "Skomax",
    aliases: [],
    categoryId: "shoes-bags",
    logo: "",
    originCountryId: "norway",
    luxuryLevel: "lifestyle",
    rankingWeight: 55,
    brandStatus: "active",
  },
  {
    brandId: "stadium",
    brandName: "Stadium",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "sweden",
    luxuryLevel: "lifestyle",
    rankingWeight: 62,
    brandStatus: "active",
  },
  {
    brandId: "the-brands-outlet",
    brandName: "The Brands Outlet",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    luxuryLevel: "fashion",
    rankingWeight: 55,
    brandStatus: "active",
  },
  {
    brandId: "sol-ere",
    brandName: "SOL'ERE",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rademar-outlet",
    brandName: "Rademar Outlet",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "rahva-raamat",
    brandName: "Rahva Raamat",
    aliases: [],
    categoryId: "books-toys",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "salamander-outlet",
    brandName: "Salamander Outlet",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sokisahtel-outlet",
    brandName: "Sokisahtel Outlet",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sportland-outlet",
    brandName: "Sportland Outlet",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sportplus-outlet",
    brandName: "Sportplus Outlet",
    aliases: [],
    categoryId: "sportswear",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "terranova",
    brandName: "TERRANOVA",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "randr-boutique",
    brandName: "R&R Boutique",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
  {
    brandId: "sofiaman",
    brandName: "Sofiaman",
    aliases: [],
    categoryId: "fashion",
    logo: "",
    originCountryId: "unknown",
    luxuryLevel: "fashion",
    rankingWeight: 60,
    brandStatus: "active",
  },
];
