import type { Brand } from "../../types/brand";

const rows: Array<[string, string, string, string]> = [
  ["adidas", "adidas", "sportswear", "sports"],
  ["nike", "Nike", "sportswear", "sports"],
  ["polo-ralph-lauren", "Polo Ralph Lauren", "fashion", "premium"],
  ["tommy-hilfiger", "Tommy Hilfiger", "fashion", "premium"],
  ["calvin-klein", "Calvin Klein", "fashion", "premium"],
  ["levis", "Levi's", "fashion", "fashion"],
  ["diesel", "Diesel", "fashion", "premium"],
  ["guess", "GUESS", "fashion", "premium"],
  ["lacoste", "Lacoste", "fashion", "premium"],
  ["puma", "Puma", "sportswear", "sports"],
  ["gant", "GANT", "fashion", "premium"],
  ["under-armour", "Under Armour", "sportswear", "sports"],
  ["boss", "BOSS", "fashion", "premium"],
  ["the-north-face", "The North Face", "sportswear", "premium"],
  ["helly-hansen", "Helly Hansen", "sportswear", "premium"],
  ["skechers", "Skechers", "shoes-bags", "fashion"],
  ["new-balance", "New Balance", "sportswear", "sports"],
  ["jack-jones", "Jack & Jones", "fashion", "fashion"],
  ["tefal", "Tefal", "home", "lifestyle"],
  ["triumph", "Triumph", "fashion", "fashion"],
  ["asics", "ASICS", "sportswear", "sports"],
  ["mizuno", "Mizuno", "sportswear", "sports"],
  ["fila", "FILA", "sportswear", "sports"],
  ["columbia", "Columbia", "sportswear", "premium"],
  ["coach", "Coach", "shoes-bags", "premium"],
  ["champion", "Champion", "sportswear", "sports"],
  ["clarks", "Clarks", "shoes-bags", "fashion"],
  ["kate-spade-new-york", "Kate Spade New York", "shoes-bags", "premium"],
  ["michael-kors", "Michael Kors", "fashion", "premium"],
  ["tory-burch", "Tory Burch", "fashion", "premium"],
  ["lululemon", "lululemon", "sportswear", "premium"],
  ["burberry", "Burberry", "luxury", "luxury"],
  ["crocs", "Crocs", "shoes-bags", "fashion"],
  ["vans", "Vans", "shoes-bags", "fashion"],
  ["napapijri", "Napapijri", "fashion", "premium"],
  ["replay", "Replay", "fashion", "premium"],
  ["geox", "Geox", "shoes-bags", "premium"],
  ["timberland", "Timberland", "shoes-bags", "premium"],
  ["karl-lagerfeld", "Karl Lagerfeld", "fashion", "premium"],
  ["salomon", "Salomon", "sportswear", "premium"],
  ["4f", "4F", "sportswear", "sports"],
  ["h-and-m", "H&M", "fashion", "fashion"],
  ["j-crew", "J.Crew", "fashion", "fashion"],
  ["reebok", "Reebok", "sportswear", "sports"],
  ["tumi", "TUMI", "shoes-bags", "premium"],
  ["victorias-secret", "Victoria's Secret", "fashion", "premium"],
  ["ugg", "UGG", "shoes-bags", "premium"],
  ["dolce-and-gabbana", "Dolce & Gabbana", "luxury", "luxury"],
  ["gucci", "Gucci", "luxury", "luxury"],
  ["zadig-and-voltaire", "Zadig & Voltaire", "fashion", "premium"],
  ["zegna", "ZEGNA", "luxury", "luxury"],
  ["armani-outlet", "Armani Outlet", "fashion", "premium"],
];

export const finalExpansionBrands: Brand[] = rows.map(([brandId, brandName, categoryId, luxuryLevel]) => ({
  brandId,
  brandName,
  aliases: [],
  categoryId,
  logo: "",
  luxuryLevel,
  rankingWeight: 70,
  brandStatus: "active",
}));
