export const austriaOutlets = [
  {
    outletId: "designer-outlet-parndorf",
    name: "Designer Outlet Parndorf",
    slug: "designer-outlet-parndorf",
    countryId: "austria",
    cityId: "vienna",
    address: "Designer Outlet Straße 1, 7111 Parndorf, Austria",
    latitude: 47.9807,
    longitude: 16.8425,
    openingHours: "Mon-Fri 09:00 - 21:00; Sat 09:00 - 18:00; Sun closed",
    heroImage: "",
    galleryImages: [],
    storesCountText: "160 designer stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Free Parking",
      "EV Charging",
      "Disabled Parking",
      "Guest Services",
      "Gift Cards",
      "Tax Free Shopping",
      "Free Wi-Fi",
      "ATM",
      "Lockers",
      "Luggage Drop",
      "Family Facilities",
      "Dog Friendly",
      "Prayer or Quiet Room",
      "Tailor Service",
      "Shuttle Bus"
    ],
    restaurants: [
      "Amici Napoli",
      "Artner",
      "Asia Up",
      "Bistrot Italiano",
      "Burger King",
      "Cioco Bar",
      "Döner Bros",
      "Le Burger",
      "Leon Street Food",
      "Lia's",
      "Lia's Bistrot",
      "myBurgenland Bistro",
      "Nannuk",
      "Nordsee",
      "Pretzels Paradise",
      "Sacher Café",
      "Starbucks",
      "Tommy's Coffee",
      "wagamama",
      "Wurstliebe"
    ],
    restaurantSummary: "Dining options listed in outlet data include Amici Napoli, Artner, Asia Up, and more.",
    parking: "Official outlet services list free parking for visitors.",
    taxFreeAvailable: true,
    vatRate: 20,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "75.01 EUR",
    taxFreeOperator: "Interchange / participating tax refund operators",
    taxFreeOfficeInfo: "Guests visiting from outside the EU can receive a tax refund on eligible purchases. Use the on-site tax-free office or participating stores for the current refund process and validate forms when leaving the EU.",
    cityCenterDistanceKm: 45,
    airportDistanceKm: 40,
    airports: [
      { code: "VIE", name: "Vienna International Airport", distanceKm: 40 },
      { code: "BTS", name: "Bratislava Airport", distanceKm: 45 }
    ],
    cityCenterInfo: {
      name: "Vienna City Centre",
      distanceKm: 45,
      recommendedRoute: "Shuttle bus from Vienna State Opera or train to Parndorf Ort with station bus"
    },
    nearby: [
      { name: "Bratislava", distanceKm: 35 },
      { name: "Neusiedl am See", distanceKm: 8 }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/at/designer-outlet-parndorf/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Designer%20Outlet%20Stra%C3%9Fe%201%2C%207111%20Parndorf%2C%20Austria",
    appleMapsUrl: "http://maps.apple.com/?q=Designer%20Outlet%20Stra%C3%9Fe%201%2C%207111%20Parndorf%2C%20Austria",
    yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Stra%C3%9Fe%201%2C%207111%20Parndorf%2C%20Austria"
  }
];
