import type { Outlet } from "../../types/outlet";

export const hongKongOutlets: Outlet[] = [
  {
    "outletId": "citygate-outlets",
    "name": "Citygate Outlets",
    "slug": "citygate-outlets",
    "countryId": "hong-kong",
    "cityId": "tung-chung",
    "address": "18-20 Tat Tung Road, Tung Chung, Lantau, Hong Kong",
    "latitude": 22.29026,
    "longitude": 113.94134,
    "openingHours": "Daily 10:00 - 22:00. Individual store and holiday hours may vary.",
    "heroImage": "",
    "galleryImages": [],
    "storesCountText": "136 listed brands",
    "rating": 0,
    "reviewCount": 0,
    "services": [
      "Customer Care Centre",
      "Free Wi-Fi",
      "Lockers",
      "Foreign Exchange",
      "Baby Care Room",
      "Breastfeeding Room",
      "ATM",
      "Mobile Phone Charger Rental",
      "Stroller Lending",
      "Wheelchair Lending",
      "Umbrella Lending",
      "Delivery Service",
      "Parking",
      "EV Charging"
    ],
    "restaurants": [
      "Olea",
      "A Cheng Goose",
      "Andante",
      "Bakehouse",
      "Blue Bottle Coffee",
      "Canton House",
      "Châteraisé",
      "Chef Hung Taiwanese Beef Noodle",
      "Chun Shui Tang Culture Tea House",
      "Cinnabon",
      "Cupping Room Coffee Roasters",
      "Dab-pa Modern Chinese Cuisine",
      "Essence",
      "FireBird",
      "Food Republic",
      "Fresh",
      "Genki Sushi",
      "Golden Dragon",
      "Goobne Chicken",
      "Gyu-Kaku J",
      "hana-musubi",
      "HANNOSUKE",
      "Jasmine",
      "Kee Wah Bakery",
      "LAW MARK KEE",
      "LIAN",
      "Luscious Yunnan Rice Noodles",
      "McDonald's & McCafé",
      "Meet Fresh",
      "Mister Donut",
      "Moccato",
      "Moon Lok Chiu Chow",
      "Nabe Urawa",
      "Nha Trang Vietnamese Cuisine",
      "Olea",
      "Oolaa",
      "Oreryu Shio Ramen",
      "Outback Steakhouse",
      "Pho Le",
      "PizzaExpress",
      "Pret A Manger",
      "QUE",
      "Shabu Days by Mou Mou Club",
      "Shake Shack",
      "Shokudo Wara",
      "Silk.",
      "Starbucks Reserve™",
      "TeaWood Taiwanese Cafe & Restaurant",
      "TenRen's Tea",
      "The Enclave",
      "The Pavilion",
      "TSUJIHAN",
      "Venchi",
      "Watson's Wine",
      "XIHE YA YUAN"
    ],
    "taxFreeAvailable": false,
    "taxFreeOfficeInfo": "Hong Kong does not impose a general sales tax, VAT or GST, so a standard tourist VAT refund scheme is not applicable.",
    "cityCenterDistanceKm": 22,
    "airportDistanceKm": 3,
    "websiteUrl": "https://www.citygateoutlets.com.hk/en/",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Citygate%20Outlets%2C%20Tung%20Chung%2C%20Hong%20Kong",
    "appleMapsUrl": "https://maps.apple.com/?q=Citygate%20Outlets%20Hong%20Kong",
    "yandexMapsUrl": "https://yandex.com/maps/?text=Citygate%20Outlets%20Hong%20Kong",
    "status": "active",
    "cityCenterInfo": {
      "name": "Hong Kong",
      "distanceKm": 22
    },
    "airports": [
      {
        "code": "HKG",
        "name": "Hong Kong",
        "distanceKm": 3
      }
    ],
    "distanceBasis": "straight-line",
    "metadataVerifiedAt": "2026-09-12"
  }
];
