export const hungaryOutlets = [
  {
    outletId: "premier-outlet-budapest",
    name: "Premier Outlet Budapest",
    slug: "premier-outlet-budapest",
    countryId: "hungary",
    cityId: "budapest",
    address: "Budaörsi út 4, 2051 Biatorbágy, Hungary",
    latitude: 47.4599,
    longitude: 18.9028,
    openingHours: "Monday-Sunday 10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    services: [],
    restaurants: [],
    taxFreeAvailable: true,
    vatRate: 0,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "",
    taxFreeOperator: "",
    taxFreeOfficeInfo: "",
    cityCenterDistanceKm: 0,
    airportDistanceKm: 0,
    airports: [],
    cityCenterInfo: {
      name: "",
      distanceKm: 0,
      recommendedRoute: ""
    },
    nearby: [],
    storesCountText: "more than 100 shops",
    websiteUrl: "https://www.premieroutlet.hu/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Premier%20Outlet%20Budapest%2C%20Buda%C3%B6rsi%20%C3%BAt%204%2C%202051%20Biatorb%C3%A1gy%2C%20Hungary",
    appleMapsUrl: "http://maps.apple.com/?q=Premier%20Outlet%20Budapest%2C%20Buda%C3%B6rsi%20%C3%BAt%204%2C%202051%20Biatorb%C3%A1gy%2C%20Hungary",
    yandexMapsUrl: "https://yandex.com/maps/?text=Premier%20Outlet%20Budapest%2C%20Buda%C3%B6rsi%20%C3%BAt%204%2C%202051%20Biatorb%C3%A1gy%2C%20Hungary"
  }
];
