export const italyOutlets = [
  {
    outletId: "barberino",
    name: "Barberino Designer Outlet",
    slug: "barberino",
    countryId: "italy",
    cityId: "florence",
    address: "Via Meucci snc, 50031 Barberino di Mugello FI, Italy",
    latitude: 44.0069,
    longitude: 11.2141,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 130 stores",
    rating: 4.5,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Private Transfer",
      "Camper Parking Area",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Antica Focacceria San Francesco",
      "Caffè Mediceo",
      "Farinella",
      "Hamerica's",
      "Il Torracchione",
      "La Piadineria",
      "Lindt",
      "Poke House"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Participating stores / Tax-Free kiosk at Guest Services / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores for purchases from €70.01 in the same store on the same day. Forms can be validated before departure at airport customs, at the Tax-Free kiosk located at Barberino Outlet Guest Services, or online.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 20,
    airports: [
      {
        code: "FLR",
        name: "Florence Airport",
        distanceKm: 20
      },
      {
        code: "BLQ",
        name: "Bologna Airport",
        distanceKm: 75
      },
      {
        code: "PSA",
        name: "Pisa International Airport",
        distanceKm: 105
      }
    ],
    cityCenterInfo: {
      name: "Florence City Centre",
      distanceKm: 30,
      recommendedRoute: "Shuttle or car via A1"
    },
    nearby: [
      {
        name: "Barberino di Mugello",
        distanceKm: 4
      },
      {
        name: "Florence",
        distanceKm: 30
      }
    ],
    websiteUrl: "https://www.barberinooutlet.com/en/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Barberino+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Barberino+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Barberino%20Designer%20Outlet"
  },
  {
    outletId: "castel-romano",
    name: "Castel Romano Designer Outlet",
    slug: "castel-romano",
    countryId: "italy",
    cityId: "rome",
    address: "Via Ponte di Piscina Cupa 64, 00128 Castel Romano, Roma, Italy",
    latitude: 41.7169,
    longitude: 12.4446,
    openingHours: "Generally 10:00 - 20:00; summer special openings may extend to 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 150 designer brands",
    rating: 4.5,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Bollicine&Co",
      "Bonetti",
      "Eat Artisti del Gusto - Illy",
      "Farinella",
      "Ham Holy Burger",
      "McDonald's",
      "Obicà",
      "Signorvino",
      "Starbucks",
      "Venchi"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue Tax Free desk / Guest Services self-service kiosks / Forexchange / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €70.01 in the same store on the same day. Castel Romano lists a Global Blue Tax Free desk and self-service kiosks at Guest Services, plus an onsite Forexchange Tax Refund Office for eligible in-centre refund assistance before EU customs validation.",
    cityCenterDistanceKm: 25,
    airportDistanceKm: 25,
    airports: [
      {
        code: "FCO",
        name: "Rome Fiumicino Airport",
        distanceKm: 25
      },
      {
        code: "CIA",
        name: "Rome Ciampino Airport",
        distanceKm: 25
      }
    ],
    cityCenterInfo: {
      name: "Rome City Centre",
      distanceKm: 25,
      recommendedRoute: "Shuttle bus from Rome Termini or car via Via Pontina"
    },
    nearby: [
      {
        name: "Rome EUR",
        distanceKm: 18
      },
      {
        name: "Pomezia",
        distanceKm: 10
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-castel-romano/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Castel+Romano+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Castel+Romano+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Castel%20Romano%20Designer%20Outlet"
  },
  {
    outletId: "fidenza-village",
    name: "Fidenza Village",
    slug: "fidenza-village",
    countryId: "italy",
    cityId: "milan",
    address: "Via Federico Fellini 1, 43036 Fidenza PR, Italy",
    latitude: 44.8637,
    longitude: 10.0616,
    openingHours: "Generally 10:00 - 20:00; Thursday until 23:00 and selected summer dates until 22:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "120+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Hands-free Shopping",
      "Personal Shopping",
      "VIP Lounge"
    ],
    restaurants: [
      "Koi Sushi",
      "Lievità",
      "Lindt",
      "Panino Giusto",
      "Parma Menù",
      "Signorvino",
      "Venchi"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue and Planet tax-free kiosks / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a VAT refund form in participating boutiques when spending over €70.01. Fidenza Village lists Global Blue and Planet instant tax-free kiosks located in The Concierge; airport customs validation remains available when leaving the EU.",
    cityCenterDistanceKm: 110,
    airportDistanceKm: 110,
    airports: [
      {
        code: "LIN",
        name: "Milan Linate Airport",
        distanceKm: 110
      },
      {
        code: "MXP",
        name: "Milan Malpensa Airport",
        distanceKm: 150
      },
      {
        code: "BLQ",
        name: "Bologna Guglielmo Marconi Airport",
        distanceKm: 115
      }
    ],
    cityCenterInfo: {
      name: "Milan City Centre",
      distanceKm: 110,
      recommendedRoute: "Train to Fidenza + local transfer"
    },
    nearby: [
      {
        name: "Parma",
        distanceKm: 30
      },
      {
        name: "Bologna",
        distanceKm: 115
      }
    ],
    websiteUrl: "https://www.thebicestercollection.com/fidenza-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Fidenza+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Fidenza+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Fidenza%20Village"
  },
  {
    outletId: "la-reggia",
    name: "La Reggia Designer Outlet",
    slug: "la-reggia",
    countryId: "italy",
    cityId: "naples",
    address: "S.P. 336 Sannitica, 81025 Marcianise CE, Italy",
    latitude: 41.0286,
    longitude: 14.3092,
    openingHours: "10:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 160 designer brands",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Artisti del Gusto",
      "Burger King",
      "Farinella",
      "La Piadineria",
      "Poke House",
      "Re Nero Caffè",
      "Rossopomodoro",
      "Starbucks"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: false,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "No official outlet/operator tax-free desk or specific tax-free operator information was verified for this outlet. Eligible visitors should confirm directly with individual stores before purchase.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 20,
    airports: [
      {
        code: "NAP",
        name: "Naples International Airport",
        distanceKm: 20
      }
    ],
    cityCenterInfo: {
      name: "Naples City Centre",
      distanceKm: 30,
      recommendedRoute: "Shuttle bus or car via A1"
    },
    nearby: [
      {
        name: "Caserta",
        distanceKm: 10
      },
      {
        name: "Naples",
        distanceKm: 30
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-la-reggia/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=La+Reggia+Designer+Outlet+S.P.+336+Sannitica+Marcianise",
    appleMapsUrl: "http://maps.apple.com/?q=La+Reggia+Designer+Outlet+S.P.+336+Sannitica+Marcianise",
    yandexMapsUrl: "https://yandex.com/maps/?text=La%20Reggia%20Designer%20Outlet%20S.P.%20336%20Sannitica%20Marcianise"
  },
  {
    outletId: "noventa",
    name: "Noventa di Piave Designer Outlet",
    slug: "noventa",
    countryId: "italy",
    cityId: "venice",
    address: "Via Marco Polo 1, 30020 Noventa di Piave VE, Italy",
    latitude: 45.6734,
    longitude: 12.5446,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 170 stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Bistrot",
      "Bollicine&Co.",
      "Bonetti",
      "Farinella",
      "Hamerica's",
      "Jody's",
      "La Piadineria",
      "Lindt",
      "Panino Giusto",
      "Starbucks",
      "Sutto Caffè",
      "Sutto Osteria",
      "Tramè",
      "Venchi"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Participating stores / in-centre Tax Refund points / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €70.01 in the same store on the same day. Noventa di Piave lists in-centre Tax Refund points for assistance before EU customs validation.",
    cityCenterDistanceKm: 45,
    airportDistanceKm: 30,
    airports: [
      {
        code: "VCE",
        name: "Venice Marco Polo Airport",
        distanceKm: 30
      },
      {
        code: "TSF",
        name: "Treviso Airport",
        distanceKm: 35
      },
      {
        code: "VRN",
        name: "Verona Airport",
        distanceKm: 145
      }
    ],
    cityCenterInfo: {
      name: "Venice City Centre",
      distanceKm: 45,
      recommendedRoute: "Shuttle, bus, or car via A4"
    },
    nearby: [
      {
        name: "Noventa di Piave",
        distanceKm: 2
      },
      {
        name: "Venice",
        distanceKm: 45
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-noventa-di-piave/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Noventa+di+Piave+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Noventa+di+Piave+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Noventa%20di%20Piave%20Designer%20Outlet"
  },
  {
    outletId: "serravalle-designer-outlet",
    name: "Serravalle Designer Outlet",
    slug: "serravalle-designer-outlet",
    countryId: "italy",
    cityId: "milan",
    address: "Via della Moda 1, 15069 Serravalle Scrivia AL, Italy",
    latitude: 44.7359,
    longitude: 8.8367,
    openingHours: "Monday - Friday 10:00 - 20:00; Saturday - Sunday 09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 230 stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Shuttle / Transport Info",
      "Premium Parking",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Hands-free Shopping",
      "Shopping from Home",
      "Currency Exchange",
      "Helmet Storage",
      "Personal Shopping"
    ],
    restaurants: [
      "Bollicine&Co",
      "Bomaki",
      "Bonetti",
      "Cioccolati Italiani",
      "Eataly",
      "Farinella",
      "Farinella Bakery",
      "Focaccino",
      "God Save The Food",
      "La Piadineria",
      "Le Dolci Terre",
      "Mc Donald's",
      "Obicà",
      "Starbucks",
      "Wagamama"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Western Union Tax Refund office / Global Blue direct refund point / Guest Services self-service kiosks / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €70.01 in the same store on the same day. Serravalle lists in-centre refund support through the Western Union Tax Refund office open 10:00–20:00, the Global Blue direct refund point open 12:00–20:00, and self-service kiosks at Guest Services; customs validation is still required before leaving the EU.",
    cityCenterDistanceKm: 95,
    airportDistanceKm: 95,
    airports: [
      {
        code: "LIN",
        name: "Milan Linate Airport",
        distanceKm: 95
      },
      {
        code: "MXP",
        name: "Milan Malpensa Airport",
        distanceKm: 120
      },
      {
        code: "GOA",
        name: "Genoa Cristoforo Colombo Airport",
        distanceKm: 55
      }
    ],
    cityCenterInfo: {
      name: "Milan City Centre",
      distanceKm: 95,
      recommendedRoute: "Shuttle or train + bus via Serravalle Scrivia"
    },
    nearby: [
      {
        name: "Genoa",
        distanceKm: 55
      },
      {
        name: "Novi Ligure",
        distanceKm: 7
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-serravalle/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Serravalle+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Serravalle+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Serravalle%20Designer%20Outlet"
  },
  {
    outletId: "the-mall-firenze",
    name: "The Mall Firenze",
    slug: "the-mall-firenze",
    countryId: "italy",
    cityId: "florence",
    address: "Via Europa 8, 50066 Leccio Reggello FI, Italy",
    latitude: 43.6936,
    longitude: 11.4656,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "30+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Booking a table",
      "Direct Bus",
      "Download Map",
      "In-store appointment",
      "Mail Order",
      "Parking",
      "Tax Free Lounge",
      "EV Charging",
      "Free Umbrella",
      "The Mall Club",
      "VIP Lounge by Poltrona Frau"
    ],
    restaurants: [
      "ToscaNino Bistrò",
      "ToscaNino Restaurant&Bottega",
      "Toscapino"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "Over 70 EUR",
    taxFreeOperator: "The Mall Firenze Tax Free Lounge",
    taxFreeOfficeInfo: "Guests from non-EU countries can request an immediate refund of part of the VAT on purchases over €70 made at The Mall Firenze or elsewhere in Italy. The Tax Free Lounge requires store-issued Tax Free forms, passport or eligible Swiss identity card, and a valid credit card in the applicant's name. The airport customs validation step is still required when leaving the European Union.",
    cityCenterDistanceKm: 35,
    airportDistanceKm: 45,
    airports: [
      {
        code: "FLR",
        name: "Florence Airport",
        distanceKm: 45
      },
      {
        code: "PSA",
        name: "Pisa International Airport",
        distanceKm: 120
      },
      {
        code: "BLQ",
        name: "Bologna Airport",
        distanceKm: 125
      }
    ],
    cityCenterInfo: {
      name: "Florence City Centre",
      distanceKm: 35,
      recommendedRoute: "Direct bus or car via A1"
    },
    nearby: [
      {
        name: "Reggello",
        distanceKm: 8
      },
      {
        name: "Florence",
        distanceKm: 35
      }
    ],
    websiteUrl: "https://firenze.themall.it/en/visit-us",
    status: "active",
    googleMapsUrl: "https://www.google.it/maps/dir//The+Mall+Firenze,+Via+Europa+8,+50066+Leccio+Reggello+FI",
    appleMapsUrl: "http://maps.apple.com/?q=The+Mall+Firenze",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Mall%20Firenze"
  },
  {
    outletId: "valdichiana-village",
    name: "Valdichiana Village",
    slug: "valdichiana-village",
    countryId: "italy",
    cityId: "foiano-della-chiana",
    address: "Via Enzo Ferrari 5, 52045 Foiano della Chiana AR, Italy",
    latitude: 43.2669,
    longitude: 11.8147,
    openingHours: "Shops daily 10:00 - 20:00; restaurants & cafés Mon-Thu 09:00 - 21:00; Fri-Sun and public holidays 09:00 - 22:00; special summer opening hours may vary",
    heroImage: "",
    galleryImages: [],
    storesCountText: "130+ Fashion & Lifestyle Brands",
    rating: 4.5,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Premium CLUB"
    ],
    restaurants: [
      "Badiani",
      "Billi's",
      "Da Michele",
      "Ice Village",
      "La Piadineria - Yoyogurt",
      "Old Wild West",
      "Poke House",
      "Terre di Masaccio"
    ],
    taxFreeAvailable: false,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "No official outlet/operator tax-free desk or specific tax-free operator information was verified for this outlet. Eligible visitors should confirm directly with individual stores before purchase.",
    parking: "Official directions and village pages provide visitor access to Valdichiana Designer Village at Via Enzo Ferrari 5; parking availability should be confirmed on arrival.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 75,
    airports: [
      {
        code: "FLR",
        name: "Florence Airport",
        distanceKm: 95
      },
      {
        code: "PEG",
        name: "Perugia San Francesco d'Assisi Airport",
        distanceKm: 75
      }
    ],
    cityCenterInfo: {
      name: "Arezzo City Centre",
      distanceKm: 30,
      recommendedRoute: "Car via A1 / Valdichiana exit"
    },
    nearby: [
      {
        name: "Foiano della Chiana",
        distanceKm: 4
      },
      {
        name: "Arezzo",
        distanceKm: 30
      }
    ],
    websiteUrl: "https://www.valdichianadesignervillage.com/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Valdichiana+Village+Via+Enzo+Ferrari+5+52045+Foiano+della+Chiana",
    appleMapsUrl: "http://maps.apple.com/?q=Valdichiana%20Village&address=Via%20Enzo%20Ferrari%205%2C%2052045%20Foiano%20della%20Chiana%20AR%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Valdichiana%20Village%2C%20Via%20Enzo%20Ferrari%205%2C%2052045%20Foiano%20della%20Chiana"
  } as any,
  {
    outletId: "palmanova-designer-village",
    name: "Palmanova Designer Village",
    slug: "palmanova-designer-village",
    countryId: "italy",
    cityId: "palmanova",
    address: "SP 126 Km 1,6, 33041 Joannis di Aiello del Friuli (UD), Italy",
    latitude: 45.8786,
    longitude: 13.3308,
    openingHours: "Monday - Sunday 10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 90 FASHION & LIFESTYLE BRANDS",
    rating: 0,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Centre Information",
      "Restaurants & Cafes",
      "Free Wi-Fi",
      "Gift Card",
      "Premium CLUB",
      "Transport Info"
    ],
    restaurants: ["Antica Pizzeria Da Michele", "Dall'Ava Italian Excellence", "Dall’Ava Italian Excellence – Caffetteria Bakery", "Hamerica's", "La Piadineria"],
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "TAX FREE Shopping / participating stores / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request tax-free shopping support in participating stores and validate export documents when leaving the EU.",
    parking: "ROS lists 2,500 parking spaces for Palmanova Designer Village.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 20,
    airports: [
      { code: "TRS", name: "Trieste Airport", distanceKm: 20 }
    ],
    cityCenterInfo: {
      name: "Udine City Centre",
      distanceKm: 30,
      recommendedRoute: "Follow official Palmanova Designer Village directions to SP 126 Km 1,6."
    },
    websiteUrl: "https://www.palmanovadesignervillage.com/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Palmanova+Designer+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Palmanova%20Designer%20Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Palmanova%20Designer%20Village"
  } as any,
  {
    outletId: "franciacorta-designer-village",
    name: "Franciacorta Designer Village",
    slug: "franciacorta-designer-village",
    countryId: "italy",
    cityId: "rodengo-saiano",
    address: "Piazza Cascina Moie 1/2, 25050 Rodengo Saiano BS, Italy",
    latitude: 45.5969,
    longitude: 10.1078,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 190 fashion, home, sports, and lifestyle brands",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Centre Map", "Gift Card", "Premium CLUB", "Transport Info"],
    restaurants: ["Il Cascinale", "McDonald's", "Poke House", "Spontini"],
    parking: "Official centre pages list visitor services and centre map information for Franciacorta Designer Village; confirm current parking details on the official website before visiting.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Participating stores / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors should confirm tax-free availability with participating stores and validate export documents when leaving the EU.",
    cityCenterDistanceKm: 12,
    airportDistanceKm: 43,
    airports: [{ code: "BGY", name: "Milan Bergamo Airport", distanceKm: 43 }],
    cityCenterInfo: { name: "Brescia City Centre", distanceKm: 12, recommendedRoute: "Use car or regional transport to Rodengo Saiano." },
    websiteUrl: "https://www.franciacortadesignervillage.com/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Franciacorta+Designer+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Franciacorta%20Designer%20Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Franciacorta%20Designer%20Village"
  } as any,
  {
    outletId: "mantova-village",
    name: "Mantova Village",
    slug: "mantova-village",
    countryId: "italy",
    cityId: "bagnolo-san-vito",
    address: "Via Marco Biagi, 46031 Bagnolo San Vito MN, Italy",
    latitude: 45.0818,
    longitude: 10.8762,
    openingHours: "10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 70 shops with Land of Fashion Club advantages",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Land of Fashion Club", "Restaurants & Cafes", "Village Map", "Transport Info", "Accessibility"],
    restaurants: ["Antica Pizzeria da Michele", "Badiani", "Hamerica's", "I BELLINI", "La Piadineria", "Lindt", "Pane Piero Pizza & Focaccia", "Poke House", "Renato Bosco"],
    parking: "Official Mantova Village pages list Info Point entrance at Parking B and parking areas A-B-C-D.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue Tax Free Refunds Kiosk / participating stores / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can use the Global Blue instant Tax Free Refunds Kiosk at the Village Info Point, where available, and must validate export documents when leaving the EU.",
    cityCenterDistanceKm: 12,
    airportDistanceKm: 45,
    airports: [{ code: "VRN", name: "Verona Villafranca Airport", distanceKm: 45 }],
    cityCenterInfo: { name: "Mantua City Centre", distanceKm: 12, recommendedRoute: "Use car or regional transport to Bagnolo San Vito." },
    websiteUrl: "https://www.mantovavillage.it/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mantova+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Mantova%20Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Mantova%20Village"
  } as any,
  {
    outletId: "vicolungo-the-style-outlets",
    outletName: "Vicolungo The Style Outlets",
    name: "Vicolungo The Style Outlets",
    slug: "vicolungo-the-style-outlets",
    countryId: "italy",
    cityId: "vicolungo",
    restaurants: [
      "ALICE PIZZA",
      "ANTONINO, IL BANCO DI CANNAVACCIUOLO",
      "ART&FOOD WOW VICOLUNGO",
      "BEFED",
      "BILLY TACOS",
      "BOTEGA CAFFE CACAO",
      "CALAVERA",
      "EMOZIONI D'ITALIA",
      "LA PIADINERIA",
      "LINDT",
      "LINO'S COFFEE",
      "MISCUSI",
      "OLD WILD WEST",
      "PARMA MENÙ",
      "PASTICCERIA PARIANI",
      "POKE HOUSE",
      "POPEYES",
      "ROADHOUSE MEATERY",
      "SIGNORVINO"
    ],
    officialWebsite: "https://vicolungo.thestyleoutlets.it/en",
    websiteUrl: "https://vicolungo.thestyleoutlets.it/en",
    address: "Piazza Santa Caterina, angolo Via Papa Giovanni XXIII, 28060 Vicolungo NO, Italy",
    latitude: 45.4677,
    longitude: 8.4612,
    openingHours: "Daily 09:00 - 21:00",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "150 boutiques with over 300 brands",
    services: [
      "Tax Free",
      "Fast refund",
      "Info Point",
      "Shuttle Service",
      "Free WiFi",
      "Tesla Supercharger",
      "Vico Lounge",
      "Water refill station",
      "Vico Junior",
      "Kinder Joy of Moving park",
      "YESMILANO CITY PASS"
    ],
    parking: "Official parking information lists 3,500 car parking spaces, 95 motorcycle spaces and 18 bicycle spaces.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 13,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue / Tax Refund for Tourists / Premier Tax Free / Tax Free VAT Refund Service for Tourists",
    taxFreeOfficeInfo: "Eligible non-EU residents can ask participating stores for a Tax-Free form; Global Blue forms can be brought with a passport to the Info Point in the main square for credit-card refund processing before customs validation.",
    status: "active",
    airportDistanceKm: 33,
    airportInfoText: "Milan Malpensa Airport • 33 km",
    airports: [{ code: "MXP", name: "Milan Malpensa Airport", distanceKm: 33 }],
    cityCenterDistanceKm: 60,
    cityCenterInfoText: "Milan City Centre • 60 km",
    cityCenterInfo: { name: "Milan City Centre", distanceKm: 60, recommendedRoute: "Use current official map directions." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Vicolungo%20The%20Style%20Outlets%2C%20Piazza%20Santa%20Caterina%2C%2028060%20Vicolungo%20NO%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Vicolungo%20The%20Style%20Outlets&address=Piazza%20Santa%20Caterina%2C%2028060%20Vicolungo%20NO%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Vicolungo%20The%20Style%20Outlets%2C%20Piazza%20Santa%20Caterina%2C%2028060%20Vicolungo%20NO%2C%20Italy"
  },
  {
    outletId: "castel-guelfo-the-style-outlets",
    outletName: "Castel Guelfo The Style Outlets",
    name: "Castel Guelfo The Style Outlets",
    slug: "castel-guelfo-the-style-outlets",
    countryId: "italy",
    cityId: "castel-guelfo-di-bologna",
    restaurants: [
      "ALICE PIZZA",
      "BILLY TACOS",
      "BOTEGA CAFFE CACAO",
      "FARINELLA BAKERY E COFFEE",
      "I LOVE POKE",
      "LA PIADINERIA",
      "LINDT",
      "ROADHOUSE MEATERY"
    ],
    officialWebsite: "https://castel-guelfo.thestyleoutlets.it/en",
    websiteUrl: "https://castel-guelfo.thestyleoutlets.it/en",
    address: "Via del Commercio 4/2, 40023 Castel Guelfo di Bologna BO, Italy",
    latitude: 44.4414,
    longitude: 11.6690,
    openingHours: "Daily 10:00 - 21:00",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "110 boutiques with over 200 brands",
    services: [
      "Tax free",
      "Info Point",
      "Shuttle Service",
      "Free WiFi",
      "Gift card",
      "Foodie Bag",
      "Water refill station",
      "Book Sharing",
      "Too Good To Go",
      "Clothing collection",
      "Playground"
    ],
    parking: "Official services page links parking as visitor information; no further official parking capacity details were verified from official outlet/operator sources.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 13,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official services list Tax free; no specific refund operator or outlet desk process was verified from official outlet/operator sources.",
    status: "active",
    airportDistanceKm: 35,
    airportInfoText: "Bologna Guglielmo Marconi Airport • 35 km",
    airports: [{ code: "BLQ", name: "Bologna Guglielmo Marconi Airport", distanceKm: 35 }],
    cityCenterDistanceKm: 28,
    cityCenterInfoText: "Bologna City Centre • 28 km",
    cityCenterInfo: { name: "Bologna City Centre", distanceKm: 28, recommendedRoute: "Use current official map directions." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Castel%20Guelfo%20The%20Style%20Outlets%2C%20Via%20del%20Commercio%204%2F2%2C%2040023%20Castel%20Guelfo%20di%20Bologna%20BO%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Castel%20Guelfo%20The%20Style%20Outlets&address=Via%20del%20Commercio%204%2F2%2C%2040023%20Castel%20Guelfo%20di%20Bologna%20BO%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Castel%20Guelfo%20The%20Style%20Outlets%2C%20Via%20del%20Commercio%204%2F2%2C%2040023%20Castel%20Guelfo%20di%20Bologna%20BO%2C%20Italy"
  } as any,
  {
    outletId: "puglia-village",
    name: "Puglia Village",
    slug: "puglia-village",
    aliases: ["Puglia Outlet", "Puglia Village Molfetta", "Molfetta Outlet", "Land of Fashion Puglia Village"],
    countryId: "italy",
    cityId: "molfetta",
    address: "Via dei Portuali 12, Zona Calderina, 70056 Molfetta BA, Italy",
    latitude: 41.2147,
    longitude: 16.5636,
    openingHours: "Monday to Sunday and holidays 10:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90 stores",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Info Point", "Restaurants & Cafes", "Land of Fashion Club", "Gift Card", "Tax Free", "EV Charging", "Services for Children", "Umbrella Hire", "Bag Storage"],
    restaurants: ["Bacio di Latte", "Bacio di Puglia", "Lindt", "Momi Poke", "Old Wild West", "WHAO"],
    parking: "Official Puglia Village information lists Info Point entrance at Parking A-C and parking areas A-B-C-D-E-F.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue Tax Free Refunds Kiosk / participating stores / EU customs validation",
    taxFreeOfficeInfo: "Official Puglia Village news lists a Global Blue instant Tax Free Refunds Kiosk in the Village Info Point. Eligible non-EU visitors should request tax-free forms in participating stores and validate export documents when leaving the EU.",
    cityCenterDistanceKm: 25,
    airportDistanceKm: 20,
    airports: [{ code: "BRI", name: "Bari Karol Wojtyla Airport", distanceKm: 20 }],
    cityCenterInfo: { name: "Bari City Centre", distanceKm: 25, recommendedRoute: "Use current official map directions to Via dei Portuali 12, Molfetta." },
    websiteUrl: "https://www.pugliaoutlet.it/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Puglia%20Village%2C%20Via%20dei%20Portuali%2012%2C%2070056%20Molfetta%20BA%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Puglia%20Village&address=Via%20dei%20Portuali%2012%2C%2070056%20Molfetta%20BA%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Puglia%20Village%2C%20Via%20dei%20Portuali%2012%2C%2070056%20Molfetta%20BA%2C%20Italy"
  } as any,
  {
    outletId: "sicilia-outlet-village",
    name: "Sicilia Outlet Village",
    slug: "sicilia-outlet-village",
    aliases: ["Sicily Outlet Village", "Sicilia Outlet Village Agira", "Dittaino Outlet"],
    countryId: "italy",
    cityId: "agira",
    address: "Autostrada A19 Palermo-Catania, Uscita Dittaino Outlet, 94011 Agira EN, Italy",
    latitude: 37.5637,
    longitude: 14.4666,
    openingHours: "Check official website for current opening hours",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Check official website for current store count",
    rating: 0,
    reviewCount: 0,
    services: ["Infopoint", "Children's Play Area", "Hands-free Shopping", "Free Wifi", "Tax Free Shopping", "Shuttle Bus Service", "Dog Friendly Services", "Gift Card", "Parking"],
    restaurants: ["Caffè Vergnano", "Fud Sud"],
    parking: "Official services copy references large parking at Sicilia Outlet Village; confirm current parking details on the official website before visiting.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Participating stores / EU customs validation",
    taxFreeOfficeInfo: "Official services list Tax Free Shopping; no specific refund operator or outlet desk process was verified from official outlet/operator sources.",
    cityCenterDistanceKm: 60,
    airportDistanceKm: 70,
    airports: [{ code: "CTA", name: "Catania-Fontanarossa Airport", distanceKm: 70 }],
    cityCenterInfo: { name: "Catania City Centre", distanceKm: 60, recommendedRoute: "Use current official map directions to the A19 Dittaino Outlet exit." },
    websiteUrl: "https://www.siciliaoutletvillage.com/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sicilia%20Outlet%20Village%2C%20Agira%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Sicilia%20Outlet%20Village&address=Agira%20EN%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Sicilia%20Outlet%20Village%2C%20Agira%2C%20Italy"
  } as any,
  {
    outletId: "scalo-milano-outlet-more",
    name: "Scalo Milano Outlet & More",
    slug: "scalo-milano-outlet-more",
    aliases: ["Scalo Milano", "Scalo Milano Outlet", "Scalo Milano Outlet and More", "Scalo Milano Locate Triulzi"],
    countryId: "italy",
    cityId: "locate-triulzi",
    address: "Via Milano 5, 20085 Locate di Triulzi MI, Italy",
    latitude: 45.3577,
    longitude: 9.2267,
    openingHours: "Monday - Friday 10:00 - 21:00; Saturday - Sunday 09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "180 boutiques",
    rating: 0,
    reviewCount: 0,
    services: ["Infopoint", "Free Parking", "Shuttle Bus", "Global Blue Tax Free", "Kids Area", "Amazon Locker", "The Concierge", "The Place Hospitality Lounge", "Free Wi-Fi"],
    restaurants: ["Doppio Malto", "La Piadineria", "Mi scusi", "Osteria Urbana - Vino e Cucina", "Roadhouse Restaurant", "Rossopomodoro"],
    parking: "Official services list free parking outdoors and in a multilevel indoor garage.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue kiosks / participating boutiques / EU customs validation",
    taxFreeOfficeInfo: "Official Scalo Milano services state non-EU residents can claim a tax refund from a minimum purchase of €70.01 and obtain instant refunds from Global Blue kiosks located at The Concierge and Info Point.",
    cityCenterDistanceKm: 15,
    airportDistanceKm: 18,
    airports: [{ code: "LIN", name: "Milan Linate Airport", distanceKm: 18 }, { code: "MXP", name: "Milan Malpensa Airport", distanceKm: 65 }],
    cityCenterInfo: { name: "Milan City Centre", distanceKm: 15, recommendedRoute: "Use current official map directions or Locate Triulzi railway station near Gate 1." },
    websiteUrl: "https://www.scalomilano.it/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Scalo%20Milano%20Outlet%20%26%20More%2C%20Via%20Milano%205%2C%20Locate%20di%20Triulzi%20MI%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Scalo%20Milano%20Outlet%20%26%20More&address=Via%20Milano%205%2C%20Locate%20di%20Triulzi%20MI%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Scalo%20Milano%20Outlet%20%26%20More%2C%20Via%20Milano%205%2C%20Locate%20di%20Triulzi%20MI%2C%20Italy"
  } as any,
  {
    outletId: "torino-outlet-village",
    name: "Torino Outlet Village",
    slug: "torino-outlet-village",
    aliases: ["Turin Outlet Village", "Torino Outlet Village Settimo Torinese", "Settimo Torinese Outlet"],
    countryId: "italy",
    cityId: "settimo-torinese",
    address: "Via Torino 160-162, 10036 Settimo Torinese TO, Italy",
    latitude: 45.1238,
    longitude: 7.7770,
    openingHours: "Check official website for current opening hours",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Check official website for current store count",
    rating: 0,
    reviewCount: 0,
    services: ["Infopoint - Tourist Office", "Kids Area", "Free Parking", "Transfer - Chauffeur-driven Rental", "Electric Car Charging Stations", "Hands-free Shopping", "Free Wifi", "Tax-Free Shopping", "Dog Friendly Services", "Gift Card"],
    restaurants: ["Caffè e Bollicine", "La Piadineria", "Re Nero Caffè"],
    parking: "Official visit information lists ample free parking for visitors.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Participating stores / EU customs validation",
    taxFreeOfficeInfo: "Official services list Tax-Free Shopping; no specific refund operator or outlet desk process was verified from official outlet/operator sources.",
    cityCenterDistanceKm: 12,
    airportDistanceKm: 15,
    airports: [{ code: "TRN", name: "Turin Airport", distanceKm: 15 }],
    cityCenterInfo: { name: "Turin City Centre", distanceKm: 12, recommendedRoute: "Use current official map directions to Via Torino 160-162, Settimo Torinese." },
    websiteUrl: "https://www.torinooutletvillage.com/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Torino%20Outlet%20Village%2C%20Via%20Torino%20160-162%2C%20Settimo%20Torinese%20TO%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Torino%20Outlet%20Village&address=Via%20Torino%20160-162%2C%20Settimo%20Torinese%20TO%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Torino%20Outlet%20Village%2C%20Via%20Torino%20160-162%2C%20Settimo%20Torinese%20TO%2C%20Italy"
  } as any,
  {
    outletId: "mondovicino-outlet-village",
    name: "Mondovicino Outlet Village",
    slug: "mondovicino-outlet-village",
    aliases: ["Mondovicino", "Mondovicino Outlet", "Mondovì Outlet Village", "Mondovi Outlet Village"],
    countryId: "italy",
    cityId: "mondovi",
    address: "Piazza G. Jemina 47, 12084 Mondovì CN, Italy",
    latitude: 44.3995,
    longitude: 7.8157,
    openingHours: "Monday - Sunday 10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Check official website for current store count",
    rating: 0,
    reviewCount: 0,
    services: ["Tax Free Shopping", "Equipped Camper Area", "Kids Play Area", "Minigolf", "Block Busters", "Free Time"],
    restaurants: ["Caffè Bistrot La Scuderia", "Caffetteria Le Fontane", "I Partenopei CAFE’ – RESTAURANT", "Love IT Pizza", "Sapori della Regione"],
    parking: "Official services list an equipped camper area; confirm current visitor parking details on the official website before visiting.",
    taxFreeAvailable: true,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "International tax-free partners / participating stores / EU customs validation",
    taxFreeOfficeInfo: "Official Mondovicino tax-free information states extra-EU citizens can request a tax-free form in store for single receipts of at least €70.01; no specific outlet desk location was verified from official outlet/operator sources.",
    cityCenterDistanceKm: 4,
    airportDistanceKm: 35,
    airports: [{ code: "CUF", name: "Cuneo International Airport", distanceKm: 35 }, { code: "TRN", name: "Turin Airport", distanceKm: 115 }],
    cityCenterInfo: { name: "Mondovì City Centre", distanceKm: 4, recommendedRoute: "Use current official map directions to Mondovicino Outlet Village." },
    websiteUrl: "https://mondovicino.it/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mondovicino%20Outlet%20Village%2C%20Mondov%C3%AC%20CN%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Mondovicino%20Outlet%20Village&address=Mondov%C3%AC%20CN%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Mondovicino%20Outlet%20Village%2C%20Mondov%C3%AC%20CN%2C%20Italy"
  } as any,
  {
    outletId: "brugnato-5terre-outlet-village",
    name: "Brugnato 5Terre Outlet Village",
    slug: "brugnato-5terre-outlet-village",
    aliases: ["Brugnato 5Terre Outlet Village", "Brugnato 5 Terre Outlet Village", "5Terre Outlet Village", "Brugnato Outlet"],
    countryId: "italy",
    cityId: "brugnato",
    address: "Via Nuova Antica Romana snc, 19020 Brugnato SP, Italy",
    latitude: 44.2365,
    longitude: 9.7287,
    openingHours: "Mon-Sun 10:00 - 21:00; seasonal Summer Nights may vary",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 70 brands",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Info Point", "Gift Card", "Shuttle / Transport Info", "VIP Club", "App"],
    restaurants: [],
    parking: "Official visit pages include parking/visitor information; confirm current parking details on the official website before visiting.",
    taxFreeAvailable: false,
    vatRate: 22,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "No official outlet/operator tax-free desk or specific tax-free operator information was verified for this outlet. Eligible visitors should confirm directly with individual stores before purchase.",
    cityCenterDistanceKm: 1,
    airportDistanceKm: 85,
    airports: [{ code: "PSA", name: "Pisa International Airport", distanceKm: 85 }, { code: "GOA", name: "Genoa Cristoforo Colombo Airport", distanceKm: 90 }],
    cityCenterInfo: { name: "Brugnato Town Centre", distanceKm: 1, recommendedRoute: "Use current official map directions to Via Nuova Antica Romana." },
    nearby: [],
    websiteUrl: "https://www.brugnato5terreoutletvillage.it/it/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Brugnato%205Terre%20Outlet%20Village%2C%20Via%20Nuova%20Antica%20Romana%2C%20Brugnato%2C%20Italy",
    appleMapsUrl: "http://maps.apple.com/?q=Brugnato%205Terre%20Outlet%20Village&address=Via%20Nuova%20Antica%20Romana%2C%20Brugnato%2C%20Italy",
    yandexMapsUrl: "https://yandex.com/maps/?text=Brugnato%205Terre%20Outlet%20Village%2C%20Via%20Nuova%20Antica%20Romana%2C%20Brugnato%2C%20Italy"
  } as any
];
