export const japanOutlets = [
  {
    outletId: "gotemba-premium-outlets",
    outletName: "Gotemba Premium Outlets",
    name: "Gotemba Premium Outlets",
    slug: "gotemba-premium-outlets",
    countryId: "japan",
    cityId: "gotemba",
    address: "1312 Fukasawa, Gotemba-shi, Shizuoka 412-0023, Japan",
    latitude: 35.3067588,
    longitude: 138.9620686,
    openingHours: "Mar-Nov 10:00 - 20:00; Dec-Feb 10:00 - 19:00. Closed once yearly; next scheduled closure February 25, 2027. Seasonal and special hours may vary.",
    heroImage: "",
    galleryImages: [],
    storesCountText: "290 outlet stores",
    rating: 0,
    reviewCount: 0,
    services: ["Information Center", "Welcome Center", "Tax-Free Shopping", "Free Wi-Fi", "ATM", "Currency Exchange", "Lockers", "Prayer Room", "Telephone Interpreting", "Free Shuttle Bus", "Taxi", "Nursing Room", "Baby Changing", "First Aid / AED", "Stroller Rental", "Wheelchair Rental", "Barrier-Free Access", "Delivery Service", "Parking", "EV Charging", "Pet-Friendly Areas", "Smoking Areas"],
    restaurants: [],
    parking: "All Gotemba Premium Outlets parking areas are free. Overflow/off-site parking may be used on busy days.",
    taxFreeAvailable: true,
    cityCenterDistanceKm: 3,
    airportDistanceKm: 98,
    airports: [
      { code: "HND", name: "Haneda Airport", distanceKm: 98 },
      { code: "NRT", name: "Narita International Airport", distanceKm: 165 },
    ],
    cityCenterInfo: { name: "JR Gotemba Station", distanceKm: 3 },
    nearby: [],
    officialWebsite: "https://www.premiumoutlets.co.jp/en/gotemba/",
    websiteUrl: "https://www.premiumoutlets.co.jp/en/gotemba/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.3067588,138.9620686",
    appleMapsUrl: "https://maps.apple.com/?ll=35.3067588,138.9620686&q=Gotemba%20Premium%20Outlets",
    yandexMapsUrl: "https://yandex.com/maps/?ll=138.9620686,35.3067588&z=16&text=Gotemba%20Premium%20Outlets",
    status: "active",
  },
];
