export const kuwaitOutlets = [
  {
    outletId: "al-khiran-hybrid-outlet-mall",
    outletName: "Al Khiran Hybrid Outlet Mall",
    name: "Al Khiran Hybrid Outlet Mall",
    slug: "al-khiran-hybrid-outlet-mall",
    countryId: "kuwait",
    cityId: "al-khiran",
    address: "Al Khiran Hybrid Outlet Mall, Arabian Gulf Road, Al Khiran, Al Ahmadi Governorate, Kuwait",
    latitude: 28.6618,
    longitude: 48.3689,
    openingHours: "Tenant hours commonly published for the mall are Sun-Wed 10:00 - 22:00 and Thu-Sat 10:00 - 23:00; confirm mall-wide and holiday hours before travel.",
    heroImage: "",
    galleryImages: [],
    storesCountText: "284 retail stores",
    rating: 0,
    reviewCount: 0,
    services: [
      "Customer Service",
      "Dining",
      "Parking",
      "Waterfront Promenade",
    ],
    restaurants: [],
    parking: "Tamdeen Group lists 4,884 parking spaces for Al Khiran.",
    taxFreeAvailable: false,
    cityCenterDistanceKm: 98,
    airportDistanceKm: 86,
    airports: [{ code: "KWI", name: "Kuwait International Airport", distanceKm: 86 }],
    cityCenterInfo: { name: "Kuwait City / Kuwait Towers", distanceKm: 98 },
    nearby: [],
    officialWebsite: "https://www.tamdeen.com/portfolio/al-khiran",
    websiteUrl: "https://www.tamdeen.com/portfolio/al-khiran",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=28.6618,48.3689",
    appleMapsUrl: "https://maps.apple.com/?ll=28.6618,48.3689&q=Al%20Khiran%20Hybrid%20Outlet%20Mall",
    yandexMapsUrl: "https://yandex.com/maps/?ll=48.3689,28.6618&z=16&text=Al%20Khiran%20Hybrid%20Outlet%20Mall",
    status: "active"
  }
];
