export const netherlandsOutlets = [
  {
    outletId: "designer-outlet-roermond",
    name: "Designer Outlet Roermond",
    slug: "designer-outlet-roermond",
    countryId: "netherlands",
    cityId: "amsterdam",
    address: "Stadsweide 2, 6041 TD Roermond, Netherlands",
    latitude: 51.1994,
    longitude: 5.9883,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat-Sun 09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 200 designer brands",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Chez Margot",
      "Cinnamood",
      "Crêpes",
      "Döner Kebab",
      "Dunkin'",
      "Frankie's Churros",
      "Frites Boutique",
      "Go To Italiano",
      "Käfer",
      "Kamps",
      "Kamps To Go",
      "La Place",
      "La Place Cuisine",
      "La Place Express",
      "Le Pain Quotidien",
      "Lindt",
      "Macarons",
      "MADAQ",
      "McDonald's",
      "MOOD to go",
      "Oakberry",
      "Pizzeria Positano On Wheels",
      "Pommes Frites",
      "Starbucks",
      "Starbucks To Go",
      "Sweet Avenue",
      "The Burger Federation",
      "Wagamama",
      "Wurzt",
      "YoYo Fresh Tea"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "50.00 EUR",
    taxFreeOperator: "Global Blue / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €50 in the same store on the same day. Guest Services, next to Polo Ralph Lauren, can assist with refund options before customs validation when leaving the EU.",
    cityCenterDistanceKm: 180,
    airportDistanceKm: 60,
    airports: [
      {
        code: "EIN",
        name: "Eindhoven Airport",
        distanceKm: 60
      },
      {
        code: "DUS",
        name: "Düsseldorf Airport",
        distanceKm: 65
      },
      {
        code: "AMS",
        name: "Amsterdam Schiphol Airport",
        distanceKm: 180
      }
    ],
    cityCenterInfo: {
      name: "Amsterdam City Centre",
      distanceKm: 180,
      recommendedRoute: "Train to Roermond, then walk 10-15 minutes"
    },
    nearby: [
      {
        name: "Roermond City Centre",
        distanceKm: 1
      },
      {
        name: "Düsseldorf",
        distanceKm: 65
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/nl/designer-outlet-roermond/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Roermond%2C+Stadsweide+2%2C+6041+TD+Roermond%2C+Netherlands",
    appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Roermond&address=Stadsweide+2%2C+6041+TD+Roermond%2C+Netherlands",
    yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Roermond%2C%20Stadsweide%202%2C%206041%20TD%20Roermond%2C%20Netherlands"
  },
  {
    outletId: "designer-outlet-roosendaal",
    name: "Designer Outlet Roosendaal",
    slug: "designer-outlet-roosendaal",
    countryId: "netherlands",
    cityId: "rotterdam",
    address: "Rosada 70, 4703 TB Roosendaal, Netherlands",
    latitude: 51.5365,
    longitude: 4.4777,
    openingHours: "Mon-Sun 10:00 - 20:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 100 brands",
    rating: 4.4,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Bonton",
      "Casa del Caffè",
      "Daan's Churros",
      "Dunkin'",
      "Frites Atelier",
      "La Place",
      "Lindt",
      "Per Tutti"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "50.00 EUR",
    taxFreeOperator: "Global Blue / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a tax refund form in participating stores when spending at least €50 in the same store on the same day. Guest Services can assist with refund options before customs validation when leaving the EU.",
    cityCenterDistanceKm: 65,
    airportDistanceKm: 65,
    airports: [
      {
        code: "RTM",
        name: "Rotterdam The Hague Airport",
        distanceKm: 65
      },
      {
        code: "AMS",
        name: "Amsterdam Schiphol Airport",
        distanceKm: 115
      },
      {
        code: "BRU",
        name: "Brussels Airport",
        distanceKm: 105
      }
    ],
    cityCenterInfo: {
      name: "Rotterdam City Centre",
      distanceKm: 65,
      recommendedRoute: "Train to Roosendaal, then local bus or taxi"
    },
    nearby: [
      {
        name: "Roosendaal City Centre",
        distanceKm: 3
      },
      {
        name: "Antwerp",
        distanceKm: 45
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/nl/designer-outlet-roosendaal/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Designer+Outlet+Roosendaal%2C+Rosada+70%2C+4703+TB+Roosendaal%2C+Netherlands",
    appleMapsUrl: "http://maps.apple.com/?q=Designer+Outlet+Roosendaal&address=Rosada+70%2C+4703+TB+Roosendaal%2C+Netherlands",
    yandexMapsUrl: "https://yandex.com/maps/?text=Designer%20Outlet%20Roosendaal%2C%20Rosada%2070%2C%204703%20TB%20Roosendaal%2C%20Netherlands"
  },
  {
    outletId: "amsterdam-the-style-outlets",
    outletName: "Amsterdam The Style Outlets",
    name: "Amsterdam The Style Outlets",
    slug: "amsterdam-the-style-outlets",
    countryId: "netherlands",
    cityId: "amsterdam",
    restaurants: [
      "COFFEE FELLOWS",
      "POMMES FRITES",
      "SELVA ORO",
      "STARBUCKS",
      "THE BURGER FEDERATION"
    ],
    officialWebsite: "https://amsterdam.thestyleoutlets.nl/en",
    websiteUrl: "https://amsterdam.thestyleoutlets.nl/en",
    address: "SugarCity Ring 1, 1165 PB Halfweg, Netherlands",
    latitude: 52.3842,
    longitude: 4.7511,
    openingHours: "Mon-Thu 10:00 - 18:00; Fri-Sun 10:00 - 20:00",
    storesCountText: "Over 80 brands",
    services: [
      "Tax refund",
      "Information point",
      "Gift card",
      "Free WiFi",
      "Electric car charging points",
      "Pet friendly area",
      "Borrow an umbrella",
      "Borrow a phone charger",
      "Luggage storage",
      "Borrow a wheelchair",
      "Taxi Stand",
      "ATM",
      "DHL ServicePoint"
    ],
    parking: "Official parking information lists more than 1,470 covered parking spaces below the centre, including 40 electric charging spots, plus another 750 outdoor spaces next to it.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 13,
    minimumTaxFreeSpend: "50 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official tourism information says tax refunds are available at the infopoint; no specific refund operator was verified from official outlet/operator sources.",
    status: "active",
    airportDistanceKm: 17,
    airportInfoText: "Amsterdam Schiphol Airport • 17 km",
    airports: [{ code: "AMS", name: "Amsterdam Schiphol Airport", distanceKm: 17 }],
    cityCenterDistanceKm: 17,
    cityCenterInfoText: "Amsterdam City Centre • 17 km",
    cityCenterInfo: { name: "Amsterdam City Centre", distanceKm: 17, recommendedRoute: "Use current official map directions." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Amsterdam%20The%20Style%20Outlets%2C%20SugarCity%20Ring%201%2C%201165%20PB%20Halfweg%2C%20Netherlands",
    appleMapsUrl: "http://maps.apple.com/?q=Amsterdam%20The%20Style%20Outlets&address=SugarCity%20Ring%201%2C%201165%20PB%20Halfweg%2C%20Netherlands",
    yandexMapsUrl: "https://yandex.com/maps/?text=Amsterdam%20The%20Style%20Outlets%2C%20SugarCity%20Ring%201%2C%201165%20PB%20Halfweg%2C%20Netherlands"
  },
  {
    outletId: "batavia-stad-fashion-outlet",
    outletName: "Batavia Stad Fashion Outlet",
    name: "Batavia Stad Fashion Outlet",
    slug: "batavia-stad-fashion-outlet",
    countryId: "netherlands",
    cityId: "lelystad",
    restaurants: [
      "Âme Fashion Café",
      "Coffeecompany",
      "De Ruyter Vis",
      "Dunkin' Donuts",
      "Dutch Originals",
      "Ekmekci",
      "La Place",
      "McDonald's",
      "Salsa Shop",
      "Subway",
      "Twelve12"
    ],
    officialWebsite: "https://www.bataviastad.nl/en",
    websiteUrl: "https://www.bataviastad.nl/en",
    address: "Bataviaplein 60, 8242 PN Lelystad, Netherlands",
    latitude: 52.5226,
    longitude: 5.4397,
    openingHours: "Mon-Fri 10:00 - 18:00; Sat-Sun 10:00 - 20:00; special opening hours may apply",
    storesCountText: "250+ brands",
    services: [
      "Tax Refund",
      "Information Centre",
      "Parking",
      "WiFi",
      "Luggage",
      "Shopping Guide",
      "Charging point cars",
      "Payment options",
      "VIP Room",
      "Gift card",
      "Wheelchair-friendly",
      "Dogs",
      "Groups",
      "Powerbank",
      "Flying Blue"
    ],
    parking: "Official tourism information says parking is affordable and there are electric charging stations in the large car parks.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 13,
    minimumTaxFreeSpend: "50 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official amenities list Tax Refund, but no specific refund operator or outlet desk process was verified from official outlet/operator sources.",
    status: "active",
    airportDistanceKm: 70,
    airportInfoText: "Amsterdam Schiphol Airport • 70 km",
    airports: [{ code: "AMS", name: "Amsterdam Schiphol Airport", distanceKm: 70 }],
    cityCenterDistanceKm: 60,
    cityCenterInfoText: "Amsterdam City Centre • 60 km",
    cityCenterInfo: { name: "Amsterdam City Centre", distanceKm: 60, recommendedRoute: "Use current official map directions." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Batavia%20Stad%20Fashion%20Outlet%2C%20Bataviaplein%2060%2C%208242%20PN%20Lelystad%2C%20Netherlands",
    appleMapsUrl: "http://maps.apple.com/?q=Batavia%20Stad%20Fashion%20Outlet&address=Bataviaplein%2060%2C%208242%20PN%20Lelystad%2C%20Netherlands",
    yandexMapsUrl: "https://yandex.com/maps/?text=Batavia%20Stad%20Fashion%20Outlet%2C%20Bataviaplein%2060%2C%208242%20PN%20Lelystad%2C%20Netherlands"
  }

];
