import type { Outlet } from "../../types/outlet";

export const southKoreaOutlets: Outlet[] = [
  {
    outletId: "yeoju-premium-outlets",
    name: "Yeoju Premium Outlets",
    slug: "yeoju-premium-outlets",
    countryId: "south-korea",
    cityId: "yeoju",
    address: "360, Myeongpum-ro, Yeoju-si, Gyeonggi-do, Republic of Korea",
    latitude: "",
    longitude: "",
    openingHours: "May-Oct: daily 10:30 - 21:00; Nov-Apr: Mon-Thu 10:30 - 20:30, Fri-Sun and public holidays 10:30 - 21:00. Restaurants daily 11:00 - 21:00; restaurant last orders close 30 minutes before closing time. Some stores close 30 minutes early.",
    heroImage: "",
    galleryImages: [],
    storesCountText: "",
    rating: 0,
    reviewCount: 0,
    services: [
      "Information Center",
      "Stroller Rental",
      "Wheelchair Rental",
      "Tax-Free Shopping",
      "Payment Methods",
      "Free Circular Bus",
      "Shinsegae Gift Certificates",
      "ATM",
      "Free Wi-Fi",
      "Lockers",
      "Clothing Alteration Service",
      "Mini Train",
      "Children’s Playground",
      "Merry-go-round",
      "Bounce Spin",
      "emart24",
      "Nursing Room",
      "Electric Car Charging Station",
      "Tesla Electric Car Charging Station",
      "Premium Lounge",
      "Premium Parking Zone",
      "Art Museum Ryeo",
      "Mobile Phone Charging",
      "Lost and Found",
      "Pet-Friendly Areas",
    ],
    restaurants: [],
    taxFreeAvailable: true,
    vatRate: 10,
    minimumTaxFreeSpend: "KRW 15,000",
    taxFreeOfficeInfo: "Tax Refund is available only at participating stores marked GLOBAL TAX FREE, GLOBAL BLUE, NICE TAX FREE, or another eligible Tax Refund operator. On-site kiosks are located at the East Bus Stop and West Information Center. Minimum purchase: KRW 15,000. Downtown refund limit: KRW 6,000,000; immediate refund limit per purchase: KRW 1,000,000; total immediate refund limit during the stay: KRW 5,000,000. Eligibility, documentation, customs validation and export-within-three-months requirements apply.",
    websiteUrl: "https://premiumoutlets.co.kr/rpage/en/main/index/01",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Yeoju%20Premium%20Outlets%2C%20360%2C%20Myeongpum-ro%2C%20Yeoju-si%2C%20Gyeonggi-do%2C%20Republic%20of%20Korea",
    appleMapsUrl: "https://maps.apple.com/?q=Yeoju%20Premium%20Outlets&address=360%2C%20Myeongpum-ro%2C%20Yeoju-si%2C%20Gyeonggi-do%2C%20Republic%20of%20Korea",
    yandexMapsUrl: "https://yandex.com/maps/?text=Yeoju%20Premium%20Outlets%2C%20360%2C%20Myeongpum-ro%2C%20Yeoju-si%2C%20Gyeonggi-do%2C%20Republic%20of%20Korea",
    status: "active",
  },
];
