export const spainOutlets = [
  {
    outletId: "las-rozas-village",
    name: "Las Rozas Village",
    slug: "las-rozas-village",
    countryId: "spain",
    cityId: "madrid",
    address: "Calle Juan Ramón Jiménez 3, 28232 Las Rozas, Madrid, Spain",
    latitude: 40.5037,
    longitude: -3.8968,
    openingHours: "10:00 - 22:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 100 boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Hands-free Shopping",
      "Personal Shopping",
      "EV Charging",
      "Baby-changing Facilities"
    ],
    restaurants: [
      "Cristina Oria",
      "Joselito Kiosk",
      "Joselito's Restaurant",
      "Lindt",
      "Mentidero Sal y Brasas",
      "Mistura"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "0.01 EUR",
    taxFreeOperator: "Global Blue / Planet",
    taxFreeOfficeInfo: "Eligible non-EU visitors can recover applicable VAT on purchases, up to 21%; ask Concierge for tax-free shopping assistance and complete EU customs validation when leaving the EU.",
    cityCenterDistanceKm: 25,
    airportDistanceKm: 30,
    airports: [
      {
        code: "MAD",
        name: "Madrid-Barajas Airport",
        distanceKm: 30
      }
    ],
    cityCenterInfo: {
      name: "Madrid City Centre",
      distanceKm: 25,
      recommendedRoute: "Bus, taxi or car"
    },
    nearby: [
      {
        name: "Las Rozas",
        distanceKm: 2
      },
      {
        name: "Madrid",
        distanceKm: 25
      }
    ],
    websiteUrl: "https://www.thebicestercollection.com/las-rozas-village/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=40.5037,-3.8968",
    appleMapsUrl: "http://maps.apple.com/?ll=40.5037,-3.8968&q=Las%20Rozas%20Village",
    yandexMapsUrl: "https://yandex.com/maps/?ll=-3.8968,40.5037&z=16&text=Las%20Rozas%20Village"
  },
  {
    outletId: "designer-outlet-malaga",
    name: "McArthurGlen Designer Outlet Málaga",
    slug: "designer-outlet-malaga",
    countryId: "spain",
    cityId: "malaga",
    address: "Calle Alfonso Ponce de León 6, 29004 Málaga, Spain",
    latitude: 36.6738,
    longitude: -4.4899,
    openingHours: "10:00 - 22:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 100 brands",
    rating: 4.5,
    reviewCount: 0,
    services: [
      "Parking",
      "Tax Free",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Ben & Jerry's",
      "Five Guys",
      "La Pecera",
      "Sabor a España",
      "Santo Cielo",
      "Starbucks"
    ],
    parking: "Official outlet services list visitor parking; check the official outlet website for current parking details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "0.01 EUR",
    taxFreeOperator: "Planet / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request tax-free shopping information at Guest Services; Planet lists a refund location at McArthurGlen, Alfonso Ponce de León 6, with EU customs validation required when leaving the EU.",
    cityCenterDistanceKm: 15,
    airportDistanceKm: 3,
    airports: [
      {
        code: "AGP",
        name: "Málaga-Costa del Sol Airport",
        distanceKm: 3
      }
    ],
    cityCenterInfo: {
      name: "Málaga City Centre",
      distanceKm: 15,
      recommendedRoute: "Train, bus or taxi"
    },
    nearby: [
      {
        name: "Málaga Airport",
        distanceKm: 3
      },
      {
        name: "Torremolinos",
        distanceKm: 6
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/es/designer-outlet-malaga/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=36.6738,-4.4899",
    appleMapsUrl: "http://maps.apple.com/?ll=36.6738,-4.4899&q=McArthurGlen%20Designer%20Outlet%20Malaga",
    yandexMapsUrl: "https://yandex.com/maps/?ll=-4.4899,36.6738&z=16&text=McArthurGlen%20Designer%20Outlet%20Malaga"
  },
  {
    outletId: "viladecans-the-style-outlets",
    name: "Viladecans The Style Outlets",
    slug: "viladecans-the-style-outlets",
    countryId: "spain",
    cityId: "viladecans",
    address: "Ctra. de la Vila, 90, 08840 Viladecans, Barcelona, Spain",
    latitude: 41.3189,
    longitude: 2.0357,
    openingHours: "10:00 - 22:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "All stores directory verified on the official website",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Tax Free", "Restaurants & Cafes", "Pet Friendly", "Free Wi-Fi", "Personal Shopper", "Luggage Lockers", "Transport Info"],
    restaurants: ["BURGER KING", "CASA CARMEN", "CHALITO", "FIVE GUYS", "GROSSO NAPOLETANO", "HARRY", "LLAOLLAO", "STARBUCKS", "SUSHISOM", "UDON"],
    parking: "Official address is Ctra. de la Vila, 90, Viladecans; confirm current parking details on the official website before visiting.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "70.01 EUR",
    taxFreeOperator: "Global Blue, Tax Refund for Tourists, Premier Tax Free, or Tax Free VAT Refund Service for Tourists / EU customs validation",
    taxFreeOfficeInfo: "Eligible non-EU visitors can request a Tax Free form at participating store cash desks for purchases of 70.01 EUR or more in a single receipt and validate the form at customs when leaving the EU.",
    cityCenterDistanceKm: 15,
    airportDistanceKm: 6,
    airports: [{ code: "BCN", name: "Barcelona-El Prat Airport", distanceKm: 6 }],
    cityCenterInfo: { name: "Barcelona City Centre", distanceKm: 15, recommendedRoute: "Use RENFE commuter rail, car, taxi, or bus toward Viladecans." },
    websiteUrl: "https://viladecans.thestyleoutlets.es/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Viladecans+The+Style+Outlets",
    appleMapsUrl: "http://maps.apple.com/?q=Viladecans%20The%20Style%20Outlets",
    yandexMapsUrl: "https://yandex.com/maps/?text=Viladecans%20The%20Style%20Outlets"
  } as any,
  {
    outletId: "la-roca-village",
    outletName: "La Roca Village",
    name: "La Roca Village",
    slug: "la-roca-village",
    countryId: "spain",
    cityId: "barcelona",
    restaurants: [
      "Andreu",
      "Atmósferas Mordisco",
      "Corso Iluzione",
      "Cèntric",
      "Dino",
      "Farggi 1957"
    ],
    officialWebsite: "https://www.thebicestercollection.com/la-roca-village/en/",
    websiteUrl: "https://www.thebicestercollection.com/la-roca-village/en/",
    address: "La Roca Village s/n, Santa Agnès de Malanyanes, 08430 Barcelona, Spain",
    latitude: 41.6105,
    longitude: 2.3436,
    openingHours: "Mon-Sun 10:00 - 22:00",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "More than 150 boutiques",
    services: [
      "Tax-Free Shopping",
      "Personal Shopping",
      "Reserved Parking",
      "Hands-Free Shopping",
      "Concierge Services",
      "Digital map",
      "Gift Card",
      "Shopping Express"
    ],
    parking: "Official visit information lists free parking and electric car charging points; reserved parking can be requested through Concierge Services.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 15.7,
    minimumTaxFreeSpend: "Not verified",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official Village pages advertise Tax-Free Shopping and instant tax refunds/currency exchange, but a minimum spend and named refund operator were not verified from official outlet/operator sources.",
    status: "active",
    airportDistanceKm: 40,
    airportInfoText: "Barcelona-El Prat Airport • 40 km",
    airports: [{ code: "BCN", name: "Barcelona-El Prat Airport", distanceKm: 40 }],
    cityCenterDistanceKm: 40,
    cityCenterInfoText: "Barcelona City Centre • 40 km",
    cityCenterInfo: { name: "Barcelona City Centre", distanceKm: 40, recommendedRoute: "Use Shopping Express from Estació del Nord or current official map directions." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=La%20Roca%20Village%2C%20Santa%20Agn%C3%A8s%20de%20Malanyanes%2C%2008430%20Barcelona%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=La%20Roca%20Village&address=Santa%20Agn%C3%A8s%20de%20Malanyanes%2C%2008430%20Barcelona%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=La%20Roca%20Village%2C%20Santa%20Agn%C3%A8s%20de%20Malanyanes%2C%2008430%20Barcelona%2C%20Spain"
  }

,
  {
    outletId: "mallorca-fashion-outlet",
    outletName: "Mallorca Fashion Outlet",
    name: "Mallorca Fashion Outlet",
    slug: "mallorca-fashion-outlet",
    countryId: "spain",
    cityId: "marratxi",
    restaurants: [
      "Amorino",
      "Block House",
      "Coffee Fellows",
      "Diablito",
      "Don't Cry For Me",
      "Dumpling Hub",
      "Enrique Tomás",
      "L'Osteria",
      "Foster's Hollywood",
      "Ginos",
      "Häagen Dazs",
      "Lindt",
      "McDonald's",
      "Skalop",
      "Starbucks"
    ],
    officialWebsite: "https://www.mallorcafashionoutlet.com/en",
    websiteUrl: "https://www.mallorcafashionoutlet.com/en",
    address: "Autovía Palma-Inca, Km 7.1, salida 8, 07141 Marratxí, Balearic Islands, Spain",
    latitude: 39.6215,
    longitude: 2.7266,
    openingHours: "Mon-Sun 10:00 - 22:00; special days may vary",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "Official current brand directory available",
    services: [
      "Tax Free Shopping",
      "Free Parking",
      "Train Station",
      "Virtual Shopping",
      "Free Wi-Fi",
      "Children's Area",
      "Pet Friendly",
      "Take Away",
      "Bike Lockers",
      "Rest Zone"
    ],
    parking: "Official services list free parking at the centre.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not officially verified",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official centre services list Tax Free Shopping; confirm participating stores, refund provider, minimum spend, and customs process at the centre.",
    aliases: ["Mallorca Fashion Outlet", "MFO", "Mallorca outlet"],
    status: "active",
    airportDistanceKm: 15,
    airportInfoText: "Palma de Mallorca Airport • 15 km",
    airports: [{ code: "PMI", name: "Palma de Mallorca Airport", distanceKm: 15 }],
    cityCenterDistanceKm: 10,
    cityCenterInfoText: "Palma City Centre • 10 km",
    cityCenterInfo: { name: "Palma City Centre", distanceKm: 10, recommendedRoute: "Use current official map directions to Autovía Palma-Inca, Km 7.1, salida 8." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mallorca%20Fashion%20Outlet%2C%20Autov%C3%ADa%20Palma-Inca%2C%20Km%207.1%2C%2007141%20Marratx%C3%AD%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=Mallorca%20Fashion%20Outlet&address=Autov%C3%ADa%20Palma-Inca%2C%20Km%207.1%2C%2007141%20Marratx%C3%AD%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=Mallorca%20Fashion%20Outlet%2C%20Autov%C3%ADa%20Palma-Inca%2C%20Km%207.1%2C%2007141%20Marratx%C3%AD%2C%20Spain"
  } as any,
  {
    outletId: "sevilla-fashion-outlet",
    outletName: "Sevilla Fashion Outlet",
    name: "Sevilla Fashion Outlet",
    slug: "sevilla-fashion-outlet",
    countryId: "spain",
    cityId: "seville",
    restaurants: [
      "100 Montaditos",
      "Five Guys",
      "Mito",
      "Miro Tapas",
      "Pinsere",
      "Santa Gloria",
      "Starbucks"
    ],
    officialWebsite: "https://www.sevillafashionoutlet.com/en",
    websiteUrl: "https://www.sevillafashionoutlet.com/en",
    address: "Calle Finca los Espartales, A-4, Km 531, 41300 San José de la Rinconada, Seville, Spain",
    latitude: 37.4279,
    longitude: -5.9219,
    openingHours: "Mon-Sun 10:00 - 22:00; special days may vary",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "Official current brand directory available; operator reports 100+ brands",
    services: [
      "Tax Free Shopping",
      "Free Parking",
      "Information",
      "Free Wi-Fi",
      "ATM Service",
      "Wheelchairs",
      "Rest Zone",
      "Lost & Found",
      "First Aid",
      "Pets",
      "Lactation",
      "Mobile Phone Chargers",
      "Electric Chargers",
      "Cloakroom"
    ],
    parking: "Official amenities list free parking at the centre.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not officially verified",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official centre pages list Tax Free Shopping and a non-resident VIP Day Pass; confirm participating stores, refund provider, minimum spend, and customs process at the Information Point.",
    aliases: ["Sevilla Fashion Outlet", "Seville Fashion Outlet"],
    status: "active",
    airportDistanceKm: 5,
    airportInfoText: "Seville Airport • 5 km",
    airports: [{ code: "SVQ", name: "Seville Airport", distanceKm: 5 }],
    cityCenterDistanceKm: 15,
    cityCenterInfoText: "Seville City Centre • 15 km",
    cityCenterInfo: { name: "Seville City Centre", distanceKm: 15, recommendedRoute: "Use current official map directions to Calle Finca los Espartales." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sevilla%20Fashion%20Outlet%2C%20Calle%20Finca%20los%20Espartales%2C%20San%20Jos%C3%A9%20de%20la%20Rinconada%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=Sevilla%20Fashion%20Outlet&address=Calle%20Finca%20los%20Espartales%2C%20San%20Jos%C3%A9%20de%20la%20Rinconada%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=Sevilla%20Fashion%20Outlet%2C%20Calle%20Finca%20los%20Espartales%2C%20San%20Jos%C3%A9%20de%20la%20Rinconada%2C%20Spain"
  } as any,
  {
    outletId: "getafe-the-style-outlets",
    outletName: "Getafe The Style Outlets",
    name: "Getafe The Style Outlets",
    slug: "getafe-the-style-outlets",
    countryId: "spain",
    cityId: "getafe",
    restaurants: [
      "CAFÉ Y TE",
      "FIVE GUYS",
      "HARRY THE COFFEE COLLECTIVE",
      "RODILLA",
      "THE CHATTER CAFÉ"
    ],
    officialWebsite: "https://getafe.thestyleoutlets.es/en",
    websiteUrl: "https://getafe.thestyleoutlets.es/en",
    address: "Avda. Río Guadalquivir, 15, 28906 Getafe, Madrid, Spain",
    latitude: 40.2699,
    longitude: -3.6951,
    openingHours: "Mon-Sun 10:00 - 22:00; special days may vary",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "Official current all stores directory available",
    services: [
      "Tax Free Shopping",
      "Tourist Discount Card",
      "Free Wi-Fi",
      "Electric Car Charging",
      "Wheelchairs",
      "Baby Cart Rental",
      "Motorcycle Parking and Lockers",
      "Gift Card",
      "Storage",
      "Safe Kids",
      "Nursing Rooms",
      "WhatsApp Chat",
      "Pets Allowed"
    ],
    parking: "Official visitor pages include parking information; services include motorcycle parking and lockers. Check official parking page for current car-parking details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "70.01 EUR on a single receipt",
    taxFreeOperator: "Global Blue / Tax Refund for Tourists / Premier Tax Free / Tax Free VAT Refund Service for Tourists",
    taxFreeOfficeInfo: "Official Tax Free Shopping page says non-EU residents should request the Tax-Free form in participating stores or use Global Blue Mobile Customer Care, validate at customs, and send the stamped form to the provider.",
    aliases: ["Getafe The Style Outlets", "The Style Outlets Getafe"],
    status: "active",
    airportDistanceKm: 25,
    airportInfoText: "Adolfo Suárez Madrid-Barajas Airport • 25 km",
    airports: [{ code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", distanceKm: 25 }],
    cityCenterDistanceKm: 17,
    cityCenterInfoText: "Madrid City Centre • 17 km",
    cityCenterInfo: { name: "Madrid City Centre", distanceKm: 17, recommendedRoute: "Use current official map directions to Avda. Río Guadalquivir, 15." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Getafe%20The%20Style%20Outlets%2C%20Avda.%20R%C3%ADo%20Guadalquivir%2015%2C%20Getafe%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=Getafe%20The%20Style%20Outlets&address=Avda.%20R%C3%ADo%20Guadalquivir%2015%2C%20Getafe%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=Getafe%20The%20Style%20Outlets%2C%20Avda.%20R%C3%ADo%20Guadalquivir%2015%2C%20Getafe%2C%20Spain"
  } as any,
  {
    outletId: "san-sebastian-de-los-reyes-the-style-outlets",
    outletName: "San Sebastián de los Reyes The Style Outlets",
    name: "San Sebastián de los Reyes The Style Outlets",
    slug: "san-sebastian-de-los-reyes-the-style-outlets",
    countryId: "spain",
    cityId: "san-sebastian-de-los-reyes",
    restaurants: [
      "FIVE GUYS",
      "GROSSO NAPOLETANO",
      "STARBUCKS COFFEE",
      "THE CHATTER CAFÉ"
    ],
    officialWebsite: "https://ss-de-los-reyes.thestyleoutlets.es/en",
    websiteUrl: "https://ss-de-los-reyes.thestyleoutlets.es/en",
    address: "C/ Salvador de Madariaga, s/n, 28702 San Sebastián de los Reyes, Madrid, Spain",
    latitude: 40.5464,
    longitude: -3.6067,
    openingHours: "Mon-Sun 10:00 - 22:00; special days may vary",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "Official current all stores directory available; official tourism page says over 80 brands",
    services: [
      "Tax Free Shopping",
      "Parking",
      "Visitor Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Tourist Services"
    ],
    parking: "Official visitor pages include parking information; check the official parking page for current details.",
    taxFreeAvailable: true,
    vatRate: 21,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not officially verified",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "Official tourism page says Tax Free shopping is available in stores; confirm participating stores, refund provider, minimum spend, and customs process at the centre.",
    aliases: ["San Sebastián de los Reyes The Style Outlets", "SS de los Reyes The Style Outlets", "The Style Outlets San Sebastián de los Reyes"],
    status: "active",
    airportDistanceKm: 10,
    airportInfoText: "Adolfo Suárez Madrid-Barajas Airport • 10 km",
    airports: [{ code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", distanceKm: 10 }],
    cityCenterDistanceKm: 20,
    cityCenterInfoText: "Madrid City Centre • 20 km",
    cityCenterInfo: { name: "Madrid City Centre", distanceKm: 20, recommendedRoute: "Use current official map directions to C/ Salvador de Madariaga." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=San%20Sebasti%C3%A1n%20de%20los%20Reyes%20The%20Style%20Outlets%2C%20C%2F%20Salvador%20de%20Madariaga%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=San%20Sebasti%C3%A1n%20de%20los%20Reyes%20The%20Style%20Outlets&address=C%2F%20Salvador%20de%20Madariaga%2C%2028702%20San%20Sebasti%C3%A1n%20de%20los%20Reyes%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=San%20Sebasti%C3%A1n%20de%20los%20Reyes%20The%20Style%20Outlets%2C%20C%2F%20Salvador%20de%20Madariaga%2C%20Spain"
  } as any,
  {
    outletId: "coruna-the-style-outlets",
    outletName: "Coruña The Style Outlets",
    name: "Coruña The Style Outlets",
    slug: "coruna-the-style-outlets",
    countryId: "spain",
    cityId: "a-coruna",
    restaurants: ["LLAOLLAO", "BURGER KING", "PANARIA"],
    officialWebsite: "https://coruna.thestyleoutlets.es/en",
    websiteUrl: "https://coruna.thestyleoutlets.es/en",
    address: "Avenida de Alvedro, 5, Nacional 550 km 9.5, 15189 Culleredo, A Coruña, Spain",
    latitude: 43.3026,
    longitude: -8.3794,
    openingHours: "Mon-Sat 10:00 - 21:00; Sun closed",
    heroImage: "",
    galleryImages: [],
    rating: 0,
    reviewCount: 0,
    storesCountText: "Over 50 stores",
    services: ["Parking", "Free Wi-Fi", "Free Storage", "Nursing Rooms", "Amazon Lockers", "Umbrella Service", "Electric Car Charging", "Wheelchair Loan", "Gift Card", "Motorcycle Parking", "WhatsApp Services", "Pet Friendly"],
    parking: "Official centre navigation includes Parking and official services list free parking.",
    taxFreeAvailable: false,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "0.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "No official outlet/operator tax-free service page, refund provider, or desk information was verified for this outlet. Eligible visitors should confirm directly with individual stores before purchase.",
    aliases: ["Coruña The Style Outlets", "Coruna The Style Outlets", "A Coruña The Style Outlets", "The Style Outlets Coruña", "The Style Outlets Coruna"],
    status: "active",
    airportDistanceKm: 3,
    airportInfoText: "A Coruña Airport • 3 km",
    airports: [{ code: "LCG", name: "A Coruña Airport", distanceKm: 3 }],
    cityCenterDistanceKm: 10,
    cityCenterInfoText: "A Coruña City Centre • 10 km",
    cityCenterInfo: { name: "A Coruña City Centre", distanceKm: 10, recommendedRoute: "Official operator information says the centre is 10 minutes from A Coruña city centre and less than 3 minutes from A Coruña airport." },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Coru%C3%B1a%20The%20Style%20Outlets%2C%20Avenida%20de%20Alvedro%205%2C%2015189%20Culleredo%2C%20A%20Coru%C3%B1a%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=Coru%C3%B1a%20The%20Style%20Outlets&address=Avenida%20de%20Alvedro%205%2C%2015189%20Culleredo%2C%20A%20Coru%C3%B1a%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=Coru%C3%B1a%20The%20Style%20Outlets%2C%20Avenida%20de%20Alvedro%205%2C%2015189%20Culleredo%2C%20A%20Coru%C3%B1a%2C%20Spain"
  } as any,
  {
    outletId: "sambil-madrid",
    name: "Sambil Madrid",
    slug: "sambil-madrid",
    aliases: ["Sambil Outlet", "Sambil Outlet Madrid", "Centro Comercial Sambil Leganés"],
    countryId: "spain",
    cityId: "madrid",
    address: "Calle de Mondragón s/n, 28917 Leganés, Madrid, Spain",
    latitude: 40.3355,
    longitude: -3.7379,
    openingHours: "Mon-Sat 09:00 - 22:00; Sun and holidays 09:00 - 21:00; leisure and restaurants have separate hours",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Official current store directory available",
    rating: 0,
    reviewCount: 0,
    services: ["Parking", "Restaurants & Cafes", "Leisure", "Cinema", "Accessibility"],
    restaurants: ["100 Montaditos", "Acadios Kebab", "Anubis Coctelería", "Burger King", "Candy Candy", "El Reino Asador", "Pure & Bowl"],
    parking: "Official centre pages include visitor information for the centre; confirm current parking details on the official website before visiting.",
    taxFreeAvailable: false,
    vatRate: 21,
    estimatedRefundRate: 12,
    minimumTaxFreeSpend: "0.01 EUR",
    taxFreeOperator: "Not officially verified",
    taxFreeOfficeInfo: "No official outlet/operator tax-free desk or specific tax-free operator information was verified for this centre. Eligible visitors should confirm directly with individual stores before purchase.",
    cityCenterDistanceKm: 12,
    airportDistanceKm: 28,
    airports: [{ code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", distanceKm: 28 }],
    cityCenterInfo: { name: "Madrid City Centre", distanceKm: 12, recommendedRoute: "Use current official map directions to Sambil Madrid in Leganés." },
    websiteUrl: "https://sambiloutlet.es/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sambil%20Madrid%2C%20Legan%C3%A9s%2C%20Madrid%2C%20Spain",
    appleMapsUrl: "http://maps.apple.com/?q=Sambil%20Madrid&address=Legan%C3%A9s%2C%20Madrid%2C%20Spain",
    yandexMapsUrl: "https://yandex.com/maps/?text=Sambil%20Madrid%2C%20Legan%C3%A9s%2C%20Madrid%2C%20Spain"
  } as any
];
