export const switzerlandOutlets = [
  {
    outletId: "foxtown-factory-stores",
    name: "FoxTown Factory Stores",
    slug: "foxtown-factory-stores",
    countryId: "switzerland",
    cityId: "mendrisio",
    address: "Via Angelo Maspoli 18, 6850 Mendrisio, Switzerland",
    latitude: 45.8653,
    longitude: 8.9802,
    openingHours: "Daily 11:00 - 19:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 160 stores",
    rating: 0,
    reviewCount: 0,
    services: [],
    taxFreeAvailable: true,
    vatRate: 8.1,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "",
    taxFreeOperator: "",
    taxFreeOfficeInfo: "",
    cityCenterDistanceKm: 0,
    airportDistanceKm: 0,
    airports: [],
    cityCenterInfo: {
      name: "",
      distanceKm: 0,
      recommendedRoute: ""
    },
    nearby: [],
    websiteUrl: "https://www.foxtown.com/en/homepage",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=FoxTown%20Factory%20Stores%2C%20Via%20Angelo%20Maspoli%2018%2C%206850%20Mendrisio%2C%20Switzerland",
    appleMapsUrl: "http://maps.apple.com/?q=FoxTown%20Factory%20Stores%2C%20Via%20Angelo%20Maspoli%2018%2C%206850%20Mendrisio%2C%20Switzerland",
    yandexMapsUrl: "https://yandex.com/maps/?text=FoxTown%20Factory%20Stores%2C%20Via%20Angelo%20Maspoli%2018%2C%206850%20Mendrisio%2C%20Switzerland"
  },
  {
    outletId: "landquart-fashion-outlet",
    name: "Landquart Fashion Outlet",
    slug: "landquart-fashion-outlet",
    countryId: "switzerland",
    cityId: "landquart",
    address: "Alpenblick 5, 7302 Landquart, Switzerland",
    latitude: 46.9672,
    longitude: 9.5580,
    openingHours: "Daily 10:00 - 19:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "More than 80 stores",
    rating: 0,
    reviewCount: 0,
    services: [],
    taxFreeAvailable: true,
    vatRate: 8.1,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "",
    taxFreeOperator: "",
    taxFreeOfficeInfo: "",
    cityCenterDistanceKm: 0,
    airportDistanceKm: 0,
    airports: [],
    cityCenterInfo: {
      name: "",
      distanceKm: 0,
      recommendedRoute: ""
    },
    nearby: [],
    websiteUrl: "https://www.landquartfashionoutlet.ch/en",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Landquart%20Fashion%20Outlet%2C%20Alpenblick%205%2C%207302%20Landquart%2C%20Switzerland",
    appleMapsUrl: "http://maps.apple.com/?q=Landquart%20Fashion%20Outlet%2C%20Alpenblick%205%2C%207302%20Landquart%2C%20Switzerland",
    yandexMapsUrl: "https://yandex.com/maps/?text=Landquart%20Fashion%20Outlet%2C%20Alpenblick%205%2C%207302%20Landquart%2C%20Switzerland"
  },
  {
    outletId: "fashion-fish-factory-outlet",
    name: "Fashion Fish Factory Outlet",
    slug: "fashion-fish-factory-outlet",
    countryId: "switzerland",
    cityId: "schoenenwerd",
    address: "Parkstrasse 1, 5012 Schönenwerd, Switzerland",
    latitude: 47.3718,
    longitude: 8.0012,
    openingHours: "Mon-Fri 10:00 - 18:30; Sat 10:00 - 18:00; Sun closed",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 45 stores",
    rating: 0,
    reviewCount: 0,
    services: [],
    taxFreeAvailable: true,
    vatRate: 8.1,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "",
    taxFreeOperator: "",
    taxFreeOfficeInfo: "",
    cityCenterDistanceKm: 0,
    airportDistanceKm: 0,
    airports: [],
    cityCenterInfo: {
      name: "",
      distanceKm: 0,
      recommendedRoute: ""
    },
    nearby: [],
    websiteUrl: "https://www.fashionfish.ch/en/",
    status: "active",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Fashion%20Fish%2C%20Parkstrasse%201%2C%205012%20Sch%C3%B6nenwerd%2C%20Switzerland",
    appleMapsUrl: "http://maps.apple.com/?q=Fashion%20Fish%2C%20Parkstrasse%201%2C%205012%20Sch%C3%B6nenwerd%2C%20Switzerland",
    yandexMapsUrl: "https://yandex.com/maps/?text=Fashion%20Fish%2C%20Parkstrasse%201%2C%205012%20Sch%C3%B6nenwerd%2C%20Switzerland"
  }
];
