export const ukOutlets = [
  {
    outletId: "bicester-village",
    name: "Bicester Village",
    slug: "bicester-village",
    countryId: "united-kingdom",
    cityId: "london",
    address: "50 Pingle Drive, Bicester, Oxfordshire OX26 6WD, United Kingdom",
    latitude: 51.8916,
    longitude: -1.1561,
    openingHours: "09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "150+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Guest Services",
      "Restaurants & Cafes",
      "Train Station Nearby",
      "Hands-free Shopping",
      "Personal Shopping",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Tax Free Info"
    ],
    restaurants: [
      "Cecconi's",
      "Ottolenghi",
      "La Tua Pasta",
      "Shan Shui",
      "The Double Red Duke",
      "Ralph's Coffee"
    ],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for goods carried in personal luggage are generally not available for in-store purchases in Great Britain. Check official UK rules and the boutique before planning a tax-free refund.",
    cityCenterDistanceKm: 95,
    airportDistanceKm: 85,
    airports: [
      {
        code: "LHR",
        name: "London Heathrow Airport",
        distanceKm: 85
      },
      {
        code: "LGW",
        name: "London Gatwick Airport",
        distanceKm: 110
      }
    ],
    cityCenterInfo: {
      name: "London City Center",
      distanceKm: 95,
      recommendedRoute: "Train from London Marylebone to Bicester Village"
    },
    nearby: [
      {
        name: "Oxford",
        distanceKm: 25
      },
      {
        name: "Bicester Town Centre",
        distanceKm: 2
      }
    ],
    websiteUrl: "https://www.thebicestercollection.com/bicester-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Bicester+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Bicester+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Bicester%20Village"
  },
  {
    outletId: "cheshire-oaks",
    name: "Cheshire Oaks Designer Outlet",
    slug: "cheshire-oaks",
    countryId: "united-kingdom",
    cityId: "liverpool",
    address: "Kinsey Road, Ellesmere Port, Cheshire CH65 9JJ, United Kingdom",
    latitude: 53.2654,
    longitude: -2.8842,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 09:00 - 21:00; Sun 10:00 - 19:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "140+ Stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: [
      "Wagamama",
      "Comptoir Libanais",
      "YO! Sushi",
      "Starbucks",
      "Joe & The Juice",
      "GAIL's Bakery"
    ],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Visitors should check official UK rules and individual stores before planning any tax-free shopping.",
    cityCenterDistanceKm: 25,
    airportDistanceKm: 40,
    airports: [
      {
        code: "LPL",
        name: "Liverpool John Lennon Airport",
        distanceKm: 40
      },
      {
        code: "MAN",
        name: "Manchester Airport",
        distanceKm: 55
      }
    ],
    cityCenterInfo: {
      name: "Liverpool City Center",
      distanceKm: 25,
      recommendedRoute: "Train to Ellesmere Port or bus via Chester / Liverpool"
    },
    nearby: [
      {
        name: "Chester",
        distanceKm: 12
      },
      {
        name: "Ellesmere Port",
        distanceKm: 3
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-cheshire-oaks/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Cheshire+Oaks+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Cheshire+Oaks+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Cheshire%20Oaks%20Designer%20Outlet"
  },
  {
    outletId: "ashford-designer-outlet",
    name: "Ashford Designer Outlet",
    slug: "ashford-designer-outlet",
    countryId: "united-kingdom",
    cityId: "ashford",
    address: "Kimberley Way, Ashford TN24 0SD, United Kingdom",
    latitude: 51.1436,
    longitude: 0.8754,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "100+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Ashford City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-ashford/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Ashford+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Ashford+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Ashford%20Designer%20Outlet"
  },
  {
    outletId: "bridgend-designer-outlet",
    name: "Bridgend Designer Outlet",
    slug: "bridgend-designer-outlet",
    countryId: "united-kingdom",
    cityId: "cardiff",
    address: "The Derwen, Bridgend CF32 9SU, United Kingdom",
    latitude: 51.5338,
    longitude: -3.577,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Cardiff City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-bridgend/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Bridgend+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Bridgend+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Bridgend%20Designer%20Outlet"
  },
  {
    outletId: "caledonia-park",
    name: "Caledonia Park Designer Outlet",
    slug: "caledonia-park",
    countryId: "united-kingdom",
    cityId: "gretna",
    address: "Glasgow Road, Gretna DG16 5GG, United Kingdom",
    latitude: 55.0006,
    longitude: -3.0676,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "45+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Gretna City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://caledoniapark.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Caledonia+Park+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Caledonia+Park+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Caledonia%20Park%20Designer%20Outlet"
  },
  {
    outletId: "clarks-village",
    name: "Clarks Village",
    slug: "clarks-village",
    countryId: "united-kingdom",
    cityId: "street",
    address: "Farm Road, Street BA16 0BB, United Kingdom",
    latitude: 51.1277,
    longitude: -2.7425,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Street City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.clarksvillage.co.uk/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Clarks+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Clarks+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Clarks%20Village"
  },
  {
    outletId: "dalton-park",
    name: "Dalton Park Outlet Shopping Destination",
    slug: "dalton-park",
    countryId: "united-kingdom",
    cityId: "durham",
    address: "Murton, Seaham SR7 9HU, United Kingdom",
    latitude: 54.8194,
    longitude: -1.3722,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "65+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Durham City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.dalton-park.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Dalton+Park+Outlet+Shopping+Destination",
    appleMapsUrl: "http://maps.apple.com/?q=Dalton+Park+Outlet+Shopping+Destination",
    yandexMapsUrl: "https://yandex.com/maps/?text=Dalton%20Park%20Outlet%20Shopping%20Destination"
  },
  {
    outletId: "east-midlands-designer-outlet",
    name: "East Midlands Designer Outlet",
    slug: "east-midlands-designer-outlet",
    countryId: "united-kingdom",
    cityId: "nottingham",
    address: "Mansfield Road, South Normanton DE55 2JW, United Kingdom",
    latitude: 53.1062,
    longitude: -1.3239,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "65+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Nottingham City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-east-midlands/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=East+Midlands+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=East+Midlands+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=East%20Midlands%20Designer%20Outlet"
  },
  {
    outletId: "gloucester-quays",
    name: "Gloucester Quays",
    slug: "gloucester-quays",
    countryId: "united-kingdom",
    cityId: "gloucester",
    address: "St Ann Way, Gloucester GL1 5SH, United Kingdom",
    latitude: 51.8591,
    longitude: -2.2529,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "50+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Gloucester City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://gloucesterquays.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Gloucester+Quays",
    appleMapsUrl: "http://maps.apple.com/?q=Gloucester+Quays",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gloucester%20Quays"
  },
  {
    outletId: "gretna-gateway-outlet-village",
    name: "Gretna Gateway Outlet Village",
    slug: "gretna-gateway-outlet-village",
    countryId: "united-kingdom",
    cityId: "gretna",
    address: "Glasgow Road, Gretna DG16 5GG, United Kingdom",
    latitude: 55.0006,
    longitude: -3.0676,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "45+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Gretna City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://caledoniapark.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Gretna+Gateway+Outlet+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Gretna+Gateway+Outlet+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gretna%20Gateway%20Outlet%20Village"
  },
  {
    outletId: "gunwharf-quays",
    name: "Gunwharf Quays",
    slug: "gunwharf-quays",
    countryId: "united-kingdom",
    cityId: "portsmouth",
    address: "Gunwharf Quays, Portsmouth PO1 3TZ, United Kingdom",
    latitude: 50.7952,
    longitude: -1.105,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Portsmouth City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://gunwharf-quays.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Gunwharf+Quays",
    appleMapsUrl: "http://maps.apple.com/?q=Gunwharf+Quays",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gunwharf%20Quays"
  },
  {
    outletId: "icon-outlet-at-the-o2",
    name: "Icon Outlet at The O2",
    slug: "icon-outlet-at-the-o2",
    countryId: "united-kingdom",
    cityId: "london",
    address: "Peninsula Square, London SE10 0DX, United Kingdom",
    latitude: 51.5029,
    longitude: 0.0032,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "60+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "London City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.theo2.co.uk/icon-outlet",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Icon+Outlet+at+The+O2",
    appleMapsUrl: "http://maps.apple.com/?q=Icon+Outlet+at+The+O2",
    yandexMapsUrl: "https://yandex.com/maps/?text=Icon%20Outlet%20at%20The%20O2"
  },
  {
    outletId: "junction-32-outlet",
    name: "Junction 32 Outlet Shopping Village",
    slug: "junction-32-outlet",
    countryId: "united-kingdom",
    cityId: "leeds",
    address: "Carr Wood Road, Castleford WF10 4FR, United Kingdom",
    latitude: 53.7105,
    longitude: -1.3427,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "80+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Leeds City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://junction32.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Junction+32+Outlet+Shopping+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Junction+32+Outlet+Shopping+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Junction%2032%20Outlet%20Shopping%20Village"
  },
  {
    outletId: "lakeside-village",
    name: "Lakeside Village Outlet Shopping",
    slug: "lakeside-village",
    countryId: "united-kingdom",
    cityId: "doncaster",
    address: "White Rose Way, Doncaster DN4 5PH, United Kingdom",
    latitude: 53.5031,
    longitude: -1.1284,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "45+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Doncaster City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://lakeside-village.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Lakeside+Village+Outlet+Shopping",
    appleMapsUrl: "http://maps.apple.com/?q=Lakeside+Village+Outlet+Shopping",
    yandexMapsUrl: "https://yandex.com/maps/?text=Lakeside%20Village%20Outlet%20Shopping"
  },
  {
    outletId: "london-designer-outlet",
    name: "London Designer Outlet",
    slug: "london-designer-outlet",
    countryId: "united-kingdom",
    cityId: "london",
    address: "Wembley Park Boulevard, London HA9 0QL, United Kingdom",
    latitude: 51.558,
    longitude: -0.2836,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "70+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "London City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.londondesigneroutlet.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=London+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=London+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=London%20Designer%20Outlet"
  },
  {
    outletId: "springfields-outlet",
    name: "Springfields Outlet Shopping & Leisure",
    slug: "springfields-outlet",
    countryId: "united-kingdom",
    cityId: "spalding",
    address: "Camel Gate, Spalding PE12 6EU, United Kingdom",
    latitude: 52.791,
    longitude: -0.1511,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "50+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Spalding City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://springfieldsshopping.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Springfields+Outlet+Shopping+&+Leisure",
    appleMapsUrl: "http://maps.apple.com/?q=Springfields+Outlet+Shopping+&+Leisure",
    yandexMapsUrl: "https://yandex.com/maps/?text=Springfields%20Outlet%20Shopping%20&%20Leisure"
  },
  {
    outletId: "swindon-designer-outlet",
    name: "Swindon Designer Outlet",
    slug: "swindon-designer-outlet",
    countryId: "united-kingdom",
    cityId: "swindon",
    address: "Kemble Drive, Swindon SN2 2DY, United Kingdom",
    latitude: 51.5656,
    longitude: -1.7984,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Swindon City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-swindon/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Swindon+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Swindon+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Swindon%20Designer%20Outlet"
  },
  {
    outletId: "the-boulevard-banbridge",
    name: "The Boulevard Banbridge",
    slug: "the-boulevard-banbridge",
    countryId: "united-kingdom",
    cityId: "banbridge",
    address: "Cascum Road, Banbridge BT32 4LF, United Kingdom",
    latitude: 54.3449,
    longitude: -6.2842,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "50+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Banbridge City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://the-boulevard.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=The+Boulevard+Banbridge",
    appleMapsUrl: "http://maps.apple.com/?q=The+Boulevard+Banbridge",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Boulevard%20Banbridge"
  },
  {
    outletId: "the-galleria-outlet",
    name: "The Galleria Outlet Shopping",
    slug: "the-galleria-outlet",
    countryId: "united-kingdom",
    cityId: "hatfield",
    address: "Comet Way, Hatfield AL10 0XR, United Kingdom",
    latitude: 51.763,
    longitude: -0.2417,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "80+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Hatfield City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://thegalleria.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=The+Galleria+Outlet+Shopping",
    appleMapsUrl: "http://maps.apple.com/?q=The+Galleria+Outlet+Shopping",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Galleria%20Outlet%20Shopping"
  },
  {
    outletId: "west-midlands-designer-outlet",
    name: "West Midlands Designer Outlet",
    slug: "west-midlands-designer-outlet",
    countryId: "united-kingdom",
    cityId: "birmingham",
    address: "Eastern Way, Cannock WS11 7JZ, United Kingdom",
    latitude: 52.6819,
    longitude: -2.015,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "80+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "Birmingham City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-west-midlands/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=West+Midlands+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=West+Midlands+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=West%20Midlands%20Designer%20Outlet"
  },
  {
    outletId: "york-designer-outlet",
    name: "York Designer Outlet",
    slug: "york-designer-outlet",
    countryId: "united-kingdom",
    cityId: "york",
    address: "St Nicholas Avenue, York YO19 4TA, United Kingdom",
    latitude: 53.9227,
    longitude: -1.0786,
    openingHours: "Check official website",
    heroImage: "",
    galleryImages: [],
    storesCountText: "100+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Costa Coffee", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 50,
    airports: [],
    cityCenterInfo: { name: "York City Center", distanceKm: 10, recommendedRoute: "Check official outlet getting-here guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-york/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=York+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=York+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=York%20Designer%20Outlet"
  }
];
