export const ukOutlets = [
  {
    outletId: "bicester-village",
    name: "Bicester Village",
    slug: "bicester-village",
    countryId: "united-kingdom",
    cityId: "london",
    address: "50 Pingle Drive, Bicester, Oxfordshire OX26 6WD, United Kingdom",
    latitude: 51.8916,
    longitude: -1.1561,
    openingHours: "09:00 - 21:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "150+ Boutiques",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Guest Services",
      "Restaurants & Cafes",
      "Train Station Nearby",
      "Hands-free Shopping",
      "Personal Shopping",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "Tax Free Info"
    ],
    restaurants: [
      "Cecconi's",
      "Ottolenghi",
      "La Tua Pasta",
      "Shan Shui",
      "The Double Red Duke",
      "Ralph's Coffee"
    ],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for goods carried in personal luggage are generally not available for in-store purchases in Great Britain. Check official UK rules and the boutique before planning a tax-free refund.",
    cityCenterDistanceKm: 95,
    airportDistanceKm: 85,
    airports: [
      {
        code: "LHR",
        name: "London Heathrow Airport",
        distanceKm: 85
      },
      {
        code: "LGW",
        name: "London Gatwick Airport",
        distanceKm: 110
      }
    ],
    cityCenterInfo: {
      name: "London City Centre",
      distanceKm: 95,
      recommendedRoute: "Train from London Marylebone to Bicester Village"
    },
    nearby: [
      {
        name: "Oxford",
        distanceKm: 25
      },
      {
        name: "Bicester Town Centre",
        distanceKm: 2
      }
    ],
    websiteUrl: "https://www.thebicestercollection.com/bicester-village/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Bicester+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Bicester+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Bicester%20Village"
  },
  {
    outletId: "cheshire-oaks",
    name: "Cheshire Oaks Designer Outlet",
    slug: "cheshire-oaks",
    countryId: "united-kingdom",
    cityId: "liverpool",
    address: "Kinsey Road, Ellesmere Port, Cheshire CH65 9JJ, United Kingdom",
    latitude: 53.2654,
    longitude: -2.8842,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 09:00 - 21:00; Sun 10:00 - 19:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "140+ stores",
    rating: 4.6,
    reviewCount: 0,
    services: [
      "Parking",
      "Guest Services",
      "Restaurants & Cafes",
      "Transport Info",
      "Wi-Fi",
      "Gift Cards",
      "Accessibility",
      "ATM",
      "Kids Area",
      "Personal Shopping"
    ],
    restaurants: ["Auntie Anne's", "Bakers & Baristas", "Bubbleology", "Chit 'n' Chaat", "Comptoir Libanais", "Costa Coffee", "Ed's Easy Diner", "Five Guys", "Gail's Bakery", "Greggs", "Harry Ramsdens", "Joe and The Juice", "Krispy Kreme", "McDonald's", "Mowgli", "PHO", "Pizza Express", "Pret A Manger", "Slim Chickens", "Starbucks", "Tortilla", "Wagamama", "YO! Sushi"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Visitors should check official UK rules and individual stores before planning any tax-free shopping.",
    cityCenterDistanceKm: 25,
    airportDistanceKm: 40,
    airports: [
      {
        code: "LPL",
        name: "Liverpool John Lennon Airport",
        distanceKm: 40
      },
      {
        code: "MAN",
        name: "Manchester Airport",
        distanceKm: 55
      }
    ],
    cityCenterInfo: {
      name: "Liverpool City Centre",
      distanceKm: 25,
      recommendedRoute: "Train to Ellesmere Port or bus via Chester / Liverpool"
    },
    nearby: [
      {
        name: "Chester",
        distanceKm: 12
      },
      {
        name: "Ellesmere Port",
        distanceKm: 3
      }
    ],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-cheshire-oaks/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Cheshire+Oaks+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Cheshire+Oaks+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Cheshire%20Oaks%20Designer%20Outlet"
  },
  {
    outletId: "ashford-designer-outlet",
    name: "Ashford Designer Outlet",
    slug: "ashford-designer-outlet",
    countryId: "united-kingdom",
    cityId: "ashford",
    address: "Kimberley Way, Ashford, Kent TN24 0SD, United Kingdom",
    latitude: 51.1436,
    longitude: 0.8754,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 09:00 - 21:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "100+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Wagamama", "Pizza Express", "Five Guys", "Nando's", "KOKORO", "The Cornish Bakery"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1,
    airportDistanceKm: 95,
    airports: [
      {
        code: "LGW",
        name: "London Gatwick Airport",
        distanceKm: 95
      }
    ],
    cityCenterInfo: { name: "Ashford Town Centre", distanceKm: 1, recommendedRoute: "Follow official outlet getting-here guidance via Kimberley Way" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-ashford/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Ashford+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Ashford+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Ashford%20Designer%20Outlet"
  },
  {
    outletId: "bridgend-designer-outlet",
    name: "McArthurGlen Designer Outlet Bridgend",
    slug: "bridgend-designer-outlet",
    countryId: "united-kingdom",
    cityId: "cardiff",
    address: "The Derwen, Bridgend, South Wales CF32 9SU, United Kingdom",
    latitude: 51.5338,
    longitude: -3.577,
    openingHours: "Mon-Sat 10:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "80+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Free Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging"],
    restaurants: ["Chopstix", "Costa Coffee", "Cwtch x Crafty Smuggler", "Five Guys", "Greggs", "Krispy Kreme", "Love Churros", "McDonald's", "Mowgli", "Nando's", "Pogo Bakery", "Slim Chickens", "Starbucks", "The Strawberry Hut", "Wagamama", "Zizzi"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 35,
    airports: [
      { code: "CWL", name: "Cardiff Airport", distanceKm: 35 }
    ],
    cityCenterInfo: { name: "Cardiff City Centre", distanceKm: 30, recommendedRoute: "Follow official outlet getting-here guidance from Cardiff or Swansea" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-bridgend/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Bridgend+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Bridgend+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Bridgend%20Designer%20Outlet"
  },
  {
    outletId: "caledonia-park",
    name: "Caledonia Park Designer Outlet",
    slug: "caledonia-park",
    countryId: "united-kingdom",
    cityId: "gretna",
    address: "Glasgow Road, Gretna DG16 5GG, United Kingdom",
    latitude: 55.0006,
    longitude: -3.0676,
    openingHours: "Daily 09:00 - 18:00 (park hours; individual restaurants and stores may vary)",
    heroImage: "",
    galleryImages: [],
    storesCountText: "over 50 stores and restaurants",
    rating: 4.5,
    reviewCount: 0,
    services: ["Free Parking", "Guest Information Hub", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging", "Quiet Hours"],
    restaurants: ["Burger King", "Cadbury", "Churro Loco", "Cornish Bakery", "Costa Coffee", "Drummuir Farm", "Greggs", "Pizza Express", "Starbucks", "Subway", "The Sweet Emporium"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 90,
    airports: [
      { code: "NCL", name: "Newcastle International Airport", distanceKm: 90 }
    ],
    cityCenterInfo: { name: "Gretna City Centre", distanceKm: 10, recommendedRoute: "Follow official Caledonia Park getting-here guidance via the Gretna exit from the M6/M74/A75" },
    nearby: [],
    websiteUrl: "https://caledoniapark.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Caledonia+Park+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=Caledonia+Park+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=Caledonia%20Park%20Designer%20Outlet"
  },
  {
    outletId: "clarks-village",
    name: "Clarks Village",
    slug: "clarks-village",
    countryId: "united-kingdom",
    cityId: "street",
    address: "12 Farm Road, Street BA16 0BB, United Kingdom",
    latitude: 51.1277,
    longitude: -2.7425,
    openingHours: "Mon-Sat 09:00 - 18:00; Sun larger stores from 11:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Bill's", "PizzaExpress", "Wagamama", "Slim Chickens", "The Cornish Bakery", "Caffè Nero"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1,
    airportDistanceKm: 40,
    airports: [
      {
        code: "BRS",
        name: "Bristol Airport",
        distanceKm: 40
      }
    ],
    cityCenterInfo: { name: "Street Town Centre", distanceKm: 1, recommendedRoute: "Follow official Clarks Village getting-here and parking guidance" },
    nearby: [],
    websiteUrl: "https://www.clarksvillage.co.uk/en",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Clarks+Village",
    appleMapsUrl: "http://maps.apple.com/?q=Clarks+Village",
    yandexMapsUrl: "https://yandex.com/maps/?text=Clarks%20Village"
  },
  {
    outletId: "dalton-park",
    name: "Dalton Park Outlet Shopping Destination",
    slug: "dalton-park",
    countryId: "united-kingdom",
    cityId: "durham",
    address: "Church St, Murton, Seaham SR7 9HU, United Kingdom",
    latitude: 54.8194,
    longitude: -1.3722,
    openingHours: "Mon-Fri 10:00 - 18:00; Sat 09:30 - 18:00; Sun 10:30 - 16:30",
    heroImage: "",
    galleryImages: [],
    storesCountText: "65+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Dancing Betty", "Etto", "Cafebar 1838", "Costa Coffee", "Bakers + Baristas", "KFC"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 15,
    airportDistanceKm: 35,
    airports: [
      {
        code: "NCL",
        name: "Newcastle International Airport",
        distanceKm: 35
      }
    ],
    cityCenterInfo: { name: "Durham City Centre", distanceKm: 15, recommendedRoute: "Follow official Dalton Park getting-here guidance via the A19" },
    nearby: [],
    websiteUrl: "https://www.dalton-park.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Dalton+Park+Outlet+Shopping+Destination",
    appleMapsUrl: "http://maps.apple.com/?q=Dalton+Park+Outlet+Shopping+Destination",
    yandexMapsUrl: "https://yandex.com/maps/?text=Dalton%20Park%20Outlet%20Shopping%20Destination"
  },
  {
    outletId: "east-midlands-designer-outlet",
    name: "Frasers Plus Designer Outlet East Midlands",
    slug: "east-midlands-designer-outlet",
    countryId: "united-kingdom",
    cityId: "nottingham",
    address: "Mansfield Road, South Normanton, Derbyshire DE55 2JW, United Kingdom",
    latitude: 53.1062,
    longitude: -1.3239,
    openingHours: "Mon-Sat 09:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 65 designer brands",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging"],
    restaurants: ["200 Degrees Coffee", "BB’s", "Burger Bar", "Chopstix", "Costa Coffee", "Doughnotts", "Five Guys", "Fluffy Fluffy", "Kouzina Greek", "Loaded Fries", "Love Churros", "Pizza Express", "Rose Deli", "Slim Chickens", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 35,
    airports: [
      { code: "EMA", name: "East Midlands Airport", distanceKm: 35 }
    ],
    cityCenterInfo: { name: "Nottingham City Centre", distanceKm: 30, recommendedRoute: "Follow official outlet guidance from Junction 28 of the M1" },
    nearby: [],
    websiteUrl: "https://fraserspluseastmidlands.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=East+Midlands+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=East+Midlands+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=East%20Midlands%20Designer%20Outlet"
  },
  {
    outletId: "gloucester-quays",
    name: "Gloucester Quays",
    slug: "gloucester-quays",
    countryId: "united-kingdom",
    cityId: "gloucester",
    address: "St Ann Way, Gloucester GL1 5SH, United Kingdom",
    latitude: 51.8591,
    longitude: -2.2529,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 10:00 - 19:00; Sun 10:00 - 17:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "50 stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Bill’s", "Brewhouse & Kitchen", "Coal Kitchen", "Five Guys", "Nando’s", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1,
    airportDistanceKm: 80,
    airports: [
      {
        code: "BHX",
        name: "Birmingham Airport",
        distanceKm: 80
      }
    ],
    cityCenterInfo: { name: "Gloucester City Centre", distanceKm: 1, recommendedRoute: "10-minute walk from Gloucester City Centre per official getting-here guidance" },
    nearby: [],
    websiteUrl: "https://gloucesterquays.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Gloucester+Quays",
    appleMapsUrl: "http://maps.apple.com/?q=Gloucester+Quays",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gloucester%20Quays"
  },
  {
    outletId: "gretna-gateway-outlet-village",
    name: "Gretna Gateway Outlet Village (legacy alias of Caledonia Park)",
    slug: "gretna-gateway-outlet-village",
    countryId: "united-kingdom",
    cityId: "gretna",
    address: "Glasgow Road, Gretna DG16 5GG, United Kingdom",
    latitude: 55.0006,
    longitude: -3.0676,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 10:00 - 19:00; Sun 10:00 - 17:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "over 50 stores and restaurants",
    rating: 4.5,
    reviewCount: 0,
    services: ["Free Parking", "Guest Information Hub", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging", "Quiet Hours"],
    restaurants: [],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 90,
    airports: [
      { code: "NCL", name: "Newcastle International Airport", distanceKm: 90 }
    ],
    cityCenterInfo: { name: "Gretna City Centre", distanceKm: 10, recommendedRoute: "Follow official Caledonia Park getting-here guidance via the Gretna exit from the M6/M74/A75" },
    nearby: [],
    websiteUrl: "https://caledoniapark.com/",
    status: "inactive",
    googleMapsUrl: "https://maps.google.com/?q=Caledonia+Park+Glasgow+Road+Gretna+DG16+5GG",
    appleMapsUrl: "http://maps.apple.com/?q=Caledonia+Park+Glasgow+Road+Gretna+DG16+5GG",
    yandexMapsUrl: "https://yandex.com/maps/?text=Caledonia%20Park%20Glasgow%20Road%20Gretna%20DG16%205GG"
  },
  {
    outletId: "gunwharf-quays",
    name: "Gunwharf Quays",
    slug: "gunwharf-quays",
    countryId: "united-kingdom",
    cityId: "portsmouth",
    address: "Gunwharf Quays House, Portsmouth PO1 3TZ, United Kingdom",
    latitude: 50.7952,
    longitude: -1.105,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "90+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["Carluccio's", "Cosy Club", "Frankie & Benny’s", "Giggling Squid", "Nando's", "PizzaExpress"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1,
    airportDistanceKm: 35,
    airports: [
      {
        code: "SOU",
        name: "Southampton Airport",
        distanceKm: 35
      }
    ],
    cityCenterInfo: { name: "Portsmouth City Centre", distanceKm: 1, recommendedRoute: "Follow official Gunwharf Quays getting-here guidance" },
    nearby: [],
    websiteUrl: "https://gunwharf-quays.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Gunwharf+Quays",
    appleMapsUrl: "http://maps.apple.com/?q=Gunwharf+Quays",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gunwharf%20Quays"
  },
  {
    outletId: "icon-outlet-at-the-o2",
    name: "Outlet Shopping at The O2",
    slug: "icon-outlet-at-the-o2",
    countryId: "united-kingdom",
    cityId: "london",
    address: "Peninsula Square, London SE10 0DX, United Kingdom",
    latitude: 51.5029,
    longitude: 0.0032,
    openingHours: "The O2 open daily 10:00 - 22:00; Outlet Shopping hours vary, check official listing",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 60 brands",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Welcome Desk", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "Outlet Shopping Parking Offer"],
    restaurants: ["Afrikana", "All Bar One", "ASK Italian", "Busaba", "Cabana", "Cafe Mint", "Chipotle", "Costa Coffee", "Five Guys", "Frankie & Benny’s", "Gaucho", "German Doner Kebab", "Gordon Ramsay Street Burger", "Haidilao Hot Pot", "Haute Dolci", "Hollywood Bowl", "Jimmy’s World Grill & Bar", "KFC", "Kitchen Pizzeria", "Las Iguanas", "Maki & Ramen", "Marugame Udon", "Nando’s", "PizzaExpress", "Rodizio Rico", "Scarlet Rasoi", "Slim Chickens", "Slug & Lettuce", "Snowflake Luxury Gelato", "Starbucks", "TGI Fridays™", "TOCA Social", "The Observatory", "Thunderbird Fried Chicken", "WHSmith", "Wasabi", "Wetherspoon", "Zizzi"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 6,
    airports: [
      {
        code: "LCY",
        name: "London City Airport",
        distanceKm: 6
      }
    ],
    cityCenterInfo: { name: "London City Centre", distanceKm: 10, recommendedRoute: "Follow official The O2 tube and rail guidance to North Greenwich" },
    nearby: [],
    websiteUrl: "https://www.theo2.co.uk/icon-outlet",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Outlet+Shopping+at+The+O2+SE10+0DX",
    appleMapsUrl: "http://maps.apple.com/?q=Outlet+Shopping+at+The+O2+SE10+0DX",
    yandexMapsUrl: "https://yandex.com/maps/?text=Outlet%20Shopping%20at%20The%20O2%20SE10%200DX"
  },
  {
    outletId: "junction-32-outlet",
    name: "Frasers Plus Designer Outlet Leeds",
    slug: "junction-32-outlet",
    countryId: "united-kingdom",
    cityId: "leeds",
    address: "Tomahawk Trail, Glasshoughton, Castleford WF10 4FR, United Kingdom",
    latitude: 53.7105,
    longitude: -1.3427,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 10:00 - 18:00; Sun 11:00 - 17:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "80+ Stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["200 Degrees Coffee", "Bakers + Baristas", "Cadbury Outlet", "Chopstix", "Costa", "For the Love of Hot Dogs", "Grape Tree", "Greggs", "Holland & Barrett", "Krispy Kreme", "Starbucks", "Subway", "The Nutella Donut Co", "Tilly's Kitchen"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 16,
    airportDistanceKm: 35,
    airports: [
      { code: "LBA", name: "Leeds Bradford Airport", distanceKm: 35 }
    ],
    cityCenterInfo: { name: "Leeds City Centre", distanceKm: 16, recommendedRoute: "Follow official outlet directions to Tomahawk Trail, Glasshoughton, Castleford" },
    nearby: [],
    websiteUrl: "https://frasersplusleeds.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Frasers+Plus+Designer+Outlet+Leeds+Tomahawk+Trail+Glasshoughton+Castleford+WF10+4FR",
    appleMapsUrl: "http://maps.apple.com/?q=Frasers+Plus+Designer+Outlet+Leeds+Tomahawk+Trail+Glasshoughton+Castleford+WF10+4FR",
    yandexMapsUrl: "https://yandex.com/maps/?text=Frasers%20Plus%20Designer%20Outlet%20Leeds%20Tomahawk%20Trail%20Glasshoughton%20Castleford%20WF10%204FR"
  },
  {
    outletId: "lakeside-village",
    name: "Lakeside Village Outlet Shopping",
    slug: "lakeside-village",
    countryId: "united-kingdom",
    cityId: "doncaster",
    address: "White Rose Way, Doncaster DN4 5PH, United Kingdom",
    latitude: 53.5031,
    longitude: -1.1284,
    openingHours: "Opening times vary per store; check official store pages",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 45 stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Free Parking", "Restaurants & Cafes", "Transport Info", "Accessibility", "Facilities", "Coaches", "Dog Friendly", "Play Areas"],
    restaurants: ["Costa Coffee", "Costa Drive Thru", "Etto", "Greggs", "Jamaica Blue", "KFC", "McDonald’s", "Pizza Hut"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 3,
    airportDistanceKm: 75,
    airports: [
      { code: "LBA", name: "Leeds Bradford Airport", distanceKm: 75 }
    ],
    cityCenterInfo: { name: "Doncaster City Centre", distanceKm: 3, recommendedRoute: "Follow official directions to White Rose Way, just off Junction 3 of the M18" },
    nearby: [],
    websiteUrl: "https://lakeside-village.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Lakeside+Village+White+Rose+Way+Doncaster+DN4+5PH",
    appleMapsUrl: "http://maps.apple.com/?q=Lakeside+Village+White+Rose+Way+Doncaster+DN4+5PH",
    yandexMapsUrl: "https://yandex.com/maps/?text=Lakeside%20Village%20White%20Rose%20Way%20Doncaster%20DN4%205PH"
  },
  {
    outletId: "london-designer-outlet",
    name: "London Designer Outlet",
    slug: "london-designer-outlet",
    countryId: "united-kingdom",
    cityId: "london",
    address: "Wembley Park Boulevard, Wembley Park, London HA9 0FD, United Kingdom",
    latitude: 51.558,
    longitude: -0.2836,
    openingHours: "Opening times vary per store/café/restaurant; Sunday larger-store hours split 11:00 - 17:00 or 12:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 80 stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "Dog Friendly", "Cinema", "M&S Currency Exchange"],
    restaurants: ["Afrikana", "Amorino", "Beirut Wonders – Lebanese Street Food", "Big Moe’s", "Chaboba Bubble Tea", "Churros Buenos", "Costa Coffee", "DumDum Donutterie", "Frankie & Benny’s", "JRC Global Buffet", "Las Iguanas", "Mowchi", "Nando’s Wembley", "Opa! Greek Bakery & Patisserie", "Pizza Express", "Pret A Manger", "Subway", "Tandoori Fusion", "TGI Fridays", "Wagamama", "Wenzel’s The Bakers", "You Me Sushi", "Zizzi"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 10,
    airportDistanceKm: 20,
    airports: [
      {
        code: "LHR",
        name: "London Heathrow Airport",
        distanceKm: 20
      }
    ],
    cityCenterInfo: { name: "London City Centre", distanceKm: 10, recommendedRoute: "Train from London Marylebone to Wembley Stadium" },
    nearby: [],
    websiteUrl: "https://www.londondesigneroutlet.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=London+Designer+Outlet+Wembley+Park+Boulevard+HA9+0FD",
    appleMapsUrl: "http://maps.apple.com/?q=London+Designer+Outlet+Wembley+Park+Boulevard+HA9+0FD",
    yandexMapsUrl: "https://yandex.com/maps/?text=London%20Designer%20Outlet%20Wembley%20Park%20Boulevard%20HA9%200FD"
  },
  {
    outletId: "springfields-outlet",
    name: "Springfields Designer Outlet & Leisure",
    slug: "springfields-outlet",
    countryId: "united-kingdom",
    cityId: "spalding",
    address: "Camelgate, Spalding, Lincolnshire PE12 6EU, United Kingdom",
    latitude: 52.791,
    longitude: -0.1511,
    openingHours: "Mon-Wed 09:30 - 18:00; Thu 09:30 - 20:00; Fri 09:30 - 18:00; Sat 09:00 - 18:00; Sun 10:30 - 17:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 55 outlet stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging", "Festival Gardens"],
    restaurants: ["Cadbury Outlet", "Caffè Nero", "Costa Coffee", "Petalo Lounge", "Springy's American Diner", "Subway", "The Noshery Co. Café & Restaurant", "The Parlour Restaurant", "The Sweet Emporium"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 2,
    airportDistanceKm: 100,
    airports: [
      { code: "EMA", name: "East Midlands Airport", distanceKm: 100 }
    ],
    cityCenterInfo: { name: "Spalding Town Centre", distanceKm: 2, recommendedRoute: "Follow official directions to Camelgate via the A16" },
    nearby: [],
    websiteUrl: "https://springfieldsoutlet.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Springfields+Designer+Outlet+%26+Leisure+PE12+6EU",
    appleMapsUrl: "http://maps.apple.com/?q=Springfields+Designer+Outlet+%26+Leisure+PE12+6EU",
    yandexMapsUrl: "https://yandex.com/maps/?text=Springfields%20Designer%20Outlet%20%26%20Leisure%20PE12%206EU"
  },
  {
    outletId: "swindon-designer-outlet",
    name: "Swindon Designer Outlet",
    slug: "swindon-designer-outlet",
    countryId: "united-kingdom",
    cityId: "swindon",
    address: "Kemble Drive, Swindon SN2 2DY, United Kingdom",
    latitude: 51.5656,
    longitude: -1.7984,
    openingHours: "Mon-Sat 10:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 90 brands",
    rating: 4.5,
    reviewCount: 0,
    services: ["Transport & Parking", "Shopping & Visitor Services", "Accessibility", "Family Services", "Guest Services", "Restaurants & Cafes", "Gift Cards"],
    restaurants: ["Auntie Anne’s", "Bubbleology", "Costa Coffee", "Don Churro", "El Mexicana", "Five Guys", "Greggs", "KFC", "Kouzina Greek", "Krispy Kreme Doughnuts", "Pizza Express", "Slim Chickens", "SOHO Coffee", "Starbucks", "Subway", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1.5,
    airportDistanceKm: 75,
    airports: [
      {
        code: "BRS",
        name: "Bristol Airport",
        distanceKm: 75
      }
    ],
    cityCenterInfo: { name: "Swindon Town Centre", distanceKm: 1.5, recommendedRoute: "15 minute walk from Swindon Town Centre per official outlet guidance" },
    nearby: [],
    websiteUrl: "https://designeroutletswindon.com/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=Swindon+Designer+Outlet+Kemble+Drive+SN2+2DY",
    appleMapsUrl: "http://maps.apple.com/?q=Swindon+Designer+Outlet+Kemble+Drive+SN2+2DY",
    yandexMapsUrl: "https://yandex.com/maps/?text=Swindon%20Designer%20Outlet%20Kemble%20Drive%20SN2%202DY"
  },
  {
    outletId: "the-boulevard-banbridge",
    name: "The Boulevard Banbridge",
    slug: "the-boulevard-banbridge",
    countryId: "united-kingdom",
    cityId: "banbridge",
    address: "The Boulevard, Outlet Park, Banbridge BT32 4LF, United Kingdom",
    latitude: 54.3449,
    longitude: -6.2842,
    openingHours: "Mon-Wed 10:00 - 18:00; Thu-Fri 10:00 - 21:00; Sat 09:00 - 18:00; Sun 13:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "60+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Free Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "EV Charging", "Tax Free Shopping"],
    restaurants: ["Bakers & Baristas", "Burger King", "Costa Coffee", "McDonald's", "Salt Kitchen", "Starbucks"],
    taxFreeAvailable: true,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Check participating stores",
    taxFreeOperator: "Participating stores at The Boulevard",
    taxFreeOfficeInfo: "The Boulevard states non-EU citizens can request a tax refund receipt at participating stores when exporting goods. Check participating stores before purchase.",
    cityCenterDistanceKm: 2,
    airportDistanceKm: 50,
    airports: [
      { code: "BFS", name: "Belfast International Airport", distanceKm: 50 }
    ],
    cityCenterInfo: { name: "Banbridge Town Centre", distanceKm: 2, recommendedRoute: "Follow official directions via the main A1 Belfast to Dublin road" },
    nearby: [],
    websiteUrl: "https://the-boulevard.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=The+Boulevard+Banbridge",
    appleMapsUrl: "http://maps.apple.com/?q=The+Boulevard+Banbridge",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Boulevard%20Banbridge"
  },
  {
    outletId: "the-galleria-outlet",
    name: "The Galleria Outlet Shopping Centre",
    slug: "the-galleria-outlet",
    countryId: "united-kingdom",
    cityId: "hatfield",
    address: "The Galleria Outlet Shopping Centre, Comet Way, Hatfield, Hertfordshire AL10 0XR, United Kingdom",
    latitude: 51.763,
    longitude: -0.2417,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 10:00 - 18:00; Sun 11:00 - 17:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Stores, restaurants and leisure venues under one roof",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Restaurants & Cafes", "Transport Info", "Accessibility", "Wi-Fi", "Baby Changing", "Amazon Lockers", "Post Office"],
    restaurants: ["Bite & Feast", "Burger King", "Caffè Nero", "Costa Coffee", "Nando's", "PizzaExpress", "Prezzo", "Sumac & Saffron", "The Real China", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 1.5,
    airportDistanceKm: 20,
    airports: [
      { code: "LTN", name: "London Luton Airport", distanceKm: 20 }
    ],
    cityCenterInfo: { name: "Hatfield Town Centre", distanceKm: 1.5, recommendedRoute: "Use A1(M) junction 3 or 4 and follow the A1001; use AL10 9TF for satnav parking access" },
    nearby: [],
    websiteUrl: "https://thegalleria.co.uk/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=The+Galleria+Outlet+Shopping+Centre+AL10+0XR",
    appleMapsUrl: "http://maps.apple.com/?q=The+Galleria+Outlet+Shopping+Centre+AL10+0XR",
    yandexMapsUrl: "https://yandex.com/maps/?text=The%20Galleria%20Outlet%20Shopping%20Centre%20AL10%200XR"
  },
  {
    outletId: "west-midlands-designer-outlet",
    name: "West Midlands Designer Outlet",
    slug: "west-midlands-designer-outlet",
    countryId: "united-kingdom",
    cityId: "birmingham",
    address: "Eastern Way, Cannock WS11 7JZ, United Kingdom",
    latitude: 52.6819,
    longitude: -2.015,
    openingHours: "Mon-Fri 10:00 - 20:00; Sat 09:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "Over 65 iconic brands",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards", "Changing Places", "SignLive"],
    restaurants: ["200 Degrees Coffee", "Doughnotts", "Five Guys", "Kouzina Greek", "Love Churros", "Meli Café & Patisserie", "Phata Phat", "Pizza Express", "Slim Chickens", "Starbucks", "Wagamama"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 30,
    airportDistanceKm: 45,
    airports: [
      {
        code: "BHX",
        name: "Birmingham Airport",
        distanceKm: 45
      }
    ],
    cityCenterInfo: { name: "Birmingham City Centre", distanceKm: 30, recommendedRoute: "30 minute drive from Birmingham City Centre per official outlet guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-west-midlands/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=West+Midlands+Designer+Outlet+Eastern+Way+Cannock+WS11+7JZ",
    appleMapsUrl: "http://maps.apple.com/?q=West+Midlands+Designer+Outlet+Eastern+Way+Cannock+WS11+7JZ",
    yandexMapsUrl: "https://yandex.com/maps/?text=West%20Midlands%20Designer%20Outlet%20Eastern%20Way%20Cannock%20WS11%207JZ"
  },
  {
    outletId: "york-designer-outlet",
    name: "York Designer Outlet",
    slug: "york-designer-outlet",
    countryId: "united-kingdom",
    cityId: "york",
    address: "St Nicholas Avenue, Fulford, York YO19 4TA, United Kingdom",
    latitude: 53.9227,
    longitude: -1.0786,
    openingHours: "Mon-Fri 09:30 - 20:00; Sat 09:00 - 20:00; Sun 10:00 - 18:00",
    heroImage: "",
    galleryImages: [],
    storesCountText: "100+ stores",
    rating: 4.5,
    reviewCount: 0,
    services: ["Parking", "Guest Services", "Restaurants & Cafes", "Transport Info", "Accessibility", "Gift Cards"],
    restaurants: ["200 Degrees Coffee", "Bagel Factory", "Brew'd", "Caffe Nero", "Caffe Valeria", "Chopstix", "Five Guys", "Krispy Kreme", "McDonald's", "Pizza Express", "Pret A Manger", "Shakamaka", "Slim Chickens", "Starbucks", "The Fisherman's Wife", "Wagamama", "YO!"],
    taxFreeAvailable: false,
    vatRate: 20,
    estimatedRefundRate: 0,
    minimumTaxFreeSpend: "Not available",
    taxFreeOperator: "UK VAT Retail Export Scheme withdrawn in Great Britain",
    taxFreeOfficeInfo: "Tourist VAT refunds for in-store purchases are generally not available in Great Britain. Check official UK rules and the outlet before planning any tax-free shopping.",
    cityCenterDistanceKm: 6,
    airportDistanceKm: 50,
    airports: [
      { code: "LBA", name: "Leeds Bradford Airport", distanceKm: 50 }
    ],
    cityCenterInfo: { name: "York City Centre", distanceKm: 6, recommendedRoute: "Approximately 15 minutes from York per official McArthurGlen plan-your-visit guidance" },
    nearby: [],
    websiteUrl: "https://www.mcarthurglen.com/en/outlets/uk/designer-outlet-york/",
    status: "active",
    googleMapsUrl: "https://maps.google.com/?q=York+Designer+Outlet",
    appleMapsUrl: "http://maps.apple.com/?q=York+Designer+Outlet",
    yandexMapsUrl: "https://yandex.com/maps/?text=York%20Designer%20Outlet"
  }
];
