export type OutletMediaSourceStatus =
  | "project-owned"
  | "licensed"
  | "public-domain"
  | "permission-granted"
  | "official-operator"
  | "unknown";

export type OutletMediaAssetRole = "hero" | "gallery";

export type OutletMediaAssetMetadata = {
  outletId: string;
  role: OutletMediaAssetRole;
  assetPath: string;
  sourceStatus: OutletMediaSourceStatus;
  sourceUrl?: string;
  credit?: string;
  license?: string;
  licenseUrl?: string;
  alt: string;
  notes?: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isOutletMediaSourceStatus(
  value: unknown,
): value is OutletMediaSourceStatus {
  return (
    value === "project-owned" ||
    value === "licensed" ||
    value === "public-domain" ||
    value === "permission-granted" ||
    value === "official-operator" ||
    value === "unknown"
  );
}

function isOutletMediaAssetRole(value: unknown): value is OutletMediaAssetRole {
  return value === "hero" || value === "gallery";
}

function isOutletMediaAssetMetadata(
  metadata: unknown,
): metadata is OutletMediaAssetMetadata {
  return (
    isRecord(metadata) &&
    typeof metadata.outletId === "string" &&
    isOutletMediaAssetRole(metadata.role) &&
    typeof metadata.assetPath === "string" &&
    isOutletMediaSourceStatus(metadata.sourceStatus) &&
    typeof metadata.alt === "string"
  );
}

// Phase 1C provenance inventory scaffold. Unknown-provenance assets are
// inventory-tracked here, but they are not production-cleared until source,
// credit, and license details are documented and validated.
const outletMediaMetadataRaw: readonly unknown[] = [
  {
    outletId: "la-vallee-village",
    role: "hero",
    assetPath: "assets/outlet-images/la-vallee/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Vall%C3%A9e_Village,_f%C3%A9vrier_2025_2.jpg",
    credit: "Artvill / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "La Vallée Village pedestrian shopping street in February 2025",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "la-vallee-village",
    role: "gallery",
    assetPath: "assets/outlet-images/la-vallee/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Vall%C3%A9e_Village,_f%C3%A9vrier_2025_1.jpg",
    credit: "Artvill / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "La Vallée Village storefronts and walkway in February 2025",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "la-vallee-village",
    role: "gallery",
    assetPath: "assets/outlet-images/la-vallee/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vall%C3%A9e_Village_(Serris)_(1).jpg",
    credit: "Gzen92 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "La Vallée Village at Serris exterior walkway",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "la-vallee-village",
    role: "gallery",
    assetPath: "assets/outlet-images/la-vallee/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:France_-_Val_d%27Europe_-_La_vall%C3%A9e.JPG",
    credit: "Pinpin / Wikimedia Commons",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5/",
    alt: "La Vallée outlet shopping village at Val d'Europe",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "bicester-village",
    role: "hero",
    assetPath: "assets/outlet-images/bicester/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bicester_outlet_village_-_panoramio.jpg",
    credit: "ianpudsey / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Bicester Village outlet street with storefronts and shoppers",
    notes:
      "For assets/outlet-images/bicester/hero.webp. Wikimedia source File:Bicester_outlet_village_-_panoramio.jpg is licensed CC BY 3.0; attribute ianpudsey / Wikimedia Commons, link the license, and indicate changes made during import.",
  },
  {
    outletId: "bicester-village",
    role: "gallery",
    assetPath: "assets/outlet-images/bicester/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bicester_Village_Shopping_-_geograph.org.uk_-_2517805.jpg",
    credit: "Ian Rob / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Bicester Village shopping arcade and storefronts",
    notes:
      "For assets/outlet-images/bicester/gallery1.webp. Wikimedia source File:Bicester_Village_Shopping_-_geograph.org.uk_-_2517805.jpg is licensed CC BY-SA 2.0; attribute Ian Rob / Geograph / Wikimedia Commons, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "serravalle-designer-outlet",
    role: "hero",
    assetPath: "assets/outlet-images/serravalle/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.mcarthurglen.com/en/outlets/it/serravalle-designer-outlet/",
    alt: "Official McArthurGlen Serravalle Designer Outlet image showing shoppers in an outdoor outlet street.",
  },
  {
    outletId: "serravalle-designer-outlet",
    role: "hero",
    assetPath: "assets/outlet-images/serravalle/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Serravalle_-_panoramio.jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Serravalle Designer Outlet entrance with storefronts and parked cars",
    notes:
      "For assets/outlet-images/serravalle/hero.webp. Wikimedia source File:Designer_Outlet_Serravalle_-_panoramio.jpg is licensed CC BY 3.0; attribute qwesy qwesy / Wikimedia Commons, link the license, and indicate changes made during import.",
  },
  {
    outletId: "serravalle-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/serravalle/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Serravalle_-_panoramio_(2).jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Serravalle Designer Outlet pedestrian street and shop façades",
    notes:
      "For assets/outlet-images/serravalle/gallery1.webp. Wikimedia source File:Designer_Outlet_Serravalle_-_panoramio_(2).jpg is licensed CC BY 3.0; attribute qwesy qwesy / Wikimedia Commons, link the license, and indicate changes made during import.",
  },
  {
    outletId: "designer-outlet-parndorf",
    role: "hero",
    assetPath: "assets/outlet-images/parndorf/hero.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Parndorf_Designer_Outlet_(1).jpg",
    credit: "Wizzard / Wikimedia Commons",
    license: "Public domain / PD-self",
    licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-self",
    alt: "Designer Outlet Parndorf exterior",
    notes:
      "Verified Wikimedia Commons public-domain / PD-self source; local WebP was imported from the source file.",
  },
  {
    outletId: "designer-outlet-parndorf",
    role: "gallery",
    assetPath: "assets/outlet-images/parndorf/gallery1.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Parndorf_Designer_Outlet_(3).jpg",
    credit: "Wizzard / Wikimedia Commons",
    license: "Public domain / PD-self",
    licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-self",
    alt: "Designer Outlet Parndorf storefronts",
    notes:
      "Verified Wikimedia Commons public-domain / PD-self source; local WebP was imported from the source file.",
  },
  {
    outletId: "fidenza-village",
    role: "hero",
    assetPath: "assets/outlet-images/fidenza/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fidenza_village_-_panoramio.jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Fidenza Village outlet exterior view hero",
    notes: "Exact Fidenza Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "fidenza-village",
    role: "gallery",
    assetPath: "assets/outlet-images/fidenza/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fidenza_village_-_panoramio_(1).jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Fidenza Village outlet exterior view gallery1",
    notes: "Exact Fidenza Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "fidenza-village",
    role: "gallery",
    assetPath: "assets/outlet-images/fidenza/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fidenza_village_-_panoramio_(2).jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Fidenza Village outlet exterior view gallery2",
    notes: "Exact Fidenza Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "fidenza-village",
    role: "gallery",
    assetPath: "assets/outlet-images/fidenza/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fidenza_village_-_panoramio_(3).jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Fidenza Village outlet exterior view gallery3",
    notes: "Exact Fidenza Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "ingolstadt-village",
    role: "hero",
    assetPath: "assets/outlet-images/ingolstadt/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FOC_Ingolstadt_Village_Stores_2013.jpg",
    credit: "Henk Bekker / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Factory outlet stores at Ingolstadt Village in Ingolstadt, Germany",
    notes: "Exact Wikimedia Commons source; file description identifies factory outlet stores at Ingolstadt Village. Flickr-origin file was reviewed by FlickreviewR 2 as CC BY-SA 2.0. No downloadUrl is included so the importer can auto-resolve the original.",
  },
  {
    outletId: "ingolstadt-village",
    role: "gallery",
    assetPath: "assets/outlet-images/ingolstadt/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:GER_Ingolstadt_Village_001.jpg",
    credit: "-wuppertaler / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "View inside Ingolstadt Village in Ingolstadt, Germany",
    notes: "Exact Wikimedia Commons source from the Ingolstadt Village category; own-work file licensed CC BY-SA 4.0. Distinct source from the selected hero and gallery slots.",
  },
  {
    outletId: "ingolstadt-village",
    role: "gallery",
    assetPath: "assets/outlet-images/ingolstadt/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FOC_Ingolstadt_Village_Restaurants_2013.jpg",
    credit: "Henk Bekker / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Restaurants at Ingolstadt Village outlet center in Ingolstadt, Germany",
    notes: "Exact Wikimedia Commons source; file description identifies restaurants at Ingolstadt Village factory outlet center. Flickr-origin file was reviewed by FlickreviewR 2 as CC BY-SA 2.0.",
  },
  {
    outletId: "ingolstadt-village",
    role: "gallery",
    assetPath: "assets/outlet-images/ingolstadt/gallery3.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FOC_Ingolstadtvillage.jpg",
    credit: "Marom / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags/General_public_domain",
    alt: "Factory Outlet Center Ingolstadt Village shortly after opening",
    notes: "Exact Wikimedia Commons source; uploader/copyright holder released the work into the public domain. Distinct older exterior outlet-center source.",
  },
  {
    outletId: "wertheim-village",
    role: "hero",
    assetPath: "assets/outlet-images/wertheim/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023-06-09_Wertheim_Village_01.jpg",
    credit: "Triplec85 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Wertheim Village entrance and pedestrian area",
    notes: "Exact Wertheim Village source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "wertheim-village",
    role: "gallery",
    assetPath: "assets/outlet-images/wertheim/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023-06-09_Wertheim_Village_05.jpg",
    credit: "Triplec85 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Wertheim Village storefronts and shopping street",
    notes: "Exact Wertheim Village source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "wertheim-village",
    role: "gallery",
    assetPath: "assets/outlet-images/wertheim/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wertheim_Village_-_panoramio_(4).jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Wertheim Village exterior shopping area",
    notes: "Exact Wertheim Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "wertheim-village",
    role: "gallery",
    assetPath: "assets/outlet-images/wertheim/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wertheim_Village_-_panoramio_(6).jpg",
    credit: "qwesy qwesy / Panoramio / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Wertheim Village shopping street with storefronts",
    notes: "Exact Wertheim Village source from Wikimedia Commons/Panoramio; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "the-mall-firenze",
    role: "hero",
    assetPath: "assets/outlet-images/the-mall-firenze/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_mall_outlet_01.jpg",
    credit: "Sailko / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "The Mall Firenze outlet building and pedestrian area",
    notes: "Exact The Mall Outlets (Reggello/The Mall Firenze) source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "the-mall-firenze",
    role: "gallery",
    assetPath: "assets/outlet-images/the-mall-firenze/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_mall_outlet_02.jpg",
    credit: "Sailko / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "The Mall Firenze outlet walkway and storefronts",
    notes: "Exact The Mall Outlets (Reggello/The Mall Firenze) source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "the-mall-firenze",
    role: "gallery",
    assetPath: "assets/outlet-images/the-mall-firenze/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_mall_outlet_03.jpg",
    credit: "Sailko / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "The Mall Firenze outlet exterior and landscaped walkway",
    notes: "Exact The Mall Outlets (Reggello/The Mall Firenze) source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "the-mall-firenze",
    role: "gallery",
    assetPath: "assets/outlet-images/the-mall-firenze/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E8%BF%AA%E5%A5%A7%E8%B3%A3%E5%A0%B4_Dior_Outlet_-_panoramio.jpg",
    credit: "Wing1990hk / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Dior Outlet storefront at The Mall Firenze",
    notes: "Exact The Mall Outlets (Reggello/The Mall Firenze) source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "barberino",
    role: "hero",
    assetPath: "assets/outlet-images/barberino/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.barberinooutlet.com/en/sales/",
    alt: "Official Barberino Designer Outlet image showing shoppers and outdoor outlet seating.",
  },
  {
    outletId: "barberino",
    role: "hero",
    assetPath: "assets/outlet-images/barberino/hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.barberinooutlet.com/en/sales/",
    alt: "Official Barberino Designer Outlet summer sale image with outlet shopping bags and outdoor seating.",
  },
  {
    outletId: "barberino",
    role: "gallery",
    assetPath: "assets/outlet-images/barberino/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:GEST_1007_piazza_Muratori_Barberino_Outlet_20240426.jpg",
    credit: "Sailko / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Piazza Muratori at Barberino Designer Outlet",
    notes: "Exact Barberino Designer Outlet source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "noventa",
    role: "hero",
    assetPath: "assets/outlet-images/noventa/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-noventa-di-piave/",
    alt: "Official McArthurGlen Noventa di Piave Designer Outlet image showing shoppers walking through the outlet village.",
  },
  {
    outletId: "noventa",
    role: "hero",
    assetPath: "assets/outlet-images/noventa/hero.webp",
    sourceStatus: "unknown",
    alt: "Noventa di Piave Designer Outlet hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "noventa",
    role: "gallery",
    assetPath: "assets/outlet-images/noventa/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Noventa di Piave Designer Outlet gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "noventa",
    role: "gallery",
    assetPath: "assets/outlet-images/noventa/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Noventa di Piave Designer Outlet gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "noventa",
    role: "gallery",
    assetPath: "assets/outlet-images/noventa/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Noventa di Piave Designer Outlet gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "outletcity-metzingen",
    role: "hero",
    assetPath: "assets/outlet-images/metzingen/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outletcity,_Metzingen.jpg",
    credit: "MirwaldM / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Outletcity Metzingen storefronts on an urban shopping street",
    notes:
      "For assets/outlet-images/metzingen/hero.webp. Wikimedia source File:Outletcity,_Metzingen.jpg is licensed CC BY-SA 4.0; attribute MirwaldM / Wikimedia Commons, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "outletcity-metzingen",
    role: "gallery",
    assetPath: "assets/outlet-images/metzingen/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outletcity_Metzingen_IMG_4508.jpg",
    credit: "Tresckow / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Outletcity Metzingen shopping street with modern façades",
    notes:
      "For assets/outlet-images/metzingen/gallery1.webp. Wikimedia source File:Outletcity_Metzingen_IMG_4508.jpg is licensed CC BY-SA 4.0; attribute Tresckow / Wikimedia Commons, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "designer-outlet-troyes",
    role: "hero",
    assetPath: "assets/outlet-images/troyes/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Village_Marques_McArthurGlen_-_Pont-Sainte-Marie_(FR10)_-_2026-02-27_-_1.jpg",
    credit: "Chabe01 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "McArthurGlen Troyes outlet village exterior view 1",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-troyes",
    role: "gallery",
    assetPath: "assets/outlet-images/troyes/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Village_Marques_McArthurGlen_-_Pont-Sainte-Marie_(FR10)_-_2026-02-27_-_2.jpg",
    credit: "Chabe01 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "McArthurGlen Troyes outlet village exterior view 2",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-troyes",
    role: "gallery",
    assetPath: "assets/outlet-images/troyes/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Village_Marques_McArthurGlen_-_Pont-Sainte-Marie_(FR10)_-_2026-02-27_-_3.jpg",
    credit: "Chabe01 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "McArthurGlen Troyes outlet village exterior view 3",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-troyes",
    role: "gallery",
    assetPath: "assets/outlet-images/troyes/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Village_Marques_McArthurGlen_-_Pont-Sainte-Marie_(FR10)_-_2026-02-27_-_4.jpg",
    credit: "Chabe01 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "McArthurGlen Troyes outlet village exterior view 4",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-provence",
    role: "hero",
    assetPath: "assets/outlet-images/provence/hero.webp",
    sourceStatus: "unknown",
    alt: "McArthurGlen Designer Outlet Provence hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-provence",
    role: "gallery",
    assetPath: "assets/outlet-images/provence/gallery1.webp",
    sourceStatus: "unknown",
    alt: "McArthurGlen Designer Outlet Provence gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-provence",
    role: "gallery",
    assetPath: "assets/outlet-images/provence/gallery2.webp",
    sourceStatus: "unknown",
    alt: "McArthurGlen Designer Outlet Provence gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-provence",
    role: "gallery",
    assetPath: "assets/outlet-images/provence/gallery3.webp",
    sourceStatus: "unknown",
    alt: "McArthurGlen Designer Outlet Provence gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-roermond",
    role: "hero",
    assetPath: "assets/outlet-images/roermond/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:McArthur_Glen_Designer_Outlet_Roermond.jpeg",
    credit: "Dammit / Wikimedia Commons",
    license: "CC BY-SA 2.5 NL",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5/nl/",
    alt: "Designer Outlet Roermond entrance and shopping street",
    notes:
      "For assets/outlet-images/roermond/hero.webp. Wikimedia source File:McArthur_Glen_Designer_Outlet_Roermond.jpeg is licensed CC BY-SA 2.5 NL; attribute Dammit / Wikimedia Commons, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "designer-outlet-roermond",
    role: "gallery",
    assetPath: "assets/outlet-images/roermond/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Roermond_-_panoramio_(5).jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlet Roermond storefronts along a pedestrian walkway",
    notes:
      "For assets/outlet-images/roermond/gallery1.webp. Wikimedia source File:Designer_Outlet_Roermond_-_panoramio_(5).jpg is licensed CC BY 3.0; attribute qwesy qwesy / Wikimedia Commons, link the license, and indicate changes made during import.",
  },
  {
    outletId: "castel-romano",
    role: "hero",
    assetPath: "assets/outlet-images/castel-romano/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-castel-romano/",
    alt: "Official McArthurGlen Castel Romano Designer Outlet image showing shoppers walking through an outdoor outlet street.",
  },
  {
    outletId: "castel-romano",
    role: "hero",
    assetPath: "assets/outlet-images/castel-romano/hero.webp",
    sourceStatus: "unknown",
    alt: "Castel Romano Designer Outlet hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "castel-romano",
    role: "gallery",
    assetPath: "assets/outlet-images/castel-romano/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Castel Romano Designer Outlet gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "castel-romano",
    role: "gallery",
    assetPath: "assets/outlet-images/castel-romano/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Castel Romano Designer Outlet gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "castel-romano",
    role: "gallery",
    assetPath: "assets/outlet-images/castel-romano/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Castel Romano Designer Outlet gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "cheshire-oaks",
    role: "hero",
    assetPath: "assets/outlet-images/cheshire-oaks/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheshire_Oaks_-_geograph.org.uk_-_199420.jpg",
    credit: "Eirian Evans / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Cheshire Oaks Designer Outlet exterior walkway and storefronts",
    notes: "Exact Cheshire Oaks Designer Outlet source from Wikimedia Commons/Geograph; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "cheshire-oaks",
    role: "gallery",
    assetPath: "assets/outlet-images/cheshire-oaks/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheshire_Oaks_-_geograph.org.uk_-_829370.jpg",
    credit: "Stephen McKay / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Cheshire Oaks Designer Outlet shopping street with visitors",
    notes: "Exact Cheshire Oaks Designer Outlet source from Wikimedia Commons/Geograph; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "cheshire-oaks",
    role: "gallery",
    assetPath: "assets/outlet-images/cheshire-oaks/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheshire_Oaks_Shopping_Centre_-_geograph.org.uk_-_652712.jpg",
    credit: "Steve Daniels / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Cheshire Oaks Designer Outlet storefronts along the shopping centre",
    notes: "Exact Cheshire Oaks Designer Outlet source from Wikimedia Commons/Geograph; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "cheshire-oaks",
    role: "gallery",
    assetPath: "assets/outlet-images/cheshire-oaks/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Three_units_at_Cheshire_Oaks_Shopping_Centre_-_geograph.org.uk_-_1248609.jpg",
    credit: "David Dixon / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Three retail units at Cheshire Oaks Designer Outlet",
    notes: "Exact Cheshire Oaks Designer Outlet source from Wikimedia Commons/Geograph; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-berlin",
    role: "hero",
    assetPath: "assets/outlet-images/berlin/hero.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Berlin hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-berlin",
    role: "gallery",
    assetPath: "assets/outlet-images/berlin/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Berlin gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-berlin",
    role: "gallery",
    assetPath: "assets/outlet-images/berlin/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Berlin gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-berlin",
    role: "gallery",
    assetPath: "assets/outlet-images/berlin/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Berlin gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-neumunster",
    role: "hero",
    assetPath: "assets/outlet-images/neumunster/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:DOC_Neum%C3%BCnster_Eingang.JPG",
    credit: "Wusel007 / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Designer Outlet Neumünster main entrance",
    notes: "Exact Designer Outlet Center Neumünster source from Wikimedia Commons; selected CC BY-SA 3.0 from available licenses; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-neumunster",
    role: "gallery",
    assetPath: "assets/outlet-images/neumunster/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:DOC_Neum%C3%BCnster1.JPG",
    credit: "Wusel007 / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Designer Outlet Neumünster shopping street and storefronts",
    notes: "Exact Designer Outlet Center Neumünster source from Wikimedia Commons; selected CC BY-SA 3.0 from available licenses; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-neumunster",
    role: "gallery",
    assetPath: "assets/outlet-images/neumunster/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:DOC_Neum%C3%BCnster2.JPG",
    credit: "Wusel007 / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Designer Outlet Neumünster storefronts and pedestrian area",
    notes: "Exact Designer Outlet Center Neumünster source from Wikimedia Commons; selected CC BY-SA 3.0 from available licenses; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-neumunster",
    role: "gallery",
    assetPath: "assets/outlet-images/neumunster/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:McArthurGlen_Designer_Outlet._Neum%C3%BCnster._Neumuenster._Shopping.jpg",
    credit: "Paasikivi / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "McArthurGlen Designer Outlet Neumünster shopping area",
    notes: "Exact Designer Outlet Neumünster source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "designer-outlet-roosendaal",
    role: "hero",
    assetPath: "assets/outlet-images/roosendaal/hero.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Roosendaal hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-roosendaal",
    role: "gallery",
    assetPath: "assets/outlet-images/roosendaal/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Roosendaal gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-roosendaal",
    role: "gallery",
    assetPath: "assets/outlet-images/roosendaal/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Roosendaal gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-roosendaal",
    role: "gallery",
    assetPath: "assets/outlet-images/roosendaal/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Roosendaal gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "la-reggia",
    role: "hero",
    assetPath: "assets/outlet-images/la-reggia/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.mcarthurglen.com/en/outlets/it/designer-outlet-la-reggia/",
    alt: "Official McArthurGlen La Reggia Designer Outlet image showing shoppers in an outdoor outlet setting.",
  },
  {
    outletId: "la-reggia",
    role: "hero",
    assetPath: "assets/outlet-images/la-reggia/hero.webp",
    sourceStatus: "unknown",
    alt: "La Reggia Designer Outlet hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "la-reggia",
    role: "gallery",
    assetPath: "assets/outlet-images/la-reggia/gallery1.webp",
    sourceStatus: "unknown",
    alt: "La Reggia Designer Outlet gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "la-reggia",
    role: "gallery",
    assetPath: "assets/outlet-images/la-reggia/gallery2.webp",
    sourceStatus: "unknown",
    alt: "La Reggia Designer Outlet gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "la-reggia",
    role: "gallery",
    assetPath: "assets/outlet-images/la-reggia/gallery3.webp",
    sourceStatus: "unknown",
    alt: "La Reggia Designer Outlet gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-malaga",
    role: "hero",
    assetPath: "assets/outlet-images/malaga/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fuego,_Nic_Fiddian_Green.jpg",
    credit: "Jl FilpoC / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Fuego sculpture at McArthurGlen Designer Outlet Málaga.",
    notes: "Exact outlet image from Wikimedia Commons; used under documented CC BY-SA 4.0 license. Source page describes Fuego by Nic Fiddian Green as a 2022 sculpture for McArthurGlen Designer Outlet, Málaga. Hero-only candidate under the revised one exact safe source threshold.",
  },
  {
    outletId: "designer-outlet-malaga",
    role: "gallery",
    assetPath: "assets/outlet-images/malaga/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Málaga gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-malaga",
    role: "gallery",
    assetPath: "assets/outlet-images/malaga/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Málaga gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "designer-outlet-malaga",
    role: "gallery",
    assetPath: "assets/outlet-images/malaga/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Designer Outlet Málaga gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "montabaur-the-style-outlets",
    role: "hero",
    assetPath: "assets/outlet-images/montabaur/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fashion-Outlet-Center_in_Montabaur.jpg",
    credit: "Christian Pulfrich / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Fashion Outlet Center in Montabaur.",
    notes: "Exact outlet image from Wikimedia Commons; used under documented CC BY-SA 4.0 license. Source page identifies Fashion Outlet Center in Montabaur / Montabaur The Style Outlets. Hero-only candidate under the revised one exact safe source threshold.",
  },
  {
    outletId: "montabaur-the-style-outlets",
    role: "gallery",
    assetPath: "assets/outlet-images/montabaur/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Montabaur The Style Outlets gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "montabaur-the-style-outlets",
    role: "gallery",
    assetPath: "assets/outlet-images/montabaur/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Montabaur The Style Outlets gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "montabaur-the-style-outlets",
    role: "gallery",
    assetPath: "assets/outlet-images/montabaur/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Montabaur The Style Outlets gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    role: "hero",
    assetPath: "assets/outlet-images/zweibrucken/hero.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Center_Zweibr%C3%BCcken_pic1.JPG",
    credit: "Alf van Beem / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
    alt: "Zweibrücken Fashion Outlet exterior shopping street",
    notes: "Exact Zweibrücken Fashion Outlet source from Wikimedia Commons; public-domain release by the copyright holder verified on the Wikimedia Commons file page.",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/zweibrucken/gallery1.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Center_Zweibr%C3%BCcken_pic2.JPG",
    credit: "Alf van Beem / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
    alt: "Zweibrücken Fashion Outlet pedestrian area and storefronts",
    notes: "Exact Zweibrücken Fashion Outlet source from Wikimedia Commons; public-domain release by the copyright holder verified on the Wikimedia Commons file page.",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/zweibrucken/gallery2.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Center_Zweibr%C3%BCcken_pic3.JPG",
    credit: "Alf van Beem / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
    alt: "Zweibrücken Fashion Outlet shopping promenade",
    notes: "Exact Zweibrücken Fashion Outlet source from Wikimedia Commons; public-domain release by the copyright holder verified on the Wikimedia Commons file page.",
  },
  {
    outletId: "zweibrucken-fashion-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/zweibrucken/gallery3.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Center_Zweibr%C3%BCcken_pic4.JPG",
    credit: "Alf van Beem / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
    alt: "Zweibrücken Fashion Outlet storefront row",
    notes: "Exact Zweibrücken Fashion Outlet source from Wikimedia Commons; public-domain release by the copyright holder verified on the Wikimedia Commons file page.",
  },
  {
    outletId: "maasmechelen-village",
    role: "hero",
    assetPath: "assets/outlet-images/maasmechelen/hero.webp",
    sourceStatus: "unknown",
    alt: "Maasmechelen Village hero image",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "maasmechelen-village",
    role: "gallery",
    assetPath: "assets/outlet-images/maasmechelen/gallery1.webp",
    sourceStatus: "unknown",
    alt: "Maasmechelen Village gallery image 1",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "maasmechelen-village",
    role: "gallery",
    assetPath: "assets/outlet-images/maasmechelen/gallery2.webp",
    sourceStatus: "unknown",
    alt: "Maasmechelen Village gallery image 2",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "maasmechelen-village",
    role: "gallery",
    assetPath: "assets/outlet-images/maasmechelen/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Maasmechelen Village gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "las-rozas-village",
    role: "hero",
    assetPath: "assets/outlet-images/las-rozas/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Restaurante_-_Las_Rozas_Village_-_Chic_outlet_shopping_(6926664573).jpg",
    credit: "jacilluch / Flickr / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Restaurant terrace at Las Rozas Village",
    notes: "Exact Las Rozas Village source from Wikimedia Commons/Flickr; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "las-rozas-village",
    role: "gallery",
    assetPath: "assets/outlet-images/las-rozas/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alumbrado_de_Navidad.jpg",
    credit: "Dcarolina.2000 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Christmas lights at Las Rozas Village",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "las-rozas-village",
    role: "gallery",
    assetPath: "assets/outlet-images/las-rozas/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Venado_Las_Rozas_Village.jpg",
    credit: "Dcarolina.2000 / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Holiday deer decoration at Las Rozas Village",
    notes: "Exact source from Wikimedia Commons; preserve attribution, link license, indicate import crop/resize changes, and comply with share-alike requirements.",
  },
  {
    outletId: "las-rozas-village",
    role: "gallery",
    assetPath: "assets/outlet-images/las-rozas/gallery3.webp",
    sourceStatus: "unknown",
    alt: "Las Rozas Village gallery image 3",
    notes:
      "Inventory-tracked local asset with unknown provenance; not production-cleared until source, credit, and license are documented.",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    role: "hero",
    assetPath: "assets/outlet-images/bad-munstereifel/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:City_Outlet_Shops,_Trierer_Stra%C3%9Fe,_Bad_M%C3%BCnstereifel-2442.jpg",
    credit: "Raimond Spekking / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "City Outlet shops on Trierer Straße in Bad Münstereifel",
    notes: "Exact Wikimedia Commons source; title and image metadata identify City Outlet shops on Trierer Straße, Bad Münstereifel. Distinct from the selected gallery sources.",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    role: "gallery",
    assetPath: "assets/outlet-images/bad-munstereifel/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bad_M%C3%BCnstereifel_City_Outlet.jpg",
    credit: "Zairon / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "City Outlet storefronts in Bad Münstereifel",
    notes: "Exact Wikimedia Commons source from Category:City Outlet Bad Münstereifel; own-work Commons file licensed CC BY-SA 4.0.",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    role: "gallery",
    assetPath: "assets/outlet-images/bad-munstereifel/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Robert_Ley_Outlet,_Trierer_Stra%C3%9Fe_1,_Bad_M%C3%BCnstereifel._-9886.jpg",
    credit: "Raimond Spekking / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Robert Ley Outlet at Trierer Straße 1 in City Outlet Bad Münstereifel",
    notes: "Exact Wikimedia Commons source; title and metadata identify Robert Ley Outlet at Trierer Straße 1, Bad Münstereifel, within the City Outlet Commons category.",
  },
  {
    outletId: "city-outlet-bad-munstereifel",
    role: "gallery",
    assetPath: "assets/outlet-images/bad-munstereifel/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Erweiterungsbau_City_Outlet,_Trierer_Stra%C3%9Fe_31-39,_Bad_M%C3%BCnstereifel-4401.jpg",
    credit: "Raimond Spekking / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "City Outlet extension building on Trierer Straße 31-39 in Bad Münstereifel",
    notes: "Exact Wikimedia Commons source; title and metadata identify the City Outlet extension building at Trierer Straße 31-39, Bad Münstereifel. Distinct from other Bad Münstereifel selected sources.",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    role: "hero",
    assetPath: "assets/outlet-images/wolfsburg/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlets_Wolfsburg_8021.jpg",
    credit: "Gerd Fahrenhorst / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlets Wolfsburg exterior shopping street",
    notes: "Exact Designer Outlets Wolfsburg source from Wikimedia Commons; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    role: "gallery",
    assetPath: "assets/outlet-images/wolfsburg/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlets_Wolfsburg_8037.jpg",
    credit: "Gerd Fahrenhorst / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlets Wolfsburg pedestrian shopping area",
    notes: "Exact Designer Outlets Wolfsburg source from Wikimedia Commons; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    role: "gallery",
    assetPath: "assets/outlet-images/wolfsburg/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlets_Wolfsburg_8038.jpg",
    credit: "Gerd Fahrenhorst / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlets Wolfsburg storefronts",
    notes: "Exact Designer Outlets Wolfsburg source from Wikimedia Commons; preserve attribution, link license, and indicate import crop/resize changes.",
  },
  {
    outletId: "designer-outlets-wolfsburg",
    role: "gallery",
    assetPath: "assets/outlet-images/wolfsburg/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:5357_Wolfsburg.JPG",
    credit: "Gerd Fahrenhorst / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlets Wolfsburg building exterior",
    notes: "Exact Designer Outlets Wolfsburg source from Wikimedia Commons; preserve attribution, link license, and indicate import crop/resize changes.",
  },,
  {
    outletId: "designer-outlet-parndorf",
    role: "gallery",
    assetPath: "assets/outlet-images/parndorf/gallery2.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Parndorf_Designer_Outlet_(2).jpg",
    credit: "Wizzard / Wikimedia Commons",
    license: "Public domain / PD-self",
    licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-self",
    alt: "Designer Outlet Parndorf storefronts and parking area",
    notes: "Wikimedia Commons file page identifies the source as own work by Wizzard and states all rights released / public domain via PD-self. Use for assets/outlet-images/parndorf/gallery2.webp; indicate changes made during import.",
  },
  {
    outletId: "bicester-village",
    role: "gallery",
    assetPath: "assets/outlet-images/bicester/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bicester_Village_-_geograph.org.uk_-_1828514.jpg",
    credit: "Des Blenkinsopp / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Bicester Village shopping center exterior",
    notes: "Wikimedia Commons file page identifies the source as Geograph Britain and Ireland by Des Blenkinsopp and licenses it under CC BY-SA 2.0. Use for assets/outlet-images/bicester/gallery2.webp; attribute the author, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "bicester-village",
    role: "gallery",
    assetPath: "assets/outlet-images/bicester/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Coccinelle_and_Prada,_Bicester_Village_-_geograph.org.uk_-_4562347.jpg",
    credit: "Jaggery / Geograph / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Coccinelle and Prada storefronts at Bicester Village",
    notes: "Wikimedia Commons file page identifies the exact Bicester Village storefront source and licenses it under CC BY-SA 2.0 with attribution to Jaggery. Use for assets/outlet-images/bicester/gallery3.webp; attribute the author, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "serravalle-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/serravalle/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Serravalle_-_panoramio_(1).jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Serravalle Designer Outlet shopping street and storefronts",
    notes: "Wikimedia Commons file page identifies Designer Outlet Serravalle as the subject and licenses the qwesy qwesy Panoramio source under CC BY 3.0. Use for assets/outlet-images/serravalle/gallery2.webp; attribute the author, link the license, and indicate changes made during import.",
  },
  {
    outletId: "serravalle-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/serravalle/gallery3.webp",
    sourceStatus: "public-domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Serravalle.JPG",
    credit: "Andre86 / Wikimedia Commons",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Copyright_tags/General_public_domain",
    alt: "Serravalle Designer Outlet viewed from Monte Spineto",
    notes: "Wikimedia Commons file page describes the outlet at Serravalle Scrivia viewed from Monte Spineto, identifies the source as own work by Andre86, and records permission as public domain. Use for assets/outlet-images/serravalle/gallery3.webp; indicate changes made during import.",
  },
  {
    outletId: "designer-outlet-roermond",
    role: "gallery",
    assetPath: "assets/outlet-images/roermond/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Roermond_-_panoramio_(3).jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlet Roermond pedestrian street",
    notes: "Wikimedia Commons file page identifies Designer Outlet Roermond as the subject and licenses the qwesy qwesy Panoramio source under CC BY 3.0. Use for assets/outlet-images/roermond/gallery2.webp; attribute the author, link the license, and indicate changes made during import.",
  },
  {
    outletId: "designer-outlet-roermond",
    role: "gallery",
    assetPath: "assets/outlet-images/roermond/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Designer_Outlet_Roermond_-_panoramio_(2).jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlet Roermond storefronts and walkway",
    notes: "Wikimedia Commons file page identifies Designer Outlet Roermond as the subject and licenses the qwesy qwesy Panoramio source under CC BY 3.0. Use for assets/outlet-images/roermond/gallery3.webp; attribute the author, link the license, and indicate changes made during import.",
  },
  {
    outletId: "outletcity-metzingen",
    role: "gallery",
    assetPath: "assets/outlet-images/metzingen/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outletcity_Metzingen_IMG_4511.jpg",
    credit: "Tresckow / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Outletcity Metzingen storefronts in February 2020",
    notes: "Wikimedia Commons file page identifies Outletcity Metzingen as the subject, source as own work by Tresckow, and licenses it under CC BY-SA 4.0. Use for assets/outlet-images/metzingen/gallery2.webp; attribute the author, link the license, indicate changes made during import, and preserve share-alike requirements.",
  },
  {
    outletId: "outletcity-metzingen",
    role: "gallery",
    assetPath: "assets/outlet-images/metzingen/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:OUTLETCITY_METZINGEN_-_panoramio.jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Outletcity Metzingen shopping street",
    notes: "Wikimedia Commons file page identifies OUTLETCITY METZINGEN as the subject and licenses the qwesy qwesy Panoramio source under CC BY 3.0. Use for assets/outlet-images/metzingen/gallery3.webp; attribute the author, link the license, and indicate changes made during import.",
  },
  {
    outletId: "designer-outlet-parndorf",
    role: "gallery",
    assetPath: "assets/outlet-images/parndorf/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Outlet_Parndorf_-_panoramio.jpg",
    credit: "qwesy qwesy / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "Designer Outlet Parndorf exterior with outlet storefronts and walkways",
    notes: "Wikimedia Commons file page describes Outlet Parndorf, places the file in Category:Outletcenter Parndorf, identifies the author as qwesy qwesy, and records the reviewed Panoramio source as licensed under CC BY 3.0. Use for assets/outlet-images/parndorf/gallery3.webp; attribute the author, link the license, and indicate changes made during import.",
  },
  {
    outletId: "sicilia-outlet-village",
    role: "hero",
    assetPath: "assets/outlet-images/sicilia-outlet-village/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sicilia_outlet_village,_Agira,_Province_of_Enna,_Sicily,_Italy_-_panoramio.jpg",
    credit: "trolvag / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Sicilia Outlet Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Sicilia Outlet Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "sicilia-outlet-village",
    role: "gallery",
    assetPath: "assets/outlet-images/sicilia-outlet-village/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sicilia_outlet_village_-_panoramio_(1).jpg",
    credit: "trolvag / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Sicilia Outlet Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Sicilia Outlet Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "sicilia-outlet-village",
    role: "gallery",
    assetPath: "assets/outlet-images/sicilia-outlet-village/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sicilia_outlet_village_-_panoramio_(2).jpg",
    credit: "trolvag / Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    alt: "Sicilia Outlet Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Sicilia Outlet Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "sicilia-outlet-village",
    role: "gallery",
    assetPath: "assets/outlet-images/sicilia-outlet-village/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sicilia_Outlet_Village_2025-07-03_001.jpg",
    credit: "Antonino Faro / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Sicilia Outlet Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Sicilia Outlet Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "la-roca-village",
    role: "hero",
    assetPath: "assets/outlet-images/la-roca-village/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Roca_Village_Chic_Outlet_Shopping_(15275455890).jpg",
    credit: "Jorge Franganillo / Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    alt: "La Roca Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies La Roca Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "la-roca-village",
    role: "gallery",
    assetPath: "assets/outlet-images/la-roca-village/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Roca_Village_-_panoramio.jpg",
    credit: "Jorge Franganillo / Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    alt: "La Roca Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies La Roca Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "ashford-designer-outlet",
    role: "hero",
    assetPath: "assets/outlet-images/ashford-designer-outlet/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ashford_Designer_Outlet_-_geograph.org.uk_-_5775452.jpg",
    credit: "N Chadwick / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Ashford Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Ashford Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "ashford-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/ashford-designer-outlet/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ashford_Designer_Outlet_-_geograph.org.uk_-_5865160.jpg",
    credit: "PAUL FARMER / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Ashford Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Ashford Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "ashford-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/ashford-designer-outlet/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_to_Ashford_Designer_Outlet_geograph-2491591-by-David-Anstiss.jpg",
    credit: "David Anstiss / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Ashford Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Ashford Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "ashford-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/ashford-designer-outlet/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ashford_Designer_Outlet_and_railway,_aerial_2017_-_geograph.org.uk_-_5534479.jpg",
    credit: "Oast House Archive / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Ashford Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Ashford Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "clarks-village",
    role: "hero",
    assetPath: "assets/outlet-images/clarks-village/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Clarks_Village_shopping_outlet_2014.jpg",
    credit: "Lucychg / Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    alt: "Clarks Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Clarks Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "clarks-village",
    role: "gallery",
    assetPath: "assets/outlet-images/clarks-village/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Clarks_Village_Outlet_Shopping_-_geograph.org.uk_-_32757.jpg",
    credit: "Penny Mayes / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Clarks Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Clarks Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "clarks-village",
    role: "gallery",
    assetPath: "assets/outlet-images/clarks-village/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Clarks_Village_Street.jpg",
    credit: "Penny Mayes / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Clarks Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Clarks Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "clarks-village",
    role: "gallery",
    assetPath: "assets/outlet-images/clarks-village/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Shops_in_Clarks_Village,_Street_-_geograph.org.uk_-_1178910.jpg",
    credit: "Ken Grainger / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Clarks Village exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Clarks Village or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "gunwharf-quays",
    role: "hero",
    assetPath: "assets/outlet-images/gunwharf-quays/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gunwharf_Quays_East_Plaza_1.jpg",
    credit: "Unisouth / Wikimedia Commons",
    license: "GFDL",
    licenseUrl: "https://www.gnu.org/copyleft/fdl.html",
    alt: "Gunwharf Quays exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Gunwharf Quays or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "gunwharf-quays",
    role: "gallery",
    assetPath: "assets/outlet-images/gunwharf-quays/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Portsmouth_,_Gunwharf_Quays_Shopping_Precinct_-_geograph.org.uk_-_1990319.jpg",
    credit: "Lewis Clarke / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Gunwharf Quays exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Gunwharf Quays or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "gunwharf-quays",
    role: "gallery",
    assetPath: "assets/outlet-images/gunwharf-quays/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Strada_at_Gunwharf_Quays_-_geograph.org.uk_-_1657432.jpg",
    credit: "Curtis Bateman / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Gunwharf Quays exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Gunwharf Quays or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "gunwharf-quays",
    role: "gallery",
    assetPath: "assets/outlet-images/gunwharf-quays/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gunwharf_Quays,_Portsmouth_-_geograph.org.uk_-_1108408.jpg",
    credit: "Colin Smith / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Gunwharf Quays exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Gunwharf Quays or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "swindon-designer-outlet",
    role: "hero",
    assetPath: "assets/outlet-images/swindon-designer-outlet/hero.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Swindon_Designer_Outlet,_Swindon_(16)_-_geograph.org.uk_-_446348.jpg",
    credit: "Brian Robert Marshall / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Swindon Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Swindon Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "swindon-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/swindon-designer-outlet/gallery1.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Swindon_Designer_Outlet,_Swindon_(5)_-_geograph.org.uk_-_446190.jpg",
    credit: "Brian Robert Marshall / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Swindon Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Swindon Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "swindon-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/swindon-designer-outlet/gallery2.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Swindon_Designer_Outlet,_Swindon_(13)_-_geograph.org.uk_-_446243.jpg",
    credit: "Brian Robert Marshall / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Swindon Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Swindon Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "swindon-designer-outlet",
    role: "gallery",
    assetPath: "assets/outlet-images/swindon-designer-outlet/gallery3.webp",
    sourceStatus: "licensed",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_to_Swindon_Designer_Outlet,_Swindon_-_geograph.org.uk_-_814452.jpg",
    credit: "Brian Robert Marshall / Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    alt: "Swindon Designer Outlet exact outlet view",
    notes: "Exact Wikimedia Commons/Geograph-on-Commons source found during corrected Media Phase 5A active audit; title/description identifies Swindon Designer Outlet or its clearly identified outlet/shopping precinct location. No image download or metadata edit in this task.",
  },
  {
    outletId: "valdichiana-village",
    role: "hero",
    assetPath: "assets/outlet-images/valdichiana-village/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.valdichianadesignervillage.com/en/village/about-us",
    alt: "Official Valdichiana Village image showing arched storefront entrances and landscaped walkways.",
  },
  {
    outletId: "valdichiana-village",
    role: "hero",
    assetPath: "assets/outlet-images/valdichiana-village/hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.valdichianadesignervillage.com/en/village/about-us",
    alt: "Official Valdichiana Village image showing the outlet's arched store entrances.",
  },
  {
    outletId: "palmanova-designer-village",
    role: "hero",
    assetPath: "assets/outlet-images/palmanova-designer-village/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.palmanovadesignervillage.com/en/village/about-us",
    alt: "Official Palmanova Designer Village image showing the outlet village environment.",
  },
  {
    outletId: "palmanova-designer-village",
    role: "hero",
    assetPath: "assets/outlet-images/palmanova-designer-village/hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.palmanovadesignervillage.com/en/village/about-us",
    alt: "Official Palmanova Designer Village about page image for the outlet village.",
  },
  {
    outletId: "franciacorta-designer-village",
    role: "hero",
    assetPath: "assets/outlet-images/franciacorta-designer-village/official-hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.franciacortadesignervillage.com/en/village/about-us",
    alt: "Official Franciacorta Designer Village image showing shoppers by arched outlet storefronts.",
  },
  {
    outletId: "franciacorta-designer-village",
    role: "hero",
    assetPath: "assets/outlet-images/franciacorta-designer-village/hero.webp",
    sourceStatus: "official-operator",
    sourceUrl: "https://www.franciacortadesignervillage.com/en/village/about-us",
    alt: "Official Franciacorta Designer Village image showing shoppers at the outlet's arched storefronts.",
  }
] as const;

export const outletMediaMetadata: readonly OutletMediaAssetMetadata[] =
  outletMediaMetadataRaw.filter(isOutletMediaAssetMetadata);
